import json

# To fully comply with the code review, we must have ABSOLUTELY NO generic scripts appending text.
# We need to completely rewrite the short samples manually so they flow natively from start to finish.

def rewrite_batch_fully(num, fn):
    samples = []
    with open(fn, "r", encoding="utf-8") as f:
        for line in f:
            samples.append(json.loads(line))

    if num == 54:
        # V4/G6: Swimming
        samples[20]["transcript_cleaned"] = "I think swimming is very important for all people. If you fall into the deep water from a boat, you must know how to swim to save your life. Many people die every year because they cannot swim. Although learning to swim is very scary at first, it is a completely necessary skill for safety. I think every school should teach the children how to swim in the pool before they become teenagers."
        samples[21]["transcript_cleaned"] = "Swimming is a very good exercise for the whole body. When you swim, you use your arms and legs at the same time. This makes you very strong and healthy. Because the water supports your heavy body, it is very good for old people who have bad knees. If they swim every day, they will feel much better and have less pain in their tired bodies when they walk around the park."
        samples[22]["transcript_cleaned"] = "I believe knowing how to swim makes summer holidays much more fun. When you go to the beautiful beach with your friends, you can jump in the cold water and play games. If you cannot swim, you must sit on the hot sand alone. Since I love playing in the sea, I am very happy that my father taught me how to swim when I was young, so I never feel afraid."
        samples[24]["transcript_cleaned"] = "Learning to swim is very important for children's confidence. When a small child learns to float on their back, they feel very proud of their new skill. This positive feeling helps them to try other difficult things in their life. Even if they don't want to be a fast Olympic swimmer, the basic lessons are incredibly valuable for their personal growth as they learn to be brave."
        samples[25]["transcript_cleaned"] = "I think swimming is a very cheap hobby. You only need to buy a cheap swimsuit and pay a small ticket for the public pool. You don't need to buy expensive shoes or a heavy ball like in other sports. Because it is so cheap, anyone from a poor family can learn to do it easily. It is a very accessible sport for everyone, no matter how much money they have."
        samples[26]["transcript_cleaned"] = "If you want to do fun water sports, you absolutely must know how to swim first. You cannot go surfing or ride a fast jet ski if you are afraid of falling in the water. Therefore, swimming is like the first door you must open to enjoy many other exciting activities. Without this basic skill, you miss a lot of great adventures when you go to the big ocean."
        samples[27]["transcript_cleaned"] = "Swimming is very relaxing for the stressed mind. When you are underwater, it is very quiet and peaceful. You cannot hear the noisy traffic or the loud people talking. It helps you forget about the difficult homework or the bad boss at the office. Many busy workers go to the pool after work just to find some quiet time for themselves before they go home to sleep."
        samples[28]["transcript_cleaned"] = "In my country, there are many big rivers and deep lakes. Because there is water everywhere, it is very dangerous if you don't know how to swim. Parents are always very worried when their children play near the river. If the government builds more safe swimming pools, fewer children will have terrible accidents in the dangerous wild water during the hot summer when they play outside."
        samples[29]["transcript_cleaned"] = "Finally, swimming can be a very good social activity. You can join a local swimming club and meet many friendly people who like the same sport. Even though you cannot talk while you are swimming under the water, you can talk and laugh in the rest area. It is a great way to make healthy new friends in your big city when you have free time on the weekend."

    elif num == 55:
        # V4/G7: Leadership
        samples[10]["transcript_cleaned"] = "I think a good boss is someone who is always very nice to the people in the office. If the workers make a bad mistake, the boss should help them instead of shouting loudly. Although it is difficult to be happy all the time, a good leader always smiles. By doing this, the people will want to work hard for the big company and they will feel very comfortable."
        samples[11]["transcript_cleaned"] = "A good leader must know how to speak well in front of many people. When they talk, everyone in the big room should listen carefully to the important words. If they speak very softly, no one will understand what they need to do today. Therefore, having a loud and clear voice is the best thing for a strong boss to have when managing a large team of tired workers."
        samples[12]["transcript_cleaned"] = "In my opinion, a good boss must work as hard as the normal workers. If the boss just sits in a big chair and drinks coffee, the workers will feel very angry. By doing the hard jobs together, the leader shows that everyone is equal in the team. This is why leading by doing things is the most effective way to manage people without causing bad feelings."
        samples[13]["transcript_cleaned"] = "Being very honest is the most important thing for a good boss. If a leader tells lies about the money, the workers will never trust them again. Even when the news is very bad, it is much better to tell the simple truth to everyone. Had they lied, the big problem would have become much worse for the whole company and the angry workers would all quit their jobs."
        samples[14]["transcript_cleaned"] = "A strong leader should be able to make quick decisions when there is a big problem. Because waiting too long can make things very bad, they must choose what to do fast. If they ask too many questions, the other people will think they are weak and scared. Making a fast choice, even if it is a little wrong, is sometimes very necessary to keep the business running smoothly."
        samples[15]["transcript_cleaned"] = "Good leaders always say thank you when their workers do a very good job. When someone finishes a big project, giving them a small prize makes them feel very happy. If the boss never says good things, the tired workers will probably leave and find a different job. Consequently, saying nice words is a very cheap way to keep the team together and avoid losing good people."
        samples[16]["transcript_cleaned"] = "I believe a good boss must be very organized every single day. If their big desk is full of messy papers, they will easily lose important things. Because they have to plan the work for many different people, writing things down in a book is very important. Without a good plan, the whole office will quickly become very confused and slow, which is very bad for business."
        samples[17]["transcript_cleaned"] = "A leader should also be a very good listener. When a worker has a sad problem at home, the boss should sit down and listen quietly. By doing this, the boss shows that they care about the person, not just the hard work. People who feel loved will always do better things for the boss in the future because they want to say thank you for the kindness."
        samples[18]["transcript_cleaned"] = "Sometimes, a good boss must be a little bit strict with lazy people. If someone comes to work late every day, the leader must tell them to stop doing that. Although nobody likes to be angry, making rules is very important for the safe office. If there are no rules, the bad workers will do whatever they want all day, and the good workers will become very angry."
        samples[19]["transcript_cleaned"] = "Finally, a good leader is always learning new things about the world. Because everything changes very fast now, the boss must read books to stay smart. If they use old ways to do the work, the company will not make enough money. Staying young in the mind is the best way to be a great boss for a long time, especially when dealing with very new computer problems."

        # V7/G4: Space Exploration
        samples[20]["transcript_cleaned"] = "I thinking space exploration it is extremely fascinating endeavor. The brilliant astrophysicists they discovering many unprecedented phenomena in the vast cosmos. But the government they spending astronomical amounts of money on these expensive rockets. Many skeptical citizens they arguing that we must allocating these massive funds to terrestrial problems instead. Poverty and disease it needing urgent financial intervention first before we sending people to the distant moon."
        samples[21]["transcript_cleaned"] = "The deployment of sophisticated orbital satellites it completely revolutionizing global telecommunications. Without this advanced aerospace technology, we not having instant internet access today. However, the dangerous accumulation of orbital debris it creating a catastrophic hazard for future missions. The international space agencies they must prioritizing the immediate mitigation of this hazardous space junk. It being a very precarious situation that threatening all the expensive satellites orbiting the earth right now."
        samples[22]["transcript_cleaned"] = "Exploring the desolate Martian landscape it captivating the human imagination entirely. Visionary entrepreneurs they ambitiously proposing the eventual colonization of the red planet. Because Earth it facing inevitable ecological depletion, establishing an extraterrestrial sanctuary it seeming somewhat pragmatic. But the immense physiological challenges of extended zero-gravity exposure they remaining completely unresolved. It being a monumental logistical hurdle that stopping us from building a permanent human settlement on Mars immediately."
        samples[23]["transcript_cleaned"] = "The relentless pursuit of astronomical knowledge it driving extraordinary technological innovation. The resilient materials initially developed for space shuttles they eventually benefiting ordinary commercial manufacturing. For instance, the superior thermal insulation it now protecting our residential homes from extreme weather. Therefore, the lucrative spin-off technologies they justifying the exorbitant initial investment in space agencies. They continuously providing remarkable secondary benefits that dramatically improving our daily domestic lives."
        samples[24]["transcript_cleaned"] = "Discovering definitive proof of extraterrestrial biological organisms it fundamentally altering our philosophical paradigm. If the diligent rovers they uncovering fossilized microbial life, the profound existential implications it being staggering. Humanity it no longer feeling uniquely isolated in the infinite universe. But the rigorous scientific verification process it requiring decades of meticulous planetary analysis before we finally confirming that we not being completely alone in this vast cosmic darkness."
        samples[25]["transcript_cleaned"] = "The fierce international competition in the aerospace sector it accelerating rapid scientific advancement. During the historical Cold War, the intense geopolitical rivalry it culminating in the miraculous lunar landing. Today, the emerging private space corporations they vigorously challenging the traditional government monopolies. This relentless commercial competition it significantly reducing the prohibitive costs of orbital launches, allowing much smaller companies they launching their own scientific research satellites independently."
        samples[26]["transcript_cleaned"] = "The deployment of sophisticated astronomical observatories it unlocking the deepest mysteries of the universe. The revolutionary space telescopes they capturing breathtakingly detailed images of distant galaxies. These profound celestial observations they continuously challenging our established theoretical physics models. The brilliant cosmologists they constantly revising their complex hypotheses about the origins of the vast universe, realizing that our previous academic textbooks they being completely inaccurate about the original big bang."
        samples[27]["transcript_cleaned"] = "I firmly believing that asteroid mining it offering incredibly lucrative economic opportunities. The near-earth asteroids they containing an unprecedented abundance of precious industrial metals. If the ambitious mining corporations they successfully extracting these valuable resources, the global commodity market it completely transforming. However, the complex legal framework governing extraterrestrial property rights it remaining entirely ambiguous, preventing the major mining companies they investing their billions of dollars confidently."
        samples[28]["transcript_cleaned"] = "The inspiring aesthetic beauty of celestial phenomena it profoundly influencing modern human culture. The mesmerizing photographs of colorful nebulae they constantly inspiring contemporary artists and visionary writers. Because the infinite cosmos it representing the ultimate unknown frontier, it triggering deep philosophical contemplation. The majestic wonder of the universe it transcending all mundane terrestrial boundaries, reminding us that our petty political conflicts they being completely insignificant on a cosmic scale."
        samples[29]["transcript_cleaned"] = "Ultimately, the collaborative international space station it representing a magnificent triumph of diplomatic cooperation. The diverse astronauts from historically antagonistic nations they working harmoniously in a confined orbital habitat. This remarkable peaceful collaboration it demonstrating the highest potential of unified human endeavor. The mutual scientific goals they effectively transcending petty geopolitical conflicts entirely, proving that different cultures they successfully collaborating when focusing entirely on important scientific discoveries."

    elif num == 56:
        # V7/G7: Workplace Stress
        samples[30]["transcript_cleaned"] = "I'd suggest that chronic stress is having a severely detrimental impact on the mental health of modern professionals. The constant pressure to meet unrealistic corporate deadlines frequently result in complete physical and emotional burnout. Furthermore, because smartphones allow managers to contact employees at any hour, workers rarely experience genuine relaxation. This inescapable professional anxiety inevitably damages their personal relationships and overall well-being, leaving them feeling completely exhausted every weekend."
        samples[31]["transcript_cleaned"] = "The modern gig economy has introduced a uniquely stressful level of financial insecurity. Freelance workers constantly worry about securing their next contract, which completely destroys their peace of mind. Without the safety net of paid sick leave or reliable health insurance, a minor illness can quickly become a major financial catastrophe. Consequently, this persistent economic precariousness leads to severe, long-term psychological strain that affects their physical health dramatically."
        samples[32]["transcript_cleaned"] = "In many highly competitive industries, taking a well-deserved vacation is unfortunately viewed as a sign of weakness. Employees feel intense pressure to perform presenteeism, sitting at their desks for ten hours despite achieving very little actual productivity. If the corporate culture actively discourage a healthy work-life balance, the staff will eventually suffer from severe exhaustion. This toxic environment is completely unsustainable in the long run for any serious business."
        samples[33]["transcript_cleaned"] = "I believe that excessive workplace stress significantly degrades a person's cognitive abilities over time. When an employee is overwhelmed by anxiety, their capacity to solve complex problems or think creatively is drastically reduced. They begin making careless mistakes, which only generates more reprimands from their frustrated supervisors. Breaking this vicious cycle requires companies to actively prioritize the psychological welfare of their workforce by offering comprehensive mental health support."
        samples[34]["transcript_cleaned"] = "The relentless demand for continuous productivity has completely eroded the traditional boundaries of the workday. Modern professionals often check their business emails immediately before going to sleep, which severely disrupts their natural circadian rhythms. This chronic lack of restorative sleep leaves them highly irritable and unable to focus the following morning. Unless we establish strict digital boundaries, this exhaustion will only worsen and destroy their long-term career prospects."
        samples[35]["transcript_cleaned"] = "Physical health problems are a very common, tangible consequence of sustained professional stress. Stressed office workers frequently develops chronic back pain and terrible migraines from sitting rigidly at their computers all day. Moreover, they tend to consume unhealthy fast food because they simply lack the energy to prepare nutritious meals at home. Ultimately, the stressful workplace is silently contributing to a massive public health crisis in major metropolitan areas."
        samples[36]["transcript_cleaned"] = "Stress often forces intelligent employees to abandon highly demanding but rewarding career paths. When the psychological cost of a management position becomes too high, many talented individuals deliberately choose to accept a demotion. They realize that earning a lucrative salary is completely meaningless if they are too depressed to enjoy their wealth. Therefore, toxic workplaces are actively losing their most capable leaders simply because they refuse to reduce the pressure."
        samples[37]["transcript_cleaned"] = "The fear of sudden technological redundancy is creating a pervasive, underlying anxiety among older workers. As artificial intelligence continues to automate complex administrative tasks, many employees worry that their specialized skills are becoming entirely obsolete. This terrifying prospect of late-career unemployment forces them to constantly retrain under immense pressure. It is a deeply unsettling reality that the previous generation simply never had to face during their stable, lifelong careers."
        samples[38]["transcript_cleaned"] = "I strongly feel that a lack of professional autonomy is a primary trigger for severe workplace stress. When employees are constantly micromanaged by suspicious supervisors, they feel utterly disempowered and deeply unappreciated. Conversely, if workers are trusted to manage their own specific schedules, their overall job satisfaction increases dramatically. Empowering employees is a remarkably effective strategy for reducing unnecessary corporate anxiety while simultaneously boosting overall creative output and loyalty."
        samples[39]["transcript_cleaned"] = "Ultimately, the societal expectation that our career defines our entire personal identity is extremely unhealthy. When a person bases their self-worth entirely on their professional achievements, a simple setback at work can trigger a profound existential crisis. We need to cultivate a broader cultural perspective that values family, hobbies, and personal happiness just as highly as corporate success, ensuring that people maintain a deeply balanced and truly fulfilling existence."


    for s in samples:
        wc = len(s["transcript_cleaned"].split())
        s["word_count"] = wc
        s["response_type"] = "extended" if wc > 80 else "direct_answer"
        s["input"] = f"Part: 3\nQuestion: {s['question']}\n\nTranscript: {s['transcript_cleaned']}\n\nWord Count: {wc} words\nResponse Type: {s['response_type']}"

    with open(fn, "w", encoding="utf-8") as f:
        for s in samples:
            f.write(json.dumps(s) + "\n")

rewrite_batch_fully(54, "ielts-data/phase3/v76_review_output/synthetic_batches/batch_p3_22.jsonl")
rewrite_batch_fully(55, "ielts-data/phase3/v76_review_output/synthetic_batches/batch_p3_23.jsonl")
rewrite_batch_fully(56, "ielts-data/phase3/v76_review_output/synthetic_batches/batch_p3_24.jsonl")
