import json

OUTPUT_FILE = 'ielts-data/phase3/v76_review_output/jules1/jules1_batch04.jsonl'

samples = [
    {
        "sample_id": "syn_p2_v6_g6_291",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a goal.",
        "transcript_cleaned": "I wanted to learn to play the guitar. It was my goal last year. I bought a second-hand guitar. It was cheap. I practiced every day after work. My fingers hurt at first. I learned chords from the internet. It was difficult but fun. I can play three songs now. I played for my girlfriend. She liked it. I am proud of my progress. I want to learn more.",
        "word_count": 72,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'goal', 'second-hand', 'practiced', 'chords', 'progress'. >Band 5: 'Second-hand', 'chords'. Not Band 7: Simple vocab.",
        "grammar_reason": "[GRA6] Key evidence: 'wanted to learn', 'fingers hurt at first'. >Band 5: Past tense used correctly. Not Band 7: Short sentences.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a goal.\n\nTranscript: I wanted to learn to play the guitar. It was my goal last year. I bought a second-hand guitar. It was cheap. I practiced every day after work. My fingers hurt at first. I learned chords from the internet. It was difficult but fun. I can play three songs now. I played for my girlfriend. She liked it. I am proud of my progress. I want to learn more.\n\nWord Count: 72 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'goal', 'second-hand', 'practiced', 'chords', 'progress'. \n\n>Band 5: 'Second-hand', 'chords'.\n\nNot Band 7: Simple vocab.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'wanted to learn', 'fingers hurt at first'. \n\n>Band 5: Past tense used correctly.\n\nNot Band 7: Short sentences.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_292",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a useful object.",
        "transcript_cleaned": "I use a power bank for my phone. It is a portable charger. It is small and heavy. I carry it in my bag. My phone battery dies quickly. So I need it often. I plug my phone into it. It charges fast. It is very convenient when I travel. I do not have to find a socket. It was a gift from my brother. It is a lifesaver.",
        "word_count": 71,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'power bank', 'portable', 'charger', 'battery', 'dies', 'plug', 'charges', 'convenient', 'socket', 'lifesaver'. >Band 5: 'Portable', 'lifesaver'. Not Band 7: Good range.",
        "grammar_reason": "[GRA6] Key evidence: 'convenient when I travel', 'do not have to find'. >Band 5: Time clauses and modals correct. Not Band 7: Simple structure.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a useful object.\n\nTranscript: I use a power bank for my phone. It is a portable charger. It is small and heavy. I carry it in my bag. My phone battery dies quickly. So I need it often. I plug my phone into it. It charges fast. It is very convenient when I travel. I do not have to find a socket. It was a gift from my brother. It is a lifesaver.\n\nWord Count: 71 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'power bank', 'portable', 'charger', 'battery', 'dies', 'plug', 'charges', 'convenient', 'socket', 'lifesaver'. \n\n>Band 5: 'Portable', 'lifesaver'.\n\nNot Band 7: Good range.\n\n**Idiom present:** Yes\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'convenient when I travel', 'do not have to find'. \n\n>Band 5: Time clauses and modals correct.\n\nNot Band 7: Simple structure.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_293",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a busy time.",
        "transcript_cleaned": "I was busy last Christmas. My family came to visit. I had to cook for ten people. I went shopping for food. The supermarket was crowded. It took a long time. I cooked a turkey and vegetables. I was in the kitchen all day. I was tired but happy. Everyone enjoyed the meal. We opened presents afterwards. It was a festive day. I slept well that night.",
        "word_count": 68,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'crowded', 'turkey', 'vegetables', 'enjoyed', 'presents', 'festive'. >Band 5: 'Festive', 'crowded'. Not Band 7: Standard holiday vocab.",
        "grammar_reason": "[GRA6] Key evidence: 'had to cook', 'went shopping'. >Band 5: Past tense and modals correct. Not Band 7: Very short sentences.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a busy time.\n\nTranscript: I was busy last Christmas. My family came to visit. I had to cook for ten people. I went shopping for food. The supermarket was crowded. It took a long time. I cooked a turkey and vegetables. I was in the kitchen all day. I was tired but happy. Everyone enjoyed the meal. We opened presents afterwards. It was a festive day. I slept well that night.\n\nWord Count: 68 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'crowded', 'turkey', 'vegetables', 'enjoyed', 'presents', 'festive'. \n\n>Band 5: 'Festive', 'crowded'.\n\nNot Band 7: Standard holiday vocab.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'had to cook', 'went shopping'. \n\n>Band 5: Past tense and modals correct.\n\nNot Band 7: Very short sentences.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_294",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a competition.",
        "transcript_cleaned": "I watched a singing competition on TV. It is called American Idol. Many people auditioned. Some were good, some were bad. The judges were funny. I liked one singer. She had a powerful voice. She sang a sad song. I voted for her. She reached the final. It was suspenseful. She did not win, but she became famous. I enjoy watching talent shows. They are entertaining.",
        "word_count": 66,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'competition', 'auditioned', 'judges', 'powerful voice', 'voted', 'final', 'suspenseful', 'famous', 'talent shows', 'entertaining'. >Band 5: 'Auditioned', 'suspenseful'. Not Band 7: Good range.",
        "grammar_reason": "[GRA6] Key evidence: 'She did not win, but', 'people auditioned'. >Band 5: Compound sentences and past tense correct. Not Band 7: Simple structure.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a competition.\n\nTranscript: I watched a singing competition on TV. It is called American Idol. Many people auditioned. Some were good, some were bad. The judges were funny. I liked one singer. She had a powerful voice. She sang a sad song. I voted for her. She reached the final. It was suspenseful. She did not win, but she became famous. I enjoy watching talent shows. They are entertaining.\n\nWord Count: 66 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'competition', 'auditioned', 'judges', 'powerful voice', 'voted', 'final', 'suspenseful', 'famous', 'talent shows', 'entertaining'. \n\n>Band 5: 'Auditioned', 'suspenseful'.\n\nNot Band 7: Good range.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'She did not win, but', 'people auditioned'. \n\n>Band 5: Compound sentences and past tense correct.\n\nNot Band 7: Simple structure.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_295",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a friend.",
        "transcript_cleaned": "My friend David is very adventurous. He likes outdoor activities. We go hiking together. He is also generous. He often pays for lunch. He works as a teacher. He is patient with students. We met at university. We have been friends for ten years. I can trust him with my secrets. He gives good advice. He is like a brother to me. I am lucky.",
        "word_count": 66,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'adventurous', 'outdoor activities', 'generous', 'patient', 'trust', 'secrets', 'advice'. >Band 5: 'Adventurous', 'generous'. Not Band 7: Standard descriptions.",
        "grammar_reason": "[GRA6] Key evidence: 'have been friends', 'He works as'. >Band 5: Present perfect and simple tenses correct. Not Band 7: Very short sentences.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a friend.\n\nTranscript: My friend David is very adventurous. He likes outdoor activities. We go hiking together. He is also generous. He often pays for lunch. He works as a teacher. He is patient with students. We met at university. We have been friends for ten years. I can trust him with my secrets. He gives good advice. He is like a brother to me. I am lucky.\n\nWord Count: 66 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'adventurous', 'outdoor activities', 'generous', 'patient', 'trust', 'secrets', 'advice'. \n\n>Band 5: 'Adventurous', 'generous'.\n\nNot Band 7: Standard descriptions.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'have been friends', 'He works as'. \n\n>Band 5: Present perfect and simple tenses correct.\n\nNot Band 7: Very short sentences.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_296",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a place.",
        "transcript_cleaned": "I visited a large shopping mall in Dubai. It was huge. It had many shops and restaurants. There was an aquarium inside. I saw sharks and fish. It was amazing. I bought some clothes. They were expensive. The mall was crowded with tourists. It was air-conditioned, which was good because it was hot outside. I spent the whole day there. It was a shopper's paradise.",
        "word_count": 66,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'shopping mall', 'aquarium', 'sharks', 'expensive', 'crowded', 'tourists', 'air-conditioned', 'shopper's paradise'. >Band 5: 'Shopper's paradise', 'aquarium'. Not Band 7: Good range.",
        "grammar_reason": "[GRA6] Key evidence: 'which was good', 'It was huge'. >Band 5: Relative clause and simple sentences correct. Not Band 7: Repetitive structure.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a place.\n\nTranscript: I visited a large shopping mall in Dubai. It was huge. It had many shops and restaurants. There was an aquarium inside. I saw sharks and fish. It was amazing. I bought some clothes. They were expensive. The mall was crowded with tourists. It was air-conditioned, which was good because it was hot outside. I spent the whole day there. It was a shopper's paradise.\n\nWord Count: 66 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'shopping mall', 'aquarium', 'sharks', 'expensive', 'crowded', 'tourists', 'air-conditioned', 'shopper's paradise'. \n\n>Band 5: 'Shopper's paradise', 'aquarium'.\n\nNot Band 7: Good range.\n\n**Idiom present:** Yes\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'which was good', 'It was huge'. \n\n>Band 5: Relative clause and simple sentences correct.\n\nNot Band 7: Repetitive structure.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_297",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a historical figure.",
        "transcript_cleaned": "I admire Thomas Edison. He was an inventor. He invented the light bulb. He was American. He worked very hard. He failed many times, but he kept trying. He was persistent. He also invented the phonograph. His inventions changed the world. He had many patents. I think he was a genius. He showed us that failure is part of success. He is an inspiration.",
        "word_count": 65,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'inventor', 'invented', 'light bulb', 'failed', 'persistent', 'phonograph', 'inventions', 'patents', 'genius', 'inspiration'. >Band 5: 'Persistent', 'patents'. Not Band 7: Good range.",
        "grammar_reason": "[GRA6] Key evidence: 'failed... but he kept', 'showed us that'. >Band 5: Compound and complex sentences correct. Not Band 7: Short sentences.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a historical figure.\n\nTranscript: I admire Thomas Edison. He was an inventor. He invented the light bulb. He was American. He worked very hard. He failed many times, but he kept trying. He was persistent. He also invented the phonograph. His inventions changed the world. He had many patents. I think he was a genius. He showed us that failure is part of success. He is an inspiration.\n\nWord Count: 65 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'inventor', 'invented', 'light bulb', 'failed', 'persistent', 'phonograph', 'inventions', 'patents', 'genius', 'inspiration'. \n\n>Band 5: 'Persistent', 'patents'.\n\nNot Band 7: Good range.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'failed... but he kept', 'showed us that'. \n\n>Band 5: Compound and complex sentences correct.\n\nNot Band 7: Short sentences.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_298",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a difficult task.",
        "transcript_cleaned": "I had to study for a math exam. It was very difficult. I am not good at numbers. I had to learn many formulas. I studied for a week. I asked my brother for help. He explained the problems to me. I did practice tests. I was stressed. On the exam day, I was nervous. But I passed the exam. I was relieved. Hard work pays off.",
        "word_count": 68,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'formulas', 'practice tests', 'stressed', 'nervous', 'passed', 'relieved', 'hard work', 'pays off'. >Band 5: 'Formulas', 'pays off'. Not Band 7: Idiom used correctly but isolated.",
        "grammar_reason": "[GRA6] Key evidence: 'had to learn', 'explained... to me'. >Band 5: Modals and prepositions correct. Not Band 7: Very short sentences.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a difficult task.\n\nTranscript: I had to study for a math exam. It was very difficult. I am not good at numbers. I had to learn many formulas. I studied for a week. I asked my brother for help. He explained the problems to me. I did practice tests. I was stressed. On the exam day, I was nervous. But I passed the exam. I was relieved. Hard work pays off.\n\nWord Count: 68 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'formulas', 'practice tests', 'stressed', 'nervous', 'passed', 'relieved', 'hard work', 'pays off'. \n\n>Band 5: 'Formulas', 'pays off'.\n\nNot Band 7: Idiom used correctly but isolated.\n\n**Idiom present:** Yes\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'had to learn', 'explained... to me'. \n\n>Band 5: Modals and prepositions correct.\n\nNot Band 7: Very short sentences.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_299",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a useful skill.",
        "transcript_cleaned": "I learned how to swim. It is a life skill. I took lessons at a pool. My instructor was good. I learned freestyle and backstroke. I was afraid of deep water. But I overcame my fear. Now I can swim laps. It is good for my health. It builds muscles. I go swimming in the summer. It is refreshing. I think everyone should learn to swim.",
        "word_count": 67,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'life skill', 'instructor', 'freestyle', 'backstroke', 'overcame', 'fear', 'laps', 'muscles', 'refreshing'. >Band 5: 'Overcame fear', 'refreshing'. Not Band 7: Good range.",
        "grammar_reason": "[GRA6] Key evidence: 'how to swim', 'should learn'. >Band 5: Infinitives and modals correct. Not Band 7: Short sentences.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a useful skill.\n\nTranscript: I learned how to swim. It is a life skill. I took lessons at a pool. My instructor was good. I learned freestyle and backstroke. I was afraid of deep water. But I overcame my fear. Now I can swim laps. It is good for my health. It builds muscles. I go swimming in the summer. It is refreshing. I think everyone should learn to swim.\n\nWord Count: 67 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'life skill', 'instructor', 'freestyle', 'backstroke', 'overcame', 'fear', 'laps', 'muscles', 'refreshing'. \n\n>Band 5: 'Overcame fear', 'refreshing'.\n\nNot Band 7: Good range.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'how to swim', 'should learn'. \n\n>Band 5: Infinitives and modals correct.\n\nNot Band 7: Short sentences.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_300",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a party.",
        "transcript_cleaned": "I went to a New Year's Eve party. It was at a hotel. There were many people. We wore formal clothes. The decorations were silver and gold. There was a band playing music. We danced all night. At midnight, we counted down. We watched fireworks. It was spectacular. We drank champagne. It was a celebration of the new year. I had a wonderful time with my friends.",
        "word_count": 68,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'New Year's Eve', 'formal', 'decorations', 'band', 'counted down', 'fireworks', 'spectacular', 'champagne', 'celebration'. >Band 5: 'Spectacular', 'celebration'. Not Band 7: Standard party vocab.",
        "grammar_reason": "[GRA6] Key evidence: 'There were', 'band playing'. >Band 5: Existential there and participle phrase correct. Not Band 7: Simple structure.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a party.\n\nTranscript: I went to a New Year's Eve party. It was at a hotel. There were many people. We wore formal clothes. The decorations were silver and gold. There was a band playing music. We danced all night. At midnight, we counted down. We watched fireworks. It was spectacular. We drank champagne. It was a celebration of the new year. I had a wonderful time with my friends.\n\nWord Count: 68 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'New Year's Eve', 'formal', 'decorations', 'band', 'counted down', 'fireworks', 'spectacular', 'champagne', 'celebration'. \n\n>Band 5: 'Spectacular', 'celebration'.\n\nNot Band 7: Standard party vocab.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'There were', 'band playing'. \n\n>Band 5: Existential there and participle phrase correct.\n\nNot Band 7: Simple structure.\n\n**Micro flaws identified:**\n- none significant"
    }
]

with open(OUTPUT_FILE, 'a') as f:
    for sample in samples:
        json.dump(sample, f)
        f.write('\n')
