import json

OUTPUT_FILE = 'ielts-data/phase3/v76_review_output/jules1/jules1_batch04.jsonl'

samples = [
    {
        "sample_id": "syn_p2_v6_g6_276",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a historical figure.",
        "transcript_cleaned": "I admire Martin Luther King Jr. He was a civil rights leader. He fought against racism. He gave a famous speech called \"I Have a Dream\". It was very powerful. He inspired millions of people. He advocated for non-violence. He was awarded the Nobel Peace Prize. Sadly, he was assassinated. He is a legend. His message of equality is still relevant today. I learned about him in history class.",
        "word_count": 70,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'civil rights', 'racism', 'inspired', 'advocated', 'non-violence', 'awarded', 'assassinated', 'legend', 'equality', 'relevant'. >Band 5: 'Advocated', 'relevant'. Not Band 7: Standard history vocab.",
        "grammar_reason": "[GRA6] Key evidence: 'called I Have a Dream', 'message... is still relevant'. >Band 5: Participle phrases and present simple correct. Not Band 7: Short sentences.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a historical figure.\n\nTranscript: I admire Martin Luther King Jr. He was a civil rights leader. He fought against racism. He gave a famous speech called \"I Have a Dream\". It was very powerful. He inspired millions of people. He advocated for non-violence. He was awarded the Nobel Peace Prize. Sadly, he was assassinated. He is a legend. His message of equality is still relevant today. I learned about him in history class.\n\nWord Count: 70 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'civil rights', 'racism', 'inspired', 'advocated', 'non-violence', 'awarded', 'assassinated', 'legend', 'equality', 'relevant'. \n\n>Band 5: 'Advocated', 'relevant'.\n\nNot Band 7: Standard history vocab.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'called I Have a Dream', 'message... is still relevant'. \n\n>Band 5: Participle phrases and present simple correct.\n\nNot Band 7: Short sentences.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_277",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a piece of news.",
        "transcript_cleaned": "I read about a new technology. It is about self-driving cars. Companies like Tesla are developing them. They use sensors and cameras. They can drive without a human. It sounds futuristic. It could reduce accidents. However, some people are skeptical. They worry about safety. I think it is an exciting innovation. It will change transportation. I hope to ride in one someday. It would be a unique experience.",
        "word_count": 68,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'technology', 'self-driving', 'developing', 'sensors', 'futuristic', 'reduce', 'skeptical', 'safety', 'innovation', 'transportation', 'unique'. >Band 5: 'Skeptical', 'futuristic'. Not Band 7: Good range.",
        "grammar_reason": "[GRA6] Key evidence: 'Companies like Tesla', 'It could reduce', 'It would be'. >Band 5: Modals of possibility correct. Not Band 7: Simple structure.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a piece of news.\n\nTranscript: I read about a new technology. It is about self-driving cars. Companies like Tesla are developing them. They use sensors and cameras. They can drive without a human. It sounds futuristic. It could reduce accidents. However, some people are skeptical. They worry about safety. I think it is an exciting innovation. It will change transportation. I hope to ride in one someday. It would be a unique experience.\n\nWord Count: 68 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'technology', 'self-driving', 'developing', 'sensors', 'futuristic', 'reduce', 'skeptical', 'safety', 'innovation', 'transportation', 'unique'. \n\n>Band 5: 'Skeptical', 'futuristic'.\n\nNot Band 7: Good range.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'Companies like Tesla', 'It could reduce', 'It would be'. \n\n>Band 5: Modals of possibility correct.\n\nNot Band 7: Simple structure.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_278",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a useful object.",
        "transcript_cleaned": "I use a pair of headphones. They are noise-cancelling. I bought them online. They block out background noise. I use them when I study or travel. The sound quality is excellent. They are wireless, so they connect via Bluetooth. They are comfortable to wear. The battery lasts a long time. I listen to music and podcasts. They help me focus. They are an indispensable gadget for me.",
        "word_count": 68,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'headphones', 'noise-cancelling', 'block out', 'background noise', 'quality', 'wireless', 'Bluetooth', 'podcasts', 'focus', 'indispensable', 'gadget'. >Band 5: 'Indispensable', 'block out'. Not Band 7: Standard tech vocab.",
        "grammar_reason": "[GRA6] Key evidence: 'when I study', 'so they connect'. >Band 5: Connectors and time clauses used correctly. Not Band 7: Short sentences.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a useful object.\n\nTranscript: I use a pair of headphones. They are noise-cancelling. I bought them online. They block out background noise. I use them when I study or travel. The sound quality is excellent. They are wireless, so they connect via Bluetooth. They are comfortable to wear. The battery lasts a long time. I listen to music and podcasts. They help me focus. They are an indispensable gadget for me.\n\nWord Count: 68 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'headphones', 'noise-cancelling', 'block out', 'background noise', 'quality', 'wireless', 'Bluetooth', 'podcasts', 'focus', 'indispensable', 'gadget'. \n\n>Band 5: 'Indispensable', 'block out'.\n\nNot Band 7: Standard tech vocab.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'when I study', 'so they connect'. \n\n>Band 5: Connectors and time clauses used correctly.\n\nNot Band 7: Short sentences.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_279",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a busy time.",
        "transcript_cleaned": "I was busy during my final exams. It was a stressful period. I had to revise for five subjects. I made a study schedule. I woke up early and slept late. I drank coffee to stay awake. I felt pressure from my parents. They wanted me to get high marks. I did not have time for hobbies. After the exams, I was exhausted. But I passed with flying colors.",
        "word_count": 71,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'final exams', 'stressful', 'period', 'revise', 'schedule', 'pressure', 'hobbies', 'exhausted', 'passed', 'flying colors'. >Band 5: 'Revise', 'flying colors'. Not Band 7: Idiom used correctly but isolated.",
        "grammar_reason": "[GRA6] Key evidence: 'to stay awake', 'wanted me to get'. >Band 5: Infinitive of purpose and verb patterns correct. Not Band 7: Simple structure.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a busy time.\n\nTranscript: I was busy during my final exams. It was a stressful period. I had to revise for five subjects. I made a study schedule. I woke up early and slept late. I drank coffee to stay awake. I felt pressure from my parents. They wanted me to get high marks. I did not have time for hobbies. After the exams, I was exhausted. But I passed with flying colors.\n\nWord Count: 71 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'final exams', 'stressful', 'period', 'revise', 'schedule', 'pressure', 'hobbies', 'exhausted', 'passed', 'flying colors'. \n\n>Band 5: 'Revise', 'flying colors'.\n\nNot Band 7: Idiom used correctly but isolated.\n\n**Idiom present:** Yes\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'to stay awake', 'wanted me to get'. \n\n>Band 5: Infinitive of purpose and verb patterns correct.\n\nNot Band 7: Simple structure.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_280",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a party.",
        "transcript_cleaned": "I went to a housewarming party. My friend moved into a new apartment. It was a casual gathering. We brought gifts for his home. The apartment was modern and spacious. He gave us a tour. We ate snacks and chatted. The atmosphere was cozy. We played some board games. It was a good way to relax. I met some interesting people there. We stayed until midnight. It was enjoyable.",
        "word_count": 69,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'housewarming', 'casual', 'gathering', 'spacious', 'tour', 'snacks', 'atmosphere', 'cozy', 'board games', 'relax', 'enjoyable'. >Band 5: 'Housewarming', 'spacious'. Not Band 7: Good range.",
        "grammar_reason": "[GRA6] Key evidence: 'moved into', 'way to relax'. >Band 5: Phrasal verbs and infinitives correct. Not Band 7: Simple sentences.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a party.\n\nTranscript: I went to a housewarming party. My friend moved into a new apartment. It was a casual gathering. We brought gifts for his home. The apartment was modern and spacious. He gave us a tour. We ate snacks and chatted. The atmosphere was cozy. We played some board games. It was a good way to relax. I met some interesting people there. We stayed until midnight. It was enjoyable.\n\nWord Count: 69 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'housewarming', 'casual', 'gathering', 'spacious', 'tour', 'snacks', 'atmosphere', 'cozy', 'board games', 'relax', 'enjoyable'. \n\n>Band 5: 'Housewarming', 'spacious'.\n\nNot Band 7: Good range.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'moved into', 'way to relax'. \n\n>Band 5: Phrasal verbs and infinitives correct.\n\nNot Band 7: Simple sentences.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_281",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a difficult decision.",
        "transcript_cleaned": "I had to decide whether to quit my piano lessons. I had played for five years. I was quite good. However, I had too much homework from school. I felt stressed. I talked to my teacher. She understood my situation. It was a tough call. I didn't want to give up. Finally, I stopped the lessons. I miss playing, but I have more time for study now. It was necessary.",
        "word_count": 71,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'quit', 'homework', 'stressed', 'situation', 'tough call', 'give up', 'necessary'. >Band 5: 'Tough call', 'situation'. Not Band 7: Idiom used correctly.",
        "grammar_reason": "[GRA6] Key evidence: 'whether to quit', 'had played', 'didn't want to'. >Band 5: Past perfect and infinitives correct. Not Band 7: Short sentences.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a difficult decision.\n\nTranscript: I had to decide whether to quit my piano lessons. I had played for five years. I was quite good. However, I had too much homework from school. I felt stressed. I talked to my teacher. She understood my situation. It was a tough call. I didn't want to give up. Finally, I stopped the lessons. I miss playing, but I have more time for study now. It was necessary.\n\nWord Count: 71 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'quit', 'homework', 'stressed', 'situation', 'tough call', 'give up', 'necessary'. \n\n>Band 5: 'Tough call', 'situation'.\n\nNot Band 7: Idiom used correctly.\n\n**Idiom present:** Yes\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'whether to quit', 'had played', 'didn't want to'. \n\n>Band 5: Past perfect and infinitives correct.\n\nNot Band 7: Short sentences.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_282",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a historical place.",
        "transcript_cleaned": "I visited the Acropolis in Athens. It is an ancient citadel. It sits on a rocky hill. The most famous building is the Parthenon. It was built for the goddess Athena. The columns are huge. It is in ruins, but still majestic. I saw many tourists there. I hired a guide to explain the history. It was fascinating to learn about Greek civilization. The view of the city was spectacular.",
        "word_count": 71,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'ancient', 'citadel', 'rocky', 'Parthenon', 'goddess', 'columns', 'ruins', 'majestic', 'civilization', 'spectacular'. >Band 5: 'Citadel', 'civilization'. Not Band 7: Good range.",
        "grammar_reason": "[GRA6] Key evidence: 'most famous building', 'It was built', 'to learn about'. >Band 5: Passive voice and superlatives correct. Not Band 7: Simple structure.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a historical place.\n\nTranscript: I visited the Acropolis in Athens. It is an ancient citadel. It sits on a rocky hill. The most famous building is the Parthenon. It was built for the goddess Athena. The columns are huge. It is in ruins, but still majestic. I saw many tourists there. I hired a guide to explain the history. It was fascinating to learn about Greek civilization. The view of the city was spectacular.\n\nWord Count: 71 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'ancient', 'citadel', 'rocky', 'Parthenon', 'goddess', 'columns', 'ruins', 'majestic', 'civilization', 'spectacular'. \n\n>Band 5: 'Citadel', 'civilization'.\n\nNot Band 7: Good range.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'most famous building', 'It was built', 'to learn about'. \n\n>Band 5: Passive voice and superlatives correct.\n\nNot Band 7: Simple structure.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_283",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a game.",
        "transcript_cleaned": "I play Scrabble with my family. It is a word game. We play on a board. You get tiles with letters. You have to make words. Each letter has points. The goal is to get the highest score. It is educational. I learn new vocabulary. It is competitive but friendly. Sometimes we argue about spelling. We use a dictionary to check. It is a great way to bond.",
        "word_count": 69,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'word game', 'tiles', 'points', 'goal', 'score', 'educational', 'vocabulary', 'competitive', 'spelling', 'dictionary', 'bond'. >Band 5: 'Educational', 'bond'. Not Band 7: Good range.",
        "grammar_reason": "[GRA6] Key evidence: 'have to make', 'goal is to get', 'use... to check'. >Band 5: Infinitives and modals correct. Not Band 7: Short sentences.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a game.\n\nTranscript: I play Scrabble with my family. It is a word game. We play on a board. You get tiles with letters. You have to make words. Each letter has points. The goal is to get the highest score. It is educational. I learn new vocabulary. It is competitive but friendly. Sometimes we argue about spelling. We use a dictionary to check. It is a great way to bond.\n\nWord Count: 69 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'word game', 'tiles', 'points', 'goal', 'score', 'educational', 'vocabulary', 'competitive', 'spelling', 'dictionary', 'bond'. \n\n>Band 5: 'Educational', 'bond'.\n\nNot Band 7: Good range.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'have to make', 'goal is to get', 'use... to check'. \n\n>Band 5: Infinitives and modals correct.\n\nNot Band 7: Short sentences.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_284",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a movie character.",
        "transcript_cleaned": "I like the Joker from the Batman movies. He is a villain. He wears makeup and a purple suit. He is very intelligent but insane. He creates chaos in Gotham City. He fights Batman. I like him because he is unpredictable. His laugh is scary. Heath Ledger played him well. He won an award. The character is iconic. He represents anarchy. It is a memorable performance.",
        "word_count": 66,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'villain', 'makeup', 'insane', 'chaos', 'unpredictable', 'scary', 'award', 'iconic', 'represents', 'anarchy', 'memorable', 'performance'. >Band 5: 'Anarchy', 'iconic'. Not Band 7: Good range.",
        "grammar_reason": "[GRA6] Key evidence: 'intelligent but insane', 'because he is unpredictable'. >Band 5: Compound and complex sentences correct. Not Band 7: Simple structure.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a movie character.\n\nTranscript: I like the Joker from the Batman movies. He is a villain. He wears makeup and a purple suit. He is very intelligent but insane. He creates chaos in Gotham City. He fights Batman. I like him because he is unpredictable. His laugh is scary. Heath Ledger played him well. He won an award. The character is iconic. He represents anarchy. It is a memorable performance.\n\nWord Count: 66 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'villain', 'makeup', 'insane', 'chaos', 'unpredictable', 'scary', 'award', 'iconic', 'represents', 'anarchy', 'memorable', 'performance'. \n\n>Band 5: 'Anarchy', 'iconic'.\n\nNot Band 7: Good range.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'intelligent but insane', 'because he is unpredictable'. \n\n>Band 5: Compound and complex sentences correct.\n\nNot Band 7: Simple structure.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_285",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a difficult journey.",
        "transcript_cleaned": "I went on a road trip to the desert. It was a long drive. The weather was extremely hot. The air conditioning in the car broke. We were sweating. Then we got a flat tire. We had to change it on the side of the road. It was dangerous. We ran out of water. We were thirsty. When we reached the hotel, we were relieved. It was a disastrous journey.",
        "word_count": 71,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'road trip', 'desert', 'extremely', 'air conditioning', 'sweating', 'flat tire', 'thirsty', 'relieved', 'disastrous'. >Band 5: 'Disastrous', 'relieved'. Not Band 7: Standard vocab.",
        "grammar_reason": "[GRA6] Key evidence: 'had to change', 'When we reached... we were'. >Band 5: Time clauses and modals correct. Not Band 7: Short sentences.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a difficult journey.\n\nTranscript: I went on a road trip to the desert. It was a long drive. The weather was extremely hot. The air conditioning in the car broke. We were sweating. Then we got a flat tire. We had to change it on the side of the road. It was dangerous. We ran out of water. We were thirsty. When we reached the hotel, we were relieved. It was a disastrous journey.\n\nWord Count: 71 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'road trip', 'desert', 'extremely', 'air conditioning', 'sweating', 'flat tire', 'thirsty', 'relieved', 'disastrous'. \n\n>Band 5: 'Disastrous', 'relieved'.\n\nNot Band 7: Standard vocab.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'had to change', 'When we reached... we were'. \n\n>Band 5: Time clauses and modals correct.\n\nNot Band 7: Short sentences.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_286",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a useful skill.",
        "transcript_cleaned": "I learned basic carpentry. I can make simple furniture. I learned it from my father. He has a workshop. I use tools like a hammer and saw. It requires precision. I made a bookshelf for my room. It is sturdy. I like working with wood. It smells good. It is a practical skill. If something breaks, I can fix it. I feel independent. I want to make a table next.",
        "word_count": 70,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'carpentry', 'furniture', 'workshop', 'hammer', 'saw', 'precision', 'sturdy', 'practical', 'fix', 'independent'. >Band 5: 'Precision', 'sturdy'. Not Band 7: Good range.",
        "grammar_reason": "[GRA6] Key evidence: 'If something breaks, I can', 'like working with'. >Band 5: Conditionals and gerunds correct. Not Band 7: Simple structure.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a useful skill.\n\nTranscript: I learned basic carpentry. I can make simple furniture. I learned it from my father. He has a workshop. I use tools like a hammer and saw. It requires precision. I made a bookshelf for my room. It is sturdy. I like working with wood. It smells good. It is a practical skill. If something breaks, I can fix it. I feel independent. I want to make a table next.\n\nWord Count: 70 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'carpentry', 'furniture', 'workshop', 'hammer', 'saw', 'precision', 'sturdy', 'practical', 'fix', 'independent'. \n\n>Band 5: 'Precision', 'sturdy'.\n\nNot Band 7: Good range.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'If something breaks, I can', 'like working with'. \n\n>Band 5: Conditionals and gerunds correct.\n\nNot Band 7: Simple structure.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_287",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a place.",
        "transcript_cleaned": "I went to a market in Marrakech. It is a bustling place. There are many stalls. They sell spices and carpets. The colors are vibrant. The smell is strong. It is very crowded. People are shouting. I bargained for a scarf. It was cheap. I drank mint tea. It was refreshing. I felt like I was in a movie. It is an exotic location. I loved the energy there.",
        "word_count": 69,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'bustling', 'stalls', 'spices', 'carpets', 'vibrant', 'bargained', 'refreshing', 'exotic', 'location', 'energy'. >Band 5: 'Bustling', 'exotic'. Not Band 7: Good range.",
        "grammar_reason": "[GRA6] Key evidence: 'felt like I was', 'There are many'. >Band 5: Complex sentences used correctly. Not Band 7: Short sentences.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a place.\n\nTranscript: I went to a market in Marrakech. It is a bustling place. There are many stalls. They sell spices and carpets. The colors are vibrant. The smell is strong. It is very crowded. People are shouting. I bargained for a scarf. It was cheap. I drank mint tea. It was refreshing. I felt like I was in a movie. It is an exotic location. I loved the energy there.\n\nWord Count: 69 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'bustling', 'stalls', 'spices', 'carpets', 'vibrant', 'bargained', 'refreshing', 'exotic', 'location', 'energy'. \n\n>Band 5: 'Bustling', 'exotic'.\n\nNot Band 7: Good range.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'felt like I was', 'There are many'. \n\n>Band 5: Complex sentences used correctly.\n\nNot Band 7: Short sentences.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_288",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a piece of clothes.",
        "transcript_cleaned": "I wear a uniform to work. It is a blue shirt and black trousers. It is formal wear. It makes me look professional. I have to iron it every day. I must keep it clean. It has the company logo on it. I do not like it very much. It is boring. But it saves time in the morning. I do not need to choose what to wear. It is practical.",
        "word_count": 72,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'uniform', 'trousers', 'formal wear', 'professional', 'iron', 'logo', 'boring', 'saves time', 'practical'. >Band 5: 'Formal wear', 'practical'. Not Band 7: Standard vocab.",
        "grammar_reason": "[GRA6] Key evidence: 'makes me look', 'do not need to choose'. >Band 5: Causative and infinitive structures correct. Not Band 7: Simple sentences.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a piece of clothes.\n\nTranscript: I wear a uniform to work. It is a blue shirt and black trousers. It is formal wear. It makes me look professional. I have to iron it every day. I must keep it clean. It has the company logo on it. I do not like it very much. It is boring. But it saves time in the morning. I do not need to choose what to wear. It is practical.\n\nWord Count: 72 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'uniform', 'trousers', 'formal wear', 'professional', 'iron', 'logo', 'boring', 'saves time', 'practical'. \n\n>Band 5: 'Formal wear', 'practical'.\n\nNot Band 7: Standard vocab.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'makes me look', 'do not need to choose'. \n\n>Band 5: Causative and infinitive structures correct.\n\nNot Band 7: Simple sentences.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_289",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a gift.",
        "transcript_cleaned": "I received a painting from my friend. She is an artist. She painted a landscape for me. It shows a forest in autumn. The colors are warm. Orange and yellow. It is very detailed. I hung it in my living room. It brightens the room. I was touched by her gesture. It is a unique gift. No one else has it. I value it more than expensive things. It is meaningful.",
        "word_count": 71,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'painting', 'artist', 'landscape', 'detailed', 'hung', 'brightens', 'touched', 'gesture', 'unique', 'value', 'meaningful'. >Band 5: 'Gesture', 'brightens'. Not Band 7: Good range.",
        "grammar_reason": "[GRA6] Key evidence: 'more than expensive things', 'touched by'. >Band 5: Comparative and passive phrases correct. Not Band 7: Short sentences.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a gift.\n\nTranscript: I received a painting from my friend. She is an artist. She painted a landscape for me. It shows a forest in autumn. The colors are warm. Orange and yellow. It is very detailed. I hung it in my living room. It brightens the room. I was touched by her gesture. It is a unique gift. No one else has it. I value it more than expensive things. It is meaningful.\n\nWord Count: 71 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'painting', 'artist', 'landscape', 'detailed', 'hung', 'brightens', 'touched', 'gesture', 'unique', 'value', 'meaningful'. \n\n>Band 5: 'Gesture', 'brightens'.\n\nNot Band 7: Good range.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'more than expensive things', 'touched by'. \n\n>Band 5: Comparative and passive phrases correct.\n\nNot Band 7: Short sentences.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_290",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a historical figure.",
        "transcript_cleaned": "I admire Marie Curie. She was a scientist. She discovered radium. She was the first woman to win a Nobel Prize. She worked very hard. She faced discrimination because she was a woman. But she did not stop. She contributed to medicine. Her work helps cure cancer. She is an inspiration. She showed that women can be great scientists. She died for her work. She is a hero.",
        "word_count": 67,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'scientist', 'discovered', 'radium', 'discrimination', 'contributed', 'medicine', 'cure', 'inspiration', 'hero'. >Band 5: 'Discrimination', 'contributed'. Not Band 7: Standard vocab.",
        "grammar_reason": "[GRA6] Key evidence: 'first woman to win', 'because she was'. >Band 5: Infinitive phrases and causal clauses correct. Not Band 7: Very short sentences.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a historical figure.\n\nTranscript: I admire Marie Curie. She was a scientist. She discovered radium. She was the first woman to win a Nobel Prize. She worked very hard. She faced discrimination because she was a woman. But she did not stop. She contributed to medicine. Her work helps cure cancer. She is an inspiration. She showed that women can be great scientists. She died for her work. She is a hero.\n\nWord Count: 67 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'scientist', 'discovered', 'radium', 'discrimination', 'contributed', 'medicine', 'cure', 'inspiration', 'hero'. \n\n>Band 5: 'Discrimination', 'contributed'.\n\nNot Band 7: Standard vocab.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'first woman to win', 'because she was'. \n\n>Band 5: Infinitive phrases and causal clauses correct.\n\nNot Band 7: Very short sentences.\n\n**Micro flaws identified:**\n- none significant"
    }
]

with open(OUTPUT_FILE, 'a') as f:
    for sample in samples:
        json.dump(sample, f)
        f.write('\n')
