import json
import os

OUTPUT_FILE = 'ielts-data/phase3/v76_review_output/jules1/jules1_batch01.jsonl'

samples = [
    {
        "sample_id": "syn_p2_v4_g4_001",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a family member you spend a lot of time with.",
        "transcript_cleaned": "I want talk about my grandmother. She is very old, maybe eighty years. She live in my house with my family. I like her very much because she is nice. Every day, she cook food for me. The food is very good. We talk about many thing. She tell me story about old time. I listen to her. Sometimes she is tired, so she sleep. I help her do things in house. She is short and has white hair. Her face is kind. I think she is important person in family. We go to park together on Sunday. I am happy when I see her.",
        "word_count": 96,
        "response_type": "long_turn",
        "micro_flaws": [
            "missing preposition: 'want talk' -> 'want to talk'",
            "subject-verb agreement: 'She live' -> 'She lives'",
            "subject-verb agreement: 'she cook' -> 'she cooks'",
            "plural error: 'many thing' -> 'many things'",
            "article error: 'in house' -> 'in the house'",
            "article error: 'in family' -> 'in the family'",
            "article error: 'to park' -> 'to the park'"
        ],
        "grammar_profile": {
            "complexity": "low",
            "accuracy": "low",
            "flexibility": "low"
        },
        "vocab_reason": "[LR4] Key evidence: 'old', 'house', 'nice', 'food', 'good', 'happy'. >Band 3: Can convey basic meaning. Not Band 5: Vocabulary is repetitive and very basic ('very old', 'very good'). No paraphrase attempts.",
        "grammar_reason": "[GRA4] Key evidence: Simple sentences mostly. 'She live', 'she cook'. >Band 3: Some correct simple sentences. Not Band 5: Frequent errors in basic structures ('She live') cause some strain.",
        "vocabulary": 4,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a family member you spend a lot of time with.\n\nTranscript: I want talk about my grandmother. She is very old, maybe eighty years. She live in my house with my family. I like her very much because she is nice. Every day, she cook food for me. The food is very good. We talk about many thing. She tell me story about old time. I listen to her. Sometimes she is tired, so she sleep. I help her do things in house. She is short and has white hair. Her face is kind. I think she is important person in family. We go to park together on Sunday. I am happy when I see her.\n\nWord Count: 96 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Key evidence: 'old', 'house', 'nice', 'food', 'good', 'happy'. \n\n>Band 3: Can convey basic meaning.\n\nNot Band 5: Vocabulary is repetitive and very basic ('very old', 'very good'). No paraphrase attempts.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Key evidence: Simple sentences mostly. 'She live', 'she cook'. \n\n>Band 3: Some correct simple sentences.\n\nNot Band 5: Frequent errors in basic structures ('She live') cause some strain.\n\n**Micro flaws identified:**\n- missing preposition: 'want talk'\n- subject-verb agreement: 'She live'\n- plural error: 'many thing'\n- article error: 'in house'\n- article error: 'to park'"
    },
    {
        "sample_id": "syn_p2_v4_g4_002",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a gift you received that you liked.",
        "transcript_cleaned": "The gift I receive is a watch. My father give it to me on my birthday. It is a beautiful watch. The color is black. I like black color. I wear it every day on my hand. It help me know time. Before, I not have watch, so I am late for school. Now I am on time. My friends say it is nice watch. I feel happy when I look at it. It is expensive, I think. My father buy it in a big shop. I keep it carefully. I don't want to break it. It is best gift I have.",
        "word_count": 99,
        "response_type": "long_turn",
        "micro_flaws": [
            "verb tense: 'receive' -> 'received'",
            "verb tense: 'give' -> 'gave'",
            "word choice: 'on my hand' -> 'on my wrist'",
            "subject-verb agreement: 'It help' -> 'It helps'",
            "negative structure: 'I not have' -> 'I did not have'",
            "article error: 'is nice watch' -> 'is a nice watch'",
            "verb tense: 'buy' -> 'bought'",
            "superlative error: 'is best gift' -> 'is the best gift'"
        ],
        "grammar_profile": {
            "complexity": "low",
            "accuracy": "low",
            "flexibility": "low"
        },
        "vocab_reason": "[LR4] Key evidence: 'gift', 'watch', 'beautiful', 'black', 'happy'. >Band 3: Basic words used correctly. Not Band 5: Frequent repetition ('watch', 'it'). Very limited range.",
        "grammar_reason": "[GRA4] Key evidence: Simple sentences only. 'My father give', 'I not have'. >Band 3: Subordinate clauses absent or rare. Not Band 5: Basic sentence errors ('I not have') are frequent.",
        "vocabulary": 4,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a gift you received that you liked.\n\nTranscript: The gift I receive is a watch. My father give it to me on my birthday. It is a beautiful watch. The color is black. I like black color. I wear it every day on my hand. It help me know time. Before, I not have watch, so I am late for school. Now I am on time. My friends say it is nice watch. I feel happy when I look at it. It is expensive, I think. My father buy it in a big shop. I keep it carefully. I don't want to break it. It is best gift I have.\n\nWord Count: 99 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Key evidence: 'gift', 'watch', 'beautiful', 'black', 'happy'. \n\n>Band 3: Basic words used correctly.\n\nNot Band 5: Frequent repetition ('watch', 'it'). Very limited range.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Key evidence: Simple sentences only. 'My father give', 'I not have'. \n\n>Band 3: Subordinate clauses absent or rare.\n\nNot Band 5: Basic sentence errors ('I not have') are frequent.\n\n**Micro flaws identified:**\n- verb tense: 'receive', 'give', 'buy'\n- negative structure: 'I not have'\n- article error: 'is nice watch'"
    },
    {
        "sample_id": "syn_p2_v4_g4_003",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a park or garden you visited and liked.",
        "transcript_cleaned": "I visit a park near my house. It is big park. Many trees and flowers are there. The flowers is red and yellow. I go there with my friend. We walk and talk. It is quiet place. I like see the birds. They sing songs. Sometimes people play sport in park. I sit on chair and look. It is good for relax. The air is clean. I feel good there. I go every weekend. It is beautiful place. I like nature very much.",
        "word_count": 83,
        "response_type": "long_turn",
        "micro_flaws": [
            "article error: 'is big park' -> 'is a big park'",
            "subject-verb agreement: 'flowers is' -> 'flowers are'",
            "article error: 'is quiet place' -> 'is a quiet place'",
            "verb pattern: 'like see' -> 'like to see' or 'like seeing'",
            "article error: 'in park' -> 'in the park'",
            "word choice: 'on chair' -> 'on a bench'",
            "word form: 'for relax' -> 'for relaxing'",
            "article error: 'is beautiful place' -> 'is a beautiful place'"
        ],
        "grammar_profile": {
            "complexity": "low",
            "accuracy": "low",
            "flexibility": "low"
        },
        "vocab_reason": "[LR4] Key evidence: 'park', 'house', 'big', 'trees', 'flowers', 'good'. >Band 3: Words are relevant to topic. Not Band 5: Very basic and repetitive ('place', 'good').",
        "grammar_reason": "[GRA4] Key evidence: Simple sentences. 'The flowers is', 'I like see'. >Band 3: Can form simple sentences. Not Band 5: Frequent errors in simple structures ('flowers is', 'like see').",
        "vocabulary": 4,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a park or garden you visited and liked.\n\nTranscript: I visit a park near my house. It is big park. Many trees and flowers are there. The flowers is red and yellow. I go there with my friend. We walk and talk. It is quiet place. I like see the birds. They sing songs. Sometimes people play sport in park. I sit on chair and look. It is good for relax. The air is clean. I feel good there. I go every weekend. It is beautiful place. I like nature very much.\n\nWord Count: 83 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Key evidence: 'park', 'house', 'big', 'trees', 'flowers', 'good'. \n\n>Band 3: Words are relevant to topic.\n\nNot Band 5: Very basic and repetitive ('place', 'good').\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Key evidence: Simple sentences. 'The flowers is', 'I like see'. \n\n>Band 3: Can form simple sentences.\n\nNot Band 5: Frequent errors in simple structures ('flowers is', 'like see').\n\n**Micro flaws identified:**\n- article error: 'is big park'\n- subject-verb agreement: 'flowers is'\n- verb pattern: 'like see'\n- word form: 'for relax'"
    },
    {
        "sample_id": "syn_p2_v4_g4_004",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a close friend you have.",
        "transcript_cleaned": "My friend name is Ahmed. He is very tall man. We are friend for long time. He have brown eyes and black hair. He is funny. He make me laugh. We play football together on Saturday. He is good player. I like him because he is kind. He help me when I have problem. He live near my home. We go school together before. Now he work in shop. I meet him in cafe sometimes. We drink coffee and talk. He is best friend for me.",
        "word_count": 87,
        "response_type": "long_turn",
        "micro_flaws": [
            "possessive error: 'friend name' -> 'friend\\'s name'",
            "article error: 'is very tall man' -> 'is a very tall man'",
            "plural error: 'are friend' -> 'are friends'",
            "subject-verb agreement: 'He have' -> 'He has'",
            "subject-verb agreement: 'He make' -> 'He makes'",
            "article error: 'is good player' -> 'is a good player'",
            "subject-verb agreement: 'He help' -> 'He helps'",
            "subject-verb agreement: 'He live' -> 'He lives'",
            "verb tense: 'go school' -> 'went to school'",
            "subject-verb agreement: 'he work' -> 'he works'",
            "article error: 'is best friend' -> 'is my best friend'"
        ],
        "grammar_profile": {
            "complexity": "low",
            "accuracy": "low",
            "flexibility": "low"
        },
        "vocab_reason": "[LR4] Key evidence: 'tall', 'eyes', 'hair', 'funny', 'football'. >Band 3: Uses basic words to describe person. Not Band 5: Limited range, repetitive 'he is'.",
        "grammar_reason": "[GRA4] Key evidence: Simple sentences, frequent errors. 'He have', 'He make', 'He live'. >Band 3: Simple sentence structure is attempted. Not Band 5: Systematic subject-verb agreement errors.",
        "vocabulary": 4,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a close friend you have.\n\nTranscript: My friend name is Ahmed. He is very tall man. We are friend for long time. He have brown eyes and black hair. He is funny. He make me laugh. We play football together on Saturday. He is good player. I like him because he is kind. He help me when I have problem. He live near my home. We go school together before. Now he work in shop. I meet him in cafe sometimes. We drink coffee and talk. He is best friend for me.\n\nWord Count: 87 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Key evidence: 'tall', 'eyes', 'hair', 'funny', 'football'. \n\n>Band 3: Uses basic words to describe person.\n\nNot Band 5: Limited range, repetitive 'he is'.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Key evidence: Simple sentences, frequent errors. 'He have', 'He make', 'He live'. \n\n>Band 3: Simple sentence structure is attempted.\n\nNot Band 5: Systematic subject-verb agreement errors.\n\n**Micro flaws identified:**\n- possessive error: 'friend name'\n- subject-verb agreement: 'He have', 'He make'\n- verb tense: 'go school'\n- article error: 'is best friend'"
    },
    {
        "sample_id": "syn_p2_v4_g4_005",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a holiday you enjoyed.",
        "transcript_cleaned": "Last year I go to beach with family. It was summer time. The weather is very hot. I swim in water. The water is blue and clean. I play sand with my brother. We eat fish in restaurant. It is delicious. I sleep in hotel near beach. The room is big. I see many people there. Everyone is happy. I take many photo. I buy souvenir for friend. I stay there three days. I want go back again. It is very nice holiday.",
        "word_count": 84,
        "response_type": "long_turn",
        "micro_flaws": [
            "verb tense: 'go to beach' -> 'went to the beach'",
            "verb tense: 'weather is' -> 'weather was'",
            "verb tense: 'swim' -> 'swam'",
            "verb tense: 'play sand' -> 'played in the sand'",
            "verb tense: 'eat fish' -> 'ate fish'",
            "verb tense: 'is delicious' -> 'was delicious'",
            "verb tense: 'sleep' -> 'slept'",
            "verb tense: 'see' -> 'saw'",
            "verb tense: 'take' -> 'took'",
            "plural error: 'many photo' -> 'many photos'",
            "verb tense: 'buy' -> 'bought'",
            "verb pattern: 'want go' -> 'want to go'",
            "article error: 'is very nice holiday' -> 'was a very nice holiday'"
        ],
        "grammar_profile": {
            "complexity": "low",
            "accuracy": "low",
            "flexibility": "low"
        },
        "vocab_reason": "[LR4] Key evidence: 'beach', 'summer', 'hot', 'swim', 'water', 'sand', 'fish'. >Band 3: Basic travel words used. Not Band 5: Vocabulary limited to very common words. No less common items.",
        "grammar_reason": "[GRA4] Key evidence: Simple sentences mostly. Wrong tenses throughout ('I go', 'is hot' for past event). >Band 3: Simple sentences are recognizable. Not Band 5: Past tense is almost completely absent or incorrect.",
        "vocabulary": 4,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a holiday you enjoyed.\n\nTranscript: Last year I go to beach with family. It was summer time. The weather is very hot. I swim in water. The water is blue and clean. I play sand with my brother. We eat fish in restaurant. It is delicious. I sleep in hotel near beach. The room is big. I see many people there. Everyone is happy. I take many photo. I buy souvenir for friend. I stay there three days. I want go back again. It is very nice holiday.\n\nWord Count: 84 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Key evidence: 'beach', 'summer', 'hot', 'swim', 'water', 'sand', 'fish'. \n\n>Band 3: Basic travel words used.\n\nNot Band 5: Vocabulary limited to very common words. No less common items.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Key evidence: Simple sentences mostly. Wrong tenses throughout ('I go', 'is hot' for past event). \n\n>Band 3: Simple sentences are recognizable.\n\nNot Band 5: Past tense is almost completely absent or incorrect.\n\n**Micro flaws identified:**\n- verb tense: 'go', 'is', 'swim', 'play', 'eat', 'sleep', 'see', 'take', 'buy'\n- plural error: 'many photo'\n- verb pattern: 'want go'"
    },
    {
        "sample_id": "syn_p2_v4_g4_006",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a job you would like to do in the future.",
        "transcript_cleaned": "I want to be doctor. It is good job. I can help sick people. I like help people. Doctors have much money. I work in hospital. It is clean place. I wear white coat. I study hard now for this job. It is difficult but I try. My father is doctor too. He tell me it is interesting. I must know about medicine. I want save life. It is important job for society. Everyone respect doctor. I hope I can do it.",
        "word_count": 86,
        "response_type": "long_turn",
        "micro_flaws": [
            "article error: 'be doctor' -> 'be a doctor'",
            "article error: 'is good job' -> 'is a good job'",
            "verb pattern: 'like help' -> 'like helping'",
            "quantifier error: 'much money' -> 'a lot of money' (much is unnatural here)",
            "article error: 'in hospital' -> 'in a hospital'",
            "article error: 'is clean place' -> 'is a clean place'",
            "article error: 'wear white coat' -> 'wear a white coat'",
            "article error: 'is doctor' -> 'is a doctor'",
            "subject-verb agreement: 'He tell' -> 'He tells'",
            "verb pattern: 'want save' -> 'want to save'",
            "article error: 'is important job' -> 'is an important job'",
            "plural error: 'life' -> 'lives'",
            "article error: 'respect doctor' -> 'respects doctors'"
        ],
        "grammar_profile": {
            "complexity": "low",
            "accuracy": "low",
            "flexibility": "low"
        },
        "vocab_reason": "[LR4] Key evidence: 'doctor', 'job', 'help', 'sick', 'money', 'hospital'. >Band 3: Correct words for topic. Not Band 5: Repetitive 'job', 'doctor'. Basic descriptors.",
        "grammar_reason": "[GRA4] Key evidence: Simple sentences mainly. 'I want be', 'It is good'. >Band 3: Meaning is clear through simple sentences. Not Band 5: Frequent article errors ('be doctor', 'is good job') and verb pattern errors ('like help').",
        "vocabulary": 4,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a job you would like to do in the future.\n\nTranscript: I want to be doctor. It is good job. I can help sick people. I like help people. Doctors have much money. I work in hospital. It is clean place. I wear white coat. I study hard now for this job. It is difficult but I try. My father is doctor too. He tell me it is interesting. I must know about medicine. I want save life. It is important job for society. Everyone respect doctor. I hope I can do it.\n\nWord Count: 86 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Key evidence: 'doctor', 'job', 'help', 'sick', 'money', 'hospital'. \n\n>Band 3: Correct words for topic.\n\nNot Band 5: Repetitive 'job', 'doctor'. Basic descriptors.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Key evidence: Simple sentences mainly. 'I want be', 'It is good'. \n\n>Band 3: Meaning is clear through simple sentences.\n\nNot Band 5: Frequent article errors ('be doctor', 'is good job') and verb pattern errors ('like help').\n\n**Micro flaws identified:**\n- article error: 'be doctor', 'is good job', 'in hospital', 'is doctor', 'is important job'\n- verb pattern: 'like help', 'want save'\n- subject-verb agreement: 'He tell'"
    },
    {
        "sample_id": "syn_p2_v4_g4_007",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a movie you watched recently.",
        "transcript_cleaned": "I watch a movie yesterday. The name is Action Man. It is action movie. I watch it in cinema with friend. The movie is very exciting. Many fight and car fast. The actor is very strong. He fight bad people. I like the story. It is easy understand. I eat popcorn and drink cola. The cinema is big and dark. Sound is very loud. I feel happy when good man win. I tell my brother see this movie. It is good movie for young people.",
        "word_count": 87,
        "response_type": "long_turn",
        "micro_flaws": [
            "verb tense: 'watch' -> 'watched'",
            "article error: 'is action movie' -> 'is an action movie'",
            "article error: 'in cinema' -> 'in the cinema'",
            "plural error: 'with friend' -> 'with a friend' or 'friends'",
            "word choice/grammar: 'Many fight and car fast' -> 'There were many fights and fast cars'",
            "subject-verb agreement: 'He fight' -> 'He fights' (or 'fought' for past)",
            "verb pattern: 'easy understand' -> 'easy to understand'",
            "article error: 'Sound is' -> 'The sound is'",
            "verb tense/agreement: 'good man win' -> 'the good man won'",
            "verb pattern: 'tell my brother see' -> 'told my brother to see'",
            "article error: 'is good movie' -> 'is a good movie'"
        ],
        "grammar_profile": {
            "complexity": "low",
            "accuracy": "low",
            "flexibility": "low"
        },
        "vocab_reason": "[LR4] Key evidence: 'movie', 'cinema', 'exciting', 'fight', 'actor', 'story'. >Band 3: Basic entertainment words. Not Band 5: 'Many fight and car fast' shows lack of vocabulary to describe scenes properly.",
        "grammar_reason": "[GRA4] Key evidence: Simple sentences. Frequent omission of articles/verbs. >Band 3: Simple structures present. Not Band 5: Errors like 'easy understand', 'tell brother see' impede communication slightly.",
        "vocabulary": 4,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a movie you watched recently.\n\nTranscript: I watch a movie yesterday. The name is Action Man. It is action movie. I watch it in cinema with friend. The movie is very exciting. Many fight and car fast. The actor is very strong. He fight bad people. I like the story. It is easy understand. I eat popcorn and drink cola. The cinema is big and dark. Sound is very loud. I feel happy when good man win. I tell my brother see this movie. It is good movie for young people.\n\nWord Count: 87 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Key evidence: 'movie', 'cinema', 'exciting', 'fight', 'actor', 'story'. \n\n>Band 3: Basic entertainment words.\n\nNot Band 5: 'Many fight and car fast' shows lack of vocabulary to describe scenes properly.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Key evidence: Simple sentences. Frequent omission of articles/verbs. \n\n>Band 3: Simple structures present.\n\nNot Band 5: Errors like 'easy understand', 'tell brother see' impede communication slightly.\n\n**Micro flaws identified:**\n- verb tense: 'watch', 'fight'\n- article error: 'is action movie', 'in cinema', 'Sound is'\n- verb pattern: 'easy understand', 'tell ... see'\n- sentence structure: 'Many fight and car fast'"
    },
    {
        "sample_id": "syn_p2_v4_g4_008",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe an animal you like.",
        "transcript_cleaned": "I like cat. Cat is very cute animal. I have one cat in my home. Its name is Mimi. It is white and small. It like to sleep on my bed. It eat fish and drink milk. Sometimes it play with ball. I touch it, it is soft. I like cat because it is quiet. Not loud like dog. When I come home, it come to me. I think cat is good friend for people. It catch mouse too. I love my cat very much.",
        "word_count": 88,
        "response_type": "long_turn",
        "micro_flaws": [
            "article error: 'I like cat' -> 'I like cats'",
            "article error: 'Cat is' -> 'A cat is' or 'Cats are'",
            "article error: 'is very cute animal' -> 'is a very cute animal'",
            "subject-verb agreement: 'It like' -> 'It likes'",
            "subject-verb agreement: 'It eat' -> 'It eats'",
            "subject-verb agreement: 'it play' -> 'it plays'",
            "article error: 'with ball' -> 'with a ball'",
            "fragment: 'Not loud like dog' -> 'It is not loud like a dog'",
            "subject-verb agreement: 'it come' -> 'it comes'",
            "article error: 'catch mouse' -> 'catches mice'"
        ],
        "grammar_profile": {
            "complexity": "low",
            "accuracy": "low",
            "flexibility": "low"
        },
        "vocab_reason": "[LR4] Key evidence: 'cat', 'cute', 'home', 'sleep', 'bed', 'fish'. >Band 3: Identifies animal and actions. Not Band 5: Very limited descriptive words ('cute', 'small', 'soft', 'good').",
        "grammar_reason": "[GRA4] Key evidence: Simple sentences mostly. 'It like', 'It eat'. >Band 3: Basic sentence forms. Not Band 5: Constant subject-verb agreement errors ('It like', 'It play').",
        "vocabulary": 4,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe an animal you like.\n\nTranscript: I like cat. Cat is very cute animal. I have one cat in my home. Its name is Mimi. It is white and small. It like to sleep on my bed. It eat fish and drink milk. Sometimes it play with ball. I touch it, it is soft. I like cat because it is quiet. Not loud like dog. When I come home, it come to me. I think cat is good friend for people. It catch mouse too. I love my cat very much.\n\nWord Count: 88 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Key evidence: 'cat', 'cute', 'home', 'sleep', 'bed', 'fish'. \n\n>Band 3: Identifies animal and actions.\n\nNot Band 5: Very limited descriptive words ('cute', 'small', 'soft', 'good').\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Key evidence: Simple sentences mostly. 'It like', 'It eat'. \n\n>Band 3: Basic sentence forms.\n\nNot Band 5: Constant subject-verb agreement errors ('It like', 'It play').\n\n**Micro flaws identified:**\n- article error: 'like cat', 'Cat is', 'is cute animal'\n- subject-verb agreement: 'It like', 'It eat', 'it play', 'it come'\n- plural error: 'catch mouse' (mice)"
    },
    {
        "sample_id": "syn_p2_v4_g4_009",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a meal you had with friends.",
        "transcript_cleaned": "I eat dinner with friends last Saturday. We go to pizza restaurant. It is popular place. I order big pizza with cheese. My friends order pasta. We drink juice. The food taste very good. We are hungry so we eat fast. We talk about school and funny things. We laugh a lot. The restaurant have music. It is nice atmosphere. After eat, we pay money. It is not expensive. I like eat with friends because it is fun. We plan go again next week.",
        "word_count": 86,
        "response_type": "long_turn",
        "micro_flaws": [
            "verb tense: 'eat' -> 'ate'",
            "verb tense: 'go' -> 'went'",
            "article error: 'is popular place' -> 'is a popular place'",
            "subject-verb agreement: 'food taste' -> 'food tastes' (or 'tasted')",
            "subject-verb agreement: 'restaurant have' -> 'restaurant has' (or 'had')",
            "article error: 'is nice atmosphere' -> 'is a nice atmosphere'",
            "preposition/gerund: 'After eat' -> 'After eating'",
            "verb pattern: 'like eat' -> 'like eating' or 'like to eat'",
            "verb pattern: 'plan go' -> 'plan to go'"
        ],
        "grammar_profile": {
            "complexity": "low",
            "accuracy": "low",
            "flexibility": "low"
        },
        "vocab_reason": "[LR4] Key evidence: 'dinner', 'pizza', 'cheese', 'hungry', 'laugh', 'music'. >Band 3: Basic food words. Not Band 5: Repetitive 'good', 'nice'. No specific food vocabulary beyond 'pizza/pasta'.",
        "grammar_reason": "[GRA4] Key evidence: Simple sentences. Wrong tenses. >Band 3: Simple sentences clear. Not Band 5: 'After eat', 'plan go', 'food taste' show poor control of basic structures.",
        "vocabulary": 4,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a meal you had with friends.\n\nTranscript: I eat dinner with friends last Saturday. We go to pizza restaurant. It is popular place. I order big pizza with cheese. My friends order pasta. We drink juice. The food taste very good. We are hungry so we eat fast. We talk about school and funny things. We laugh a lot. The restaurant have music. It is nice atmosphere. After eat, we pay money. It is not expensive. I like eat with friends because it is fun. We plan go again next week.\n\nWord Count: 86 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Key evidence: 'dinner', 'pizza', 'cheese', 'hungry', 'laugh', 'music'. \n\n>Band 3: Basic food words.\n\nNot Band 5: Repetitive 'good', 'nice'. No specific food vocabulary beyond 'pizza/pasta'.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Key evidence: Simple sentences. Wrong tenses. \n\n>Band 3: Simple sentences clear.\n\nNot Band 5: 'After eat', 'plan go', 'food taste' show poor control of basic structures.\n\n**Micro flaws identified:**\n- verb tense: 'eat', 'go', 'order'\n- article error: 'is popular place'\n- subject-verb agreement: 'food taste', 'restaurant have'\n- verb pattern: 'After eat', 'like eat', 'plan go'"
    },
    {
        "sample_id": "syn_p2_v4_g4_010",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a teacher who helped you.",
        "transcript_cleaned": "My English teacher help me much. Her name is Ms. Mary. She is very kind woman. She teach me in high school. My English is bad before. She explain very clear. She give me extra homework. I do it and she check. She tell me \"good job\". I feel happy. She speak slowly for me understand. She never angry. She smile always. I learn many word from her. Now I can speak better. She is best teacher I know. I want say thank you to her.",
        "word_count": 87,
        "response_type": "long_turn",
        "micro_flaws": [
            "verb tense: 'help' -> 'helped'",
            "word choice: 'much' -> 'a lot'",
            "article error: 'is very kind woman' -> 'is a very kind woman'",
            "verb tense: 'teach' -> 'taught'",
            "verb tense: 'is bad' -> 'was bad'",
            "word form: 'explain very clear' -> 'explained very clearly'",
            "verb tense: 'give' -> 'gave'",
            "verb tense: 'check' -> 'checked'",
            "verb pattern: 'for me understand' -> 'for me to understand'",
            "verb tense: 'never angry' -> 'was never angry'",
            "word order/tense: 'She smile always' -> 'She always smiled'",
            "plural error: 'many word' -> 'many words'",
            "article error: 'is best teacher' -> 'is the best teacher'",
            "verb pattern: 'want say' -> 'want to say'"
        ],
        "grammar_profile": {
            "complexity": "low",
            "accuracy": "low",
            "flexibility": "low"
        },
        "vocab_reason": "[LR4] Key evidence: 'teacher', 'help', 'kind', 'school', 'homework', 'good'. >Band 3: Context clear. Not Band 5: 'My English is bad' is very basic. 'Explain very clear' (wrong form).",
        "grammar_reason": "[GRA4] Key evidence: Simple sentences only. Wrong tenses. >Band 3: Simple sentences. Not Band 5: Errors in almost every sentence ('She teach', 'She explain', 'She give').",
        "vocabulary": 4,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a teacher who helped you.\n\nTranscript: My English teacher help me much. Her name is Ms. Mary. She is very kind woman. She teach me in high school. My English is bad before. She explain very clear. She give me extra homework. I do it and she check. She tell me \"good job\". I feel happy. She speak slowly for me understand. She never angry. She smile always. I learn many word from her. Now I can speak better. She is best teacher I know. I want say thank you to her.\n\nWord Count: 87 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Key evidence: 'teacher', 'help', 'kind', 'school', 'homework', 'good'. \n\n>Band 3: Context clear.\n\nNot Band 5: 'My English is bad' is very basic. 'Explain very clear' (wrong form).\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Key evidence: Simple sentences only. Wrong tenses. \n\n>Band 3: Simple sentences.\n\nNot Band 5: Errors in almost every sentence ('She teach', 'She explain', 'She give').\n\n**Micro flaws identified:**\n- verb tense: 'help', 'teach', 'is', 'give', 'check'\n- word form: 'clear' (clearly)\n- verb pattern: 'for me understand', 'want say'\n- article error: 'is best teacher'"
    },
    {
        "sample_id": "syn_p2_v4_g4_011",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a sport you played or watched.",
        "transcript_cleaned": "I play football. It is my favorite sport. I play in park with friends. We play on Sunday usually. I like run and kick ball. It make me healthy. The game is exciting. Sometimes I watch football on TV. I like Brazil team. They play very good. I want be like them. Football is popular in my country. Everyone like it. I buy new shoes for football last month. They are red. I play better with new shoes. I think football is best sport.",
        "word_count": 87,
        "response_type": "long_turn",
        "micro_flaws": [
            "article error: 'in park' -> 'in the park'",
            "word choice: 'on Sunday usually' -> 'usually on Sunday' (word order)",
            "verb pattern: 'like run' -> 'like running'",
            "article error: 'kick ball' -> 'kick the ball'",
            "subject-verb agreement: 'It make' -> 'It makes'",
            "article error: 'Brazil team' -> 'the Brazil team'",
            "word form: 'play very good' -> 'play very well'",
            "verb pattern: 'want be' -> 'want to be'",
            "subject-verb agreement: 'Everyone like' -> 'Everyone likes'",
            "verb tense: 'buy' -> 'bought'",
            "article error: 'is best sport' -> 'is the best sport'"
        ],
        "grammar_profile": {
            "complexity": "low",
            "accuracy": "low",
            "flexibility": "low"
        },
        "vocab_reason": "[LR4] Key evidence: 'football', 'sport', 'run', 'kick', 'ball', 'healthy'. >Band 3: Topic clear. Not Band 5: 'Play very good' (wrong form). Very basic words.",
        "grammar_reason": "[GRA4] Key evidence: Simple sentences. 'It make', 'Everyone like'. >Band 3: Simple sentences. Not Band 5: Subject-verb agreement errors frequent. Wrong word order 'on Sunday usually'.",
        "vocabulary": 4,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a sport you played or watched.\n\nTranscript: I play football. It is my favorite sport. I play in park with friends. We play on Sunday usually. I like run and kick ball. It make me healthy. The game is exciting. Sometimes I watch football on TV. I like Brazil team. They play very good. I want be like them. Football is popular in my country. Everyone like it. I buy new shoes for football last month. They are red. I play better with new shoes. I think football is best sport.\n\nWord Count: 87 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Key evidence: 'football', 'sport', 'run', 'kick', 'ball', 'healthy'. \n\n>Band 3: Topic clear.\n\nNot Band 5: 'Play very good' (wrong form). Very basic words.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Key evidence: Simple sentences. 'It make', 'Everyone like'. \n\n>Band 3: Simple sentences.\n\nNot Band 5: Subject-verb agreement errors frequent. Wrong word order 'on Sunday usually'.\n\n**Micro flaws identified:**\n- subject-verb agreement: 'It make', 'Everyone like'\n- verb pattern: 'like run', 'want be'\n- word form: 'good' (well)\n- article error: 'kick ball', 'Brazil team', 'is best sport'"
    },
    {
        "sample_id": "syn_p2_v4_g4_012",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a house or apartment you would like to live in.",
        "transcript_cleaned": "I want live in big house. It is in countryside. I not like city. Too noisy. The house have five rooms. A big kitchen for cooking. I like garden too. I plant flowers there. The house is white color. I have dog in garden. It is quiet place. I can sleep well. I want big window to see sun. My family live with me. We are happy there. It is dream house. Cost is expensive, I think. But I work hard to buy it one day.",
        "word_count": 91,
        "response_type": "long_turn",
        "micro_flaws": [
            "verb pattern: 'want live' -> 'want to live'",
            "article error: 'in big house' -> 'in a big house'",
            "article error: 'in countryside' -> 'in the countryside'",
            "negative structure: 'I not like' -> 'I do not like'",
            "subject-verb agreement: 'house have' -> 'house has'",
            "article error: 'like garden' -> 'like a garden' or 'the garden'",
            "article error: 'have dog' -> 'have a dog'",
            "article error: 'is quiet place' -> 'is a quiet place'",
            "article error: 'want big window' -> 'want a big window'",
            "article error: 'see sun' -> 'see the sun'",
            "subject-verb agreement: 'family live' -> 'family lives'",
            "article error: 'is dream house' -> 'is a dream house'",
            "article error: 'Cost is' -> 'The cost is'"
        ],
        "grammar_profile": {
            "complexity": "low",
            "accuracy": "low",
            "flexibility": "low"
        },
        "vocab_reason": "[LR4] Key evidence: 'house', 'countryside', 'city', 'noisy', 'kitchen', 'garden'. >Band 3: Can describe housing. Not Band 5: 'White color' (redundant). 'Big' repeated often.",
        "grammar_reason": "[GRA4] Key evidence: Simple sentences. 'I not like', 'house have'. >Band 3: Simple sentences. Not Band 5: Negative structure 'I not like' is Band 4. Article errors very frequent.",
        "vocabulary": 4,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a house or apartment you would like to live in.\n\nTranscript: I want live in big house. It is in countryside. I not like city. Too noisy. The house have five rooms. A big kitchen for cooking. I like garden too. I plant flowers there. The house is white color. I have dog in garden. It is quiet place. I can sleep well. I want big window to see sun. My family live with me. We are happy there. It is dream house. Cost is expensive, I think. But I work hard to buy it one day.\n\nWord Count: 91 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Key evidence: 'house', 'countryside', 'city', 'noisy', 'kitchen', 'garden'. \n\n>Band 3: Can describe housing.\n\nNot Band 5: 'White color' (redundant). 'Big' repeated often.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Key evidence: Simple sentences. 'I not like', 'house have'. \n\n>Band 3: Simple sentences.\n\nNot Band 5: Negative structure 'I not like' is Band 4. Article errors very frequent.\n\n**Micro flaws identified:**\n- verb pattern: 'want live'\n- negative structure: 'I not like'\n- subject-verb agreement: 'house have', 'family live'\n- article error: 'in big house', 'in countryside', 'have dog'"
    },
    {
        "sample_id": "syn_p2_v4_g4_013",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a city you have visited.",
        "transcript_cleaned": "I visit Istanbul last summer. It is beautiful city in Turkey. Many people live there. The city is very big. I see many mosque. They are old and nice. I go to market. It is busy. I buy some clothes. The food is delicious. I eat kebab every day. The weather is hot. I walk near sea. It is blue. People are friendly. I speak English with them. I like Istanbul because it is historic. I want visit again. It is good memory for me.",
        "word_count": 89,
        "response_type": "long_turn",
        "micro_flaws": [
            "verb tense: 'visit' -> 'visited'",
            "article error: 'is beautiful city' -> 'is a beautiful city'",
            "plural error: 'many mosque' -> 'many mosques'",
            "verb tense: 'go' -> 'went'",
            "verb tense: 'buy' -> 'bought'",
            "verb tense: 'eat' -> 'ate'",
            "verb tense: 'is hot' -> 'was hot'",
            "verb tense: 'walk' -> 'walked'",
            "article error: 'near sea' -> 'near the sea'",
            "verb pattern: 'want visit' -> 'want to visit'",
            "article error: 'is good memory' -> 'is a good memory'"
        ],
        "grammar_profile": {
            "complexity": "low",
            "accuracy": "low",
            "flexibility": "low"
        },
        "vocab_reason": "[LR4] Key evidence: 'city', 'big', 'market', 'clothes', 'food', 'hot'. >Band 3: Basic travel vocab. Not Band 5: 'Nice' and 'good' used repeatedly. 'Historic' is the only less common word but maybe memorized.",
        "grammar_reason": "[GRA4] Key evidence: Simple sentences only. Wrong tenses. >Band 3: Simple sentences. Not Band 5: 'I visit', 'I go', 'I buy' (present for past) is a typical Band 4 error pattern.",
        "vocabulary": 4,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a city you have visited.\n\nTranscript: I visit Istanbul last summer. It is beautiful city in Turkey. Many people live there. The city is very big. I see many mosque. They are old and nice. I go to market. It is busy. I buy some clothes. The food is delicious. I eat kebab every day. The weather is hot. I walk near sea. It is blue. People are friendly. I speak English with them. I like Istanbul because it is historic. I want visit again. It is good memory for me.\n\nWord Count: 89 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Key evidence: 'city', 'big', 'market', 'clothes', 'food', 'hot'. \n\n>Band 3: Basic travel vocab.\n\nNot Band 5: 'Nice' and 'good' used repeatedly. 'Historic' is the only less common word but maybe memorized.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Key evidence: Simple sentences only. Wrong tenses. \n\n>Band 3: Simple sentences.\n\nNot Band 5: 'I visit', 'I go', 'I buy' (present for past) is a typical Band 4 error pattern.\n\n**Micro flaws identified:**\n- verb tense: 'visit', 'go', 'buy', 'eat', 'is', 'walk'\n- plural error: 'many mosque'\n- article error: 'is beautiful city', 'near sea'"
    }
]

with open(OUTPUT_FILE, 'a') as f:
    for sample in samples:
        json.dump(sample, f)
        f.write('\n')
