import json

OUTPUT_FILE = 'ielts-data/phase3/v76_review_output/jules1/jules1_batch04.jsonl'

samples = [
    {
        "sample_id": "syn_p2_v6_g6_251",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a book you read recently.",
        "transcript_cleaned": "I recently read \"The Alchemist\" by Paulo Coelho. It is a very inspiring novel about following your dreams. The protagonist is a shepherd boy who travels from Spain to Egypt. He faces many challenges along the way, but he never gives up. The language is simple but profound. I learned that we should listen to our hearts. It is a bestseller for a reason. I would recommend it to anyone who feels lost.",
        "word_count": 76,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'inspiring', 'protagonist', 'shepherd', 'profound', 'bestseller', 'recommend', 'lost'. >Band 5: 'Protagonist', 'profound'. Not Band 7: Standard collocations.",
        "grammar_reason": "[GRA6] Key evidence: 'boy who travels', 'learned that we should', 'anyone who feels'. >Band 5: Mix of complex structures. Not Band 7: Simple sentence structure still frequent.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a book you read recently.\n\nTranscript: I recently read \"The Alchemist\" by Paulo Coelho. It is a very inspiring novel about following your dreams. The protagonist is a shepherd boy who travels from Spain to Egypt. He faces many challenges along the way, but he never gives up. The language is simple but profound. I learned that we should listen to our hearts. It is a bestseller for a reason. I would recommend it to anyone who feels lost.\n\nWord Count: 76 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'inspiring', 'protagonist', 'shepherd', 'profound', 'bestseller', 'recommend', 'lost'. \n\n>Band 5: 'Protagonist', 'profound'.\n\nNot Band 7: Standard collocations.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'boy who travels', 'learned that we should', 'anyone who feels'. \n\n>Band 5: Mix of complex structures.\n\nNot Band 7: Simple sentence structure still frequent.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_252",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a historical place.",
        "transcript_cleaned": "I visited the Colosseum in Rome last year. It is an ancient amphitheater which was built by the Romans. It is massive and impressive. In the past, gladiators fought there. It was a brutal form of entertainment. Now, it is a ruin, but it still stands. I was amazed by the engineering. I took a guided tour to learn more. It is a major tourist attraction. I think it is important to preserve such sites.",
        "word_count": 78,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'ancient', 'amphitheater', 'massive', 'impressive', 'gladiators', 'brutal', 'entertainment', 'ruin', 'engineering', 'preserve'. >Band 5: 'Amphitheater', 'brutal'. Not Band 7: Good range but standard.",
        "grammar_reason": "[GRA6] Key evidence: 'amphitheater which was built', 'I think it is important to'. >Band 5: Passive voice and complex sentences correct. Not Band 7: Short sentences.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a historical place.\n\nTranscript: I visited the Colosseum in Rome last year. It is an ancient amphitheater which was built by the Romans. It is massive and impressive. In the past, gladiators fought there. It was a brutal form of entertainment. Now, it is a ruin, but it still stands. I was amazed by the engineering. I took a guided tour to learn more. It is a major tourist attraction. I think it is important to preserve such sites.\n\nWord Count: 78 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'ancient', 'amphitheater', 'massive', 'impressive', 'gladiators', 'brutal', 'entertainment', 'ruin', 'engineering', 'preserve'. \n\n>Band 5: 'Amphitheater', 'brutal'.\n\nNot Band 7: Good range but standard.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'amphitheater which was built', 'I think it is important to'. \n\n>Band 5: Passive voice and complex sentences correct.\n\nNot Band 7: Short sentences.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_253",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a difficult task.",
        "transcript_cleaned": "I had to organize a surprise party for my mother. It was a challenging task. I had to invite guests without her knowing. I also had to order food and decorations. It was stressful because I had little time. However, my sister helped me. We worked together as a team. The party was a success. My mother was shocked and happy. I felt relieved when it was over. It taught me about planning.",
        "word_count": 76,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'organize', 'surprise party', 'challenging', 'invite', 'decorations', 'stressful', 'success', 'shocked', 'relieved', 'planning'. >Band 5: 'Challenging', 'relieved'. Not Band 7: Standard vocab.",
        "grammar_reason": "[GRA6] Key evidence: 'without her knowing', 'because I had little time', 'when it was over'. >Band 5: Adverbial clauses and gerund phrases correct. Not Band 7: Simple structure.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a difficult task.\n\nTranscript: I had to organize a surprise party for my mother. It was a challenging task. I had to invite guests without her knowing. I also had to order food and decorations. It was stressful because I had little time. However, my sister helped me. We worked together as a team. The party was a success. My mother was shocked and happy. I felt relieved when it was over. It taught me about planning.\n\nWord Count: 76 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'organize', 'surprise party', 'challenging', 'invite', 'decorations', 'stressful', 'success', 'shocked', 'relieved', 'planning'. \n\n>Band 5: 'Challenging', 'relieved'.\n\nNot Band 7: Standard vocab.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'without her knowing', 'because I had little time', 'when it was over'. \n\n>Band 5: Adverbial clauses and gerund phrases correct.\n\nNot Band 7: Simple structure.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_254",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a movie character.",
        "transcript_cleaned": "I like Iron Man from the Marvel movies. He is a wealthy businessman named Tony Stark. He is very intelligent but arrogant. He builds a high-tech suit to fight crime. I like him because he is funny and brave. He sacrifices himself to save the world. He is a complex character. He makes mistakes, but he learns from them. Robert Downey Jr. plays the role perfectly. He is my favorite superhero.",
        "word_count": 74,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'wealthy', 'businessman', 'intelligent', 'arrogant', 'high-tech', 'crime', 'sacrifices', 'complex character', 'superhero'. >Band 5: 'Arrogant', 'sacrifices'. Not Band 7: Standard descriptions.",
        "grammar_reason": "[GRA6] Key evidence: 'named Tony Stark', 'because he is funny', 'to save the world'. >Band 5: Participle phrases and infinitive purpose used correctly. Not Band 7: Short sentences.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a movie character.\n\nTranscript: I like Iron Man from the Marvel movies. He is a wealthy businessman named Tony Stark. He is very intelligent but arrogant. He builds a high-tech suit to fight crime. I like him because he is funny and brave. He sacrifices himself to save the world. He is a complex character. He makes mistakes, but he learns from them. Robert Downey Jr. plays the role perfectly. He is my favorite superhero.\n\nWord Count: 74 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'wealthy', 'businessman', 'intelligent', 'arrogant', 'high-tech', 'crime', 'sacrifices', 'complex character', 'superhero'. \n\n>Band 5: 'Arrogant', 'sacrifices'.\n\nNot Band 7: Standard descriptions.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'named Tony Stark', 'because he is funny', 'to save the world'. \n\n>Band 5: Participle phrases and infinitive purpose used correctly.\n\nNot Band 7: Short sentences.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_255",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a useful skill.",
        "transcript_cleaned": "I learned how to manage my time effectively. It is a soft skill. I used to procrastinate a lot. I wasted time on social media. Now, I use a planner to organize my tasks. I prioritize important work. It helps me reduce stress. I can finish my assignments on time. Time management is crucial for success. I think students should learn this skill early. It makes life more productive.",
        "word_count": 72,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'manage', 'effectively', 'soft skill', 'procrastinate', 'organize', 'tasks', 'prioritize', 'reduce stress', 'crucial', 'productive'. >Band 5: 'Procrastinate', 'prioritize'. Not Band 7: Good range.",
        "grammar_reason": "[GRA6] Key evidence: 'how to manage', 'used to procrastinate', 'to organize my tasks'. >Band 5: Correct use of 'used to' and infinitives. Not Band 7: Simple structure.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a useful skill.\n\nTranscript: I learned how to manage my time effectively. It is a soft skill. I used to procrastinate a lot. I wasted time on social media. Now, I use a planner to organize my tasks. I prioritize important work. It helps me reduce stress. I can finish my assignments on time. Time management is crucial for success. I think students should learn this skill early. It makes life more productive.\n\nWord Count: 72 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'manage', 'effectively', 'soft skill', 'procrastinate', 'organize', 'tasks', 'prioritize', 'reduce stress', 'crucial', 'productive'. \n\n>Band 5: 'Procrastinate', 'prioritize'.\n\nNot Band 7: Good range.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'how to manage', 'used to procrastinate', 'to organize my tasks'. \n\n>Band 5: Correct use of 'used to' and infinitives.\n\nNot Band 7: Simple structure.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_256",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a holiday.",
        "transcript_cleaned": "I went camping in the forest last month. It was an adventurous trip. We set up a tent near a river. We made a campfire and cooked food. At night, we looked at the stars. It was peaceful. We went hiking during the day. The trails were steep. We saw some wild animals like deer. I enjoyed being close to nature. It was a break from city life. I felt refreshed.",
        "word_count": 73,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'camping', 'adventurous', 'set up', 'campfire', 'hiking', 'trails', 'steep', 'wild animals', 'nature', 'refreshed'. >Band 5: 'Adventurous', 'refreshed'. Not Band 7: Standard camping vocab.",
        "grammar_reason": "[GRA6] Key evidence: 'near a river', 'during the day', 'being close to nature'. >Band 5: Prepositional phrases and gerunds correct. Not Band 7: Simple sentence structure.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a holiday.\n\nTranscript: I went camping in the forest last month. It was an adventurous trip. We set up a tent near a river. We made a campfire and cooked food. At night, we looked at the stars. It was peaceful. We went hiking during the day. The trails were steep. We saw some wild animals like deer. I enjoyed being close to nature. It was a break from city life. I felt refreshed.\n\nWord Count: 73 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'camping', 'adventurous', 'set up', 'campfire', 'hiking', 'trails', 'steep', 'wild animals', 'nature', 'refreshed'. \n\n>Band 5: 'Adventurous', 'refreshed'.\n\nNot Band 7: Standard camping vocab.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'near a river', 'during the day', 'being close to nature'. \n\n>Band 5: Prepositional phrases and gerunds correct.\n\nNot Band 7: Simple sentence structure.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_257",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a successful person.",
        "transcript_cleaned": "I admire Oprah Winfrey. She is a famous media executive. She faced many hardships in her life. She was poor, but she worked hard. She became a talk show host. Her show was very popular globally. She is also a philanthropist. She gives money to education. She inspires women everywhere. She is a powerful figure. I think she is a role model because she overcame adversity. Her success story is motivating.",
        "word_count": 73,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'media executive', 'hardships', 'host', 'globally', 'philanthropist', 'powerful figure', 'role model', 'overcame', 'adversity', 'motivating'. >Band 5: 'Philanthropist', 'adversity'. Not Band 7: Good range.",
        "grammar_reason": "[GRA6] Key evidence: 'She was poor, but', 'because she overcame'. >Band 5: Compound and complex sentences correct. Not Band 7: Repetitive 'She'.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a successful person.\n\nTranscript: I admire Oprah Winfrey. She is a famous media executive. She faced many hardships in her life. She was poor, but she worked hard. She became a talk show host. Her show was very popular globally. She is also a philanthropist. She gives money to education. She inspires women everywhere. She is a powerful figure. I think she is a role model because she overcame adversity. Her success story is motivating.\n\nWord Count: 73 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'media executive', 'hardships', 'host', 'globally', 'philanthropist', 'powerful figure', 'role model', 'overcame', 'adversity', 'motivating'. \n\n>Band 5: 'Philanthropist', 'adversity'.\n\nNot Band 7: Good range.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'She was poor, but', 'because she overcame'. \n\n>Band 5: Compound and complex sentences correct.\n\nNot Band 7: Repetitive 'She'.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_258",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a piece of news.",
        "transcript_cleaned": "I watched the news about the Olympics. It was held in Tokyo. I saw many athletes competing. I was interested in swimming. My country won a gold medal. It was a proud moment. The news showed the medal ceremony. The athletes looked happy. I think sports events unite people. It promotes peace. I enjoyed watching the highlights. It was inspiring to see their dedication.",
        "word_count": 66,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'Olympics', 'athletes', 'competing', 'gold medal', 'ceremony', 'unite', 'promotes', 'highlights', 'dedication'. >Band 5: 'Unite', 'promotes peace'. Not Band 7: Standard sports vocab.",
        "grammar_reason": "[GRA6] Key evidence: 'It was held', 'inspiring to see'. >Band 5: Passive voice and infinitive subject complement correct. Not Band 7: Simple structure.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a piece of news.\n\nTranscript: I watched the news about the Olympics. It was held in Tokyo. I saw many athletes competing. I was interested in swimming. My country won a gold medal. It was a proud moment. The news showed the medal ceremony. The athletes looked happy. I think sports events unite people. It promotes peace. I enjoyed watching the highlights. It was inspiring to see their dedication.\n\nWord Count: 66 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'Olympics', 'athletes', 'competing', 'gold medal', 'ceremony', 'unite', 'promotes', 'highlights', 'dedication'. \n\n>Band 5: 'Unite', 'promotes peace'.\n\nNot Band 7: Standard sports vocab.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'It was held', 'inspiring to see'. \n\n>Band 5: Passive voice and infinitive subject complement correct.\n\nNot Band 7: Simple structure.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_259",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a gift.",
        "transcript_cleaned": "I gave my father a watch. It was his retirement gift. He worked for 40 years. I wanted to give him something special. The watch is classic and stylish. It has a leather strap. He was emotional when he opened it. He wears it every day. It symbolizes his time and hard work. I saved money for months to buy it. It was expensive but valuable.",
        "word_count": 68,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'retirement', 'special', 'classic', 'stylish', 'leather strap', 'emotional', 'symbolizes', 'valuable'. >Band 5: 'Symbolizes', 'retirement'. Not Band 7: Good range.",
        "grammar_reason": "[GRA6] Key evidence: 'wanted to give', 'when he opened it'. >Band 5: Infinitive and time clause correct. Not Band 7: Short sentences.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a gift.\n\nTranscript: I gave my father a watch. It was his retirement gift. He worked for 40 years. I wanted to give him something special. The watch is classic and stylish. It has a leather strap. He was emotional when he opened it. He wears it every day. It symbolizes his time and hard work. I saved money for months to buy it. It was expensive but valuable.\n\nWord Count: 68 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'retirement', 'special', 'classic', 'stylish', 'leather strap', 'emotional', 'symbolizes', 'valuable'. \n\n>Band 5: 'Symbolizes', 'retirement'.\n\nNot Band 7: Good range.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'wanted to give', 'when he opened it'. \n\n>Band 5: Infinitive and time clause correct.\n\nNot Band 7: Short sentences.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_260",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a game.",
        "transcript_cleaned": "I play basketball with my friends. We play on a public court. It is a fast-paced game. We dribble and shoot the ball. It requires teamwork and coordination. I am not very tall, but I am fast. We play for fun, not competition. It is a good way to stay fit. I usually play on Sunday afternoons. After the game, we are exhausted but happy.",
        "word_count": 67,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'public court', 'fast-paced', 'dribble', 'shoot', 'teamwork', 'coordination', 'competition', 'stay fit', 'exhausted'. >Band 5: 'Fast-paced', 'coordination'. Not Band 7: Standard sports vocab.",
        "grammar_reason": "[GRA6] Key evidence: 'requires teamwork', 'not very tall, but'. >Band 5: Compound sentences correct. Not Band 7: Simple structure.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a game.\n\nTranscript: I play basketball with my friends. We play on a public court. It is a fast-paced game. We dribble and shoot the ball. It requires teamwork and coordination. I am not very tall, but I am fast. We play for fun, not competition. It is a good way to stay fit. I usually play on Sunday afternoons. After the game, we are exhausted but happy.\n\nWord Count: 67 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'public court', 'fast-paced', 'dribble', 'shoot', 'teamwork', 'coordination', 'competition', 'stay fit', 'exhausted'. \n\n>Band 5: 'Fast-paced', 'coordination'.\n\nNot Band 7: Standard sports vocab.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'requires teamwork', 'not very tall, but'. \n\n>Band 5: Compound sentences correct.\n\nNot Band 7: Simple structure.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_261",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a historical building.",
        "transcript_cleaned": "I visited the Tower of London. It is a fortress in London. It has a long history. It was used as a prison. Many famous people were imprisoned there. It is also where the Crown Jewels are kept. They are very shiny and expensive. I saw the Beefeaters, who are the guards. They wear traditional uniforms. The tour was educational. I learned a lot about British history.",
        "word_count": 69,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'fortress', 'prison', 'imprisoned', 'Crown Jewels', 'shiny', 'Beefeaters', 'guards', 'traditional', 'uniforms', 'educational'. >Band 5: 'Fortress', 'imprisoned'. Not Band 7: Good range.",
        "grammar_reason": "[GRA6] Key evidence: 'was used as', 'where the Crown Jewels are', 'who are the guards'. >Band 5: Passive, relative clauses correct. Not Band 7: Simple structure.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a historical building.\n\nTranscript: I visited the Tower of London. It is a fortress in London. It has a long history. It was used as a prison. Many famous people were imprisoned there. It is also where the Crown Jewels are kept. They are very shiny and expensive. I saw the Beefeaters, who are the guards. They wear traditional uniforms. The tour was educational. I learned a lot about British history.\n\nWord Count: 69 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'fortress', 'prison', 'imprisoned', 'Crown Jewels', 'shiny', 'Beefeaters', 'guards', 'traditional', 'uniforms', 'educational'. \n\n>Band 5: 'Fortress', 'imprisoned'.\n\nNot Band 7: Good range.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'was used as', 'where the Crown Jewels are', 'who are the guards'. \n\n>Band 5: Passive, relative clauses correct.\n\nNot Band 7: Simple structure.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_262",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a place.",
        "transcript_cleaned": "I went to a theme park called Disneyland. It is a magical place. There are many rides and attractions. I went on a roller coaster. It was fast and scary. I also met Mickey Mouse. The park is very colorful. There was a parade with floats and music. It was crowded with families. Everyone looked happy. It is a place where dreams come true. I had a wonderful time.",
        "word_count": 71,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'theme park', 'magical', 'rides', 'attractions', 'roller coaster', 'colorful', 'parade', 'floats', 'dreams come true'. >Band 5: 'Attractions', 'floats'. Not Band 7: Good range.",
        "grammar_reason": "[GRA6] Key evidence: 'place where dreams come true', 'There are many'. >Band 5: Relative clause correct. Not Band 7: Simple structure.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a place.\n\nTranscript: I went to a theme park called Disneyland. It is a magical place. There are many rides and attractions. I went on a roller coaster. It was fast and scary. I also met Mickey Mouse. The park is very colorful. There was a parade with floats and music. It was crowded with families. Everyone looked happy. It is a place where dreams come true. I had a wonderful time.\n\nWord Count: 71 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'theme park', 'magical', 'rides', 'attractions', 'roller coaster', 'colorful', 'parade', 'floats', 'dreams come true'. \n\n>Band 5: 'Attractions', 'floats'.\n\nNot Band 7: Good range.\n\n**Idiom present:** Yes\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'place where dreams come true', 'There are many'. \n\n>Band 5: Relative clause correct.\n\nNot Band 7: Simple structure.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_263",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a difficult task.",
        "transcript_cleaned": "I tried to learn knitting. It looked easy, but it was hard. I bought wool and needles. I watched a tutorial online. I tried to make a scarf. I made many mistakes. The stitches were uneven. I had to start over many times. It was frustrating. My grandmother helped me. She showed me the technique. Slowly, I improved. I finished the scarf in a month. I was proud of my persistence.",
        "word_count": 73,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'knitting', 'wool', 'needles', 'tutorial', 'scarf', 'mistakes', 'stitches', 'uneven', 'frustrating', 'technique', 'persistence'. >Band 5: 'Uneven', 'persistence'. Not Band 7: Standard vocab.",
        "grammar_reason": "[GRA6] Key evidence: 'looked easy, but', 'had to start over'. >Band 5: Compound sentences and phrasal verbs correct. Not Band 7: Short sentences.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a difficult task.\n\nTranscript: I tried to learn knitting. It looked easy, but it was hard. I bought wool and needles. I watched a tutorial online. I tried to make a scarf. I made many mistakes. The stitches were uneven. I had to start over many times. It was frustrating. My grandmother helped me. She showed me the technique. Slowly, I improved. I finished the scarf in a month. I was proud of my persistence.\n\nWord Count: 73 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'knitting', 'wool', 'needles', 'tutorial', 'scarf', 'mistakes', 'stitches', 'uneven', 'frustrating', 'technique', 'persistence'. \n\n>Band 5: 'Uneven', 'persistence'.\n\nNot Band 7: Standard vocab.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'looked easy, but', 'had to start over'. \n\n>Band 5: Compound sentences and phrasal verbs correct.\n\nNot Band 7: Short sentences.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_264",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a piece of clothes.",
        "transcript_cleaned": "I have a suit for formal occasions. It is dark blue. I bought it for a wedding. It consists of a jacket and trousers. I wear it with a white shirt and a tie. It makes me look professional. The fabric is high quality. It fits me perfectly. I do not wear it often because it is uncomfortable. However, I think every man needs a good suit. It is stylish.",
        "word_count": 72,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'suit', 'formal occasions', 'consists of', 'trousers', 'tie', 'professional', 'fabric', 'high quality', 'uncomfortable', 'stylish'. >Band 5: 'Consists of', 'fabric'. Not Band 7: Good range.",
        "grammar_reason": "[GRA6] Key evidence: 'because it is uncomfortable', 'makes me look'. >Band 5: Causal and causative structures correct. Not Band 7: Simple structure.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a piece of clothes.\n\nTranscript: I have a suit for formal occasions. It is dark blue. I bought it for a wedding. It consists of a jacket and trousers. I wear it with a white shirt and a tie. It makes me look professional. The fabric is high quality. It fits me perfectly. I do not wear it often because it is uncomfortable. However, I think every man needs a good suit. It is stylish.\n\nWord Count: 72 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'suit', 'formal occasions', 'consists of', 'trousers', 'tie', 'professional', 'fabric', 'high quality', 'uncomfortable', 'stylish'. \n\n>Band 5: 'Consists of', 'fabric'.\n\nNot Band 7: Good range.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'because it is uncomfortable', 'makes me look'. \n\n>Band 5: Causal and causative structures correct.\n\nNot Band 7: Simple structure.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_265",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a difficult decision.",
        "transcript_cleaned": "I had to decide whether to lend money to a friend. He asked me for a large amount. I wanted to help him, but I was worried. He is not good with money. I thought about it for days. I was afraid he would not pay me back. It might ruin our friendship. Finally, I decided to lend him half the amount. He was grateful. He promised to return it. It was a risky decision.",
        "word_count": 78,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'lend', 'amount', 'worried', 'afraid', 'ruin', 'friendship', 'grateful', 'promised', 'return', 'risky decision'. >Band 5: 'Ruin friendship', 'risky'. Not Band 7: Good range.",
        "grammar_reason": "[GRA6] Key evidence: 'whether to lend', 'afraid he would not', 'decided to lend'. >Band 5: Infinitive and modal structures correct. Not Band 7: Short sentences.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a difficult decision.\n\nTranscript: I had to decide whether to lend money to a friend. He asked me for a large amount. I wanted to help him, but I was worried. He is not good with money. I thought about it for days. I was afraid he would not pay me back. It might ruin our friendship. Finally, I decided to lend him half the amount. He was grateful. He promised to return it. It was a risky decision.\n\nWord Count: 78 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'lend', 'amount', 'worried', 'afraid', 'ruin', 'friendship', 'grateful', 'promised', 'return', 'risky decision'. \n\n>Band 5: 'Ruin friendship', 'risky'.\n\nNot Band 7: Good range.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'whether to lend', 'afraid he would not', 'decided to lend'. \n\n>Band 5: Infinitive and modal structures correct.\n\nNot Band 7: Short sentences.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_266",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a useful skill.",
        "transcript_cleaned": "I learned how to swim. It is a life skill. I took lessons at a local pool. The instructor was patient. I learned different strokes like freestyle and breaststroke. Breathing was the hardest part. I swallowed water many times. But I kept trying. Now I can swim laps. It builds endurance. I feel safe in the water. I enjoy swimming in the ocean on holidays. It is refreshing.",
        "word_count": 69,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'life skill', 'instructor', 'patient', 'strokes', 'freestyle', 'breaststroke', 'swallowed', 'laps', 'endurance', 'refreshing'. >Band 5: 'Strokes', 'endurance'. Not Band 7: Good range.",
        "grammar_reason": "[GRA6] Key evidence: 'how to swim', 'hardest part', 'I enjoy swimming'. >Band 5: Gerunds and superlatives correct. Not Band 7: Simple structure.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a useful skill.\n\nTranscript: I learned how to swim. It is a life skill. I took lessons at a local pool. The instructor was patient. I learned different strokes like freestyle and breaststroke. Breathing was the hardest part. I swallowed water many times. But I kept trying. Now I can swim laps. It builds endurance. I feel safe in the water. I enjoy swimming in the ocean on holidays. It is refreshing.\n\nWord Count: 69 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'life skill', 'instructor', 'patient', 'strokes', 'freestyle', 'breaststroke', 'swallowed', 'laps', 'endurance', 'refreshing'. \n\n>Band 5: 'Strokes', 'endurance'.\n\nNot Band 7: Good range.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'how to swim', 'hardest part', 'I enjoy swimming'. \n\n>Band 5: Gerunds and superlatives correct.\n\nNot Band 7: Simple structure.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_267",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a historical place.",
        "transcript_cleaned": "I visited the pyramids in Egypt. They are ancient monuments. They are located in the desert. They were tombs for kings. The structures are geometric. They are very tall. I wondered how they built them. It must have been difficult. I rode a camel there. It was a unique experience. I bought a small statue as a souvenir. The history of Egypt is fascinating. I learned a lot.",
        "word_count": 68,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'ancient', 'monuments', 'located', 'desert', 'tombs', 'structures', 'geometric', 'camel', 'unique', 'souvenir', 'fascinating'. >Band 5: 'Geometric', 'monuments'. Not Band 7: Good range.",
        "grammar_reason": "[GRA6] Key evidence: 'must have been', 'how they built them'. >Band 5: Modals of deduction and indirect questions correct. Not Band 7: Short sentences.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a historical place.\n\nTranscript: I visited the pyramids in Egypt. They are ancient monuments. They are located in the desert. They were tombs for kings. The structures are geometric. They are very tall. I wondered how they built them. It must have been difficult. I rode a camel there. It was a unique experience. I bought a small statue as a souvenir. The history of Egypt is fascinating. I learned a lot.\n\nWord Count: 68 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'ancient', 'monuments', 'located', 'desert', 'tombs', 'structures', 'geometric', 'camel', 'unique', 'souvenir', 'fascinating'. \n\n>Band 5: 'Geometric', 'monuments'.\n\nNot Band 7: Good range.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'must have been', 'how they built them'. \n\n>Band 5: Modals of deduction and indirect questions correct.\n\nNot Band 7: Short sentences.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_268",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a place.",
        "transcript_cleaned": "I went to a zoo in my city. It has many animals from different countries. I saw lions and elephants. They were in large enclosures. The zoo tries to mimic their natural habitat. I learned about conservation. The zoo protects endangered species. I watched a seal show. It was entertaining. I spent the afternoon there. It is a good place for education. I think animals should be free, though.",
        "word_count": 69,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'enclosures', 'mimic', 'natural habitat', 'conservation', 'endangered species', 'entertaining', 'education'. >Band 5: 'Mimic', 'conservation'. Not Band 7: Good range.",
        "grammar_reason": "[GRA6] Key evidence: 'animals from different countries', 'should be free'. >Band 5: Prepositional phrases and passive voice correct. Not Band 7: Simple structure.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a place.\n\nTranscript: I went to a zoo in my city. It has many animals from different countries. I saw lions and elephants. They were in large enclosures. The zoo tries to mimic their natural habitat. I learned about conservation. The zoo protects endangered species. I watched a seal show. It was entertaining. I spent the afternoon there. It is a good place for education. I think animals should be free, though.\n\nWord Count: 69 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'enclosures', 'mimic', 'natural habitat', 'conservation', 'endangered species', 'entertaining', 'education'. \n\n>Band 5: 'Mimic', 'conservation'.\n\nNot Band 7: Good range.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'animals from different countries', 'should be free'. \n\n>Band 5: Prepositional phrases and passive voice correct.\n\nNot Band 7: Simple structure.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_269",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a party.",
        "transcript_cleaned": "I went to a farewell party for my colleague. He was leaving the company. We had a party in the office. We ordered pizza and drinks. We decorated his desk. We gave him a card and a gift. Everyone signed the card. We shared memories of working together. It was a bit sad, but we wished him luck. It was a nice send-off. I will miss him.",
        "word_count": 68,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'farewell party', 'colleague', 'leaving', 'ordered', 'decorated', 'signed', 'memories', 'wished him luck', 'send-off'. >Band 5: 'Send-off', 'colleague'. Not Band 7: Good range.",
        "grammar_reason": "[GRA6] Key evidence: 'memories of working', 'bit sad, but'. >Band 5: Gerunds and compound sentences correct. Not Band 7: Short sentences.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a party.\n\nTranscript: I went to a farewell party for my colleague. He was leaving the company. We had a party in the office. We ordered pizza and drinks. We decorated his desk. We gave him a card and a gift. Everyone signed the card. We shared memories of working together. It was a bit sad, but we wished him luck. It was a nice send-off. I will miss him.\n\nWord Count: 68 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'farewell party', 'colleague', 'leaving', 'ordered', 'decorated', 'signed', 'memories', 'wished him luck', 'send-off'. \n\n>Band 5: 'Send-off', 'colleague'.\n\nNot Band 7: Good range.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'memories of working', 'bit sad, but'. \n\n>Band 5: Gerunds and compound sentences correct.\n\nNot Band 7: Short sentences.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_270",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a difficult task.",
        "transcript_cleaned": "I had to assemble a bookshelf. I bought it from IKEA. It came in a flat box. There were many pieces of wood and screws. The instructions were confusing. I made a mistake and had to unscrew it. It took three hours. I was frustrated. My hands hurt. But finally, I finished it. It looked good in my room. I put my books on it. I felt a sense of achievement.",
        "word_count": 72,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'assemble', 'bookshelf', 'flat box', 'screws', 'instructions', 'confusing', 'mistake', 'unscrew', 'frustrated', 'achievement'. >Band 5: 'Assemble', 'unscrew'. Not Band 7: Good range.",
        "grammar_reason": "[GRA6] Key evidence: 'pieces of wood', 'mistake and had to'. >Band 5: Prepositional phrases and compound verbs correct. Not Band 7: Simple structure.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a difficult task.\n\nTranscript: I had to assemble a bookshelf. I bought it from IKEA. It came in a flat box. There were many pieces of wood and screws. The instructions were confusing. I made a mistake and had to unscrew it. It took three hours. I was frustrated. My hands hurt. But finally, I finished it. It looked good in my room. I put my books on it. I felt a sense of achievement.\n\nWord Count: 72 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'assemble', 'bookshelf', 'flat box', 'screws', 'instructions', 'confusing', 'mistake', 'unscrew', 'frustrated', 'achievement'. \n\n>Band 5: 'Assemble', 'unscrew'.\n\nNot Band 7: Good range.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'pieces of wood', 'mistake and had to'. \n\n>Band 5: Prepositional phrases and compound verbs correct.\n\nNot Band 7: Simple structure.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_271",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a useful skill.",
        "transcript_cleaned": "I learned how to budget my money. It is a financial skill. I used to spend too much. I was always broke. I started writing down my expenses. I tracked where my money went. I set limits for spending. It was hard at first. But now I have savings. I can buy things I need. Being financially responsible is important. It gives me peace of mind.",
        "word_count": 67,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'budget', 'financial', 'spend', 'broke', 'expenses', 'tracked', 'limits', 'savings', 'financially responsible', 'peace of mind'. >Band 5: 'Peace of mind', 'tracked'. Not Band 7: Good range.",
        "grammar_reason": "[GRA6] Key evidence: 'how to budget', 'where my money went'. >Band 5: Infinitives and noun clauses correct. Not Band 7: Short sentences.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a useful skill.\n\nTranscript: I learned how to budget my money. It is a financial skill. I used to spend too much. I was always broke. I started writing down my expenses. I tracked where my money went. I set limits for spending. It was hard at first. But now I have savings. I can buy things I need. Being financially responsible is important. It gives me peace of mind.\n\nWord Count: 67 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'budget', 'financial', 'spend', 'broke', 'expenses', 'tracked', 'limits', 'savings', 'financially responsible', 'peace of mind'. \n\n>Band 5: 'Peace of mind', 'tracked'.\n\nNot Band 7: Good range.\n\n**Idiom present:** Yes\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'how to budget', 'where my money went'. \n\n>Band 5: Infinitives and noun clauses correct.\n\nNot Band 7: Short sentences.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_272",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a person you admire.",
        "transcript_cleaned": "I admire my friend Anna. She is a talented musician. She plays the violin beautifully. She practices for hours every day. She is very dedicated. She performs in concerts. I have seen her on stage. She looks confident. She also teaches music to children. She is patient and kind. She inspires me to work hard at my hobbies. I think she has a bright future.",
        "word_count": 66,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'admire', 'talented', 'musician', 'violin', 'practices', 'dedicated', 'performs', 'concerts', 'stage', 'confident', 'inspires', 'bright future'. >Band 5: 'Bright future', 'dedicated'. Not Band 7: Standard vocab.",
        "grammar_reason": "[GRA6] Key evidence: 'she has a bright future', 'inspires me to work'. >Band 5: Correct sentence structures. Not Band 7: Very repetitive 'She'.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a person you admire.\n\nTranscript: I admire my friend Anna. She is a talented musician. She plays the violin beautifully. She practices for hours every day. She is very dedicated. She performs in concerts. I have seen her on stage. She looks confident. She also teaches music to children. She is patient and kind. She inspires me to work hard at my hobbies. I think she has a bright future.\n\nWord Count: 66 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'admire', 'talented', 'musician', 'violin', 'practices', 'dedicated', 'performs', 'concerts', 'stage', 'confident', 'inspires', 'bright future'. \n\n>Band 5: 'Bright future', 'dedicated'.\n\nNot Band 7: Standard vocab.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'she has a bright future', 'inspires me to work'. \n\n>Band 5: Correct sentence structures.\n\nNot Band 7: Very repetitive 'She'.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_273",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a piece of clothes.",
        "transcript_cleaned": "I have a woolen sweater. My mother knitted it for me. It is green with a pattern. It is very warm. I wear it in winter. It is comfortable and cozy. It fits me well. I wear it when I go out or stay home. It is a bit old now, but I still love it. It has sentimental value. It reminds me of my mother's love. I will keep it forever.",
        "word_count": 73,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'woolen', 'sweater', 'knitted', 'pattern', 'cozy', 'fits', 'sentimental value', 'reminds', 'forever'. >Band 5: 'Sentimental value', 'cozy'. Not Band 7: Good range.",
        "grammar_reason": "[GRA6] Key evidence: 'when I go out', 'bit old now, but'. >Band 5: Time clauses and compound sentences correct. Not Band 7: Simple structure.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a piece of clothes.\n\nTranscript: I have a woolen sweater. My mother knitted it for me. It is green with a pattern. It is very warm. I wear it in winter. It is comfortable and cozy. It fits me well. I wear it when I go out or stay home. It is a bit old now, but I still love it. It has sentimental value. It reminds me of my mother's love. I will keep it forever.\n\nWord Count: 73 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'woolen', 'sweater', 'knitted', 'pattern', 'cozy', 'fits', 'sentimental value', 'reminds', 'forever'. \n\n>Band 5: 'Sentimental value', 'cozy'.\n\nNot Band 7: Good range.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'when I go out', 'bit old now, but'. \n\n>Band 5: Time clauses and compound sentences correct.\n\nNot Band 7: Simple structure.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_274",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a historical place.",
        "transcript_cleaned": "I visited a castle in Germany. It is called Neuschwanstein. It looks like a fairytale castle. It is built on a hill. The architecture is romantic. I took a bus to get there. The interior was lavish. There were paintings and gold decorations. It was built by a king who was eccentric. I loved the view from the balcony. It was breathtaking. It is a famous landmark. I took many pictures.",
        "word_count": 71,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'castle', 'fairytale', 'architecture', 'romantic', 'interior', 'lavish', 'decorations', 'eccentric', 'balcony', 'breathtaking', 'landmark'. >Band 5: 'Lavish', 'eccentric'. Not Band 7: Good range.",
        "grammar_reason": "[GRA6] Key evidence: 'king who was eccentric', 'took a bus to get'. >Band 5: Relative clauses and infinitive purpose correct. Not Band 7: Short sentences.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a historical place.\n\nTranscript: I visited a castle in Germany. It is called Neuschwanstein. It looks like a fairytale castle. It is built on a hill. The architecture is romantic. I took a bus to get there. The interior was lavish. There were paintings and gold decorations. It was built by a king who was eccentric. I loved the view from the balcony. It was breathtaking. It is a famous landmark. I took many pictures.\n\nWord Count: 71 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'castle', 'fairytale', 'architecture', 'romantic', 'interior', 'lavish', 'decorations', 'eccentric', 'balcony', 'breathtaking', 'landmark'. \n\n>Band 5: 'Lavish', 'eccentric'.\n\nNot Band 7: Good range.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'king who was eccentric', 'took a bus to get'. \n\n>Band 5: Relative clauses and infinitive purpose correct.\n\nNot Band 7: Short sentences.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_275",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a difficult decision.",
        "transcript_cleaned": "I had to decide where to go for my holiday. I wanted to go to the beach or the mountains. My friends wanted the beach. My family wanted the mountains. I was in the middle. I weighed the options. The beach is relaxing, but the mountains are adventurous. Finally, I chose the beach. I thought it would be more fun. We swam and sunbathed. I think I made the right decision.",
        "word_count": 71,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'decide', 'options', 'relaxing', 'adventurous', 'chose', 'sunbathed', 'right decision'. >Band 5: 'Adventurous', 'sunbathed'. Not Band 7: Standard vocab.",
        "grammar_reason": "[GRA6] Key evidence: 'where to go', 'thought it would be'. >Band 5: Noun clauses and future in past correct. Not Band 7: Simple structure.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a difficult decision.\n\nTranscript: I had to decide where to go for my holiday. I wanted to go to the beach or the mountains. My friends wanted the beach. My family wanted the mountains. I was in the middle. I weighed the options. The beach is relaxing, but the mountains are adventurous. Finally, I chose the beach. I thought it would be more fun. We swam and sunbathed. I think I made the right decision.\n\nWord Count: 71 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'decide', 'options', 'relaxing', 'adventurous', 'chose', 'sunbathed', 'right decision'. \n\n>Band 5: 'Adventurous', 'sunbathed'.\n\nNot Band 7: Standard vocab.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'where to go', 'thought it would be'. \n\n>Band 5: Noun clauses and future in past correct.\n\nNot Band 7: Simple structure.\n\n**Micro flaws identified:**\n- none significant"
    }
]

with open(OUTPUT_FILE, 'a') as f:
    for sample in samples:
        json.dump(sample, f)
        f.write('\n')
