import json

OUTPUT_FILE = 'ielts-data/phase3/v76_review_output/jules1/jules1_batch01.jsonl'

samples = [
    {
        "sample_id": "syn_p2_v4_g4_014",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a memorable journey you made.",
        "transcript_cleaned": "I want talk about my trip to mountain. I go there with my family. We drive car for long time. Maybe five hours. The road is bad. Many holes. I feel tired in car. But mountain is beautiful. Big trees and green grass. We stop for lunch. We eat sandwiches. My mother make them. They are good. We see some animals. I think it is monkey. I take photo. At night we sleep in tent. It is cold but I like. We make fire. I remember this trip because I am happy with family.",
        "word_count": 92,
        "response_type": "long_turn",
        "micro_flaws": [
            "missing preposition: 'want talk' -> 'want to talk'",
            "article error: 'to mountain' -> 'to the mountain'",
            "verb tense: 'go' -> 'went'",
            "article error: 'drive car' -> 'drove the car' or 'drove a car'",
            "verb tense: 'is bad' -> 'was bad'",
            "fragment: 'Many holes' -> 'There were many holes'",
            "verb tense: 'feel' -> 'felt'",
            "article error: 'in car' -> 'in the car'",
            "verb tense: 'is beautiful' -> 'was beautiful'",
            "fragment: 'Big trees...' -> 'There were big trees...'",
            "verb tense: 'stop' -> 'stopped'",
            "verb tense: 'eat' -> 'ate'",
            "verb tense: 'make' -> 'made'",
            "verb tense: 'are' -> 'were'",
            "verb tense: 'see' -> 'saw'",
            "verb tense: 'take' -> 'took'",
            "article error: 'take photo' -> 'took a photo'",
            "verb tense: 'sleep' -> 'slept'",
            "word choice: 'I like' -> 'I liked it'",
            "verb tense: 'make' -> 'made'",
            "verb tense: 'am happy' -> 'was happy'"
        ],
        "grammar_profile": {
            "complexity": "low",
            "accuracy": "low",
            "flexibility": "low"
        },
        "vocab_reason": "[LR4] Key evidence: 'trip', 'mountain', 'car', 'lunch', 'sandwiches', 'monkey', 'tent'. >Band 3: Tells a story with basic words. Not Band 5: 'Big trees', 'good', 'happy' are very basic descriptors.",
        "grammar_reason": "[GRA4] Key evidence: Simple sentences mostly. Wrong tenses. 'I go', 'We drive'. >Band 3: Simple sentences. Not Band 5: Past tense is systematically incorrect.",
        "vocabulary": 4,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a memorable journey you made.\n\nTranscript: I want talk about my trip to mountain. I go there with my family. We drive car for long time. Maybe five hours. The road is bad. Many holes. I feel tired in car. But mountain is beautiful. Big trees and green grass. We stop for lunch. We eat sandwiches. My mother make them. They are good. We see some animals. I think it is monkey. I take photo. At night we sleep in tent. It is cold but I like. We make fire. I remember this trip because I am happy with family.\n\nWord Count: 92 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Key evidence: 'trip', 'mountain', 'car', 'lunch', 'sandwiches', 'monkey', 'tent'. \n\n>Band 3: Tells a story with basic words.\n\nNot Band 5: 'Big trees', 'good', 'happy' are very basic descriptors.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Key evidence: Simple sentences mostly. Wrong tenses. 'I go', 'We drive'. \n\n>Band 3: Simple sentences.\n\nNot Band 5: Past tense is systematically incorrect.\n\n**Micro flaws identified:**\n- verb tense: 'go', 'drive', 'is', 'feel', 'stop', 'eat', 'make', 'see', 'take', 'sleep'\n- missing preposition: 'want talk'\n- article error: 'to mountain', 'drive car', 'in car'"
    },
    {
        "sample_id": "syn_p2_v4_g4_015",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a book you read recently.",
        "transcript_cleaned": "The book name is Harry Potter. I read it last month. It is very famous book. The story about a boy. He is wizard. He have magic power. He go to school for magic. The school is big castle. I like Harry because he is brave. He fight bad man name Voldemort. The book is long. Many pages. But I read fast. It is interesting. My friend give it to me. I want read next book too. It is best book for me. I learn some English words from it.",
        "word_count": 92,
        "response_type": "long_turn",
        "micro_flaws": [
            "possessive error: 'book name' -> 'book\\'s name'",
            "article error: 'is very famous book' -> 'is a very famous book'",
            "missing verb: 'The story about' -> 'The story is about'",
            "article error: 'is wizard' -> 'is a wizard'",
            "subject-verb agreement: 'He have' -> 'He has'",
            "subject-verb agreement: 'He go' -> 'He goes' (or 'went')",
            "article error: 'is big castle' -> 'is a big castle'",
            "subject-verb agreement: 'He fight' -> 'He fights'",
            "article error: 'bad man' -> 'a bad man'",
            "verb tense: 'give' -> 'gave'",
            "verb pattern: 'want read' -> 'want to read'",
            "article error: 'is best book' -> 'is the best book'"
        ],
        "grammar_profile": {
            "complexity": "low",
            "accuracy": "low",
            "flexibility": "low"
        },
        "vocab_reason": "[LR4] Key evidence: 'book', 'story', 'boy', 'wizard', 'magic', 'school', 'castle'. >Band 3: Topic clear. Not Band 5: Repetitive 'book'. Basic adjectives 'big', 'bad', 'long'.",
        "grammar_reason": "[GRA4] Key evidence: Simple sentences. 'He have', 'He go'. >Band 3: Simple sentences attempted. Not Band 5: Subject-verb agreement errors are frequent ('He have').",
        "vocabulary": 4,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a book you read recently.\n\nTranscript: The book name is Harry Potter. I read it last month. It is very famous book. The story about a boy. He is wizard. He have magic power. He go to school for magic. The school is big castle. I like Harry because he is brave. He fight bad man name Voldemort. The book is long. Many pages. But I read fast. It is interesting. My friend give it to me. I want read next book too. It is best book for me. I learn some English words from it.\n\nWord Count: 92 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Key evidence: 'book', 'story', 'boy', 'wizard', 'magic', 'school', 'castle'. \n\n>Band 3: Topic clear.\n\nNot Band 5: Repetitive 'book'. Basic adjectives 'big', 'bad', 'long'.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Key evidence: Simple sentences. 'He have', 'He go'. \n\n>Band 3: Simple sentences attempted.\n\nNot Band 5: Subject-verb agreement errors are frequent ('He have').\n\n**Micro flaws identified:**\n- possessive error: 'book name'\n- article error: 'is famous book', 'is wizard', 'is big castle', 'is best book'\n- subject-verb agreement: 'He have', 'He go', 'He fight'\n- verb pattern: 'want read'"
    },
    {
        "sample_id": "syn_p2_v4_g4_016",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a restaurant you like to eat at.",
        "transcript_cleaned": "I like eat at KFC. It is fast food place. It is near my school. I go there often. The chicken is very tasty. I like it much. It is crispy. I eat with chips and drink coke. The price is cheap. Not expensive. Many students go there. We sit and talk. The place is clean. But sometimes very noisy. The workers are fast. They give food quickly. I like this place because I love chicken. It is good for lunch. I feel full after eat.",
        "word_count": 89,
        "response_type": "long_turn",
        "micro_flaws": [
            "verb pattern: 'like eat' -> 'like eating' or 'like to eat'",
            "article error: 'is fast food place' -> 'is a fast food place'",
            "word choice: 'like it much' -> 'like it a lot'",
            "fragment: 'Not expensive' -> 'It is not expensive'",
            "preposition/gerund: 'after eat' -> 'after eating'"
        ],
        "grammar_profile": {
            "complexity": "low",
            "accuracy": "low",
            "flexibility": "low"
        },
        "vocab_reason": "[LR4] Key evidence: 'fast food', 'chicken', 'tasty', 'chips', 'coke', 'price', 'cheap'. >Band 3: Food context clear. Not Band 5: Very common brand name 'KFC' used as description. Basic words 'good', 'clean', 'fast'.",
        "grammar_reason": "[GRA4] Key evidence: Simple sentences mostly correct but very short. 'The chicken is tasty'. >Band 3: Simple sentences. Not Band 5: 'Like eat', 'after eat' are basic errors.",
        "vocabulary": 4,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a restaurant you like to eat at.\n\nTranscript: I like eat at KFC. It is fast food place. It is near my school. I go there often. The chicken is very tasty. I like it much. It is crispy. I eat with chips and drink coke. The price is cheap. Not expensive. Many students go there. We sit and talk. The place is clean. But sometimes very noisy. The workers are fast. They give food quickly. I like this place because I love chicken. It is good for lunch. I feel full after eat.\n\nWord Count: 89 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Key evidence: 'fast food', 'chicken', 'tasty', 'chips', 'coke', 'price', 'cheap'. \n\n>Band 3: Food context clear.\n\nNot Band 5: Very common brand name 'KFC' used as description. Basic words 'good', 'clean', 'fast'.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Key evidence: Simple sentences mostly correct but very short. 'The chicken is tasty'. \n\n>Band 3: Simple sentences.\n\nNot Band 5: 'Like eat', 'after eat' are basic errors.\n\n**Micro flaws identified:**\n- verb pattern: 'like eat'\n- article error: 'is fast food place'\n- preposition/gerund: 'after eat'"
    },
    {
        "sample_id": "syn_p2_v4_g4_017",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a skill you would like to learn.",
        "transcript_cleaned": "I want learn play guitar. I like music very much. Guitar sound is beautiful. My friend play guitar well. He teach me a little. It is difficult for my fingers. But I want try. If I play guitar, I can sing song. I can play for my family. I need buy a guitar first. It cost money. Maybe I save money to buy. I practice every day. I think it is cool skill. Girls like boy play guitar. I hope I can learn fast.",
        "word_count": 87,
        "response_type": "long_turn",
        "micro_flaws": [
            "verb pattern: 'want learn' -> 'want to learn'",
            "verb pattern: 'learn play' -> 'learn to play'",
            "article error: 'Guitar sound' -> 'The guitar sound'",
            "subject-verb agreement: 'friend play' -> 'friend plays'",
            "subject-verb agreement: 'He teach' -> 'He teaches'",
            "verb pattern: 'want try' -> 'want to try'",
            "article error: 'sing song' -> 'sing songs' or 'sing a song'",
            "verb pattern: 'need buy' -> 'need to buy'",
            "subject-verb agreement: 'It cost' -> 'It costs'",
            "article error: 'is cool skill' -> 'is a cool skill'",
            "grammar/clarity: 'Girls like boy play guitar' -> 'Girls like boys who play guitar'"
        ],
        "grammar_profile": {
            "complexity": "low",
            "accuracy": "low",
            "flexibility": "low"
        },
        "vocab_reason": "[LR4] Key evidence: 'guitar', 'music', 'sound', 'fingers', 'sing', 'money', 'practice'. >Band 3: Topic clear. Not Band 5: 'Cool skill' is basic. 'Sound is beautiful' is simple.",
        "grammar_reason": "[GRA4] Key evidence: Simple sentences. 'I want learn'. >Band 3: Simple sentences. Not Band 5: Multiple verb pattern errors ('want learn', 'need buy') and agreement errors ('friend play').",
        "vocabulary": 4,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a skill you would like to learn.\n\nTranscript: I want learn play guitar. I like music very much. Guitar sound is beautiful. My friend play guitar well. He teach me a little. It is difficult for my fingers. But I want try. If I play guitar, I can sing song. I can play for my family. I need buy a guitar first. It cost money. Maybe I save money to buy. I practice every day. I think it is cool skill. Girls like boy play guitar. I hope I can learn fast.\n\nWord Count: 87 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Key evidence: 'guitar', 'music', 'sound', 'fingers', 'sing', 'money', 'practice'. \n\n>Band 3: Topic clear.\n\nNot Band 5: 'Cool skill' is basic. 'Sound is beautiful' is simple.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Key evidence: Simple sentences. 'I want learn'. \n\n>Band 3: Simple sentences.\n\nNot Band 5: Multiple verb pattern errors ('want learn', 'need buy') and agreement errors ('friend play').\n\n**Micro flaws identified:**\n- verb pattern: 'want learn', 'learn play', 'want try', 'need buy'\n- subject-verb agreement: 'friend play', 'He teach', 'It cost'\n- article error: 'Guitar sound', 'is cool skill'"
    },
    {
        "sample_id": "syn_p2_v4_g4_018",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a childhood memory.",
        "transcript_cleaned": "I remember when I am small. Maybe five years old. I play in garden with dog. My dog is black. One day I fall down. I cry very loud. My mother come and help me. She give me candy. I stop cry. I am happy again. Also I remember first day school. I am scared. I not want go. But teacher is nice. I make new friend. We play toy together. It is good time. I miss my childhood. No work, only play.",
        "word_count": 89,
        "response_type": "long_turn",
        "micro_flaws": [
            "verb tense: 'am small' -> 'was small'",
            "verb tense: 'play' -> 'played'",
            "verb tense: 'fall' -> 'fell'",
            "verb tense: 'cry' -> 'cried'",
            "verb tense: 'come' -> 'came'",
            "verb tense: 'give' -> 'gave'",
            "verb pattern: 'stop cry' -> 'stopped crying'",
            "verb tense: 'am happy' -> 'was happy'",
            "article error: 'first day school' -> 'first day of school' or 'the first day of school'",
            "verb tense: 'am scared' -> 'was scared'",
            "negative structure/tense: 'not want go' -> 'did not want to go'",
            "verb tense: 'make' -> 'made'",
            "plural error: 'make new friend' -> 'made a new friend'",
            "plural error: 'play toy' -> 'played with toys'",
            "article error: 'is good time' -> 'was a good time'"
        ],
        "grammar_profile": {
            "complexity": "low",
            "accuracy": "low",
            "flexibility": "low"
        },
        "vocab_reason": "[LR4] Key evidence: 'small', 'garden', 'dog', 'fall', 'cry', 'candy', 'school', 'scared'. >Band 3: Tells story. Not Band 5: Basic emotional words 'happy', 'scared', 'nice'.",
        "grammar_reason": "[GRA4] Key evidence: Simple sentences. Wrong tenses throughout. >Band 3: Simple sentences. Not Band 5: Past tense almost completely absent ('I am small', 'I play'). 'I not want go' is Band 4.",
        "vocabulary": 4,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a childhood memory.\n\nTranscript: I remember when I am small. Maybe five years old. I play in garden with dog. My dog is black. One day I fall down. I cry very loud. My mother come and help me. She give me candy. I stop cry. I am happy again. Also I remember first day school. I am scared. I not want go. But teacher is nice. I make new friend. We play toy together. It is good time. I miss my childhood. No work, only play.\n\nWord Count: 89 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Key evidence: 'small', 'garden', 'dog', 'fall', 'cry', 'candy', 'school', 'scared'. \n\n>Band 3: Tells story.\n\nNot Band 5: Basic emotional words 'happy', 'scared', 'nice'.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Key evidence: Simple sentences. Wrong tenses throughout. \n\n>Band 3: Simple sentences.\n\nNot Band 5: Past tense almost completely absent ('I am small', 'I play'). 'I not want go' is Band 4.\n\n**Micro flaws identified:**\n- verb tense: 'am', 'play', 'fall', 'cry', 'come', 'give', 'make'\n- verb pattern: 'stop cry', 'not want go'\n- plural error: 'toy', 'friend'"
    },
    {
        "sample_id": "syn_p2_v4_g4_019",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a photograph you like.",
        "transcript_cleaned": "I like photo of my family. We take it last year. In the photo, there is my father, mother and me. Also my sister. We stand in front of house. We smile. The weather is sunny. I wear blue shirt. My mother wear red dress. She look beautiful. This photo is on wall in living room. I see it every day. I like it because we are together. We look happy. It is good memory. I want keep this photo forever. It is special for me.",
        "word_count": 91,
        "response_type": "long_turn",
        "micro_flaws": [
            "article error: 'like photo' -> 'like a photo' or 'the photo'",
            "verb tense: 'take' -> 'took'",
            "verb tense: 'stand' -> 'are standing' or 'stood'",
            "article error: 'front of house' -> 'front of the house'",
            "verb tense: 'smile' -> 'are smiling' or 'smiled'",
            "article error: 'wear blue shirt' -> 'am wearing a blue shirt'",
            "subject-verb agreement: 'mother wear' -> 'mother is wearing' or 'wears'",
            "subject-verb agreement: 'She look' -> 'She looks'",
            "article error: 'on wall' -> 'on the wall'",
            "article error: 'is good memory' -> 'is a good memory'",
            "verb pattern: 'want keep' -> 'want to keep'"
        ],
        "grammar_profile": {
            "complexity": "low",
            "accuracy": "low",
            "flexibility": "low"
        },
        "vocab_reason": "[LR4] Key evidence: 'photo', 'family', 'house', 'smile', 'shirt', 'dress', 'wall'. >Band 3: Describes image. Not Band 5: Colors 'blue', 'red' and 'beautiful' are very basic.",
        "grammar_reason": "[GRA4] Key evidence: Simple sentences. 'We take', 'She look'. >Band 3: Simple sentences. Not Band 5: Incorrect tense/aspect for describing photo ('We stand' vs 'We are standing'). Agreement errors ('She look').",
        "vocabulary": 4,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a photograph you like.\n\nTranscript: I like photo of my family. We take it last year. In the photo, there is my father, mother and me. Also my sister. We stand in front of house. We smile. The weather is sunny. I wear blue shirt. My mother wear red dress. She look beautiful. This photo is on wall in living room. I see it every day. I like it because we are together. We look happy. It is good memory. I want keep this photo forever. It is special for me.\n\nWord Count: 91 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Key evidence: 'photo', 'family', 'house', 'smile', 'shirt', 'dress', 'wall'. \n\n>Band 3: Describes image.\n\nNot Band 5: Colors 'blue', 'red' and 'beautiful' are very basic.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Key evidence: Simple sentences. 'We take', 'She look'. \n\n>Band 3: Simple sentences.\n\nNot Band 5: Incorrect tense/aspect for describing photo ('We stand' vs 'We are standing'). Agreement errors ('She look').\n\n**Micro flaws identified:**\n- verb tense: 'take', 'stand', 'smile', 'wear'\n- subject-verb agreement: 'She look', 'mother wear'\n- article error: 'photo', 'house', 'blue shirt', 'wall'\n- verb pattern: 'want keep'"
    },
    {
        "sample_id": "syn_p2_v4_g4_020",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a piece of clothing you like.",
        "transcript_cleaned": "I like my jacket. It is leather jacket. The color is black. I buy it in mall two years ago. It is expensive but I like. It is warm. I wear it in winter. It fit me very well. It have many pockets. I put my phone in pocket. My friends say it is cool. I feel strong when I wear it. I clean it sometimes. I want buy another one, maybe brown color. But I no have money now. This jacket is my favorite thing.",
        "word_count": 89,
        "response_type": "long_turn",
        "micro_flaws": [
            "article error: 'is leather jacket' -> 'is a leather jacket'",
            "verb tense: 'buy' -> 'bought'",
            "word choice: 'I like' -> 'I like it'",
            "subject-verb agreement: 'It fit' -> 'It fits'",
            "subject-verb agreement: 'It have' -> 'It has'",
            "article error: 'in pocket' -> 'in the pocket'",
            "verb pattern: 'want buy' -> 'want to buy'",
            "negative structure: 'I no have' -> 'I do not have'"
        ],
        "grammar_profile": {
            "complexity": "low",
            "accuracy": "low",
            "flexibility": "low"
        },
        "vocab_reason": "[LR4] Key evidence: 'jacket', 'leather', 'black', 'mall', 'warm', 'winter', 'pockets'. >Band 3: Clothing words used. Not Band 5: 'Cool' and 'strong' are basic. 'Brown color' is redundant.",
        "grammar_reason": "[GRA4] Key evidence: Simple sentences. 'It fit', 'It have'. >Band 3: Simple sentences. Not Band 5: 'I no have' is a classic low-band error. Frequent agreement errors.",
        "vocabulary": 4,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a piece of clothing you like.\n\nTranscript: I like my jacket. It is leather jacket. The color is black. I buy it in mall two years ago. It is expensive but I like. It is warm. I wear it in winter. It fit me very well. It have many pockets. I put my phone in pocket. My friends say it is cool. I feel strong when I wear it. I clean it sometimes. I want buy another one, maybe brown color. But I no have money now. This jacket is my favorite thing.\n\nWord Count: 89 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Key evidence: 'jacket', 'leather', 'black', 'mall', 'warm', 'winter', 'pockets'. \n\n>Band 3: Clothing words used.\n\nNot Band 5: 'Cool' and 'strong' are basic. 'Brown color' is redundant.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Key evidence: Simple sentences. 'It fit', 'It have'. \n\n>Band 3: Simple sentences.\n\nNot Band 5: 'I no have' is a classic low-band error. Frequent agreement errors.\n\n**Micro flaws identified:**\n- article error: 'is leather jacket', 'in pocket'\n- verb tense: 'buy'\n- subject-verb agreement: 'It fit', 'It have'\n- negative structure: 'I no have'\n- verb pattern: 'want buy'"
    },
    {
        "sample_id": "syn_p2_v4_g4_021",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a problem you solved.",
        "transcript_cleaned": "I have problem with my phone. It stop working. Screen is black. I cannot call friend. I am worried. I try open it but cannot. I ask my brother. He know about phone. He look at it. He say battery is dead. We go to shop. Buy new battery. It cost ten dollars. We put in phone. Then it work. I am happy. Now I charge battery every day. I solve problem with brother help. It is not big problem but I scare at first.",
        "word_count": 89,
        "response_type": "long_turn",
        "micro_flaws": [
            "article error: 'have problem' -> 'had a problem'",
            "subject-verb agreement: 'It stop' -> 'It stopped' (past)",
            "article error: 'Screen is' -> 'The screen is/was'",
            "article error: 'call friend' -> 'call a friend'",
            "verb pattern: 'try open' -> 'try to open' or 'tried to open'",
            "subject-verb agreement: 'He know' -> 'He knows' (or 'knew')",
            "subject-verb agreement: 'He look' -> 'He looks' (or 'looked')",
            "subject-verb agreement: 'He say' -> 'He says' (or 'said')",
            "sentence fragment/imperative: 'Buy new battery' -> 'We bought a new battery'",
            "subject-verb agreement: 'It cost' -> 'It cost' (past) or 'costs' (present)",
            "subject-verb agreement: 'it work' -> 'it worked'",
            "noun phrase: 'brother help' -> 'brother\\'s help'",
            "word choice: 'I scare' -> 'I was scared'"
        ],
        "grammar_profile": {
            "complexity": "low",
            "accuracy": "low",
            "flexibility": "low"
        },
        "vocab_reason": "[LR4] Key evidence: 'phone', 'screen', 'call', 'battery', 'shop', 'charge'. >Band 3: Technical words 'battery', 'charge' used. Not Band 5: 'I scare' (wrong form). Basic problem description.",
        "grammar_reason": "[GRA4] Key evidence: Simple sentences. 'He know', 'It stop'. >Band 3: Simple sentences. Not Band 5: Tense/agreement errors in almost every clause.",
        "vocabulary": 4,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a problem you solved.\n\nTranscript: I have problem with my phone. It stop working. Screen is black. I cannot call friend. I am worried. I try open it but cannot. I ask my brother. He know about phone. He look at it. He say battery is dead. We go to shop. Buy new battery. It cost ten dollars. We put in phone. Then it work. I am happy. Now I charge battery every day. I solve problem with brother help. It is not big problem but I scare at first.\n\nWord Count: 89 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Key evidence: 'phone', 'screen', 'call', 'battery', 'shop', 'charge'. \n\n>Band 3: Technical words 'battery', 'charge' used.\n\nNot Band 5: 'I scare' (wrong form). Basic problem description.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Key evidence: Simple sentences. 'He know', 'It stop'. \n\n>Band 3: Simple sentences.\n\nNot Band 5: Tense/agreement errors in almost every clause.\n\n**Micro flaws identified:**\n- verb tense/agreement: 'stop', 'know', 'look', 'say', 'work'\n- article error: 'have problem', 'Screen is', 'call friend'\n- verb pattern: 'try open'\n- word choice: 'I scare'"
    },
    {
        "sample_id": "syn_p2_v4_g4_022",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a festival in your country.",
        "transcript_cleaned": "I talk about New Year festival. It is big festival. Everyone happy. We clean house before festival. We buy new clothes. We cook special food. Name is Banh Chung. It made from rice. We visit family. Grandfather give lucky money to children. Red envelope. I like this. We watch firework at night. It is beautiful. Many color in sky. People say \"Happy New Year\". We not work for three days. It is time for relax. I love New Year.",
        "word_count": 87,
        "response_type": "long_turn",
        "micro_flaws": [
            "missing verb: 'Everyone happy' -> 'Everyone is happy'",
            "passive voice error: 'It made from' -> 'It is made from'",
            "subject-verb agreement: 'Grandfather give' -> 'Grandfather gives'",
            "fragment: 'Red envelope' -> 'It is a red envelope'",
            "plural error: 'firework' -> 'fireworks'",
            "plural error: 'Many color' -> 'Many colors'",
            "negative structure: 'We not work' -> 'We do not work'",
            "word form: 'for relax' -> 'for relaxing' or 'relaxation'"
        ],
        "grammar_profile": {
            "complexity": "low",
            "accuracy": "low",
            "flexibility": "low"
        },
        "vocab_reason": "[LR4] Key evidence: 'festival', 'clothes', 'rice', 'lucky money', 'firework'. >Band 3: Topic specific words. Not Band 5: 'Big festival', 'beautiful' are basic. 'Time for relax' (wrong form).",
        "grammar_reason": "[GRA4] Key evidence: Simple sentences. 'Everyone happy' (missing verb). >Band 3: Simple sentences. Not Band 5: Missing verbs and incorrect negatives ('We not work').",
        "vocabulary": 4,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a festival in your country.\n\nTranscript: I talk about New Year festival. It is big festival. Everyone happy. We clean house before festival. We buy new clothes. We cook special food. Name is Banh Chung. It made from rice. We visit family. Grandfather give lucky money to children. Red envelope. I like this. We watch firework at night. It is beautiful. Many color in sky. People say \"Happy New Year\". We not work for three days. It is time for relax. I love New Year.\n\nWord Count: 87 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Key evidence: 'festival', 'clothes', 'rice', 'lucky money', 'firework'. \n\n>Band 3: Topic specific words.\n\nNot Band 5: 'Big festival', 'beautiful' are basic. 'Time for relax' (wrong form).\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Key evidence: Simple sentences. 'Everyone happy' (missing verb). \n\n>Band 3: Simple sentences.\n\nNot Band 5: Missing verbs and incorrect negatives ('We not work').\n\n**Micro flaws identified:**\n- missing verb: 'Everyone happy'\n- passive voice: 'It made'\n- subject-verb agreement: 'Grandfather give'\n- negative structure: 'We not work'\n- plural error: 'firework', 'Many color'"
    },
    {
        "sample_id": "syn_p2_v4_g4_023",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a place where you relax.",
        "transcript_cleaned": "I relax in my bedroom. It is small room but comfortable. I have bed and desk. The wall is blue. I like blue. I listen to music there. I lie on bed and close eyes. Sometimes I read book. No one disturb me. It is quiet. I feel safe there. I sleep there every night. I put poster of singer on wall. I clean my room on Sunday. It is my favorite place in house. I can be myself.",
        "word_count": 86,
        "response_type": "long_turn",
        "micro_flaws": [
            "article error: 'is small room' -> 'is a small room'",
            "article error: 'have bed' -> 'have a bed'",
            "article error: 'read book' -> 'read a book'",
            "subject-verb agreement: 'No one disturb' -> 'No one disturbs'",
            "article error: 'put poster' -> 'put a poster'",
            "article error: 'on wall' -> 'on the wall'",
            "article error: 'in house' -> 'in the house'"
        ],
        "grammar_profile": {
            "complexity": "low",
            "accuracy": "low",
            "flexibility": "low"
        },
        "vocab_reason": "[LR4] Key evidence: 'bedroom', 'comfortable', 'desk', 'wall', 'music', 'disturb', 'safe'. >Band 3: Describes place. Not Band 5: 'I can be myself' is good but might be memorized. Other words basic.",
        "grammar_reason": "[GRA4] Key evidence: Simple sentences. 'No one disturb'. >Band 3: Simple sentences. Not Band 5: Article errors frequent. Agreement error 'disturb'.",
        "vocabulary": 4,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a place where you relax.\n\nTranscript: I relax in my bedroom. It is small room but comfortable. I have bed and desk. The wall is blue. I like blue. I listen to music there. I lie on bed and close eyes. Sometimes I read book. No one disturb me. It is quiet. I feel safe there. I sleep there every night. I put poster of singer on wall. I clean my room on Sunday. It is my favorite place in house. I can be myself.\n\nWord Count: 86 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Key evidence: 'bedroom', 'comfortable', 'desk', 'wall', 'music', 'disturb', 'safe'. \n\n>Band 3: Describes place.\n\nNot Band 5: 'I can be myself' is good but might be memorized. Other words basic.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Key evidence: Simple sentences. 'No one disturb'. \n\n>Band 3: Simple sentences.\n\nNot Band 5: Article errors frequent. Agreement error 'disturb'.\n\n**Micro flaws identified:**\n- article error: 'is small room', 'have bed', 'read book', 'put poster', 'on wall'\n- subject-verb agreement: 'No one disturb'"
    },
    {
        "sample_id": "syn_p2_v4_g4_024",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a person you admire.",
        "transcript_cleaned": "I admire my father. He is hard worker. He work in factory. He start work early morning. He come home late. He is strong man. He take care of family. He never complain. He help me with homework. He fix things in house. He like watch football. We watch together. He tell me be good person. I respect him much. He is hero for me. I want be like him when I grow up.",
        "word_count": 81,
        "response_type": "long_turn",
        "micro_flaws": [
            "article error: 'is hard worker' -> 'is a hard worker'",
            "subject-verb agreement: 'He work' -> 'He works'",
            "subject-verb agreement: 'He start' -> 'He starts'",
            "subject-verb agreement: 'He come' -> 'He comes'",
            "article error: 'is strong man' -> 'is a strong man'",
            "subject-verb agreement: 'He take' -> 'He takes'",
            "subject-verb agreement: 'He help' -> 'He helps'",
            "subject-verb agreement: 'He fix' -> 'He fixes'",
            "subject-verb agreement: 'He like' -> 'He likes'",
            "verb pattern: 'like watch' -> 'likes watching' or 'likes to watch'",
            "subject-verb agreement: 'He tell' -> 'He tells'",
            "verb pattern: 'be good person' -> 'to be a good person'",
            "word choice: 'much' -> 'a lot'",
            "article error: 'is hero' -> 'is a hero'",
            "verb pattern: 'want be' -> 'want to be'"
        ],
        "grammar_profile": {
            "complexity": "low",
            "accuracy": "low",
            "flexibility": "low"
        },
        "vocab_reason": "[LR4] Key evidence: 'father', 'factory', 'strong', 'fix', 'hero', 'respect'. >Band 3: Descriptors used. Not Band 5: 'Hard worker' (good phrase but common). 'Much' used incorrectly.",
        "grammar_reason": "[GRA4] Key evidence: Simple sentences. 'He work', 'He start'. >Band 3: Simple sentences. Not Band 5: 3rd person singular 's' omitted systematically.",
        "vocabulary": 4,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a person you admire.\n\nTranscript: I admire my father. He is hard worker. He work in factory. He start work early morning. He come home late. He is strong man. He take care of family. He never complain. He help me with homework. He fix things in house. He like watch football. We watch together. He tell me be good person. I respect him much. He is hero for me. I want be like him when I grow up.\n\nWord Count: 81 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Key evidence: 'father', 'factory', 'strong', 'fix', 'hero', 'respect'. \n\n>Band 3: Descriptors used.\n\nNot Band 5: 'Hard worker' (good phrase but common). 'Much' used incorrectly.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Key evidence: Simple sentences. 'He work', 'He start'. \n\n>Band 3: Simple sentences.\n\nNot Band 5: 3rd person singular 's' omitted systematically.\n\n**Micro flaws identified:**\n- subject-verb agreement: 'He work', 'He start', 'He come', 'He take', 'He help', 'He fix', 'He like', 'He tell'\n- article error: 'is hard worker', 'is strong man', 'is hero'\n- verb pattern: 'like watch', 'want be'"
    },
    {
        "sample_id": "syn_p2_v4_g4_025",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe an advertisement you saw.",
        "transcript_cleaned": "I see advertisement on TV. It is for phone. New iPhone. The ad is very color. Music is loud and fast. People dance in ad. They hold phone and smile. Phone look beautiful. It has good camera. I want buy it. But it is too money. The ad show phone can take water photo. Under water. I think it is amazing. I watch this ad many times. It make me want phone. Advertising is clever.",
        "word_count": 81,
        "response_type": "long_turn",
        "micro_flaws": [
            "verb tense: 'see' -> 'saw'",
            "word form: 'very color' -> 'very colorful'",
            "article error: 'in ad' -> 'in the ad'",
            "subject-verb agreement: 'Phone look' -> 'The phone looks'",
            "verb pattern: 'want buy' -> 'want to buy'",
            "word choice: 'too money' -> 'too expensive' or 'too much money'",
            "subject-verb agreement: 'ad show' -> 'ad shows'",
            "word choice: 'take water photo' -> 'take photos under water'",
            "subject-verb agreement: 'It make' -> 'It makes'"
        ],
        "grammar_profile": {
            "complexity": "low",
            "accuracy": "low",
            "flexibility": "low"
        },
        "vocab_reason": "[LR4] Key evidence: 'advertisement', 'phone', 'camera', 'dance', 'smile', 'water'. >Band 3: Topic clear. Not Band 5: 'Very color' (wrong form). 'Too money' (wrong word).",
        "grammar_reason": "[GRA4] Key evidence: Simple sentences. 'It make', 'Phone look'. >Band 3: Simple sentences. Not Band 5: Frequent subject-verb agreement errors. Word form errors impacting grammar.",
        "vocabulary": 4,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe an advertisement you saw.\n\nTranscript: I see advertisement on TV. It is for phone. New iPhone. The ad is very color. Music is loud and fast. People dance in ad. They hold phone and smile. Phone look beautiful. It has good camera. I want buy it. But it is too money. The ad show phone can take water photo. Under water. I think it is amazing. I watch this ad many times. It make me want phone. Advertising is clever.\n\nWord Count: 81 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Key evidence: 'advertisement', 'phone', 'camera', 'dance', 'smile', 'water'. \n\n>Band 3: Topic clear.\n\nNot Band 5: 'Very color' (wrong form). 'Too money' (wrong word).\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Key evidence: Simple sentences. 'It make', 'Phone look'. \n\n>Band 3: Simple sentences.\n\nNot Band 5: Frequent subject-verb agreement errors. Word form errors impacting grammar.\n\n**Micro flaws identified:**\n- verb tense: 'see'\n- word form: 'very color', 'too money'\n- subject-verb agreement: 'Phone look', 'ad show', 'It make'\n- verb pattern: 'want buy'"
    }
]

with open(OUTPUT_FILE, 'a') as f:
    for sample in samples:
        json.dump(sample, f)
        f.write('\n')
