import json

OUTPUT_FILE = 'ielts-data/phase3/v76_review_output/jules1/jules1_batch04.jsonl'

samples = [
    {
        "sample_id": "syn_p2_v6_g6_301",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a difficult journey.",
        "transcript_cleaned": "I climbed Mount Fuji in Japan. It was a steep climb. The path was volcanic rock. It was slippery. I started at night. I wanted to see the sunrise. It was freezing cold. I wore many layers of clothes. The air was thin near the top. I felt dizzy. However, the view from the summit was worth it. The sun rising above the clouds was spectacular. It was a spiritual experience.",
        "word_count": 73,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'steep', 'volcanic', 'slippery', 'sunrise', 'layers', 'dizzy', 'summit', 'worth it', 'spectacular', 'spiritual'. >Band 5: 'Summit', 'volcanic'. Not Band 7: Standard hiking vocab.",
        "grammar_reason": "[GRA6] Key evidence: 'wanted to see', 'rising above the clouds'. >Band 5: Infinitive and participle phrases correct. Not Band 7: Short sentences.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a difficult journey.\n\nTranscript: I climbed Mount Fuji in Japan. It was a steep climb. The path was volcanic rock. It was slippery. I started at night. I wanted to see the sunrise. It was freezing cold. I wore many layers of clothes. The air was thin near the top. I felt dizzy. However, the view from the summit was worth it. The sun rising above the clouds was spectacular. It was a spiritual experience.\n\nWord Count: 73 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'steep', 'volcanic', 'slippery', 'sunrise', 'layers', 'dizzy', 'summit', 'worth it', 'spectacular', 'spiritual'. \n\n>Band 5: 'Summit', 'volcanic'.\n\nNot Band 7: Standard hiking vocab.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'wanted to see', 'rising above the clouds'. \n\n>Band 5: Infinitive and participle phrases correct.\n\nNot Band 7: Short sentences.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_302",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a person you admire.",
        "transcript_cleaned": "I admire my grandfather. He is a retired soldier. He is disciplined and punctual. He wakes up early every day. He exercises regularly. He tells stories about his time in the army. He faced many dangers. He is brave and resilient. He taught me the value of hard work. He is strict but loving. I respect him deeply. He is a pillar of our family. I want to be strong like him.",
        "word_count": 73,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'retired', 'soldier', 'disciplined', 'punctual', 'regularly', 'army', 'dangers', 'resilient', 'value', 'strict', 'deeply', 'pillar'. >Band 5: 'Resilient', 'pillar'. Not Band 7: Standard descriptions.",
        "grammar_reason": "[GRA6] Key evidence: 'stories about his time', 'want to be'. >Band 5: Prepositional phrases and infinitives correct. Not Band 7: Repetitive 'He'.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a person you admire.\n\nTranscript: I admire my grandfather. He is a retired soldier. He is disciplined and punctual. He wakes up early every day. He exercises regularly. He tells stories about his time in the army. He faced many dangers. He is brave and resilient. He taught me the value of hard work. He is strict but loving. I respect him deeply. He is a pillar of our family. I want to be strong like him.\n\nWord Count: 73 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'retired', 'soldier', 'disciplined', 'punctual', 'regularly', 'army', 'dangers', 'resilient', 'value', 'strict', 'deeply', 'pillar'. \n\n>Band 5: 'Resilient', 'pillar'.\n\nNot Band 7: Standard descriptions.\n\n**Idiom present:** Yes\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'stories about his time', 'want to be'. \n\n>Band 5: Prepositional phrases and infinitives correct.\n\nNot Band 7: Repetitive 'He'.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_303",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a place.",
        "transcript_cleaned": "I visited a floating market in Thailand. It was a unique experience. The market is on a river. Vendors sell goods from boats. There were fruits, vegetables, and souvenirs. The colors were bright. It was noisy and chaotic but fun. I tried coconut ice cream. It was refreshing. I took a boat ride through the market. I bargained for a hat. It was a cultural immersion. I loved the lively atmosphere.",
        "word_count": 72,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'floating market', 'unique', 'vendors', 'goods', 'souvenirs', 'chaotic', 'refreshing', 'bargained', 'cultural immersion', 'lively', 'atmosphere'. >Band 5: 'Cultural immersion', 'chaotic'. Not Band 7: Good range.",
        "grammar_reason": "[GRA6] Key evidence: 'sell goods from boats', 'boat ride through'. >Band 5: Prepositional phrases correct. Not Band 7: Simple structure.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a place.\n\nTranscript: I visited a floating market in Thailand. It was a unique experience. The market is on a river. Vendors sell goods from boats. There were fruits, vegetables, and souvenirs. The colors were bright. It was noisy and chaotic but fun. I tried coconut ice cream. It was refreshing. I took a boat ride through the market. I bargained for a hat. It was a cultural immersion. I loved the lively atmosphere.\n\nWord Count: 72 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'floating market', 'unique', 'vendors', 'goods', 'souvenirs', 'chaotic', 'refreshing', 'bargained', 'cultural immersion', 'lively', 'atmosphere'. \n\n>Band 5: 'Cultural immersion', 'chaotic'.\n\nNot Band 7: Good range.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'sell goods from boats', 'boat ride through'. \n\n>Band 5: Prepositional phrases correct.\n\nNot Band 7: Simple structure.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_304",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a traditional event.",
        "transcript_cleaned": "I attended a tea ceremony in Japan. It is a traditional ritual. It takes place in a tea room. The room is simple and quiet. The host prepares matcha tea. Every movement is precise. It is an art form. I had to sit on the floor. My legs were numb. But I enjoyed the peace. The tea was bitter but tasty. It taught me about mindfulness. It was a spiritual experience.",
        "word_count": 73,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'tea ceremony', 'ritual', 'takes place', 'prepares', 'movement', 'precise', 'art form', 'numb', 'bitter', 'mindfulness', 'spiritual'. >Band 5: 'Mindfulness', 'precise'. Not Band 7: Standard culture vocab.",
        "grammar_reason": "[GRA6] Key evidence: 'takes place in', 'taught me about'. >Band 5: Phrasal verbs and prepositions correct. Not Band 7: Short sentences.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a traditional event.\n\nTranscript: I attended a tea ceremony in Japan. It is a traditional ritual. It takes place in a tea room. The room is simple and quiet. The host prepares matcha tea. Every movement is precise. It is an art form. I had to sit on the floor. My legs were numb. But I enjoyed the peace. The tea was bitter but tasty. It taught me about mindfulness. It was a spiritual experience.\n\nWord Count: 73 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'tea ceremony', 'ritual', 'takes place', 'prepares', 'movement', 'precise', 'art form', 'numb', 'bitter', 'mindfulness', 'spiritual'. \n\n>Band 5: 'Mindfulness', 'precise'.\n\nNot Band 7: Standard culture vocab.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'takes place in', 'taught me about'. \n\n>Band 5: Phrasal verbs and prepositions correct.\n\nNot Band 7: Short sentences.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_305",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a difficult choice.",
        "transcript_cleaned": "I had to choose between two jobs. One job offered a high salary. But it was far from home. The other job had a lower salary. But it was near my house. I was conflicted. I value my free time. If I took the first job, I would commute for hours. I decided to take the second job. I chose quality of life over money. I am happy with my decision.",
        "word_count": 72,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'choose between', 'offered', 'salary', 'lower', 'conflicted', 'value', 'commute', 'quality of life', 'decision'. >Band 5: 'Conflicted', 'quality of life'. Not Band 7: Good range.",
        "grammar_reason": "[GRA6] Key evidence: 'If I took... I would commute', 'decided to take'. >Band 5: 2nd conditional and infinitives correct. Not Band 7: Short sentences.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a difficult choice.\n\nTranscript: I had to choose between two jobs. One job offered a high salary. But it was far from home. The other job had a lower salary. But it was near my house. I was conflicted. I value my free time. If I took the first job, I would commute for hours. I decided to take the second job. I chose quality of life over money. I am happy with my decision.\n\nWord Count: 72 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'choose between', 'offered', 'salary', 'lower', 'conflicted', 'value', 'commute', 'quality of life', 'decision'. \n\n>Band 5: 'Conflicted', 'quality of life'.\n\nNot Band 7: Good range.\n\n**Idiom present:** Yes\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'If I took... I would commute', 'decided to take'. \n\n>Band 5: 2nd conditional and infinitives correct.\n\nNot Band 7: Short sentences.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_306",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a plant.",
        "transcript_cleaned": "I like the lavender plant. It is a herb. It has purple flowers. It smells wonderful. I have some in my garden. Bees love it. It is useful. I use dried lavender to make tea. It helps me sleep. I also use it in my bath. It is relaxing. Lavender needs sun to grow. It is a hardy plant. The color is soothing. I think it is the best smelling plant.",
        "word_count": 73,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'herb', 'purple', 'dried', 'relaxing', 'hardy', 'soothing', 'smelling'. >Band 5: 'Hardy', 'soothing'. Not Band 7: Good range.",
        "grammar_reason": "[GRA6] Key evidence: 'use... to make', 'needs sun to grow'. >Band 5: Infinitives of purpose correct. Not Band 7: Simple structure.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a plant.\n\nTranscript: I like the lavender plant. It is a herb. It has purple flowers. It smells wonderful. I have some in my garden. Bees love it. It is useful. I use dried lavender to make tea. It helps me sleep. I also use it in my bath. It is relaxing. Lavender needs sun to grow. It is a hardy plant. The color is soothing. I think it is the best smelling plant.\n\nWord Count: 73 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'herb', 'purple', 'dried', 'relaxing', 'hardy', 'soothing', 'smelling'. \n\n>Band 5: 'Hardy', 'soothing'.\n\nNot Band 7: Good range.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'use... to make', 'needs sun to grow'. \n\n>Band 5: Infinitives of purpose correct.\n\nNot Band 7: Simple structure.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_307",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a useful object.",
        "transcript_cleaned": "I use a fitness tracker watch. It tracks my steps and heart rate. It connects to my phone. I check my progress daily. It motivates me to move more. It also tracks my sleep. I can see if I slept well. It is waterproof, so I can swim with it. The battery lasts a week. It is a handy gadget. It helps me maintain a healthy lifestyle. I wear it everywhere.",
        "word_count": 73,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'fitness tracker', 'tracks', 'heart rate', 'progress', 'motivates', 'waterproof', 'handy', 'gadget', 'maintain', 'lifestyle'. >Band 5: 'Handy gadget', 'maintain lifestyle'. Not Band 7: Standard tech vocab.",
        "grammar_reason": "[GRA6] Key evidence: 'see if I slept', 'waterproof, so I can'. >Band 5: Noun clauses and compound sentences correct. Not Band 7: Short sentences.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a useful object.\n\nTranscript: I use a fitness tracker watch. It tracks my steps and heart rate. It connects to my phone. I check my progress daily. It motivates me to move more. It also tracks my sleep. I can see if I slept well. It is waterproof, so I can swim with it. The battery lasts a week. It is a handy gadget. It helps me maintain a healthy lifestyle. I wear it everywhere.\n\nWord Count: 73 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'fitness tracker', 'tracks', 'heart rate', 'progress', 'motivates', 'waterproof', 'handy', 'gadget', 'maintain', 'lifestyle'. \n\n>Band 5: 'Handy gadget', 'maintain lifestyle'.\n\nNot Band 7: Standard tech vocab.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'see if I slept', 'waterproof, so I can'. \n\n>Band 5: Noun clauses and compound sentences correct.\n\nNot Band 7: Short sentences.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_308",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a busy time.",
        "transcript_cleaned": "I was busy before my sister's wedding. I was the maid of honor. I had many responsibilities. I helped her choose the dress. I organized the bridal shower. I wrote a speech. I was running around all day. I felt stressed but excited. I wanted everything to be perfect. The wedding day was chaotic but beautiful. I was exhausted afterwards. But seeing my sister happy made it worthwhile.",
        "word_count": 69,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'maid of honor', 'responsibilities', 'bridal shower', 'speech', 'stressed', 'perfect', 'chaotic', 'exhausted', 'worthwhile'. >Band 5: 'Worthwhile', 'chaotic'. Not Band 7: Good range.",
        "grammar_reason": "[GRA6] Key evidence: 'wanted everything to be', 'seeing... made it'. >Band 5: Infinitive patterns and gerund subjects correct. Not Band 7: Simple structure.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a busy time.\n\nTranscript: I was busy before my sister's wedding. I was the maid of honor. I had many responsibilities. I helped her choose the dress. I organized the bridal shower. I wrote a speech. I was running around all day. I felt stressed but excited. I wanted everything to be perfect. The wedding day was chaotic but beautiful. I was exhausted afterwards. But seeing my sister happy made it worthwhile.\n\nWord Count: 69 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'maid of honor', 'responsibilities', 'bridal shower', 'speech', 'stressed', 'perfect', 'chaotic', 'exhausted', 'worthwhile'. \n\n>Band 5: 'Worthwhile', 'chaotic'.\n\nNot Band 7: Good range.\n\n**Idiom present:** Yes\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'wanted everything to be', 'seeing... made it'. \n\n>Band 5: Infinitive patterns and gerund subjects correct.\n\nNot Band 7: Simple structure.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_309",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a competition.",
        "transcript_cleaned": "I entered a cooking competition. It was held at my school. I decided to bake a cake. I practiced the recipe many times. On the day, I was nervous. I had one hour to bake. I forgot to add sugar at first. I panicked. But I fixed it. My cake looked good. The judges tasted it. They said it was moist. I came second. I was proud of my effort.",
        "word_count": 71,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'competition', 'held', 'bake', 'recipe', 'nervous', 'panicked', 'fixed', 'judges', 'tasted', 'moist', 'effort'. >Band 5: 'Panicked', 'moist'. Not Band 7: Standard cooking vocab.",
        "grammar_reason": "[GRA6] Key evidence: 'decided to bake', 'forgot to add'. >Band 5: Infinitive patterns correct. Not Band 7: Very short sentences.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a competition.\n\nTranscript: I entered a cooking competition. It was held at my school. I decided to bake a cake. I practiced the recipe many times. On the day, I was nervous. I had one hour to bake. I forgot to add sugar at first. I panicked. But I fixed it. My cake looked good. The judges tasted it. They said it was moist. I came second. I was proud of my effort.\n\nWord Count: 71 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'competition', 'held', 'bake', 'recipe', 'nervous', 'panicked', 'fixed', 'judges', 'tasted', 'moist', 'effort'. \n\n>Band 5: 'Panicked', 'moist'.\n\nNot Band 7: Standard cooking vocab.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'decided to bake', 'forgot to add'. \n\n>Band 5: Infinitive patterns correct.\n\nNot Band 7: Very short sentences.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_310",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a friend.",
        "transcript_cleaned": "My friend John is very funny. He is the class clown. He always tells jokes. He can mimic teachers well. He makes everyone laugh. He is also smart. He helps me with math. We play video games together. He is easygoing. We never fight. He is a good listener too. I can tell him my secrets. He is a loyal friend. I hope our friendship lasts a lifetime.",
        "word_count": 69,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'class clown', 'jokes', 'mimic', 'smart', 'easygoing', 'listener', 'secrets', 'loyal', 'friendship', 'lifetime'. >Band 5: 'Class clown', 'mimic', 'easygoing'. Not Band 7: Good range.",
        "grammar_reason": "[GRA6] Key evidence: 'helps me with', 'hope... lasts'. >Band 5: Prepositional phrases and future hope correct. Not Band 7: Short sentences.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a friend.\n\nTranscript: My friend John is very funny. He is the class clown. He always tells jokes. He can mimic teachers well. He makes everyone laugh. He is also smart. He helps me with math. We play video games together. He is easygoing. We never fight. He is a good listener too. I can tell him my secrets. He is a loyal friend. I hope our friendship lasts a lifetime.\n\nWord Count: 69 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'class clown', 'jokes', 'mimic', 'smart', 'easygoing', 'listener', 'secrets', 'loyal', 'friendship', 'lifetime'. \n\n>Band 5: 'Class clown', 'mimic', 'easygoing'.\n\nNot Band 7: Good range.\n\n**Idiom present:** Yes\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'helps me with', 'hope... lasts'. \n\n>Band 5: Prepositional phrases and future hope correct.\n\nNot Band 7: Short sentences.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_311",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a place.",
        "transcript_cleaned": "I went to a science museum. It was interactive. I could touch the exhibits. There was a robot section. I saw robots dancing. It was cool. I learned about space travel. I saw a model of a rocket. It was huge. The museum was crowded with students. It was noisy but interesting. I bought a science kit in the shop. It is a great place to learn science. I want to be a scientist.",
        "word_count": 75,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'interactive', 'exhibits', 'section', 'robots', 'space travel', 'model', 'rocket', 'crowded', 'kit', 'scientist'. >Band 5: 'Interactive', 'exhibits'. Not Band 7: Standard museum words.",
        "grammar_reason": "[GRA6] Key evidence: 'could touch', 'place to learn', 'want to be'. >Band 5: Modals and infinitives correct. Not Band 7: Simple structure.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a place.\n\nTranscript: I went to a science museum. It was interactive. I could touch the exhibits. There was a robot section. I saw robots dancing. It was cool. I learned about space travel. I saw a model of a rocket. It was huge. The museum was crowded with students. It was noisy but interesting. I bought a science kit in the shop. It is a great place to learn science. I want to be a scientist.\n\nWord Count: 75 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'interactive', 'exhibits', 'section', 'robots', 'space travel', 'model', 'rocket', 'crowded', 'kit', 'scientist'. \n\n>Band 5: 'Interactive', 'exhibits'.\n\nNot Band 7: Standard museum words.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'could touch', 'place to learn', 'want to be'. \n\n>Band 5: Modals and infinitives correct.\n\nNot Band 7: Simple structure.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_312",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a historical figure.",
        "transcript_cleaned": "I know about Leonardo da Vinci. He was an Italian artist. He painted the Mona Lisa. It is a famous painting. He was also an inventor. He drew plans for flying machines. He was ahead of his time. He was a genius. He studied anatomy too. He was very curious. I saw his drawings in a book. He is an inspiration to me. His work is still admired today.",
        "word_count": 69,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'artist', 'inventor', 'plans', 'flying machines', 'ahead of his time', 'genius', 'anatomy', 'curious', 'drawings', 'inspiration', 'admired'. >Band 5: 'Anatomy', 'ahead of his time'. Not Band 7: Good range.",
        "grammar_reason": "[GRA6] Key evidence: 'is still admired', 'saw his drawings'. >Band 5: Passive and past tense correct. Not Band 7: Short sentences.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a historical figure.\n\nTranscript: I know about Leonardo da Vinci. He was an Italian artist. He painted the Mona Lisa. It is a famous painting. He was also an inventor. He drew plans for flying machines. He was ahead of his time. He was a genius. He studied anatomy too. He was very curious. I saw his drawings in a book. He is an inspiration to me. His work is still admired today.\n\nWord Count: 69 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'artist', 'inventor', 'plans', 'flying machines', 'ahead of his time', 'genius', 'anatomy', 'curious', 'drawings', 'inspiration', 'admired'. \n\n>Band 5: 'Anatomy', 'ahead of his time'.\n\nNot Band 7: Good range.\n\n**Idiom present:** Yes\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'is still admired', 'saw his drawings'. \n\n>Band 5: Passive and past tense correct.\n\nNot Band 7: Short sentences.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_313",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a difficult task.",
        "transcript_cleaned": "I helped my father paint the house. It was a big job. We painted the living room. We had to move the furniture. We covered the floor with plastic. Painting the ceiling was hard. My neck hurt. We used white paint. It took two days. I was messy with paint on my clothes. But the room looked bright and clean. My mother was happy. It was tiring but satisfying.",
        "word_count": 70,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'paint', 'furniture', 'covered', 'plastic', 'ceiling', 'messy', 'bright', 'tiring', 'satisfying'. >Band 5: 'Satisfying', 'ceiling'. Not Band 7: Standard chore vocab.",
        "grammar_reason": "[GRA6] Key evidence: 'had to move', 'Painting the ceiling was'. >Band 5: Gerund subject and modal obligation correct. Not Band 7: Simple structure.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a difficult task.\n\nTranscript: I helped my father paint the house. It was a big job. We painted the living room. We had to move the furniture. We covered the floor with plastic. Painting the ceiling was hard. My neck hurt. We used white paint. It took two days. I was messy with paint on my clothes. But the room looked bright and clean. My mother was happy. It was tiring but satisfying.\n\nWord Count: 70 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'paint', 'furniture', 'covered', 'plastic', 'ceiling', 'messy', 'bright', 'tiring', 'satisfying'. \n\n>Band 5: 'Satisfying', 'ceiling'.\n\nNot Band 7: Standard chore vocab.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'had to move', 'Painting the ceiling was'. \n\n>Band 5: Gerund subject and modal obligation correct.\n\nNot Band 7: Simple structure.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_314",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a useful skill.",
        "transcript_cleaned": "I learned to type fast. It is a computer skill. I used a typing program. I practiced with my fingers. At first, I was slow. I looked at the keyboard. Now I can type without looking. It is called touch typing. It saves me time when I write essays. I can finish my homework quickly. It is a practical skill for work too. I think everyone should learn it.",
        "word_count": 70,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'type', 'program', 'keyboard', 'touch typing', 'saves time', 'essays', 'practical'. >Band 5: 'Touch typing', 'practical'. Not Band 7: Basic sentences.",
        "grammar_reason": "[GRA6] Key evidence: 'type without looking', 'when I write', 'should learn'. >Band 5: Prepositional phrases and modals correct. Not Band 7: Short sentences.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a useful skill.\n\nTranscript: I learned to type fast. It is a computer skill. I used a typing program. I practiced with my fingers. At first, I was slow. I looked at the keyboard. Now I can type without looking. It is called touch typing. It saves me time when I write essays. I can finish my homework quickly. It is a practical skill for work too. I think everyone should learn it.\n\nWord Count: 70 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'type', 'program', 'keyboard', 'touch typing', 'saves time', 'essays', 'practical'. \n\n>Band 5: 'Touch typing', 'practical'.\n\nNot Band 7: Basic sentences.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'type without looking', 'when I write', 'should learn'. \n\n>Band 5: Prepositional phrases and modals correct.\n\nNot Band 7: Short sentences.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_315",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a historical place.",
        "transcript_cleaned": "I visited a museum in Cairo. It had many mummies. They were wrapped in cloth. It was a bit scary. I saw gold masks and jewelry. They belonged to ancient kings. The museum was old and dusty. But the artifacts were amazing. I learned about Egyptian beliefs. They believed in the afterlife. It was a fascinating visit. I want to read more about it. History is full of mysteries.",
        "word_count": 69,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'mummies', 'wrapped', 'cloth', 'masks', 'jewelry', 'belonged', 'ancient', 'dusty', 'artifacts', 'beliefs', 'afterlife', 'fascinating', 'mysteries'. >Band 5: 'Afterlife', 'artifacts'. Not Band 7: Good range.",
        "grammar_reason": "[GRA6] Key evidence: 'They were wrapped', 'belonged to'. >Band 5: Passive voice and past tense correct. Not Band 7: Simple structure.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a historical place.\n\nTranscript: I visited a museum in Cairo. It had many mummies. They were wrapped in cloth. It was a bit scary. I saw gold masks and jewelry. They belonged to ancient kings. The museum was old and dusty. But the artifacts were amazing. I learned about Egyptian beliefs. They believed in the afterlife. It was a fascinating visit. I want to read more about it. History is full of mysteries.\n\nWord Count: 69 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'mummies', 'wrapped', 'cloth', 'masks', 'jewelry', 'belonged', 'ancient', 'dusty', 'artifacts', 'beliefs', 'afterlife', 'fascinating', 'mysteries'. \n\n>Band 5: 'Afterlife', 'artifacts'.\n\nNot Band 7: Good range.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'They were wrapped', 'belonged to'. \n\n>Band 5: Passive voice and past tense correct.\n\nNot Band 7: Simple structure.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_316",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a party.",
        "transcript_cleaned": "I went to a picnic party. It was in a park. We brought blankets and food. Everyone brought a dish. It was a potluck. The weather was sunny. We played badminton and frisbee. We talked and laughed. My friend played the guitar. We sang songs. It was a relaxing afternoon. I enjoyed the fresh air. I like outdoor parties because they are informal. It was a great way to bond.",
        "word_count": 70,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'picnic', 'blankets', 'dish', 'potluck', 'badminton', 'frisbee', 'relaxing', 'fresh air', 'outdoor', 'informal', 'bond'. >Band 5: 'Potluck', 'informal'. Not Band 7: Good range.",
        "grammar_reason": "[GRA6] Key evidence: 'because they are informal', 'way to bond'. >Band 5: Causal and infinitive structures correct. Not Band 7: Short sentences.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a party.\n\nTranscript: I went to a picnic party. It was in a park. We brought blankets and food. Everyone brought a dish. It was a potluck. The weather was sunny. We played badminton and frisbee. We talked and laughed. My friend played the guitar. We sang songs. It was a relaxing afternoon. I enjoyed the fresh air. I like outdoor parties because they are informal. It was a great way to bond.\n\nWord Count: 70 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'picnic', 'blankets', 'dish', 'potluck', 'badminton', 'frisbee', 'relaxing', 'fresh air', 'outdoor', 'informal', 'bond'. \n\n>Band 5: 'Potluck', 'informal'.\n\nNot Band 7: Good range.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'because they are informal', 'way to bond'. \n\n>Band 5: Causal and infinitive structures correct.\n\nNot Band 7: Short sentences.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_317",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a difficult decision.",
        "transcript_cleaned": "I had to choose a birthday gift for my mother. It was hard. She has everything. I looked in many shops. I saw clothes, bags, and jewelry. I did not know what she liked. I asked my father. He suggested a scarf. I found a silk scarf. It was expensive but beautiful. I bought it. My mother loved it. She wears it often. I was relieved she liked it.",
        "word_count": 70,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'choose', 'jewelry', 'suggested', 'scarf', 'silk', 'expensive', 'relieved'. >Band 5: 'Relieved', 'suggested'. Not Band 7: Standard shopping vocab.",
        "grammar_reason": "[GRA6] Key evidence: 'did not know what', 'relieved she liked it'. >Band 5: Noun clauses correct. Not Band 7: Simple structure.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a difficult decision.\n\nTranscript: I had to choose a birthday gift for my mother. It was hard. She has everything. I looked in many shops. I saw clothes, bags, and jewelry. I did not know what she liked. I asked my father. He suggested a scarf. I found a silk scarf. It was expensive but beautiful. I bought it. My mother loved it. She wears it often. I was relieved she liked it.\n\nWord Count: 70 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'choose', 'jewelry', 'suggested', 'scarf', 'silk', 'expensive', 'relieved'. \n\n>Band 5: 'Relieved', 'suggested'.\n\nNot Band 7: Standard shopping vocab.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'did not know what', 'relieved she liked it'. \n\n>Band 5: Noun clauses correct.\n\nNot Band 7: Simple structure.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_318",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a beautiful place.",
        "transcript_cleaned": "I visited a garden in Kyoto. It was a Japanese garden. It had a pond with koi fish. The fish were orange and gold. There were stone lanterns. The trees were shaped perfectly. It was very serene. I walked on a stone path. I heard water flowing. It felt like paradise. I took many photos. It was the most beautiful place I have ever seen. I want to go back.",
        "word_count": 71,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'Japanese garden', 'pond', 'koi fish', 'stone lanterns', 'shaped', 'serene', 'path', 'flowing', 'paradise'. >Band 5: 'Serene', 'paradise'. Not Band 7: Good range.",
        "grammar_reason": "[GRA6] Key evidence: 'most beautiful place I have ever seen', 'felt like'. >Band 5: Superlative and perfect tense correct. Not Band 7: Short sentences.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a beautiful place.\n\nTranscript: I visited a garden in Kyoto. It was a Japanese garden. It had a pond with koi fish. The fish were orange and gold. There were stone lanterns. The trees were shaped perfectly. It was very serene. I walked on a stone path. I heard water flowing. It felt like paradise. I took many photos. It was the most beautiful place I have ever seen. I want to go back.\n\nWord Count: 71 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'Japanese garden', 'pond', 'koi fish', 'stone lanterns', 'shaped', 'serene', 'path', 'flowing', 'paradise'. \n\n>Band 5: 'Serene', 'paradise'.\n\nNot Band 7: Good range.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'most beautiful place I have ever seen', 'felt like'. \n\n>Band 5: Superlative and perfect tense correct.\n\nNot Band 7: Short sentences.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_319",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a game.",
        "transcript_cleaned": "I play hide and seek with my cousins. It is a childhood game. One person counts, and others hide. I try to find a good hiding spot. I am quiet. It is suspenseful. I do not want to be found. If I win, I am happy. We play in the garden. It is simple but fun. It reminds me of being young. We laugh a lot. It creates good memories.",
        "word_count": 71,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'hide and seek', 'childhood', 'counts', 'hiding spot', 'suspenseful', 'found', 'reminds', 'memories'. >Band 5: 'Suspenseful', 'hiding spot'. Not Band 7: Standard game vocab.",
        "grammar_reason": "[GRA6] Key evidence: 'try to find', 'do not want to be found'. >Band 5: Passive voice and infinitives correct. Not Band 7: Short sentences.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a game.\n\nTranscript: I play hide and seek with my cousins. It is a childhood game. One person counts, and others hide. I try to find a good hiding spot. I am quiet. It is suspenseful. I do not want to be found. If I win, I am happy. We play in the garden. It is simple but fun. It reminds me of being young. We laugh a lot. It creates good memories.\n\nWord Count: 71 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'hide and seek', 'childhood', 'counts', 'hiding spot', 'suspenseful', 'found', 'reminds', 'memories'. \n\n>Band 5: 'Suspenseful', 'hiding spot'.\n\nNot Band 7: Standard game vocab.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'try to find', 'do not want to be found'. \n\n>Band 5: Passive voice and infinitives correct.\n\nNot Band 7: Short sentences.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_320",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a difficult task.",
        "transcript_cleaned": "I had to learn English. It was difficult at first. The grammar is complicated. There are many rules. I struggled with pronunciation. I made many mistakes. People did not understand me. I felt embarrassed. But I studied every day. I watched English movies. Slowly, I improved. Now I can speak confidently. It was a long journey. I am proud of my progress. Learning a language opens new doors.",
        "word_count": 68,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'grammar', 'complicated', 'rules', 'struggled', 'pronunciation', 'mistakes', 'embarrassed', 'improved', 'confidently', 'journey', 'progress', 'opens new doors'. >Band 5: 'Struggled', 'opens new doors'. Not Band 7: Idiom used correctly but isolated.",
        "grammar_reason": "[GRA6] Key evidence: 'difficult at first', 'proud of my progress'. >Band 5: Prepositional phrases correct. Not Band 7: Short sentences.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a difficult task.\n\nTranscript: I had to learn English. It was difficult at first. The grammar is complicated. There are many rules. I struggled with pronunciation. I made many mistakes. People did not understand me. I felt embarrassed. But I studied every day. I watched English movies. Slowly, I improved. Now I can speak confidently. It was a long journey. I am proud of my progress. Learning a language opens new doors.\n\nWord Count: 68 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'grammar', 'complicated', 'rules', 'struggled', 'pronunciation', 'mistakes', 'embarrassed', 'improved', 'confidently', 'journey', 'progress', 'opens new doors'. \n\n>Band 5: 'Struggled', 'opens new doors'.\n\nNot Band 7: Idiom used correctly but isolated.\n\n**Idiom present:** Yes\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'difficult at first', 'proud of my progress'. \n\n>Band 5: Prepositional phrases correct.\n\nNot Band 7: Short sentences.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_321",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a historical figure.",
        "transcript_cleaned": "I admire Shakespeare. He was a famous writer from England. He wrote plays and poems. His works are known worldwide. He wrote Romeo and Juliet. It is a tragic love story. He invented many words in English. He was a creative genius. His plays are still performed today. I read them in school. The language is old but beautiful. He had a great impact on literature.",
        "word_count": 67,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'writer', 'plays', 'poems', 'worldwide', 'tragic', 'invented', 'creative genius', 'performed', 'literature', 'impact'. >Band 5: 'Creative genius', 'impact'. Not Band 7: Good range.",
        "grammar_reason": "[GRA6] Key evidence: 'known worldwide', 'still performed today'. >Band 5: Passive voice correct. Not Band 7: Simple structure.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a historical figure.\n\nTranscript: I admire Shakespeare. He was a famous writer from England. He wrote plays and poems. His works are known worldwide. He wrote Romeo and Juliet. It is a tragic love story. He invented many words in English. He was a creative genius. His plays are still performed today. I read them in school. The language is old but beautiful. He had a great impact on literature.\n\nWord Count: 67 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'writer', 'plays', 'poems', 'worldwide', 'tragic', 'invented', 'creative genius', 'performed', 'literature', 'impact'. \n\n>Band 5: 'Creative genius', 'impact'.\n\nNot Band 7: Good range.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'known worldwide', 'still performed today'. \n\n>Band 5: Passive voice correct.\n\nNot Band 7: Simple structure.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_322",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a meal.",
        "transcript_cleaned": "I ate a burger at a fast food restaurant. It was a cheeseburger. It had beef, cheese, and lettuce. I ordered fries and a soda too. It was a quick meal. I was hungry after school. The burger was juicy and tasty. It was not healthy, but I liked it. I ate it with my friends. We chatted while we ate. It was a cheap and satisfying lunch.",
        "word_count": 69,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'fast food', 'cheeseburger', 'beef', 'lettuce', 'fries', 'soda', 'quick meal', 'juicy', 'tasty', 'satisfying'. >Band 5: 'Juicy', 'satisfying'. Not Band 7: Standard food vocab.",
        "grammar_reason": "[GRA6] Key evidence: 'chatted while we ate', 'not healthy, but'. >Band 5: Time clauses and compound sentences correct. Not Band 7: Short sentences.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a meal.\n\nTranscript: I ate a burger at a fast food restaurant. It was a cheeseburger. It had beef, cheese, and lettuce. I ordered fries and a soda too. It was a quick meal. I was hungry after school. The burger was juicy and tasty. It was not healthy, but I liked it. I ate it with my friends. We chatted while we ate. It was a cheap and satisfying lunch.\n\nWord Count: 69 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'fast food', 'cheeseburger', 'beef', 'lettuce', 'fries', 'soda', 'quick meal', 'juicy', 'tasty', 'satisfying'. \n\n>Band 5: 'Juicy', 'satisfying'.\n\nNot Band 7: Standard food vocab.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'chatted while we ate', 'not healthy, but'. \n\n>Band 5: Time clauses and compound sentences correct.\n\nNot Band 7: Short sentences.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_323",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a difficult task.",
        "transcript_cleaned": "I had to give a dog a bath. My dog hates water. He ran away when he saw the hose. I had to catch him. He is heavy. I got wet. He shook water on me. I used dog shampoo. I scrubbed his fur. He tried to escape. It was a struggle. Finally, he was clean. He smelled good. I gave him a treat. It was messy work.",
        "word_count": 69,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'bath', 'hose', 'catch', 'shook', 'shampoo', 'scrubbed', 'fur', 'escape', 'struggle', 'treat', 'messy'. >Band 5: 'Scrubbed', 'struggle'. Not Band 7: Basic sentences.",
        "grammar_reason": "[GRA6] Key evidence: 'when he saw', 'tried to escape'. >Band 5: Time clauses and infinitives correct. Not Band 7: Very short sentences.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a difficult task.\n\nTranscript: I had to give a dog a bath. My dog hates water. He ran away when he saw the hose. I had to catch him. He is heavy. I got wet. He shook water on me. I used dog shampoo. I scrubbed his fur. He tried to escape. It was a struggle. Finally, he was clean. He smelled good. I gave him a treat. It was messy work.\n\nWord Count: 69 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'bath', 'hose', 'catch', 'shook', 'shampoo', 'scrubbed', 'fur', 'escape', 'struggle', 'treat', 'messy'. \n\n>Band 5: 'Scrubbed', 'struggle'.\n\nNot Band 7: Basic sentences.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'when he saw', 'tried to escape'. \n\n>Band 5: Time clauses and infinitives correct.\n\nNot Band 7: Very short sentences.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_324",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a beautiful place.",
        "transcript_cleaned": "I went to a flower field in the Netherlands. There were millions of tulips. They were all different colors. Red, yellow, pink, and purple. It looked like a rainbow on the ground. The field was endless. The smell was sweet. I rode a bicycle through the field. It was sunny and breezy. I took amazing photos. It was a breathtaking sight. I felt happy and peaceful there.",
        "word_count": 67,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'flower field', 'tulips', 'rainbow', 'endless', 'breezy', 'amazing', 'breathtaking', 'sight', 'peaceful'. >Band 5: 'Breathtaking', 'endless'. Not Band 7: Good range.",
        "grammar_reason": "[GRA6] Key evidence: 'looked like', 'There were'. >Band 5: Comparisons and existential there correct. Not Band 7: Simple structure.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a beautiful place.\n\nTranscript: I went to a flower field in the Netherlands. There were millions of tulips. They were all different colors. Red, yellow, pink, and purple. It looked like a rainbow on the ground. The field was endless. The smell was sweet. I rode a bicycle through the field. It was sunny and breezy. I took amazing photos. It was a breathtaking sight. I felt happy and peaceful there.\n\nWord Count: 67 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'flower field', 'tulips', 'rainbow', 'endless', 'breezy', 'amazing', 'breathtaking', 'sight', 'peaceful'. \n\n>Band 5: 'Breathtaking', 'endless'.\n\nNot Band 7: Good range.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'looked like', 'There were'. \n\n>Band 5: Comparisons and existential there correct.\n\nNot Band 7: Simple structure.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_325",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a friend.",
        "transcript_cleaned": "My friend Peter is an architect. He designs houses. He is very creative. He draws plans on his computer. He is also hardworking. He often works late. But he is always cheerful. He likes to tell jokes. He is a good person to be around. He gives me advice about my career. We have been friends since college. I value his opinion. He is a true friend.",
        "word_count": 67,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'architect', 'designs', 'creative', 'plans', 'hardworking', 'cheerful', 'jokes', 'advice', 'career', 'value', 'opinion', 'true friend'. >Band 5: 'True friend', 'cheerful'. Not Band 7: Standard vocab.",
        "grammar_reason": "[GRA6] Key evidence: 'person to be around', 'have been friends since'. >Band 5: Infinitives and present perfect correct. Not Band 7: Short sentences.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a friend.\n\nTranscript: My friend Peter is an architect. He designs houses. He is very creative. He draws plans on his computer. He is also hardworking. He often works late. But he is always cheerful. He likes to tell jokes. He is a good person to be around. He gives me advice about my career. We have been friends since college. I value his opinion. He is a true friend.\n\nWord Count: 67 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'architect', 'designs', 'creative', 'plans', 'hardworking', 'cheerful', 'jokes', 'advice', 'career', 'value', 'opinion', 'true friend'. \n\n>Band 5: 'True friend', 'cheerful'.\n\nNot Band 7: Standard vocab.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'person to be around', 'have been friends since'. \n\n>Band 5: Infinitives and present perfect correct.\n\nNot Band 7: Short sentences.\n\n**Micro flaws identified:**\n- none significant"
    }
]

with open(OUTPUT_FILE, 'a') as f:
    for sample in samples:
        json.dump(sample, f)
        f.write('\n')
