import json

OUTPUT_FILE = 'ielts-data/phase3/v76_review_output/jules1/jules1_batch04.jsonl'

samples = [
    {
        "sample_id": "syn_p2_v6_g6_326",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a historical building.",
        "transcript_cleaned": "I visited a castle in Scotland. It is a medieval fortress. It was built on a cliff. The view is panoramic. It has thick stone walls. It was used to defend the city. I saw old cannons there. The history is fascinating. It was a home for kings. Now it is a museum. I learned about battles. It is a well-preserved site. I recommend visiting it.",
        "word_count": 66,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'medieval', 'fortress', 'cliff', 'panoramic', 'defend', 'cannons', 'fascinating', 'museum', 'battles', 'well-preserved', 'recommend'. >Band 5: 'Well-preserved', 'panoramic'. Not Band 7: Good range.",
        "grammar_reason": "[GRA6] Key evidence: 'was built on', 'used to defend'. >Band 5: Passive voice and infinitive purpose correct. Not Band 7: Simple structure.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a historical building.\n\nTranscript: I visited a castle in Scotland. It is a medieval fortress. It was built on a cliff. The view is panoramic. It has thick stone walls. It was used to defend the city. I saw old cannons there. The history is fascinating. It was a home for kings. Now it is a museum. I learned about battles. It is a well-preserved site. I recommend visiting it.\n\nWord Count: 66 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'medieval', 'fortress', 'cliff', 'panoramic', 'defend', 'cannons', 'fascinating', 'museum', 'battles', 'well-preserved', 'recommend'. \n\n>Band 5: 'Well-preserved', 'panoramic'.\n\nNot Band 7: Good range.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'was built on', 'used to defend'. \n\n>Band 5: Passive voice and infinitive purpose correct.\n\nNot Band 7: Simple structure.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_327",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a difficult task.",
        "transcript_cleaned": "I had to learn a dance routine. It was for a school performance. I am not a good dancer. The steps were complicated. I had to memorize them. I practiced every day after school. My legs were sore. I made many mistakes. But I did not give up. My friends encouraged me. On the day of the show, I was nervous. But I performed well. It was a rewarding experience.",
        "word_count": 71,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'routine', 'performance', 'dancer', 'complicated', 'memorize', 'practiced', 'sore', 'mistakes', 'give up', 'encouraged', 'rewarding'. >Band 5: 'Complicated', 'rewarding'. Not Band 7: Standard vocab.",
        "grammar_reason": "[GRA6] Key evidence: 'had to learn', 'did not give up'. >Band 5: Modals and phrasal verbs correct. Not Band 7: Short sentences.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a difficult task.\n\nTranscript: I had to learn a dance routine. It was for a school performance. I am not a good dancer. The steps were complicated. I had to memorize them. I practiced every day after school. My legs were sore. I made many mistakes. But I did not give up. My friends encouraged me. On the day of the show, I was nervous. But I performed well. It was a rewarding experience.\n\nWord Count: 71 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'routine', 'performance', 'dancer', 'complicated', 'memorize', 'practiced', 'sore', 'mistakes', 'give up', 'encouraged', 'rewarding'. \n\n>Band 5: 'Complicated', 'rewarding'.\n\nNot Band 7: Standard vocab.\n\n**Idiom present:** Yes\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'had to learn', 'did not give up'. \n\n>Band 5: Modals and phrasal verbs correct.\n\nNot Band 7: Short sentences.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_328",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a useful skill.",
        "transcript_cleaned": "I learned how to garden. It is a relaxing skill. I learned from my mother. She has a green thumb. I learned to plant seeds. I learned how to water and fertilize them. I grow vegetables like tomatoes and lettuce. It takes patience. I have to weed the garden. But seeing the plants grow is satisfying. I eat fresh vegetables from my garden. It is healthier and cheaper.",
        "word_count": 68,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'garden', 'relaxing', 'green thumb', 'seeds', 'fertilize', 'weed', 'satisfying', 'fresh', 'healthier'. >Band 5: 'Green thumb', 'fertilize'. Not Band 7: Good range.",
        "grammar_reason": "[GRA6] Key evidence: 'how to garden', 'seeing the plants grow is'. >Band 5: Infinitives and gerund subjects correct. Not Band 7: Simple structure.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a useful skill.\n\nTranscript: I learned how to garden. It is a relaxing skill. I learned from my mother. She has a green thumb. I learned to plant seeds. I learned how to water and fertilize them. I grow vegetables like tomatoes and lettuce. It takes patience. I have to weed the garden. But seeing the plants grow is satisfying. I eat fresh vegetables from my garden. It is healthier and cheaper.\n\nWord Count: 68 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'garden', 'relaxing', 'green thumb', 'seeds', 'fertilize', 'weed', 'satisfying', 'fresh', 'healthier'. \n\n>Band 5: 'Green thumb', 'fertilize'.\n\nNot Band 7: Good range.\n\n**Idiom present:** Yes\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'how to garden', 'seeing the plants grow is'. \n\n>Band 5: Infinitives and gerund subjects correct.\n\nNot Band 7: Simple structure.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_329",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a place.",
        "transcript_cleaned": "I went to a national park. It was a wildlife sanctuary. I saw many animals in their natural habitat. There were deer, bears, and birds. We drove through the park. It was like a safari. The forest was dense. The air was pure. I took many photos of the animals. It is important to protect wildlife. I learned about conservation. It was an educational trip.",
        "word_count": 66,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'national park', 'wildlife sanctuary', 'natural habitat', 'safari', 'dense', 'pure', 'protect', 'conservation', 'educational'. >Band 5: 'Sanctuary', 'conservation'. Not Band 7: Good range.",
        "grammar_reason": "[GRA6] Key evidence: 'animals in their natural habitat', 'important to protect'. >Band 5: Prepositional phrases and adjective + infinitive correct. Not Band 7: Short sentences.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a place.\n\nTranscript: I went to a national park. It was a wildlife sanctuary. I saw many animals in their natural habitat. There were deer, bears, and birds. We drove through the park. It was like a safari. The forest was dense. The air was pure. I took many photos of the animals. It is important to protect wildlife. I learned about conservation. It was an educational trip.\n\nWord Count: 66 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'national park', 'wildlife sanctuary', 'natural habitat', 'safari', 'dense', 'pure', 'protect', 'conservation', 'educational'. \n\n>Band 5: 'Sanctuary', 'conservation'.\n\nNot Band 7: Good range.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'animals in their natural habitat', 'important to protect'. \n\n>Band 5: Prepositional phrases and adjective + infinitive correct.\n\nNot Band 7: Short sentences.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_330",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a party.",
        "transcript_cleaned": "I attended a costume party. It was for Halloween. Everyone wore a costume. I dressed as a vampire. The house was decorated with spider webs. It looked spooky. There was scary music playing. We played games and danced. The food was themed. There were cookies shaped like fingers. It was creative. I had a lot of fun with my friends. It was a memorable night.",
        "word_count": 66,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'costume party', 'dressed as', 'vampire', 'decorated', 'spider webs', 'spooky', 'scary', 'themed', 'fingers', 'creative', 'memorable'. >Band 5: 'Spooky', 'themed'. Not Band 7: Good range.",
        "grammar_reason": "[GRA6] Key evidence: 'decorated with spider webs', 'shaped like fingers'. >Band 5: Passive voice and participle phrases correct. Not Band 7: Simple structure.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a party.\n\nTranscript: I attended a costume party. It was for Halloween. Everyone wore a costume. I dressed as a vampire. The house was decorated with spider webs. It looked spooky. There was scary music playing. We played games and danced. The food was themed. There were cookies shaped like fingers. It was creative. I had a lot of fun with my friends. It was a memorable night.\n\nWord Count: 66 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'costume party', 'dressed as', 'vampire', 'decorated', 'spider webs', 'spooky', 'scary', 'themed', 'fingers', 'creative', 'memorable'. \n\n>Band 5: 'Spooky', 'themed'.\n\nNot Band 7: Good range.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'decorated with spider webs', 'shaped like fingers'. \n\n>Band 5: Passive voice and participle phrases correct.\n\nNot Band 7: Simple structure.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_331",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a difficult decision.",
        "transcript_cleaned": "I had to decide on a career. I liked art and science. It was a hard choice. My parents wanted me to be a doctor. I wanted to be an artist. I was confused. I talked to a counselor. She gave me advice. She said I should follow my passion. I thought about it carefully. Finally, I chose graphic design. It combines art and technology. I am happy with my choice.",
        "word_count": 72,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'career', 'choice', 'confused', 'counselor', 'advice', 'passion', 'carefully', 'graphic design', 'combines', 'technology'. >Band 5: 'Combines', 'passion'. Not Band 7: Standard vocab.",
        "grammar_reason": "[GRA6] Key evidence: 'wanted me to be', 'should follow'. >Band 5: Verb patterns and modals correct. Not Band 7: Short sentences.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a difficult decision.\n\nTranscript: I had to decide on a career. I liked art and science. It was a hard choice. My parents wanted me to be a doctor. I wanted to be an artist. I was confused. I talked to a counselor. She gave me advice. She said I should follow my passion. I thought about it carefully. Finally, I chose graphic design. It combines art and technology. I am happy with my choice.\n\nWord Count: 72 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'career', 'choice', 'confused', 'counselor', 'advice', 'passion', 'carefully', 'graphic design', 'combines', 'technology'. \n\n>Band 5: 'Combines', 'passion'.\n\nNot Band 7: Standard vocab.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'wanted me to be', 'should follow'. \n\n>Band 5: Verb patterns and modals correct.\n\nNot Band 7: Short sentences.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_332",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a historical figure.",
        "transcript_cleaned": "I admire Mother Teresa. She was a nun. She dedicated her life to helping the poor. She lived in India. She started a charity. She cared for sick and dying people. She was selfless. She won the Nobel Peace Prize. She is a symbol of compassion. Her work inspired many people. I think she is a saint. Her legacy lives on. She taught us to love everyone.",
        "word_count": 68,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'nun', 'dedicated', 'charity', 'cared for', 'sick', 'dying', 'selfless', 'symbol', 'compassion', 'inspired', 'saint', 'legacy'. >Band 5: 'Selfless', 'compassion', 'legacy'. Not Band 7: Good range.",
        "grammar_reason": "[GRA6] Key evidence: 'dedicated her life to helping', 'taught us to love'. >Band 5: Gerunds after prepositions and infinitives correct. Not Band 7: Simple structure.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a historical figure.\n\nTranscript: I admire Mother Teresa. She was a nun. She dedicated her life to helping the poor. She lived in India. She started a charity. She cared for sick and dying people. She was selfless. She won the Nobel Peace Prize. She is a symbol of compassion. Her work inspired many people. I think she is a saint. Her legacy lives on. She taught us to love everyone.\n\nWord Count: 68 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'nun', 'dedicated', 'charity', 'cared for', 'sick', 'dying', 'selfless', 'symbol', 'compassion', 'inspired', 'saint', 'legacy'. \n\n>Band 5: 'Selfless', 'compassion', 'legacy'.\n\nNot Band 7: Good range.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'dedicated her life to helping', 'taught us to love'. \n\n>Band 5: Gerunds after prepositions and infinitives correct.\n\nNot Band 7: Simple structure.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_333",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a meal.",
        "transcript_cleaned": "I ate a traditional Indian meal. It was chicken curry. I ate it at a restaurant. It was spicy and flavorful. It had many spices like cumin and turmeric. I ate it with rice and naan bread. The aroma was strong. It made me hungry. I drank a mango lassi. It was sweet. I enjoyed the different tastes. Indian food is rich and varied. It was a satisfying dinner.",
        "word_count": 70,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'traditional', 'curry', 'flavorful', 'spices', 'cumin', 'turmeric', 'naan', 'aroma', 'lassi', 'tastes', 'rich', 'varied', 'satisfying'. >Band 5: 'Flavorful', 'varied'. Not Band 7: Specific food vocab.",
        "grammar_reason": "[GRA6] Key evidence: 'It made me hungry', 'It was... but'. >Band 5: Causative and compound sentences correct. Not Band 7: Simple structure.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a meal.\n\nTranscript: I ate a traditional Indian meal. It was chicken curry. I ate it at a restaurant. It was spicy and flavorful. It had many spices like cumin and turmeric. I ate it with rice and naan bread. The aroma was strong. It made me hungry. I drank a mango lassi. It was sweet. I enjoyed the different tastes. Indian food is rich and varied. It was a satisfying dinner.\n\nWord Count: 70 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'traditional', 'curry', 'flavorful', 'spices', 'cumin', 'turmeric', 'naan', 'aroma', 'lassi', 'tastes', 'rich', 'varied', 'satisfying'. \n\n>Band 5: 'Flavorful', 'varied'.\n\nNot Band 7: Specific food vocab.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'It made me hungry', 'It was... but'. \n\n>Band 5: Causative and compound sentences correct.\n\nNot Band 7: Simple structure.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_334",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a goal.",
        "transcript_cleaned": "My goal is to run a marathon. It is a long race. I need to be fit. I started training last month. I run three times a week. It is tiring, but I feel good. I want to challenge myself. I am increasing my distance slowly. I eat healthy food to fuel my body. I want to cross the finish line. It will be a great achievement. I am determined to do it.",
        "word_count": 74,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'marathon', 'race', 'fit', 'training', 'tiring', 'challenge', 'increasing', 'distance', 'fuel', 'finish line', 'achievement', 'determined'. >Band 5: 'Fuel', 'determined'. Not Band 7: Good range.",
        "grammar_reason": "[GRA6] Key evidence: 'need to be', 'increasing my distance'. >Band 5: Infinitives and progressive tenses correct. Not Band 7: Short sentences.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a goal.\n\nTranscript: My goal is to run a marathon. It is a long race. I need to be fit. I started training last month. I run three times a week. It is tiring, but I feel good. I want to challenge myself. I am increasing my distance slowly. I eat healthy food to fuel my body. I want to cross the finish line. It will be a great achievement. I am determined to do it.\n\nWord Count: 74 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'marathon', 'race', 'fit', 'training', 'tiring', 'challenge', 'increasing', 'distance', 'fuel', 'finish line', 'achievement', 'determined'. \n\n>Band 5: 'Fuel', 'determined'.\n\nNot Band 7: Good range.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'need to be', 'increasing my distance'. \n\n>Band 5: Infinitives and progressive tenses correct.\n\nNot Band 7: Short sentences.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_335",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a useful object.",
        "transcript_cleaned": "I use a blender. It is a kitchen gadget. I make smoothies with it. I put fruit and yogurt in. I press a button. It blends everything. It is fast and efficient. I have a healthy breakfast every day. It is easy to clean. It takes only a minute. I can also make soup. It is a versatile tool. I cannot live without it. It helps me eat more fruit.",
        "word_count": 71,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'blender', 'gadget', 'smoothies', 'yogurt', 'blends', 'efficient', 'versatile', 'tool'. >Band 5: 'Versatile', 'efficient'. Not Band 7: Standard kitchen vocab.",
        "grammar_reason": "[GRA6] Key evidence: 'easy to clean', 'helps me eat'. >Band 5: Adjective + infinitive and causative correct. Not Band 7: Very short sentences.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a useful object.\n\nTranscript: I use a blender. It is a kitchen gadget. I make smoothies with it. I put fruit and yogurt in. I press a button. It blends everything. It is fast and efficient. I have a healthy breakfast every day. It is easy to clean. It takes only a minute. I can also make soup. It is a versatile tool. I cannot live without it. It helps me eat more fruit.\n\nWord Count: 71 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'blender', 'gadget', 'smoothies', 'yogurt', 'blends', 'efficient', 'versatile', 'tool'. \n\n>Band 5: 'Versatile', 'efficient'.\n\nNot Band 7: Standard kitchen vocab.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'easy to clean', 'helps me eat'. \n\n>Band 5: Adjective + infinitive and causative correct.\n\nNot Band 7: Very short sentences.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_336",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a historical place.",
        "transcript_cleaned": "I visited Pompeii in Italy. It is an ancient Roman city. It was destroyed by a volcano. Mount Vesuvius erupted. The city was buried in ash. I walked through the ruins. I saw houses and temples. It was like going back in time. The preservation is amazing. I saw casts of people. It was sad but interesting. It is a world heritage site. I learned a lot about history.",
        "word_count": 69,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'ancient', 'destroyed', 'volcano', 'erupted', 'buried', 'ash', 'ruins', 'preservation', 'casts', 'heritage site'. >Band 5: 'Preservation', 'erupted'. Not Band 7: Good range.",
        "grammar_reason": "[GRA6] Key evidence: 'was destroyed by', 'was buried in'. >Band 5: Passive voice used correctly. Not Band 7: Simple structure.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a historical place.\n\nTranscript: I visited Pompeii in Italy. It is an ancient Roman city. It was destroyed by a volcano. Mount Vesuvius erupted. The city was buried in ash. I walked through the ruins. I saw houses and temples. It was like going back in time. The preservation is amazing. I saw casts of people. It was sad but interesting. It is a world heritage site. I learned a lot about history.\n\nWord Count: 69 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'ancient', 'destroyed', 'volcano', 'erupted', 'buried', 'ash', 'ruins', 'preservation', 'casts', 'heritage site'. \n\n>Band 5: 'Preservation', 'erupted'.\n\nNot Band 7: Good range.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'was destroyed by', 'was buried in'. \n\n>Band 5: Passive voice used correctly.\n\nNot Band 7: Simple structure.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_337",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a piece of clothes.",
        "transcript_cleaned": "I like my sneakers. They are running shoes. They are comfortable and light. I wear them every day. They are stylish. They are white with red stripes. I bought them on sale. They were a bargain. I can walk for hours in them. They support my feet. I clean them often to keep them white. They match my jeans. I think good shoes are essential.",
        "word_count": 66,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'sneakers', 'running shoes', 'comfortable', 'light', 'stylish', 'stripes', 'sale', 'bargain', 'support', 'match', 'essential'. >Band 5: 'Bargain', 'essential'. Not Band 7: Standard vocab.",
        "grammar_reason": "[GRA6] Key evidence: 'to keep them white', 'walk for hours'. >Band 5: Infinitives of purpose and prepositional phrases correct. Not Band 7: Very short sentences.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a piece of clothes.\n\nTranscript: I like my sneakers. They are running shoes. They are comfortable and light. I wear them every day. They are stylish. They are white with red stripes. I bought them on sale. They were a bargain. I can walk for hours in them. They support my feet. I clean them often to keep them white. They match my jeans. I think good shoes are essential.\n\nWord Count: 66 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'sneakers', 'running shoes', 'comfortable', 'light', 'stylish', 'stripes', 'sale', 'bargain', 'support', 'match', 'essential'. \n\n>Band 5: 'Bargain', 'essential'.\n\nNot Band 7: Standard vocab.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'to keep them white', 'walk for hours'. \n\n>Band 5: Infinitives of purpose and prepositional phrases correct.\n\nNot Band 7: Very short sentences.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_338",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a difficult decision.",
        "transcript_cleaned": "I had to decide what to study in college. It was a major decision. I liked science and literature. I was torn. My parents advised me to study science. They said it has better job prospects. But I loved reading books. I thought about my future. I realized I could be a teacher if I studied literature. So I chose literature. I followed my passion. I have no regrets.",
        "word_count": 70,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'college', 'major decision', 'literature', 'torn', 'advised', 'prospects', 'realized', 'passion', 'regrets'. >Band 5: 'Prospects', 'regrets'. Not Band 7: Good range.",
        "grammar_reason": "[GRA6] Key evidence: 'could be a teacher if', 'advised me to study'. >Band 5: 2nd conditional and verb patterns correct. Not Band 7: Short sentences.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a difficult decision.\n\nTranscript: I had to decide what to study in college. It was a major decision. I liked science and literature. I was torn. My parents advised me to study science. They said it has better job prospects. But I loved reading books. I thought about my future. I realized I could be a teacher if I studied literature. So I chose literature. I followed my passion. I have no regrets.\n\nWord Count: 70 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'college', 'major decision', 'literature', 'torn', 'advised', 'prospects', 'realized', 'passion', 'regrets'. \n\n>Band 5: 'Prospects', 'regrets'.\n\nNot Band 7: Good range.\n\n**Idiom present:** Yes\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'could be a teacher if', 'advised me to study'. \n\n>Band 5: 2nd conditional and verb patterns correct.\n\nNot Band 7: Short sentences.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_339",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a plant.",
        "transcript_cleaned": "I like the aloe vera plant. It is a succulent. It has thick, green leaves. It contains a gel. The gel is useful. It heals burns and cuts. It is medicinal. I have one in my kitchen. It is easy to grow. It does not need much water. It likes sunlight. It is a practical plant. I use it for my skin too. It is a natural remedy.",
        "word_count": 69,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'succulent', 'thick', 'leaves', 'contains', 'gel', 'heals', 'burns', 'medicinal', 'sunlight', 'practical', 'remedy'. >Band 5: 'Succulent', 'medicinal', 'remedy'. Not Band 7: Good range.",
        "grammar_reason": "[GRA6] Key evidence: 'easy to grow', 'does not need'. >Band 5: Adjective + infinitive and negative present simple correct. Not Band 7: Very short sentences.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a plant.\n\nTranscript: I like the aloe vera plant. It is a succulent. It has thick, green leaves. It contains a gel. The gel is useful. It heals burns and cuts. It is medicinal. I have one in my kitchen. It is easy to grow. It does not need much water. It likes sunlight. It is a practical plant. I use it for my skin too. It is a natural remedy.\n\nWord Count: 69 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'succulent', 'thick', 'leaves', 'contains', 'gel', 'heals', 'burns', 'medicinal', 'sunlight', 'practical', 'remedy'. \n\n>Band 5: 'Succulent', 'medicinal', 'remedy'.\n\nNot Band 7: Good range.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'easy to grow', 'does not need'. \n\n>Band 5: Adjective + infinitive and negative present simple correct.\n\nNot Band 7: Very short sentences.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_340",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a historical figure.",
        "transcript_cleaned": "I admire George Washington. He was the first president of the USA. He was a general in the army. He led his country to independence. He was a brave leader. He is on the dollar bill. He is a founding father. He helped write the constitution. He was honest and fair. There is a story about a cherry tree. He said, \"I cannot tell a lie.\" He is a role model.",
        "word_count": 72,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'president', 'general', 'army', 'independence', 'brave', 'founding father', 'constitution', 'honest', 'fair', 'role model'. >Band 5: 'Founding father', 'constitution'. Not Band 7: Standard history vocab.",
        "grammar_reason": "[GRA6] Key evidence: 'led his country to', 'helped write'. >Band 5: Past tense and phrasal verbs correct. Not Band 7: Simple structure.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a historical figure.\n\nTranscript: I admire George Washington. He was the first president of the USA. He was a general in the army. He led his country to independence. He was a brave leader. He is on the dollar bill. He is a founding father. He helped write the constitution. He was honest and fair. There is a story about a cherry tree. He said, \"I cannot tell a lie.\" He is a role model.\n\nWord Count: 72 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'president', 'general', 'army', 'independence', 'brave', 'founding father', 'constitution', 'honest', 'fair', 'role model'. \n\n>Band 5: 'Founding father', 'constitution'.\n\nNot Band 7: Standard history vocab.\n\n**Idiom present:** Yes\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'led his country to', 'helped write'. \n\n>Band 5: Past tense and phrasal verbs correct.\n\nNot Band 7: Simple structure.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_341",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a difficult task.",
        "transcript_cleaned": "I had to plan a trip for my family. It was a big responsibility. I booked flights and hotels. I researched activities. I made an itinerary. It took a lot of time. I compared prices to save money. I was worried about making mistakes. But everything went smoothly. My family enjoyed the trip. They thanked me for my hard work. I felt capable and organized. It was a good learning experience.",
        "word_count": 71,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'responsibility', 'booked', 'flights', 'researched', 'itinerary', 'compared prices', 'worried', 'smoothly', 'capable', 'organized', 'learning experience'. >Band 5: 'Itinerary', 'capable'. Not Band 7: Good range.",
        "grammar_reason": "[GRA6] Key evidence: 'compared prices to save', 'worried about making'. >Band 5: Infinitive of purpose and preposition + gerund correct. Not Band 7: Short sentences.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a difficult task.\n\nTranscript: I had to plan a trip for my family. It was a big responsibility. I booked flights and hotels. I researched activities. I made an itinerary. It took a lot of time. I compared prices to save money. I was worried about making mistakes. But everything went smoothly. My family enjoyed the trip. They thanked me for my hard work. I felt capable and organized. It was a good learning experience.\n\nWord Count: 71 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'responsibility', 'booked', 'flights', 'researched', 'itinerary', 'compared prices', 'worried', 'smoothly', 'capable', 'organized', 'learning experience'. \n\n>Band 5: 'Itinerary', 'capable'.\n\nNot Band 7: Good range.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'compared prices to save', 'worried about making'. \n\n>Band 5: Infinitive of purpose and preposition + gerund correct.\n\nNot Band 7: Short sentences.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_342",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a difficult decision.",
        "transcript_cleaned": "I had to decide whether to move to a new city. I got a job offer in London. It was a great opportunity. But I would have to leave my friends. I was happy in my hometown. I made a list of pros and cons. The job paid well, but London is expensive. It was a risk. I talked to my parents. They encouraged me to go. I decided to move. It was the right choice.",
        "word_count": 77,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'job offer', 'opportunity', 'hometown', 'pros and cons', 'expensive', 'risk', 'encouraged', 'right choice'. >Band 5: 'Pros and cons', 'opportunity'. Not Band 7: Standard vocab.",
        "grammar_reason": "[GRA6] Key evidence: 'whether to move', 'would have to leave'. >Band 5: Noun clause and modal perfect correct. Not Band 7: Simple structure.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a difficult decision.\n\nTranscript: I had to decide whether to move to a new city. I got a job offer in London. It was a great opportunity. But I would have to leave my friends. I was happy in my hometown. I made a list of pros and cons. The job paid well, but London is expensive. It was a risk. I talked to my parents. They encouraged me to go. I decided to move. It was the right choice.\n\nWord Count: 77 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'job offer', 'opportunity', 'hometown', 'pros and cons', 'expensive', 'risk', 'encouraged', 'right choice'. \n\n>Band 5: 'Pros and cons', 'opportunity'.\n\nNot Band 7: Standard vocab.\n\n**Idiom present:** Yes\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'whether to move', 'would have to leave'. \n\n>Band 5: Noun clause and modal perfect correct.\n\nNot Band 7: Simple structure.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_343",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a friend.",
        "transcript_cleaned": "My friend Maria is very creative. She likes painting and drawing. She is also stylish. She makes her own clothes. She is unique. We met in art class. We have similar interests. We visit galleries together. She inspires me to be creative. She is honest and trustworthy. I can tell her anything. We laugh a lot. She is a true friend. I am glad I met her.",
        "word_count": 67,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'creative', 'painting', 'drawing', 'stylish', 'unique', 'interests', 'galleries', 'inspires', 'honest', 'trustworthy', 'true friend'. >Band 5: 'Trustworthy', 'unique'. Not Band 7: Good range.",
        "grammar_reason": "[GRA6] Key evidence: 'makes her own', 'inspires me to be'. >Band 5: Causative and infinitive structures correct. Not Band 7: Very short sentences.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a friend.\n\nTranscript: My friend Maria is very creative. She likes painting and drawing. She is also stylish. She makes her own clothes. She is unique. We met in art class. We have similar interests. We visit galleries together. She inspires me to be creative. She is honest and trustworthy. I can tell her anything. We laugh a lot. She is a true friend. I am glad I met her.\n\nWord Count: 67 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'creative', 'painting', 'drawing', 'stylish', 'unique', 'interests', 'galleries', 'inspires', 'honest', 'trustworthy', 'true friend'. \n\n>Band 5: 'Trustworthy', 'unique'.\n\nNot Band 7: Good range.\n\n**Idiom present:** Yes\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'makes her own', 'inspires me to be'. \n\n>Band 5: Causative and infinitive structures correct.\n\nNot Band 7: Very short sentences.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_344",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a historical figure.",
        "transcript_cleaned": "I admire Charles Darwin. He was a biologist. He is famous for his theory of evolution. He traveled on a ship called the Beagle. He visited the Galapagos Islands. He studied animals there. He wrote a book called \"The Origin of Species\". It changed science forever. Some people disagreed with him. But his ideas were correct. He was a curious and observant man. He is a scientific giant.",
        "word_count": 68,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'biologist', 'theory', 'evolution', 'species', 'disagreed', 'curious', 'observant', 'scientific giant'. >Band 5: 'Evolution', 'observant'. Not Band 7: Standard science vocab.",
        "grammar_reason": "[GRA6] Key evidence: 'famous for his theory', 'called The Origin'. >Band 5: Prepositional phrases and participle phrases correct. Not Band 7: Simple structure.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a historical figure.\n\nTranscript: I admire Charles Darwin. He was a biologist. He is famous for his theory of evolution. He traveled on a ship called the Beagle. He visited the Galapagos Islands. He studied animals there. He wrote a book called \"The Origin of Species\". It changed science forever. Some people disagreed with him. But his ideas were correct. He was a curious and observant man. He is a scientific giant.\n\nWord Count: 68 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'biologist', 'theory', 'evolution', 'species', 'disagreed', 'curious', 'observant', 'scientific giant'. \n\n>Band 5: 'Evolution', 'observant'.\n\nNot Band 7: Standard science vocab.\n\n**Idiom present:** Yes\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'famous for his theory', 'called The Origin'. \n\n>Band 5: Prepositional phrases and participle phrases correct.\n\nNot Band 7: Simple structure.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_345",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a game.",
        "transcript_cleaned": "I play Sudoku. It is a word game with numbers. You have a grid. You must fill it with numbers 1 to 9. No number can repeat in a row or column. It is a puzzle. It challenges my brain. I play it on my phone. There are different levels. Easy, medium, and hard. I like the hard ones. It takes time to solve. It improves logic. It is addictive.",
        "word_count": 70,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'grid', 'repeat', 'row', 'column', 'puzzle', 'challenges', 'levels', 'solve', 'logic', 'addictive'. >Band 5: 'Grid', 'addictive'. Not Band 7: Good range.",
        "grammar_reason": "[GRA6] Key evidence: 'must fill it', 'takes time to solve'. >Band 5: Modals and infinitives correct. Not Band 7: Short sentences.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a game.\n\nTranscript: I play Sudoku. It is a word game with numbers. You have a grid. You must fill it with numbers 1 to 9. No number can repeat in a row or column. It is a puzzle. It challenges my brain. I play it on my phone. There are different levels. Easy, medium, and hard. I like the hard ones. It takes time to solve. It improves logic. It is addictive.\n\nWord Count: 70 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'grid', 'repeat', 'row', 'column', 'puzzle', 'challenges', 'levels', 'solve', 'logic', 'addictive'. \n\n>Band 5: 'Grid', 'addictive'.\n\nNot Band 7: Good range.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'must fill it', 'takes time to solve'. \n\n>Band 5: Modals and infinitives correct.\n\nNot Band 7: Short sentences.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_346",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a historical place.",
        "transcript_cleaned": "I visited Stonehenge in England. It is a prehistoric monument. It consists of a ring of standing stones. The stones are huge. It is a mystery how they got there. People think it was for astronomy or religion. It is very old. It was built thousands of years ago. It is a world heritage site. I walked around it. It felt spiritual. It is an iconic symbol of Britain.",
        "word_count": 70,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'prehistoric', 'monument', 'consists of', 'ring', 'astronomy', 'religion', 'heritage site', 'spiritual', 'iconic', 'symbol'. >Band 5: 'Prehistoric', 'iconic'. Not Band 7: Good range.",
        "grammar_reason": "[GRA6] Key evidence: 'mystery how they got', 'think it was for'. >Band 5: Indirect questions and past tense correct. Not Band 7: Simple structure.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a historical place.\n\nTranscript: I visited Stonehenge in England. It is a prehistoric monument. It consists of a ring of standing stones. The stones are huge. It is a mystery how they got there. People think it was for astronomy or religion. It is very old. It was built thousands of years ago. It is a world heritage site. I walked around it. It felt spiritual. It is an iconic symbol of Britain.\n\nWord Count: 70 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'prehistoric', 'monument', 'consists of', 'ring', 'astronomy', 'religion', 'heritage site', 'spiritual', 'iconic', 'symbol'. \n\n>Band 5: 'Prehistoric', 'iconic'.\n\nNot Band 7: Good range.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'mystery how they got', 'think it was for'. \n\n>Band 5: Indirect questions and past tense correct.\n\nNot Band 7: Simple structure.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_347",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a difficult task.",
        "transcript_cleaned": "I had to give a speech at my sister's wedding. I was the best man. I had to write a funny and touching speech. I am not a writer. It was hard. I thought about our childhood memories. I wrote a draft. I practiced in front of my mirror. I was nervous on the wedding day. But when I spoke, everyone laughed and clapped. I felt proud. It was a success.",
        "word_count": 71,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'speech', 'best man', 'touching', 'childhood memories', 'draft', 'practiced', 'nervous', 'laughed', 'clapped', 'proud', 'success'. >Band 5: 'Touching', 'draft'. Not Band 7: Standard event vocab.",
        "grammar_reason": "[GRA6] Key evidence: 'had to give', 'But when I spoke'. >Band 5: Modals and time clauses correct. Not Band 7: Very short sentences.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a difficult task.\n\nTranscript: I had to give a speech at my sister's wedding. I was the best man. I had to write a funny and touching speech. I am not a writer. It was hard. I thought about our childhood memories. I wrote a draft. I practiced in front of my mirror. I was nervous on the wedding day. But when I spoke, everyone laughed and clapped. I felt proud. It was a success.\n\nWord Count: 71 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'speech', 'best man', 'touching', 'childhood memories', 'draft', 'practiced', 'nervous', 'laughed', 'clapped', 'proud', 'success'. \n\n>Band 5: 'Touching', 'draft'.\n\nNot Band 7: Standard event vocab.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'had to give', 'But when I spoke'. \n\n>Band 5: Modals and time clauses correct.\n\nNot Band 7: Very short sentences.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_348",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a useful skill.",
        "transcript_cleaned": "I learned to edit videos. It is a creative skill. I use software on my computer. I can cut and join clips. I add music and text. I make videos for YouTube. It was difficult to learn the software. There are many tools. I watched tutorials. Now I am proficient. I can make professional-looking videos. It takes time but it is fun. I can express my ideas visually.",
        "word_count": 69,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'edit', 'creative', 'software', 'clips', 'tutorials', 'proficient', 'professional-looking', 'express', 'visually'. >Band 5: 'Proficient', 'visually'. Not Band 7: Good range.",
        "grammar_reason": "[GRA6] Key evidence: 'difficult to learn', 'There are many'. >Band 5: Adjective + infinitive and existential there correct. Not Band 7: Simple structure.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a useful skill.\n\nTranscript: I learned to edit videos. It is a creative skill. I use software on my computer. I can cut and join clips. I add music and text. I make videos for YouTube. It was difficult to learn the software. There are many tools. I watched tutorials. Now I am proficient. I can make professional-looking videos. It takes time but it is fun. I can express my ideas visually.\n\nWord Count: 69 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'edit', 'creative', 'software', 'clips', 'tutorials', 'proficient', 'professional-looking', 'express', 'visually'. \n\n>Band 5: 'Proficient', 'visually'.\n\nNot Band 7: Good range.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'difficult to learn', 'There are many'. \n\n>Band 5: Adjective + infinitive and existential there correct.\n\nNot Band 7: Simple structure.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_349",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a party.",
        "transcript_cleaned": "I went to a surprise party for my sister. It was her 18th birthday. We hid in the living room. When she came in, we shouted \"Surprise!\". She was shocked. She cried a little. We gave her gifts. We had a big cake. We danced to pop music. It was a lively party. My sister was very happy. She thanked us for the surprise. It was a night to remember.",
        "word_count": 71,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'surprise party', 'hid', 'shocked', 'gifts', 'pop music', 'lively', 'night to remember'. >Band 5: 'Lively', 'night to remember'. Not Band 7: Idiom used correctly but common.",
        "grammar_reason": "[GRA6] Key evidence: 'When she came in', 'thanked us for'. >Band 5: Time clause and prepositional phrases correct. Not Band 7: Short sentences.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a party.\n\nTranscript: I went to a surprise party for my sister. It was her 18th birthday. We hid in the living room. When she came in, we shouted \"Surprise!\". She was shocked. She cried a little. We gave her gifts. We had a big cake. We danced to pop music. It was a lively party. My sister was very happy. She thanked us for the surprise. It was a night to remember.\n\nWord Count: 71 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'surprise party', 'hid', 'shocked', 'gifts', 'pop music', 'lively', 'night to remember'. \n\n>Band 5: 'Lively', 'night to remember'.\n\nNot Band 7: Idiom used correctly but common.\n\n**Idiom present:** Yes\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'When she came in', 'thanked us for'. \n\n>Band 5: Time clause and prepositional phrases correct.\n\nNot Band 7: Short sentences.\n\n**Micro flaws identified:**\n- none significant"
    },
    {
        "sample_id": "syn_p2_v6_g6_350",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a movie.",
        "transcript_cleaned": "I watched the movie \"Avatar\". It is a science fiction movie. It is set on a planet called Pandora. The visuals are stunning. The creatures are blue and tall. It is about a war between humans and aliens. The story is emotional. I liked the special effects. They were realistic. The movie has a message about nature. We should protect our planet. It was a blockbuster. I watched it in 3D.",
        "word_count": 72,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {
            "complexity": "moderate",
            "accuracy": "good",
            "flexibility": "moderate"
        },
        "vocab_reason": "[LR6] Key evidence: 'science fiction', 'set on', 'planet', 'visuals', 'stunning', 'aliens', 'emotional', 'special effects', 'realistic', 'message', 'protect', 'blockbuster'. >Band 5: 'Blockbuster', 'stunning'. Not Band 7: Good range.",
        "grammar_reason": "[GRA6] Key evidence: 'planet called Pandora', 'war between humans and aliens'. >Band 5: Participle phrases and prepositions correct. Not Band 7: Simple structure.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a movie.\n\nTranscript: I watched the movie \"Avatar\". It is a science fiction movie. It is set on a planet called Pandora. The visuals are stunning. The creatures are blue and tall. It is about a war between humans and aliens. The story is emotional. I liked the special effects. They were realistic. The movie has a message about nature. We should protect our planet. It was a blockbuster. I watched it in 3D.\n\nWord Count: 72 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Key evidence: 'science fiction', 'set on', 'planet', 'visuals', 'stunning', 'aliens', 'emotional', 'special effects', 'realistic', 'message', 'protect', 'blockbuster'. \n\n>Band 5: 'Blockbuster', 'stunning'.\n\nNot Band 7: Good range.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Key evidence: 'planet called Pandora', 'war between humans and aliens'. \n\n>Band 5: Participle phrases and prepositions correct.\n\nNot Band 7: Simple structure.\n\n**Micro flaws identified:**\n- none significant"
    }
]

with open(OUTPUT_FILE, 'a') as f:
    for sample in samples:
        json.dump(sample, f)
        f.write('\n')
