import os
import json

def create_dir(path):
    os.makedirs(path, exist_ok=True)

cam15_l1 = {
  "id": "cambridge_15_listening_test_1",
  "title": "Cam 15 - Listening Test 1",
  "description": "Tuyển tập từ vựng 'Key Words' (Band 7.0+) từ Cambridge IELTS 15 Listening Test 1.",
  "wordCount": 35,
  "category": "Listening",
  "color": "from-teal-500 to-green-600",
  "isPro": True,
  "words": [
    {"word": "recruitment", "phonetic": "/rɪˈkruːtmənt/", "partOfSpeech": "Noun", "cefrLevel": "B2", "meaning": "The action of finding new people to join an organization.", "translation": "Sự tuyển dụng", "concept": "Tìm người làm việc.", "register": "Business", "grammar_note": "", "synonyms": ["hiring"], "collocations": ["recruitment agency"], "contexts": [{"sentence": "Becky mostly recruits temporary staff.", "translation": "Becky chủ yếu tuyển nhân viên tạm thời."}], "level": "seed"},
    {"word": "clerical", "phonetic": "/ˈklerɪkl/", "partOfSpeech": "Adjective", "cefrLevel": "C1", "meaning": "Concerned with routine office work.", "translation": "Hành chính", "concept": "Công việc bàn giấy.", "register": "Formal", "grammar_note": "", "synonyms": ["administrative"], "collocations": ["clerical work"], "contexts": [{"sentence": "It's mainly clerical jobs.", "translation": "Chủ yếu là công việc văn thư."}], "level": "seed"},
    {"word": "temporary", "phonetic": "/ˈtemprəri/", "partOfSpeech": "Adjective", "cefrLevel": "B1", "meaning": "Lasting for only a limited period.", "translation": "Tạm thời", "concept": "Không lâu dài.", "register": "General", "grammar_note": "", "synonyms": ["provisional"], "collocations": ["temporary staff"], "contexts": [{"sentence": "You're likely to be offered something temporary.", "translation": "Bạn có khả năng được đề nghị công việc tạm thời."}], "level": "seed"},
    {"word": "receptionist", "phonetic": "/rɪˈsepʃənɪst/", "partOfSpeech": "Noun", "cefrLevel": "A2", "meaning": "A person employed to answer the telephone and greet visitors.", "translation": "Lễ tân", "concept": "Người đón khách.", "register": "General", "grammar_note": "", "synonyms": ["front desk officer"], "collocations": ["hotel receptionist"], "contexts": [{"sentence": "They'll start you as a receptionist.", "translation": "Họ sẽ bắt đầu cho bạn làm lễ tân."}], "level": "seed"},
    {"word": "vacancy", "phonetic": "/ˈveɪkənsi/", "partOfSpeech": "Noun", "cefrLevel": "B2", "meaning": "An unoccupied position.", "translation": "Vị trí trống", "concept": "Chỗ khuyết.", "register": "Business", "grammar_note": "", "synonyms": ["opening"], "collocations": ["fill a vacancy"], "contexts": [{"sentence": "She's busy filling vacancies.", "translation": "Cô ấy bận rộn lấp đầy các vị trí trống."}], "level": "seed"},
    {"word": "admin", "phonetic": "/ˈædmɪn/", "partOfSpeech": "Noun", "cefrLevel": "B2", "meaning": "Administration.", "translation": "Quản trị", "concept": "Hành chính.", "register": "Informal", "grammar_note": "", "synonyms": ["administration"], "collocations": ["admin assistant"], "contexts": [{"sentence": "It's mainly admin jobs.", "translation": "Chủ yếu là công việc hành chính."}], "level": "seed"},
    {"word": "sector", "phonetic": "/ˈsektə/", "partOfSpeech": "Noun", "cefrLevel": "B2", "meaning": "An area or portion that is distinct.", "translation": "Lĩnh vực", "concept": "Mảng công việc.", "register": "Formal", "grammar_note": "", "synonyms": ["field"], "collocations": ["finance sector"], "contexts": [{"sentence": "Becky recruits for the finance sector.", "translation": "Becky tuyển dụng cho lĩnh vực tài chính."}], "level": "seed"},
    {"word": "communication", "phonetic": "/kəˌmjuːnɪˈkeɪʃn/", "partOfSpeech": "Noun", "cefrLevel": "B1", "meaning": "The imparting or exchanging of information.", "translation": "Sự giao tiếp", "concept": "Trao đổi thông tin.", "register": "General", "grammar_note": "", "synonyms": ["interaction"], "collocations": ["communication skills"], "contexts": [{"sentence": "Communication really matters.", "translation": "Giao tiếp thực sự quan trọng."}], "level": "seed"},
    {"word": "feedback", "phonetic": "/ˈfiːdbæk/", "partOfSpeech": "Noun", "cefrLevel": "B2", "meaning": "Information about reactions to a product or performance.", "translation": "Phản hồi", "concept": "Ý kiến đóng góp.", "register": "General", "grammar_note": "", "synonyms": ["response"], "collocations": ["positive feedback"], "contexts": [{"sentence": "You'll get feedback on your performance.", "translation": "Bạn sẽ nhận được phản hồi."}], "level": "seed"},
    {"word": "personality", "phonetic": "/ˌpɜːsəˈnæləti/", "partOfSpeech": "Noun", "cefrLevel": "B1", "meaning": "The combination of characteristics that form an individual's character.", "translation": "Tính cách", "concept": "Bản chất.", "register": "General", "grammar_note": "", "synonyms": ["character"], "collocations": ["personality traits"], "contexts": [{"sentence": "They match the personality to the job.", "translation": "Họ khớp tính cách với công việc."}], "level": "seed"},
    {"word": "sibling", "phonetic": "/ˈsɪblɪŋ/", "partOfSpeech": "Noun", "cefrLevel": "C1", "meaning": "A brother or sister.", "translation": "Anh chị em ruột", "concept": "Người cùng cha mẹ.", "register": "Formal", "grammar_note": "", "synonyms": ["brother", "sister"], "collocations": ["sibling rivalry"], "contexts": [{"sentence": "It's hard to share attention with a sibling.", "translation": "Thật khó để chia sẻ sự chú ý với anh chị em."}], "level": "seed"},
    {"word": "rivalry", "phonetic": "/ˈraɪvlri/", "partOfSpeech": "Noun", "cefrLevel": "C1", "meaning": "Competition for the same objective.", "translation": "Sự ganh đua", "concept": "Cạnh tranh.", "register": "General", "grammar_note": "", "synonyms": ["competition"], "collocations": ["sibling rivalry"], "contexts": [{"sentence": "This leads to sibling rivalry.", "translation": "Điều này dẫn đến sự ganh đua."}], "level": "seed"},
    {"word": "nurture", "phonetic": "/ˈnɜːtʃə/", "partOfSpeech": "Verb", "cefrLevel": "C1", "meaning": "Care for and protect while they are growing.", "translation": "Nuôi dưỡng", "concept": "Chăm sóc.", "register": "Formal", "grammar_note": "", "synonyms": ["raise"], "collocations": ["nature vs nurture"], "contexts": [{"sentence": "It's a mix of nature and nurture.", "translation": "Đó là sự kết hợp giữa bản năng và nuôi dưỡng."}], "level": "seed"},
    {"word": "consensus", "phonetic": "/kənˈsensəs/", "partOfSpeech": "Noun", "cefrLevel": "C1", "meaning": "A general agreement.", "translation": "Sự đồng thuận", "concept": "Mọi người đồng ý.", "register": "Formal", "grammar_note": "", "synonyms": ["agreement"], "collocations": ["reach a consensus"], "contexts": [{"sentence": "There is no general consensus.", "translation": "Không có sự đồng thuận chung."}], "level": "seed"},
    {"word": "clamour", "phonetic": "/ˈklæmə/", "partOfSpeech": "Verb", "cefrLevel": "C2", "meaning": "Shout loudly and insistently.", "translation": "Đòi hỏi ầm ĩ", "concept": "Gây ồn ào.", "register": "Formal", "grammar_note": "", "synonyms": ["demand"], "collocations": ["clamour for attention"], "contexts": [{"sentence": "Middle children clamour for attention.", "translation": "Con thứ thường ồn ào đòi sự chú ý."}], "level": "seed"},
    {"word": "trait", "phonetic": "/treɪt/", "partOfSpeech": "Noun", "cefrLevel": "C1", "meaning": "A distinguishing quality or characteristic.", "translation": "Đặc điểm", "concept": "Nét riêng.", "register": "General", "grammar_note": "", "synonyms": ["characteristic"], "collocations": ["personality trait"], "contexts": [{"sentence": "Traits are linked to birth order.", "translation": "Đặc điểm liên quan đến thứ tự sinh."}], "level": "seed"},
    {"word": "verbalize", "phonetic": "/ˈvɜːbəlaɪz/", "partOfSpeech": "Verb", "cefrLevel": "C2", "meaning": "Express in words.", "translation": "Diễn đạt bằng lời", "concept": "Nói ra.", "register": "Formal", "grammar_note": "", "synonyms": ["express"], "collocations": ["verbalize thoughts"], "contexts": [{"sentence": "They learn to verbalize their needs.", "translation": "Họ học cách diễn đạt nhu cầu bằng lời."}], "level": "seed"},
    {"word": "tolerance", "phonetic": "/ˈtɒlərəns/", "partOfSpeech": "Noun", "cefrLevel": "B2", "meaning": "The ability to tolerate something.", "translation": "Sự khoan dung", "concept": "Chịu đựng.", "register": "General", "grammar_note": "", "synonyms": ["patience"], "collocations": ["high tolerance"], "contexts": [{"sentence": "They develop a high level of tolerance.", "translation": "Họ phát triển mức độ khoan dung cao."}], "level": "seed"},
    {"word": "marginalized", "phonetic": "/ˈmɑːdʒɪnəlaɪzd/", "partOfSpeech": "Adjective", "cefrLevel": "C1", "meaning": "Treated as insignificant.", "translation": "Bị ra rìa", "concept": "Bị coi thường.", "register": "Formal", "grammar_note": "", "synonyms": ["sidelined"], "collocations": ["feel marginalized"], "contexts": [{"sentence": "Middle children feel marginalized.", "translation": "Con thứ cảm thấy bị ra rìa."}], "level": "seed"},
    {"word": "eucalyptus", "phonetic": "/ˌjuːkəˈlɪptəs/", "partOfSpeech": "Noun", "cefrLevel": "C1", "meaning": "An evergreen tree.", "translation": "Cây bạch đàn", "concept": "Cây lấy gỗ.", "register": "Technical", "grammar_note": "", "synonyms": ["gum tree"], "collocations": ["eucalyptus oil"], "contexts": [{"sentence": "The eucalyptus is important in Australia.", "translation": "Bạch đàn rất quan trọng ở Úc."}], "level": "seed"},
    {"word": "biodiversity", "phonetic": "/ˌbaɪəʊdaɪˈvɜːsəti/", "partOfSpeech": "Noun", "cefrLevel": "C1", "meaning": "The variety of plant and animal life.", "translation": "Sự đa dạng sinh học", "concept": "Nhiều loài sống.", "register": "Academic", "grammar_note": "", "synonyms": ["ecological variety"], "collocations": ["loss of biodiversity"], "contexts": [{"sentence": "It impacts biodiversity.", "translation": "Nó ảnh hưởng đến đa dạng sinh học."}], "level": "seed"},
    {"word": "nectar", "phonetic": "/ˈnektə/", "partOfSpeech": "Noun", "cefrLevel": "C2", "meaning": "A sugary fluid in flowers.", "translation": "Mật hoa", "concept": "Thức ăn của ong.", "register": "Technical", "grammar_note": "", "synonyms": [], "collocations": ["sweet nectar"], "contexts": [{"sentence": "It provides nectar for bees.", "translation": "Nó cung cấp mật hoa cho ong."}], "level": "seed"},
    {"word": "indigenous", "phonetic": "/ɪnˈdɪdʒənəs/", "partOfSpeech": "Adjective", "cefrLevel": "C2", "meaning": "Originating naturally in a place.", "translation": "Bản địa", "concept": "Vốn có ở đó.", "register": "Formal", "grammar_note": "", "synonyms": ["native"], "collocations": ["indigenous species"], "contexts": [{"sentence": "It is indigenous to Australia.", "translation": "Nó là loài bản địa của Úc."}], "level": "seed"},
    {"word": "cultivation", "phonetic": "/ˌkʌltɪˈveɪʃn/", "partOfSpeech": "Noun", "cefrLevel": "C1", "meaning": "The action of cultivating land.", "translation": "Sự trồng trọt", "concept": "Canh tác.", "register": "Formal", "grammar_note": "", "synonyms": ["farming"], "collocations": ["intensive cultivation"], "contexts": [{"sentence": "Cultivation has spread worldwide.", "translation": "Việc trồng trọt đã lan rộng."}], "level": "seed"},
    {"word": "disinfect", "phonetic": "/ˌdɪsɪnˈfekt/", "partOfSpeech": "Verb", "cefrLevel": "C1", "meaning": "Clean with a chemical.", "translation": "Khử trùng", "concept": "Làm sạch vi khuẩn.", "register": "Medical", "grammar_note": "", "synonyms": ["sterilize"], "collocations": ["disinfect a wound"], "contexts": [{"sentence": "The leaves were used to disinfect.", "translation": "Lá được dùng để khử trùng."}], "level": "seed"},
    {"word": "extraction", "phonetic": "/ɪkˈstrækʃn/", "partOfSpeech": "Noun", "cefrLevel": "C1", "meaning": "The action of taking out.", "translation": "Sự chiết xuất", "concept": "Lấy ra.", "register": "Technical", "grammar_note": "", "synonyms": ["removal"], "collocations": ["oil extraction"], "contexts": [{"sentence": "Oil extraction is an industry.", "translation": "Khai thác dầu là một ngành công nghiệp."}], "level": "seed"},
    {"word": "hazard", "phonetic": "/ˈhæzəd/", "partOfSpeech": "Noun", "cefrLevel": "B2", "meaning": "A danger or risk.", "translation": "Mối nguy hiểm", "concept": "Nguy cơ.", "register": "General", "grammar_note": "", "synonyms": ["danger"], "collocations": ["fire hazard"], "contexts": [{"sentence": "The dry leaves are a fire hazard.", "translation": "Lá khô là một mối nguy hiểm hỏa hoạn."}], "level": "seed"},
    {"word": "shelter", "phonetic": "/ˈʃeltə/", "partOfSpeech": "Noun", "cefrLevel": "B1", "meaning": "A place giving protection.", "translation": "Nơi trú ẩn", "concept": "Chỗ che chở.", "register": "General", "grammar_note": "", "synonyms": ["protection"], "collocations": ["take shelter"], "contexts": [{"sentence": "It provides shelter for animals.", "translation": "Nó cung cấp nơi trú ẩn cho động vật."}], "level": "seed"},
    {"word": "prematurely", "phonetic": "/ˌpreməˈtʃʊəli/", "partOfSpeech": "Adverb", "cefrLevel": "C1", "meaning": "Before the due time.", "translation": "Quá sớm", "concept": "Sớm hơn dự kiến.", "register": "Formal", "grammar_note": "", "synonyms": ["early"], "collocations": ["die prematurely"], "contexts": [{"sentence": "The trees were dying prematurely.", "translation": "Cây đang chết quá sớm."}], "level": "seed"},
    {"word": "indiscriminate", "phonetic": "/ˌɪndɪˈskrɪmɪnət/", "partOfSpeech": "Adjective", "cefrLevel": "C2", "meaning": "Done at random without judgment.", "translation": "Bừa bãi", "concept": "Không phân biệt.", "register": "Formal", "grammar_note": "", "synonyms": ["random"], "collocations": ["indiscriminate use"], "contexts": [{"sentence": "Indiscriminate clearing caused problems.", "translation": "Việc phá rừng bừa bãi gây ra vấn đề."}], "level": "seed"},
    {"word": "lime", "phonetic": "/laɪm/", "partOfSpeech": "Noun", "cefrLevel": "B2", "meaning": "A white alkaline substance.", "translation": "Vôi", "concept": "Chất xử lý đất.", "register": "Technical", "grammar_note": "", "synonyms": [], "collocations": ["lime wash"], "contexts": [{"sentence": "Lime was used to treat the soil.", "translation": "Vôi được dùng để xử lý đất."}], "level": "seed"},
    {"word": "inject", "phonetic": "/ɪnˈdʒekt/", "partOfSpeech": "Verb", "cefrLevel": "C1", "meaning": "Drive a liquid into a body.", "translation": "Tiêm / Bơm", "concept": "Đưa chất lỏng vào.", "register": "Medical", "grammar_note": "", "synonyms": ["administer"], "collocations": ["inject a solution"], "contexts": [{"sentence": "They inject a solution into trees.", "translation": "Họ tiêm dung dịch vào cây."}], "level": "seed"},
    {"word": "preserve", "phonetic": "/prɪˈzɜːv/", "partOfSpeech": "Verb", "cefrLevel": "B2", "meaning": "Maintain in its original state.", "translation": "Bảo tồn", "concept": "Giữ gìn.", "register": "General", "grammar_note": "", "synonyms": ["conserve"], "collocations": ["preserve nature"], "contexts": [{"sentence": "We need to preserve forests.", "translation": "Chúng ta cần bảo tồn rừng."}], "level": "seed"},
    {"word": "strict", "phonetic": "/strɪkt/", "partOfSpeech": "Adjective", "cefrLevel": "B2", "meaning": "Demanding that rules are obeyed.", "translation": "Nghiêm ngặt", "concept": "Phải tuân thủ.", "register": "General", "grammar_note": "", "synonyms": ["stringent"], "collocations": ["strict rules"], "contexts": [{"sentence": "There are strict regulations.", "translation": "Có những quy định nghiêm ngặt."}], "level": "seed"},
    {"word": "ecosystem", "phonetic": "/ˈiːkəʊsɪstəm/", "partOfSpeech": "Noun", "cefrLevel": "C1", "meaning": "A biological community of interacting organisms.", "translation": "Hệ sinh thái", "concept": "Môi trường sống.", "register": "Academic", "grammar_note": "", "synonyms": [], "collocations": ["fragile ecosystem"], "contexts": [{"sentence": "It plays a role in the ecosystem.", "translation": "Nó đóng vai trò trong hệ sinh thái."}], "level": "seed"}
  ]
}

def write_json(path, data):
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=4, ensure_ascii=False)

create_dir("output/cambridge_15")
write_json("output/cambridge_15/listening_test_1.json", cam15_l1)
print("File generated.")
