import json

OUTPUT_FILE = "ielts-data/phase3/v76_review_output/synthetic_batches/batch_p2_10.jsonl"

samples = [
    # 481. V7/G6 - Movie (Seen)
    {
        "sample_id": "syn_p2_v7_g6_0481",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a movie you have seen recently.",
        "transcript_cleaned": "I recently watched a documentary called 'The Social Dilemma', which explore the impact of social media. It features interviews with tech experts who exposing the manipulative algorithms used by platforms. I found it incredibly eye-opening and disturbing. The film reveal how companies harvesting our data for profit. It made me rethink my own digital habits. Although the topic is serious, the presentation were engaging. Some scenes was dramatized, which I think detracting from the message. Overall, it is a thought-provoking film that everyone should watch.",
        "word_count": 89,
        "response_type": "long_turn",
        "micro_flaws": ["agreement: 'which explore' should be 'explores'", "grammar: 'who exposing' should be 'who expose'", "agreement: 'film reveal' should be 'reveals'", "grammar: 'companies harvesting' should be 'companies harvest'", "agreement: 'presentation were' should be 'was'", "agreement: 'scenes was' should be 'were'", "grammar: 'think detracting' should be 'think detracted'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR7] Vocabulary: 'documentary', 'impact', 'tech experts', 'manipulative', 'algorithms', 'platforms', 'eye-opening', 'disturbing', 'harvesting', 'profit', 'digital habits', 'presentation', 'dramatized', 'detracting', 'thought-provoking'. Precise and sophisticated. >Band 6: Uses less common words effectively. Not Band 8: Some phrases are standard.",
        "grammar_reason": "[GRA6] Uses complex structures but with frequent errors. Subject-verb agreement errors ('explore', 'reveal', 'presentation were'). Verb form errors ('exposing', 'harvesting', 'detracting'). >Band 5: Attempts complex sentences. Not Band 7: Errors are frequent.",
        "vocabulary": 7,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a movie you have seen recently.\n\nTranscript: I recently watched a documentary called 'The Social Dilemma', which explore the impact of social media. It features interviews with tech experts who exposing the manipulative algorithms used by platforms. I found it incredibly eye-opening and disturbing. The film reveal how companies harvesting our data for profit. It made me rethink my own digital habits. Although the topic is serious, the presentation were engaging. Some scenes was dramatized, which I think detracting from the message. Overall, it is a thought-provoking film that everyone should watch.\n\nWord Count: 89 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses sophisticated vocabulary: 'manipulative', 'algorithms', 'eye-opening', 'thought-provoking'. Precise meaning.\n\n>Band 6: Advanced vocabulary.\n\nNot Band 8: Lacks native-like flow.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Frequent errors in verb forms and agreement. 'Which explore', 'who exposing' are incorrect.\n\n>Band 5: Complex sentences attempted.\n\nNot Band 7: Systematic errors.\n\n**Micro flaws identified:**\n- 'which explore' should be 'explores'\n- 'who exposing' should be 'who expose'\n- 'film reveal' should be 'reveals'\n- 'companies harvesting' should be 'companies harvest'\n- 'presentation were' should be 'was'\n- 'scenes was' should be 'scenes were'\n- 'think detracting' should be 'think detracted'"
    },
    # 482. V7/G6 - Place (Shopping)
    {
        "sample_id": "syn_p2_v7_g6_0482",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a place where you like to shop.",
        "transcript_cleaned": "I enjoy shopping at a local flea market that is held every Sunday. It is a treasure trove of vintage clothing and antique furniture. I love the thrill of rummaging through piles of items to find a bargain. The vendors is very friendly and often haggling with customers. The atmosphere are always vibrant and chaotic. I have found some unique artifacts there that is one-of-a-kind. It is much more interesting than visiting a sterile shopping mall. However, it can getting very crowded, which I find annoying.",
        "word_count": 89,
        "response_type": "long_turn",
        "micro_flaws": ["agreement: 'vendors is' should be 'are'", "grammar: 'often haggling' should be 'often haggle'", "agreement: 'atmosphere are' should be 'is'", "agreement: 'artifacts... that is' should be 'are'", "grammar: 'can getting' should be 'can get'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR7] Vocabulary: 'flea market', 'treasure trove', 'vintage', 'antique', 'thrill', 'rummaging', 'bargain', 'vendors', 'haggling', 'vibrant', 'chaotic', 'artifacts', 'one-of-a-kind', 'sterile'. Uses idioms and less common words. >Band 6: Good range of descriptive vocabulary. Not Band 8: Some errors in usage.",
        "grammar_reason": "[GRA6] Uses complex structures but has frequent errors in agreement and verb forms ('vendors is', 'haggling', 'atmosphere are', 'can getting'). >Band 5: Attempts complex sentences. Not Band 7: Errors are noticeable.",
        "vocabulary": 7,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a place where you like to shop.\n\nTranscript: I enjoy shopping at a local flea market that is held every Sunday. It is a treasure trove of vintage clothing and antique furniture. I love the thrill of rummaging through piles of items to find a bargain. The vendors is very friendly and often haggling with customers. The atmosphere are always vibrant and chaotic. I have found some unique artifacts there that is one-of-a-kind. It is much more interesting than visiting a sterile shopping mall. However, it can getting very crowded, which I find annoying.\n\nWord Count: 89 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses idiomatic language: 'treasure trove', 'one-of-a-kind'. Precise vocabulary: 'rummaging', 'haggling'.\n\n>Band 6: Good range.\n\nNot Band 8: Slightly forced usage.\n\n**Idiom present:** Yes ('treasure trove')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Frequent errors in verb forms ('can getting', 'haggling') and agreement ('vendors is').\n\n>Band 5: Complex sentences attempted.\n\nNot Band 7: Errors are frequent.\n\n**Micro flaws identified:**\n- 'vendors is' should be 'vendors are'\n- 'often haggling' should be 'often haggle'\n- 'atmosphere are' should be 'atmosphere is'\n- 'artifacts... that is' should be 'are'\n- 'can getting' should be 'can get'"
    },
    # 483. V7/G6 - Event (Music)
    {
        "sample_id": "syn_p2_v7_g6_0483",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a live music event you went to.",
        "transcript_cleaned": "I attended a jazz festival in New Orleans, which were an unforgettable experience. The musicians was incredibly talented, improvising complex melodies effortlessly. The venue, an open-air park, providing a relaxed setting. I was mesmerizing by the soulful saxophone solos. The crowd were diverse, united by their love for music. We sat on the grass, swaying to the rhythm. Although it starting to rain, nobody left. The spontaneity of the performances were what made it special. It was a celebration of culture and creativity.",
        "word_count": 86,
        "response_type": "long_turn",
        "micro_flaws": ["agreement: 'which were' should be 'was'", "agreement: 'musicians was' should be 'were'", "grammar: 'providing' should be 'provided'", "grammar: 'was mesmerizing' should be 'was mesmerized'", "agreement: 'crowd were' should be 'was'", "grammar: 'it starting' should be 'it started'", "agreement: 'performances were' should be 'was' (referring to spontaneity)"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR7] Vocabulary: 'jazz festival', 'unforgettable', 'improvising', 'complex melodies', 'effortlessly', 'venue', 'open-air', 'mesmerized', 'soulful', 'diverse', 'united', 'swaying', 'rhythm', 'spontaneity', 'celebration'. Precise musical vocabulary. >Band 6: Good range. Not Band 8: Some errors in word form.",
        "grammar_reason": "[GRA6] Uses complex structures but has frequent errors. Agreement errors ('which were', 'musicians was', 'crowd were'). Verb form errors ('providing', 'starting'). >Band 5: Attempts complex sentences. Not Band 7: Errors are frequent.",
        "vocabulary": 7,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a live music event you went to.\n\nTranscript: I attended a jazz festival in New Orleans, which were an unforgettable experience. The musicians was incredibly talented, improvising complex melodies effortlessly. The venue, an open-air park, providing a relaxed setting. I was mesmerizing by the soulful saxophone solos. The crowd were diverse, united by their love for music. We sat on the grass, swaying to the rhythm. Although it starting to rain, nobody left. The spontaneity of the performances were what made it special. It was a celebration of culture and creativity.\n\nWord Count: 86 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses precise vocabulary: 'improvising', 'soulful', 'spontaneity'. Good range.\n\n>Band 6: Advanced words used.\n\nNot Band 8: Word form error ('mesmerizing').\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Frequent errors in agreement and verb forms ('musicians was', 'providing').\n\n>Band 5: Complex sentences attempted.\n\nNot Band 7: Systematic errors.\n\n**Micro flaws identified:**\n- 'which were' should be 'which was'\n- 'musicians was' should be 'musicians were'\n- 'providing' should be 'provided'\n- 'was mesmerizing' should be 'was mesmerized'\n- 'crowd were' should be 'crowd was'\n- 'it starting' should be 'it started'\n- 'performances were' should be 'was'"
    },
    # 484. V7/G6 - Person (Teacher)
    {
        "sample_id": "syn_p2_v7_g6_0484",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a teacher who inspired you.",
        "transcript_cleaned": "I want to talk about my literature teacher, Mr. Black. He was a charismatic individual who ignite my passion for reading. He engaging us with his dramatic storytelling. Unlike other teachers who relying on textbooks, he encouraged critical thinking. He possess an encyclopedic knowledge of classic novels. I was often awe-struck by his interpretations. He challenged me to look beyond the surface meaning. Because of his guidance, I pursuing a degree in English. He is a role model who I looking up to greatly.",
        "word_count": 86,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'who ignite' should be 'ignited'", "grammar: 'He engaging' should be 'He engaged'", "grammar: 'who relying' should be 'who relied'", "agreement: 'He possess' should be 'possessed'", "grammar: 'I pursuing' should be 'I pursued'", "grammar: 'who I looking' should be 'who I look'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR7] Vocabulary: 'literature', 'charismatic', 'ignite', 'passion', 'engaging', 'dramatic', 'textbooks', 'critical thinking', 'encyclopedic knowledge', 'classic novels', 'awe-struck', 'interpretations', 'surface meaning', 'guidance', 'role model'. Very sophisticated. >Band 6: Precise vocabulary. Not Band 8: Errors in word form.",
        "grammar_reason": "[GRA6] Uses complex structures but has frequent errors. Verb form errors are systematic ('ignite', 'engaging', 'relying', 'possess', 'pursuing'). >Band 5: Attempts complex sentences. Not Band 7: Errors are frequent.",
        "vocabulary": 7,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a teacher who inspired you.\n\nTranscript: I want to talk about my literature teacher, Mr. Black. He was a charismatic individual who ignite my passion for reading. He engaging us with his dramatic storytelling. Unlike other teachers who relying on textbooks, he encouraged critical thinking. He possess an encyclopedic knowledge of classic novels. I was often awe-struck by his interpretations. He challenged me to look beyond the surface meaning. Because of his guidance, I pursuing a degree in English. He is a role model who I looking up to greatly.\n\nWord Count: 86 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses sophisticated vocabulary: 'charismatic', 'encyclopedic', 'awe-struck'. Precise.\n\n>Band 6: Advanced vocabulary.\n\nNot Band 8: Errors affect accuracy.\n\n**Idiom present:** Yes ('looking up to')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Frequent errors in verb forms ('ignite', 'engaging', 'relying'). Complex structures used but flawed.\n\n>Band 5: Complex sentences attempted.\n\nNot Band 7: Systematic errors.\n\n**Micro flaws identified:**\n- 'who ignite' should be 'ignited'\n- 'He engaging' should be 'He engaged'\n- 'who relying' should be 'who relied'\n- 'He possess' should be 'He possessed'\n- 'I pursuing' should be 'I pursued'\n- 'who I looking' should be 'who I look'"
    },
    # 485. V7/G6 - Activity (Skill)
    {
        "sample_id": "syn_p2_v7_g6_0485",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a skill you improved.",
        "transcript_cleaned": "I have been working on improving my public speaking skills, which was a daunting prospect for me. I used to be petrified of speaking in front of a crowd. To overcoming this fear, I joined a Toastmasters club. The members giving me constructive feedback on my body language and tone. I learned to articulate my ideas more clearly. It requiring a lot of practice and perseverance. Gradually, my confidence growing. Now, I can deliver presentations without stuttering. It has been a transformative journey that have boosted my self-esteem significantly.",
        "word_count": 92,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'To overcoming' should be 'To overcome'", "grammar: 'members giving' should be 'members gave'", "grammar: 'It requiring' should be 'It required'", "grammar: 'confidence growing' should be 'confidence grew'", "agreement: 'journey that have' should be 'has'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR7] Vocabulary: 'public speaking', 'daunting prospect', 'petrified', 'constructive feedback', 'body language', 'tone', 'articulate', 'perseverance', 'deliver presentations', 'stuttering', 'transformative journey', 'boosted', 'self-esteem'. Very sophisticated. >Band 6: Precise vocabulary. Not Band 8: Errors in word form.",
        "grammar_reason": "[GRA6] Uses complex structures but has frequent errors. Verb form errors ('overcoming', 'giving', 'requiring', 'growing'). Agreement error ('that have'). >Band 5: Attempts complex sentences. Not Band 7: Errors are frequent.",
        "vocabulary": 7,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a skill you improved.\n\nTranscript: I have been working on improving my public speaking skills, which was a daunting prospect for me. I used to be petrified of speaking in front of a crowd. To overcoming this fear, I joined a Toastmasters club. The members giving me constructive feedback on my body language and tone. I learned to articulate my ideas more clearly. It requiring a lot of practice and perseverance. Gradually, my confidence growing. Now, I can deliver presentations without stuttering. It has been a transformative journey that have boosted my self-esteem significantly.\n\nWord Count: 92 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses sophisticated vocabulary: 'daunting', 'petrified', 'articulate', 'transformative'. Precise.\n\n>Band 6: Advanced vocabulary.\n\nNot Band 8: Errors affect accuracy.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Frequent errors in verb forms ('overcoming', 'giving'). Complex structures used but flawed.\n\n>Band 5: Complex sentences attempted.\n\nNot Band 7: Systematic errors.\n\n**Micro flaws identified:**\n- 'To overcoming' should be 'To overcome'\n- 'members giving' should be 'members gave'\n- 'It requiring' should be 'It required'\n- 'confidence growing' should be 'confidence grew'\n- 'journey that have' should be 'has'"
    },
    # 486. V7/G6 - Object (Gift)
    {
        "sample_id": "syn_p2_v7_g6_0486",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a gift you received that was useful.",
        "transcript_cleaned": "My parents gave me a noise-cancelling headphone for my birthday, which is an indispensable gadget for me. I am easily distracted by background noise when I studying. These headphones has exceptional sound quality. They allowing me to immerse myself in my work completely. I also using them when I commute on the noisy subway. It create a personal sanctuary for me. The battery life is impressive, lasting for days. It was a thoughtful and practical gift that I appreciating greatly.",
        "word_count": 84,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'when I studying' should be 'when I am studying'", "agreement: 'headphones has' should be 'have'", "grammar: 'They allowing' should be 'They allow'", "grammar: 'I also using' should be 'I also use'", "agreement: 'It create' should be 'It creates'", "grammar: 'I appreciating' should be 'I appreciate'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR7] Vocabulary: 'noise-cancelling', 'indispensable', 'gadget', 'distracted', 'background noise', 'exceptional', 'immerse', 'commute', 'subway', 'sanctuary', 'battery life', 'impressive', 'thoughtful', 'practical'. Uses less common words effectively. >Band 6: Good range. Not Band 8: Some errors in word form.",
        "grammar_reason": "[GRA6] Uses complex structures but has frequent errors. Verb form errors ('studying', 'allowing', 'using', 'appreciating'). Agreement errors ('headphones has', 'It create'). >Band 5: Attempts complex sentences. Not Band 7: Errors are frequent.",
        "vocabulary": 7,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a gift you received that was useful.\n\nTranscript: My parents gave me a noise-cancelling headphone for my birthday, which is an indispensable gadget for me. I am easily distracted by background noise when I studying. These headphones has exceptional sound quality. They allowing me to immerse myself in my work completely. I also using them when I commute on the noisy subway. It create a personal sanctuary for me. The battery life is impressive, lasting for days. It was a thoughtful and practical gift that I appreciating greatly.\n\nWord Count: 84 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses topic words: 'indispensable', 'immerse', 'sanctuary'. Precise meaning.\n\n>Band 6: Advanced vocabulary.\n\nNot Band 8: Errors affect accuracy.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Frequent errors in verb forms and agreement ('studying', 'headphones has'). Complex structures used but flawed.\n\n>Band 5: Complex sentences attempted.\n\nNot Band 7: Systematic errors.\n\n**Micro flaws identified:**\n- 'when I studying' should be 'when I am studying'\n- 'headphones has' should be 'headphones have'\n- 'They allowing' should be 'They allow'\n- 'I also using' should be 'I also use'\n- 'It create' should be 'It creates'\n- 'I appreciating' should be 'I appreciate'"
    },
    # 487. V7/G6 - Place (Nature)
    {
        "sample_id": "syn_p2_v7_g6_0487",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a natural place you like.",
        "transcript_cleaned": "I love visiting a secluded lake in the mountains, which offers a tranquil escape from the city. The water is crystal clear, reflecting the surrounding peaks like a mirror. It is a pristine environment, untouched by human development. I enjoy hiking through the dense forest to reach it. The fresh air are invigorating. Sometimes I spotting wildlife like deer and eagles. The silence is profound, broken only by the chirping of birds. It is a place where I can rejuvenating my spirit. I wish I can go there more often.",
        "word_count": 92,
        "response_type": "long_turn",
        "micro_flaws": ["agreement: 'air are' should be 'is'", "grammar: 'I spotting' should be 'I spot'", "grammar: 'can rejuvenating' should be 'can rejuvenate'", "grammar: 'wish I can' should be 'wish I could'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR7] Vocabulary: 'secluded', 'tranquil escape', 'crystal clear', 'reflecting', 'peaks', 'pristine', 'untouched', 'development', 'dense forest', 'invigorating', 'wildlife', 'profound', 'chirping', 'rejuvenating'. Uses descriptive vocabulary well. >Band 6: Good range of adjectives. Not Band 8: Some errors in usage.",
        "grammar_reason": "[GRA6] Uses complex structures but has frequent errors. Agreement error ('air are'). Verb form errors ('spotting', 'rejuvenating'). Modal error ('wish I can'). >Band 5: Attempts complex sentences. Not Band 7: Errors are frequent.",
        "vocabulary": 7,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a natural place you like.\n\nTranscript: I love visiting a secluded lake in the mountains, which offers a tranquil escape from the city. The water is crystal clear, reflecting the surrounding peaks like a mirror. It is a pristine environment, untouched by human development. I enjoy hiking through the dense forest to reach it. The fresh air are invigorating. Sometimes I spotting wildlife like deer and eagles. The silence is profound, broken only by the chirping of birds. It is a place where I can rejuvenating my spirit. I wish I can go there more often.\n\nWord Count: 92 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses descriptive words: 'secluded', 'pristine', 'invigorating', 'rejuvenating'. Clear meaning.\n\n>Band 6: Advanced vocabulary.\n\nNot Band 8: Errors affect accuracy.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Frequent errors in verb forms and agreement ('air are', 'I spotting'). Complex structures used but flawed.\n\n>Band 5: Complex sentences attempted.\n\nNot Band 7: Systematic errors.\n\n**Micro flaws identified:**\n- 'air are' should be 'air is'\n- 'I spotting' should be 'I spot'\n- 'can rejuvenating' should be 'can rejuvenate'\n- 'wish I can' should be 'wish I could'"
    },
    # 488. V7/G6 - Activity (Hobby)
    {
        "sample_id": "syn_p2_v7_g6_0488",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a hobby you are interested in.",
        "transcript_cleaned": "I am interested in pottery, which is a therapeutic and creative outlet. It involves molding clay into functional shapes like bowls and vases. I took a workshop last month to learn the basics. The tactile sensation of the clay is very satisfying. However, using the potter's wheel requiring coordination and patience. My first attempt were a disaster; the bowl collapsed. But I kept trying until I succeeding. Glazing the pottery is also fun, adding vibrant colors. It is a rewarding hobby that allowing me to express myself artistically.",
        "word_count": 93,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'wheel requiring' should be 'wheel requires'", "agreement: 'attempt were' should be 'was'", "grammar: 'I succeeding' should be 'I succeeded'", "grammar: 'that allowing' should be 'that allows'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR7] Vocabulary: 'pottery', 'therapeutic', 'creative outlet', 'molding', 'clay', 'functional', 'workshop', 'basics', 'tactile', 'sensation', 'satisfying', 'coordination', 'patience', 'disaster', 'collapsed', 'glazing', 'vibrant', 'rewarding', 'artistically'. Very sophisticated. >Band 6: Precise vocabulary. Not Band 8: Errors in word form.",
        "grammar_reason": "[GRA6] Uses complex structures but has frequent errors. Verb form errors ('requiring', 'succeeding', 'allowing'). Agreement error ('attempt were'). >Band 5: Attempts complex sentences. Not Band 7: Errors are frequent.",
        "vocabulary": 7,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a hobby you are interested in.\n\nTranscript: I am interested in pottery, which is a therapeutic and creative outlet. It involves molding clay into functional shapes like bowls and vases. I took a workshop last month to learn the basics. The tactile sensation of the clay is very satisfying. However, using the potter's wheel requiring coordination and patience. My first attempt were a disaster; the bowl collapsed. But I kept trying until I succeeding. Glazing the pottery is also fun, adding vibrant colors. It is a rewarding hobby that allowing me to express myself artistically.\n\nWord Count: 93 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses topic words: 'therapeutic', 'tactile', 'coordination', 'artistically'. Meaning is clear.\n\n>Band 6: Advanced vocabulary.\n\nNot Band 8: Errors affect accuracy.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Frequent errors in verb forms ('requiring', 'succeeding'). Complex structures used but flawed.\n\n>Band 5: Complex sentences attempted.\n\nNot Band 7: Systematic errors.\n\n**Micro flaws identified:**\n- 'wheel requiring' should be 'wheel requires'\n- 'attempt were' should be 'attempt was'\n- 'I succeeding' should be 'I succeeded'\n- 'that allowing' should be 'that allows'"
    },
    # 489. V7/G6 - Event (Tradition)
    {
        "sample_id": "syn_p2_v7_g6_0489",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a tradition in your family.",
        "transcript_cleaned": "Every New Year's Eve, my family observing a special tradition. We gather to make dumplings from scratch, symbolizing wealth and prosperity. It is a communal activity where everyone participate. My grandmother prepare the filling with secret ingredients. We chatting and laughing while wrapping the dough. It is a time for bonding and reflecting on the past year. At midnight, we eating the dumplings and set off fireworks. This ritual reinforces our family values and unity. It is a cherished custom that I hoping to continue.",
        "word_count": 89,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'family observing' should be 'observes'", "agreement: 'everyone participate' should be 'participates'", "agreement: 'grandmother prepare' should be 'prepares'", "grammar: 'We chatting' should be 'We chat'", "grammar: 'we eating' should be 'we eat'", "grammar: 'I hoping' should be 'I hope'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR7] Vocabulary: 'observing', 'tradition', 'scratch', 'symbolizing', 'wealth', 'prosperity', 'communal', 'participate', 'filling', 'ingredients', 'dough', 'bonding', 'reflecting', 'ritual', 'reinforces', 'values', 'unity', 'cherished', 'custom'. Very sophisticated. >Band 6: Precise vocabulary. Not Band 8: Errors in word form.",
        "grammar_reason": "[GRA6] Uses complex structures but has frequent errors. Verb form errors ('observing', 'chatting', 'eating', 'hoping'). Agreement errors ('everyone participate', 'grandmother prepare'). >Band 5: Attempts complex sentences. Not Band 7: Errors are frequent.",
        "vocabulary": 7,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a tradition in your family.\n\nTranscript: Every New Year's Eve, my family observing a special tradition. We gather to make dumplings from scratch, symbolizing wealth and prosperity. It is a communal activity where everyone participate. My grandmother prepare the filling with secret ingredients. We chatting and laughing while wrapping the dough. It is a time for bonding and reflecting on the past year. At midnight, we eating the dumplings and set off fireworks. This ritual reinforces our family values and unity. It is a cherished custom that I hoping to continue.\n\nWord Count: 89 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses topic words: 'symbolizing', 'prosperity', 'communal', 'ritual'. Meaning is clear.\n\n>Band 6: Advanced vocabulary.\n\nNot Band 8: Errors affect accuracy.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Frequent errors in verb forms and agreement ('observing', 'participate'). Complex structures used but flawed.\n\n>Band 5: Complex sentences attempted.\n\nNot Band 7: Systematic errors.\n\n**Micro flaws identified:**\n- 'family observing' should be 'family observes'\n- 'everyone participate' should be 'everyone participates'\n- 'grandmother prepare' should be 'grandmother prepares'\n- 'We chatting' should be 'We chat'\n- 'we eating' should be 'we eat'\n- 'I hoping' should be 'I hope'"
    },
    # 490. V7/G6 - Activity (Daily)
    {
        "sample_id": "syn_p2_v7_g6_0490",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe your favorite time of day.",
        "transcript_cleaned": "My favorite time of day is dusk, when the sun begins to set. The sky transforming into a canvas of vibrant colors. It is a fleeting moment of tranquility before the night falls. I usually taking a stroll in the park to unwind. The cool breeze is refreshing after a hectic day. I watching the city lights flicker on one by one. It is a time for introspection and gratitude. I feeling a sense of peace that is hard to describe. It is the perfect transition between work and rest.",
        "word_count": 92,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'sky transforming' should be 'transforms'", "grammar: 'I usually taking' should be 'take'", "grammar: 'I watching' should be 'watch'", "grammar: 'I feeling' should be 'feel'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR7] Vocabulary: 'dusk', 'transforming', 'canvas', 'vibrant', 'fleeting', 'tranquility', 'falls', 'stroll', 'unwind', 'breeze', 'refreshing', 'hectic', 'flicker', 'introspection', 'gratitude', 'transition'. Very sophisticated. >Band 6: Precise vocabulary. Not Band 8: Errors in word form.",
        "grammar_reason": "[GRA6] Uses complex structures but has frequent errors. Verb form errors ('transforming', 'taking', 'watching', 'feeling'). >Band 5: Attempts complex sentences. Not Band 7: Errors are frequent.",
        "vocabulary": 7,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe your favorite time of day.\n\nTranscript: My favorite time of day is dusk, when the sun begins to set. The sky transforming into a canvas of vibrant colors. It is a fleeting moment of tranquility before the night falls. I usually taking a stroll in the park to unwind. The cool breeze is refreshing after a hectic day. I watching the city lights flicker on one by one. It is a time for introspection and gratitude. I feeling a sense of peace that is hard to describe. It is the perfect transition between work and rest.\n\nWord Count: 92 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses descriptive words: 'dusk', 'fleeting', 'introspection', 'transition'. Clear meaning.\n\n>Band 6: Advanced vocabulary.\n\nNot Band 8: Errors affect accuracy.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Frequent errors in verb forms ('transforming', 'taking'). Complex structures used but flawed.\n\n>Band 5: Complex sentences attempted.\n\nNot Band 7: Systematic errors.\n\n**Micro flaws identified:**\n- 'sky transforming' should be 'transforms'\n- 'I usually taking' should be 'take'\n- 'I watching' should be 'watch'\n- 'I feeling' should be 'feel'"
    }
]

with open(OUTPUT_FILE, 'a', encoding='utf-8') as f:
    for sample in samples:
        f.write(json.dumps(sample) + '\n')
