import json

OUTPUT_FILE = "ielts-data/phase3/v76_review_output/synthetic_batches/batch_p2_07.jsonl"

samples = [
    # 321. V8/G9 - Book (Recommended)
    {
        "sample_id": "syn_p2_v8_g9_0321",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a book you would recommend to others.",
        "transcript_cleaned": "I wholeheartedly recommend 'Sapiens: A Brief History of Humankind' by Yuval Noah Harari. It is a thought-provoking exploration of our species' evolution, from the Cognitive Revolution to the present day. What makes it compelling is Harari's ability to synthesize complex historical trends into accessible narratives. He challenges conventional wisdom about agriculture, religion, and capitalism. Reading it fundamentally altered my perspective on human progress and our impact on the planet. The prose is lucid and engaging, filled with witty anecdotes. It is not merely a history book but a philosophical treatise. I believe it is essential reading for anyone seeking to understand the human condition.",
        "word_count": 115,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR8] Vocabulary: 'wholeheartedly', 'thought-provoking', 'exploration', 'evolution', 'compelling', 'synthesize', 'narratives', 'conventional wisdom', 'fundamentally altered', 'perspective', 'prose', 'lucid', 'engaging', 'anecdotes', 'treatise', 'human condition'.",
        "grammar_reason": "[GRA9] Full range. 'What makes it compelling is...' (Cleft). 'From the Cognitive Revolution to the present day' (Prepositional phrase). 'Reading it fundamentally altered...' (Gerund subject). 'Seeking to understand...' (Participle phrase). Error-free.",
        "vocabulary": 8,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a book you would recommend to others.\n\nTranscript: I wholeheartedly recommend 'Sapiens: A Brief History of Humankind' by Yuval Noah Harari. It is a thought-provoking exploration of our species' evolution, from the Cognitive Revolution to the present day. What makes it compelling is Harari's ability to synthesize complex historical trends into accessible narratives. He challenges conventional wisdom about agriculture, religion, and capitalism. Reading it fundamentally altered my perspective on human progress and our impact on the planet. The prose is lucid and engaging, filled with witty anecdotes. It is not merely a history book but a philosophical treatise. I believe it is essential reading for anyone seeking to understand the human condition.\n\nWord Count: 115 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses 'thought-provoking', 'synthesize', 'conventional wisdom', 'lucid', 'treatise'. Very sophisticated.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Excellent usage.\n\n**Idiom present:** Yes ('conventional wisdom')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Full range of structures used naturally. Cleft sentences, gerund subjects, and participle phrases are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    },
    # 322. V8/G9 - Tradition
    {
        "sample_id": "syn_p2_v8_g9_0322",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a tradition in your country.",
        "transcript_cleaned": "In my country, we observe the Lunar New Year with great fervor, a festival that unites the entire nation. It is a time-honored tradition that signifies the beginning of spring and the renewal of life. Families gather for a lavish reunion dinner, which is the centerpiece of the celebration. We exchange red envelopes containing money, symbolizing good fortune and warding off evil spirits. The streets are adorned with vibrant lanterns and calligraphy, creating a festive atmosphere. Firecrackers are set off to drive away bad luck and welcome prosperity. It is a period of introspection and reconciliation, where we pay respects to our ancestors. This cultural heritage fosters a deep sense of belonging and continuity among generations.",
        "word_count": 122,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR8] Vocabulary: 'fervor', 'time-honored', 'signifies', 'renewal', 'lavish', 'centerpiece', 'symbolizing', 'warding off', 'adorned', 'vibrant', 'calligraphy', 'introspection', 'reconciliation', 'heritage', 'fosters', 'continuity'.",
        "grammar_reason": "[GRA9] Full range. 'With great fervor' (Prepositional phrase). 'Which is the centerpiece...' (Relative clause). 'Containing money' (Participle phrase). 'Where we pay respects...' (Relative clause). Error-free.",
        "vocabulary": 8,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a tradition in your country.\n\nTranscript: In my country, we observe the Lunar New Year with great fervor, a festival that unites the entire nation. It is a time-honored tradition that signifies the beginning of spring and the renewal of life. Families gather for a lavish reunion dinner, which is the centerpiece of the celebration. We exchange red envelopes containing money, symbolizing good fortune and warding off evil spirits. The streets are adorned with vibrant lanterns and calligraphy, creating a festive atmosphere. Firecrackers are set off to drive away bad luck and welcome prosperity. It is a period of introspection and reconciliation, where we pay respects to our ancestors. This cultural heritage fosters a deep sense of belonging and continuity among generations.\n\nWord Count: 122 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses 'fervor', 'time-honored', 'lavish', 'adorned', 'introspection', 'reconciliation'. Very sophisticated.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Excellent usage.\n\n**Idiom present:** Yes ('warding off')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Full range of structures used naturally. Relative clauses and participle phrases are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    },
    # 323. V8/G9 - Achievement
    {
        "sample_id": "syn_p2_v8_g9_0323",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe an achievement you are proud of.",
        "transcript_cleaned": "I take immense pride in having completed a full marathon last year, a feat I never thought possible. It was a grueling endeavor that tested my physical and mental limits to the breaking point. I had spent six months adhering to a rigorous training schedule, often waking up before dawn to run in the cold. The race itself was arduous; around the 30-kilometer mark, I hit the proverbial 'wall' and wanted to quit. However, fueled by sheer determination and the cheering crowd, I powered through the overwhelming fatigue. Crossing the finish line was an indescribable feeling of euphoria and relief. This accomplishment taught me that with discipline and perseverance, any obstacle can be surmounted. It has instilled in me a lasting sense of resilience.",
        "word_count": 133,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR8] Vocabulary: 'immense', 'grueling', 'endeavor', 'adhering', 'rigorous', 'arduous', 'proverbial', 'fatigue', 'indescribable', 'euphoria', 'perseverance', 'surmounted', 'instilled', 'resilience'.",
        "grammar_reason": "[GRA9] Full range. 'Having completed a marathon' (Perfect Gerund). 'That tested my... limits' (Relative clause). 'Fueled by determination...' (Participle phrase). 'Crossing the finish line was...' (Gerund subject). Error-free.",
        "vocabulary": 8,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe an achievement you are proud of.\n\nTranscript: I take immense pride in having completed a full marathon last year, a feat I never thought possible. It was a grueling endeavor that tested my physical and mental limits to the breaking point. I had spent six months adhering to a rigorous training schedule, often waking up before dawn to run in the cold. The race itself was arduous; around the 30-kilometer mark, I hit the proverbial 'wall' and wanted to quit. However, fueled by sheer determination and the cheering crowd, I powered through the overwhelming fatigue. Crossing the finish line was an indescribable feeling of euphoria and relief. This accomplishment taught me that with discipline and perseverance, any obstacle can be surmounted. It has instilled in me a lasting sense of resilience.\n\nWord Count: 133 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses 'grueling', 'endeavor', 'rigorous', 'arduous', 'euphoria', 'surmounted', 'instilled'. Very sophisticated.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Excellent usage.\n\n**Idiom present:** Yes ('hit the wall')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Full range of structures used naturally. Perfect gerunds and participle phrases are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    },
    # 324. V8/G9 - Movie (Funny)
    {
        "sample_id": "syn_p2_v8_g9_0324",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a movie that made you laugh.",
        "transcript_cleaned": "I recently watched a brilliant satire called 'Don't Look Up', which I found hilariously poignant and timely. It is a dark comedy that lampoons modern society's indifference to scientific warnings and our obsession with trivia. The film features a stellar ensemble cast delivering razor-sharp dialogue that bites with wit. One scene where the politicians prioritize poll numbers over an impending asteroid apocalypse had me in stitches. The absurdity of the situations, though exaggerated for comedic effect, felt uncomfortably real. It cleverly uses humor to critique media sensationalism and political incompetence. While it deals with a grim subject, the comedic timing is impeccable throughout. It is a brilliant piece of cinema that entertains while provoking serious thought about our world.",
        "word_count": 130,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR8] Vocabulary: 'satire', 'hilariously', 'poignant', 'lampoons', 'indifference', 'ensemble cast', 'razor-sharp', 'impending', 'apocalypse', 'absurdity', 'exaggerated', 'sensationalism', 'incompetence', 'impeccable', 'provoking thought'.",
        "grammar_reason": "[GRA9] Full range. 'Which I found hilariously poignant' (Relative clause). 'Delivering razor-sharp dialogue' (Participle phrase). 'Where the politicians prioritize...' (Relative clause). 'Though exaggerated' (Elliptical clause). Error-free.",
        "vocabulary": 8,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a movie that made you laugh.\n\nTranscript: I recently watched a brilliant satire called 'Don't Look Up', which I found hilariously poignant and timely. It is a dark comedy that lampoons modern society's indifference to scientific warnings and our obsession with trivia. The film features a stellar ensemble cast delivering razor-sharp dialogue that bites with wit. One scene where the politicians prioritize poll numbers over an impending asteroid apocalypse had me in stitches. The absurdity of the situations, though exaggerated for comedic effect, felt uncomfortably real. It cleverly uses humor to critique media sensationalism and political incompetence. While it deals with a grim subject, the comedic timing is impeccable throughout. It is a brilliant piece of cinema that entertains while provoking serious thought about our world.\n\nWord Count: 130 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses 'satire', 'poignant', 'lampoons', 'sensationalism', 'impeccable'. Very sophisticated.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Excellent usage.\n\n**Idiom present:** Yes ('in stitches')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Full range of structures used naturally. Participle phrases and elliptical clauses are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    },
    # 325. V8/G9 - Trip (Short)
    {
        "sample_id": "syn_p2_v8_g9_0325",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a short trip you often take.",
        "transcript_cleaned": "I frequently take a weekend excursion to a nearby mountain resort to escape the relentless urban sprawl. The journey itself is therapeutic, winding through lush forests and scenic valleys that calm the mind. Upon arrival, I am immediately greeted by the crisp, invigorating mountain air. I usually spend my time hiking the rugged trails, which offers a welcome respite from the digital world. Reaching the summit provides a panoramic view that puts my daily trivialities into perspective. The solitude allows me to recharge my mental batteries and find inner peace. It is a cherished ritual that restores my equilibrium. Even a short sojourn in nature has a profound restorative effect on my overall well-being.",
        "word_count": 122,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR8] Vocabulary: 'excursion', 'urban sprawl', 'therapeutic', 'winding', 'lush', 'invigorating', 'respite', 'summit', 'panoramic', 'trivialities', 'perspective', 'solitude', 'recharge', 'ritual', 'equilibrium', 'sojourn', 'restorative'.",
        "grammar_reason": "[GRA9] Full range. 'To escape the urban sprawl' (Infinitive of purpose). 'Winding through lush forests' (Participle phrase). 'Upon arrival' (Prepositional phrase). 'Which offers a respite' (Relative clause). Error-free.",
        "vocabulary": 8,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a short trip you often take.\n\nTranscript: I frequently take a weekend excursion to a nearby mountain resort to escape the relentless urban sprawl. The journey itself is therapeutic, winding through lush forests and scenic valleys that calm the mind. Upon arrival, I am immediately greeted by the crisp, invigorating mountain air. I usually spend my time hiking the rugged trails, which offers a welcome respite from the digital world. Reaching the summit provides a panoramic view that puts my daily trivialities into perspective. The solitude allows me to recharge my mental batteries and find inner peace. It is a cherished ritual that restores my equilibrium. Even a short sojourn in nature has a profound restorative effect on my overall well-being.\n\nWord Count: 122 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses 'excursion', 'urban sprawl', 'therapeutic', 'respite', 'panoramic', 'equilibrium', 'sojourn'. Very sophisticated.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Excellent usage.\n\n**Idiom present:** Yes ('recharge my batteries')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Full range of structures used naturally. Participle phrases and relative clauses are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    },
    # 326. V8/G9 - Plant
    {
        "sample_id": "syn_p2_v8_g9_0326",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a plant you are familiar with.",
        "transcript_cleaned": "I am particularly fond of the bamboo plant, which is ubiquitous in my culture and revered for its elegance. It is renowned for its rapid growth rate and remarkable resilience in harsh conditions. Bamboo can thrive in diverse climates and poor soil conditions where other plants fail. What fascinates me is its incredible versatility; it is used in construction, cuisine, and even textiles. Symbolically, it represents strength and flexibility, bending with the wind but never breaking under pressure. I have a few bamboo stalks in my apartment, adding a touch of greenery and serenity to the space. Maintaining them is effortless as they require minimal care. To me, bamboo embodies the perfect harmony between practical utility and natural beauty.",
        "word_count": 125,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR8] Vocabulary: 'fond', 'ubiquitous', 'renowned', 'resilience', 'thrive', 'diverse', 'versatility', 'cuisine', 'textiles', 'symbolically', 'flexibility', 'stalks', 'greenery', 'serenity', 'minimal', 'embodies', 'utility'.",
        "grammar_reason": "[GRA9] Full range. 'Which is ubiquitous...' (Relative clause). 'What fascinates me is...' (Cleft sentence). 'Bending with the wind...' (Participle phrase). 'Adding a touch of greenery' (Participle phrase). Error-free.",
        "vocabulary": 8,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a plant you are familiar with.\n\nTranscript: I am particularly fond of the bamboo plant, which is ubiquitous in my culture and revered for its elegance. It is renowned for its rapid growth rate and remarkable resilience in harsh conditions. Bamboo can thrive in diverse climates and poor soil conditions where other plants fail. What fascinates me is its incredible versatility; it is used in construction, cuisine, and even textiles. Symbolically, it represents strength and flexibility, bending with the wind but never breaking under pressure. I have a few bamboo stalks in my apartment, adding a touch of greenery and serenity to the space. Maintaining them is effortless as they require minimal care. To me, bamboo embodies the perfect harmony between practical utility and natural beauty.\n\nWord Count: 125 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses 'ubiquitous', 'resilience', 'versatility', 'embodies'. Very sophisticated.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Excellent usage.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Full range of structures used naturally. Cleft sentences and participle phrases are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    },
    # 327. V8/G9 - Change (Life)
    {
        "sample_id": "syn_p2_v8_g9_0327",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a positive change in your life.",
        "transcript_cleaned": "Adopting a minimalist lifestyle was a transformative change I made two years ago that has improved my life. I felt overwhelmed by the clutter in my apartment and the constant, nagging urge to consume more. I decided to declutter ruthlessly, donating clothes and gadgets I didn't need to charity. The process was cathartic, liberating me from material attachment and the need to impress others. This shift allowed me to focus on meaningful experiences rather than accumulating possessions. I now spend my money on travel and learning new skills. The mental clarity I have gained is invaluable to me. It has simplified my daily routine and reduced my stress levels significantly. Living with intention has brought me a profound sense of contentment.",
        "word_count": 126,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR8] Vocabulary: 'minimalist', 'transformative', 'overwhelmed', 'clutter', 'urge', 'consume', 'declutter', 'ruthlessly', 'gadgets', 'cathartic', 'liberating', 'attachment', 'shift', 'possessions', 'clarity', 'invaluable', 'intention', 'contentment'.",
        "grammar_reason": "[GRA9] Full range. 'Adopting a minimalist lifestyle was...' (Gerund subject). 'Donating clothes... I didn't need' (Participle phrase + Relative clause). 'Rather than possessions' (Prepositional phrase). 'The mental clarity I have gained' (Relative clause). Error-free.",
        "vocabulary": 8,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a positive change in your life.\n\nTranscript: Adopting a minimalist lifestyle was a transformative change I made two years ago that has improved my life. I felt overwhelmed by the clutter in my apartment and the constant, nagging urge to consume more. I decided to declutter ruthlessly, donating clothes and gadgets I didn't need to charity. The process was cathartic, liberating me from material attachment and the need to impress others. This shift allowed me to focus on meaningful experiences rather than accumulating possessions. I now spend my money on travel and learning new skills. The mental clarity I have gained is invaluable to me. It has simplified my daily routine and reduced my stress levels significantly. Living with intention has brought me a profound sense of contentment.\n\nWord Count: 126 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses 'minimalist', 'transformative', 'clutter', 'cathartic', 'contentment'. Very sophisticated.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Excellent usage.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Full range of structures used naturally. Gerund subjects and participle phrases are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    },
    # 328. V8/G9 - Polluted Place
    {
        "sample_id": "syn_p2_v8_g9_0328",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a place you visited that was polluted.",
        "transcript_cleaned": "I was appalled by the condition of a coastal beach I visited during a holiday last summer. Once a pristine paradise, it was now littered with mountains of plastic debris and industrial waste. The water was murky, with an oily sheen on the surface that smelled of chemicals. It was heartbreaking to see seabirds entangled in fishing nets and struggling to move. The stench of decaying garbage was overpowering and nauseating. It was a stark reminder of human negligence and the urgent need for environmental stewardship. Local authorities seemed indifferent to the ecological degradation happening before their eyes. I participated in a cleanup drive, but the scale of the problem was daunting. It marred what should have been an idyllic vacation.",
        "word_count": 125,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR8] Vocabulary: 'appalled', 'pristine', 'paradise', 'littered', 'debris', 'industrial waste', 'murky', 'sheen', 'heartbreaking', 'entangled', 'stench', 'decaying', 'overpowering', 'stark', 'negligence', 'stewardship', 'indifferent', 'degradation', 'daunting', 'marred', 'idyllic'.",
        "grammar_reason": "[GRA9] Full range. 'Once a pristine paradise' (Appositive). 'With an oily sheen...' (Prepositional phrase). 'It was a stark reminder of...' (Noun phrase). 'What should have been...' (Noun clause). Error-free.",
        "vocabulary": 8,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a place you visited that was polluted.\n\nTranscript: I was appalled by the condition of a coastal beach I visited during a holiday last summer. Once a pristine paradise, it was now littered with mountains of plastic debris and industrial waste. The water was murky, with an oily sheen on the surface that smelled of chemicals. It was heartbreaking to see seabirds entangled in fishing nets and struggling to move. The stench of decaying garbage was overpowering and nauseating. It was a stark reminder of human negligence and the urgent need for environmental stewardship. Local authorities seemed indifferent to the ecological degradation happening before their eyes. I participated in a cleanup drive, but the scale of the problem was daunting. It marred what should have been an idyllic vacation.\n\nWord Count: 125 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses 'appalled', 'pristine', 'debris', 'murky', 'negligence', 'stewardship', 'idyllic'. Very sophisticated.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Excellent usage.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Full range of structures used naturally. Appositives and noun clauses are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    },
    # 329. V8/G9 - Clothes (Special)
    {
        "sample_id": "syn_p2_v8_g9_0329",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a piece of clothing you like to wear.",
        "transcript_cleaned": "My favorite garment is a vintage leather jacket passed down from my father when I turned eighteen. It has a rugged, weathered aesthetic that exudes character and timeless style. The leather is supple and has developed a unique patina over the years of wear. Wearing it gives me a sense of confidence and deep nostalgia for my father's youth. It is incredibly versatile, pairing well with both casual jeans and formal trousers. Despite its age, the craftsmanship is impeccable; the stitching remains intact and strong. It is not merely an article of clothing but a tangible link to my family history. I cherish it deeply and hope to pass it on to my own children one day.",
        "word_count": 121,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR8] Vocabulary: 'garment', 'vintage', 'rugged', 'weathered', 'aesthetic', 'exudes', 'supple', 'patina', 'versatile', 'craftsmanship', 'impeccable', 'stitching', 'intact', 'tangible', 'cherish'.",
        "grammar_reason": "[GRA9] Full range. 'Passed down from my father' (Participle phrase). 'That exudes character' (Relative clause). 'Despite its age' (Prepositional phrase). 'Not merely... but...' (Correlative). Error-free.",
        "vocabulary": 8,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a piece of clothing you like to wear.\n\nTranscript: My favorite garment is a vintage leather jacket passed down from my father when I turned eighteen. It has a rugged, weathered aesthetic that exudes character and timeless style. The leather is supple and has developed a unique patina over the years of wear. Wearing it gives me a sense of confidence and deep nostalgia for my father's youth. It is incredibly versatile, pairing well with both casual jeans and formal trousers. Despite its age, the craftsmanship is impeccable; the stitching remains intact and strong. It is not merely an article of clothing but a tangible link to my family history. I cherish it deeply and hope to pass it on to my own children one day.\n\nWord Count: 121 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses 'garment', 'rugged', 'aesthetic', 'exudes', 'patina', 'impeccable', 'tangible'. Very sophisticated.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Excellent usage.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Full range of structures used naturally. Participle phrases and correlative structures are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    },
    # 330. V8/G9 - TV Program
    {
        "sample_id": "syn_p2_v8_g9_0330",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a TV program you like to watch.",
        "transcript_cleaned": "I am an avid viewer of 'Planet Earth', a nature documentary series narrated by the legendary David Attenborough. The cinematography is breathtaking, capturing the raw beauty and brutality of the natural world in high definition. It employs state-of-the-art cameras to film elusive species in their natural habitats without disturbing them. The narration is both informative and poetic, enhancing the visual experience significantly. One episode about deep-sea creatures left me completely mesmerized by the alien-like life forms. The series highlights the fragility of our ecosystems and the urgent need for global conservation efforts. It is educational yet deeply moving. Watching it transports me to remote corners of the globe I will likely never visit. It is a masterpiece of broadcasting.",
        "word_count": 122,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR8] Vocabulary: 'avid', 'documentary', 'narrated', 'cinematography', 'breathtaking', 'raw', 'brutality', 'employs', 'elusive', 'habitats', 'poetic', 'mesmerized', 'fragility', 'ecosystems', 'conservation', 'remote', 'masterpiece', 'broadcasting'.",
        "grammar_reason": "[GRA9] Full range. 'Narrated by David Attenborough' (Participle phrase). 'Capturing the raw beauty...' (Participle phrase). 'One episode... left me...' (Noun phrase subject). 'Watching it transports me...' (Gerund subject). Error-free.",
        "vocabulary": 8,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a TV program you like to watch.\n\nTranscript: I am an avid viewer of 'Planet Earth', a nature documentary series narrated by the legendary David Attenborough. The cinematography is breathtaking, capturing the raw beauty and brutality of the natural world in high definition. It employs state-of-the-art cameras to film elusive species in their natural habitats without disturbing them. The narration is both informative and poetic, enhancing the visual experience significantly. One episode about deep-sea creatures left me completely mesmerized by the alien-like life forms. The series highlights the fragility of our ecosystems and the urgent need for global conservation efforts. It is educational yet deeply moving. Watching it transports me to remote corners of the globe I will likely never visit. It is a masterpiece of broadcasting.\n\nWord Count: 122 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses 'avid', 'cinematography', 'elusive', 'mesmerized', 'fragility', 'masterpiece'. Very sophisticated.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Excellent usage.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Full range of structures used naturally. Participle phrases and gerund subjects are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    }
]

with open(OUTPUT_FILE, 'a', encoding='utf-8') as f:
    for sample in samples:
        f.write(json.dumps(sample) + '\n')
