import json

OUTPUT_FILE = "ielts-data/phase3/v76_review_output/synthetic_batches/batch_p2_11.jsonl"

samples = [
    # 521. V8/G8 - Job (Ideal)
    {
        "sample_id": "syn_p2_v8_g8_0521",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a job you think is important.",
        "transcript_cleaned": "I believe that being a paramedic is a vocation of immense significance. They are the first responders in critical emergencies, often making life-or-death decisions under extreme pressure. The role requires not only medical expertise but also emotional resilience and rapid problem-solving skills. I am in awe of their ability to remain composed amidst chaos and trauma. Their interventions stabilize patients before they reach the hospital, which is often crucial for survival. Although the work is physically demanding and emotionally draining, the impact they have on society is immeasurable. They are unsung heroes who deserve our utmost respect and gratitude.",
        "word_count": 99,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR8] Vocabulary: 'vocation', 'immense significance', 'first responders', 'critical emergencies', 'life-or-death decisions', 'extreme pressure', 'expertise', 'emotional resilience', 'rapid problem-solving', 'awe', 'composed', 'chaos', 'trauma', 'interventions', 'stabilize', 'physically demanding', 'emotionally draining', 'immeasurable', 'unsung heroes', 'utmost respect'. Very sophisticated. >Band 7: Precise vocabulary. Not Band 9: Some collocations are standard.",
        "grammar_reason": "[GRA8] Wide range of structures used accurately. 'That being a paramedic is...' (Noun clause). 'Often making life-or-death decisions' (Participle phrase). 'Not only... but also...' (Correlative conjunction). 'Which is often crucial...' (Relative clause). Error-free. >Band 7: More complex structures.",
        "vocabulary": 8,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a job you think is important.\n\nTranscript: I believe that being a paramedic is a vocation of immense significance. They are the first responders in critical emergencies, often making life-or-death decisions under extreme pressure. The role requires not only medical expertise but also emotional resilience and rapid problem-solving skills. I am in awe of their ability to remain composed amidst chaos and trauma. Their interventions stabilize patients before they reach the hospital, which is often crucial for survival. Although the work is physically demanding and emotionally draining, the impact they have on society is immeasurable. They are unsung heroes who deserve our utmost respect and gratitude.\n\nWord Count: 99 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses sophisticated vocabulary: 'vocation', 'resilience', 'interventions', 'immeasurable'. Precise.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Lacks native-like flow.\n\n**Idiom present:** Yes ('unsung heroes')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Uses complex structures accurately (noun clauses, correlative conjunctions). Error-free.\n\n>Band 7: High accuracy.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    },
    # 522. V8/G8 - Place (Historical)
    {
        "sample_id": "syn_p2_v8_g8_0522",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a historical event you find interesting.",
        "transcript_cleaned": "The moon landing in 1969 is a pivotal moment in human history that captivates me. It represented the culmination of years of scientific innovation and daring exploration. The sheer audacity of sending humans to another celestial body is mind-boggling. I am fascinated by the technical challenges that had to be overcome with limited computing power. The footage of Neil Armstrong taking that first step is iconic and profoundly moving. It united the world in a shared sense of wonder and possibility. This achievement demonstrated that with collective effort and ingenuity, humanity can transcend its earthly boundaries.",
        "word_count": 98,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR8] Vocabulary: 'pivotal moment', 'captivates', 'culmination', 'innovation', 'daring exploration', 'sheer audacity', 'celestial body', 'mind-boggling', 'technical challenges', 'footage', 'iconic', 'profoundly moving', 'united', 'collective effort', 'ingenuity', 'transcend', 'earthly boundaries'. Very sophisticated. >Band 7: Precise vocabulary. Not Band 9: Some phrases are common.",
        "grammar_reason": "[GRA8] Wide range of structures used accurately. 'That captivates me' (Relative clause). 'Sending humans... is...' (Gerund phrase subject). 'That had to be overcome' (Passive relative clause). 'Taking that first step' (Participle phrase). Error-free. >Band 7: More complex structures.",
        "vocabulary": 8,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a historical event you find interesting.\n\nTranscript: The moon landing in 1969 is a pivotal moment in human history that captivates me. It represented the culmination of years of scientific innovation and daring exploration. The sheer audacity of sending humans to another celestial body is mind-boggling. I am fascinated by the technical challenges that had to be overcome with limited computing power. The footage of Neil Armstrong taking that first step is iconic and profoundly moving. It united the world in a shared sense of wonder and possibility. This achievement demonstrated that with collective effort and ingenuity, humanity can transcend its earthly boundaries.\n\nWord Count: 98 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses sophisticated vocabulary: 'pivotal', 'audacity', 'celestial', 'ingenuity'. Precise.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Lacks native-like flow.\n\n**Idiom present:** Yes ('mind-boggling')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Uses complex structures accurately (passive relative clauses, gerund phrases). Error-free.\n\n>Band 7: High accuracy.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    },
    # 523. V8/G8 - Activity (Project)
    {
        "sample_id": "syn_p2_v8_g8_0523",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a project you would like to do.",
        "transcript_cleaned": "I have always harbored an ambition to initiate a community garden project in my neighborhood. This endeavor would involve transforming a vacant lot into a productive green space. My goal is to cultivate organic vegetables and foster a sense of community ownership. It would require coordinating volunteers and securing funding from local businesses. I envision it as a hub for educational workshops on sustainability and nutrition. The project would not only beautify the area but also provide fresh produce for low-income families. It is a tangible way to address food insecurity while promoting environmental stewardship.",
        "word_count": 96,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR8] Vocabulary: 'harbored', 'ambition', 'initiate', 'endeavor', 'transforming', 'vacant lot', 'productive', 'cultivate', 'organic', 'foster', 'ownership', 'coordinating volunteers', 'securing funding', 'envision', 'hub', 'sustainability', 'nutrition', 'beautify', 'produce', 'low-income', 'tangible', 'address', 'food insecurity', 'promoting', 'stewardship'. Very sophisticated. >Band 7: Precise vocabulary. Not Band 9: Some phrases are common.",
        "grammar_reason": "[GRA8] Wide range of structures used accurately. 'To initiate a community garden project' (Infinitive phrase). 'Transforming a vacant lot...' (Gerund phrase). 'Not only... but also...' (Correlative conjunction). 'While promoting...' (Conjunction + Participle). Error-free. >Band 7: More complex structures.",
        "vocabulary": 8,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a project you would like to do.\n\nTranscript: I have always harbored an ambition to initiate a community garden project in my neighborhood. This endeavor would involve transforming a vacant lot into a productive green space. My goal is to cultivate organic vegetables and foster a sense of community ownership. It would require coordinating volunteers and securing funding from local businesses. I envision it as a hub for educational workshops on sustainability and nutrition. The project would not only beautify the area but also provide fresh produce for low-income families. It is a tangible way to address food insecurity while promoting environmental stewardship.\n\nWord Count: 96 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses sophisticated vocabulary: 'harbored', 'endeavor', 'cultivate', 'stewardship'. Precise.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Lacks native-like flow.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Uses complex structures accurately (correlative conjunctions, participial phrases). Error-free.\n\n>Band 7: High accuracy.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    },
    # 524. V8/G8 - Person (Friend)
    {
        "sample_id": "syn_p2_v8_g8_0524",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a person who is good at their job.",
        "transcript_cleaned": "I want to describe my dentist, Dr. Lee, who is exceptionally skilled at his profession. He possesses a gentle demeanor that instantly puts anxious patients at ease. His technical proficiency is evident in the precision of his work. What sets him apart is his ability to explain complex procedures in layman's terms. He is also meticulously hygienic, ensuring a sterile environment at all times. I admire his commitment to continuous learning, as he stays updated with the latest dental advancements. He treats every patient with empathy and respect. He is a shining example of professionalism.",
        "word_count": 96,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR8] Vocabulary: 'exceptionally skilled', 'profession', 'possesses', 'gentle demeanor', 'anxious', 'at ease', 'technical proficiency', 'evident', 'precision', 'sets him apart', 'layman\'s terms', 'meticulously hygienic', 'sterile environment', 'commitment', 'continuous learning', 'advancements', 'empathy', 'professionalism'. Very sophisticated. >Band 7: Precise vocabulary. Not Band 9: Some phrases are common.",
        "grammar_reason": "[GRA8] Wide range of structures used accurately. 'Who is exceptionally skilled' (Relative clause). 'That instantly puts...' (Relative clause). 'What sets him apart is...' (Pseudo-cleft). 'Ensuring a sterile environment' (Participle phrase). Error-free. >Band 7: More complex structures.",
        "vocabulary": 8,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a person who is good at their job.\n\nTranscript: I want to describe my dentist, Dr. Lee, who is exceptionally skilled at his profession. He possesses a gentle demeanor that instantly puts anxious patients at ease. His technical proficiency is evident in the precision of his work. What sets him apart is his ability to explain complex procedures in layman's terms. He is also meticulously hygienic, ensuring a sterile environment at all times. I admire his commitment to continuous learning, as he stays updated with the latest dental advancements. He treats every patient with empathy and respect. He is a shining example of professionalism.\n\nWord Count: 96 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses sophisticated vocabulary: 'demeanor', 'proficiency', 'meticulously', 'empathy'. Precise.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Lacks native-like flow.\n\n**Idiom present:** Yes ('layman's terms', 'sets him apart')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Uses complex structures accurately (pseudo-cleft, participle phrases). Error-free.\n\n>Band 7: High accuracy.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    },
    # 525. V8/G8 - Event (Party)
    {
        "sample_id": "syn_p2_v8_g8_0525",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a party that you enjoyed.",
        "transcript_cleaned": "I attended a masquerade ball last New Year's Eve, which was an enchanting affair. The venue was a historic mansion, adorned with opulent decorations and twinkling lights. Everyone was dressed in elaborate costumes, concealing their identities behind ornate masks. The atmosphere was filled with intrigue and excitement. We danced to a live orchestra playing classical waltzes, which felt incredibly elegant. The culinary spread was exquisite, featuring gourmet hors d'oeuvres and champagne. I loved the element of mystery and the opportunity to interact with strangers freely. It was a magical night that transported us to a bygone era.",
        "word_count": 98,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR8] Vocabulary: 'masquerade ball', 'enchanting affair', 'venue', 'historic mansion', 'adorned', 'opulent', 'twinkling', 'elaborate costumes', 'concealing', 'identities', 'ornate masks', 'intrigue', 'orchestra', 'waltzes', 'elegant', 'culinary spread', 'exquisite', 'gourmet', 'hors d'oeuvres', 'mystery', 'interact', 'bygone era'. Very sophisticated. >Band 7: Precise vocabulary. Not Band 9: Some phrases are common.",
        "grammar_reason": "[GRA8] Wide range of structures used accurately. 'Which was an enchanting affair' (Relative clause). 'Adorned with opulent decorations' (Participle phrase). 'Concealing their identities' (Participle phrase). 'That transported us...' (Relative clause). Error-free. >Band 7: More complex structures.",
        "vocabulary": 8,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a party that you enjoyed.\n\nTranscript: I attended a masquerade ball last New Year's Eve, which was an enchanting affair. The venue was a historic mansion, adorned with opulent decorations and twinkling lights. Everyone was dressed in elaborate costumes, concealing their identities behind ornate masks. The atmosphere was filled with intrigue and excitement. We danced to a live orchestra playing classical waltzes, which felt incredibly elegant. The culinary spread was exquisite, featuring gourmet hors d'oeuvres and champagne. I loved the element of mystery and the opportunity to interact with strangers freely. It was a magical night that transported us to a bygone era.\n\nWord Count: 98 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses sophisticated vocabulary: 'enchanting', 'opulent', 'intrigue', 'exquisite'. Precise.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Lacks native-like flow.\n\n**Idiom present:** Yes ('bygone era')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Uses complex structures accurately (participle phrases, relative clauses). Error-free.\n\n>Band 7: High accuracy.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    },
    # 526. V8/G8 - Object (Art)
    {
        "sample_id": "syn_p2_v8_g8_0526",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a piece of art you like.",
        "transcript_cleaned": "I am deeply moved by 'The Kiss' by Gustav Klimt, a masterpiece of the Art Nouveau period. The painting depicts a couple embraced in a field of wildflowers, shrouded in gold leaf. I am captivated by the intricate patterns and the luminous quality of the work. The contrast between the geometric shapes on the robes and the organic forms of the figures is striking. It evokes a sense of intimacy and timeless love. Viewing it in person was a transcendent experience that left me speechless. It is a dazzling celebration of romance and artistic craftsmanship.",
        "word_count": 98,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR8] Vocabulary: 'deeply moved', 'masterpiece', 'Art Nouveau', 'depicts', 'embraced', 'shrouded', 'gold leaf', 'captivated', 'intricate patterns', 'luminous', 'geometric shapes', 'organic forms', 'striking', 'evokes', 'intimacy', 'timeless', 'transcendent', 'speechless', 'dazzling', 'celebration', 'craftsmanship'. Very sophisticated. >Band 7: Precise vocabulary. Not Band 9: Some phrases are common.",
        "grammar_reason": "[GRA8] Wide range of structures used accurately. 'Embraced in a field...' (Participle phrase). 'Shrouded in gold leaf' (Participle phrase). 'Viewing it in person was...' (Gerund subject). 'That left me speechless' (Relative clause). Error-free. >Band 7: More complex structures.",
        "vocabulary": 8,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a piece of art you like.\n\nTranscript: I am deeply moved by 'The Kiss' by Gustav Klimt, a masterpiece of the Art Nouveau period. The painting depicts a couple embraced in a field of wildflowers, shrouded in gold leaf. I am captivated by the intricate patterns and the luminous quality of the work. The contrast between the geometric shapes on the robes and the organic forms of the figures is striking. It evokes a sense of intimacy and timeless love. Viewing it in person was a transcendent experience that left me speechless. It is a dazzling celebration of romance and artistic craftsmanship.\n\nWord Count: 98 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses sophisticated vocabulary: 'masterpiece', 'luminous', 'transcendent', 'craftsmanship'. Precise.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Lacks native-like flow.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Uses complex structures accurately (gerund subjects, participle phrases). Error-free.\n\n>Band 7: High accuracy.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    },
    # 527. V8/G8 - Activity (Exercise)
    {
        "sample_id": "syn_p2_v8_g8_0527",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe an exercise you find effective.",
        "transcript_cleaned": "I find swimming to be an exceptionally effective form of exercise for overall fitness. It provides a comprehensive cardiovascular workout while engaging all major muscle groups. The resistance of the water helps to build strength and endurance without straining the joints. I am particularly fond of the meditative quality of swimming laps. The rhythmic breathing and repetitive motion induce a state of mental clarity. After a session, I feel invigorated and refreshed. It is also a therapeutic way to alleviate back pain. I try to incorporate it into my weekly routine as often as possible.",
        "word_count": 97,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR8] Vocabulary: 'exceptionally effective', 'comprehensive', 'cardiovascular workout', 'engaging', 'muscle groups', 'resistance', 'endurance', 'straining', 'joints', 'fond', 'meditative quality', 'rhythmic breathing', 'repetitive motion', 'induce', 'mental clarity', 'invigorated', 'refreshed', 'therapeutic', 'alleviate', 'incorporate'. Very sophisticated. >Band 7: Precise vocabulary. Not Band 9: Some phrases are common.",
        "grammar_reason": "[GRA8] Wide range of structures used accurately. 'While engaging all major muscle groups' (Conjunction + Participle). 'Without straining the joints' (Preposition + Gerund). 'I find swimming to be...' (Verb pattern). Error-free. >Band 7: More complex structures.",
        "vocabulary": 8,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe an exercise you find effective.\n\nTranscript: I find swimming to be an exceptionally effective form of exercise for overall fitness. It provides a comprehensive cardiovascular workout while engaging all major muscle groups. The resistance of the water helps to build strength and endurance without straining the joints. I am particularly fond of the meditative quality of swimming laps. The rhythmic breathing and repetitive motion induce a state of mental clarity. After a session, I feel invigorated and refreshed. It is also a therapeutic way to alleviate back pain. I try to incorporate it into my weekly routine as often as possible.\n\nWord Count: 97 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses sophisticated vocabulary: 'comprehensive', 'endurance', 'invigorated', 'therapeutic'. Precise.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Lacks native-like flow.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Uses complex structures accurately (prepositional gerunds, verb patterns). Error-free.\n\n>Band 7: High accuracy.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    },
    # 528. V8/G8 - Book (Recommended)
    {
        "sample_id": "syn_p2_v8_g8_0528",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a book you would recommend to a friend.",
        "transcript_cleaned": "I would highly recommend 'To Kill a Mockingbird' by Harper Lee, a seminal work of American literature. It explores profound themes of racial injustice and moral integrity through the eyes of a child. The protagonist's father, Atticus Finch, serves as a paragon of virtue and courage. I was deeply moved by his unwavering commitment to defending the innocent. The narrative is both heartwarming and heartbreaking, offering a poignant critique of societal prejudice. It compels the reader to confront uncomfortable truths about human nature. This novel is a timeless classic that resonates with readers of all ages.",
        "word_count": 98,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR8] Vocabulary: 'seminal work', 'profound themes', 'racial injustice', 'moral integrity', 'protagonist', 'paragon', 'virtue', 'courage', 'unwavering commitment', 'defending', 'innocent', 'narrative', 'heartwarming', 'heartbreaking', 'poignant critique', 'societal prejudice', 'compels', 'confront', 'uncomfortable truths', 'timeless classic', 'resonates'. Very sophisticated. >Band 7: Precise vocabulary. Not Band 9: Some phrases are common.",
        "grammar_reason": "[GRA8] Wide range of structures used accurately. 'Through the eyes of a child' (Prepositional phrase). 'Serves as a paragon...' (Verb phrase). 'Offering a poignant critique...' (Participle phrase). 'Compels the reader to confront...' (Verb pattern). Error-free. >Band 7: More complex structures.",
        "vocabulary": 8,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a book you would recommend to a friend.\n\nTranscript: I would highly recommend 'To Kill a Mockingbird' by Harper Lee, a seminal work of American literature. It explores profound themes of racial injustice and moral integrity through the eyes of a child. The protagonist's father, Atticus Finch, serves as a paragon of virtue and courage. I was deeply moved by his unwavering commitment to defending the innocent. The narrative is both heartwarming and heartbreaking, offering a poignant critique of societal prejudice. It compels the reader to confront uncomfortable truths about human nature. This novel is a timeless classic that resonates with readers of all ages.\n\nWord Count: 98 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses sophisticated vocabulary: 'seminal', 'integrity', 'paragon', 'poignant'. Precise.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Lacks native-like flow.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Uses complex structures accurately (participle phrases, verb patterns). Error-free.\n\n>Band 7: High accuracy.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    },
    # 529. V8/G8 - Place (Quiet)
    {
        "sample_id": "syn_p2_v8_g8_0529",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a quiet place in your city.",
        "transcript_cleaned": "There is a secluded botanical garden on the outskirts of the city that serves as a tranquil refuge. It is a sprawling sanctuary, meticulously landscaped with exotic flora and winding pathways. I go there to escape the cacophony of urban life and reconnect with nature. The silence is profound, broken only by the chirping of birds and the rustling of leaves. I cherish the solitude it offers, allowing for deep introspection. Sitting by the koi pond, I feel a sense of serenity wash over me. It is an idyllic spot to recharge and find mental clarity.",
        "word_count": 98,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR8] Vocabulary: 'secluded', 'outskirts', 'tranquil refuge', 'sprawling sanctuary', 'meticulously landscaped', 'exotic flora', 'winding pathways', 'cacophony', 'urban life', 'reconnect', 'profound', 'rustling', 'cherish', 'solitude', 'introspection', 'koi pond', 'serenity', 'idyllic', 'recharge', 'mental clarity'. Very sophisticated. >Band 7: Precise vocabulary. Not Band 9: Some phrases are common.",
        "grammar_reason": "[GRA8] Wide range of structures used accurately. 'That serves as a tranquil refuge' (Relative clause). 'Meticulously landscaped with...' (Participle phrase). 'Broken only by...' (Participle phrase). 'Allowing for deep introspection' (Participle phrase). Error-free. >Band 7: More complex structures.",
        "vocabulary": 8,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a quiet place in your city.\n\nTranscript: There is a secluded botanical garden on the outskirts of the city that serves as a tranquil refuge. It is a sprawling sanctuary, meticulously landscaped with exotic flora and winding pathways. I go there to escape the cacophony of urban life and reconnect with nature. The silence is profound, broken only by the chirping of birds and the rustling of leaves. I cherish the solitude it offers, allowing for deep introspection. Sitting by the koi pond, I feel a sense of serenity wash over me. It is an idyllic spot to recharge and find mental clarity.\n\nWord Count: 98 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses sophisticated vocabulary: 'refuge', 'cacophony', 'introspection', 'idyllic'. Precise.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Lacks native-like flow.\n\n**Idiom present:** Yes ('wash over me')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Uses complex structures accurately (participle phrases, relative clauses). Error-free.\n\n>Band 7: High accuracy.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    },
    # 530. V8/G8 - Event (Festival)
    {
        "sample_id": "syn_p2_v8_g8_0530",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a festival you like.",
        "transcript_cleaned": "I am particularly fond of the Cherry Blossom Festival, a vibrant celebration of spring's arrival. It is a fleeting spectacle where the city is blanketed in pink and white petals. The atmosphere is jubilant, with families picnicking under the blooming trees. I enjoy the cultural performances, which showcase traditional music and dance. The festival fosters a sense of communal joy and appreciation for ephemeral beauty. It is a photographer's paradise, offering stunning visual compositions. I make it a point to attend every year to witness nature's grandeur. It is a cherished tradition that rejuvenates my spirit.",
        "word_count": 97,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR8] Vocabulary: 'particularly fond', 'vibrant celebration', 'fleeting spectacle', 'blanketed', 'jubilant', 'blooming', 'cultural performances', 'showcase', 'fosters', 'communal joy', 'appreciation', 'ephemeral beauty', 'paradise', 'compositions', 'grandeur', 'cherished tradition', 'rejuvenates'. Very sophisticated. >Band 7: Precise vocabulary. Not Band 9: Some phrases are common.",
        "grammar_reason": "[GRA8] Wide range of structures used accurately. 'Where the city is blanketed' (Relative clause). 'With families picnicking...' (Prepositional phrase + Participle). 'Which showcase traditional music' (Relative clause). 'Offering stunning visual compositions' (Participle phrase). Error-free. >Band 7: More complex structures.",
        "vocabulary": 8,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a festival you like.\n\nTranscript: I am particularly fond of the Cherry Blossom Festival, a vibrant celebration of spring's arrival. It is a fleeting spectacle where the city is blanketed in pink and white petals. The atmosphere is jubilant, with families picnicking under the blooming trees. I enjoy the cultural performances, which showcase traditional music and dance. The festival fosters a sense of communal joy and appreciation for ephemeral beauty. It is a photographer's paradise, offering stunning visual compositions. I make it a point to attend every year to witness nature's grandeur. It is a cherished tradition that rejuvenates my spirit.\n\nWord Count: 97 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses sophisticated vocabulary: 'spectacle', 'jubilant', 'ephemeral', 'grandeur'. Precise.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Lacks native-like flow.\n\n**Idiom present:** Yes ('make it a point')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Uses complex structures accurately (relative clauses, participle phrases). Error-free.\n\n>Band 7: High accuracy.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    }
]

with open(OUTPUT_FILE, 'a', encoding='utf-8') as f:
    for sample in samples:
        f.write(json.dumps(sample) + '\n')
