import json

OUTPUT_FILE = "ielts-data/phase3/v76_review_output/synthetic_batches/batch_p2_02.jsonl"

samples = [
    # 71. V6/G7 - History
    {
        "sample_id": "syn_p2_v6_g7_0071",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a historical period you would like to know more about.",
        "transcript_cleaned": "I would like to learn more about the Renaissance period. It was a very important time in history. It started in Italy in the 14th century. I am interested in this period because of the art and science. Famous artists like Leonardo da Vinci and Michelangelo lived during this time. They created amazing paintings and sculptures. I want to know how they lived and worked. Also, there were many scientific discoveries. People started to think differently. Humanism. It was a time of rebirth. If I could travel back in time, I would like to visit Florence. To see the beautiful buildings. The architecture was magnificent. I think learning about the Renaissance helps us understand modern culture. It influenced art and thinking in Europe for a long time.",
        "word_count": 136,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'started in Italy' → 'started in Italy'", "grammar: 'lived during this time' → 'lived during this time'", "grammar: 'think differently' → 'think differently'", "grammar: 'travel back in time' → 'travel back in time'", "grammar: 'modern culture' → 'modern culture'"],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR6] Vocabulary: 'Renaissance', 'century', 'sculptures', 'discoveries', 'humanism', 'rebirth', 'architecture', 'magnificent', 'culture', 'influenced'. Adequate range.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'I am interested in this period because of...' (Reason). 'If I could travel back in time, I would like to visit...' (Second Conditional). 'I want to know how they lived...' (Noun clause).",
        "vocabulary": 6,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a historical period you would like to know more about.\n\nTranscript: I would like to learn more about the Renaissance period. It was a very important time in history. It started in Italy in the 14th century. I am interested in this period because of the art and science. Famous artists like Leonardo da Vinci and Michelangelo lived during this time. They created amazing paintings and sculptures. I want to know how they lived and worked. Also, there were many scientific discoveries. People started to think differently. Humanism. It was a time of rebirth. If I could travel back in time, I would like to visit Florence. To see the beautiful buildings. The architecture was magnificent. I think learning about the Renaissance helps us understand modern culture. It influenced art and thinking in Europe for a long time.\n\nWord Count: 136 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses 'Renaissance', 'sculptures', 'humanism', 'rebirth', 'architecture', 'magnificent'.\n\n>Band 5: Uses topic-specific words.\n\nNot Band 7: Vocabulary is functional but lacks flair.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Frequent error-free complex structures. Uses second conditional ('If I could... I would...'), noun clauses, and reason clauses correctly. Good control.\n\n>Band 6: More flexibility and accuracy.\n\nNot Band 8: Range is not fully wide.\n\n**Micro flaws identified:**\n- None significant."
    },
    # 72. V6/G7 - Lake
    {
        "sample_id": "syn_p2_v6_g7_0072",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a lake, a river or a sea you have visited.",
        "transcript_cleaned": "I visited Lake Como in Italy last summer. It is one of the most beautiful lakes in Europe. The lake is surrounded by mountains and small villages. The scenery was stunning. The water was deep blue and very clean. I took a boat trip around the lake. It was very relaxing. I saw many luxurious villas on the shore. Some famous people live there. I also visited a town called Bellagio. It had narrow streets and colorful houses. I ate delicious pasta there. What impressed me the most was the peaceful atmosphere. It was very different from the busy city life. I wish I could live there. It is a perfect place for retirement. I would recommend this place to anyone who loves nature and beauty.",
        "word_count": 139,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'surrounded by mountains' → 'surrounded by mountains'", "grammar: 'luxurious villas' → 'luxurious villas'", "grammar: 'impressed me the most' → 'impressed me the most'", "grammar: 'peaceful atmosphere' → 'peaceful atmosphere'", "grammar: 'recommend this place' → 'recommend this place'"],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR6] Vocabulary: 'surrounded', 'villages', 'scenery', 'stunning', 'luxurious', 'villas', 'shore', 'narrow', 'impressed', 'atmosphere', 'retirement', 'recommend'.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'The lake is surrounded by...' (Passive). 'What impressed me the most was...' (Cleft sentence). 'I wish I could live there' (Wish structure). 'I would recommend this place to anyone who loves...' (Relative clause).",
        "vocabulary": 6,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a lake, a river or a sea you have visited.\n\nTranscript: I visited Lake Como in Italy last summer. It is one of the most beautiful lakes in Europe. The lake is surrounded by mountains and small villages. The scenery was stunning. The water was deep blue and very clean. I took a boat trip around the lake. It was very relaxing. I saw many luxurious villas on the shore. Some famous people live there. I also visited a town called Bellagio. It had narrow streets and colorful houses. I ate delicious pasta there. What impressed me the most was the peaceful atmosphere. It was very different from the busy city life. I wish I could live there. It is a perfect place for retirement. I would recommend this place to anyone who loves nature and beauty.\n\nWord Count: 139 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses 'surrounded', 'stunning', 'luxurious', 'shore', 'impressed', 'atmosphere', 'retirement'.\n\n>Band 5: Uses topic-specific words.\n\nNot Band 7: Lacks sophisticated collocations.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Frequent error-free complex structures. Uses passive voice, cleft sentences, wish structures, and relative clauses correctly. Strong control.\n\n>Band 6: Higher accuracy and flexibility.\n\nNot Band 8: Range could be wider.\n\n**Micro flaws identified:**\n- None significant."
    },
    # 73. V6/G7 - News
    {
        "sample_id": "syn_p2_v6_g7_0073",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a piece of news that you heard recently.",
        "transcript_cleaned": "I heard some news about a new park opening in my city. I read it on a local news website yesterday. The government decided to build a large green park in the city center. It used to be an old factory site. I was very happy to hear this because our city needs more green spaces. The air pollution is getting worse. The new park will have many trees, a lake, and a playground for children. It will also have a walking path for people to exercise. I think it is a great initiative. It will improve the quality of life for residents. I look forward to visiting the park when it opens next year. I hope the government will build more parks in the future. It is beneficial for the environment.",
        "word_count": 139,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'decided to build' → 'decided to build'", "grammar: 'used to be' → 'used to be'", "grammar: 'green spaces' → 'green spaces'", "grammar: 'getting worse' → 'getting worse'", "grammar: 'walking path' → 'walking path'", "grammar: 'great initiative' → 'great initiative'", "grammar: 'quality of life' → 'quality of life'", "grammar: 'look forward to visiting' → 'look forward to visiting'"],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR6] Vocabulary: 'opening', 'site', 'pollution', 'playground', 'exercise', 'initiative', 'residents', 'quality of life', 'beneficial', 'environment'.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'The government decided to build...' (Infinitive). 'It used to be...' (Used to). 'I was very happy to hear this because...' (Reason). 'I look forward to visiting...' (Gerund after preposition). Accurate.",
        "vocabulary": 6,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a piece of news that you heard recently.\n\nTranscript: I heard some news about a new park opening in my city. I read it on a local news website yesterday. The government decided to build a large green park in the city center. It used to be an old factory site. I was very happy to hear this because our city needs more green spaces. The air pollution is getting worse. The new park will have many trees, a lake, and a playground for children. It will also have a walking path for people to exercise. I think it is a great initiative. It will improve the quality of life for residents. I look forward to visiting the park when it opens next year. I hope the government will build more parks in the future. It is beneficial for the environment.\n\nWord Count: 139 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses 'initiative', 'residents', 'quality of life', 'beneficial'.\n\n>Band 5: Uses topic-specific words.\n\nNot Band 7: Vocabulary is standard.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Frequent error-free complex structures. Uses 'used to', 'because', 'look forward to visiting'. High accuracy.\n\n>Band 6: Good control of grammar.\n\nNot Band 8: Sentence variety could be better.\n\n**Micro flaws identified:**\n- None significant."
    },
    # 74. V6/G7 - Childhood Friend
    {
        "sample_id": "syn_p2_v6_g7_0074",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a childhood friend you remember well.",
        "transcript_cleaned": "I remember my best friend from primary school. His name was Peter. We were in the same class for five years. He was a very funny and energetic boy. We used to play football together every recess. I liked him because he was very loyal. Once, I got into trouble with a bully, and Peter stood up for me. He defended me. I was very grateful. We also shared many secrets. We promised to be friends forever. However, when we finished primary school, his family moved to another city. We lost touch. I was very sad. I often wonder what he is doing now. If I met him again, I would be very happy. I cherish the memories we had together. Childhood friendship is very pure and innocent.",
        "word_count": 136,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'same class' → 'same class'", "grammar: 'used to play' → 'used to play'", "grammar: 'stood up for me' → 'stood up for me'", "grammar: 'defended me' → 'defended me'", "grammar: 'lost touch' → 'lost touch'", "grammar: 'cherish the memories' → 'cherish the memories'", "grammar: 'pure and innocent' → 'pure and innocent'"],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR6] Vocabulary: 'primary', 'energetic', 'recess', 'loyal', 'bully', 'defended', 'grateful', 'secrets', 'promised', 'lost touch', 'cherish', 'innocent'.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'We used to play...' (Habitual past). 'I liked him because...' (Reason). 'If I met him again, I would be...' (Second Conditional). 'I often wonder what he is doing now' (Embedded question).",
        "vocabulary": 6,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a childhood friend you remember well.\n\nTranscript: I remember my best friend from primary school. His name was Peter. We were in the same class for five years. He was a very funny and energetic boy. We used to play football together every recess. I liked him because he was very loyal. Once, I got into trouble with a bully, and Peter stood up for me. He defended me. I was very grateful. We also shared many secrets. We promised to be friends forever. However, when we finished primary school, his family moved to another city. We lost touch. I was very sad. I often wonder what he is doing now. If I met him again, I would be very happy. I cherish the memories we had together. Childhood friendship is very pure and innocent.\n\nWord Count: 136 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses 'loyal', 'bully', 'defended', 'lost touch', 'cherish', 'innocent'.\n\n>Band 5: Uses less common words.\n\nNot Band 7: Limited precision.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Frequent error-free complex structures. Uses second conditional, embedded questions, and 'used to' correctly.\n\n>Band 6: Higher accuracy.\n\nNot Band 8: Sentences are somewhat short.\n\n**Micro flaws identified:**\n- None significant."
    },
    # 75. V6/G7 - Game
    {
        "sample_id": "syn_p2_v6_g7_0075",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a game you played in your childhood.",
        "transcript_cleaned": "I used to play Hide and Seek with my neighbors. It was a very popular game in my neighborhood. We usually played it in the evening after school. The rules were simple. One person counted to ten, and others hid. I was good at hiding. I often hid behind a big tree or under a car. It was exciting to wait in silence. If the seeker found someone, they would run to the base. I remember laughing a lot when playing this game. It helped us to be active and make friends. We didn't need any equipment. Just a safe place to run. Nowadays, children play video games inside. They don't go out much. I think traditional games are better for their physical and mental health. I miss those days.",
        "word_count": 139,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'popular game' → 'popular game'", "grammar: 'counted to ten' → 'counted to ten'", "grammar: 'good at hiding' → 'good at hiding'", "grammar: 'wait in silence' → 'wait in silence'", "grammar: 'didn't need any equipment' → 'didn't need any equipment'", "grammar: 'physical and mental health' → 'physical and mental health'"],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR6] Vocabulary: 'popular', 'neighbors', 'rules', 'hid', 'seeker', 'base', 'equipment', 'traditional', 'physical', 'mental', 'health'.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'One person counted..., and others hid' (Compound). 'If the seeker found someone, they would run...' (Second Conditional/Habitual past). 'It helped us to be active' (Infinitive pattern). Accurate.",
        "vocabulary": 6,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a game you played in your childhood.\n\nTranscript: I used to play Hide and Seek with my neighbors. It was a very popular game in my neighborhood. We usually played it in the evening after school. The rules were simple. One person counted to ten, and others hid. I was good at hiding. I often hid behind a big tree or under a car. It was exciting to wait in silence. If the seeker found someone, they would run to the base. I remember laughing a lot when playing this game. It helped us to be active and make friends. We didn't need any equipment. Just a safe place to run. Nowadays, children play video games inside. They don't go out much. I think traditional games are better for their physical and mental health. I miss those days.\n\nWord Count: 139 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses 'seeker', 'equipment', 'traditional', 'physical', 'mental'.\n\n>Band 5: Uses topic-specific words.\n\nNot Band 7: Limited flexibility.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Frequent error-free complex structures. Uses conditionals and compound sentences correctly. Good control of past tenses.\n\n>Band 6: Higher accuracy.\n\nNot Band 8: Structure is a bit repetitive.\n\n**Micro flaws identified:**\n- None significant."
    },
    # 76. V6/G7 - Animal
    {
        "sample_id": "syn_p2_v6_g7_0076",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe an animal you think is interesting.",
        "transcript_cleaned": "I find dolphins very interesting. They are marine mammals. They live in the ocean. I saw them in an aquarium once. They are known for their intelligence. They can learn tricks and communicate with each other. I read that they use sound to navigate. Echolocation. It is fascinating. Dolphins are also very friendly. There are stories about dolphins saving humans from sharks. They are social animals. They live in groups called pods. I think they are beautiful creatures. Sleek and graceful. Unfortunately, they face threats from pollution and fishing nets. We need to protect them. I would love to swim with dolphins in the wild one day. It would be a magical experience. They remind us that animals have feelings and intelligence too.",
        "word_count": 133,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'marine mammals' → 'marine mammals'", "grammar: 'navigate' → 'navigate'", "grammar: 'echolocation' → 'echolocation'", "grammar: 'saving humans' → 'saving humans'", "grammar: 'social animals' → 'social animals'", "grammar: 'face threats' → 'face threats'", "grammar: 'magical experience' → 'magical experience'"],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR6] Vocabulary: 'mammals', 'aquarium', 'intelligence', 'communicate', 'navigate', 'echolocation', 'fascinating', 'pods', 'creatures', 'sleek', 'graceful', 'threats', 'pollution', 'magical'. Good range.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'They are known for...' (Passive). 'I read that they use sound...' (Noun clause). 'There are stories about dolphins saving humans' (Participle phrase). 'They remind us that...' (Noun clause). Accurate.",
        "vocabulary": 6,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe an animal you think is interesting.\n\nTranscript: I find dolphins very interesting. They are marine mammals. They live in the ocean. I saw them in an aquarium once. They are known for their intelligence. They can learn tricks and communicate with each other. I read that they use sound to navigate. Echolocation. It is fascinating. Dolphins are also very friendly. There are stories about dolphins saving humans from sharks. They are social animals. They live in groups called pods. I think they are beautiful creatures. Sleek and graceful. Unfortunately, they face threats from pollution and fishing nets. We need to protect them. I would love to swim with dolphins in the wild one day. It would be a magical experience. They remind us that animals have feelings and intelligence too.\n\nWord Count: 133 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses 'mammals', 'intelligence', 'navigate', 'echolocation', 'pods', 'sleek', 'graceful'.\n\n>Band 5: Uses topic-specific words.\n\nNot Band 7: Vocabulary is functional.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Frequent error-free complex structures. Uses passive voice and noun clauses correctly. High accuracy.\n\n>Band 6: Good control.\n\nNot Band 8: Sentences could be more varied.\n\n**Micro flaws identified:**\n- None significant."
    },
    # 77. V6/G7 - Skill
    {
        "sample_id": "syn_p2_v6_g7_0077",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a practical skill you learned.",
        "transcript_cleaned": "I learned how to cook when I went to university. I had to live alone, so cooking was necessary. My mother taught me some basic recipes before I left home. At first, I made many mistakes. I burned the rice and put too much salt in the soup. But I didn't give up. I practiced every day. I also watched cooking videos on the internet. It was helpful. Now, I can cook many delicious dishes. My specialty is spaghetti carbonara. Cooking is a useful skill. It saves money and it is healthier than eating out. It is also a creative process. I enjoy experimenting with different ingredients. I sometimes cook for my friends. They love my food. I feel proud when people enjoy my cooking.",
        "word_count": 136,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'basic recipes' → 'basic recipes'", "grammar: 'didn't give up' → 'didn't give up'", "grammar: 'delicious dishes' → 'delicious dishes'", "grammar: 'specialty' → 'specialty'", "grammar: 'healthier than' → 'healthier than'", "grammar: 'creative process' → 'creative process'", "grammar: 'experimenting with' → 'experimenting with'"],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR6] Vocabulary: 'recipes', 'basic', 'burned', 'specialty', 'carbonara', 'useful', 'creative', 'process', 'experimenting', 'ingredients', 'proud'.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'I had to live alone, so cooking was necessary' (Compound). 'My mother taught me... before I left home' (Time clause). 'It is healthier than eating out' (Comparative). Accurate.",
        "vocabulary": 6,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a practical skill you learned.\n\nTranscript: I learned how to cook when I went to university. I had to live alone, so cooking was necessary. My mother taught me some basic recipes before I left home. At first, I made many mistakes. I burned the rice and put too much salt in the soup. But I didn't give up. I practiced every day. I also watched cooking videos on the internet. It was helpful. Now, I can cook many delicious dishes. My specialty is spaghetti carbonara. Cooking is a useful skill. It saves money and it is healthier than eating out. It is also a creative process. I enjoy experimenting with different ingredients. I sometimes cook for my friends. They love my food. I feel proud when people enjoy my cooking.\n\nWord Count: 136 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses 'recipes', 'specialty', 'creative', 'experimenting', 'ingredients'.\n\n>Band 5: Uses topic-specific words.\n\nNot Band 7: Limited precision.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Frequent error-free complex structures. Uses time clauses, compound sentences, and comparatives correctly. High accuracy.\n\n>Band 6: Good control.\n\nNot Band 8: Range is not fully wide.\n\n**Micro flaws identified:**\n- None significant."
    },
    # 78. V6/G7 - Teacher (Influence)
    {
        "sample_id": "syn_p2_v6_g7_0078",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a teacher who influenced you.",
        "transcript_cleaned": "I would like to talk about my history teacher, Mr. Jones. He taught me in high school. He was very passionate about history. He didn't just read from the textbook. He told us stories about the past. He made history come alive. I used to find history boring, but he changed my mind. He encouraged us to ask questions and think critically. He was also very supportive. When I struggled with my essays, he gave me extra help. He believed in my potential. Because of him, I decided to study history at university. He inspired me to become a teacher too. I want to have the same impact on students. He showed me that a good teacher can change a student's life. I am very grateful to him.",
        "word_count": 136,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'passionate about' → 'passionate about'", "grammar: 'come alive' → 'come alive'", "grammar: 'think critically' → 'think critically'", "grammar: 'supportive' → 'supportive'", "grammar: 'struggled with' → 'struggled with'", "grammar: 'potential' → 'potential'", "grammar: 'impact on' → 'impact on'"],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR6] Vocabulary: 'passionate', 'textbook', 'alive', 'encouraged', 'critically', 'supportive', 'struggled', 'essays', 'potential', 'inspired', 'impact', 'grateful'.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'He didn't just read... he told...' (Not only/but also implied). 'I used to find history boring, but he changed...' (Contrast). 'When I struggled..., he gave...' (Time clause). 'He showed me that...' (Noun clause).",
        "vocabulary": 6,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a teacher who influenced you.\n\nTranscript: I would like to talk about my history teacher, Mr. Jones. He taught me in high school. He was very passionate about history. He didn't just read from the textbook. He told us stories about the past. He made history come alive. I used to find history boring, but he changed my mind. He encouraged us to ask questions and think critically. He was also very supportive. When I struggled with my essays, he gave me extra help. He believed in my potential. Because of him, I decided to study history at university. He inspired me to become a teacher too. I want to have the same impact on students. He showed me that a good teacher can change a student's life. I am very grateful to him.\n\nWord Count: 136 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses 'passionate', 'critically', 'supportive', 'potential', 'impact'.\n\n>Band 5: Uses less common words.\n\nNot Band 7: Limited flexibility.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Frequent error-free complex structures. Uses noun clauses, time clauses, and contrast correctly. High accuracy.\n\n>Band 6: Good control.\n\nNot Band 8: Sentence structure is a bit repetitive.\n\n**Micro flaws identified:**\n- None significant."
    },
    # 79. V6/G7 - Shopping Mall
    {
        "sample_id": "syn_p2_v6_g7_0079",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a shopping mall you go to.",
        "transcript_cleaned": "I often go to a shopping mall called Grand Plaza. It is the biggest mall in my city. It is located in the city center, so it is easily accessible. The mall has five floors. It has a wide variety of shops. Clothing, electronics, books. There is also a large food court with many restaurants. I usually go there on weekends with my friends. We like to window shop and watch a movie at the cinema. The mall is modern and clean. It is air-conditioned, which is nice in summer. Sometimes there are events or performances in the main hall. It is a lively place. I like it because it is a one-stop destination for entertainment and shopping. However, it can get very crowded during holidays. Parking is also a problem.",
        "word_count": 139,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'easily accessible' → 'easily accessible'", "grammar: 'wide variety' → 'wide variety'", "grammar: 'window shop' → 'window shop'", "grammar: 'air-conditioned' → 'air-conditioned'", "grammar: 'lively place' → 'lively place'", "grammar: 'one-stop destination' → 'one-stop destination'"],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR6] Vocabulary: 'accessible', 'variety', 'electronics', 'food court', 'window shop', 'cinema', 'modern', 'air-conditioned', 'performances', 'lively', 'destination', 'entertainment', 'crowded'.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'It is located..., so it is...' (Result). 'It is air-conditioned, which is nice...' (Relative clause). 'I like it because...' (Reason). 'However, it can get...' (Contrast). Accurate.",
        "vocabulary": 6,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a shopping mall you go to.\n\nTranscript: I often go to a shopping mall called Grand Plaza. It is the biggest mall in my city. It is located in the city center, so it is easily accessible. The mall has five floors. It has a wide variety of shops. Clothing, electronics, books. There is also a large food court with many restaurants. I usually go there on weekends with my friends. We like to window shop and watch a movie at the cinema. The mall is modern and clean. It is air-conditioned, which is nice in summer. Sometimes there are events or performances in the main hall. It is a lively place. I like it because it is a one-stop destination for entertainment and shopping. However, it can get very crowded during holidays. Parking is also a problem.\n\nWord Count: 139 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses 'accessible', 'variety', 'window shop', 'destination', 'entertainment'.\n\n>Band 5: Uses topic-specific words.\n\nNot Band 7: Limited precision.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Frequent error-free complex structures. Uses relative clauses, result clauses, and contrast markers correctly. High accuracy.\n\n>Band 6: Good control.\n\nNot Band 8: Range is not fully wide.\n\n**Micro flaws identified:**\n- None significant."
    },
    # 80. V6/G7 - Photo (Taken)
    {
        "sample_id": "syn_p2_v6_g7_0080",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a photograph you took that you are proud of.",
        "transcript_cleaned": "I took a photograph of a sunset at the beach last year. I am very proud of it because it looks professional. I used my new camera. I waited for the perfect moment when the sun was touching the horizon. The sky was orange and purple. The colors were vibrant. There was a silhouette of a boat in the distance. It created a beautiful contrast. I posted it on social media and received many likes. My friends said it looked like a painting. I think photography is a great hobby. It allows us to capture memories and beauty. I framed this photo and put it on my wall. Every time I look at it, I feel calm. It reminds me of that peaceful evening. I want to learn more about photography techniques.",
        "word_count": 139,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'perfect moment' → 'perfect moment'", "grammar: 'horizon' → 'horizon'", "grammar: 'vibrant' → 'vibrant'", "grammar: 'silhouette' → 'silhouette'", "grammar: 'contrast' → 'contrast'", "grammar: 'capture memories' → 'capture memories'", "grammar: 'techniques' → 'techniques'"],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR6] Vocabulary: 'professional', 'horizon', 'vibrant', 'silhouette', 'contrast', 'social media', 'received', 'painting', 'capture', 'memories', 'framed', 'peaceful', 'techniques'.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'I am very proud of it because...' (Reason). 'I waited for the moment when...' (Relative clause). 'Every time I look at it, I feel calm' (Time clause). Accurate.",
        "vocabulary": 6,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a photograph you took that you are proud of.\n\nTranscript: I took a photograph of a sunset at the beach last year. I am very proud of it because it looks professional. I used my new camera. I waited for the perfect moment when the sun was touching the horizon. The sky was orange and purple. The colors were vibrant. There was a silhouette of a boat in the distance. It created a beautiful contrast. I posted it on social media and received many likes. My friends said it looked like a painting. I think photography is a great hobby. It allows us to capture memories and beauty. I framed this photo and put it on my wall. Every time I look at it, I feel calm. It reminds me of that peaceful evening. I want to learn more about photography techniques.\n\nWord Count: 139 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses 'horizon', 'vibrant', 'silhouette', 'contrast', 'capture', 'techniques'.\n\n>Band 5: Uses topic-specific words.\n\nNot Band 7: Limited precision.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Frequent error-free complex structures. Uses relative clauses and time clauses correctly. High accuracy.\n\n>Band 6: Good control.\n\nNot Band 8: Sentence structure is a bit simple.\n\n**Micro flaws identified:**\n- None significant."
    }
]

with open(OUTPUT_FILE, 'a', encoding='utf-8') as f:
    for sample in samples:
        f.write(json.dumps(sample) + '\n')
