import json

OUTPUT_FILE = "ielts-data/phase3/v76_review_output/synthetic_batches/batch_p2_02.jsonl"

samples = [
    # 81. V7/G6 - Movie
    {
        "sample_id": "syn_p2_v7_g6_0081",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a movie that made you laugh.",
        "transcript_cleaned": "I recently watched a comedy movie called 'The Hangover'. It is a hilarious film about four friends who go to Las Vegas for a bachelor party. The plot is very engaging. They wake up the next morning with no memory of the previous night. The groom is missing. They have to retrace their steps to find him. The situations they get into are absurd and comical. For example, they find a tiger in their bathroom. I couldn't stop laughing throughout the movie. The acting was superb. The characters were eccentric and witty. I think the movie was successful because of the script. It was full of clever jokes. Although some scenes were a bit exaggerated, it was pure entertainment. I would recommend it to anyone who needs a good laugh.",
        "word_count": 139,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'hilarious film' → 'hilarious film'", "grammar: 'engaging' → 'engaging'", "grammar: 'retrace their steps' → 'retrace their steps'", "grammar: 'absurd and comical' → 'absurd and comical'", "grammar: 'eccentric and witty' → 'eccentric and witty'", "grammar: 'exaggerated' → 'exaggerated'", "grammar: 'pure entertainment' → 'pure entertainment'"],
        "grammar_profile": {"complexity": "high", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR7] Vocabulary: 'hilarious', 'bachelor party', 'engaging', 'retrace', 'absurd', 'comical', 'superb', 'eccentric', 'witty', 'script', 'exaggerated', 'entertainment'. Uses less common lexical items with some awareness of style and collocation.",
        "grammar_reason": "[GRA6] Mix of simple and complex structures. 'It is a hilarious film about four friends who go...' (Relative clause). 'Although some scenes were a bit exaggerated, it was...' (Concessive). Generally accurate.",
        "vocabulary": 7,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a movie that made you laugh.\n\nTranscript: I recently watched a comedy movie called 'The Hangover'. It is a hilarious film about four friends who go to Las Vegas for a bachelor party. The plot is very engaging. They wake up the next morning with no memory of the previous night. The groom is missing. They have to retrace their steps to find him. The situations they get into are absurd and comical. For example, they find a tiger in their bathroom. I couldn't stop laughing throughout the movie. The acting was superb. The characters were eccentric and witty. I think the movie was successful because of the script. It was full of clever jokes. Although some scenes were a bit exaggerated, it was pure entertainment. I would recommend it to anyone who needs a good laugh.\n\nWord Count: 139 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses 'hilarious', 'bachelor party', 'retrace', 'absurd', 'comical', 'eccentric', 'witty', 'exaggerated'. Shows awareness of style and collocation.\n\n>Band 6: More precise and varied.\n\nNot Band 8: Lacks sophistication.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Mix of structures. 'who go', 'Although'. Generally accurate.\n\n>Band 5: More complex structures.\n\nNot Band 7: Sentence variety is somewhat limited.\n\n**Micro flaws identified:**\n- None significant."
    },
    # 82. V7/G6 - Ideal Job
    {
        "sample_id": "syn_p2_v7_g6_0082",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe your ideal job.",
        "transcript_cleaned": "My ideal job would be a travel writer. I have a passion for exploring new cultures and destinations. I love writing and sharing my experiences with others. As a travel writer, I would have the opportunity to visit exotic places. I could taste authentic cuisines and meet diverse people. It sounds like a dream job. However, I know it is not just a vacation. It requires hard work and dedication. I would need to research thoroughly and write engaging articles. Deadlines can be stressful. But the rewards are worth it. I would be able to broaden my horizons and gain a deeper understanding of the world. Flexibility is also a key factor. I don't want a 9-to-5 job. I prefer autonomy and creativity. This career path aligns with my interests perfectly.",
        "word_count": 139,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'passion for exploring' → 'passion for exploring'", "grammar: 'exotic places' → 'exotic places'", "grammar: 'authentic cuisines' → 'authentic cuisines'", "grammar: 'diverse people' → 'diverse people'", "grammar: 'dedication' → 'dedication'", "grammar: 'research thoroughly' → 'research thoroughly'", "grammar: 'broaden my horizons' → 'broaden my horizons'", "grammar: 'autonomy' → 'autonomy'", "grammar: 'career path' → 'career path'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR7] Vocabulary: 'passion', 'exploring', 'destinations', 'exotic', 'authentic', 'cuisines', 'diverse', 'dedication', 'thoroughly', 'engaging', 'broaden horizons', 'flexibility', 'autonomy', 'aligns'. Good collocations.",
        "grammar_reason": "[GRA6] Mix of structures. 'I would have the opportunity...' (Modal). 'However, I know it is...' (Contrast). 'I prefer autonomy...' (Simple). Accurate.",
        "vocabulary": 7,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe your ideal job.\n\nTranscript: My ideal job would be a travel writer. I have a passion for exploring new cultures and destinations. I love writing and sharing my experiences with others. As a travel writer, I would have the opportunity to visit exotic places. I could taste authentic cuisines and meet diverse people. It sounds like a dream job. However, I know it is not just a vacation. It requires hard work and dedication. I would need to research thoroughly and write engaging articles. Deadlines can be stressful. But the rewards are worth it. I would be able to broaden my horizons and gain a deeper understanding of the world. Flexibility is also a key factor. I don't want a 9-to-5 job. I prefer autonomy and creativity. This career path aligns with my interests perfectly.\n\nWord Count: 139 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses 'exotic', 'authentic', 'diverse', 'dedication', 'thoroughly', 'broaden horizons', 'autonomy', 'aligns'. Shows awareness of style.\n\n>Band 6: More precise and varied.\n\nNot Band 8: Lacks sophistication.\n\n**Idiom present:** Yes ('broaden my horizons', '9-to-5 job')\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Mix of structures. Uses modals ('would', 'could') correctly. Generally accurate.\n\n>Band 5: More complex structures.\n\nNot Band 7: Sentence structure is somewhat repetitive.\n\n**Micro flaws identified:**\n- None significant."
    },
    # 83. V7/G6 - Crowded Place (Festival)
    {
        "sample_id": "syn_p2_v7_g6_0083",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a crowded place you visited.",
        "transcript_cleaned": "I visited a music festival in my city last summer. It was incredibly crowded. Thousands of people gathered in the central park. The atmosphere was electrifying. Vibrant energy. I went there to see my favorite band perform. Getting to the stage was a struggle. We had to squeeze through the crowd. It was a bit claustrophobic. However, once the music started, I forgot about the discomfort. The crowd sang along in unison. It was a magical moment. I felt a sense of belonging. The festival also had food stalls offering diverse cuisines. I tried some street food. It was delicious. Although it was packed and noisy, I enjoyed the communal experience. It is amazing how music can unite people from different backgrounds.",
        "word_count": 133,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'incredibly crowded' → 'incredibly crowded'", "grammar: 'electrifying' → 'electrifying'", "grammar: 'squeeze through' → 'squeeze through'", "grammar: 'claustrophobic' → 'claustrophobic'", "grammar: 'in unison' → 'in unison'", "grammar: 'sense of belonging' → 'sense of belonging'", "grammar: 'diverse cuisines' → 'diverse cuisines'", "grammar: 'communal experience' → 'communal experience'", "grammar: 'unite people' → 'unite people'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR7] Vocabulary: 'incredibly', 'gathered', 'electrifying', 'vibrant', 'squeeze', 'claustrophobic', 'discomfort', 'unison', 'belonging', 'diverse', 'cuisines', 'communal', 'unite'. Good collocations.",
        "grammar_reason": "[GRA6] Mix of structures. 'It was incredibly crowded' (Simple). 'We had to squeeze...' (Modals). 'Although it was packed..., I enjoyed...' (Concessive). Generally accurate.",
        "vocabulary": 7,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a crowded place you visited.\n\nTranscript: I visited a music festival in my city last summer. It was incredibly crowded. Thousands of people gathered in the central park. The atmosphere was electrifying. Vibrant energy. I went there to see my favorite band perform. Getting to the stage was a struggle. We had to squeeze through the crowd. It was a bit claustrophobic. However, once the music started, I forgot about the discomfort. The crowd sang along in unison. It was a magical moment. I felt a sense of belonging. The festival also had food stalls offering diverse cuisines. I tried some street food. It was delicious. Although it was packed and noisy, I enjoyed the communal experience. It is amazing how music can unite people from different backgrounds.\n\nWord Count: 133 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses 'electrifying', 'vibrant', 'squeeze', 'claustrophobic', 'unison', 'communal'. Shows awareness of style.\n\n>Band 6: More precise and varied.\n\nNot Band 8: Lacks sophistication.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Mix of structures. 'Although it was packed...'. Generally accurate.\n\n>Band 5: More complex structures.\n\nNot Band 7: Simple sentences still common.\n\n**Micro flaws identified:**\n- None significant."
    },
    # 84. V7/G6 - Traditional Product
    {
        "sample_id": "syn_p2_v7_g6_0084",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a traditional product in your country.",
        "transcript_cleaned": "I would like to talk about silk. It is a traditional product of my country, Vietnam. Silk has been produced here for centuries. It is known for its high quality and softness. The process of making silk is meticulous. It involves raising silkworms and harvesting their cocoons. The weavers then spin the threads into fabric. It requires great skill and patience. Silk is often used to make traditional costumes like Ao Dai. It is elegant and graceful. Many tourists buy silk products as souvenirs. Scarves, ties, dresses. I think silk represents our cultural heritage. It is a symbol of beauty and craftsmanship. Although modern fabrics are cheaper, silk remains popular because of its unique texture and durability. We should preserve this traditional craft.",
        "word_count": 139,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'meticulous' → 'meticulous'", "grammar: 'harvesting' → 'harvesting'", "grammar: 'weavers' → 'weavers'", "grammar: 'costumes' → 'costumes'", "grammar: 'cultural heritage' → 'cultural heritage'", "grammar: 'craftsmanship' → 'craftsmanship'", "grammar: 'durability' → 'durability'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR7] Vocabulary: 'meticulous', 'raising', 'harvesting', 'cocoons', 'weavers', 'spin', 'fabric', 'costumes', 'elegant', 'graceful', 'souvenirs', 'heritage', 'craftsmanship', 'texture', 'durability', 'preserve'.",
        "grammar_reason": "[GRA6] Mix of structures. 'Silk has been produced here for centuries' (Passive/Present Perfect). 'It involves raising...' (Gerund). 'Although modern fabrics are cheaper...' (Concessive). Accurate.",
        "vocabulary": 7,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a traditional product in your country.\n\nTranscript: I would like to talk about silk. It is a traditional product of my country, Vietnam. Silk has been produced here for centuries. It is known for its high quality and softness. The process of making silk is meticulous. It involves raising silkworms and harvesting their cocoons. The weavers then spin the threads into fabric. It requires great skill and patience. Silk is often used to make traditional costumes like Ao Dai. It is elegant and graceful. Many tourists buy silk products as souvenirs. Scarves, ties, dresses. I think silk represents our cultural heritage. It is a symbol of beauty and craftsmanship. Although modern fabrics are cheaper, silk remains popular because of its unique texture and durability. We should preserve this traditional craft.\n\nWord Count: 139 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses 'meticulous', 'harvesting', 'cocoons', 'weavers', 'craftsmanship', 'texture', 'durability'. Shows awareness of style.\n\n>Band 6: More precise and varied.\n\nNot Band 8: Lacks sophistication.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Mix of structures. 'Silk has been produced...' (Passive). 'Although modern fabrics...'. Generally accurate.\n\n>Band 5: More complex structures.\n\nNot Band 7: Simple sentences still common.\n\n**Micro flaws identified:**\n- None significant."
    },
    # 85. V7/G6 - Complaint (Service)
    {
        "sample_id": "syn_p2_v7_g6_0085",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a time you received bad service.",
        "transcript_cleaned": "I had a terrible experience at a hotel last month. I booked a room for my holiday. When I arrived, the receptionist was rude and dismissive. She didn't greet me properly. It took a long time to check in. When I got to my room, it was messy. Unacceptable. The bed was not made, and there were towels on the floor. I was furious. I called the reception to complain. They didn't apologize sincerely. They just said they were busy. Lack of professionalism. I felt frustrated and disrespected. I decided to leave and find another hotel. I wrote a negative review online to warn other customers. Good service is crucial in hospitality industry. Businesses should prioritize customer satisfaction.",
        "word_count": 133,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'rude and dismissive' → 'rude and dismissive'", "grammar: 'unacceptable' → 'unacceptable'", "grammar: 'furious' → 'furious'", "grammar: 'sincerely' → 'sincerely'", "grammar: 'professionalism' → 'professionalism'", "grammar: 'frustrated and disrespected' → 'frustrated and disrespected'", "grammar: 'hospitality industry' → 'the hospitality industry'", "grammar: 'prioritize' → 'prioritize'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR7] Vocabulary: 'terrible', 'receptionist', 'rude', 'dismissive', 'greet', 'unacceptable', 'furious', 'sincerely', 'professionalism', 'frustrated', 'disrespected', 'negative review', 'crucial', 'hospitality', 'prioritize', 'satisfaction'.",
        "grammar_reason": "[GRA6] Mix of structures. 'When I arrived, the receptionist was...' (Time clause). 'They didn't apologize sincerely' (Adverb). 'I decided to leave...' (Infinitive). Accurate but simple structure.",
        "vocabulary": 7,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a time you received bad service.\n\nTranscript: I had a terrible experience at a hotel last month. I booked a room for my holiday. When I arrived, the receptionist was rude and dismissive. She didn't greet me properly. It took a long time to check in. When I got to my room, it was messy. Unacceptable. The bed was not made, and there were towels on the floor. I was furious. I called the reception to complain. They didn't apologize sincerely. They just said they were busy. Lack of professionalism. I felt frustrated and disrespected. I decided to leave and find another hotel. I wrote a negative review online to warn other customers. Good service is crucial in hospitality industry. Businesses should prioritize customer satisfaction.\n\nWord Count: 133 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses 'dismissive', 'unacceptable', 'professionalism', 'frustrated', 'disrespected', 'prioritize'. Shows awareness of style.\n\n>Band 6: More precise and varied.\n\nNot Band 8: Lacks sophistication.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Mix of structures. 'When I arrived...'. 'I decided to...'. Generally accurate.\n\n>Band 5: More complex structures.\n\nNot Band 7: Simple sentences still common.\n\n**Micro flaws identified:**\n- 'hospitality industry' should be 'the hospitality industry'"
    },
    # 86. V7/G6 - Important Letter
    {
        "sample_id": "syn_p2_v7_g6_0086",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe an important letter or email you wrote.",
        "transcript_cleaned": "I wrote a formal email to apply for a scholarship last year. It was a significant opportunity for me. I wanted to study abroad. I spent days drafting the email. I had to express my motivation and qualifications clearly. I highlighted my academic achievements and extracurricular activities. I used formal language. Appropriate tone. I addressed the admission committee respectfully. I proofread it many times to avoid errors. Typos. I asked my teacher to review it as well. Sending that email was nerve-wracking. I was anxious about the result. Fortunately, I received a positive response. I got the scholarship. It was a life-changing moment. Writing effective emails is an essential skill in academic and professional settings.",
        "word_count": 133,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'significant opportunity' → 'significant opportunity'", "grammar: 'drafting' → 'drafting'", "grammar: 'qualifications' → 'qualifications'", "grammar: 'academic achievements' → 'academic achievements'", "grammar: 'extracurricular activities' → 'extracurricular activities'", "grammar: 'proofread' → 'proofread'", "grammar: 'nerve-wracking' → 'nerve-wracking'", "grammar: 'effective emails' → 'effective emails'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR7] Vocabulary: 'formal', 'scholarship', 'significant', 'opportunity', 'drafting', 'motivation', 'qualifications', 'highlighted', 'achievements', 'extracurricular', 'appropriate', 'committee', 'proofread', 'typos', 'nerve-wracking', 'anxious', 'effective', 'essential'.",
        "grammar_reason": "[GRA6] Mix of structures. 'I spent days drafting the email' (Gerund). 'I had to express...' (Modal). 'I asked my teacher to review it' (Infinitive pattern). Accurate.",
        "vocabulary": 7,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe an important letter or email you wrote.\n\nTranscript: I wrote a formal email to apply for a scholarship last year. It was a significant opportunity for me. I wanted to study abroad. I spent days drafting the email. I had to express my motivation and qualifications clearly. I highlighted my academic achievements and extracurricular activities. I used formal language. Appropriate tone. I addressed the admission committee respectfully. I proofread it many times to avoid errors. Typos. I asked my teacher to review it as well. Sending that email was nerve-wracking. I was anxious about the result. Fortunately, I received a positive response. I got the scholarship. It was a life-changing moment. Writing effective emails is an essential skill in academic and professional settings.\n\nWord Count: 133 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses 'drafting', 'qualifications', 'highlighted', 'achievements', 'extracurricular', 'proofread', 'nerve-wracking'. Shows awareness of style.\n\n>Band 6: More precise and varied.\n\nNot Band 8: Lacks sophistication.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Mix of structures. 'I spent days drafting...'. 'I asked my teacher to...'. Generally accurate.\n\n>Band 5: More complex structures.\n\nNot Band 7: Simple sentences still common.\n\n**Micro flaws identified:**\n- None significant."
    },
    # 87. V7/G6 - Changed Life
    {
        "sample_id": "syn_p2_v7_g6_0087",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe something that changed your life.",
        "transcript_cleaned": "Learning English changed my life significantly. Before, I was shy and lacked confidence. I couldn't communicate with foreigners. I felt limited. But when I started learning English seriously, everything changed. It opened new doors for me. Opportunities. I could access a vast amount of information online. Knowledge. I made friends from different countries. Cultural exchange. It broadened my perspective. I became more open-minded and tolerant. English also helped me in my career. I got a better job in a multinational company. Promotion. I can travel the world without language barrier. Independence. I think learning a language is not just about words. It is about connecting with the world. It transformed me into a better version of myself.",
        "word_count": 139,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'significantly' → 'significantly'", "grammar: 'lacked confidence' → 'lacked confidence'", "grammar: 'vast amount' → 'vast amount'", "grammar: 'broadened my perspective' → 'broadened my perspective'", "grammar: 'open-minded and tolerant' → 'open-minded and tolerant'", "grammar: 'multinational company' → 'multinational company'", "grammar: 'language barrier' → 'language barriers'", "grammar: 'transformed me' → 'transformed me'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR7] Vocabulary: 'significantly', 'lacked', 'confidence', 'limited', 'access', 'vast', 'perspective', 'open-minded', 'tolerant', 'multinational', 'promotion', 'barrier', 'independence', 'transformed', 'version'. Good range.",
        "grammar_reason": "[GRA6] Mix of structures. 'Before, I was..., but when I started..., everything changed' (Contrast/Time clause). 'I think learning a language is not just..., it is...' (Noun clause). Accurate.",
        "vocabulary": 7,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe something that changed your life.\n\nTranscript: Learning English changed my life significantly. Before, I was shy and lacked confidence. I couldn't communicate with foreigners. I felt limited. But when I started learning English seriously, everything changed. It opened new doors for me. Opportunities. I could access a vast amount of information online. Knowledge. I made friends from different countries. Cultural exchange. It broadened my perspective. I became more open-minded and tolerant. English also helped me in my career. I got a better job in a multinational company. Promotion. I can travel the world without language barrier. Independence. I think learning a language is not just about words. It is about connecting with the world. It transformed me into a better version of myself.\n\nWord Count: 139 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses 'significantly', 'lacked', 'perspective', 'open-minded', 'tolerant', 'multinational', 'barrier', 'transformed'. Shows awareness of style.\n\n>Band 6: More precise and varied.\n\nNot Band 8: Lacks sophistication.\n\n**Idiom present:** Yes ('opened new doors', 'better version of myself')\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Mix of structures. 'Before... but when...'. Generally accurate.\n\n>Band 5: More complex structures.\n\nNot Band 7: Simple sentences still common.\n\n**Micro flaws identified:**\n- 'language barrier' should be 'language barriers'"
    },
    # 88. V7/G6 - Performance
    {
        "sample_id": "syn_p2_v7_g6_0088",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a performance you watched.",
        "transcript_cleaned": "I watched a theatrical performance of 'Romeo and Juliet' last month. It was staged in a local theater. The production was impressive. The set design was realistic and detailed. It transported audience to Verona. The costumes were authentic to the period. Renaissance style. The actors were talented. They portrayed the characters with emotion and depth. Especially Juliet. She was captivating. I was moved by the tragic ending. Although I knew the story, I still cried. The lighting and sound effects enhanced the mood. Dramatic. The applause at the end was thunderous. Standing ovation. I think live theatre is unique because of the interaction between actors and audience. It was a memorable evening. Artistic experience.",
        "word_count": 133,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'theatrical performance' → 'theatrical performance'", "grammar: 'staged' → 'staged'", "grammar: 'production' → 'production'", "grammar: 'transported audience' → 'transported the audience'", "grammar: 'authentic' → 'authentic'", "grammar: 'portrayed' → 'portrayed'", "grammar: 'captivating' → 'captivating'", "grammar: 'tragic ending' → 'tragic ending'", "grammar: 'enhanced' → 'enhanced'", "grammar: 'thunderous' → 'thunderous'", "grammar: 'standing ovation' → 'standing ovation'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR7] Vocabulary: 'theatrical', 'staged', 'production', 'realistic', 'transported', 'authentic', 'portrayed', 'captivating', 'tragic', 'enhanced', 'thunderous', 'ovation', 'interaction'. Good collocations.",
        "grammar_reason": "[GRA6] Mix of structures. 'It was staged in a local theater' (Passive). 'Although I knew the story, I still cried' (Concessive). 'I think live theatre is unique because...' (Reason). Accurate.",
        "vocabulary": 7,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a performance you watched.\n\nTranscript: I watched a theatrical performance of 'Romeo and Juliet' last month. It was staged in a local theater. The production was impressive. The set design was realistic and detailed. It transported audience to Verona. The costumes were authentic to the period. Renaissance style. The actors were talented. They portrayed the characters with emotion and depth. Especially Juliet. She was captivating. I was moved by the tragic ending. Although I knew the story, I still cried. The lighting and sound effects enhanced the mood. Dramatic. The applause at the end was thunderous. Standing ovation. I think live theatre is unique because of the interaction between actors and audience. It was a memorable evening. Artistic experience.\n\nWord Count: 133 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses 'theatrical', 'staged', 'transported', 'authentic', 'portrayed', 'captivating', 'thunderous', 'ovation'. Shows awareness of style.\n\n>Band 6: More precise and varied.\n\nNot Band 8: Lacks sophistication.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Mix of structures. 'Although I knew...'. 'It was staged...'. Generally accurate.\n\n>Band 5: More complex structures.\n\nNot Band 7: Simple sentences still common.\n\n**Micro flaws identified:**\n- 'transported audience' should be 'transported the audience'"
    },
    # 89. V7/G6 - Healthy Habit
    {
        "sample_id": "syn_p2_v7_g6_0089",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a healthy habit you have.",
        "transcript_cleaned": "My healthy habit is drinking warm lemon water every morning. I started this routine two years ago. I read an article about its benefits. Detoxification. It helps to cleanse the system and boost metabolism. Digestion. It is simple to prepare. Just squeeze half a lemon into warm water. I drink it on an empty stomach. Before breakfast. I feel refreshed and hydrated. Energized. Since I started this habit, my skin has improved. Glowing. I also rarely get sick. Immune system. I think small habits can make a big difference to our health. Consistency is key. Many people look for complicated diets, but simple remedies are often the best. I encourage my family to do it too. It is a natural way to stay healthy.",
        "word_count": 139,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'routine' → 'routine'", "grammar: 'detoxification' → 'detoxification'", "grammar: 'cleanse the system' → 'cleanse the system'", "grammar: 'boost metabolism' → 'boost metabolism'", "grammar: 'digestion' → 'digestion'", "grammar: 'refreshed and hydrated' → 'refreshed and hydrated'", "grammar: 'immune system' → 'immune system'", "grammar: 'consistency is key' → 'consistency is key'", "grammar: 'complicated diets' → 'complicated diets'", "grammar: 'remedies' → 'remedies'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR7] Vocabulary: 'routine', 'benefits', 'detoxification', 'cleanse', 'boost', 'metabolism', 'digestion', 'squeeze', 'hydrated', 'energized', 'glowing', 'immune system', 'consistency', 'complicated', 'remedies'. Good technical terms.",
        "grammar_reason": "[GRA6] Mix of structures. 'Since I started this habit, my skin has improved' (Present Perfect). 'I think small habits can make...' (Noun clause). 'Many people look for..., but simple remedies are...' (Compound). Accurate.",
        "vocabulary": 7,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a healthy habit you have.\n\nTranscript: My healthy habit is drinking warm lemon water every morning. I started this routine two years ago. I read an article about its benefits. Detoxification. It helps to cleanse the system and boost metabolism. Digestion. It is simple to prepare. Just squeeze half a lemon into warm water. I drink it on an empty stomach. Before breakfast. I feel refreshed and hydrated. Energized. Since I started this habit, my skin has improved. Glowing. I also rarely get sick. Immune system. I think small habits can make a big difference to our health. Consistency is key. Many people look for complicated diets, but simple remedies are often the best. I encourage my family to do it too. It is a natural way to stay healthy.\n\nWord Count: 139 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses 'detoxification', 'cleanse', 'metabolism', 'digestion', 'hydrated', 'immune system', 'remedies'. Shows awareness of style.\n\n>Band 6: More precise and varied.\n\nNot Band 8: Lacks sophistication.\n\n**Idiom present:** Yes ('Consistency is key')\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Mix of structures. 'Since I started...'. 'Many people look..., but...'. Generally accurate.\n\n>Band 5: More complex structures.\n\nNot Band 7: Simple sentences still common.\n\n**Micro flaws identified:**\n- None significant."
    },
    # 90. V7/G6 - Ambition
    {
        "sample_id": "syn_p2_v7_g6_0090",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe an ambition you have not achieved yet.",
        "transcript_cleaned": "I have an ambition to learn a third language. Spanish. I speak English and my native language fluently. But I want to expand my linguistic skills. I am fascinated by Spanish culture. Music, dance, food. Also, it is a widely spoken language. Global. If I know Spanish, I can travel to South America easily. I tried to learn it a few years ago. Self-study. But I failed. Lack of discipline. I gave up too soon. It requires consistent practice. Dedication. I regret stopping. My plan is to enroll in a language course next year. Professional guidance. I want to achieve fluency. It will be challenging, but rewarding. I believe being multilingual is a great asset in modern world. It enhances cognitive abilities.",
        "word_count": 136,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'linguistic skills' → 'linguistic skills'", "grammar: 'fascinated by' → 'fascinated by'", "grammar: 'widely spoken' → 'widely spoken'", "grammar: 'lack of discipline' → 'lack of discipline'", "grammar: 'consistent practice' → 'consistent practice'", "grammar: 'enroll in' → 'enroll in'", "grammar: 'guidance' → 'guidance'", "grammar: 'achieve fluency' → 'achieve fluency'", "grammar: 'multilingual' → 'multilingual'", "grammar: 'asset' → 'asset'", "grammar: 'enhances cognitive abilities' → 'enhances cognitive abilities'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR7] Vocabulary: 'ambition', 'fluently', 'expand', 'linguistic', 'fascinated', 'widely spoken', 'discipline', 'consistent', 'dedication', 'enroll', 'guidance', 'fluency', 'multilingual', 'asset', 'enhances', 'cognitive'. Good academic range.",
        "grammar_reason": "[GRA6] Mix of structures. 'If I know Spanish, I can travel...' (First Conditional). 'I tried to learn it..., but I failed' (Compound). 'I believe being multilingual is...' (Noun clause + Gerund). Accurate.",
        "vocabulary": 7,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe an ambition you have not achieved yet.\n\nTranscript: I have an ambition to learn a third language. Spanish. I speak English and my native language fluently. But I want to expand my linguistic skills. I am fascinated by Spanish culture. Music, dance, food. Also, it is a widely spoken language. Global. If I know Spanish, I can travel to South America easily. I tried to learn it a few years ago. Self-study. But I failed. Lack of discipline. I gave up too soon. It requires consistent practice. Dedication. I regret stopping. My plan is to enroll in a language course next year. Professional guidance. I want to achieve fluency. It will be challenging, but rewarding. I believe being multilingual is a great asset in modern world. It enhances cognitive abilities.\n\nWord Count: 136 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses 'linguistic', 'fascinated', 'discipline', 'enroll', 'fluency', 'multilingual', 'asset', 'cognitive'. Shows awareness of style.\n\n>Band 6: More precise and varied.\n\nNot Band 8: Lacks sophistication.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Mix of structures. 'If I know Spanish...'. 'I believe being...'. Generally accurate.\n\n>Band 5: More complex structures.\n\nNot Band 7: Simple sentences still common.\n\n**Micro flaws identified:**\n- None significant."
    }
]

with open(OUTPUT_FILE, 'a', encoding='utf-8') as f:
    for sample in samples:
        f.write(json.dumps(sample) + '\n')
