import json

OUTPUT_FILE = "ielts-data/phase3/v76_review_output/synthetic_batches/batch_p2_12.jsonl"

samples = [
    # 561. V5/G7 - Job (Dislike)
    {
        "sample_id": "syn_p2_v5_g7_0561",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a job you would hate to do.",
        "transcript_cleaned": "I would really hate to be a cleaner in a big hotel. The main reason is that I think it is dirty work. Cleaning toilets and changing sheets every day sounds very boring to me. Also, the salary is usually low, which is not good. If I had to do this job, I would be very unhappy. I prefer a job where I can use my brain more. Although cleaners are important, I do not want to do it. It is hard work for the body. I would rather work in an office with computers.",
        "word_count": 97,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR5] Vocabulary: 'hate', 'cleaner', 'hotel', 'dirty work', 'toilets', 'sheets', 'boring', 'salary', 'low', 'unhappy', 'brain', 'important', 'hard work', 'body', 'office'. Functional but limited range. >Band 4: Uses some relevant words. Not Band 6: Lacks variety.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'The main reason is that...' (Noun clause). 'If I had to do..., I would be...' (Second conditional). 'Where I can use my brain' (Relative clause). 'Although cleaners are important...' (Concessive clause). Accurate.",
        "vocabulary": 5,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a job you would hate to do.\n\nTranscript: I would really hate to be a cleaner in a big hotel. The main reason is that I think it is dirty work. Cleaning toilets and changing sheets every day sounds very boring to me. Also, the salary is usually low, which is not good. If I had to do this job, I would be very unhappy. I prefer a job where I can use my brain more. Although cleaners are important, I do not want to do it. It is hard work for the body. I would rather work in an office with computers.\n\nWord Count: 97 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses basic vocabulary: 'dirty', 'boring', 'salary'. Limited range.\n\n>Band 4: Clear meaning.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures like second conditionals and noun clauses correctly. Good grammatical control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Not enough range of structures.\n\n**Micro flaws identified:**\n- None."
    },
    # 562. V5/G7 - Place (Shop)
    {
        "sample_id": "syn_p2_v5_g7_0562",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a shop you often visit.",
        "transcript_cleaned": "I often visit a supermarket called Tesco near my house. It is a very convenient place because it sells everything I need. I go there to buy food for the week, like bread and milk. The shop is big and clean, which I like. The staff are friendly and help me find things. If I go on Saturday, it is usually crowded. I prefer to go in the evening when it is quiet. Although the prices are a bit high, the quality is good. It is the best shop in my neighborhood.",
        "word_count": 95,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR5] Vocabulary: 'supermarket', 'convenient', 'sells', 'need', 'buy food', 'bread', 'milk', 'clean', 'staff', 'friendly', 'find things', 'crowded', 'evening', 'quiet', 'prices', 'quality', 'neighborhood'. Functional but limited range. >Band 4: Uses some relevant words. Not Band 6: Lacks variety.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'Because it sells...' (Reason clause). 'Like bread and milk' (Prepositional phrase). 'Which I like' (Relative clause). 'If I go..., it is...' (First conditional). 'When it is quiet' (Time clause). Accurate.",
        "vocabulary": 5,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a shop you often visit.\n\nTranscript: I often visit a supermarket called Tesco near my house. It is a very convenient place because it sells everything I need. I go there to buy food for the week, like bread and milk. The shop is big and clean, which I like. The staff are friendly and help me find things. If I go on Saturday, it is usually crowded. I prefer to go in the evening when it is quiet. Although the prices are a bit high, the quality is good. It is the best shop in my neighborhood.\n\nWord Count: 95 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses basic vocabulary: 'convenient', 'crowded', 'quality'. Limited range.\n\n>Band 4: Clear meaning.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures like conditionals and time clauses correctly. Good grammatical control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Not enough range of structures.\n\n**Micro flaws identified:**\n- None."
    },
    # 563. V5/G7 - Event (Family)
    {
        "sample_id": "syn_p2_v5_g7_0563",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a family celebration you remember.",
        "transcript_cleaned": "I remember my grandfather's 80th birthday party last year. It was a special event because all my relatives came. We had a big dinner in a nice restaurant. My mother ordered a huge cake with candles. We sang happy birthday to him, which made him smile. I gave him a watch as a gift. If we had celebrated at home, it would have been too much work. The party was fun, although I was tired at the end. It is a memory that I will keep for a long time.",
        "word_count": 93,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR5] Vocabulary: 'birthday party', 'special event', 'relatives', 'dinner', 'restaurant', 'ordered', 'huge cake', 'candles', 'sang', 'smile', 'gift', 'celebrated', 'tired', 'memory'. Functional but limited range. >Band 4: Uses some relevant words. Not Band 6: Lacks variety.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'Because all my relatives came' (Reason clause). 'Which made him smile' (Relative clause). 'If we had celebrated..., it would have been...' (Third conditional). 'Although I was tired...' (Concessive clause). Accurate.",
        "vocabulary": 5,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a family celebration you remember.\n\nTranscript: I remember my grandfather's 80th birthday party last year. It was a special event because all my relatives came. We had a big dinner in a nice restaurant. My mother ordered a huge cake with candles. We sang happy birthday to him, which made him smile. I gave him a watch as a gift. If we had celebrated at home, it would have been too much work. The party was fun, although I was tired at the end. It is a memory that I will keep for a long time.\n\nWord Count: 93 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses basic vocabulary: 'relatives', 'huge', 'celebrated'. Limited range.\n\n>Band 4: Clear meaning.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures like third conditionals and relative clauses correctly. Good grammatical control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Not enough range of structures.\n\n**Micro flaws identified:**\n- None."
    },
    # 564. V5/G7 - Person (Teacher)
    {
        "sample_id": "syn_p2_v5_g7_0564",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a teacher you liked.",
        "transcript_cleaned": "I liked my art teacher, Mrs. Green, who taught me in primary school. She was a very kind woman with a happy face. I enjoyed her classes because she let us be creative. We used to paint pictures and make things with paper. She always said my drawings were good, which encouraged me. If I made a mistake, she helped me fix it. I think she was a good teacher because she was patient. I still remember the things she taught me about colors. She made me love art.",
        "word_count": 91,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR5] Vocabulary: 'art teacher', 'primary school', 'kind', 'happy face', 'creative', 'paint pictures', 'drawings', 'encouraged', 'mistake', 'fix', 'patient', 'colors', 'love art'. Functional but limited range. >Band 4: Uses some relevant words. Not Band 6: Lacks variety.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'Who taught me...' (Relative clause). 'Because she let us be creative' (Reason clause). 'Which encouraged me' (Relative clause). 'If I made a mistake...' (First/mixed conditional contextually valid). 'Because she was patient' (Reason clause). Accurate.",
        "vocabulary": 5,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a teacher you liked.\n\nTranscript: I liked my art teacher, Mrs. Green, who taught me in primary school. She was a very kind woman with a happy face. I enjoyed her classes because she let us be creative. We used to paint pictures and make things with paper. She always said my drawings were good, which encouraged me. If I made a mistake, she helped me fix it. I think she was a good teacher because she was patient. I still remember the things she taught me about colors. She made me love art.\n\nWord Count: 91 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses basic vocabulary: 'creative', 'encouraged', 'patient'. Limited range.\n\n>Band 4: Clear meaning.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures like relative clauses and conditionals correctly. Good grammatical control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Not enough range of structures.\n\n**Micro flaws identified:**\n- None."
    },
    # 565. V5/G7 - Object (Toy)
    {
        "sample_id": "syn_p2_v5_g7_0565",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a toy you liked as a child.",
        "transcript_cleaned": "I had a teddy bear that I loved very much when I was small. It was brown and very soft. My parents gave it to me for my fifth birthday. I named him 'Beary'. I slept with him every night because I was afraid of the dark. If I lost him, I would cry. I liked to play games with him and my other toys. Although he is old now, I still keep him in my room. He reminds me of my happy childhood. It was my best friend.",
        "word_count": 93,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR5] Vocabulary: 'teddy bear', 'soft', 'birthday', 'named', 'slept', 'afraid of the dark', 'lost', 'cry', 'games', 'toys', 'old', 'keep', 'room', 'reminds', 'childhood', 'best friend'. Functional but limited range. >Band 4: Uses some relevant words. Not Band 6: Lacks variety.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'That I loved very much' (Relative clause). 'When I was small' (Time clause). 'Because I was afraid...' (Reason clause). 'If I lost him, I would cry' (Second conditional). 'Although he is old now...' (Concessive clause). Accurate.",
        "vocabulary": 5,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a toy you liked as a child.\n\nTranscript: I had a teddy bear that I loved very much when I was small. It was brown and very soft. My parents gave it to me for my fifth birthday. I named him 'Beary'. I slept with him every night because I was afraid of the dark. If I lost him, I would cry. I liked to play games with him and my other toys. Although he is old now, I still keep him in my room. He reminds me of my happy childhood. It was my best friend.\n\nWord Count: 93 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses basic vocabulary: 'soft', 'afraid', 'childhood'. Limited range.\n\n>Band 4: Clear meaning.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures like second conditionals and concessive clauses correctly. Good grammatical control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Not enough range of structures.\n\n**Micro flaws identified:**\n- None."
    },
    # 566. V5/G7 - Activity (Daily)
    {
        "sample_id": "syn_p2_v5_g7_0566",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe something you do to help your parents.",
        "transcript_cleaned": "I help my parents by washing the dishes after dinner every evening. It is a simple job, but it helps my mother a lot. She cooks the food, so I think it is fair that I clean. I start by collecting the dirty plates from the table. Then, I wash them with soap and water. If there are many dishes, it takes about 20 minutes. I listen to music while I work, which makes it less boring. My parents appreciate my help. It is one way I can show my love for them.",
        "word_count": 96,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR5] Vocabulary: 'washing dishes', 'dinner', 'simple job', 'helps', 'cooks', 'fair', 'clean', 'collecting', 'dirty plates', 'soap', 'water', 'music', 'boring', 'appreciate', 'show love'. Functional but limited range. >Band 4: Uses some relevant words. Not Band 6: Lacks variety.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'So I think it is fair...' (Result clause). 'That I clean' (Noun clause). 'If there are many dishes...' (First conditional). 'While I work' (Time clause). 'Which makes it less boring' (Relative clause). Accurate.",
        "vocabulary": 5,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe something you do to help your parents.\n\nTranscript: I help my parents by washing the dishes after dinner every evening. It is a simple job, but it helps my mother a lot. She cooks the food, so I think it is fair that I clean. I start by collecting the dirty plates from the table. Then, I wash them with soap and water. If there are many dishes, it takes about 20 minutes. I listen to music while I work, which makes it less boring. My parents appreciate my help. It is one way I can show my love for them.\n\nWord Count: 96 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses basic vocabulary: 'fair', 'collecting', 'appreciate'. Limited range.\n\n>Band 4: Clear meaning.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures like relative clauses and conditionals correctly. Good grammatical control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Not enough range of structures.\n\n**Micro flaws identified:**\n- None."
    },
    # 567. V5/G7 - Place (Travel)
    {
        "sample_id": "syn_p2_v5_g7_0567",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a country you would like to visit.",
        "transcript_cleaned": "I would like to visit Australia, which is a very big country. I have seen pictures of the Sydney Opera House, and it looks beautiful. I want to go to the beach and learn how to surf. Also, I want to see kangaroos and koalas in the wild. If I had enough money, I would fly there next summer. I heard the people are friendly and speak English. It would be a great adventure to travel around the country. Although the flight is long, I think it is worth it.",
        "word_count": 94,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR5] Vocabulary: 'visit', 'big country', 'pictures', 'Opera House', 'beautiful', 'beach', 'surf', 'kangaroos', 'koalas', 'wild', 'money', 'fly', 'friendly', 'adventure', 'travel', 'flight', 'long', 'worth it'. Functional but limited range. >Band 4: Uses some relevant words. Not Band 6: Lacks variety.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'Which is a very big country' (Relative clause). 'If I had enough money, I would fly...' (Second conditional). 'I heard the people are friendly' (Noun clause). 'Although the flight is long...' (Concessive clause). Accurate.",
        "vocabulary": 5,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a country you would like to visit.\n\nTranscript: I would like to visit Australia, which is a very big country. I have seen pictures of the Sydney Opera House, and it looks beautiful. I want to go to the beach and learn how to surf. Also, I want to see kangaroos and koalas in the wild. If I had enough money, I would fly there next summer. I heard the people are friendly and speak English. It would be a great adventure to travel around the country. Although the flight is long, I think it is worth it.\n\nWord Count: 94 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses basic vocabulary: 'surf', 'wild', 'adventure'. Limited range.\n\n>Band 4: Clear meaning.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures like second conditionals and concessive clauses correctly. Good grammatical control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Not enough range of structures.\n\n**Micro flaws identified:**\n- None."
    },
    # 568. V5/G7 - Book (Recommend)
    {
        "sample_id": "syn_p2_v5_g7_0568",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a book you recommend.",
        "transcript_cleaned": "I recommend a book called 'Harry Potter', which is very popular. It is about a boy who goes to a magic school. I read it when I was a teenager, and I liked it very much. The story is exciting because there are wizards and monsters. I think everyone should read it because it teaches you about friendship. If you like fantasy stories, you will love this book. Although it is long, it is easy to read. I have read it three times, and I still enjoy it.",
        "word_count": 90,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR5] Vocabulary: 'recommend', 'popular', 'magic school', 'teenager', 'exciting', 'wizards', 'monsters', 'friendship', 'fantasy stories', 'love', 'long', 'easy to read', 'enjoy'. Functional but limited range. >Band 4: Uses some relevant words. Not Band 6: Lacks variety.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'Which is very popular' (Relative clause). 'Who goes to a magic school' (Relative clause). 'Because there are wizards...' (Reason clause). 'If you like fantasy stories...' (First conditional). 'Although it is long...' (Concessive clause). Accurate.",
        "vocabulary": 5,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a book you recommend.\n\nTranscript: I recommend a book called 'Harry Potter', which is very popular. It is about a boy who goes to a magic school. I read it when I was a teenager, and I liked it very much. The story is exciting because there are wizards and monsters. I think everyone should read it because it teaches you about friendship. If you like fantasy stories, you will love this book. Although it is long, it is easy to read. I have read it three times, and I still enjoy it.\n\nWord Count: 90 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses basic vocabulary: 'magic', 'wizards', 'fantasy'. Limited range.\n\n>Band 4: Clear meaning.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures like relative clauses and conditionals correctly. Good grammatical control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Not enough range of structures.\n\n**Micro flaws identified:**\n- None."
    },
    # 569. V5/G7 - Activity (Exercise)
    {
        "sample_id": "syn_p2_v5_g7_0569",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe an exercise you do.",
        "transcript_cleaned": "I go running in the park every morning to stay healthy. It is a simple exercise that does not need any equipment. I run for 30 minutes before I go to work. I like it because the fresh air wakes me up. If it is raining, I do not go, which happens sometimes. Running makes my legs strong and helps me lose weight. Although I get tired, I feel good afterwards. I think it is the best way to start the day. I have been doing this for two years.",
        "word_count": 93,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR5] Vocabulary: 'running', 'park', 'stay healthy', 'simple exercise', 'equipment', 'fresh air', 'wakes me up', 'raining', 'legs strong', 'lose weight', 'tired', 'feel good', 'start the day'. Functional but limited range. >Band 4: Uses some relevant words. Not Band 6: Lacks variety.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'That does not need any equipment' (Relative clause). 'Before I go to work' (Time clause). 'If it is raining...' (First conditional). 'Which happens sometimes' (Relative clause). 'Although I get tired...' (Concessive clause). Accurate.",
        "vocabulary": 5,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe an exercise you do.\n\nTranscript: I go running in the park every morning to stay healthy. It is a simple exercise that does not need any equipment. I run for 30 minutes before I go to work. I like it because the fresh air wakes me up. If it is raining, I do not go, which happens sometimes. Running makes my legs strong and helps me lose weight. Although I get tired, I feel good afterwards. I think it is the best way to start the day. I have been doing this for two years.\n\nWord Count: 93 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses basic vocabulary: 'healthy', 'equipment', 'lose weight'. Limited range.\n\n>Band 4: Clear meaning.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures like relative clauses and conditionals correctly. Good grammatical control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Not enough range of structures.\n\n**Micro flaws identified:**\n- None."
    },
    # 570. V5/G7 - Object (Technology)
    {
        "sample_id": "syn_p2_v5_g7_0570",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a piece of technology you use.",
        "transcript_cleaned": "I use my smartphone every day, which is very useful. It is a small device that I can carry in my pocket. I use it to call my friends and send messages. Also, I can use the internet to find information. If I get lost, I use the map app. I bought it last year because my old phone was broken. Although it was expensive, I think it was worth the money. I take many photos with it because the camera is good. It helps me stay connected with the world.",
        "word_count": 94,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR5] Vocabulary: 'smartphone', 'useful', 'device', 'carry', 'pocket', 'messages', 'internet', 'information', 'lost', 'map app', 'broken', 'expensive', 'worth the money', 'camera', 'connected'. Functional but limited range. >Band 4: Uses some relevant words. Not Band 6: Lacks variety.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'Which is very useful' (Relative clause). 'That I can carry...' (Relative clause). 'If I get lost...' (First conditional). 'Because my old phone was broken' (Reason clause). 'Although it was expensive...' (Concessive clause). Accurate.",
        "vocabulary": 5,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a piece of technology you use.\n\nTranscript: I use my smartphone every day, which is very useful. It is a small device that I can carry in my pocket. I use it to call my friends and send messages. Also, I can use the internet to find information. If I get lost, I use the map app. I bought it last year because my old phone was broken. Although it was expensive, I think it was worth the money. I take many photos with it because the camera is good. It helps me stay connected with the world.\n\nWord Count: 94 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses basic vocabulary: 'device', 'internet', 'connected'. Limited range.\n\n>Band 4: Clear meaning.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures like relative clauses and conditionals correctly. Good grammatical control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Not enough range of structures.\n\n**Micro flaws identified:**\n- None."
    }
]

with open(OUTPUT_FILE, 'a', encoding='utf-8') as f:
    for sample in samples:
        f.write(json.dumps(sample) + '\n')
