import json

OUTPUT_FILE = "ielts-data/phase3/v76_review_output/synthetic_batches/batch_p2_12.jsonl"

samples = [
    # 571. V7/G5 - Book (Recently Read)
    {
        "sample_id": "syn_p2_v7_g5_0571",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a book you read recently.",
        "transcript_cleaned": "I recently reading a novel called 'The Great Gatsby', which is a classic of American literature. It explore themes of decadence, idealism, and social upheaval. I was fascinated by the vivid descriptions of the Jazz Age. The protagonist, Jay Gatsby, are a mysterious millionaire who throw lavish parties. However, he is drive by an obsession with the past. The book revealing the emptiness of the American Dream. Although the language were sometimes difficult, I finding the plot compelling. It is a tragic story that resonate with many readers. I would recommending it to anyone interested in history.",
        "word_count": 97,
        "response_type": "long_turn",
        "micro_flaws": ["tense: 'I recently reading' should be 'I recently read'", "agreement: 'It explore' should be 'It explores'", "agreement: 'Gatsby, are' should be 'is'", "agreement: 'who throw' should be 'who throws'", "tense: 'he is drive' should be 'driven'", "tense: 'book revealing' should be 'reveals'", "agreement: 'language were' should be 'was'", "tense: 'I finding' should be 'found'", "agreement: 'story that resonate' should be 'resonates'", "grammar: 'would recommending' should be 'would recommend'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR7] Vocabulary: 'classic', 'literature', 'themes', 'decadence', 'idealism', 'social upheaval', 'vivid descriptions', 'Jazz Age', 'protagonist', 'mysterious', 'millionaire', 'lavish parties', 'obsession', 'emptiness', 'American Dream', 'compelling', 'tragic', 'resonate'. Sophisticated and precise. >Band 6: Uses less common words effectively. Not Band 8: Some errors in usage.",
        "grammar_reason": "[GRA5] Frequent grammatical errors. Continuous tense used incorrectly ('reading', 'revealing', 'finding'). Subject-verb agreement errors ('It explore', 'Gatsby are', 'who throw'). Verb form errors ('is drive', 'would recommending'). >Band 4: Basic meaning clear. Not Band 6: Errors are systematic.",
        "vocabulary": 7,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a book you read recently.\n\nTranscript: I recently reading a novel called 'The Great Gatsby', which is a classic of American literature. It explore themes of decadence, idealism, and social upheaval. I was fascinated by the vivid descriptions of the Jazz Age. The protagonist, Jay Gatsby, are a mysterious millionaire who throw lavish parties. However, he is drive by an obsession with the past. The book revealing the emptiness of the American Dream. Although the language were sometimes difficult, I finding the plot compelling. It is a tragic story that resonate with many readers. I would recommending it to anyone interested in history.\n\nWord Count: 97 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses sophisticated vocabulary: 'decadence', 'idealism', 'upheaval', 'protagonist'. Precise meaning.\n\n>Band 6: Advanced vocabulary.\n\nNot Band 8: Lacks native-like flow.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Frequent errors in verb forms and agreement. 'I recently reading', 'It explore' are incorrect.\n\n>Band 4: Basic sentences are recognizable.\n\nNot Band 6: Errors are frequent and noticeable.\n\n**Micro flaws identified:**\n- 'I recently reading' should be 'I recently read'\n- 'It explore' should be 'It explores'\n- 'Gatsby, are' should be 'Gatsby, is'\n- 'who throw' should be 'who throws'\n- 'he is drive' should be 'he is driven'\n- 'book revealing' should be 'book reveals'\n- 'language were' should be 'language was'\n- 'I finding' should be 'I found'\n- 'story that resonate' should be 'story that resonates'\n- 'would recommending' should be 'would recommend'"
    },
    # 572. V7/G5 - Event (Festival)
    {
        "sample_id": "syn_p2_v7_g5_0572",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a festival you want to attend.",
        "transcript_cleaned": "I dreaming of attending the Rio Carnival in Brazil, which is a world-famous spectacle. It is known for its exuberant atmosphere and flamboyant costumes. I want to witnessing the Samba Parade, where dancers performs intricate routines. The rhythmic beats of the drums is intoxicating. I imagine the streets filled with vibrant colors and energetic crowds. It would be a once-in-a-lifetime opportunity to experience such cultural richness. However, the travel costs is very high. I hoping to save enough money one day. Being part of this massive celebration appeal to me greatly.",
        "word_count": 93,
        "response_type": "long_turn",
        "micro_flaws": ["tense: 'I dreaming' should be 'dream'", "grammar: 'want to witnessing' should be 'want to witness'", "agreement: 'dancers performs' should be 'perform'", "agreement: 'beats... is' should be 'are'", "agreement: 'costs is' should be 'are'", "tense: 'I hoping' should be 'hope'", "agreement: 'celebration appeal' should be 'appeals'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR7] Vocabulary: 'dreaming', 'spectacle', 'exuberant', 'flamboyant costumes', 'witnessing', 'intricate routines', 'rhythmic beats', 'intoxicating', 'vibrant', 'energetic', 'once-in-a-lifetime', 'cultural richness', 'massive celebration', 'appeal'. Very sophisticated. >Band 6: Precise vocabulary. Not Band 8: Some phrases are common.",
        "grammar_reason": "[GRA5] Frequent grammatical errors. Continuous tense used incorrectly ('I dreaming', 'I hoping'). Verb form error ('want to witnessing'). Subject-verb agreement errors ('dancers performs', 'beats is', 'costs is', 'celebration appeal'). >Band 4: Basic meaning clear. Not Band 6: Errors are systematic.",
        "vocabulary": 7,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a festival you want to attend.\n\nTranscript: I dreaming of attending the Rio Carnival in Brazil, which is a world-famous spectacle. It is known for its exuberant atmosphere and flamboyant costumes. I want to witnessing the Samba Parade, where dancers performs intricate routines. The rhythmic beats of the drums is intoxicating. I imagine the streets filled with vibrant colors and energetic crowds. It would be a once-in-a-lifetime opportunity to experience such cultural richness. However, the travel costs is very high. I hoping to save enough money one day. Being part of this massive celebration appeal to me greatly.\n\nWord Count: 93 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses descriptive words: 'exuberant', 'flamboyant', 'intoxicating'. Clear meaning.\n\n>Band 6: Advanced vocabulary.\n\nNot Band 8: Errors affect accuracy.\n\n**Idiom present:** Yes ('once-in-a-lifetime')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Frequent errors in verb forms and agreement. 'I dreaming', 'dancers performs' are incorrect.\n\n>Band 4: Basic sentences are recognizable.\n\nNot Band 6: Errors are frequent and noticeable.\n\n**Micro flaws identified:**\n- 'I dreaming' should be 'I dream'\n- 'want to witnessing' should be 'want to witness'\n- 'dancers performs' should be 'dancers perform'\n- 'beats... is' should be 'beats... are'\n- 'costs is' should be 'costs are'\n- 'I hoping' should be 'I hope'\n- 'celebration appeal' should be 'celebration appeals'"
    },
    # 573. V7/G5 - Person (Family)
    {
        "sample_id": "syn_p2_v7_g5_0573",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a family member you are close to.",
        "transcript_cleaned": "I am very close to my aunt, who act as a mentor to me. She is a compassionate woman with a generous spirit. We sharing a mutual love for literature and art. She often giving me insightful advice when I face dilemmas. Her resilience in the face of adversity inspire me deeply. Despite her busy schedule, she always making time for family. We possess a similar sense of humor, which keeping our conversations lively. I cherish our bond because it is based on trust and understanding. She is a pillar of strength in my life.",
        "word_count": 98,
        "response_type": "long_turn",
        "micro_flaws": ["agreement: 'who act' should be 'acts'", "tense: 'We sharing' should be 'share'", "tense: 'She often giving' should be 'gives'", "agreement: 'adversity inspire' should be 'inspires'", "tense: 'she always making' should be 'makes'", "agreement: 'which keeping' should be 'keeps'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR7] Vocabulary: 'mentor', 'compassionate', 'generous spirit', 'mutual love', 'literature', 'insightful advice', 'dilemmas', 'resilience', 'adversity', 'inspire', 'sense of humor', 'lively', 'cherish', 'bond', 'trust', 'pillar of strength'. Very sophisticated. >Band 6: Precise vocabulary. Not Band 8: Some phrases are common.",
        "grammar_reason": "[GRA5] Frequent grammatical errors. Incorrect use of continuous tense ('We sharing', 'giving', 'making', 'keeping'). Subject-verb agreement errors ('who act', 'adversity inspire'). >Band 4: Basic meaning clear. Not Band 6: Errors are systematic.",
        "vocabulary": 7,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a family member you are close to.\n\nTranscript: I am very close to my aunt, who act as a mentor to me. She is a compassionate woman with a generous spirit. We sharing a mutual love for literature and art. She often giving me insightful advice when I face dilemmas. Her resilience in the face of adversity inspire me deeply. Despite her busy schedule, she always making time for family. We possess a similar sense of humor, which keeping our conversations lively. I cherish our bond because it is based on trust and understanding. She is a pillar of strength in my life.\n\nWord Count: 98 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses sophisticated vocabulary: 'compassionate', 'resilience', 'adversity'. Precise.\n\n>Band 6: Advanced vocabulary.\n\nNot Band 8: Lacks native-like flow.\n\n**Idiom present:** Yes ('pillar of strength')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Frequent errors in verb forms and agreement. 'We sharing', 'who act' are incorrect.\n\n>Band 4: Basic sentences are recognizable.\n\nNot Band 6: Errors are frequent and noticeable.\n\n**Micro flaws identified:**\n- 'who act' should be 'who acts'\n- 'We sharing' should be 'We share'\n- 'She often giving' should be 'She often gives'\n- 'adversity inspire' should be 'adversity inspires'\n- 'she always making' should be 'she always makes'\n- 'which keeping' should be 'which keeps'"
    },
    # 574. V7/G5 - Object (Art)
    {
        "sample_id": "syn_p2_v7_g5_0574",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a piece of art you dislike.",
        "transcript_cleaned": "I dislike a modern sculpture in the city center that looking very abstract. It is a twisted metal structure that seem meaningless to me. I finding it aesthetically unappealing and confusing. It clash with the historic architecture surrounding it. Many people criticizing it for being a waste of money. I prefer art that depict realistic scenes or emotions. This sculpture evoke no feelings in me other than confusion. It stand as a symbol of pretentiousness. I wish the city council replacing it with something more beautiful.",
        "word_count": 87,
        "response_type": "long_turn",
        "micro_flaws": ["tense: 'that looking' should be 'looks'", "agreement: 'structure that seem' should be 'seems'", "tense: 'I finding' should be 'find'", "agreement: 'It clash' should be 'clashes'", "tense: 'people criticizing' should be 'criticize'", "agreement: 'art that depict' should be 'depicts'", "agreement: 'sculpture evoke' should be 'evokes'", "agreement: 'It stand' should be 'stands'", "grammar: 'council replacing' should be 'would replace' or 'replaced'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR7] Vocabulary: 'modern sculpture', 'abstract', 'twisted', 'structure', 'meaningless', 'aesthetically unappealing', 'confusing', 'clash', 'historic architecture', 'criticizing', 'depict', 'realistic scenes', 'evoke', 'pretentiousness', 'council'. Very sophisticated. >Band 6: Precise vocabulary. Not Band 8: Errors in usage.",
        "grammar_reason": "[GRA5] Frequent grammatical errors. Continuous tense used incorrectly ('looking', 'finding', 'criticizing'). Subject-verb agreement errors ('structure seem', 'It clash', 'art depict', 'sculpture evoke', 'It stand'). >Band 4: Basic meaning clear. Not Band 6: Errors are systematic.",
        "vocabulary": 7,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a piece of art you dislike.\n\nTranscript: I dislike a modern sculpture in the city center that looking very abstract. It is a twisted metal structure that seem meaningless to me. I finding it aesthetically unappealing and confusing. It clash with the historic architecture surrounding it. Many people criticizing it for being a waste of money. I prefer art that depict realistic scenes or emotions. This sculpture evoke no feelings in me other than confusion. It stand as a symbol of pretentiousness. I wish the city council replacing it with something more beautiful.\n\nWord Count: 87 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses descriptive words: 'aesthetically', 'pretentiousness', 'clash'. Clear meaning.\n\n>Band 6: Advanced vocabulary.\n\nNot Band 8: Errors affect accuracy.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Frequent errors in verb forms and agreement. 'that looking', 'It clash' are incorrect.\n\n>Band 4: Basic sentences are recognizable.\n\nNot Band 6: Errors are frequent and noticeable.\n\n**Micro flaws identified:**\n- 'that looking' should be 'that looks'\n- 'structure that seem' should be 'structure that seems'\n- 'I finding' should be 'I find'\n- 'It clash' should be 'It clashes'\n- 'people criticizing' should be 'people criticize'\n- 'art that depict' should be 'art that depicts'\n- 'sculpture evoke' should be 'sculpture evokes'\n- 'It stand' should be 'It stands'\n- 'council replacing' should be 'council would replace'"
    },
    # 575. V7/G5 - Activity (Hobby)
    {
        "sample_id": "syn_p2_v7_g5_0575",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a hobby you gave up.",
        "transcript_cleaned": "I used to practicing karate, which is a martial art. I joined a club when I was a teenager to improve my fitness. It requiring a lot of discipline and physical stamina. Initially, I enjoying learning the self-defense techniques. However, the training sessions became too rigorous for me. I struggling to keep up with the other students. Also, I injuring my knee during a match. The pain were unbearable, so I had to quit. Although I missing the camaraderie, I do not regret stopping. It taught me the importance of knowing my limits.",
        "word_count": 96,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'used to practicing' should be 'used to practice'", "tense: 'It requiring' should be 'It required'", "tense: 'I enjoying' should be 'I enjoyed'", "tense: 'I struggling' should be 'I struggled'", "tense: 'I injuring' should be 'I injured'", "agreement: 'pain were' should be 'was'", "tense: 'I missing' should be 'I miss'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR7] Vocabulary: 'martial art', 'improve fitness', 'discipline', 'physical stamina', 'self-defense techniques', 'rigorous', 'struggling', 'injuring', 'unbearable', 'camaraderie', 'regret', 'limits'. Very sophisticated. >Band 6: Precise vocabulary. Not Band 8: Errors in word form.",
        "grammar_reason": "[GRA5] Frequent grammatical errors. Incorrect use of 'used to' ('used to practicing'). Tense errors ('requiring', 'enjoying', 'struggling', 'injuring', 'missing'). Agreement error ('pain were'). >Band 4: Basic meaning clear. Not Band 6: Errors are systematic.",
        "vocabulary": 7,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a hobby you gave up.\n\nTranscript: I used to practicing karate, which is a martial art. I joined a club when I was a teenager to improve my fitness. It requiring a lot of discipline and physical stamina. Initially, I enjoying learning the self-defense techniques. However, the training sessions became too rigorous for me. I struggling to keep up with the other students. Also, I injuring my knee during a match. The pain were unbearable, so I had to quit. Although I missing the camaraderie, I do not regret stopping. It taught me the importance of knowing my limits.\n\nWord Count: 96 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses topic words: 'stamina', 'rigorous', 'camaraderie'. Meaning is clear.\n\n>Band 6: Advanced vocabulary.\n\nNot Band 8: Errors affect accuracy.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Frequent errors in verb forms and tense. 'Used to practicing', 'It requiring' are incorrect.\n\n>Band 4: Basic sentences are recognizable.\n\nNot Band 6: Errors are frequent and noticeable.\n\n**Micro flaws identified:**\n- 'used to practicing' should be 'used to practice'\n- 'It requiring' should be 'It required'\n- 'I enjoying' should be 'I enjoyed'\n- 'I struggling' should be 'I struggled'\n- 'I injuring' should be 'I injured'\n- 'pain were' should be 'pain was'\n- 'I missing' should be 'I miss'"
    },
    # 576. V6/G8 - Place (Museum)
    {
        "sample_id": "syn_p2_v6_g8_0576",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a museum you want to visit.",
        "transcript_cleaned": "I would really like to visit the Science Museum in London. I have heard that it is a very interesting place with many exhibits. I am curious about space travel, and they have a section dedicated to rockets. It would be amazing to see real spacecraft. I also want to learn more about the history of medicine. If I go there, I will spend the whole day exploring. I think museums are great for learning new things in a fun way. It is a popular attraction that welcomes millions of visitors each year.",
        "word_count": 94,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR6] Vocabulary: 'Science Museum', 'exhibits', 'curious', 'space travel', 'section', 'dedicated', 'rockets', 'spacecraft', 'medicine', 'exploring', 'popular attraction', 'welcomes', 'visitors'. Adequate range. >Band 5: Uses specific words ('spacecraft', 'exhibits'). Not Band 7: Lacks sophistication.",
        "grammar_reason": "[GRA8] Wide range of structures used accurately. 'I have heard that...' (Noun clause). 'With many exhibits' (Prepositional phrase). 'Section dedicated to rockets' (Participle phrase). 'If I go there...' (First conditional). 'That welcomes millions...' (Relative clause). Error-free. >Band 7: More variety.",
        "vocabulary": 6,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a museum you want to visit.\n\nTranscript: I would really like to visit the Science Museum in London. I have heard that it is a very interesting place with many exhibits. I am curious about space travel, and they have a section dedicated to rockets. It would be amazing to see real spacecraft. I also want to learn more about the history of medicine. If I go there, I will spend the whole day exploring. I think museums are great for learning new things in a fun way. It is a popular attraction that welcomes millions of visitors each year.\n\nWord Count: 94 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses relevant vocabulary: 'exhibits', 'spacecraft', 'attraction'. Clear description.\n\n>Band 5: Good range.\n\nNot Band 7: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Uses complex structures accurately (noun clauses, conditionals). Sentences are error-free.\n\n>Band 7: High accuracy.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    },
    # 577. V6/G8 - Event (Sports)
    {
        "sample_id": "syn_p2_v6_g8_0577",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a sports competition you watched.",
        "transcript_cleaned": "I watched the final of the local basketball tournament last week. It was a thrilling game between two rival schools. The players were very skilled and played with great energy. I was cheering for my former school's team. The score was close throughout the match, which made it very exciting. In the last minute, one player scored a three-point shot to win the game. The crowd went wild, screaming and clapping. It was a memorable event that brought the community together. I felt proud of the team's achievement.",
        "word_count": 89,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR6] Vocabulary: 'basketball tournament', 'thrilling', 'rival schools', 'skilled', 'energy', 'cheering', 'score', 'close', 'three-point shot', 'crowd', 'wild', 'screaming', 'clapping', 'memorable', 'community', 'achievement'. Adequate range. >Band 5: Uses specific words ('rival', 'tournament'). Not Band 7: Lacks depth.",
        "grammar_reason": "[GRA8] Wide range of structures used accurately. 'Between two rival schools' (Prepositional phrase). 'Cheering for my former school's team' (Participle phrase). 'Which made it very exciting' (Relative clause). 'To win the game' (Infinitive of purpose). Error-free. >Band 7: More variety.",
        "vocabulary": 6,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a sports competition you watched.\n\nTranscript: I watched the final of the local basketball tournament last week. It was a thrilling game between two rival schools. The players were very skilled and played with great energy. I was cheering for my former school's team. The score was close throughout the match, which made it very exciting. In the last minute, one player scored a three-point shot to win the game. The crowd went wild, screaming and clapping. It was a memorable event that brought the community together. I felt proud of the team's achievement.\n\nWord Count: 89 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses topic words: 'tournament', 'rival', 'achievement'. Meaning is clear.\n\n>Band 5: Good range.\n\nNot Band 7: Lacks sophistication.\n\n**Idiom present:** Yes ('went wild')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Uses complex structures accurately. Relative clauses and infinitives used correctly. Good control.\n\n>Band 7: High accuracy.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    },
    # 578. V6/G8 - Activity (Skill)
    {
        "sample_id": "syn_p2_v6_g8_0578",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a skill you are good at.",
        "transcript_cleaned": "I am good at drawing, which is a skill I have practiced since childhood. I enjoy sketching portraits of my friends and family. I use charcoal and pencils to create different effects. It requires patience and a steady hand. I learned by watching tutorials online and practicing every day. Drawing helps me relax and express my feelings. I have entered several art competitions and even won a prize once. Although I am not a professional, I am proud of my artistic ability. It is a hobby that brings me great joy.",
        "word_count": 91,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR6] Vocabulary: 'drawing', 'skill', 'practiced', 'sketching portraits', 'charcoal', 'pencils', 'effects', 'patience', 'steady hand', 'tutorials', 'relax', 'express', 'competitions', 'prize', 'professional', 'artistic ability', 'joy'. Adequate range. >Band 5: Uses specific words ('charcoal', 'portraits'). Not Band 7: Lacks depth.",
        "grammar_reason": "[GRA8] Wide range of structures used accurately. 'Which is a skill I have practiced' (Relative clause). 'To create different effects' (Infinitive of purpose). 'Learned by watching...' (Preposition + Gerund). 'Although I am not...' (Concessive clause). Error-free. >Band 7: More variety.",
        "vocabulary": 6,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a skill you are good at.\n\nTranscript: I am good at drawing, which is a skill I have practiced since childhood. I enjoy sketching portraits of my friends and family. I use charcoal and pencils to create different effects. It requires patience and a steady hand. I learned by watching tutorials online and practicing every day. Drawing helps me relax and express my feelings. I have entered several art competitions and even won a prize once. Although I am not a professional, I am proud of my artistic ability. It is a hobby that brings me great joy.\n\nWord Count: 91 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses relevant vocabulary: 'sketching', 'charcoal', 'competitions'. Clear description.\n\n>Band 5: Good range.\n\nNot Band 7: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Uses complex structures accurately. Includes relative clauses, infinitives, and concessive clauses. Good control.\n\n>Band 7: High accuracy.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    },
    # 579. V6/G8 - Person (Child)
    {
        "sample_id": "syn_p2_v6_g8_0579",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a child you enjoy spending time with.",
        "transcript_cleaned": "I enjoy spending time with my younger cousin, Leo. He is a very energetic and funny five-year-old. I often look after him when his parents are busy. We like playing hide and seek in the garden. He has a vivid imagination and loves telling stories. Sometimes we draw pictures together or build things with blocks. He asks many questions because he is curious about everything. I find his laughter contagious. Spending time with him reminds me of my own childhood. He is a delightful boy who brings happiness to our family.",
        "word_count": 93,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR6] Vocabulary: 'younger cousin', 'energetic', 'funny', 'look after', 'hide and seek', 'vivid imagination', 'stories', 'draw pictures', 'blocks', 'curious', 'laughter', 'contagious', 'childhood', 'delightful', 'happiness'. Adequate range. >Band 5: Uses specific words ('imagination', 'contagious'). Not Band 7: Lacks sophistication.",
        "grammar_reason": "[GRA8] Wide range of structures used accurately. 'When his parents are busy' (Time clause). 'Because he is curious...' (Reason clause). 'Reminds me of...' (Verb pattern). 'Who brings happiness...' (Relative clause). Error-free. >Band 7: More variety.",
        "vocabulary": 6,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a child you enjoy spending time with.\n\nTranscript: I enjoy spending time with my younger cousin, Leo. He is a very energetic and funny five-year-old. I often look after him when his parents are busy. We like playing hide and seek in the garden. He has a vivid imagination and loves telling stories. Sometimes we draw pictures together or build things with blocks. He asks many questions because he is curious about everything. I find his laughter contagious. Spending time with him reminds me of my own childhood. He is a delightful boy who brings happiness to our family.\n\nWord Count: 93 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses descriptive words: 'energetic', 'vivid', 'contagious'. Clear meaning.\n\n>Band 5: Good range.\n\nNot Band 7: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Uses complex structures accurately. Includes time clauses, reason clauses, and relative clauses.\n\n>Band 7: High accuracy.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    },
    # 580. V6/G8 - Object (Gift)
    {
        "sample_id": "syn_p2_v6_g8_0580",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a gift you made for someone.",
        "transcript_cleaned": "I made a photo album for my best friend's birthday. I wanted to give her something personal and meaningful. I printed out photos from our trips and parties together. I arranged them in a nice book and wrote captions for each one. I also decorated the pages with stickers and drawings. It took me a week to finish it, but I enjoyed the process. When she opened the gift, she was very emotional. She said it was the best present she had ever received. It made me happy to see her appreciation.",
        "word_count": 94,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR6] Vocabulary: 'photo album', 'best friend', 'personal', 'meaningful', 'printed out', 'trips', 'parties', 'arranged', 'captions', 'decorated', 'stickers', 'process', 'emotional', 'present', 'received', 'appreciation'. Adequate range. >Band 5: Uses specific words ('captions', 'meaningful'). Not Band 7: Lacks depth.",
        "grammar_reason": "[GRA8] Wide range of structures used accurately. 'Wanted to give her...' (Verb pattern). 'Wrote captions for each one' (Prepositional phrase). 'It took me a week to finish' (Infinitive phrase). 'When she opened the gift' (Time clause). Error-free. >Band 7: More variety.",
        "vocabulary": 6,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a gift you made for someone.\n\nTranscript: I made a photo album for my best friend's birthday. I wanted to give her something personal and meaningful. I printed out photos from our trips and parties together. I arranged them in a nice book and wrote captions for each one. I also decorated the pages with stickers and drawings. It took me a week to finish it, but I enjoyed the process. When she opened the gift, she was very emotional. She said it was the best present she had ever received. It made me happy to see her appreciation.\n\nWord Count: 94 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses relevant vocabulary: 'meaningful', 'captions', 'appreciation'. Clear description.\n\n>Band 5: Good range.\n\nNot Band 7: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Uses complex structures accurately. Includes infinitives and time clauses. Good control.\n\n>Band 7: High accuracy.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    }
]

with open(OUTPUT_FILE, 'a', encoding='utf-8') as f:
    for sample in samples:
        f.write(json.dumps(sample) + '\n')
