import json

OUTPUT_FILE = "ielts-data/phase3/v76_review_output/synthetic_batches/batch_p2_14.jsonl"

samples = [
    # 691. V5/G5 - Book (Recently Read)
    {
        "sample_id": "syn_p2_v5_g5_0691",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a book you read recently.",
        "transcript_cleaned": "I recently read a book called 'The Old Man and the Sea'. It is a short novel about an old fisherman. He tries to catch a big fish in the sea. The story is very simple but meaningful. I liked the character of the old man because he is brave. He faces many problems but does not give up. I read this book in two days because it was interesting. The language was easy to understand. I think it is a classic book. It taught me about patience and strength.",
        "word_count": 92,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR5] Vocabulary: 'novel', 'fisherman', 'catch', 'sea', 'meaningful', 'character', 'brave', 'problems', 'give up', 'interesting', 'easy', 'classic', 'patience', 'strength'. Functional vocabulary relevant to the topic. >Band 4: Uses specific words ('novel', 'patience'). Not Band 6: Simple vocabulary.",
        "grammar_reason": "[GRA5] Basic sentence forms are accurate. Uses 'because' and 'but' clauses correctly. Past tense used correctly ('read', 'liked', 'was'). >Band 4: Accuracy is good. Not Band 6: Limited complexity.",
        "vocabulary": 5,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a book you read recently.\n\nTranscript: I recently read a book called 'The Old Man and the Sea'. It is a short novel about an old fisherman. He tries to catch a big fish in the sea. The story is very simple but meaningful. I liked the character of the old man because he is brave. He faces many problems but does not give up. I read this book in two days because it was interesting. The language was easy to understand. I think it is a classic book. It taught me about patience and strength.\n\nWord Count: 92 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses topic words: 'novel', 'brave', 'patience'. Meaning is clear.\n\n>Band 4: Adequate vocabulary.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Uses basic sentences accurately. Connectors like 'because' and 'but' are used correctly.\n\n>Band 4: Frequent error-free sentences.\n\nNot Band 6: Limited range of structures.\n\n**Micro flaws identified:**\n- None."
    },
    # 692. V5/G5 - Place (Town)
    {
        "sample_id": "syn_p2_v5_g5_0692",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a town you would like to live in.",
        "transcript_cleaned": "I would like to live in a small town near the mountains. I prefer quiet places over busy cities. I want a house with a view of the forest. The air would be fresh and clean. I imagine walking in the nature every morning. People in small towns are usually friendly. I could make friends easily there. I would grow my own vegetables in a garden. Although there might be fewer shops, I do not mind. Living close to nature is my dream. It would be a peaceful life.",
        "word_count": 92,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR5] Vocabulary: 'small town', 'mountains', 'quiet', 'busy cities', 'view', 'forest', 'fresh', 'clean', 'nature', 'friendly', 'vegetables', 'garden', 'shops', 'dream', 'peaceful life'. Functional vocabulary relevant to the topic. >Band 4: Uses specific words ('view', 'peaceful'). Not Band 6: Simple vocabulary.",
        "grammar_reason": "[GRA5] Basic sentence forms are accurate. Uses modal verbs ('would', 'could') correctly to express hypothetical situations. >Band 4: Accuracy is good. Not Band 6: Limited complexity.",
        "vocabulary": 5,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a town you would like to live in.\n\nTranscript: I would like to live in a small town near the mountains. I prefer quiet places over busy cities. I want a house with a view of the forest. The air would be fresh and clean. I imagine walking in the nature every morning. People in small towns are usually friendly. I could make friends easily there. I would grow my own vegetables in a garden. Although there might be fewer shops, I do not mind. Living close to nature is my dream. It would be a peaceful life.\n\nWord Count: 92 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses topic words: 'forest', 'fresh', 'peaceful'. Meaning is clear.\n\n>Band 4: Adequate vocabulary.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Uses basic sentences accurately. Modal verbs used correctly for hypothetical situations.\n\n>Band 4: Frequent error-free sentences.\n\nNot Band 6: Limited range of structures.\n\n**Micro flaws identified:**\n- None."
    },
    # 693. V5/G5 - Event (Festival)
    {
        "sample_id": "syn_p2_v5_g5_0693",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a festival you want to go to.",
        "transcript_cleaned": "I want to go to the Lantern Festival in Thailand. I saw pictures of it on the internet. Thousands of lanterns float into the sky at night. It looks very beautiful and magical. I want to make a wish and release a lantern myself. I think the atmosphere would be amazing. There would be many people celebrating together. I also want to try Thai street food. I heard it is spicy and tasty. Going to this festival is on my bucket list. I hope to visit next year.",
        "word_count": 91,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR5] Vocabulary: 'Lantern Festival', 'internet', 'float', 'sky', 'beautiful', 'magical', 'wish', 'release', 'atmosphere', 'celebrating', 'street food', 'spicy', 'tasty', 'bucket list', 'visit'. Functional vocabulary relevant to the topic. >Band 4: Uses specific words ('magical', 'release'). Not Band 6: Simple vocabulary.",
        "grammar_reason": "[GRA5] Basic sentence forms are accurate. Uses modal verbs ('would') and simple present/future tense correctly. >Band 4: Accuracy is good. Not Band 6: Limited complexity.",
        "vocabulary": 5,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a festival you want to go to.\n\nTranscript: I want to go to the Lantern Festival in Thailand. I saw pictures of it on the internet. Thousands of lanterns float into the sky at night. It looks very beautiful and magical. I want to make a wish and release a lantern myself. I think the atmosphere would be amazing. There would be many people celebrating together. I also want to try Thai street food. I heard it is spicy and tasty. Going to this festival is on my bucket list. I hope to visit next year.\n\nWord Count: 91 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses topic words: 'magical', 'atmosphere', 'celebrating'. Meaning is clear.\n\n>Band 4: Adequate vocabulary.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** Yes ('bucket list')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Uses basic sentences accurately. Modals and tenses used correctly.\n\n>Band 4: Frequent error-free sentences.\n\nNot Band 6: Limited range of structures.\n\n**Micro flaws identified:**\n- None."
    },
    # 694. V5/G5 - Person (Friend)
    {
        "sample_id": "syn_p2_v5_g5_0694",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a friend you admire.",
        "transcript_cleaned": "I admire my friend, Lisa, because she is very hardworking. She studies at university and also has a part-time job. She wants to be a doctor in the future. I see her studying late at night in the library. She never complains about being tired. She is also very kind to everyone. She helps me when I have problems with my schoolwork. I think she is a strong person. Her determination inspires me to do better. I am lucky to have her as my friend.",
        "word_count": 89,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR5] Vocabulary: 'admire', 'hardworking', 'university', 'part-time job', 'doctor', 'library', 'complains', 'tired', 'kind', 'problems', 'schoolwork', 'strong', 'determination', 'inspires', 'lucky'. Functional vocabulary relevant to the topic. >Band 4: Uses specific words ('determination', 'inspires'). Not Band 6: Simple vocabulary.",
        "grammar_reason": "[GRA5] Basic sentence forms are accurate. Uses 'because' and 'when' clauses correctly. Present tense used correctly ('is', 'studies', 'wants'). >Band 4: Accuracy is good. Not Band 6: Limited complexity.",
        "vocabulary": 5,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a friend you admire.\n\nTranscript: I admire my friend, Lisa, because she is very hardworking. She studies at university and also has a part-time job. She wants to be a doctor in the future. I see her studying late at night in the library. She never complains about being tired. She is also very kind to everyone. She helps me when I have problems with my schoolwork. I think she is a strong person. Her determination inspires me to do better. I am lucky to have her as my friend.\n\nWord Count: 89 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses topic words: 'hardworking', 'determination', 'inspires'. Meaning is clear.\n\n>Band 4: Adequate vocabulary.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Uses basic sentences accurately. Connectors and present tense used correctly.\n\n>Band 4: Frequent error-free sentences.\n\nNot Band 6: Limited range of structures.\n\n**Micro flaws identified:**\n- None."
    },
    # 695. V5/G5 - Activity (Hobby)
    {
        "sample_id": "syn_p2_v5_g5_0695",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a new hobby you want to start.",
        "transcript_cleaned": "I want to start learning how to paint with watercolors. I have seen many beautiful paintings online, and I like the colors. It looks like a relaxing hobby. I bought some paints and brushes yesterday. I plan to paint flowers and landscapes. I think it will be difficult at first, but I will practice. I want to express my feelings through art. Painting can help me reduce stress. I hope to create a nice picture for my room. It is something creative to do in my free time.",
        "word_count": 91,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR5] Vocabulary: 'watercolors', 'paintings', 'relaxing', 'paints', 'brushes', 'flowers', 'landscapes', 'difficult', 'practice', 'express feelings', 'art', 'reduce stress', 'create', 'creative', 'free time'. Functional vocabulary relevant to the topic. >Band 4: Uses specific words ('landscapes', 'express'). Not Band 6: Simple vocabulary.",
        "grammar_reason": "[GRA5] Basic sentence forms are accurate. Uses 'but' and infinitive 'to' correctly. Future tense used correctly ('will be', 'will practice'). >Band 4: Accuracy is good. Not Band 6: Limited complexity.",
        "vocabulary": 5,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a new hobby you want to start.\n\nTranscript: I want to start learning how to paint with watercolors. I have seen many beautiful paintings online, and I like the colors. It looks like a relaxing hobby. I bought some paints and brushes yesterday. I plan to paint flowers and landscapes. I think it will be difficult at first, but I will practice. I want to express my feelings through art. Painting can help me reduce stress. I hope to create a nice picture for my room. It is something creative to do in my free time.\n\nWord Count: 91 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses topic words: 'watercolors', 'landscapes', 'reduce stress'. Meaning is clear.\n\n>Band 4: Adequate vocabulary.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Uses basic sentences accurately. Future tense and infinitives used correctly.\n\n>Band 4: Frequent error-free sentences.\n\nNot Band 6: Limited range of structures.\n\n**Micro flaws identified:**\n- None."
    },
    # 696. V6/G6 - Object (Gift)
    {
        "sample_id": "syn_p2_v6_g6_0696",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a gift you received recently.",
        "transcript_cleaned": "I received a pair of wireless headphones for my birthday last week. My brother gave them to me because he knows I love music. They are black and have a sleek design. The sound quality is excellent, with strong bass. I connect them to my phone via Bluetooth. I use them when I travel to school on the bus. They cancel out the noise, which is great. I was very grateful for this gift. It is something I use every day. I think it was a thoughtful present.",
        "word_count": 92,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR6] Vocabulary: 'wireless headphones', 'sleek design', 'sound quality', 'excellent', 'bass', 'connect', 'Bluetooth', 'cancel out', 'noise', 'grateful', 'thoughtful present'. Adequate range. >Band 5: Uses specific words ('wireless', 'cancel out'). Not Band 7: Lacks depth.",
        "grammar_reason": "[GRA6] Uses a mix of simple and complex structures accurately. 'Because he knows...' (Reason clause). 'Which is great' (Relative clause). 'When I travel...' (Time clause). Generally error-free. >Band 5: Uses complex structures accurately. Not Band 7: Limited range.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a gift you received recently.\n\nTranscript: I received a pair of wireless headphones for my birthday last week. My brother gave them to me because he knows I love music. They are black and have a sleek design. The sound quality is excellent, with strong bass. I connect them to my phone via Bluetooth. I use them when I travel to school on the bus. They cancel out the noise, which is great. I was very grateful for this gift. It is something I use every day. I think it was a thoughtful present.\n\nWord Count: 92 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses relevant vocabulary: 'wireless', 'sleek', 'thoughtful'. Clear description.\n\n>Band 5: Good range.\n\nNot Band 7: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Uses complex structures accurately. Includes reason clauses and relative clauses. Good control.\n\n>Band 5: Frequent error-free sentences.\n\nNot Band 7: Range is limited.\n\n**Micro flaws identified:**\n- None."
    },
    # 697. V6/G6 - Place (Park)
    {
        "sample_id": "syn_p2_v6_g6_0697",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a park you like.",
        "transcript_cleaned": "I like the botanical garden in my city, which is a very peaceful place. It has a wide variety of plants and flowers from different countries. I go there to escape the busy city life. There is a large pond with colorful fish and ducks. I enjoy walking on the paths and breathing the fresh air. The garden is well-maintained and clean. In spring, the cherry blossoms are beautiful. I often see people painting or reading there. It is a perfect spot for relaxation. I feel calm whenever I visit.",
        "word_count": 94,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR6] Vocabulary: 'botanical garden', 'peaceful', 'variety', 'plants', 'escape', 'busy city life', 'pond', 'colorful', 'paths', 'fresh air', 'well-maintained', 'cherry blossoms', 'perfect spot', 'relaxation', 'calm'. Adequate range. >Band 5: Uses specific words ('botanical', 'well-maintained'). Not Band 7: Lacks sophistication.",
        "grammar_reason": "[GRA6] Uses a mix of simple and complex structures accurately. 'Which is a very peaceful place' (Relative clause). 'To escape the busy city life' (Infinitive of purpose). 'Whenever I visit' (Time clause). Generally error-free. >Band 5: Uses complex structures accurately. Not Band 7: Limited range.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a park you like.\n\nTranscript: I like the botanical garden in my city, which is a very peaceful place. It has a wide variety of plants and flowers from different countries. I go there to escape the busy city life. There is a large pond with colorful fish and ducks. I enjoy walking on the paths and breathing the fresh air. The garden is well-maintained and clean. In spring, the cherry blossoms are beautiful. I often see people painting or reading there. It is a perfect spot for relaxation. I feel calm whenever I visit.\n\nWord Count: 94 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses descriptive words: 'botanical', 'well-maintained', 'relaxation'. Clear meaning.\n\n>Band 5: Good range.\n\nNot Band 7: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Uses complex structures accurately. Includes relative clauses and infinitives. Good control.\n\n>Band 5: Frequent error-free sentences.\n\nNot Band 7: Range is limited.\n\n**Micro flaws identified:**\n- None."
    },
    # 698. V6/G6 - Activity (Daily)
    {
        "sample_id": "syn_p2_v6_g6_0698",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe your evening routine.",
        "transcript_cleaned": "I usually get home from university at 5 pm. The first thing I do is change into comfortable clothes. Then, I prepare a simple dinner, like pasta or salad. I like cooking while listening to podcasts. After eating, I study for about two hours. I review my notes and complete assignments. Around 9 pm, I relax by watching a movie or calling a friend. I try to avoid using my phone before sleep. I go to bed at 11 pm to ensure I get enough rest. This routine keeps me organized.",
        "word_count": 96,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR6] Vocabulary: 'university', 'comfortable clothes', 'prepare', 'simple dinner', 'podcasts', 'study', 'review notes', 'assignments', 'relax', 'avoid', 'ensure', 'rest', 'organized'. Adequate range. >Band 5: Uses specific words ('podcasts', 'assignments'). Not Band 7: Vocabulary is standard.",
        "grammar_reason": "[GRA6] Uses a mix of simple and complex structures accurately. 'The first thing I do is...' (Pseudo-cleft). 'While listening to podcasts' (Time clause). 'To ensure I get enough rest' (Infinitive of purpose). Generally error-free. >Band 5: Uses complex structures accurately. Not Band 7: Limited range.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe your evening routine.\n\nTranscript: I usually get home from university at 5 pm. The first thing I do is change into comfortable clothes. Then, I prepare a simple dinner, like pasta or salad. I like cooking while listening to podcasts. After eating, I study for about two hours. I review my notes and complete assignments. Around 9 pm, I relax by watching a movie or calling a friend. I try to avoid using my phone before sleep. I go to bed at 11 pm to ensure I get enough rest. This routine keeps me organized.\n\nWord Count: 96 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses relevant vocabulary: 'comfortable', 'assignments', 'organized'. Clear description.\n\n>Band 5: Good range.\n\nNot Band 7: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Uses complex structures accurately. Includes pseudo-clefts and time clauses. Good control.\n\n>Band 5: Frequent error-free sentences.\n\nNot Band 7: Range is limited.\n\n**Micro flaws identified:**\n- None."
    },
    # 699. V6/G6 - Event (Success)
    {
        "sample_id": "syn_p2_v6_g6_0699",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a success in your life.",
        "transcript_cleaned": "I consider passing my piano exam a significant success. I had been practicing for many months. The pieces I had to play were quite difficult. I felt nervous on the day of the exam. However, once I started playing, I focused on the music. I remembered all the advice my teacher gave me. When the examiner said I passed with distinction, I was overjoyed. It showed me that hard work pays off. My parents were very proud of me. This achievement boosted my confidence in my musical abilities.",
        "word_count": 91,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR6] Vocabulary: 'passing', 'piano exam', 'significant success', 'practicing', 'pieces', 'difficult', 'nervous', 'focused', 'advice', 'examiner', 'distinction', 'overjoyed', 'pays off', 'proud', 'achievement', 'boosted', 'confidence', 'abilities'. Adequate range. >Band 5: Uses specific words ('distinction', 'boosted'). Not Band 7: Lacks depth.",
        "grammar_reason": "[GRA6] Uses a mix of simple and complex structures accurately. 'I had been practicing...' (Past Perfect Continuous). 'Once I started playing...' (Time clause). 'That hard work pays off' (Noun clause). Generally error-free. >Band 5: Uses complex structures accurately. Not Band 7: Limited range.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a success in your life.\n\nTranscript: I consider passing my piano exam a significant success. I had been practicing for many months. The pieces I had to play were quite difficult. I felt nervous on the day of the exam. However, once I started playing, I focused on the music. I remembered all the advice my teacher gave me. When the examiner said I passed with distinction, I was overjoyed. It showed me that hard work pays off. My parents were very proud of me. This achievement boosted my confidence in my musical abilities.\n\nWord Count: 91 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses topic words: 'distinction', 'overjoyed', 'boosted'. Meaning is clear.\n\n>Band 5: Good range.\n\nNot Band 7: Lacks sophistication.\n\n**Idiom present:** Yes ('pays off')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Uses complex structures accurately. Includes past perfect continuous and time clauses. Good control.\n\n>Band 5: Frequent error-free sentences.\n\nNot Band 7: Range is limited.\n\n**Micro flaws identified:**\n- None."
    },
    # 700. V6/G6 - Activity (Hobby)
    {
        "sample_id": "syn_p2_v6_g6_0700",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a hobby you like.",
        "transcript_cleaned": "I like gardening, which is a very rewarding hobby. I have a small garden in my backyard where I grow flowers and vegetables. I enjoy planting seeds and watching them grow. It requires patience and care. I water the plants every day and remove weeds. When the flowers bloom, the garden looks colorful and beautiful. I also harvest fresh vegetables for my family. Gardening helps me connect with nature and relax. It is a great way to spend time outdoors. I plan to plant more fruit trees next year.",
        "word_count": 93,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR6] Vocabulary: 'gardening', 'rewarding hobby', 'backyard', 'grow', 'planting seeds', 'patience', 'care', 'water', 'remove weeds', 'bloom', 'colorful', 'harvest', 'fresh vegetables', 'connect', 'nature', 'outdoors', 'fruit trees'. Adequate range. >Band 5: Uses specific words ('harvest', 'weeds'). Not Band 7: Vocabulary is standard.",
        "grammar_reason": "[GRA6] Uses a mix of simple and complex structures accurately. 'Which is a very rewarding hobby' (Relative clause). 'Where I grow flowers...' (Relative clause). 'When the flowers bloom...' (Time clause). 'It is a great way to spend...' (Infinitive phrase). Generally error-free. >Band 5: Uses complex structures accurately. Not Band 7: Limited range.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a hobby you like.\n\nTranscript: I like gardening, which is a very rewarding hobby. I have a small garden in my backyard where I grow flowers and vegetables. I enjoy planting seeds and watching them grow. It requires patience and care. I water the plants every day and remove weeds. When the flowers bloom, the garden looks colorful and beautiful. I also harvest fresh vegetables for my family. Gardening helps me connect with nature and relax. It is a great way to spend time outdoors. I plan to plant more fruit trees next year.\n\nWord Count: 93 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses topic words: 'rewarding', 'harvest', 'connect'. Meaning is clear.\n\n>Band 5: Adequate vocabulary.\n\nNot Band 7: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Uses complex structures accurately. Includes relative clauses and time clauses. Good control.\n\n>Band 5: Frequent error-free sentences.\n\nNot Band 7: Range is limited.\n\n**Micro flaws identified:**\n- None."
    }
]

with open(OUTPUT_FILE, 'a', encoding='utf-8') as f:
    for sample in samples:
        f.write(json.dumps(sample) + '\n')
