import json

OUTPUT_FILE = "ielts-data/phase3/v76_review_output/synthetic_batches/batch_p2_12.jsonl"

samples = [
    # 581. V8/G6 - Movie (History)
    {
        "sample_id": "syn_p2_v8_g6_0581",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a historical movie you watched.",
        "transcript_cleaned": "I watched 'Schindler's List', a poignant film about the Holocaust. It depict the true story of Oskar Schindler, a German businessman who save Jewish refugees. The cinematography is stark and haunting, mostly filmed in black and white. I was deeply moved by the brutality and suffering portray on screen. The performances by the lead actors is compelling and emotional. It serve as a powerful reminder of the atrocities committed during the war. Although it is difficult to watch, it is an essential piece of cinema. It highlight the importance of compassion in the face of evil.",
        "word_count": 96,
        "response_type": "long_turn",
        "micro_flaws": ["agreement: 'It depict' should be 'It depicts'", "agreement: 'businessman who save' should be 'saved'", "grammar: 'suffering portray' should be 'portrayed'", "agreement: 'actors is' should be 'are'", "agreement: 'It serve' should be 'It serves'", "agreement: 'It highlight' should be 'It highlights'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR8] Vocabulary: 'poignant', 'Holocaust', 'depict', 'refugees', 'cinematography', 'stark', 'haunting', 'brutality', 'suffering', 'portray', 'compelling', 'emotional', 'atrocities', 'committed', 'essential', 'cinema', 'highlight', 'compassion'. Very sophisticated. >Band 7: Precise vocabulary. Not Band 9: Errors in usage distract.",
        "grammar_reason": "[GRA6] Uses complex structures but has frequent errors in agreement and verb forms ('depict', 'save', 'portray', 'is', 'serve', 'highlight'). >Band 5: Attempts complex sentences. Not Band 7: Errors are frequent.",
        "vocabulary": 8,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a historical movie you watched.\n\nTranscript: I watched 'Schindler's List', a poignant film about the Holocaust. It depict the true story of Oskar Schindler, a German businessman who save Jewish refugees. The cinematography is stark and haunting, mostly filmed in black and white. I was deeply moved by the brutality and suffering portray on screen. The performances by the lead actors is compelling and emotional. It serve as a powerful reminder of the atrocities committed during the war. Although it is difficult to watch, it is an essential piece of cinema. It highlight the importance of compassion in the face of evil.\n\nWord Count: 96 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses sophisticated vocabulary: 'poignant', 'stark', 'atrocities', 'compassion'. Precise and effective.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Errors affect flow.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Frequent errors in verb forms and agreement ('depict', 'save', 'is'). Complex structures used but flawed.\n\n>Band 5: Complex sentences attempted.\n\nNot Band 7: Systematic errors.\n\n**Micro flaws identified:**\n- 'It depict' should be 'It depicts'\n- 'businessman who save' should be 'saved'\n- 'suffering portray' should be 'portrayed'\n- 'actors is' should be 'are'\n- 'It serve' should be 'It serves'\n- 'It highlight' should be 'It highlights'"
    },
    # 582. V8/G6 - Place (Travel)
    {
        "sample_id": "syn_p2_v8_g6_0582",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a place you recommend visiting.",
        "transcript_cleaned": "I highly recommend visiting Kyoto in Japan, a city that epitomize traditional culture. It is famous for its sublime temples and Zen gardens. The atmosphere is serene, which offering a respite from modern life. I was enchanting by the geisha district, Gion. Walking through the narrow alleys feel like stepping back in time. The culinary experience is also exquisite, with many Michelin-starred restaurants. However, it can gets very crowded during cherry blossom season. I suggest visiting in autumn when the foliage are vibrant red. It is a destination that captivate the soul.",
        "word_count": 92,
        "response_type": "long_turn",
        "micro_flaws": ["agreement: 'city that epitomize' should be 'epitomizes'", "grammar: 'which offering' should be 'which offers'", "grammar: 'was enchanting' should be 'was enchanted'", "agreement: 'alleys feel' should be 'feels' (walking feels)", "grammar: 'can gets' should be 'can get'", "agreement: 'foliage are' should be 'is'", "agreement: 'destination that captivate' should be 'captivates'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR8] Vocabulary: 'epitomize', 'sublime', 'Zen gardens', 'serene', 'respite', 'enchanting', 'alleys', 'culinary experience', 'exquisite', 'Michelin-starred', 'foliage', 'vibrant', 'destination', 'captivate'. Very sophisticated. >Band 7: Precise vocabulary. Not Band 9: Errors in usage.",
        "grammar_reason": "[GRA6] Uses complex structures but has frequent errors. Verb form errors ('epitomize', 'offering', 'enchanting', 'gets', 'captivate'). Agreement error ('foliage are'). >Band 5: Attempts complex sentences. Not Band 7: Errors are noticeable.",
        "vocabulary": 8,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a place you recommend visiting.\n\nTranscript: I highly recommend visiting Kyoto in Japan, a city that epitomize traditional culture. It is famous for its sublime temples and Zen gardens. The atmosphere is serene, which offering a respite from modern life. I was enchanting by the geisha district, Gion. Walking through the narrow alleys feel like stepping back in time. The culinary experience is also exquisite, with many Michelin-starred restaurants. However, it can gets very crowded during cherry blossom season. I suggest visiting in autumn when the foliage are vibrant red. It is a destination that captivate the soul.\n\nWord Count: 92 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses sophisticated vocabulary: 'epitomize', 'sublime', 'respite', 'exquisite'. Precise.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Errors affect accuracy.\n\n**Idiom present:** Yes ('stepping back in time')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Frequent errors in verb forms ('epitomize', 'offering', 'enchanting'). Complex structures used but flawed.\n\n>Band 5: Complex sentences attempted.\n\nNot Band 7: Systematic errors.\n\n**Micro flaws identified:**\n- 'city that epitomize' should be 'epitomizes'\n- 'which offering' should be 'which offers'\n- 'was enchanting' should be 'was enchanted'\n- 'alleys feel' should be 'feels'\n- 'can gets' should be 'can get'\n- 'foliage are' should be 'foliage is'\n- 'destination that captivate' should be 'captivates'"
    },
    # 583. V8/G6 - Event (Concert)
    {
        "sample_id": "syn_p2_v8_g6_0583",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a music concert you enjoyed.",
        "transcript_cleaned": "I attended a symphony orchestra concert that was truly mesmerizing. The conductor led the musicians with impeccable precision and passion. The acoustic in the hall were phenomenal, amplifying every note clearly. I was particularly struck by the violinist's virtuosity during the solo performance. The crescendo of the finale evoking powerful emotions in the audience. Everyone were spellbound by the harmony of the instruments. It was a transcendental experience that lifted my spirits. I have never hearing such beautiful music before. It solidified my appreciation for classical compositions.",
        "word_count": 88,
        "response_type": "long_turn",
        "micro_flaws": ["agreement: 'acoustic... were' should be 'acoustics... were' or 'acoustic... was'", "grammar: 'finale evoking' should be 'evoked'", "agreement: 'Everyone were' should be 'was'", "grammar: 'never hearing' should be 'never heard'", "agreement: 'It solidified' (correct but in context of errors ok)"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR8] Vocabulary: 'symphony orchestra', 'mesmerizing', 'conductor', 'impeccable precision', 'acoustic', 'phenomenal', 'amplifying', 'virtuosity', 'crescendo', 'finale', 'evoking', 'spellbound', 'harmony', 'transcendental', 'lifted my spirits', 'solidified', 'appreciation', 'compositions'. Very sophisticated. >Band 7: Precise vocabulary. Not Band 9: Errors in usage.",
        "grammar_reason": "[GRA6] Uses complex structures but has frequent errors. Agreement errors ('acoustic were', 'Everyone were'). Verb form errors ('evoking', 'hearing'). >Band 5: Attempts complex sentences. Not Band 7: Errors are noticeable.",
        "vocabulary": 8,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a music concert you enjoyed.\n\nTranscript: I attended a symphony orchestra concert that was truly mesmerizing. The conductor led the musicians with impeccable precision and passion. The acoustic in the hall were phenomenal, amplifying every note clearly. I was particularly struck by the violinist's virtuosity during the solo performance. The crescendo of the finale evoking powerful emotions in the audience. Everyone were spellbound by the harmony of the instruments. It was a transcendental experience that lifted my spirits. I have never hearing such beautiful music before. It solidified my appreciation for classical compositions.\n\nWord Count: 88 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses sophisticated vocabulary: 'impeccable', 'virtuosity', 'crescendo', 'transcendental'. Precise.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Errors affect accuracy.\n\n**Idiom present:** Yes ('lifted my spirits')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Frequent errors in verb forms ('evoking', 'hearing') and agreement. Complex structures used but flawed.\n\n>Band 5: Complex sentences attempted.\n\nNot Band 7: Systematic errors.\n\n**Micro flaws identified:**\n- 'acoustic... were' should be 'acoustics... were'\n- 'finale evoking' should be 'finale evoked'\n- 'Everyone were' should be 'Everyone was'\n- 'never hearing' should be 'never heard'"
    },
    # 584. V8/G6 - Activity (Skill)
    {
        "sample_id": "syn_p2_v8_g6_0584",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a skill you found difficult to learn.",
        "transcript_cleaned": "Learning to code in Python was a daunting challenge for me. I initially struggling with the syntax and logical structures. Debugging the errors were frustrating and time-consuming. I often feeling overwhelmed by the complexity of the algorithms. However, I persisted because I realized the immense potential of programming. I utilizing online tutorials and forums to overcome obstacles. Slowly, the concepts beginning to make sense. Now, I can automate mundane tasks, which is incredibly satisfying. Mastering this skill have opened new doors for my career.",
        "word_count": 86,
        "response_type": "long_turn",
        "micro_flaws": ["tense: 'I initially struggling' should be 'struggled'", "agreement: 'errors were' should be 'was' (debugging was)", "tense: 'I often feeling' should be 'felt'", "grammar: 'I utilizing' should be 'I utilized'", "grammar: 'concepts beginning' should be 'began'", "agreement: 'skill have' should be 'has'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR8] Vocabulary: 'daunting challenge', 'syntax', 'logical structures', 'debugging', 'frustrating', 'time-consuming', 'overwhelmed', 'complexity', 'algorithms', 'persisted', 'immense potential', 'utilizing', 'obstacles', 'concepts', 'automate', 'mundane tasks', 'satisfying', 'mastering'. Very sophisticated. >Band 7: Precise technical vocabulary. Not Band 9: Errors in usage.",
        "grammar_reason": "[GRA6] Uses complex structures but has frequent errors. Incorrect use of continuous tense ('struggling', 'feeling', 'utilizing', 'beginning'). Agreement error ('skill have'). >Band 5: Attempts complex sentences. Not Band 7: Errors are frequent.",
        "vocabulary": 8,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a skill you found difficult to learn.\n\nTranscript: Learning to code in Python was a daunting challenge for me. I initially struggling with the syntax and logical structures. Debugging the errors were frustrating and time-consuming. I often feeling overwhelmed by the complexity of the algorithms. However, I persisted because I realized the immense potential of programming. I utilizing online tutorials and forums to overcome obstacles. Slowly, the concepts beginning to make sense. Now, I can automate mundane tasks, which is incredibly satisfying. Mastering this skill have opened new doors for my career.\n\nWord Count: 86 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses sophisticated vocabulary: 'daunting', 'syntax', 'debugging', 'algorithms', 'mundane'. Precise.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Errors affect accuracy.\n\n**Idiom present:** Yes ('opened new doors')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Frequent errors in verb forms ('struggling', 'utilizing'). Complex structures used but flawed.\n\n>Band 5: Complex sentences attempted.\n\nNot Band 7: Systematic errors.\n\n**Micro flaws identified:**\n- 'I initially struggling' should be 'I initially struggled'\n- 'errors were' should be 'errors was' (debugging was)\n- 'I often feeling' should be 'I often felt'\n- 'I utilizing' should be 'I utilized'\n- 'concepts beginning' should be 'concepts began'\n- 'skill have' should be 'skill has'"
    },
    # 585. V8/G6 - Object (Technology)
    {
        "sample_id": "syn_p2_v8_g6_0585",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a piece of technology you use often.",
        "transcript_cleaned": "I am reliant on my tablet, which serves as a versatile workstation. It allows me to edit documents and create presentations seamlessly. The high-resolution display render images with stunning clarity. I appreciate the portability, as it fit easily into my bag. I using it for both professional tasks and entertainment consumption. The battery life is impressive, enduring through long flights. However, the software occasionally lagging when I multitask. Despite this minor flaw, it remain an indispensable gadget in my daily life. It has enhanced my productivity significantly.",
        "word_count": 89,
        "response_type": "long_turn",
        "micro_flaws": ["agreement: 'display render' should be 'renders'", "agreement: 'it fit' should be 'fits'", "grammar: 'I using' should be 'I use'", "grammar: 'occasionally lagging' should be 'lags'", "agreement: 'it remain' should be 'remains'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR8] Vocabulary: 'reliant', 'versatile workstation', 'edit documents', 'presentations', 'seamlessly', 'high-resolution', 'render', 'stunning clarity', 'portability', 'consumption', 'enduring', 'software', 'multitask', 'flaw', 'indispensable gadget', 'enhanced', 'productivity'. Very sophisticated. >Band 7: Precise vocabulary. Not Band 9: Errors in usage.",
        "grammar_reason": "[GRA6] Uses complex structures but has frequent errors. Agreement errors ('render', 'fit', 'remain'). Verb form errors ('using', 'lagging'). >Band 5: Attempts complex sentences. Not Band 7: Errors are noticeable.",
        "vocabulary": 8,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a piece of technology you use often.\n\nTranscript: I am reliant on my tablet, which serves as a versatile workstation. It allows me to edit documents and create presentations seamlessly. The high-resolution display render images with stunning clarity. I appreciate the portability, as it fit easily into my bag. I using it for both professional tasks and entertainment consumption. The battery life is impressive, enduring through long flights. However, the software occasionally lagging when I multitask. Despite this minor flaw, it remain an indispensable gadget in my daily life. It has enhanced my productivity significantly.\n\nWord Count: 89 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses sophisticated vocabulary: 'reliant', 'versatile', 'seamlessly', 'indispensable'. Precise.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Errors affect flow.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Frequent errors in verb forms and agreement ('render', 'using', 'lagging'). Complex structures used but flawed.\n\n>Band 5: Complex sentences attempted.\n\nNot Band 7: Systematic errors.\n\n**Micro flaws identified:**\n- 'display render' should be 'renders'\n- 'it fit' should be 'fits'\n- 'I using' should be 'I use'\n- 'occasionally lagging' should be 'lags'\n- 'it remain' should be 'remains'"
    },
    # 586. V8/G6 - Person (Child)
    {
        "sample_id": "syn_p2_v8_g6_0586",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a clever child you know.",
        "transcript_cleaned": "I am amazed by my niece, who is a prodigy in mathematics. At age five, she can solving complex equations mentally. She possesses an insatiable curiosity about how things works. Her vocabulary is extensive, often surprising adults with her articulate responses. I watched her assemble a complicated Lego set without instructions, which were impressive. She absorbing information like a sponge. However, she sometimes struggle to interact with peers her own age. Her intellectual maturity set her apart from other children. I believe she have a brilliant future ahead.",
        "word_count": 91,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'can solving' should be 'can solve'", "agreement: 'things works' should be 'work'", "agreement: 'which were' should be 'was' (referring to the act)", "grammar: 'She absorbing' should be 'She absorbs'", "agreement: 'she... struggle' should be 'struggles'", "agreement: 'maturity set' should be 'sets'", "agreement: 'she have' should be 'has'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR8] Vocabulary: 'amazed', 'prodigy', 'equations', 'mentally', 'possesses', 'insatiable curiosity', 'extensive', 'articulate', 'assemble', 'complicated', 'instructions', 'absorbing', 'sponge', 'interact', 'peers', 'intellectual maturity', 'set her apart', 'brilliant'. Very sophisticated. >Band 7: Precise vocabulary. Not Band 9: Errors in usage.",
        "grammar_reason": "[GRA6] Uses complex structures but has frequent errors. Modal error ('can solving'). Agreement errors ('works', 'struggle', 'set', 'have'). Verb form error ('absorbing'). >Band 5: Attempts complex sentences. Not Band 7: Errors are frequent.",
        "vocabulary": 8,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a clever child you know.\n\nTranscript: I am amazed by my niece, who is a prodigy in mathematics. At age five, she can solving complex equations mentally. She possesses an insatiable curiosity about how things works. Her vocabulary is extensive, often surprising adults with her articulate responses. I watched her assemble a complicated Lego set without instructions, which were impressive. She absorbing information like a sponge. However, she sometimes struggle to interact with peers her own age. Her intellectual maturity set her apart from other children. I believe she have a brilliant future ahead.\n\nWord Count: 91 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses sophisticated vocabulary: 'prodigy', 'insatiable', 'articulate', 'maturity'. Precise.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Errors affect flow.\n\n**Idiom present:** Yes ('like a sponge')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Frequent errors in verb forms and agreement ('can solving', 'works', 'absorbing'). Complex structures used but flawed.\n\n>Band 5: Complex sentences attempted.\n\nNot Band 7: Systematic errors.\n\n**Micro flaws identified:**\n- 'can solving' should be 'can solve'\n- 'things works' should be 'work'\n- 'which were' should be 'which was'\n- 'She absorbing' should be 'She absorbs'\n- 'she... struggle' should be 'struggles'\n- 'maturity set' should be 'sets'\n- 'she have' should be 'has'"
    },
    # 587. V8/G6 - Activity (Healthy)
    {
        "sample_id": "syn_p2_v8_g6_0587",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a healthy habit you have.",
        "transcript_cleaned": "I adhere to a regimen of intermittent fasting to maintain my metabolic health. It involves cycling between periods of eating and fasting. I finding it beneficial for weight management and mental clarity. Initially, the hunger pangs was difficult to ignore. However, my body adapted, and I now feeling more energetic. This practice also promoting cellular repair through autophagy. I am disciplined about my eating window, avoiding processed foods. It has become an integral part of my lifestyle. I believing it prolongs longevity and vitality.",
        "word_count": 86,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'I finding' should be 'I find'", "agreement: 'pangs was' should be 'were'", "grammar: 'I now feeling' should be 'I now feel'", "grammar: 'practice also promoting' should be 'promotes'", "grammar: 'I believing' should be 'I believe'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR8] Vocabulary: 'adhere', 'regimen', 'intermittent fasting', 'metabolic health', 'cycling', 'beneficial', 'weight management', 'mental clarity', 'hunger pangs', 'adapted', 'energetic', 'cellular repair', 'autophagy', 'disciplined', 'eating window', 'processed foods', 'integral', 'prolongs', 'longevity', 'vitality'. Very sophisticated. >Band 7: Precise vocabulary. Not Band 9: Errors in usage.",
        "grammar_reason": "[GRA6] Uses complex structures but has frequent errors. Verb form errors are systematic ('finding', 'feeling', 'promoting', 'believing'). Agreement error ('pangs was'). >Band 5: Attempts complex sentences. Not Band 7: Errors are frequent.",
        "vocabulary": 8,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a healthy habit you have.\n\nTranscript: I adhere to a regimen of intermittent fasting to maintain my metabolic health. It involves cycling between periods of eating and fasting. I finding it beneficial for weight management and mental clarity. Initially, the hunger pangs was difficult to ignore. However, my body adapted, and I now feeling more energetic. This practice also promoting cellular repair through autophagy. I am disciplined about my eating window, avoiding processed foods. It has become an integral part of my lifestyle. I believing it prolongs longevity and vitality.\n\nWord Count: 86 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses sophisticated vocabulary: 'adhere', 'metabolic', 'autophagy', 'longevity'. Precise.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Errors affect flow.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Frequent errors in verb forms ('finding', 'feeling', 'promoting'). Complex structures used but flawed.\n\n>Band 5: Complex sentences attempted.\n\nNot Band 7: Systematic errors.\n\n**Micro flaws identified:**\n- 'I finding' should be 'I find'\n- 'pangs was' should be 'were'\n- 'I now feeling' should be 'I now feel'\n- 'practice also promoting' should be 'promotes'\n- 'I believing' should be 'I believe'"
    },
    # 588. V8/G6 - Place (Nature)
    {
        "sample_id": "syn_p2_v8_g6_0588",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a natural place you want to visit.",
        "transcript_cleaned": "I yearn to visit the Amazon Rainforest, a biodiversity hotspot of immense ecological significance. I am fascinated by the teeming wildlife and lush vegetation. The idea of navigating the winding river appeal to my adventurous spirit. I want to witnessing the vibrant plumage of macaws and the stealth of jaguars. However, the threat of deforestation concern me deeply. Preserving this pristine ecosystem is crucial for the planet's climate. I hoping to take an eco-friendly tour to minimize my carbon footprint. It would be a transformative immersion in nature.",
        "word_count": 91,
        "response_type": "long_turn",
        "micro_flaws": ["agreement: 'river appeal' should be 'appeals'", "grammar: 'want to witnessing' should be 'want to witness'", "agreement: 'threat... concern' should be 'concerns'", "grammar: 'I hoping' should be 'I hope'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR8] Vocabulary: 'yearn', 'biodiversity hotspot', 'immense', 'ecological significance', 'teeming', 'lush vegetation', 'navigating', 'winding', 'adventurous spirit', 'vibrant plumage', 'stealth', 'deforestation', 'preserving', 'pristine ecosystem', 'crucial', 'eco-friendly', 'minimize', 'carbon footprint', 'transformative immersion'. Very sophisticated. >Band 7: Precise vocabulary. Not Band 9: Errors in usage.",
        "grammar_reason": "[GRA6] Uses complex structures but has frequent errors. Agreement errors ('river appeal', 'threat concern'). Verb form errors ('witnessing', 'hoping'). >Band 5: Attempts complex sentences. Not Band 7: Errors are noticeable.",
        "vocabulary": 8,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a natural place you want to visit.\n\nTranscript: I yearn to visit the Amazon Rainforest, a biodiversity hotspot of immense ecological significance. I am fascinated by the teeming wildlife and lush vegetation. The idea of navigating the winding river appeal to my adventurous spirit. I want to witnessing the vibrant plumage of macaws and the stealth of jaguars. However, the threat of deforestation concern me deeply. Preserving this pristine ecosystem is crucial for the planet's climate. I hoping to take an eco-friendly tour to minimize my carbon footprint. It would be a transformative immersion in nature.\n\nWord Count: 91 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses sophisticated vocabulary: 'hotspot', 'plumage', 'stealth', 'immersion'. Precise.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Errors affect flow.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Frequent errors in verb forms and agreement ('appeal', 'witnessing', 'concern'). Complex structures used but flawed.\n\n>Band 5: Complex sentences attempted.\n\nNot Band 7: Systematic errors.\n\n**Micro flaws identified:**\n- 'river appeal' should be 'appeals'\n- 'want to witnessing' should be 'want to witness'\n- 'threat... concern' should be 'concerns'\n- 'I hoping' should be 'I hope'"
    },
    # 589. V8/G6 - Book (Favorite)
    {
        "sample_id": "syn_p2_v8_g6_0589",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a book you love.",
        "transcript_cleaned": "I cherish 'The Alchemist' by Paulo Coelho, a philosophical novel about following one's destiny. The protagonist's journey is allegorical, representing the pursuit of our dreams. I was inspired by the notion that the universe conspire to help us achieve our goals. The prose is simple yet profound, resonating with readers worldwide. It encourage me to listen to my intuition and embrace the unknown. Although I have read it multiple times, I always finding new insights. It is a timeless fable that uplift the spirit. It serves as a guiding light in my life.",
        "word_count": 96,
        "response_type": "long_turn",
        "micro_flaws": ["agreement: 'universe conspire' should be 'conspires'", "agreement: 'It encourage' should be 'encourages'", "grammar: 'I always finding' should be 'I always find'", "agreement: 'fable that uplift' should be 'uplifts'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR8] Vocabulary: 'cherish', 'philosophical novel', 'destiny', 'protagonist', 'allegorical', 'pursuit', 'notion', 'universe', 'conspire', 'prose', 'profound', 'resonating', 'intuition', 'embrace', 'unknown', 'insights', 'timeless fable', 'uplift', 'guiding light'. Very sophisticated. >Band 7: Precise vocabulary. Not Band 9: Errors in usage.",
        "grammar_reason": "[GRA6] Uses complex structures but has frequent errors. Agreement errors ('conspire', 'encourage', 'uplift'). Verb form error ('finding'). >Band 5: Attempts complex sentences. Not Band 7: Errors are noticeable.",
        "vocabulary": 8,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a book you love.\n\nTranscript: I cherish 'The Alchemist' by Paulo Coelho, a philosophical novel about following one's destiny. The protagonist's journey is allegorical, representing the pursuit of our dreams. I was inspired by the notion that the universe conspire to help us achieve our goals. The prose is simple yet profound, resonating with readers worldwide. It encourage me to listen to my intuition and embrace the unknown. Although I have read it multiple times, I always finding new insights. It is a timeless fable that uplift the spirit. It serves as a guiding light in my life.\n\nWord Count: 96 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses sophisticated vocabulary: 'allegorical', 'notion', 'prose', 'intuition'. Precise.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Errors affect flow.\n\n**Idiom present:** Yes ('guiding light')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Frequent errors in verb forms and agreement ('conspire', 'encourage', 'finding'). Complex structures used but flawed.\n\n>Band 5: Complex sentences attempted.\n\nNot Band 7: Systematic errors.\n\n**Micro flaws identified:**\n- 'universe conspire' should be 'conspires'\n- 'It encourage' should be 'encourages'\n- 'I always finding' should be 'I always find'\n- 'fable that uplift' should be 'uplifts'"
    },
    # 590. V8/G6 - Person (Teacher)
    {
        "sample_id": "syn_p2_v8_g6_0590",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a teacher you remember.",
        "transcript_cleaned": "I remember my biology teacher, Mr. Smith, who was an eccentric and passionate educator. He had a knack for simplifying complex biological concepts. I was captivated by his enthusiasm for the natural world. He often taking us on field trips to observe ecosystems firsthand. He encourage us to question scientific theories and think critically. His dedication to his students were exemplary. I attribute my interest in environmental science to his influence. He leave a lasting legacy in our school. I am grateful for his mentorship.",
        "word_count": 86,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'He often taking' should be 'took'", "agreement: 'He encourage' should be 'encouraged'", "agreement: 'dedication... were' should be 'was'", "agreement: 'He leave' should be 'left'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR8] Vocabulary: 'eccentric', 'passionate educator', 'knack', 'simplifying', 'biological concepts', 'captivated', 'enthusiasm', 'field trips', 'ecosystems', 'firsthand', 'critically', 'dedication', 'exemplary', 'attribute', 'environmental science', 'influence', 'lasting legacy', 'mentorship'. Very sophisticated. >Band 7: Precise vocabulary. Not Band 9: Errors in usage.",
        "grammar_reason": "[GRA6] Uses complex structures but has frequent errors. Verb form errors ('taking', 'encourage', 'leave'). Agreement error ('dedication were'). >Band 5: Attempts complex sentences. Not Band 7: Errors are frequent.",
        "vocabulary": 8,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a teacher you remember.\n\nTranscript: I remember my biology teacher, Mr. Smith, who was an eccentric and passionate educator. He had a knack for simplifying complex biological concepts. I was captivated by his enthusiasm for the natural world. He often taking us on field trips to observe ecosystems firsthand. He encourage us to question scientific theories and think critically. His dedication to his students were exemplary. I attribute my interest in environmental science to his influence. He leave a lasting legacy in our school. I am grateful for his mentorship.\n\nWord Count: 86 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses sophisticated vocabulary: 'eccentric', 'knack', 'exemplary', 'attribute'. Precise.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Errors affect flow.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Frequent errors in verb forms and agreement ('taking', 'encourage', 'were'). Complex structures used but flawed.\n\n>Band 5: Complex sentences attempted.\n\nNot Band 7: Systematic errors.\n\n**Micro flaws identified:**\n- 'He often taking' should be 'took'\n- 'He encourage' should be 'encouraged'\n- 'dedication... were' should be 'was'\n- 'He leave' should be 'left'"
    }
]

with open(OUTPUT_FILE, 'a', encoding='utf-8') as f:
    for sample in samples:
        f.write(json.dumps(sample) + '\n')
