import json

OUTPUT_FILE = "ielts-data/phase3/v76_review_output/synthetic_batches/batch_p2_14.jsonl"

samples = [
    # 661. V6/G9 - Book (Read)
    {
        "sample_id": "syn_p2_v6_g9_0661",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a book you read.",
        "transcript_cleaned": "I recently finished reading a fantasy novel that was recommended by my friend. It tells the story of a young hero who must save his kingdom from a dark force. The characters are well-developed, and the plot is exciting. What I found most interesting was the imaginary world the author created. The descriptions of the landscapes were very detailed. I enjoyed reading it because it allowed me to escape from reality. It is a book that I would definitely read again. The ending was unexpected but satisfying. I think it is suitable for people of all ages.",
        "word_count": 97,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR6] Vocabulary: 'fantasy novel', 'recommended', 'hero', 'kingdom', 'dark force', 'well-developed', 'plot', 'exciting', 'imaginary world', 'author', 'descriptions', 'detailed', 'escape', 'reality', 'unexpected', 'satisfying', 'suitable'. Adequate range. >Band 5: Uses some less common words ('well-developed', 'unexpected'). Not Band 7: Lacks style.",
        "grammar_reason": "[GRA9] Full range of structures used naturally. 'That was recommended...' (Passive relative clause). 'Who must save his kingdom' (Relative clause). 'What I found most interesting was...' (Pseudo-cleft). 'Because it allowed me to escape' (Reason clause). Error-free. >Band 8: Native-like control.",
        "vocabulary": 6,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a book you read.\n\nTranscript: I recently finished reading a fantasy novel that was recommended by my friend. It tells the story of a young hero who must save his kingdom from a dark force. The characters are well-developed, and the plot is exciting. What I found most interesting was the imaginary world the author created. The descriptions of the landscapes were very detailed. I enjoyed reading it because it allowed me to escape from reality. It is a book that I would definitely read again. The ending was unexpected but satisfying. I think it is suitable for people of all ages.\n\nWord Count: 97 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses relevant vocabulary: 'fantasy', 'well-developed', 'satisfying'. Clear description.\n\n>Band 5: Good range.\n\nNot Band 7: Lacks sophistication.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Uses a full range of structures naturally and accurately. Pseudo-cleft sentences and relative clauses are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    },
    # 662. V6/G9 - Place (Town)
    {
        "sample_id": "syn_p2_v6_g9_0662",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a town you visited.",
        "transcript_cleaned": "I visited a small coastal town last summer, which was a delightful experience. It is located in the south of France and is famous for its beaches. The town has a charming old quarter with narrow streets and colorful houses. I spent my days walking along the promenade and enjoying the sea view. What impressed me the most was the friendly nature of the locals. The food was also excellent, especially the fresh seafood dishes. Although it was a short trip, it was very relaxing. I would love to return there in the future.",
        "word_count": 96,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR6] Vocabulary: 'coastal town', 'delightful', 'located', 'famous', 'charming', 'old quarter', 'narrow streets', 'colorful', 'promenade', 'sea view', 'impressed', 'friendly nature', 'locals', 'seafood dishes', 'relaxing'. Adequate range. >Band 5: Uses descriptive adjectives ('charming', 'delightful'). Not Band 7: Vocabulary is standard.",
        "grammar_reason": "[GRA9] Full range of structures used naturally. 'Which was a delightful experience' (Relative clause). 'Located in the south...' (Participle phrase). 'What impressed me the most was...' (Pseudo-cleft). 'Although it was a short trip...' (Concessive clause). Error-free. >Band 8: Native-like control.",
        "vocabulary": 6,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a town you visited.\n\nTranscript: I visited a small coastal town last summer, which was a delightful experience. It is located in the south of France and is famous for its beaches. The town has a charming old quarter with narrow streets and colorful houses. I spent my days walking along the promenade and enjoying the sea view. What impressed me the most was the friendly nature of the locals. The food was also excellent, especially the fresh seafood dishes. Although it was a short trip, it was very relaxing. I would love to return there in the future.\n\nWord Count: 96 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses descriptive words: 'charming', 'promenade', 'relaxing'. Clear meaning.\n\n>Band 5: Good range.\n\nNot Band 7: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Uses a full range of structures naturally and accurately. Participle phrases and pseudo-clefts are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    },
    # 663. V6/G9 - Event (Party)
    {
        "sample_id": "syn_p2_v6_g9_0663",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a party you enjoyed.",
        "transcript_cleaned": "I went to a surprise birthday party for my best friend, which was held at a local restaurant. Her sister organized it, inviting all our close friends. We decorated the room with balloons and banners before she arrived. The look on her face when she walked in was priceless. We had a great time eating delicious food and playing games. What made the night special was the warm atmosphere and the laughter we shared. It was a wonderful celebration of our friendship. I am glad that I could be a part of it.",
        "word_count": 94,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR6] Vocabulary: 'surprise birthday party', 'held', 'local restaurant', 'organized', 'inviting', 'close friends', 'decorated', 'balloons', 'banners', 'priceless', 'delicious food', 'warm atmosphere', 'laughter', 'celebration', 'friendship'. Adequate range. >Band 5: Uses specific words ('priceless', 'atmosphere'). Not Band 7: Lacks sophistication.",
        "grammar_reason": "[GRA9] Full range of structures used naturally. 'Which was held at...' (Relative clause). 'Inviting all our close friends' (Participle phrase). 'When she walked in' (Time clause). 'What made the night special was...' (Pseudo-cleft). Error-free. >Band 8: Native-like control.",
        "vocabulary": 6,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a party you enjoyed.\n\nTranscript: I went to a surprise birthday party for my best friend, which was held at a local restaurant. Her sister organized it, inviting all our close friends. We decorated the room with balloons and banners before she arrived. The look on her face when she walked in was priceless. We had a great time eating delicious food and playing games. What made the night special was the warm atmosphere and the laughter we shared. It was a wonderful celebration of our friendship. I am glad that I could be a part of it.\n\nWord Count: 94 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses topic words: 'surprise', 'priceless', 'celebration'. Meaning is clear.\n\n>Band 5: Good range.\n\nNot Band 7: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Uses a full range of structures naturally and accurately. Pseudo-cleft sentences and participle phrases are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    },
    # 664. V6/G9 - Person (Teacher)
    {
        "sample_id": "syn_p2_v6_g9_0664",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a teacher you liked.",
        "transcript_cleaned": "I would like to describe my English teacher, Mr. Jones, who taught me in high school. He was a very patient and encouraging person. His lessons were always interesting because he used different teaching methods. For example, we often played educational games or watched videos. What I admired most about him was his dedication to helping students improve. He would spend extra time explaining difficult grammar points. Thanks to his guidance, my English skills improved significantly. He is a teacher whom I will always remember with fond memories.",
        "word_count": 89,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR6] Vocabulary: 'English teacher', 'patient', 'encouraging', 'teaching methods', 'educational games', 'admired', 'dedication', 'improve', 'extra time', 'explaining', 'grammar points', 'guidance', 'significantly', 'fond memories'. Adequate range. >Band 5: Uses specific words ('dedication', 'guidance'). Not Band 7: Vocabulary is standard.",
        "grammar_reason": "[GRA9] Full range of structures used naturally. 'Who taught me in high school' (Relative clause). 'Because he used different teaching methods' (Reason clause). 'What I admired most... was...' (Pseudo-cleft). 'Thanks to his guidance' (Prepositional phrase). 'Whom I will always remember' (Relative clause). Error-free. >Band 8: Native-like control.",
        "vocabulary": 6,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a teacher you liked.\n\nTranscript: I would like to describe my English teacher, Mr. Jones, who taught me in high school. He was a very patient and encouraging person. His lessons were always interesting because he used different teaching methods. For example, we often played educational games or watched videos. What I admired most about him was his dedication to helping students improve. He would spend extra time explaining difficult grammar points. Thanks to his guidance, my English skills improved significantly. He is a teacher whom I will always remember with fond memories.\n\nWord Count: 89 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses relevant vocabulary: 'encouraging', 'dedication', 'guidance'. Clear description.\n\n>Band 5: Good range.\n\nNot Band 7: Lacks sophistication.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Uses a full range of structures naturally and accurately. Pseudo-cleft sentences and relative clauses are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    },
    # 665. V6/G9 - Object (Gift)
    {
        "sample_id": "syn_p2_v6_g9_0665",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a gift you received.",
        "transcript_cleaned": "I received a digital camera for my graduation, which was a very special gift. My parents bought it for me because they knew I enjoyed photography. It is a compact camera that is easy to carry around. I was thrilled when I opened the box and saw it. Since then, I have taken hundreds of photos of my friends and family. What makes it useful is its ability to take high-quality images in low light. It has allowed me to capture many precious moments. I treasure this gift very much.",
        "word_count": 93,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR6] Vocabulary: 'digital camera', 'graduation', 'special gift', 'photography', 'compact', 'carry around', 'thrilled', 'hundreds', 'useful', 'high-quality images', 'low light', 'capture', 'precious moments', 'treasure'. Adequate range. >Band 5: Uses specific words ('compact', 'capture'). Not Band 7: Lacks depth.",
        "grammar_reason": "[GRA9] Full range of structures used naturally. 'Which was a very special gift' (Relative clause). 'Because they knew...' (Reason clause). 'That is easy to carry around' (Relative clause). 'What makes it useful is...' (Pseudo-cleft). 'It has allowed me to capture...' (Present Perfect + Infinitive). Error-free. >Band 8: Native-like control.",
        "vocabulary": 6,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a gift you received.\n\nTranscript: I received a digital camera for my graduation, which was a very special gift. My parents bought it for me because they knew I enjoyed photography. It is a compact camera that is easy to carry around. I was thrilled when I opened the box and saw it. Since then, I have taken hundreds of photos of my friends and family. What makes it useful is its ability to take high-quality images in low light. It has allowed me to capture many precious moments. I treasure this gift very much.\n\nWord Count: 93 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses topic words: 'compact', 'capture', 'treasure'. Meaning is clear.\n\n>Band 5: Adequate vocabulary.\n\nNot Band 7: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Uses a full range of structures naturally and accurately. Pseudo-cleft sentences and present perfect tense are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    },
    # 666. V6/G9 - Activity (Daily)
    {
        "sample_id": "syn_p2_v6_g9_0666",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe your morning routine.",
        "transcript_cleaned": "My morning routine is quite simple, yet it helps me start the day effectively. I usually wake up at 7 am, feeling refreshed after a good night's sleep. The first thing I do is drink a glass of water, which is a healthy habit. Then, I go for a short run in the park near my house. Running in the fresh air energizes me for the day ahead. After exercising, I take a shower and prepare a nutritious breakfast. Having a routine gives me a sense of structure. It ensures that I am ready for work on time.",
        "word_count": 100,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR6] Vocabulary: 'morning routine', 'simple', 'effectively', 'refreshed', 'healthy habit', 'run', 'park', 'fresh air', 'energizes', 'exercising', 'nutritious breakfast', 'sense of structure', 'ensures'. Adequate range. >Band 5: Uses specific words ('nutritious', 'energizes'). Not Band 7: Vocabulary is standard.",
        "grammar_reason": "[GRA9] Full range of structures used naturally. 'Yet it helps me...' (Conjunction). 'Feeling refreshed...' (Participle phrase). 'The first thing I do is...' (Pseudo-cleft). 'Which is a healthy habit' (Relative clause). 'Running in the fresh air...' (Gerund subject). Error-free. >Band 8: Native-like control.",
        "vocabulary": 6,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe your morning routine.\n\nTranscript: My morning routine is quite simple, yet it helps me start the day effectively. I usually wake up at 7 am, feeling refreshed after a good night's sleep. The first thing I do is drink a glass of water, which is a healthy habit. Then, I go for a short run in the park near my house. Running in the fresh air energizes me for the day ahead. After exercising, I take a shower and prepare a nutritious breakfast. Having a routine gives me a sense of structure. It ensures that I am ready for work on time.\n\nWord Count: 100 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses relevant vocabulary: 'refreshed', 'nutritious', 'structure'. Clear description.\n\n>Band 5: Good range.\n\nNot Band 7: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Uses a full range of structures naturally and accurately. Participle phrases and gerund subjects are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    },
    # 667. V6/G9 - Activity (Hobby)
    {
        "sample_id": "syn_p2_v6_g9_0667",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a hobby you have.",
        "transcript_cleaned": "I enjoy cooking in my free time, which is a creative and relaxing hobby. I started learning how to cook when I was a teenager. I like experimenting with different ingredients to create new dishes. My favorite thing to make is pasta, as there are so many sauce variations. What I love about cooking is the satisfaction of sharing a meal with friends. It allows me to express my care for them. Although it can be time-consuming, the result is always worth it. I hope to take a professional cooking class in the future.",
        "word_count": 97,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR6] Vocabulary: 'cooking', 'creative', 'relaxing hobby', 'experimenting', 'ingredients', 'dishes', 'pasta', 'sauce variations', 'satisfaction', 'sharing a meal', 'express', 'care', 'time-consuming', 'worth it', 'professional cooking class'. Adequate range. >Band 5: Uses specific words ('experimenting', 'variations'). Not Band 7: Lacks depth.",
        "grammar_reason": "[GRA9] Full range of structures used naturally. 'Which is a creative and relaxing hobby' (Relative clause). 'Experimenting with different ingredients' (Gerund phrase). 'As there are so many...' (Reason clause). 'What I love about cooking is...' (Pseudo-cleft). 'Although it can be...' (Concessive clause). Error-free. >Band 8: Native-like control.",
        "vocabulary": 6,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a hobby you have.\n\nTranscript: I enjoy cooking in my free time, which is a creative and relaxing hobby. I started learning how to cook when I was a teenager. I like experimenting with different ingredients to create new dishes. My favorite thing to make is pasta, as there are so many sauce variations. What I love about cooking is the satisfaction of sharing a meal with friends. It allows me to express my care for them. Although it can be time-consuming, the result is always worth it. I hope to take a professional cooking class in the future.\n\nWord Count: 97 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses topic words: 'experimenting', 'variations', 'satisfaction'. Meaning is clear.\n\n>Band 5: Adequate vocabulary.\n\nNot Band 7: Lacks sophistication.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Uses a full range of structures naturally and accurately. Pseudo-cleft sentences and concessive clauses are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    },
    # 668. V6/G9 - Place (Park)
    {
        "sample_id": "syn_p2_v6_g9_0668",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a park you visit.",
        "transcript_cleaned": "There is a beautiful park near my home that I visit frequently. It is a large green space filled with old trees and colorful flower beds. I go there to jog or simply to sit on a bench and read. The park provides a peaceful escape from the noisy city streets. I often see families having picnics on the grass, which is a lovely sight. In the spring, the flowers are in full bloom, making the park look magical. It is a place where I can relax and clear my mind.",
        "word_count": 94,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR6] Vocabulary: 'beautiful park', 'green space', 'filled with', 'old trees', 'flower beds', 'jog', 'bench', 'peaceful escape', 'noisy city streets', 'picnics', 'grass', 'lovely sight', 'full bloom', 'magical', 'relax', 'clear my mind'. Adequate range. >Band 5: Uses descriptive phrases ('peaceful escape'). Not Band 7: Vocabulary is standard.",
        "grammar_reason": "[GRA9] Full range of structures used naturally. 'That I visit frequently' (Relative clause). 'Filled with old trees...' (Participle phrase). 'To jog or simply to sit...' (Infinitive of purpose). 'Which is a lovely sight' (Relative clause). 'Making the park look magical' (Participle phrase). Error-free. >Band 8: Native-like control.",
        "vocabulary": 6,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a park you visit.\n\nTranscript: There is a beautiful park near my home that I visit frequently. It is a large green space filled with old trees and colorful flower beds. I go there to jog or simply to sit on a bench and read. The park provides a peaceful escape from the noisy city streets. I often see families having picnics on the grass, which is a lovely sight. In the spring, the flowers are in full bloom, making the park look magical. It is a place where I can relax and clear my mind.\n\nWord Count: 94 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses descriptive words: 'peaceful', 'magical', 'bloom'. Clear description.\n\n>Band 5: Good range.\n\nNot Band 7: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Uses a full range of structures naturally and accurately. Participle phrases and relative clauses are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    },
    # 669. V6/G9 - Object (Old)
    {
        "sample_id": "syn_p2_v6_g9_0669",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe an old object you own.",
        "transcript_cleaned": "I possess an old watch that belonged to my grandfather. It is a silver pocket watch with a chain. Although it is quite old, it still works perfectly. I keep it in a special box to protect it from damage. My grandfather gave it to me before he passed away, so it is very sentimental. I admire the craftsmanship and the intricate design on the cover. Whenever I look at it, I remember him. It is not just an object to me; it is a precious family heirloom.",
        "word_count": 91,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR6] Vocabulary: 'possess', 'old watch', 'belonged', 'pocket watch', 'chain', 'works perfectly', 'special box', 'protect', 'damage', 'passed away', 'sentimental', 'admire', 'craftsmanship', 'intricate design', 'cover', 'remember', 'precious', 'heirloom'. Adequate range. >Band 5: Uses specific words ('heirloom', 'craftsmanship'). Not Band 7: Lacks depth.",
        "grammar_reason": "[GRA9] Full range of structures used naturally. 'That belonged to my grandfather' (Relative clause). 'Although it is quite old...' (Concessive clause). 'To protect it from damage' (Infinitive of purpose). 'Before he passed away' (Time clause). 'Not just... but...' (Correlative). Error-free. >Band 8: Native-like control.",
        "vocabulary": 6,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe an old object you own.\n\nTranscript: I possess an old watch that belonged to my grandfather. It is a silver pocket watch with a chain. Although it is quite old, it still works perfectly. I keep it in a special box to protect it from damage. My grandfather gave it to me before he passed away, so it is very sentimental. I admire the craftsmanship and the intricate design on the cover. Whenever I look at it, I remember him. It is not just an object to me; it is a precious family heirloom.\n\nWord Count: 91 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses relevant vocabulary: 'sentimental', 'craftsmanship', 'heirloom'. Clear description.\n\n>Band 5: Good range.\n\nNot Band 7: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Uses a full range of structures naturally and accurately. Concessive clauses and time clauses are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    },
    # 670. V6/G9 - Activity (Exercise)
    {
        "sample_id": "syn_p2_v6_g9_0670",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a sport you play.",
        "transcript_cleaned": "I play tennis on weekends, which is a sport I truly enjoy. I usually play with my brother at a local club. It requires a lot of running and quick movements. I like it because it is competitive and challenging. We often play for two hours, until we are exhausted. Improving my skills, such as serving and volleying, gives me a sense of achievement. I think tennis is a great way to stay fit and healthy. Even though I am not a professional, I try my best to win.",
        "word_count": 92,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR6] Vocabulary: 'tennis', 'local club', 'running', 'quick movements', 'competitive', 'challenging', 'exhausted', 'improving skills', 'serving', 'volleying', 'achievement', 'stay fit', 'healthy', 'professional', 'try my best'. Adequate range. >Band 5: Uses specific words ('serving', 'volleying'). Not Band 7: Vocabulary is standard.",
        "grammar_reason": "[GRA9] Full range of structures used naturally. 'Which is a sport I truly enjoy' (Relative clause). 'Until we are exhausted' (Time clause). 'Improving my skills... gives me...' (Gerund subject). 'Even though I am not...' (Concessive clause). Error-free. >Band 8: Native-like control.",
        "vocabulary": 6,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a sport you play.\n\nTranscript: I play tennis on weekends, which is a sport I truly enjoy. I usually play with my brother at a local club. It requires a lot of running and quick movements. I like it because it is competitive and challenging. We often play for two hours, until we are exhausted. Improving my skills, such as serving and volleying, gives me a sense of achievement. I think tennis is a great way to stay fit and healthy. Even though I am not a professional, I try my best to win.\n\nWord Count: 92 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses topic words: 'competitive', 'volleying', 'achievement'. Meaning is clear.\n\n>Band 5: Adequate vocabulary.\n\nNot Band 7: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Uses a full range of structures naturally and accurately. Gerund subjects and concessive clauses are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    }
]

with open(OUTPUT_FILE, 'a', encoding='utf-8') as f:
    for sample in samples:
        f.write(json.dumps(sample) + '\n')
