import json

OUTPUT_FILE = "ielts-data/phase3/v76_review_output/synthetic_batches/batch_p2_07.jsonl"

samples = [
    # 301. V7/G8 - Job (Dream)
    {
        "sample_id": "syn_p2_v7_g8_0301",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a job you would like to do in the future.",
        "transcript_cleaned": "I aspire to become a marine biologist, a profession that involves deeply studying ocean ecosystems and marine life. I have always been passionate about conservation, and I firmly believe understanding our oceans is pivotal for the planet's future well-being. If I were to pursue this career, I would specifically focus on coral reef restoration projects. The reason I find this job appealing is that it perfectly combines scientific research with active field work. Moreover, the prospect of discovering new species in the deep sea would be incredibly fulfilling for me. Although it requires extensive education and advanced diving skills, I am fully committed to achieving this goal. I envision a future where marine biodiversity is protected and thriving. It would be a dream come true to contribute to this vital cause.",
        "word_count": 133,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "high", "flexibility": "very_high"},
        "vocab_reason": "[LR7] Vocabulary: 'aspire', 'profession', 'ecosystems', 'conservation', 'pivotal', 'restoration', 'appealing', 'fulfilling', 'extensive', 'biodiversity', 'thriving', 'contribute', 'cause'.",
        "grammar_reason": "[GRA8] Wide range. 'If I were to pursue..., I would focus...' (Second Conditional). 'The reason I find... is that...' (Cleft sentence). 'Discovering new species... would be...' (Gerund subject). Accurate.",
        "vocabulary": 7,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a job you would like to do in the future.\n\nTranscript: I aspire to become a marine biologist, a profession that involves deeply studying ocean ecosystems and marine life. I have always been passionate about conservation, and I firmly believe understanding our oceans is pivotal for the planet's future well-being. If I were to pursue this career, I would specifically focus on coral reef restoration projects. The reason I find this job appealing is that it perfectly combines scientific research with active field work. Moreover, the prospect of discovering new species in the deep sea would be incredibly fulfilling for me. Although it requires extensive education and advanced diving skills, I am fully committed to achieving this goal. I envision a future where marine biodiversity is protected and thriving. It would be a dream come true to contribute to this vital cause.\n\nWord Count: 133 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses 'aspire', 'ecosystems', 'pivotal', 'restoration', 'biodiversity'. Shows awareness of style.\n\n>Band 6: More precise and varied.\n\nNot Band 8: Lacks sophistication.\n\n**Idiom present:** Yes ('dream come true')\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Wide range of structures used flexibly. Uses conditionals, cleft sentences, and gerund subjects correctly. Majority of sentences are error-free.\n\n>Band 7: More flexibility.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    },
    # 302. V7/G8 - Law
    {
        "sample_id": "syn_p2_v7_g8_0302",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a law in your country that you think is good.",
        "transcript_cleaned": "I would like to discuss the law banning smoking in public places, which I believe is excellent. This legislation was enacted primarily to protect public health from the dangers of tobacco. Before this law was implemented, second-hand smoke was a major issue in restaurants, parks, and other shared spaces. Since its enforcement, the air quality in these areas has improved significantly, making them much more pleasant. I believe this law is crucial because it safeguards non-smokers from harmful toxins and carcinogens. Although some smokers initially complained about the restriction, most people now accept it as a positive step forward. Had the government not intervened, respiratory diseases would likely be even more prevalent today. It demonstrates how regulations can foster a healthier society. I fully support strict adherence to this rule.",
        "word_count": 134,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "high", "flexibility": "very_high"},
        "vocab_reason": "[LR7] Vocabulary: 'banning', 'legislation', 'enacted', 'implemented', 'enforcement', 'crucial', 'safeguards', 'toxins', 'restriction', 'intervened', 'respiratory', 'prevalent', 'foster', 'adherence'.",
        "grammar_reason": "[GRA8] Wide range. 'Before this law was implemented...' (Passive). 'Since its enforcement, the air quality... has improved' (Present Perfect). 'Had the government not intervened, ... would likely be...' (Third Conditional Inversion). Accurate.",
        "vocabulary": 7,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a law in your country that you think is good.\n\nTranscript: I would like to discuss the law banning smoking in public places, which I believe is excellent. This legislation was enacted primarily to protect public health from the dangers of tobacco. Before this law was implemented, second-hand smoke was a major issue in restaurants, parks, and other shared spaces. Since its enforcement, the air quality in these areas has improved significantly, making them much more pleasant. I believe this law is crucial because it safeguards non-smokers from harmful toxins and carcinogens. Although some smokers initially complained about the restriction, most people now accept it as a positive step forward. Had the government not intervened, respiratory diseases would likely be even more prevalent today. It demonstrates how regulations can foster a healthier society. I fully support strict adherence to this rule.\n\nWord Count: 134 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses 'legislation', 'enacted', 'enforcement', 'safeguards', 'prevalent'. Shows awareness of style.\n\n>Band 6: More precise and varied.\n\nNot Band 8: Lacks sophistication.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Wide range of structures used flexibly. Uses passive voice, perfect tenses, and inverted conditionals correctly. Majority of sentences are error-free.\n\n>Band 7: More flexibility.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    },
    # 303. V7/G8 - Interesting Conversation
    {
        "sample_id": "syn_p2_v7_g8_0303",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe an interesting conversation you had with a stranger.",
        "transcript_cleaned": "I vividly recall a fascinating conversation I had with a backpacker while staying in a hostel in Tokyo. He was a professional photographer from Brazil who had traveled the world. We started talking about travel photography over breakfast in the common room. He shared his unique perspective on capturing the soul of a city rather than just its landmarks. What struck me most was his passion for storytelling through static images. He argued that a good photo should evoke emotion, not just document a scene. Despite the language barrier, we understood each other perfectly through our shared interest in art. He showed me his portfolio, which was absolutely breathtaking. Time flew by as we discussed camera techniques and composition. That encounter inspired me to take my own photography more seriously.",
        "word_count": 133,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "high", "flexibility": "very_high"},
        "vocab_reason": "[LR7] Vocabulary: 'fascinating', 'backpacker', 'perspective', 'capturing', 'soul', 'evoke', 'document', 'portfolio', 'breathtaking', 'composition', 'encounter', 'inspired'.",
        "grammar_reason": "[GRA8] Wide range. 'What struck me was...' (Cleft sentence). 'He argued that a good photo should...' (Reported speech). 'Despite the language barrier...' (Prepositional phrase). 'Which was breathtaking' (Relative clause). Accurate.",
        "vocabulary": 7,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe an interesting conversation you had with a stranger.\n\nTranscript: I vividly recall a fascinating conversation I had with a backpacker while staying in a hostel in Tokyo. He was a professional photographer from Brazil who had traveled the world. We started talking about travel photography over breakfast in the common room. He shared his unique perspective on capturing the soul of a city rather than just its landmarks. What struck me most was his passion for storytelling through static images. He argued that a good photo should evoke emotion, not just document a scene. Despite the language barrier, we understood each other perfectly through our shared interest in art. He showed me his portfolio, which was absolutely breathtaking. Time flew by as we discussed camera techniques and composition. That encounter inspired me to take my own photography more seriously.\n\nWord Count: 133 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses 'perspective', 'evoke', 'document', 'portfolio', 'composition'. Shows awareness of style.\n\n>Band 6: More precise and varied.\n\nNot Band 8: Lacks sophistication.\n\n**Idiom present:** Yes ('Time flew by')\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Wide range of structures used flexibly. Uses cleft sentences, reported speech, and relative clauses correctly. Majority of sentences are error-free.\n\n>Band 7: More flexibility.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    },
    # 304. V7/G8 - Beautiful Place
    {
        "sample_id": "syn_p2_v7_g8_0304",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a beautiful place in your city.",
        "transcript_cleaned": "I would like to describe the Riverfront Park, which is undoubtedly the most scenic spot in my entire city. Located along the banks of the Han River, it serves as a central recreational hub for residents and tourists alike. The park boasts a wide, well-maintained promenade lined with ancient cherry blossom trees. My favorite time to visit is at sunset, characterized by the golden hues reflecting beautifully on the water. Walking along the river, one can truly appreciate the tranquility of nature amidst the urban hustle. It is particularly stunning in spring when the flowers are in full bloom, creating a pink canopy. Were I to recommend a place for a date, this would certainly be my top choice. The preservation of this green space is vital for the city's ecological balance.",
        "word_count": 135,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "high", "flexibility": "very_high"},
        "vocab_reason": "[LR7] Vocabulary: 'undoubtedly', 'scenic', 'banks', 'recreational hub', 'boasts', 'promenade', 'characterized', 'hues', 'tranquility', 'stunning', 'bloom', 'preservation', 'ecological balance'.",
        "grammar_reason": "[GRA8] Wide range. 'Which is undoubtedly...' (Relative clause). 'Located along the banks...' (Participle phrase). 'Characterized by...' (Passive participle). 'Were I to recommend...' (Inverted conditional). Accurate.",
        "vocabulary": 7,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a beautiful place in your city.\n\nTranscript: I would like to describe the Riverfront Park, which is undoubtedly the most scenic spot in my entire city. Located along the banks of the Han River, it serves as a central recreational hub for residents and tourists alike. The park boasts a wide, well-maintained promenade lined with ancient cherry blossom trees. My favorite time to visit is at sunset, characterized by the golden hues reflecting beautifully on the water. Walking along the river, one can truly appreciate the tranquility of nature amidst the urban hustle. It is particularly stunning in spring when the flowers are in full bloom, creating a pink canopy. Were I to recommend a place for a date, this would certainly be my top choice. The preservation of this green space is vital for the city's ecological balance.\n\nWord Count: 135 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses 'scenic', 'recreational hub', 'boasts', 'promenade', 'hues', 'ecological'. Shows awareness of style.\n\n>Band 6: More precise and varied.\n\nNot Band 8: Lacks sophistication.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Wide range of structures used flexibly. Uses participle phrases, passive voice, and inverted conditionals correctly. Majority of sentences are error-free.\n\n>Band 7: More flexibility.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    },
    # 305. V7/G8 - Child
    {
        "sample_id": "syn_p2_v7_g8_0305",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a child you know.",
        "transcript_cleaned": "I would like to talk about my cousin, Ben, who is currently seven years old and living in London. He is an exceptionally bright child with an insatiable curiosity about the world around him. Unlike his peers who mostly enjoy video games, Ben prefers reading encyclopedias and watching documentaries. He is always asking insightful questions about dinosaurs, history, and space exploration. For instance, he recently asked me detailed questions about the extinction of the T-Rex. I am often amazed by his extensive vocabulary and his ability to articulate complex ideas clearly. He is also quite compassionate, always willing to help his younger sister. Watching him learn has been a delightful experience. I believe that with the right guidance, he has the potential to become a great scholar in the future.",
        "word_count": 133,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "high", "flexibility": "very_high"},
        "vocab_reason": "[LR7] Vocabulary: 'exceptionally', 'bright', 'insatiable', 'curiosity', 'peers', 'encyclopedias', 'insightful', 'extinction', 'articulate', 'complex', 'compassionate', 'delightful', 'potential', 'scholar'.",
        "grammar_reason": "[GRA8] Wide range. 'Who is currently...' (Relative clause). 'Unlike his peers who enjoy...' (Contrast + Relative). 'Always asking' (Continuous for habit). 'Watching him learn has been...' (Gerund subject + Present Perfect). Accurate.",
        "vocabulary": 7,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a child you know.\n\nTranscript: I would like to talk about my cousin, Ben, who is currently seven years old and living in London. He is an exceptionally bright child with an insatiable curiosity about the world around him. Unlike his peers who mostly enjoy video games, Ben prefers reading encyclopedias and watching documentaries. He is always asking insightful questions about dinosaurs, history, and space exploration. For instance, he recently asked me detailed questions about the extinction of the T-Rex. I am often amazed by his extensive vocabulary and his ability to articulate complex ideas clearly. He is also quite compassionate, always willing to help his younger sister. Watching him learn has been a delightful experience. I believe that with the right guidance, he has the potential to become a great scholar in the future.\n\nWord Count: 133 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses 'insatiable', 'insightful', 'articulate', 'compassionate'. Shows awareness of style.\n\n>Band 6: More precise and varied.\n\nNot Band 8: Lacks sophistication.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Wide range of structures used flexibly. Uses relative clauses, contrast markers, and gerund subjects correctly. Majority of sentences are error-free.\n\n>Band 7: More flexibility.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    },
    # 306. V7/G8 - Gift (Expensive)
    {
        "sample_id": "syn_p2_v7_g8_0306",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe an expensive gift you would like to give to someone.",
        "transcript_cleaned": "I have always wanted to gift my sister a high-end designer handbag from a famous Italian brand. She has supported me throughout my studies, making countless sacrifices to ensure I succeed in my career. I feel she deserves a luxurious treat to boost her confidence and show her how much I care. I would choose a classic leather bag that is timeless, elegant, and durable. The reason I want to give her this specific gift is that she loves fashion but rarely spends money on herself. Buying such an expensive item would require significant financial planning on my part, but seeing her excitement would be priceless. It is the least I can do to express my deep gratitude for her unconditional love and support over the years.",
        "word_count": 130,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "high", "flexibility": "very_high"},
        "vocab_reason": "[LR7] Vocabulary: 'high-end', 'designer', 'sacrifices', 'succeed', 'luxurious', 'treat', 'classic', 'timeless', 'elegant', 'specific', 'significant', 'financial planning', 'priceless', 'gratitude', 'unconditional'.",
        "grammar_reason": "[GRA8] Wide range. 'Making countless sacrifices...' (Participle phrase). 'The reason I want... is that...' (Cleft sentence). 'But seeing her excitement... would be...' (Gerund subject + Modal). Accurate.",
        "vocabulary": 7,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe an expensive gift you would like to give to someone.\n\nTranscript: I have always wanted to gift my sister a high-end designer handbag from a famous Italian brand. She has supported me throughout my studies, making countless sacrifices to ensure I succeed in my career. I feel she deserves a luxurious treat to boost her confidence and show her how much I care. I would choose a classic leather bag that is timeless, elegant, and durable. The reason I want to give her this specific gift is that she loves fashion but rarely spends money on herself. Buying such an expensive item would require significant financial planning on my part, but seeing her excitement would be priceless. It is the least I can do to express my deep gratitude for her unconditional love and support over the years.\n\nWord Count: 130 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses 'high-end', 'sacrifices', 'luxurious', 'timeless', 'priceless'. Shows awareness of style.\n\n>Band 6: More precise and varied.\n\nNot Band 8: Lacks sophistication.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Wide range of structures used flexibly. Uses participle phrases, cleft sentences, and complex gerund phrases correctly. Majority of sentences are error-free.\n\n>Band 7: More flexibility.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    },
    # 307. V7/G8 - Complaint (Product)
    {
        "sample_id": "syn_p2_v7_g8_0307",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a time you complained about a product.",
        "transcript_cleaned": "I recall purchasing a high-end smartphone online last year that turned out to be defective. Upon receiving it and turning it on, I noticed the battery drained rapidly and the screen flickered incessantly. Naturally, I was exasperated as it was a costly device that I had saved up for. I immediately contacted customer support to file a formal complaint about the quality. I explained the issue clearly, providing screenshots and videos as evidence of the malfunction. Although the agent initially tried to dismiss my claim as user error, I insisted on a full refund. I cited their warranty policy which guarantees a replacement for faulty goods. Eventually, they acknowledged the defect and processed my request. This incident taught me the importance of checking reviews before buying. While it was a frustrating ordeal, the resolution was satisfactory.",
        "word_count": 140,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "high", "flexibility": "very_high"},
        "vocab_reason": "[LR7] Vocabulary: 'defective', 'drained rapidly', 'flickered', 'exasperated', 'costly', 'file a complaint', 'evidence', 'dismiss', 'claim', 'insisted', 'refund', 'cited', 'warranty', 'faulty', 'acknowledged', 'defect', 'ordeal', 'resolution'.",
        "grammar_reason": "[GRA8] Wide range. 'That turned out to be defective' (Relative clause). 'Upon receiving it...' (Prepositional phrase). 'Providing screenshots as evidence' (Participle clause). 'While it was..., the resolution was...' (Contrast). Accurate.",
        "vocabulary": 7,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a time you complained about a product.\n\nTranscript: I recall purchasing a high-end smartphone online last year that turned out to be defective. Upon receiving it and turning it on, I noticed the battery drained rapidly and the screen flickered incessantly. Naturally, I was exasperated as it was a costly device that I had saved up for. I immediately contacted customer support to file a formal complaint about the quality. I explained the issue clearly, providing screenshots and videos as evidence of the malfunction. Although the agent initially tried to dismiss my claim as user error, I insisted on a full refund. I cited their warranty policy which guarantees a replacement for faulty goods. Eventually, they acknowledged the defect and processed my request. This incident taught me the importance of checking reviews before buying. While it was a frustrating ordeal, the resolution was satisfactory.\n\nWord Count: 140 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses 'defective', 'exasperated', 'dismiss', 'insisted', 'warranty', 'ordeal'. Shows awareness of style.\n\n>Band 6: More precise and varied.\n\nNot Band 8: Lacks sophistication.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Wide range of structures used flexibly. Uses relative clauses, participle clauses, and contrast markers correctly. Majority of sentences are error-free.\n\n>Band 7: More flexibility.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    },
    # 308. V7/G8 - Party (Surprise)
    {
        "sample_id": "syn_p2_v7_g8_0308",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a surprise party you organized.",
        "transcript_cleaned": "I organized a surprise farewell party for my colleague, Sarah, who was leaving the company last month. Planning it required meticulous attention to detail to ensure everything went smoothly. I coordinated with my coworkers to book a private room in a nice restaurant and secretly invite everyone. The main challenge was keeping it a secret, as she is very observant and curious. We pretended to have a regular team meeting to get her to the venue. When she walked in, everyone shouted 'Surprise!' in unison. The look of pure astonishment on her face was incredibly rewarding for us. We had prepared a photo collage of her time with us, which was deeply emotional for her. Seeing her surrounded by friends made all the effort worthwhile. It was a memorable send-off that strengthened our team spirit.",
        "word_count": 139,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "high", "flexibility": "very_high"},
        "vocab_reason": "[LR7] Vocabulary: 'farewell', 'meticulous', 'coordinated', 'observant', 'pretended', 'astonishment', 'rewarding', 'collage', 'emotional', 'surrounded', 'worthwhile', 'send-off', 'strengthened', 'spirit'.",
        "grammar_reason": "[GRA8] Wide range. 'Planning it required...' (Gerund subject). 'The challenge was keeping it a secret, as...' (Reason clause). 'Which was deeply emotional' (Non-defining relative clause). 'Seeing her surrounded... made...' (Gerund subject). Accurate.",
        "vocabulary": 7,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a surprise party you organized.\n\nTranscript: I organized a surprise farewell party for my colleague, Sarah, who was leaving the company last month. Planning it required meticulous attention to detail to ensure everything went smoothly. I coordinated with my coworkers to book a private room in a nice restaurant and secretly invite everyone. The main challenge was keeping it a secret, as she is very observant and curious. We pretended to have a regular team meeting to get her to the venue. When she walked in, everyone shouted 'Surprise!' in unison. The look of pure astonishment on her face was incredibly rewarding for us. We had prepared a photo collage of her time with us, which was deeply emotional for her. Seeing her surrounded by friends made all the effort worthwhile. It was a memorable send-off that strengthened our team spirit.\n\nWord Count: 139 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses 'meticulous', 'observant', 'astonishment', 'collage', 'worthwhile', 'send-off'. Shows awareness of style.\n\n>Band 6: More precise and varied.\n\nNot Band 8: Lacks sophistication.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Wide range of structures used flexibly. Uses gerund subjects and non-defining relative clauses correctly. Majority of sentences are error-free.\n\n>Band 7: More flexibility.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    },
    # 309. V7/G8 - Website (Learning)
    {
        "sample_id": "syn_p2_v7_g8_0309",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a website that helps you in your studies.",
        "transcript_cleaned": "I frequently use a website called Khan Academy, which offers comprehensive online courses on various academic subjects. It is an invaluable resource for supplementing my school lessons and clarifying difficult topics. What distinguishes this platform from others is the high quality of its instructional videos, which are delivered by experts. I have taken several courses on math and history there. The interface is intuitive, allowing for seamless navigation between different modules. One feature I particularly appreciate is the interactive practice exercises, which provide instant feedback on my answers. It encourages self-paced learning, which suits my style. Furthermore, the ability to track my progress over time is a major advantage. Thanks to this website, I have acquired a deeper understanding of complex concepts. I would highly recommend it to anyone seeking to improve their grades.",
        "word_count": 139,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "high", "flexibility": "very_high"},
        "vocab_reason": "[LR7] Vocabulary: 'frequently', 'invaluable', 'supplementing', 'distinguishes', 'platform', 'instructional', 'interface', 'intuitive', 'seamless', 'navigation', 'appreciate', 'feedback', 'self-paced', 'track', 'acquired', 'concepts'.",
        "grammar_reason": "[GRA8] Wide range. 'Which offers online courses...' (Relative clause). 'What distinguishes this platform is...' (Pseudo-cleft). 'Allowing for seamless navigation' (Participle phrase). 'Seeking to improve...' (Participle). Accurate.",
        "vocabulary": 7,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a website that helps you in your studies.\n\nTranscript: I frequently use a website called Khan Academy, which offers comprehensive online courses on various academic subjects. It is an invaluable resource for supplementing my school lessons and clarifying difficult topics. What distinguishes this platform from others is the high quality of its instructional videos, which are delivered by experts. I have taken several courses on math and history there. The interface is intuitive, allowing for seamless navigation between different modules. One feature I particularly appreciate is the interactive practice exercises, which provide instant feedback on my answers. It encourages self-paced learning, which suits my style. Furthermore, the ability to track my progress over time is a major advantage. Thanks to this website, I have acquired a deeper understanding of complex concepts. I would highly recommend it to anyone seeking to improve their grades.\n\nWord Count: 139 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses 'invaluable', 'supplementing', 'distinguishes', 'intuitive', 'seamless', 'self-paced'. Shows awareness of style.\n\n>Band 6: More precise and varied.\n\nNot Band 8: Lacks sophistication.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Wide range of structures used flexibly. Uses relative clauses, pseudo-cleft sentences, and participle phrases correctly. Majority of sentences are error-free.\n\n>Band 7: More flexibility.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    },
    # 310. V7/G8 - City (Change)
    {
        "sample_id": "syn_p2_v7_g8_0310",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a change in your city that you think is positive.",
        "transcript_cleaned": "A significant positive change in my city is the recent creation of pedestrian zones in the busy downtown area. Before this initiative, traffic congestion was a chronic issue, causing frustration for shoppers and residents alike. The prohibition of vehicles in these streets has alleviated this problem substantially. It provides a safe, pollution-free environment for people to walk, relax, and socialize. I have noticed a visible reduction in noise levels since the change was implemented. Additionally, the streets are now lined with outdoor cafes and trees, enhancing the city's aesthetic appeal. This development has not only improved the quality of life but also stimulated local businesses by attracting more foot traffic. I believe this move demonstrates the council's commitment to sustainable urban living and prioritizing people over cars.",
        "word_count": 139,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "high", "flexibility": "very_high"},
        "vocab_reason": "[LR7] Vocabulary: 'significant', 'creation', 'pedestrian zones', 'initiative', 'chronic', 'congestion', 'frustration', 'prohibition', 'alleviated', 'substantially', 'socialize', 'reduction', 'aesthetic', 'appeal', 'stimulated', 'commitment', 'sustainable'.",
        "grammar_reason": "[GRA8] Wide range. 'Before this initiative, traffic... was...' (Prepositional phrase). 'Causing frustration for shoppers' (Participle phrase). 'This development has not only improved..., but also stimulated...' (Correlative conjunction). Accurate.",
        "vocabulary": 7,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a change in your city that you think is positive.\n\nTranscript: A significant positive change in my city is the recent creation of pedestrian zones in the busy downtown area. Before this initiative, traffic congestion was a chronic issue, causing frustration for shoppers and residents alike. The prohibition of vehicles in these streets has alleviated this problem substantially. It provides a safe, pollution-free environment for people to walk, relax, and socialize. I have noticed a visible reduction in noise levels since the change was implemented. Additionally, the streets are now lined with outdoor cafes and trees, enhancing the city's aesthetic appeal. This development has not only improved the quality of life but also stimulated local businesses by attracting more foot traffic. I believe this move demonstrates the council's commitment to sustainable urban living and prioritizing people over cars.\n\nWord Count: 139 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses 'chronic', 'congestion', 'prohibition', 'alleviated', 'aesthetic', 'stimulated', 'sustainable'. Shows awareness of style.\n\n>Band 6: More precise and varied.\n\nNot Band 8: Lacks sophistication.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Wide range of structures used flexibly. Uses participle phrases and correlative conjunctions correctly. Majority of sentences are error-free.\n\n>Band 7: More flexibility.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    }
]

with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
    for sample in samples:
        f.write(json.dumps(sample) + '\n')
