import json

OUTPUT_FILE = "ielts-data/phase3/v76_review_output/synthetic_batches/batch_p2_13.jsonl"

samples = [
    # 641. V4/G7 - Book (Read)
    {
        "sample_id": "syn_p2_v4_g7_0641",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a book you read at school.",
        "transcript_cleaned": "I read a book called 'Romeo and Juliet' at school. It is a famous play. The story is about a boy and a girl. They love each other, but their families fight. I liked the book because it was sad. Although the language was old, I understood the story. The teacher explained the difficult words. If I could, I would watch the movie. It is a good book about love. I think everyone should read it.",
        "word_count": 86,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR4] Limited range: 'book', 'play', 'story', 'boy', 'girl', 'love', 'fight', 'sad', 'language', 'old', 'understood', 'teacher', 'explained', 'difficult words', 'watch movie', 'good'. Basic vocabulary. >Band 3: Clear description. Not Band 5: Minimal variation.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'Because it was sad' (Reason clause). 'Although the language was old...' (Concessive clause). 'If I could, I would watch...' (Second conditional). 'I think everyone should read it' (Noun clause). Accurate. >Band 6: Good control. Not Band 8: Limited by vocabulary.",
        "vocabulary": 4,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a book you read at school.\n\nTranscript: I read a book called 'Romeo and Juliet' at school. It is a famous play. The story is about a boy and a girl. They love each other, but their families fight. I liked the book because it was sad. Although the language was old, I understood the story. The teacher explained the difficult words. If I could, I would watch the movie. It is a good book about love. I think everyone should read it.\n\nWord Count: 86 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Basic vocabulary: 'boy', 'girl', 'love', 'sad'. Simple description. No range.\n\n>Band 3: Basic meaning.\n\nNot Band 5: Lacks descriptive words.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures like concessive clauses and second conditional correctly. Good grammatical control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Limited by vocabulary.\n\n**Micro flaws identified:**\n- None."
    },
    # 642. V7/G4 - Place (Town)
    {
        "sample_id": "syn_p2_v7_g4_0642",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a town you want to live in.",
        "transcript_cleaned": "I want live in Queenstown, New Zealand. It is picturesque town. It is surrounded by majestic mountains. The lake is crystal clear. I see photos of it. It look breathtaking. I want to try bungee jumping, which is thrilling. The scenery is spectacular. It is popular destination for tourists. However, accommodation is pricey. I need save money. The atmosphere is vibrant. It is paradise for nature lovers. I hope go there one day.",
        "word_count": 86,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'want live' should be 'want to live'", "article: 'picturesque town' should be 'a picturesque town'", "tense: 'I see' should be 'I have seen'", "agreement: 'It look' should be 'It looks'", "article: 'popular destination' should be 'a popular destination'", "grammar: 'need save' should be 'need to save'", "article: 'is paradise' should be 'is a paradise'", "grammar: 'hope go' should be 'hope to go'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR7] Vocabulary: 'picturesque', 'majestic mountains', 'crystal clear', 'breathtaking', 'bungee jumping', 'thrilling', 'scenery', 'spectacular', 'destination', 'accommodation', 'pricey', 'atmosphere', 'vibrant', 'paradise', 'nature lovers'. Sophisticated descriptors. >Band 6: Precise vocabulary. Not Band 8: Errors in usage.",
        "grammar_reason": "[GRA4] Only simple sentences. Systematic errors in verbs ('want live', 'hope go'), agreement ('It look'), and articles. >Band 3: Basic meaning clear. Not Band 5: Errors are pervasive.",
        "vocabulary": 7,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a town you want to live in.\n\nTranscript: I want live in Queenstown, New Zealand. It is picturesque town. It is surrounded by majestic mountains. The lake is crystal clear. I see photos of it. It look breathtaking. I want to try bungee jumping, which is thrilling. The scenery is spectacular. It is popular destination. However, accommodation is pricey. I need save money. The atmosphere is vibrant. It is paradise for nature lovers. I hope go there one day.\n\nWord Count: 86 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses sophisticated words: 'majestic', 'crystal clear', 'spectacular'. Good range.\n\n>Band 6: Advanced vocabulary.\n\nNot Band 8: Lacks native flow.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Simple sentences. Frequent errors in verbs and articles. Strain for listener.\n\n>Band 3: Simple structures.\n\nNot Band 5: Systematic errors.\n\n**Micro flaws identified:**\n- 'want live' should be 'want to live'\n- 'picturesque town' should be 'a picturesque town'\n- 'I see' should be 'I have seen'\n- 'It look' should be 'It looks'\n- 'popular destination' should be 'a popular destination'\n- 'need save' should be 'need to save'\n- 'is paradise' should be 'is a paradise'\n- 'hope go' should be 'hope to go'"
    },
    # 643. V5/G8 - Activity (Daily)
    {
        "sample_id": "syn_p2_v5_g8_0643",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a way you relax.",
        "transcript_cleaned": "I relax by listening to music in my bedroom. It is a simple activity, but it helps me a lot. I usually listen to classical music because it is calm. I lie on my bed and close my eyes. While I listen, I forget about my problems. It makes me feel peaceful and happy. I have been doing this for many years. Even if I have a busy day, I always find time for music. It is the best way to end the day.",
        "word_count": 97,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR5] Vocabulary: 'relax', 'listening to music', 'simple activity', 'classical music', 'calm', 'lie', 'close eyes', 'forget', 'problems', 'peaceful', 'happy', 'busy day', 'find time', 'end the day'. Functional vocabulary relevant to the topic. >Band 4: Uses some specific words ('classical'). Not Band 6: Simple vocabulary.",
        "grammar_reason": "[GRA8] Wide range of structures used accurately. 'By listening to music' (Prepositional phrase). 'Because it is calm' (Reason clause). 'While I listen...' (Time clause). 'Even if I have a busy day...' (Concessive clause). Error-free. >Band 7: More variety.",
        "vocabulary": 5,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a way you relax.\n\nTranscript: I relax by listening to music in my bedroom. It is a simple activity, but it helps me a lot. I usually listen to classical music because it is calm. I lie on my bed and close my eyes. While I listen, I forget about my problems. It makes me feel peaceful and happy. I have been doing this for many years. Even if I have a busy day, I always find time for music. It is the best way to end the day.\n\nWord Count: 97 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses topic words: 'classical', 'peaceful'. Meaning is clear.\n\n>Band 4: Adequate vocabulary.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Uses complex structures accurately (concessive clauses, time clauses). Sentences are error-free.\n\n>Band 7: High accuracy.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    },
    # 644. V4/G7 - Person (Teacher)
    {
        "sample_id": "syn_p2_v4_g7_0644",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a teacher from your past.",
        "transcript_cleaned": "I remember a teacher named Mr. White. He taught me math. He was a tall man with glasses. I liked him because he was funny. He made jokes in class. Although math was hard, he made it easy. He explained the numbers well. If I had a question, he answered it. He was kind to all the students. I think he was a good teacher. I learned a lot from him.",
        "word_count": 82,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR4] Limited range: 'teacher', 'math', 'tall', 'glasses', 'funny', 'jokes', 'hard', 'easy', 'explained', 'numbers', 'question', 'answered', 'kind', 'students', 'good', 'learned'. Basic vocabulary. >Band 3: Clear description. Not Band 5: Minimal variation.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'Because he was funny' (Reason clause). 'Although math was hard...' (Concessive clause). 'If I had a question...' (First conditional in past context). Accurate. >Band 6: Good control. Not Band 8: Limited by vocabulary.",
        "vocabulary": 4,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a teacher from your past.\n\nTranscript: I remember a teacher named Mr. White. He taught me math. He was a tall man with glasses. I liked him because he was funny. He made jokes in class. Although math was hard, he made it easy. He explained the numbers well. If I had a question, he answered it. He was kind to all the students. I think he was a good teacher. I learned a lot from him.\n\nWord Count: 82 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Basic vocabulary: 'funny', 'hard', 'easy'. Simple description. No range.\n\n>Band 3: Basic meaning.\n\nNot Band 5: Lacks descriptive words.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures like concessive clauses and conditionals correctly. Good control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Limited by vocabulary.\n\n**Micro flaws identified:**\n- None."
    },
    # 645. V7/G4 - Event (Sport)
    {
        "sample_id": "syn_p2_v7_g4_0645",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a sports event you want to watch.",
        "transcript_cleaned": "I want watch the Super Bowl in America. It is massive sporting event. It is famous for halftime show. The atmosphere is electric. I see it on TV. The stadium is colossal. The players is elite athletes. It is spectacle of entertainment. I want to experience the excitement. The tickets is very expensive. I need save lot of money. It is bucket list item for me. I think it be unforgettable.",
        "word_count": 81,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'want watch' should be 'want to watch'", "article: 'massive sporting event' should be 'a massive sporting event'", "article: 'famous for halftime show' should be 'famous for the halftime show'", "agreement: 'players is' should be 'players are'", "article: 'is spectacle' should be 'is a spectacle'", "agreement: 'tickets is' should be 'tickets are'", "grammar: 'need save' should be 'need to save'", "article: 'bucket list item' should be 'a bucket list item'", "grammar: 'it be' should be 'it would be'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR7] Vocabulary: 'massive', 'sporting event', 'halftime show', 'atmosphere', 'electric', 'colossal', 'elite athletes', 'spectacle', 'entertainment', 'experience', 'excitement', 'expensive', 'bucket list', 'unforgettable'. Sophisticated descriptors. >Band 6: Precise vocabulary. Not Band 8: Errors in usage.",
        "grammar_reason": "[GRA4] Only simple sentences. Systematic errors in verbs ('want watch', 'need save'), agreement ('players is', 'tickets is'), and articles. >Band 3: Basic meaning clear. Not Band 5: Errors are pervasive.",
        "vocabulary": 7,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a sports event you want to watch.\n\nTranscript: I want watch the Super Bowl in America. It is massive sporting event. It is famous for halftime show. The atmosphere is electric. I see it on TV. The stadium is colossal. The players is elite athletes. It is spectacle of entertainment. I want to experience the excitement. The tickets is very expensive. I need save lot of money. It is bucket list item for me. I think it be unforgettable.\n\nWord Count: 81 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses sophisticated words: 'colossal', 'elite', 'spectacle'. Good range.\n\n>Band 6: Advanced vocabulary.\n\nNot Band 8: Lacks native flow.\n\n**Idiom present:** Yes ('bucket list')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Simple sentences. Frequent errors in verbs and articles. Strain for listener.\n\n>Band 3: Simple structures.\n\nNot Band 5: Systematic errors.\n\n**Micro flaws identified:**\n- 'want watch' should be 'want to watch'\n- 'massive sporting event' should be 'a massive sporting event'\n- 'famous for halftime show' should be 'famous for the halftime show'\n- 'players is' should be 'players are'\n- 'is spectacle' should be 'is a spectacle'\n- 'tickets is' should be 'tickets are'\n- 'need save' should be 'need to save'\n- 'bucket list item' should be 'a bucket list item'\n- 'it be' should be 'it would be'"
    },
    # 646. V5/G8 - Object (Old)
    {
        "sample_id": "syn_p2_v5_g8_0646",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe an old thing in your house.",
        "transcript_cleaned": "We have an old clock in our living room that belonged to my grandfather. It is made of dark wood and has a glass door. It is very heavy and tall. My father winds it up every Sunday morning. I like the sound it makes when it chimes. It reminds me of my grandfather, who was a kind man. Although it is old, it still keeps good time. We have to be careful with it because it is fragile. It is a special object for our family.",
        "word_count": 99,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR5] Vocabulary: 'old clock', 'living room', 'belonged', 'dark wood', 'glass door', 'heavy', 'winds it up', 'chimes', 'reminds', 'kind', 'keeps good time', 'careful', 'fragile', 'special object'. Functional vocabulary relevant to the topic. >Band 4: Uses some specific words ('chimes', 'fragile'). Not Band 6: Simple vocabulary.",
        "grammar_reason": "[GRA8] Wide range of structures used accurately. 'That belonged to my grandfather' (Relative clause). 'When it chimes' (Time clause). 'Who was a kind man' (Relative clause). 'Although it is old...' (Concessive clause). 'Because it is fragile' (Reason clause). Error-free. >Band 7: More variety.",
        "vocabulary": 5,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe an old thing in your house.\n\nTranscript: We have an old clock in our living room that belonged to my grandfather. It is made of dark wood and has a glass door. It is very heavy and tall. My father winds it up every Sunday morning. I like the sound it makes when it chimes. It reminds me of my grandfather, who was a kind man. Although it is old, it still keeps good time. We have to be careful with it because it is fragile. It is a special object for our family.\n\nWord Count: 99 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses topic words: 'chimes', 'fragile', 'winds up'. Meaning is clear.\n\n>Band 4: Adequate vocabulary.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Uses complex structures accurately (relative clauses, concessive clauses). Sentences are error-free.\n\n>Band 7: High accuracy.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    },
    # 647. V4/G7 - Event (Sport)
    {
        "sample_id": "syn_p2_v4_g7_0647",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a game you watched.",
        "transcript_cleaned": "I watched a football game last month. It was on TV. My favorite team played. I watched it with my brother. The game was very exciting. The players ran fast and kicked the ball. One player scored a goal. We shouted because we were happy. Although the other team tried hard, they did not win. My team won the game. It was a good night. I like watching football because it is fun.",
        "word_count": 83,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR4] Limited range: 'football game', 'TV', 'team', 'played', 'brother', 'exciting', 'ran fast', 'kicked', 'ball', 'scored a goal', 'shouted', 'happy', 'tried hard', 'win', 'won', 'good', 'fun'. Basic vocabulary. >Band 3: Clear narrative. Not Band 5: Minimal variation.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'Because we were happy' (Reason clause). 'Although the other team tried hard...' (Concessive clause). 'Because it is fun' (Reason clause). Accurate past tense usage. >Band 6: Good control. Not Band 8: Limited by vocabulary.",
        "vocabulary": 4,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a game you watched.\n\nTranscript: I watched a football game last month. It was on TV. My favorite team played. I watched it with my brother. The game was very exciting. The players ran fast and kicked the ball. One player scored a goal. We shouted because we were happy. Although the other team tried hard, they did not win. My team won the game. It was a good night. I like watching football because it is fun.\n\nWord Count: 83 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Basic vocabulary: 'game', 'goal', 'win'. Simple story. No range.\n\n>Band 3: Basic narrative.\n\nNot Band 5: Lacks descriptive words.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures like concessive clauses and reason clauses correctly. Good control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Limited by vocabulary.\n\n**Micro flaws identified:**\n- None."
    },
    # 648. V7/G4 - Activity (Exercise)
    {
        "sample_id": "syn_p2_v7_g4_0648",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe an exercise you enjoy.",
        "transcript_cleaned": "I enjoy Pilates, which is low-impact exercise. It focus on core strength and flexibility. I attend classes at local studio. I wear comfortable attire. The movements is precise and controlled. I concentrating on my breathing. It help me alleviate stress. I feel rejuvenated after class. My posture improve significantly. It is holistic approach to fitness. I recommend it to people with back pain. It is beneficial practice.",
        "word_count": 78,
        "response_type": "long_turn",
        "micro_flaws": ["article: 'low-impact exercise' should be 'a low-impact exercise'", "agreement: 'It focus' should be 'It focuses'", "article: 'at local studio' should be 'at a local studio'", "agreement: 'movements is' should be 'movements are'", "grammar: 'I concentrating' should be 'I concentrate'", "agreement: 'It help' should be 'It helps'", "agreement: 'posture improve' should be 'posture improves'", "article: 'holistic approach' should be 'a holistic approach'", "article: 'beneficial practice' should be 'a beneficial practice'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR7] Vocabulary: 'Pilates', 'low-impact', 'core strength', 'flexibility', 'attire', 'precise', 'controlled', 'concentrating', 'breathing', 'alleviate stress', 'rejuvenated', 'posture', 'significantly', 'holistic approach', 'fitness', 'recommend', 'back pain', 'beneficial'. Sophisticated descriptors. >Band 6: Precise vocabulary. Not Band 8: Errors in usage.",
        "grammar_reason": "[GRA4] Only simple sentences. Systematic errors in agreement ('It focus', 'movements is', 'It help', 'posture improve') and articles. >Band 3: Basic meaning clear. Not Band 5: Errors are pervasive.",
        "vocabulary": 7,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe an exercise you enjoy.\n\nTranscript: I enjoy Pilates, which is low-impact exercise. It focus on core strength and flexibility. I attend classes at local studio. I wear comfortable attire. The movements is precise and controlled. I concentrating on my breathing. It help me alleviate stress. I feel rejuvenated after class. My posture improve significantly. It is holistic approach to fitness. I recommend it to people with back pain. It is beneficial practice.\n\nWord Count: 78 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses sophisticated words: 'low-impact', 'alleviate', 'rejuvenated', 'holistic'. Good range.\n\n>Band 6: Advanced vocabulary.\n\nNot Band 8: Lacks native flow.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Simple sentences. Frequent errors in agreement and articles. Strain for listener.\n\n>Band 3: Simple structures.\n\nNot Band 5: Systematic errors.\n\n**Micro flaws identified:**\n- 'low-impact exercise' should be 'a low-impact exercise'\n- 'It focus' should be 'It focuses'\n- 'at local studio' should be 'at a local studio'\n- 'movements is' should be 'movements are'\n- 'I concentrating' should be 'I concentrate'\n- 'It help' should be 'It helps'\n- 'posture improve' should be 'posture improves'\n- 'holistic approach' should be 'a holistic approach'\n- 'beneficial practice' should be 'a beneficial practice'"
    },
    # 649. V5/G8 - Event (Celebration)
    {
        "sample_id": "syn_p2_v5_g8_0649",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a party you want to have.",
        "transcript_cleaned": "I would like to have a barbecue party for my graduation. It would be held in my garden on a sunny day. I would invite all my friends and family members. We would grill meat and vegetables, which everyone likes. I would also buy some drinks and snacks. Playing music is important, so I would prepare a playlist. People could dance and talk. If it rains, we would move inside the house. I want everyone to have a good time. It would be a perfect way to celebrate my success.",
        "word_count": 99,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR5] Vocabulary: 'barbecue party', 'graduation', 'held', 'garden', 'sunny', 'invite', 'grill meat', 'vegetables', 'drinks', 'snacks', 'playlist', 'dance', 'move inside', 'good time', 'celebrate', 'success'. Functional vocabulary relevant to the topic. >Band 4: Uses some specific words ('grill', 'playlist'). Not Band 6: Simple vocabulary.",
        "grammar_reason": "[GRA8] Wide range of structures used accurately. 'It would be held...' (Passive modal). 'Which everyone likes' (Relative clause). 'Playing music is important' (Gerund subject). 'So I would prepare...' (Result clause). 'If it rains, we would move...' (First/Second conditional mix - acceptable in context). Error-free. >Band 7: More variety.",
        "vocabulary": 5,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a party you want to have.\n\nTranscript: I would like to have a barbecue party for my graduation. It would be held in my garden on a sunny day. I would invite all my friends and family members. We would grill meat and vegetables, which everyone likes. I would also buy some drinks and snacks. Playing music is important, so I would prepare a playlist. People could dance and talk. If it rains, we would move inside the house. I want everyone to have a good time. It would be a perfect way to celebrate my success.\n\nWord Count: 99 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses topic words: 'grill', 'playlist', 'celebrate'. Meaning is clear.\n\n>Band 4: Adequate vocabulary.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Uses complex structures accurately (conditionals, relative clauses). Sentences are error-free.\n\n>Band 7: High accuracy.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    },
    # 650. V7/G4 - Object (Gift)
    {
        "sample_id": "syn_p2_v7_g4_0650",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a gift you made.",
        "transcript_cleaned": "I make scrapbook for my sister. It was personalized gift. I use colored paper and stickers. I paste many photos of us. I write captions for each photo. It take me three days. I want to creating something meaningful. It show our memories together. When she open it, she cry tears of joy. She cherish it very much. It was labor of love. I am proud of my creativity. It is better than bought gift.",
        "word_count": 84,
        "response_type": "long_turn",
        "micro_flaws": ["tense: 'I make' should be 'I made'", "article: 'make scrapbook' should be 'made a scrapbook'", "article: 'personalized gift' should be 'a personalized gift'", "tense: 'I use' should be 'I used'", "tense: 'I paste' should be 'I pasted'", "tense: 'I write' should be 'I wrote'", "agreement: 'It take' should be 'It took'", "grammar: 'want to creating' should be 'wanted to create'", "agreement: 'It show' should be 'It showed'", "tense: 'she open' should be 'she opened'", "tense: 'she cry' should be 'she cried'", "agreement: 'She cherish' should be 'She cherishes' (or cherished)", "article: 'labor of love' should be 'a labor of love'", "article: 'bought gift' should be 'a bought gift'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR7] Vocabulary: 'scrapbook', 'personalized', 'stickers', 'paste', 'captions', 'meaningful', 'memories', 'tears of joy', 'cherish', 'labor of love', 'creativity'. Sophisticated descriptors. >Band 6: Precise vocabulary. Not Band 8: Errors in usage.",
        "grammar_reason": "[GRA4] Only simple sentences. Systematic errors in tense ('make', 'use', 'paste', 'write', 'open', 'cry'), agreement ('It take', 'It show'), and articles. >Band 3: Basic meaning clear. Not Band 5: Errors are pervasive.",
        "vocabulary": 7,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a gift you made.\n\nTranscript: I make scrapbook for my sister. It was personalized gift. I use colored paper and stickers. I paste many photos of us. I write captions for each photo. It take me three days. I want to creating something meaningful. It show our memories together. When she open it, she cry tears of joy. She cherish it very much. It was labor of love. I am proud of my creativity. It is better than bought gift.\n\nWord Count: 84 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses sophisticated words: 'personalized', 'captions', 'cherish'. Good range.\n\n>Band 6: Advanced vocabulary.\n\nNot Band 8: Lacks native flow.\n\n**Idiom present:** Yes ('tears of joy', 'labor of love')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Simple sentences. Frequent errors in tense and articles. Strain for listener.\n\n>Band 3: Simple structures.\n\nNot Band 5: Systematic errors.\n\n**Micro flaws identified:**\n- 'I make' should be 'I made'\n- 'make scrapbook' should be 'made a scrapbook'\n- 'personalized gift' should be 'a personalized gift'\n- 'I use' should be 'I used'\n- 'I paste' should be 'I pasted'\n- 'I write' should be 'I wrote'\n- 'It take' should be 'It took'\n- 'want to creating' should be 'wanted to create'\n- 'It show' should be 'It showed'\n- 'she open' should be 'she opened'\n- 'she cry' should be 'she cried'\n- 'She cherish' should be 'She cherishes'\n- 'labor of love' should be 'a labor of love'\n- 'bought gift' should be 'a bought gift'"
    }
]

with open(OUTPUT_FILE, 'a', encoding='utf-8') as f:
    for sample in samples:
        f.write(json.dumps(sample) + '\n')
