import json

OUTPUT_FILE = "ielts-data/phase3/v76_review_output/synthetic_batches/batch_p2_10.jsonl"

samples = [
    # 461. V6/G6 - Movie (Liked)
    {
        "sample_id": "syn_p2_v6_g6_0461",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a movie you liked.",
        "transcript_cleaned": "I really enjoyed watching 'The Lion King', which is an animated movie. It tells the story of a young lion named Simba. The animation is colorful and realistic. I liked the music very much, especially the opening song. The characters are interesting, particularly the funny meerkat and warthog. The movie has a good message about responsibility and family. I watched it with my younger brother, and he loved it too. Although it is a children's movie, adults can enjoy it as well. It made me feel happy and nostalgic.",
        "word_count": 91,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR6] Vocabulary: 'animated movie', 'realistic', 'characters', 'message', 'responsibility', 'nostalgic'. Good range. >Band 5: Clear descriptions. Not Band 7: Lacks sophisticated idioms.",
        "grammar_reason": "[GRA6] Uses a mix of simple and complex structures accurately. 'Which is an animated movie' (Relative clause). 'Although it is...' (Concessive clause). >Band 5: Uses complex structures correctly. Not Band 7: Range is somewhat limited.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a movie you liked.\n\nTranscript: I really enjoyed watching 'The Lion King', which is an animated movie. It tells the story of a young lion named Simba. The animation is colorful and realistic. I liked the music very much, especially the opening song. The characters are interesting, particularly the funny meerkat and warthog. The movie has a good message about responsibility and family. I watched it with my younger brother, and he loved it too. Although it is a children's movie, adults can enjoy it as well. It made me feel happy and nostalgic.\n\nWord Count: 91 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses relevant vocabulary: 'animated', 'realistic', 'nostalgic'. Clear and descriptive.\n\n>Band 5: Good range.\n\nNot Band 7: Lacks depth.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Uses complex structures like relative clauses and concessive clauses accurately. Good control.\n\n>Band 5: Error-free sentences.\n\nNot Band 7: Structure variety is limited.\n\n**Micro flaws identified:**\n- None."
    },
    # 462. V6/G6 - Place (City)
    {
        "sample_id": "syn_p2_v6_g6_0462",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a city you have visited.",
        "transcript_cleaned": "I visited Barcelona last summer, which is a beautiful city in Spain. The architecture is unique, especially the buildings designed by Gaudi. I spent hours walking around the Gothic Quarter. The food was amazing, particularly the tapas and paella. I loved the lively atmosphere of the city. There were street performers everywhere. I also visited the beach, which was very clean. Although it was crowded, I had a great time. I think Barcelona is a perfect destination for a holiday. I hope to go back there someday.",
        "word_count": 89,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR6] Vocabulary: 'architecture', 'unique', 'designed', 'lively atmosphere', 'performers', 'destination'. Adequate range. >Band 5: Clear descriptions. Not Band 7: Vocabulary is standard.",
        "grammar_reason": "[GRA6] Uses a mix of simple and complex structures. 'Which is a beautiful city' (Relative clause). 'Designed by Gaudi' (Participle phrase). 'Although it was crowded...' (Concessive clause). Generally error-free. >Band 5: Uses complex structures accurately. Not Band 7: Limited range.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a city you have visited.\n\nTranscript: I visited Barcelona last summer, which is a beautiful city in Spain. The architecture is unique, especially the buildings designed by Gaudi. I spent hours walking around the Gothic Quarter. The food was amazing, particularly the tapas and paella. I loved the lively atmosphere of the city. There were street performers everywhere. I also visited the beach, which was very clean. Although it was crowded, I had a great time. I think Barcelona is a perfect destination for a holiday. I hope to go back there someday.\n\nWord Count: 89 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses topic words: 'architecture', 'atmosphere', 'destination'. Meaning is clear.\n\n>Band 5: Adequate vocabulary.\n\nNot Band 7: Lacks sophistication.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Uses complex structures accurately. Includes relative clauses and participle phrases.\n\n>Band 5: Good control of complex forms.\n\nNot Band 7: Range is limited.\n\n**Micro flaws identified:**\n- None."
    },
    # 463. V6/G6 - Object (Gift)
    {
        "sample_id": "syn_p2_v6_g6_0463",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a gift you gave to someone.",
        "transcript_cleaned": "I gave my mother a necklace for her birthday. It was a silver necklace with a small heart pendant. I bought it from a jewelry store in the mall. I chose it because my mother loves silver jewelry. She was very surprised when she opened the box. She put it on immediately and looked in the mirror. She said it was the best gift she had ever received. I felt very happy to see her smile. Giving gifts is a nice way to show love.",
        "word_count": 87,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR6] Vocabulary: 'necklace', 'pendant', 'jewelry store', 'surprised', 'immediately', 'received', 'show love'. Adequate range. >Band 5: Clear descriptions. Not Band 7: Vocabulary is simple.",
        "grammar_reason": "[GRA6] Uses a mix of simple and complex structures. 'Because my mother loves...' (Reason clause). 'When she opened the box' (Time clause). 'Best gift she had ever received' (Relative clause + Past Perfect). Generally error-free. >Band 5: Uses complex structures accurately. Not Band 7: Limited range.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a gift you gave to someone.\n\nTranscript: I gave my mother a necklace for her birthday. It was a silver necklace with a small heart pendant. I bought it from a jewelry store in the mall. I chose it because my mother loves silver jewelry. She was very surprised when she opened the box. She put it on immediately and looked in the mirror. She said it was the best gift she had ever received. I felt very happy to see her smile. Giving gifts is a nice way to show love.\n\nWord Count: 87 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses relevant vocabulary: 'pendant', 'jewelry'. Clear description.\n\n>Band 5: Good range.\n\nNot Band 7: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Uses complex structures accurately. Includes time clauses and past perfect tense.\n\n>Band 5: Good control of complex forms.\n\nNot Band 7: Range is limited.\n\n**Micro flaws identified:**\n- None."
    },
    # 464. V6/G6 - Person (Famous)
    {
        "sample_id": "syn_p2_v6_g6_0464",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a famous person you admire.",
        "transcript_cleaned": "I admire Elon Musk, who is a famous entrepreneur. He is the CEO of Tesla and SpaceX. I think he is a visionary because he wants to change the world. He works very hard to create electric cars and rockets. I have watched many of his interviews online. He speaks very intelligently about the future. Although he is very rich, he seems down to earth. He inspires me to study hard and follow my dreams. I hope to meet him one day.",
        "word_count": 85,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR6] Vocabulary: 'entrepreneur', 'CEO', 'visionary', 'electric cars', 'rockets', 'interviews', 'intelligently', 'down to earth', 'inspires'. Adequate range. >Band 5: Uses specific words ('visionary'). Not Band 7: Lacks sophistication.",
        "grammar_reason": "[GRA6] Uses a mix of simple and complex structures. 'Who is a famous entrepreneur' (Relative clause). 'Because he wants...' (Reason clause). 'Although he is very rich...' (Concessive clause). Generally error-free. >Band 5: Uses complex structures accurately. Not Band 7: Limited range.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a famous person you admire.\n\nTranscript: I admire Elon Musk, who is a famous entrepreneur. He is the CEO of Tesla and SpaceX. I think he is a visionary because he wants to change the world. He works very hard to create electric cars and rockets. I have watched many of his interviews online. He speaks very intelligently about the future. Although he is very rich, he seems down to earth. He inspires me to study hard and follow my dreams. I hope to meet him one day.\n\nWord Count: 85 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses topic words: 'entrepreneur', 'visionary', 'inspires'. Meaning is clear.\n\n>Band 5: Adequate vocabulary.\n\nNot Band 7: Lacks variety.\n\n**Idiom present:** Yes ('down to earth')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Uses complex structures accurately. Includes relative clauses and concessive clauses.\n\n>Band 5: Good control of complex forms.\n\nNot Band 7: Range is limited.\n\n**Micro flaws identified:**\n- None."
    },
    # 465. V6/G6 - Activity (Skill)
    {
        "sample_id": "syn_p2_v6_g6_0465",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a skill you learned recently.",
        "transcript_cleaned": "I recently learned how to edit videos on my computer. I used a software program that is very popular. I watched tutorials on YouTube to understand how it works. It was difficult at first because there were many buttons. However, after practicing for a week, I got the hang of it. I edited a video of my holiday and added music. My friends liked it very much. I think this skill is useful for my future career. I plan to make more videos soon.",
        "word_count": 86,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR6] Vocabulary: 'edit videos', 'software program', 'tutorials', 'buttons', 'practicing', 'got the hang of it', 'career'. Adequate range. >Band 5: Uses specific words ('tutorials'). Not Band 7: Lacks depth.",
        "grammar_reason": "[GRA6] Uses a mix of simple and complex structures. 'That is very popular' (Relative clause). 'Because there were many buttons' (Reason clause). 'After practicing...' (Prepositional phrase). Generally error-free. >Band 5: Uses complex structures accurately. Not Band 7: Limited range.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a skill you learned recently.\n\nTranscript: I recently learned how to edit videos on my computer. I used a software program that is very popular. I watched tutorials on YouTube to understand how it works. It was difficult at first because there were many buttons. However, after practicing for a week, I got the hang of it. I edited a video of my holiday and added music. My friends liked it very much. I think this skill is useful for my future career. I plan to make more videos soon.\n\nWord Count: 86 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses relevant vocabulary: 'software', 'tutorials'. Clear description.\n\n>Band 5: Good range.\n\nNot Band 7: Lacks variety.\n\n**Idiom present:** Yes ('got the hang of it')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Uses complex structures accurately. Includes relative clauses and reason clauses.\n\n>Band 5: Good control of complex forms.\n\nNot Band 7: Range is limited.\n\n**Micro flaws identified:**\n- None."
    },
    # 466. V6/G6 - Event (Success)
    {
        "sample_id": "syn_p2_v6_g6_0466",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a success you had in your life.",
        "transcript_cleaned": "Winning the school spelling bee competition was a big success for me. I had to learn many difficult words. I studied every evening for two months. My mother helped me by testing my memory. On the day of the competition, I was very nervous. However, I managed to stay calm and spell all the words correctly. When I was announced the winner, I felt very proud. I received a trophy and a certificate. This achievement gave me confidence in my abilities.",
        "word_count": 83,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR6] Vocabulary: 'spelling bee', 'competition', 'memory', 'nervous', 'managed', 'calm', 'announced', 'winner', 'proud', 'trophy', 'certificate', 'achievement', 'confidence', 'abilities'. Adequate range. >Band 5: Clear descriptions. Not Band 7: Vocabulary is standard.",
        "grammar_reason": "[GRA6] Uses a mix of simple and complex structures. 'By testing my memory' (Prepositional phrase). 'When I was announced...' (Time clause). 'Managed to stay calm' (Verb pattern). Generally error-free. >Band 5: Uses complex structures accurately. Not Band 7: Limited range.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a success you had in your life.\n\nTranscript: Winning the school spelling bee competition was a big success for me. I had to learn many difficult words. I studied every evening for two months. My mother helped me by testing my memory. On the day of the competition, I was very nervous. However, I managed to stay calm and spell all the words correctly. When I was announced the winner, I felt very proud. I received a trophy and a certificate. This achievement gave me confidence in my abilities.\n\nWord Count: 83 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses topic words: 'trophy', 'certificate', 'achievement'. Meaning is clear.\n\n>Band 5: Adequate vocabulary.\n\nNot Band 7: Lacks sophistication.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Uses complex structures accurately. Includes time clauses and verb patterns.\n\n>Band 5: Good control of complex forms.\n\nNot Band 7: Range is limited.\n\n**Micro flaws identified:**\n- None."
    },
    # 467. V6/G6 - Place (Museum)
    {
        "sample_id": "syn_p2_v6_g6_0467",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a museum you would like to visit.",
        "transcript_cleaned": "I would like to visit the British Museum in London. I have heard that it is one of the largest museums in the world. It has a vast collection of artifacts from different cultures. I am particularly interested in the Egyptian section. I want to see the Rosetta Stone and the mummies. I think it would be a fascinating experience to learn about history. If I go there, I will spend the whole day exploring. It is a place where you can travel through time.",
        "word_count": 86,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR6] Vocabulary: 'largest museums', 'vast collection', 'artifacts', 'cultures', 'Egyptian section', 'Rosetta Stone', 'mummies', 'fascinating', 'exploring', 'travel through time'. Adequate range. >Band 5: Uses specific words ('artifacts'). Not Band 7: Lacks depth.",
        "grammar_reason": "[GRA6] Uses a mix of simple and complex structures. 'I have heard that...' (Noun clause). 'If I go there...' (First conditional). 'Where you can travel...' (Relative clause). Generally error-free. >Band 5: Uses complex structures accurately. Not Band 7: Limited range.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a museum you would like to visit.\n\nTranscript: I would like to visit the British Museum in London. I have heard that it is one of the largest museums in the world. It has a vast collection of artifacts from different cultures. I am particularly interested in the Egyptian section. I want to see the Rosetta Stone and the mummies. I think it would be a fascinating experience to learn about history. If I go there, I will spend the whole day exploring. It is a place where you can travel through time.\n\nWord Count: 86 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses descriptive vocabulary: 'vast collection', 'fascinating'. Good range.\n\n>Band 5: Adequate vocabulary.\n\nNot Band 7: Lacks variety.\n\n**Idiom present:** Yes ('travel through time')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Uses complex structures accurately. Includes conditionals and noun clauses.\n\n>Band 5: Good control of complex forms.\n\nNot Band 7: Range is limited.\n\n**Micro flaws identified:**\n- None."
    },
    # 468. V6/G6 - Activity (Daily)
    {
        "sample_id": "syn_p2_v6_g6_0468",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe your evening routine.",
        "transcript_cleaned": "In the evening, I usually come home from work at 6 pm. I like to relax for a while before cooking dinner. I prepare simple meals like pasta or salad. After dinner, I wash the dishes and clean the kitchen. Then, I watch my favorite TV show or read a book. I find reading very relaxing. Sometimes I call my parents to chat. I get ready for bed around 10 pm. I brush my teeth and put on my pajamas. I try to sleep early so I can be fresh for the next day.",
        "word_count": 96,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR6] Vocabulary: 'relax', 'prepare', 'simple meals', 'wash dishes', 'chat', 'pajamas', 'fresh'. Adequate range. >Band 5: Clear descriptions. Not Band 7: Vocabulary is standard.",
        "grammar_reason": "[GRA6] Uses a mix of simple and complex structures. 'Before cooking dinner' (Prepositional phrase). 'So I can be fresh' (Result clause). Present tense used correctly throughout. Generally error-free. >Band 5: Uses complex structures accurately. Not Band 7: Limited range.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe your evening routine.\n\nTranscript: In the evening, I usually come home from work at 6 pm. I like to relax for a while before cooking dinner. I prepare simple meals like pasta or salad. After dinner, I wash the dishes and clean the kitchen. Then, I watch my favorite TV show or read a book. I find reading very relaxing. Sometimes I call my parents to chat. I get ready for bed around 10 pm. I brush my teeth and put on my pajamas. I try to sleep early so I can be fresh for the next day.\n\nWord Count: 96 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses topic words: 'relax', 'prepare', 'fresh'. Meaning is clear.\n\n>Band 5: Adequate vocabulary.\n\nNot Band 7: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Uses complex structures accurately. Includes prepositional phrases and result clauses.\n\n>Band 5: Good control of complex forms.\n\nNot Band 7: Range is limited.\n\n**Micro flaws identified:**\n- None."
    },
    # 469. V6/G6 - Weather (Summer)
    {
        "sample_id": "syn_p2_v6_g6_0469",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe the summer weather in your country.",
        "transcript_cleaned": "Summer in my country is very hot and humid. It lasts from June to August. The temperature often goes above 30 degrees Celsius. I usually wear light clothes like shorts and T-shirts. Many people go to the beach to swim and cool down. We also eat ice cream to stay cool. Sometimes there are thunderstorms in the afternoon. I like summer because I can do outdoor activities. However, the heat can be tiring. I prefer to stay indoors during the hottest part of the day. It is a vibrant season.",
        "word_count": 92,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR6] Vocabulary: 'humid', 'temperature', 'degrees Celsius', 'light clothes', 'cool down', 'thunderstorms', 'outdoor activities', 'heat', 'tiring', 'indoors', 'vibrant season'. Adequate range. >Band 5: Uses specific words ('humid', 'thunderstorms'). Not Band 7: Lacks depth.",
        "grammar_reason": "[GRA6] Uses a mix of simple and complex structures. 'To swim and cool down' (Infinitive of purpose). 'Because I can do...' (Reason clause). 'During the hottest part...' (Prepositional phrase). Generally error-free. >Band 5: Uses complex structures accurately. Not Band 7: Limited range.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe the summer weather in your country.\n\nTranscript: Summer in my country is very hot and humid. It lasts from June to August. The temperature often goes above 30 degrees Celsius. I usually wear light clothes like shorts and T-shirts. Many people go to the beach to swim and cool down. We also eat ice cream to stay cool. Sometimes there are thunderstorms in the afternoon. I like summer because I can do outdoor activities. However, the heat can be tiring. I prefer to stay indoors during the hottest part of the day. It is a vibrant season.\n\nWord Count: 92 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses relevant vocabulary: 'humid', 'tiring', 'vibrant'. Clear description.\n\n>Band 5: Good range.\n\nNot Band 7: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Uses complex structures accurately. Includes infinitives of purpose and prepositional phrases.\n\n>Band 5: Good control of complex forms.\n\nNot Band 7: Range is limited.\n\n**Micro flaws identified:**\n- None."
    },
    # 470. V6/G6 - Activity (Weekend)
    {
        "sample_id": "syn_p2_v6_g6_0470",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe what you plan to do next weekend.",
        "transcript_cleaned": "Next weekend, I plan to visit my grandparents who live in the countryside. I will take the train on Saturday morning. I am looking forward to seeing them because I have not seen them for a long time. We will probably have a big lunch together. My grandmother is an excellent cook. I might help my grandfather in the garden. I want to relax and enjoy the fresh air. I will return home on Sunday evening. It will be a nice break from my busy schedule.",
        "word_count": 88,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR6] Vocabulary: 'countryside', 'looking forward', 'excellent cook', 'garden', 'relax', 'fresh air', 'return', 'nice break', 'busy schedule'. Adequate range. >Band 5: Clear descriptions. Not Band 7: Vocabulary is standard.",
        "grammar_reason": "[GRA6] Uses a mix of simple and complex structures. 'Who live in the countryside' (Relative clause). 'Because I have not seen them...' (Reason clause + Present Perfect). 'Looking forward to seeing' (Verb pattern). Generally error-free. >Band 5: Uses complex structures accurately. Not Band 7: Limited range.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe what you plan to do next weekend.\n\nTranscript: Next weekend, I plan to visit my grandparents who live in the countryside. I will take the train on Saturday morning. I am looking forward to seeing them because I have not seen them for a long time. We will probably have a big lunch together. My grandmother is an excellent cook. I might help my grandfather in the garden. I want to relax and enjoy the fresh air. I will return home on Sunday evening. It will be a nice break from my busy schedule.\n\nWord Count: 88 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses topic words: 'countryside', 'schedule'. Meaning is clear.\n\n>Band 5: Adequate vocabulary.\n\nNot Band 7: Lacks variety.\n\n**Idiom present:** Yes ('looking forward')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Uses complex structures accurately. Includes relative clauses and verb patterns.\n\n>Band 5: Good control of complex forms.\n\nNot Band 7: Range is limited.\n\n**Micro flaws identified:**\n- None."
    }
]

with open(OUTPUT_FILE, 'a', encoding='utf-8') as f:
    for sample in samples:
        f.write(json.dumps(sample) + '\n')
