import json

OUTPUT_FILE = "ielts-data/phase3/v76_review_output/synthetic_batches/batch_p2_08.jsonl"

samples = [
    # 371. V7/G5 - City (Visited)
    {
        "sample_id": "syn_p2_v7_g5_0371",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a city you have visited.",
        "transcript_cleaned": "I want to talk about Kyoto, a city in Japan that I visiting last year. It is renowned for its traditional temples and stunning gardens. I was captivated by the serene atmosphere, which were very peaceful compared to Tokyo. I spent many days wandering through the historic streets, admiring the architecture. One place I remember vividly is the Golden Pavilion, a structure that gleam in the sunlight. Although the city were crowded with tourists, I managing to find some quiet spots. The food was also exceptional; I tasting many local delicacies. If I have the chance, I will definitely returned there. It is a place that offer a unique blend of ancient culture and modern life.",
        "word_count": 126,
        "response_type": "long_turn",
        "micro_flaws": ["tense: 'I visiting' should be 'I visited'", "agreement: 'atmosphere, which were' should be 'was'", "tense: 'structure that gleam' should be 'gleams' or 'gleamed'", "agreement: 'city were crowded' should be 'was'", "tense: 'I managing' should be 'I managed'", "tense: 'I tasting' should be 'I tasted'", "tense: 'I will definitely returned' should be 'return'", "agreement: 'place that offer' should be 'offers'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR7] Vocabulary: 'renowned', 'stunning', 'captivated', 'serene', 'wandering', 'historic', 'architecture', 'vividly', 'structure', 'gleam', 'exceptional', 'delicacies', 'unique blend'. Uses some less common and precise vocabulary flexibly. >Band 6: Good range of vocabulary. Not Band 8: Some collocations could be more natural.",
        "grammar_reason": "[GRA5] Basic sentence forms are generally accurate, but complex structures are faulty. Frequent errors in tense ('I visiting', 'I tasting', 'will returned') and agreement ('atmosphere were', 'city were', 'place that offer'). >Band 4: Attempts complex sentences but with errors. Not Band 6: Errors are too frequent.",
        "vocabulary": 7,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a city you have visited.\n\nTranscript: I want to talk about Kyoto, a city in Japan that I visiting last year. It is renowned for its traditional temples and stunning gardens. I was captivated by the serene atmosphere, which were very peaceful compared to Tokyo. I spent many days wandering through the historic streets, admiring the architecture. One place I remember vividly is the Golden Pavilion, a structure that gleam in the sunlight. Although the city were crowded with tourists, I managing to find some quiet spots. The food was also exceptional; I tasting many local delicacies. If I have the chance, I will definitely returned there. It is a place that offer a unique blend of ancient culture and modern life.\n\nWord Count: 126 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses 'renowned', 'captivated', 'serene', 'vividly', 'delicacies'. Good range and flexibility.\n\n>Band 6: More precise vocabulary.\n\nNot Band 8: Lacks full sophistication.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Frequent errors in tense and subject-verb agreement. Complex structures are attempted but often faulty ('which were', 'that gleam').\n\n>Band 4: Basic sentences are okay.\n\nNot Band 6: Errors are frequent and noticeable.\n\n**Micro flaws identified:**\n- 'I visiting' should be 'I visited'\n- 'which were' should be 'which was'\n- 'that gleam' should be 'that gleams'\n- 'city were' should be 'city was'\n- 'I managing' should be 'I managed'\n- 'I tasting' should be 'I tasted'\n- 'will definitely returned' should be 'return'\n- 'place that offer' should be 'offers'"
    },
    # 372. V7/G5 - Book (Recently read)
    {
        "sample_id": "syn_p2_v7_g5_0372",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a book you recently read.",
        "transcript_cleaned": "I recently read a biography of Steve Jobs, which are a very inspiring book. It details his life from his humble beginnings to becoming a tech mogul. I was fascinated by his visionary approach to innovation and design. The book describe how he revolutionized multiple industries, including personal computing and music. However, it also reveal his difficult personality and how he treating his employees. I found the narrative compelling, although some parts was a bit slow. Reading about his failures were as interesting as his successes. It taught me that perseverance is crucial for achieving greatness. I would recommending this book to anyone interested in technology or business.",
        "word_count": 121,
        "response_type": "long_turn",
        "micro_flaws": ["agreement: 'which are' should be 'is'", "agreement: 'book describe' should be 'describes'", "agreement: 'it also reveal' should be 'reveals'", "tense: 'he treating' should be 'he treated'", "agreement: 'parts was' should be 'were'", "agreement: 'failures were' should be 'was' (reading about them)", "grammar: 'would recommending' should be 'recommend'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR7] Vocabulary: 'biography', 'inspiring', 'humble beginnings', 'mogul', 'visionary', 'innovation', 'revolutionized', 'industries', 'narrative', 'compelling', 'perseverance', 'crucial', 'greatness'. Uses precise vocabulary effectively. >Band 6: Good lexical resource. Not Band 8: Some phrasing is standard.",
        "grammar_reason": "[GRA5] Frequent grammatical errors. Subject-verb agreement is consistently wrong ('which are', 'book describe', 'it reveal'). Tense errors ('he treating'). Verb form errors ('would recommending'). >Band 4: Meaning is clear despite errors. Not Band 6: Errors are systematic.",
        "vocabulary": 7,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a book you recently read.\n\nTranscript: I recently read a biography of Steve Jobs, which are a very inspiring book. It details his life from his humble beginnings to becoming a tech mogul. I was fascinated by his visionary approach to innovation and design. The book describe how he revolutionized multiple industries, including personal computing and music. However, it also reveal his difficult personality and how he treating his employees. I found the narrative compelling, although some parts was a bit slow. Reading about his failures were as interesting as his successes. It taught me that perseverance is crucial for achieving greatness. I would recommending this book to anyone interested in technology or business.\n\nWord Count: 121 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses 'mogul', 'visionary', 'revolutionized', 'compelling', 'perseverance'. Good range and flexibility.\n\n>Band 6: Precise vocabulary.\n\nNot Band 8: Lacks full sophistication.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Frequent errors in subject-verb agreement and verb forms. Complex sentences have errors ('which are', 'book describe').\n\n>Band 4: Basic sentences are recognizable.\n\nNot Band 6: Errors are too frequent.\n\n**Micro flaws identified:**\n- 'which are' should be 'which is'\n- 'book describe' should be 'book describes'\n- 'it also reveal' should be 'it also reveals'\n- 'he treating' should be 'he treated'\n- 'parts was' should be 'parts were'\n- 'failures were' should be 'was'\n- 'would recommending' should be 'would recommend'"
    },
    # 373. V7/G5 - Cafe
    {
        "sample_id": "syn_p2_v7_g5_0373",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a cafe you like to visit.",
        "transcript_cleaned": "There is a quaint cafe near my office called 'The Daily Grind' where I going often. It has a rustic interior with wooden furniture and vintage decorations. The ambiance is cozy and inviting, making it a perfect spot to unwind. I usually ordering a cappuccino and a croissant. The barista, who are very friendly, always remembers my name. What I appreciate most is the tranquility; it is never too noisy. I often brings my laptop to work there because the Wi-Fi are fast. Last week, I meeting a friend there for lunch. We enjoying the delicious sandwiches and had a great conversation. It is a hidden gem in the city.",
        "word_count": 121,
        "response_type": "long_turn",
        "micro_flaws": ["tense: 'I going' should be 'I go'", "tense: 'I usually ordering' should be 'I usually order'", "agreement: 'barista, who are' should be 'is'", "agreement: 'I often brings' should be 'bring'", "agreement: 'Wi-Fi are' should be 'is'", "tense: 'I meeting' should be 'I met'", "tense: 'We enjoying' should be 'We enjoyed'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR7] Vocabulary: 'quaint', 'rustic', 'interior', 'vintage', 'ambiance', 'inviting', 'unwind', 'barista', 'appreciate', 'tranquility', 'hidden gem'. Uses descriptive vocabulary well. >Band 6: Good range of adjectives. Not Band 8: Some phrases are common.",
        "grammar_reason": "[GRA5] Frequent grammatical errors. Continuous tense used incorrectly for habits or past events ('I going', 'I ordering', 'I meeting', 'We enjoying'). Subject-verb agreement errors ('barista who are', 'I brings', 'Wi-Fi are'). >Band 4: Basic meaning is clear. Not Band 6: Errors are systematic.",
        "vocabulary": 7,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a cafe you like to visit.\n\nTranscript: There is a quaint cafe near my office called 'The Daily Grind' where I going often. It has a rustic interior with wooden furniture and vintage decorations. The ambiance is cozy and inviting, making it a perfect spot to unwind. I usually ordering a cappuccino and a croissant. The barista, who are very friendly, always remembers my name. What I appreciate most is the tranquility; it is never too noisy. I often brings my laptop to work there because the Wi-Fi are fast. Last week, I meeting a friend there for lunch. We enjoying the delicious sandwiches and had a great conversation. It is a hidden gem in the city.\n\nWord Count: 121 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses 'quaint', 'rustic', 'ambiance', 'unwind', 'tranquility'. Good descriptive vocabulary.\n\n>Band 6: Precise words.\n\nNot Band 8: Lacks full sophistication.\n\n**Idiom present:** Yes ('hidden gem')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Frequent errors in verb tenses and agreement. Incorrect use of continuous forms ('I going', 'I ordering').\n\n>Band 4: Basic sentences are okay.\n\nNot Band 6: Errors are frequent and noticeable.\n\n**Micro flaws identified:**\n- 'I going' should be 'I go'\n- 'I usually ordering' should be 'I usually order'\n- 'barista who are' should be 'barista who is'\n- 'I often brings' should be 'I often bring'\n- 'Wi-Fi are' should be 'Wi-Fi is'\n- 'I meeting' should be 'I met'\n- 'We enjoying' should be 'We enjoyed'"
    },
    # 374. V7/G5 - Family Member
    {
        "sample_id": "syn_p2_v7_g5_0374",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a family member you admire.",
        "transcript_cleaned": "I admire my older brother, who work as a surgeon in a busy hospital. He is extremely dedicated and hardworking, often working long shifts. I am impressed by his resilience and ability to stay calm under pressure. He have saved many lives, which are a remarkable achievement. Despite his hectic schedule, he always finding time to help me with my studies. He encourages me to pursuing my dreams and never give up. I remember when he graduating from medical school; our whole family were so proud. He is a compassionate person who truly care about others. I hoping to become like him one day.",
        "word_count": 118,
        "response_type": "long_turn",
        "micro_flaws": ["agreement: 'who work' should be 'works'", "agreement: 'He have' should be 'has'", "agreement: 'which are' should be 'is'", "tense: 'he always finding' should be 'finds'", "grammar: 'to pursuing' should be 'to pursue'", "tense: 'when he graduating' should be 'graduated'", "agreement: 'family were' should be 'was'", "agreement: 'who truly care' should be 'cares'", "tense: 'I hoping' should be 'I hope'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR7] Vocabulary: 'admire', 'surgeon', 'dedicated', 'hardworking', 'resilience', 'hectic schedule', 'encourages', 'pursuing', 'compassionate'. Uses precise vocabulary effectively. >Band 6: Good lexical resource. Not Band 8: Some phrasing is standard.",
        "grammar_reason": "[GRA5] Frequent grammatical errors. Subject-verb agreement is consistently wrong ('who work', 'He have', 'which are', 'family were', 'who care'). Tense errors ('he finding', 'he graduating', 'I hoping'). Verb form errors ('to pursuing'). >Band 4: Meaning is clear despite errors. Not Band 6: Errors are systematic.",
        "vocabulary": 7,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a family member you admire.\n\nTranscript: I admire my older brother, who work as a surgeon in a busy hospital. He is extremely dedicated and hardworking, often working long shifts. I am impressed by his resilience and ability to stay calm under pressure. He have saved many lives, which are a remarkable achievement. Despite his hectic schedule, he always finding time to help me with my studies. He encourages me to pursuing my dreams and never give up. I remember when he graduating from medical school; our whole family were so proud. He is a compassionate person who truly care about others. I hoping to become like him one day.\n\nWord Count: 118 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses 'dedicated', 'resilience', 'hectic', 'compassionate'. Good range and flexibility.\n\n>Band 6: Precise words.\n\nNot Band 8: Lacks full sophistication.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Frequent errors in subject-verb agreement and verb forms. 'Who work', 'He have', 'to pursuing' are incorrect.\n\n>Band 4: Basic sentences are recognizable.\n\nNot Band 6: Errors are frequent and noticeable.\n\n**Micro flaws identified:**\n- 'who work' should be 'who works'\n- 'He have' should be 'He has'\n- 'which are' should be 'which is'\n- 'he always finding' should be 'he always finds'\n- 'to pursuing' should be 'to pursue'\n- 'he graduating' should be 'he graduated'\n- 'family were' should be 'family was'\n- 'who truly care' should be 'who truly cares'\n- 'I hoping' should be 'I hope'"
    },
    # 375. V7/G5 - Object (Old)
    {
        "sample_id": "syn_p2_v7_g5_0375",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe an old object in your home.",
        "transcript_cleaned": "I possess an antique clock that belonged to my great-grandfather. It is an exquisite piece of craftsmanship, made of mahogany wood with intricate carvings. The clock chime every hour with a melodious sound. It have been in our family for over a century, passing down through generations. Although it is very old, it still keeping perfect time. My father wind it up every Sunday morning, which are a family ritual. I cherish this object because it represent our family history and heritage. It is fragile, so we treating it with great care. I hope to inheriting it one day and pass it on to my children.",
        "word_count": 121,
        "response_type": "long_turn",
        "micro_flaws": ["agreement: 'clock chime' should be 'chimes'", "agreement: 'It have been' should be 'has been'", "tense: 'passing down' should be 'passed down'", "tense: 'it still keeping' should be 'keeps'", "agreement: 'father wind' should be 'winds'", "agreement: 'which are' should be 'is'", "agreement: 'it represent' should be 'represents'", "tense: 'we treating' should be 'we treat'", "grammar: 'hope to inheriting' should be 'hope to inherit'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR7] Vocabulary: 'possess', 'antique', 'exquisite', 'craftsmanship', 'intricate', 'carvings', 'chime', 'melodious', 'generations', 'ritual', 'cherish', 'heritage', 'fragile'. Uses descriptive vocabulary well. >Band 6: Good range of adjectives. Not Band 8: Some phrases are common.",
        "grammar_reason": "[GRA5] Frequent grammatical errors. Subject-verb agreement is consistently wrong ('clock chime', 'It have', 'father wind', 'it represent'). Tense errors ('passing down', 'keeping', 'treating'). Verb form errors ('to inheriting'). >Band 4: Basic meaning is clear. Not Band 6: Errors are systematic.",
        "vocabulary": 7,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe an old object in your home.\n\nTranscript: I possess an antique clock that belonged to my great-grandfather. It is an exquisite piece of craftsmanship, made of mahogany wood with intricate carvings. The clock chime every hour with a melodious sound. It have been in our family for over a century, passing down through generations. Although it is very old, it still keeping perfect time. My father wind it up every Sunday morning, which are a family ritual. I cherish this object because it represent our family history and heritage. It is fragile, so we treating it with great care. I hope to inheriting it one day and pass it on to my children.\n\nWord Count: 121 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses 'antique', 'exquisite', 'intricate', 'melodious', 'cherish'. Good descriptive vocabulary.\n\n>Band 6: Precise words.\n\nNot Band 8: Lacks full sophistication.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Frequent errors in subject-verb agreement and verb forms. 'Clock chime', 'It have', 'to inheriting' are incorrect.\n\n>Band 4: Basic sentences are recognizable.\n\nNot Band 6: Errors are frequent and noticeable.\n\n**Micro flaws identified:**\n- 'clock chime' should be 'chimes'\n- 'It have been' should be 'It has been'\n- 'passing down' should be 'passed down'\n- 'it still keeping' should be 'it still keeps'\n- 'father wind' should be 'father winds'\n- 'which are' should be 'which is'\n- 'it represent' should be 'it represents'\n- 'we treating' should be 'we treat'\n- 'hope to inheriting' should be 'hope to inherit'"
    },
    # 376. V7/G5 - Activity (Outdoor)
    {
        "sample_id": "syn_p2_v7_g5_0376",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe an outdoor activity you enjoy.",
        "transcript_cleaned": "I am passionate about hiking, which I usually doing on weekends. It allows me to reconnect with nature and escape the hustle and bustle of city life. I love exploring rugged trails and discovering scenic vistas. The fresh air are invigorating, and the exercise keep me fit. Last month, I climbing a mountain with my friends. It were a challenging ascent, but the view from the summit was breathtaking. We spending the whole day there, taking photos and having a picnic. I feel that hiking are beneficial for both physical and mental health. I am planning to visiting a national park next summer for a longer trek.",
        "word_count": 122,
        "response_type": "long_turn",
        "micro_flaws": ["tense: 'I usually doing' should be 'I usually do'", "agreement: 'fresh air are' should be 'is'", "agreement: 'exercise keep' should be 'keeps'", "tense: 'I climbing' should be 'I climbed'", "agreement: 'It were' should be 'was'", "tense: 'We spending' should be 'We spent'", "agreement: 'hiking are' should be 'is'", "grammar: 'planning to visiting' should be 'planning to visit'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR7] Vocabulary: 'passionate', 'reconnect', 'hustle and bustle', 'rugged', 'scenic vistas', 'invigorating', 'ascent', 'summit', 'breathtaking', 'beneficial'. Uses precise vocabulary effectively. >Band 6: Good lexical resource. Not Band 8: Some phrasing is standard.",
        "grammar_reason": "[GRA5] Frequent grammatical errors. Incorrect use of continuous tense ('I doing', 'I climbing', 'We spending'). Subject-verb agreement errors ('air are', 'exercise keep', 'It were', 'hiking are'). Verb form errors ('to visiting'). >Band 4: Meaning is clear despite errors. Not Band 6: Errors are systematic.",
        "vocabulary": 7,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe an outdoor activity you enjoy.\n\nTranscript: I am passionate about hiking, which I usually doing on weekends. It allows me to reconnect with nature and escape the hustle and bustle of city life. I love exploring rugged trails and discovering scenic vistas. The fresh air are invigorating, and the exercise keep me fit. Last month, I climbing a mountain with my friends. It were a challenging ascent, but the view from the summit was breathtaking. We spending the whole day there, taking photos and having a picnic. I feel that hiking are beneficial for both physical and mental health. I am planning to visiting a national park next summer for a longer trek.\n\nWord Count: 122 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses 'reconnect', 'rugged', 'invigorating', 'summit', 'breathtaking'. Good range and flexibility.\n\n>Band 6: Precise words.\n\nNot Band 8: Lacks full sophistication.\n\n**Idiom present:** Yes ('hustle and bustle')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Frequent errors in verb tenses and agreement. 'I doing', 'air are', 'It were' are incorrect.\n\n>Band 4: Basic sentences are recognizable.\n\nNot Band 6: Errors are frequent and noticeable.\n\n**Micro flaws identified:**\n- 'I usually doing' should be 'I usually do'\n- 'air are' should be 'air is'\n- 'exercise keep' should be 'exercise keeps'\n- 'I climbing' should be 'I climbed'\n- 'It were' should be 'It was'\n- 'We spending' should be 'We spent'\n- 'hiking are' should be 'hiking is'\n- 'planning to visiting' should be 'planning to visit'"
    },
    # 377. V7/G5 - Website (Shopping)
    {
        "sample_id": "syn_p2_v7_g5_0377",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a website you use for shopping.",
        "transcript_cleaned": "I frequently utilizing Amazon for online shopping because it is incredibly convenient. The website have a vast inventory, offering everything from electronics to groceries. I am impressed by the user-friendly interface, which make navigation effortless. I often reading customer reviews before making a purchase to ensure quality. The delivery service are also very reliable; packages usually arriving within two days. Last week, I buying a new laptop on the site. The price were competitive, and I saved a lot of money. However, I sometimes worrying about spending too much because it is so easy to buy things. It has revolutionized the way I shop.",
        "word_count": 121,
        "response_type": "long_turn",
        "micro_flaws": ["tense: 'I frequently utilizing' should be 'I frequently utilize'", "agreement: 'website have' should be 'has'", "agreement: 'which make' should be 'makes'", "tense: 'I often reading' should be 'I often read'", "agreement: 'service are' should be 'is'", "tense: 'packages usually arriving' should be 'arrive'", "tense: 'I buying' should be 'I bought'", "agreement: 'price were' should be 'was'", "tense: 'I sometimes worrying' should be 'worry'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR7] Vocabulary: 'utilizing', 'convenient', 'inventory', 'user-friendly', 'interface', 'effortless', 'reliable', 'competitive', 'revolutionized'. Uses precise vocabulary effectively. >Band 6: Good lexical resource. Not Band 8: Some phrasing is standard.",
        "grammar_reason": "[GRA5] Frequent grammatical errors. Incorrect use of continuous tense ('I utilizing', 'I reading', 'I buying', 'I worrying'). Subject-verb agreement errors ('website have', 'which make', 'service are', 'price were'). >Band 4: Meaning is clear despite errors. Not Band 6: Errors are systematic.",
        "vocabulary": 7,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a website you use for shopping.\n\nTranscript: I frequently utilizing Amazon for online shopping because it is incredibly convenient. The website have a vast inventory, offering everything from electronics to groceries. I am impressed by the user-friendly interface, which make navigation effortless. I often reading customer reviews before making a purchase to ensure quality. The delivery service are also very reliable; packages usually arriving within two days. Last week, I buying a new laptop on the site. The price were competitive, and I saved a lot of money. However, I sometimes worrying about spending too much because it is so easy to buy things. It has revolutionized the way I shop.\n\nWord Count: 121 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses 'utilizing', 'inventory', 'interface', 'effortless', 'revolutionized'. Good range and flexibility.\n\n>Band 6: Precise words.\n\nNot Band 8: Lacks full sophistication.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Frequent errors in verb tenses and agreement. 'I utilizing', 'website have', 'service are' are incorrect.\n\n>Band 4: Basic sentences are recognizable.\n\nNot Band 6: Errors are frequent and noticeable.\n\n**Micro flaws identified:**\n- 'I frequently utilizing' should be 'I frequently utilize'\n- 'website have' should be 'website has'\n- 'which make' should be 'which makes'\n- 'I often reading' should be 'I often read'\n- 'service are' should be 'service is'\n- 'packages usually arriving' should be 'packages usually arrive'\n- 'I buying' should be 'I bought'\n- 'price were' should be 'price was'\n- 'I sometimes worrying' should be 'I sometimes worry'"
    },
    # 378. V7/G5 - Subject (School)
    {
        "sample_id": "syn_p2_v7_g5_0378",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a subject you enjoyed at school.",
        "transcript_cleaned": "I really enjoyed studying biology in high school, which were my favorite subject. I was fascinated by the intricate systems of the human body and the natural world. My teacher, Mrs. Smith, were an inspiring educator who making the lessons very engaging. We often conducting experiments in the laboratory, which was very hands-on. I remember dissecting a frog, which, although gross, were educational. I learning about genetics and evolution, concepts that still interests me today. I usually scoring high marks in the exams because I studying hard. Biology helping me understand how life works. I considering studying it at university but chose engineering instead.",
        "word_count": 121,
        "response_type": "long_turn",
        "micro_flaws": ["agreement: 'which were' should be 'was'", "agreement: 'teacher... were' should be 'was'", "tense: 'who making' should be 'made'", "tense: 'We often conducting' should be 'conducted'", "agreement: 'were educational' should be 'was'", "tense: 'I learning' should be 'learned'", "agreement: 'concepts that still interests' should be 'interest'", "tense: 'I usually scoring' should be 'scored'", "tense: 'I studying' should be 'studied'", "tense: 'Biology helping' should be 'helped'", "tense: 'I considering' should be 'considered'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR7] Vocabulary: 'intricate', 'educator', 'engaging', 'experiments', 'laboratory', 'hands-on', 'dissecting', 'genetics', 'evolution', 'concepts'. Uses precise vocabulary effectively. >Band 6: Good lexical resource. Not Band 8: Some phrasing is standard.",
        "grammar_reason": "[GRA5] Frequent grammatical errors. Incorrect use of continuous tense for past events ('who making', 'We conducting', 'I learning', 'I studying', 'Biology helping', 'I considering'). Subject-verb agreement errors ('which were', 'teacher were', 'concepts that interests'). >Band 4: Meaning is clear despite errors. Not Band 6: Errors are systematic.",
        "vocabulary": 7,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a subject you enjoyed at school.\n\nTranscript: I really enjoyed studying biology in high school, which were my favorite subject. I was fascinated by the intricate systems of the human body and the natural world. My teacher, Mrs. Smith, were an inspiring educator who making the lessons very engaging. We often conducting experiments in the laboratory, which was very hands-on. I remember dissecting a frog, which, although gross, were educational. I learning about genetics and evolution, concepts that still interests me today. I usually scoring high marks in the exams because I studying hard. Biology helping me understand how life works. I considering studying it at university but chose engineering instead.\n\nWord Count: 121 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses 'intricate', 'educator', 'engaging', 'hands-on', 'genetics'. Good range and flexibility.\n\n>Band 6: Precise words.\n\nNot Band 8: Lacks full sophistication.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Frequent errors in verb tenses and agreement. 'Which were', 'who making', 'I learning' are incorrect.\n\n>Band 4: Basic sentences are recognizable.\n\nNot Band 6: Errors are frequent and noticeable.\n\n**Micro flaws identified:**\n- 'which were' should be 'which was'\n- 'teacher... were' should be 'teacher... was'\n- 'who making' should be 'who made'\n- 'We often conducting' should be 'We often conducted'\n- 'were educational' should be 'was educational'\n- 'I learning' should be 'I learned'\n- 'concepts that still interests' should be 'concepts that still interest'\n- 'I usually scoring' should be 'I usually scored'\n- 'I studying' should be 'I studied'\n- 'Biology helping' should be 'Biology helped'\n- 'I considering' should be 'I considered'"
    },
    # 379. V7/G5 - Park
    {
        "sample_id": "syn_p2_v7_g5_0379",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a park you like to visit.",
        "transcript_cleaned": "There is a sprawling park in the center of my city that I visiting frequently. It is an oasis of calm amidst the urban chaos. The park feature manicured lawns, vibrant flower beds, and towering trees. I enjoying walking along the winding paths, which is very therapeutic. There is also a large lake where people renting boats. I often seeing families having picnics and children playing. The atmosphere are always lively yet peaceful. Last Sunday, I going there to read a book under a tree. It were a perfect way to recharge my batteries. I wish there was more parks like this in the city.",
        "word_count": 121,
        "response_type": "long_turn",
        "micro_flaws": ["tense: 'I visiting' should be 'I visit'", "agreement: 'park feature' should be 'features'", "tense: 'I enjoying' should be 'I enjoy'", "agreement: 'paths, which is' should be 'are'", "tense: 'people renting' should be 'rent'", "tense: 'I often seeing' should be 'see'", "agreement: 'atmosphere are' should be 'is'", "tense: 'I going' should be 'I went'", "agreement: 'It were' should be 'was'", "agreement: 'there was more parks' should be 'were'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR7] Vocabulary: 'sprawling', 'oasis', 'calm', 'chaos', 'manicured', 'vibrant', 'winding', 'therapeutic', 'lively', 'recharge my batteries'. Uses descriptive vocabulary well. >Band 6: Good range of adjectives. Not Band 8: Some phrases are common.",
        "grammar_reason": "[GRA5] Frequent grammatical errors. Continuous tense used incorrectly ('I visiting', 'I enjoying', 'I seeing', 'I going'). Subject-verb agreement errors ('park feature', 'paths which is', 'atmosphere are', 'It were', 'there was more parks'). >Band 4: Basic meaning is clear. Not Band 6: Errors are systematic.",
        "vocabulary": 7,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a park you like to visit.\n\nTranscript: There is a sprawling park in the center of my city that I visiting frequently. It is an oasis of calm amidst the urban chaos. The park feature manicured lawns, vibrant flower beds, and towering trees. I enjoying walking along the winding paths, which is very therapeutic. There is also a large lake where people renting boats. I often seeing families having picnics and children playing. The atmosphere are always lively yet peaceful. Last Sunday, I going there to read a book under a tree. It were a perfect way to recharge my batteries. I wish there was more parks like this in the city.\n\nWord Count: 121 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses 'sprawling', 'oasis', 'manicured', 'therapeutic'. Good descriptive vocabulary.\n\n>Band 6: Precise words.\n\nNot Band 8: Lacks full sophistication.\n\n**Idiom present:** Yes ('recharge my batteries')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Frequent errors in verb tenses and agreement. 'I visiting', 'park feature', 'atmosphere are' are incorrect.\n\n>Band 4: Basic sentences are recognizable.\n\nNot Band 6: Errors are frequent and noticeable.\n\n**Micro flaws identified:**\n- 'I visiting' should be 'I visit'\n- 'park feature' should be 'park features'\n- 'I enjoying' should be 'I enjoy'\n- 'paths, which is' should be 'paths, which are'\n- 'people renting' should be 'people rent'\n- 'I often seeing' should be 'I often see'\n- 'atmosphere are' should be 'atmosphere is'\n- 'I going' should be 'I went'\n- 'It were' should be 'It was'\n- 'there was more parks' should be 'there were more parks'"
    },
    # 380. V7/G5 - Weather (Bad)
    {
        "sample_id": "syn_p2_v7_g5_0380",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a time you experienced bad weather.",
        "transcript_cleaned": "I remember a terrifying experience when I getting caught in a typhoon while on holiday. The wind were howling ferociously, and the rain were pouring down in torrents. Trees was swaying violently, and some branches snapping off. I was staying in a hotel near the beach, which felt very unsafe. The electricity going out, plunging the room into darkness. I feeling very anxious and helpless. We waiting for the storm to pass for many hours. When it finally stopping, the destruction outside were shocking. Roads was flooded, and debris were everywhere. It was a stark reminder of the power of nature. I hope I never experiencing such a calamity again.",
        "word_count": 125,
        "response_type": "long_turn",
        "micro_flaws": ["tense: 'I getting caught' should be 'I got caught'", "agreement: 'wind were' should be 'was'", "agreement: 'rain were' should be 'was'", "agreement: 'Trees was' should be 'were'", "tense: 'branches snapping' should be 'snapped'", "tense: 'electricity going' should be 'went'", "tense: 'I feeling' should be 'felt'", "tense: 'We waiting' should be 'waited'", "tense: 'it finally stopping' should be 'stopped'", "agreement: 'destruction... were' should be 'was'", "agreement: 'Roads was' should be 'were'", "agreement: 'debris were' should be 'was'", "grammar: 'I never experiencing' should be 'I never experience'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR7] Vocabulary: 'terrifying', 'typhoon', 'howling', 'ferociously', 'torrents', 'swaying', 'violently', 'plunging', 'anxious', 'helpless', 'destruction', 'debris', 'stark reminder', 'calamity'. Uses precise vocabulary effectively. >Band 6: Good lexical resource. Not Band 8: Some phrasing is standard.",
        "grammar_reason": "[GRA5] Frequent grammatical errors. Incorrect use of continuous tense ('I getting', 'branches snapping', 'electricity going', 'I feeling', 'We waiting'). Subject-verb agreement errors ('wind were', 'rain were', 'Trees was', 'Roads was', 'debris were'). >Band 4: Meaning is clear despite errors. Not Band 6: Errors are systematic.",
        "vocabulary": 7,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a time you experienced bad weather.\n\nTranscript: I remember a terrifying experience when I getting caught in a typhoon while on holiday. The wind were howling ferociously, and the rain were pouring down in torrents. Trees was swaying violently, and some branches snapping off. I was staying in a hotel near the beach, which felt very unsafe. The electricity going out, plunging the room into darkness. I feeling very anxious and helpless. We waiting for the storm to pass for many hours. When it finally stopping, the destruction outside were shocking. Roads was flooded, and debris were everywhere. It was a stark reminder of the power of nature. I hope I never experiencing such a calamity again.\n\nWord Count: 125 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses 'terrifying', 'howling', 'ferociously', 'torrents', 'calamity'. Good descriptive vocabulary.\n\n>Band 6: Precise words.\n\nNot Band 8: Lacks full sophistication.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Frequent errors in verb tenses and agreement. 'Wind were', 'Trees was', 'I getting' are incorrect.\n\n>Band 4: Basic sentences are recognizable.\n\nNot Band 6: Errors are frequent and noticeable.\n\n**Micro flaws identified:**\n- 'I getting caught' should be 'I got caught'\n- 'wind were' should be 'wind was'\n- 'rain were' should be 'rain was'\n- 'Trees was' should be 'Trees were'\n- 'branches snapping' should be 'branches snapped'\n- 'electricity going' should be 'electricity went'\n- 'I feeling' should be 'I felt'\n- 'We waiting' should be 'We waited'\n- 'it finally stopping' should be 'it finally stopped'\n- 'destruction... were' should be 'destruction... was'\n- 'Roads was' should be 'Roads were'\n- 'debris were' should be 'debris was'\n- 'I never experiencing' should be 'I never experience'"
    }
]

with open(OUTPUT_FILE, 'a', encoding='utf-8') as f:
    for sample in samples:
        f.write(json.dumps(sample) + '\n')
