import json

OUTPUT_FILE = "ielts-data/phase3/v76_review_output/synthetic_batches/batch_p2_02.jsonl"

samples = [
    # 51. V6/G5 - Book
    {
        "sample_id": "syn_p2_v6_g5_0051",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a book you enjoyed reading recently.",
        "transcript_cleaned": "I would like to talk about a novel I read last month. It is called 'The Alchemist'. The story is about a shepherd boy who travel to Egypt to find treasure. I really enjoyed this book because it is very inspiring. The language is simple but the meaning is deep. It teach us about following our dreams. I read it every night before I sleep. Sometimes I read for two hours because I cannot stop. The character development is excellent. The boy meet many people on his journey. Each person teach him a lesson. I think this book is suitable for everyone. It make me think about my own life. I want to be brave like the boy. I recommend this book to my friends already. They also like it very much.",
        "word_count": 139,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'boy who travel' → 'boy who travels'", "grammar: 'It teach us' → 'It teaches us'", "grammar: 'before I sleep' → 'before I go to sleep'", "grammar: 'boy meet many people' → 'boy meets many people'", "grammar: 'Each person teach' → 'Each person teaches'", "grammar: 'It make me think' → 'It makes me think'", "grammar: 'recommend this book to' → 'have recommended this book to'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "variable", "flexibility": "moderate"},
        "vocab_reason": "[LR6] Vocabulary: 'novel', 'shepherd', 'treasure', 'inspiring', 'character', 'development', 'journey', 'suitable', 'brave', 'recommend'. Uses some less common items correctly.",
        "grammar_reason": "[GRA5] Basic sentences are error-free but complex structures show errors. 'The story is about a shepherd boy who travel...' (Relative clause with agreement error). 'Because it is very inspiring' (Reason clause). Tense/agreement errors ('teach', 'meet', 'make').",
        "vocabulary": 6,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a book you enjoyed reading recently.\n\nTranscript: I would like to talk about a novel I read last month. It is called 'The Alchemist'. The story is about a shepherd boy who travel to Egypt to find treasure. I really enjoyed this book because it is very inspiring. The language is simple but the meaning is deep. It teach us about following our dreams. I read it every night before I sleep. Sometimes I read for two hours because I cannot stop. The character development is excellent. The boy meet many people on his journey. Each person teach him a lesson. I think this book is suitable for everyone. It make me think about my own life. I want to be brave like the boy. I recommend this book to my friends already. They also like it very much.\n\nWord Count: 139 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses 'novel', 'shepherd', 'treasure', 'inspiring', 'character development', 'journey', 'suitable'. Adequate range for the topic.\n\n>Band 5: Uses some less common items.\n\nNot Band 7: Vocabulary is somewhat repetitive and less precise.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Uses complex sentences ('who travel', 'because I cannot stop') but with frequent errors in agreement ('It teach', 'boy meet', 'It make'). Basic sentences are accurate.\n\n>Band 4: Attempts complex sentences.\n\nNot Band 6: Errors in complex structures are frequent.\n\n**Micro flaws identified:**\n- 'boy who travel' should be 'boy who travels'\n- 'It teach us' should be 'It teaches us'\n- 'boy meet' should be 'boy meets'\n- 'It make me' should be 'It makes me'"
    },
    # 52. V6/G5 - Outdoor Activity
    {
        "sample_id": "syn_p2_v6_g5_0052",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe an outdoor activity you like to do.",
        "transcript_cleaned": "I really enjoy hiking. It is my favorite outdoor activity. I usually go hiking on weekends with my colleagues. There is a mountain near my city called Blue Mountain. The scenery there is breathtaking. Fresh air and green trees. I like hiking because it is good for my health. Physical fitness. Also, it help me reduce stress from work. When I reach the top of the mountain, I feel a sense of achievement. It is amazing feeling. Sometimes we have a picnic there. We bring sandwiches and fruits. However, the path is sometimes steep and slippery. I fell down once last year. But I didn't get hurt. I think everyone should try hiking. It is a great way to connect with nature. I plan to go there again next Sunday.",
        "word_count": 139,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'it help me' → 'it helps me'", "grammar: 'amazing feeling' → 'an amazing feeling'", "grammar: 'bring sandwiches' → 'bring sandwiches'", "grammar: 'path is sometimes' → 'path is sometimes'", "grammar: 'fell down once' → 'fell down once'", "grammar: 'didn't get hurt' → 'didn't get hurt'", "grammar: 'connect with nature' → 'connect with nature'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "variable", "flexibility": "moderate"},
        "vocab_reason": "[LR6] Vocabulary: 'hiking', 'colleagues', 'scenery', 'breathtaking', 'physical', 'fitness', 'reduce stress', 'achievement', 'steep', 'slippery', 'connect with nature'. Uses some less common items.",
        "grammar_reason": "[GRA5] Basic sentences are accurate. 'I like hiking because it is good...' (Reason). 'When I reach the top..., I feel...' (Time clause). Agreement error: 'it help me'. Missing article: 'It is amazing feeling'.",
        "vocabulary": 6,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe an outdoor activity you like to do.\n\nTranscript: I really enjoy hiking. It is my favorite outdoor activity. I usually go hiking on weekends with my colleagues. There is a mountain near my city called Blue Mountain. The scenery there is breathtaking. Fresh air and green trees. I like hiking because it is good for my health. Physical fitness. Also, it help me reduce stress from work. When I reach the top of the mountain, I feel a sense of achievement. It is amazing feeling. Sometimes we have a picnic there. We bring sandwiches and fruits. However, the path is sometimes steep and slippery. I fell down once last year. But I didn't get hurt. I think everyone should try hiking. It is a great way to connect with nature. I plan to go there again next Sunday.\n\nWord Count: 139 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses 'scenery', 'breathtaking', 'physical fitness', 'reduce stress', 'achievement', 'steep', 'slippery'. Good range for the topic.\n\n>Band 5: Uses topic-specific vocabulary.\n\nNot Band 7: Less precision in collocation.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Uses 'because', 'when'. 'It help me reduce stress'. 'It is amazing feeling'. Errors in agreement and articles.\n\n>Band 4: Uses complex structures.\n\nNot Band 6: Errors are frequent in complex structures.\n\n**Micro flaws identified:**\n- 'it help me' should be 'it helps me'\n- 'amazing feeling' should be 'an amazing feeling'"
    },
    # 53. V6/G5 - Advertisement
    {
        "sample_id": "syn_p2_v6_g5_0053",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe an advertisement you remember.",
        "transcript_cleaned": "I remember a TV commercial for a soft drink. Coca Cola. It was aired during the World Cup. The advertisement show many people from different countries playing football. They looked very happy and energetic. The music was catchy. Upbeat song. I like this ad because it promote unity and friendship. It suggest that sport can bring people together. The visual effect was stunning. Colorful and bright. I saw it many times on TV. It make me want to buy the drink. I think a good advertisement should be creative and emotional. This one was very successful. Even now, when I hear the music, I remember the video. It is memorable. Marketing is very powerful tool to influence customer behavior.",
        "word_count": 133,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'advertisement show' → 'advertisement showed'", "grammar: 'it promote' → 'it promoted'", "grammar: 'It suggest' → 'It suggested'", "grammar: 'visual effect' → 'visual effects'", "grammar: 'It make me' → 'It made me'", "grammar: 'powerful tool' → 'a powerful tool'", "grammar: 'customer behavior' → 'consumer behavior'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "variable", "flexibility": "moderate"},
        "vocab_reason": "[LR6] Vocabulary: 'commercial', 'aired', 'energetic', 'catchy', 'upbeat', 'promote', 'unity', 'visual effect', 'stunning', 'creative', 'emotional', 'memorable', 'marketing', 'influence'.",
        "grammar_reason": "[GRA5] Basic sentences OK. 'I like this ad because it promote...' (Reason). 'It suggest that sport can...' (Noun clause). Tense/agreement errors ('show', 'promote', 'suggest', 'make').",
        "vocabulary": 6,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe an advertisement you remember.\n\nTranscript: I remember a TV commercial for a soft drink. Coca Cola. It was aired during the World Cup. The advertisement show many people from different countries playing football. They looked very happy and energetic. The music was catchy. Upbeat song. I like this ad because it promote unity and friendship. It suggest that sport can bring people together. The visual effect was stunning. Colorful and bright. I saw it many times on TV. It make me want to buy the drink. I think a good advertisement should be creative and emotional. This one was very successful. Even now, when I hear the music, I remember the video. It is memorable. Marketing is very powerful tool to influence customer behavior.\n\nWord Count: 133 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses 'commercial', 'aired', 'catchy', 'upbeat', 'promote', 'unity', 'visual effect', 'stunning', 'influence'.\n\n>Band 5: Uses less common items.\n\nNot Band 7: Some collocations are slightly off.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Uses 'because', 'that', 'when'. 'It suggest that...'. Tense errors ('show', 'promote', 'make' - present instead of past/agreement).\n\n>Band 4: Uses complex structures.\n\nNot Band 6: Systematic errors.\n\n**Micro flaws identified:**\n- 'advertisement show' should be 'advertisement showed'\n- 'it promote' should be 'it promoted'\n- 'It suggest' should be 'It suggested'\n- 'It make me' should be 'It made me'"
    },
    # 54. V6/G5 - Bad Weather
    {
        "sample_id": "syn_p2_v6_g5_0054",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe an experience you had with bad weather.",
        "transcript_cleaned": "I want to talk about a typhoon I experienced last summer. It was terrible. The wind was blowing very hard. Howling. The rain was pouring down. Heavy rain. I was at home with my family. We were very scare. The electricity went out. It was dark. We lit candles. I saw trees falling down on the street. It was dangerous. The roof of my neighbor's house was damage. Blown away. We stayed inside for two days. We cannot go out. We ate instant noodles. Canned food. After the typhoon, the city was flooded. It took one week to clean up. It was a disaster. I realized the power of nature. We should respect it. Global warming cause more extreme weather. We need to protect environment.",
        "word_count": 136,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'We were very scare' → 'We were very scared'", "grammar: 'was damage' → 'was damaged'", "grammar: 'We cannot go out' → 'We could not go out'", "grammar: 'Global warming cause' → 'Global warming causes'", "grammar: 'protect environment' → 'protect the environment'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "variable", "flexibility": "moderate"},
        "vocab_reason": "[LR6] Vocabulary: 'typhoon', 'experienced', 'howling', 'pouring', 'electricity', 'damage', 'canned food', 'flooded', 'disaster', 'global warming', 'extreme weather', 'protect'.",
        "grammar_reason": "[GRA5] Basic sentences OK. 'I saw trees falling down' (Participle). 'We were very scare' (Form error). 'We cannot go out' (Tense). 'Global warming cause' (Agreement). Simple sentences dominate.",
        "vocabulary": 6,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe an experience you had with bad weather.\n\nTranscript: I want to talk about a typhoon I experienced last summer. It was terrible. The wind was blowing very hard. Howling. The rain was pouring down. Heavy rain. I was at home with my family. We were very scare. The electricity went out. It was dark. We lit candles. I saw trees falling down on the street. It was dangerous. The roof of my neighbor's house was damage. Blown away. We stayed inside for two days. We cannot go out. We ate instant noodles. Canned food. After the typhoon, the city was flooded. It took one week to clean up. It was a disaster. I realized the power of nature. We should respect it. Global warming cause more extreme weather. We need to protect environment.\n\nWord Count: 136 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses 'typhoon', 'howling', 'pouring', 'electricity', 'flooded', 'disaster', 'global warming', 'extreme weather'.\n\n>Band 5: Uses topic-specific words.\n\nNot Band 7: Limited precision.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Basic sentences OK. 'I saw trees falling...'. Errors: 'We were very scare', 'was damage', 'cannot go out'.\n\n>Band 4: Uses complex structures.\n\nNot Band 6: Frequent errors.\n\n**Micro flaws identified:**\n- 'very scare' should be 'very scared'\n- 'was damage' should be 'was damaged'\n- 'cannot go out' should be 'could not go out'\n- 'Global warming cause' should be 'Global warming causes'"
    },
    # 55. V6/G5 - Gift (Received)
    {
        "sample_id": "syn_p2_v6_g5_0055",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a gift you received that you liked.",
        "transcript_cleaned": "I received a watch from my father on my 18th birthday. It is a silver watch. Very elegant and stylish. Brand name is Seiko. I was thrilled when I opened the box. I didn't expect such expensive gift. My father said it is a reward for my graduation. High school. I wear it every day now. It match with all my clothes. It help me manage my time better. Punctuality is important. The watch has sentimental value to me. It remind me of my father's love. I cherish it very much. I will keep it forever. Maybe one day I will give it to my son. Pass it down. It is not just a tool to tell time. It is a symbol of maturity. Responsibility. I am grateful for this gift.",
        "word_count": 139,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'Brand name is' → 'The brand name is'", "grammar: 'such expensive gift' → 'such an expensive gift'", "grammar: 'It match with' → 'It matches'", "grammar: 'It help me' → 'It helps me'", "grammar: 'It remind me' → 'It reminds me'", "grammar: 'Pass it down' → 'Pass it down' (Fragment)"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "variable", "flexibility": "moderate"},
        "vocab_reason": "[LR6] Vocabulary: 'elegant', 'stylish', 'thrilled', 'reward', 'graduation', 'punctuality', 'sentimental value', 'cherish', 'maturity', 'responsibility', 'grateful'. Good range.",
        "grammar_reason": "[GRA5] Basic sentences OK. 'I was thrilled when I opened...' (Time clause). 'It help me manage...' (Agreement error). 'It remind me...' (Agreement). 'It match...' (Agreement).",
        "vocabulary": 6,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a gift you received that you liked.\n\nTranscript: I received a watch from my father on my 18th birthday. It is a silver watch. Very elegant and stylish. Brand name is Seiko. I was thrilled when I opened the box. I didn't expect such expensive gift. My father said it is a reward for my graduation. High school. I wear it every day now. It match with all my clothes. It help me manage my time better. Punctuality is important. The watch has sentimental value to me. It remind me of my father's love. I cherish it very much. I will keep it forever. Maybe one day I will give it to my son. Pass it down. It is not just a tool to tell time. It is a symbol of maturity. Responsibility. I am grateful for this gift.\n\nWord Count: 139 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses 'elegant', 'stylish', 'thrilled', 'reward', 'punctuality', 'sentimental value', 'cherish', 'maturity'.\n\n>Band 5: Uses less common items.\n\nNot Band 7: Limited flexibility.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Basic sentences OK. 'I was thrilled when...'. Agreement errors ('It match', 'It help', 'It remind').\n\n>Band 4: Uses complex structures.\n\nNot Band 6: Systematic errors.\n\n**Micro flaws identified:**\n- 'It match' should be 'It matches'\n- 'It help' should be 'It helps'\n- 'It remind' should be 'It reminds'\n- 'such expensive gift' should be 'such an expensive gift'"
    },
    # 56. V6/G5 - Special Meal
    {
        "sample_id": "syn_p2_v6_g5_0056",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a special meal you had.",
        "transcript_cleaned": "I want to describe a dinner I had on New Year's Eve. My mother cooked a big feast for the family. Traditional dishes. Roast chicken, spring rolls, and sticky rice. The food looked mouth-watering. Delicious aroma filling the house. We gathered around the table. Everyone was in high spirit. Cheerful. We ate and talked about our resolution for new year. I enjoyed the spring rolls the most. Crispy and flavorful. My mother is an excellent cook. Culinary skill. The meal was special not because of the food, but the company. Being with family. It was a warm atmosphere. We toasted with wine. Celebrated. I felt very blessed. I think sharing meal with loved ones is the best happiness. It strengthen our bond.",
        "word_count": 133,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'in high spirit' → 'in high spirits'", "grammar: 'resolution for new year' → 'resolutions for the new year'", "grammar: 'Culinary skill' → 'She has great culinary skills'", "grammar: 'not because of the food, but the company' → 'not only because of the food, but also the company'", "grammar: 'sharing meal' → 'sharing a meal'", "grammar: 'It strengthen' → 'It strengthens'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "variable", "flexibility": "moderate"},
        "vocab_reason": "[LR6] Vocabulary: 'feast', 'traditional', 'mouth-watering', 'aroma', 'gathered', 'resolution', 'crispy', 'flavorful', 'culinary', 'atmosphere', 'toasted', 'blessed', 'strengthen', 'bond'.",
        "grammar_reason": "[GRA5] Basic sentences OK. 'The meal was special not because..., but...' (Contrast). 'It strengthen our bond' (Agreement error). 'Everyone was in high spirit' (Idiom error).",
        "vocabulary": 6,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a special meal you had.\n\nTranscript: I want to describe a dinner I had on New Year's Eve. My mother cooked a big feast for the family. Traditional dishes. Roast chicken, spring rolls, and sticky rice. The food looked mouth-watering. Delicious aroma filling the house. We gathered around the table. Everyone was in high spirit. Cheerful. We ate and talked about our resolution for new year. I enjoyed the spring rolls the most. Crispy and flavorful. My mother is an excellent cook. Culinary skill. The meal was special not because of the food, but the company. Being with family. It was a warm atmosphere. We toasted with wine. Celebrated. I felt very blessed. I think sharing meal with loved ones is the best happiness. It strengthen our bond.\n\nWord Count: 133 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses 'feast', 'mouth-watering', 'aroma', 'resolution', 'flavorful', 'culinary', 'blessed', 'strengthen bond'.\n\n>Band 5: Uses less common words.\n\nNot Band 7: Some phrasing is unnatural.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Basic sentences OK. 'The meal was special not because...'. Agreement errors ('It strengthen'). Idiom error ('high spirit').\n\n>Band 4: Uses complex structures.\n\nNot Band 6: Systematic errors.\n\n**Micro flaws identified:**\n- 'It strengthen' should be 'It strengthens'\n- 'in high spirit' should be 'in high spirits'\n- 'sharing meal' should be 'sharing a meal'"
    },
    # 57. V6/G5 - Hobby (Learning)
    {
        "sample_id": "syn_p2_v6_g5_0057",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a new skill you learned.",
        "transcript_cleaned": "I started learning to play the guitar six months ago. I always wanted to play a musical instrument. I bought an acoustic guitar online. It was affordable. I watch tutorial videos on YouTube. Self-taught. It was very difficult at first. My fingers hurt. Blisters. I couldn't press the strings properly. The sound was terrible. Buzzing. But I didn't give up. I practiced every day for one hour. Slowly, I improved. Now I can play some simple songs. Chords. I feel a sense of accomplishment. Playing guitar helps me relax. It is therapeutic. When I am stressed, I play guitar. It distract me from my problems. I want to learn more complex songs in future. Maybe form a band. It is a rewarding hobby.",
        "word_count": 133,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'I watch tutorial videos' → 'I watched tutorial videos'", "grammar: 'It distract me' → 'It distracts me'", "grammar: 'in future' → 'in the future'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "variable", "flexibility": "moderate"},
        "vocab_reason": "[LR6] Vocabulary: 'instrument', 'acoustic', 'affordable', 'tutorial', 'self-taught', 'blisters', 'strings', 'buzzing', 'accomplishment', 'therapeutic', 'distract', 'complex', 'rewarding'.",
        "grammar_reason": "[GRA5] Basic sentences OK. 'When I am stressed, I play guitar' (Time clause). 'It distract me' (Agreement error). Tense inconsistency ('watch' instead of 'watched').",
        "vocabulary": 6,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a new skill you learned.\n\nTranscript: I started learning to play the guitar six months ago. I always wanted to play a musical instrument. I bought an acoustic guitar online. It was affordable. I watch tutorial videos on YouTube. Self-taught. It was very difficult at first. My fingers hurt. Blisters. I couldn't press the strings properly. The sound was terrible. Buzzing. But I didn't give up. I practiced every day for one hour. Slowly, I improved. Now I can play some simple songs. Chords. I feel a sense of accomplishment. Playing guitar helps me relax. It is therapeutic. When I am stressed, I play guitar. It distract me from my problems. I want to learn more complex songs in future. Maybe form a band. It is a rewarding hobby.\n\nWord Count: 133 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses 'acoustic', 'tutorial', 'self-taught', 'blisters', 'accomplishment', 'therapeutic', 'distract', 'rewarding'.\n\n>Band 5: Uses topic-specific words.\n\nNot Band 7: Limited precision.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Basic sentences OK. 'When I am stressed...'. Agreement errors ('It distract'). Tense errors ('watch').\n\n>Band 4: Uses complex structures.\n\nNot Band 6: Systematic errors.\n\n**Micro flaws identified:**\n- 'It distract me' should be 'It distracts me'\n- 'I watch' should be 'I watched'\n- 'in future' should be 'in the future'"
    },
    # 58. V6/G5 - Place to Study
    {
        "sample_id": "syn_p2_v6_g5_0058",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a place where you can read or study.",
        "transcript_cleaned": "I usually go to a coffee shop near my university to study. It is called 'The Study Hub'. The atmosphere there is very cozy and quiet. Conducive to learning. They play soft jazz music. Background music. It helps me concentrate. The coffee is delicious too. Caffeine boost. I order a latte and sit in the corner. There are many students there. Everyone is studying or working on laptop. It motivate me to work hard. Peer pressure. The lighting is warm. Not too bright. I can read for hours without eye strain. I prefer this place than library. Library is too silent. Scary. Coffee shop has some noise. White noise. It makes me feel relaxed. I am productive there. I finished my thesis there last semester.",
        "word_count": 139,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'It motivate me' → 'It motivates me'", "grammar: 'working on laptop' → 'working on laptops/their laptops'", "grammar: 'prefer this place than' → 'prefer this place to'", "grammar: 'Library is too silent' → 'The library is too silent'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "variable", "flexibility": "moderate"},
        "vocab_reason": "[LR6] Vocabulary: 'atmosphere', 'cozy', 'conducive', 'concentrate', 'caffeine', 'boost', 'motivate', 'peer pressure', 'eye strain', 'productive', 'thesis', 'white noise'.",
        "grammar_reason": "[GRA5] Basic sentences OK. 'It helps me concentrate' (Causative). 'It motivate me' (Agreement error). 'I prefer this place than library' (Preposition error).",
        "vocabulary": 6,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a place where you can read or study.\n\nTranscript: I usually go to a coffee shop near my university to study. It is called 'The Study Hub'. The atmosphere there is very cozy and quiet. Conducive to learning. They play soft jazz music. Background music. It helps me concentrate. The coffee is delicious too. Caffeine boost. I order a latte and sit in the corner. There are many students there. Everyone is studying or working on laptop. It motivate me to work hard. Peer pressure. The lighting is warm. Not too bright. I can read for hours without eye strain. I prefer this place than library. Library is too silent. Scary. Coffee shop has some noise. White noise. It makes me feel relaxed. I am productive there. I finished my thesis there last semester.\n\nWord Count: 139 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses 'atmosphere', 'cozy', 'conducive', 'concentrate', 'caffeine', 'motivate', 'eye strain', 'productive', 'thesis'.\n\n>Band 5: Uses less common words.\n\nNot Band 7: Some phrasing is choppy.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Basic sentences OK. Agreement errors ('It motivate'). Preposition error ('prefer than').\n\n>Band 4: Uses complex structures.\n\nNot Band 6: Systematic errors.\n\n**Micro flaws identified:**\n- 'It motivate me' should be 'It motivates me'\n- 'prefer this place than' should be 'prefer this place to'\n- 'working on laptop' should be 'working on laptops'"
    },
    # 59. V6/G5 - Complaint
    {
        "sample_id": "syn_p2_v6_g5_0059",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a time you made a complaint.",
        "transcript_cleaned": "I made a complaint at a restaurant last week. I ordered a steak. Medium rare. But when the waiter brought it, it was well done. Overcooked. Tough like rubber. I was disappointed. I called the waiter and explained the problem politely. He was apologetic. He took the steak back to kitchen. The manager came to my table. He apologize to me. He offered me a free dessert. Compensation. I accepted it. I think it is important to complain when service is bad. We pay money for good quality. If we stay silent, they will not improve. Customer rights. I was satisfied with how they handled the situation. Professional. I will go there again because they respect customer. It was a minor mistake but good recovery.",
        "word_count": 136,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'He apologize' → 'He apologized'", "grammar: 'pay money for' → 'pay for'", "grammar: 'respect customer' → 'respect customers'", "grammar: 'took the steak back to kitchen' → 'took the steak back to the kitchen'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "variable", "flexibility": "moderate"},
        "vocab_reason": "[LR6] Vocabulary: 'medium rare', 'well done', 'overcooked', 'tough', 'disappointed', 'politely', 'apologetic', 'compensation', 'satisfied', 'handled', 'professional', 'recovery', 'customer rights'.",
        "grammar_reason": "[GRA5] Basic sentences OK. 'I think it is important to complain when service is bad' (Time clause). 'If we stay silent, they will not improve' (Conditional). Tense/agreement errors ('He apologize', 'respect customer').",
        "vocabulary": 6,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a time you made a complaint.\n\nTranscript: I made a complaint at a restaurant last week. I ordered a steak. Medium rare. But when the waiter brought it, it was well done. Overcooked. Tough like rubber. I was disappointed. I called the waiter and explained the problem politely. He was apologetic. He took the steak back to kitchen. The manager came to my table. He apologize to me. He offered me a free dessert. Compensation. I accepted it. I think it is important to complain when service is bad. We pay money for good quality. If we stay silent, they will not improve. Customer rights. I was satisfied with how they handled the situation. Professional. I will go there again because they respect customer. It was a minor mistake but good recovery.\n\nWord Count: 136 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses 'medium rare', 'overcooked', 'apologetic', 'compensation', 'satisfied', 'professional', 'recovery'.\n\n>Band 5: Uses topic-specific words.\n\nNot Band 7: Limited flexibility.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Basic sentences OK. Uses 'when', 'if'. 'He apologize' (Tense error). 'respect customer' (Agreement).\n\n>Band 4: Uses complex structures.\n\nNot Band 6: Systematic errors.\n\n**Micro flaws identified:**\n- 'He apologize' should be 'He apologized'\n- 'respect customer' should be 'respect customers'"
    },
    # 60. V6/G5 - Decision
    {
        "sample_id": "syn_p2_v6_g5_0060",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a difficult decision you made.",
        "transcript_cleaned": "I had to make a difficult decision when I finished high school. I had to choose my university major. My parents wanted me to study medicine. To be a doctor. Prestigious job. But I wanted to study art. Graphic design. I am passionate about drawing. Creativity. It was a dilemma. Conflict. I thought about it for a long time. Pros and cons. I didn't want to disappoint my parents. But I also want to follow my dream. Finally, I chose art. I explained to my parents. I told them I will be happy if I do what I love. They were sad at first. But they accept it now. I am studying design and I enjoy it. I think I made the right choice. No regret. It taught me to be independent.",
        "word_count": 138,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'But I also want' → 'But I also wanted'", "grammar: 'I told them I will be happy' → 'I told them I would be happy'", "grammar: 'But they accept it now' → 'But they accept it now' (Correct)", "grammar: 'No regret' → 'No regrets'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "variable", "flexibility": "moderate"},
        "vocab_reason": "[LR6] Vocabulary: 'major', 'medicine', 'prestigious', 'graphic design', 'passionate', 'creativity', 'dilemma', 'conflict', 'pros and cons', 'disappoint', 'independent', 'regret'.",
        "grammar_reason": "[GRA5] Basic sentences OK. 'I told them I will be happy if I do what I love' (Reported speech + Conditional). Tense errors ('want' instead of 'wanted', 'will' instead of 'would').",
        "vocabulary": 6,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a difficult decision you made.\n\nTranscript: I had to make a difficult decision when I finished high school. I had to choose my university major. My parents wanted me to study medicine. To be a doctor. Prestigious job. But I wanted to study art. Graphic design. I am passionate about drawing. Creativity. It was a dilemma. Conflict. I thought about it for a long time. Pros and cons. I didn't want to disappoint my parents. But I also want to follow my dream. Finally, I chose art. I explained to my parents. I told them I will be happy if I do what I love. They were sad at first. But they accept it now. I am studying design and I enjoy it. I think I made the right choice. No regret. It taught me to be independent.\n\nWord Count: 138 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses 'major', 'prestigious', 'passionate', 'dilemma', 'pros and cons', 'disappoint', 'independent'.\n\n>Band 5: Uses less common words.\n\nNot Band 7: Limited precision.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Basic sentences OK. 'I told them I will be happy...'. Tense errors ('want', 'will').\n\n>Band 4: Uses complex structures.\n\nNot Band 6: Systematic errors.\n\n**Micro flaws identified:**\n- 'But I also want' should be 'But I also wanted'\n- 'I will be happy' should be 'I would be happy'\n- 'No regret' should be 'No regrets'"
    }
]

with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
    for sample in samples:
        f.write(json.dumps(sample) + '\n')
