import json

OUTPUT_FILE = "ielts-data/phase3/v76_review_output/synthetic_batches/batch_p2_09.jsonl"

samples = [
    # 441. V5/G6 - Job (Future)
    {
        "sample_id": "syn_p2_v5_g6_0441",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a job you want to do in the future.",
        "transcript_cleaned": "I would like to be a doctor in the future. I think it is a very good job because I can help sick people. I have to study medicine at university for many years. It will be hard, but I am ready to work hard. Doctors work in hospitals and clinics. They wear white coats and use special tools. I want to cure diseases and make people healthy. Although the job is stressful, it is also rewarding. I admire doctors because they save lives. If I become a doctor, my parents will be very proud of me.",
        "word_count": 102,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR5] Vocabulary: 'doctor', 'sick', 'medicine', 'university', 'hard', 'hospitals', 'clinics', 'white coats', 'tools', 'cure', 'diseases', 'healthy', 'stressful', 'rewarding', 'admire', 'save lives', 'proud'. Functional vocabulary relevant to the topic. >Band 4: Uses specific words ('cure', 'diseases'). Not Band 6: Simple vocabulary.",
        "grammar_reason": "[GRA6] Uses a mix of simple and complex structures. 'Although the job is stressful...' (Concessive clause). 'If I become a doctor...' (First conditional). 'Because I can help...' (Reason clause). Generally error-free. >Band 5: Uses complex structures accurately. Not Band 7: Limited range.",
        "vocabulary": 5,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a job you want to do in the future.\n\nTranscript: I would like to be a doctor in the future. I think it is a very good job because I can help sick people. I have to study medicine at university for many years. It will be hard, but I am ready to work hard. Doctors work in hospitals and clinics. They wear white coats and use special tools. I want to cure diseases and make people healthy. Although the job is stressful, it is also rewarding. I admire doctors because they save lives. If I become a doctor, my parents will be very proud of me.\n\nWord Count: 102 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses topic words: 'cure', 'diseases', 'rewarding'. Meaning is clear.\n\n>Band 4: Adequate vocabulary.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Uses a mix of simple and complex structures accurately. Includes conditionals and concessive clauses.\n\n>Band 5: Good control of complex forms.\n\nNot Band 7: Range is limited.\n\n**Micro flaws identified:**\n- None."
    },
    # 442. V5/G6 - Place (Travel)
    {
        "sample_id": "syn_p2_v5_g6_0442",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a place you would like to visit.",
        "transcript_cleaned": "I want to visit Paris, which is the capital of France. It is famous for the Eiffel Tower. I have seen many pictures of it, and it looks beautiful. I want to go to the Louvre Museum to see the Mona Lisa. I also want to try French food like croissants and cheese. I heard that Paris is a romantic city. I would like to go there with my future husband. We could walk along the river Seine. Although the flight ticket is expensive, I will save money for this trip. It is my dream destination.",
        "word_count": 102,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR5] Vocabulary: 'capital', 'famous', 'pictures', 'beautiful', 'museum', 'French food', 'romantic', 'future husband', 'river', 'flight ticket', 'expensive', 'save money', 'dream destination'. Functional vocabulary relevant to the topic. >Band 4: Uses specific words ('romantic', 'destination'). Not Band 6: Simple vocabulary.",
        "grammar_reason": "[GRA6] Uses a mix of simple and complex structures. 'Which is the capital...' (Relative clause). 'Although the flight ticket is expensive...' (Concessive clause). 'I heard that...' (Noun clause). Generally error-free. >Band 5: Uses complex structures accurately. Not Band 7: Limited range.",
        "vocabulary": 5,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a place you would like to visit.\n\nTranscript: I want to visit Paris, which is the capital of France. It is famous for the Eiffel Tower. I have seen many pictures of it, and it looks beautiful. I want to go to the Louvre Museum to see the Mona Lisa. I also want to try French food like croissants and cheese. I heard that Paris is a romantic city. I would like to go there with my future husband. We could walk along the river Seine. Although the flight ticket is expensive, I will save money for this trip. It is my dream destination.\n\nWord Count: 102 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses topic words: 'romantic', 'destination', 'expensive'. Meaning is clear.\n\n>Band 4: Adequate vocabulary.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Uses a mix of simple and complex structures accurately. Includes relative clauses and noun clauses.\n\n>Band 5: Good control of complex forms.\n\nNot Band 7: Range is limited.\n\n**Micro flaws identified:**\n- None."
    },
    # 443. V5/G6 - Event (Concert)
    {
        "sample_id": "syn_p2_v5_g6_0443",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a concert you attended.",
        "transcript_cleaned": "I went to a rock concert last month with my friends. The band played at a big stadium in the city. There were thousands of people there. The music was very loud and energetic. I knew all the songs, so I sang along. The lights on the stage were amazing. I felt very excited and happy. We danced for two hours. Although my feet were tired, I did not want to stop. It was the best night of my life. I hope I can see them perform again next year.",
        "word_count": 99,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR5] Vocabulary: 'rock concert', 'band', 'stadium', 'loud', 'energetic', 'songs', 'sang along', 'stage', 'amazing', 'excited', 'danced', 'tired', 'perform'. Functional vocabulary relevant to the topic. >Band 4: Uses specific words ('energetic', 'perform'). Not Band 6: Simple vocabulary.",
        "grammar_reason": "[GRA6] Uses a mix of simple and complex structures. 'Although my feet were tired...' (Concessive clause). 'So I sang along' (Result clause). Past tense used correctly throughout. Generally error-free. >Band 5: Uses complex structures accurately. Not Band 7: Limited range.",
        "vocabulary": 5,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a concert you attended.\n\nTranscript: I went to a rock concert last month with my friends. The band played at a big stadium in the city. There were thousands of people there. The music was very loud and energetic. I knew all the songs, so I sang along. The lights on the stage were amazing. I felt very excited and happy. We danced for two hours. Although my feet were tired, I did not want to stop. It was the best night of my life. I hope I can see them perform again next year.\n\nWord Count: 99 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses topic words: 'energetic', 'perform', 'stadium'. Meaning is clear.\n\n>Band 4: Adequate vocabulary.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Uses a mix of simple and complex structures accurately. Includes concessive clauses and correct past tense usage.\n\n>Band 5: Good control of complex forms.\n\nNot Band 7: Range is limited.\n\n**Micro flaws identified:**\n- None."
    },
    # 444. V5/G6 - Person (Teacher)
    {
        "sample_id": "syn_p2_v5_g6_0444",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a teacher who helped you.",
        "transcript_cleaned": "I want to talk about my math teacher, Mrs. Jones. She taught me when I was in high school. I was not good at math, and I found it difficult. She noticed that I was struggling, so she offered to help me after class. She explained the problems clearly and patiently. Because of her help, I improved my grades. She was very kind and encouraging. I think she is a great teacher because she cares about her students. I will never forget her kindness. She inspired me to work harder.",
        "word_count": 98,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR5] Vocabulary: 'math teacher', 'high school', 'difficult', 'struggling', 'offered', 'explained', 'patiently', 'improved', 'grades', 'kind', 'encouraging', 'cares', 'inspired'. Functional vocabulary relevant to the topic. >Band 4: Uses specific words ('struggling', 'patiently'). Not Band 6: Simple vocabulary.",
        "grammar_reason": "[GRA6] Uses a mix of simple and complex structures. 'When I was in high school' (Time clause). 'She noticed that...' (Noun clause). 'Because of her help...' (Reason phrase). Generally error-free. >Band 5: Uses complex structures accurately. Not Band 7: Limited range.",
        "vocabulary": 5,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a teacher who helped you.\n\nTranscript: I want to talk about my math teacher, Mrs. Jones. She taught me when I was in high school. I was not good at math, and I found it difficult. She noticed that I was struggling, so she offered to help me after class. She explained the problems clearly and patiently. Because of her help, I improved my grades. She was very kind and encouraging. I think she is a great teacher because she cares about her students. I will never forget her kindness. She inspired me to work harder.\n\nWord Count: 98 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses topic words: 'struggling', 'patiently', 'encouraging'. Meaning is clear.\n\n>Band 4: Adequate vocabulary.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Uses a mix of simple and complex structures accurately. Includes noun clauses and time clauses.\n\n>Band 5: Good control of complex forms.\n\nNot Band 7: Range is limited.\n\n**Micro flaws identified:**\n- None."
    },
    # 445. V5/G6 - Activity (Free time)
    {
        "sample_id": "syn_p2_v5_g6_0445",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe what you do in your free time.",
        "transcript_cleaned": "In my free time, I enjoy playing football with my friends. We usually play on Saturday afternoons at the local park. It is a good way to exercise and have fun. I have been playing football since I was a child. I like it because it is a team sport. We have to work together to win the game. After the match, we often go for a drink. I think having a hobby is important for relaxing. Although I am sometimes tired, I always look forward to playing. It helps me forget about my studies.",
        "word_count": 103,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR5] Vocabulary: 'free time', 'football', 'local park', 'exercise', 'fun', 'team sport', 'win', 'match', 'drink', 'hobby', 'relaxing', 'tired', 'look forward', 'forget'. Functional vocabulary relevant to the topic. >Band 4: Uses specific words ('team sport', 'relaxing'). Not Band 6: Simple vocabulary.",
        "grammar_reason": "[GRA6] Uses a mix of simple and complex structures. 'Since I was a child' (Time clause). 'Although I am sometimes tired...' (Concessive clause). 'We have to work together...' (Modal verb). Generally error-free. >Band 5: Uses complex structures accurately. Not Band 7: Limited range.",
        "vocabulary": 5,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe what you do in your free time.\n\nTranscript: In my free time, I enjoy playing football with my friends. We usually play on Saturday afternoons at the local park. It is a good way to exercise and have fun. I have been playing football since I was a child. I like it because it is a team sport. We have to work together to win the game. After the match, we often go for a drink. I think having a hobby is important for relaxing. Although I am sometimes tired, I always look forward to playing. It helps me forget about my studies.\n\nWord Count: 103 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses topic words: 'exercise', 'match', 'relaxing'. Meaning is clear.\n\n>Band 4: Adequate vocabulary.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** Yes ('look forward')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Uses a mix of simple and complex structures accurately. Includes time clauses and concessive clauses.\n\n>Band 5: Good control of complex forms.\n\nNot Band 7: Range is limited.\n\n**Micro flaws identified:**\n- None."
    },
    # 446. V5/G6 - Object (Gift)
    {
        "sample_id": "syn_p2_v5_g6_0446",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a gift you would like to receive.",
        "transcript_cleaned": "I would like to receive a new camera for my birthday. I enjoy taking photos of nature and people. My current camera is old and does not work well. If I had a new camera, I could take better pictures. I want a digital camera with a good lens. It would allow me to capture beautiful moments. I could also make videos with it. Photography is my favorite hobby. I hope my parents will buy it for me. It is a bit expensive, but it would be the perfect gift.",
        "word_count": 100,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR5] Vocabulary: 'camera', 'birthday', 'photos', 'nature', 'work well', 'digital camera', 'lens', 'capture', 'moments', 'videos', 'photography', 'hobby', 'expensive', 'perfect'. Functional vocabulary relevant to the topic. >Band 4: Uses specific words ('lens', 'capture'). Not Band 6: Simple vocabulary.",
        "grammar_reason": "[GRA6] Uses a mix of simple and complex structures. 'If I had a new camera, I could take...' (Second conditional). 'It would allow me to...' (Modal verb). Generally error-free. >Band 5: Uses complex structures accurately. Not Band 7: Limited range.",
        "vocabulary": 5,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a gift you would like to receive.\n\nTranscript: I would like to receive a new camera for my birthday. I enjoy taking photos of nature and people. My current camera is old and does not work well. If I had a new camera, I could take better pictures. I want a digital camera with a good lens. It would allow me to capture beautiful moments. I could also make videos with it. Photography is my favorite hobby. I hope my parents will buy it for me. It is a bit expensive, but it would be the perfect gift.\n\nWord Count: 100 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses topic words: 'digital camera', 'lens', 'capture'. Meaning is clear.\n\n>Band 4: Adequate vocabulary.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Uses a mix of simple and complex structures accurately. Includes second conditional and modal verbs.\n\n>Band 5: Good control of complex forms.\n\nNot Band 7: Range is limited.\n\n**Micro flaws identified:**\n- None."
    },
    # 447. V5/G6 - Place (Home)
    {
        "sample_id": "syn_p2_v5_g6_0447",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe your ideal home.",
        "transcript_cleaned": "My ideal home would be a small house near the sea. I like the sound of the ocean, and the air is fresh there. The house would have a big garden with many flowers. I want to have a large window in the living room to see the view. It should have a modern kitchen because I like cooking. I would also like a quiet room for reading. Living near the sea would make me feel relaxed. Although it might be far from the city, I would not mind. It would be a peaceful place to live.",
        "word_count": 105,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR5] Vocabulary: 'ideal home', 'sea', 'ocean', 'fresh', 'garden', 'flowers', 'large window', 'living room', 'view', 'modern kitchen', 'cooking', 'quiet', 'reading', 'relaxed', 'peaceful'. Functional vocabulary relevant to the topic. >Band 4: Uses specific words ('modern', 'peaceful'). Not Band 6: Simple vocabulary.",
        "grammar_reason": "[GRA6] Uses a mix of simple and complex structures. 'My ideal home would be...' (Modal verb). 'Because I like cooking' (Reason clause). 'Although it might be...' (Concessive clause). Generally error-free. >Band 5: Uses complex structures accurately. Not Band 7: Limited range.",
        "vocabulary": 5,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe your ideal home.\n\nTranscript: My ideal home would be a small house near the sea. I like the sound of the ocean, and the air is fresh there. The house would have a big garden with many flowers. I want to have a large window in the living room to see the view. It should have a modern kitchen because I like cooking. I would also like a quiet room for reading. Living near the sea would make me feel relaxed. Although it might be far from the city, I would not mind. It would be a peaceful place to live.\n\nWord Count: 105 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses topic words: 'modern', 'relaxed', 'peaceful'. Meaning is clear.\n\n>Band 4: Adequate vocabulary.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Uses a mix of simple and complex structures accurately. Includes modal verbs and concessive clauses.\n\n>Band 5: Good control of complex forms.\n\nNot Band 7: Range is limited.\n\n**Micro flaws identified:**\n- None."
    },
    # 448. V5/G6 - Activity (Study)
    {
        "sample_id": "syn_p2_v5_g6_0448",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe how you study for exams.",
        "transcript_cleaned": "When I have an exam, I start studying two weeks before. I usually study in the library because it is quiet. I read my textbooks and make notes. I try to memorize important information. Sometimes I study with my friends. We ask each other questions to test our knowledge. I think this is a good way to learn. I also take breaks to rest my brain. I drink coffee to stay awake. If I do not understand something, I ask my teacher. I work hard because I want to get good grades.",
        "word_count": 100,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR5] Vocabulary: 'exam', 'studying', 'library', 'quiet', 'textbooks', 'notes', 'memorize', 'information', 'test', 'knowledge', 'breaks', 'rest', 'brain', 'coffee', 'awake', 'grades'. Functional vocabulary relevant to the topic. >Band 4: Uses specific words ('memorize', 'knowledge'). Not Band 6: Simple vocabulary.",
        "grammar_reason": "[GRA6] Uses a mix of simple and complex structures. 'When I have an exam...' (Time clause). 'If I do not understand...' (First conditional). 'Because it is quiet' (Reason clause). Generally error-free. >Band 5: Uses complex structures accurately. Not Band 7: Limited range.",
        "vocabulary": 5,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe how you study for exams.\n\nTranscript: When I have an exam, I start studying two weeks before. I usually study in the library because it is quiet. I read my textbooks and make notes. I try to memorize important information. Sometimes I study with my friends. We ask each other questions to test our knowledge. I think this is a good way to learn. I also take breaks to rest my brain. I drink coffee to stay awake. If I do not understand something, I ask my teacher. I work hard because I want to get good grades.\n\nWord Count: 100 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses topic words: 'memorize', 'knowledge', 'grades'. Meaning is clear.\n\n>Band 4: Adequate vocabulary.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Uses a mix of simple and complex structures accurately. Includes time clauses and conditionals.\n\n>Band 5: Good control of complex forms.\n\nNot Band 7: Range is limited.\n\n**Micro flaws identified:**\n- None."
    },
    # 449. V5/G6 - Object (Electronic)
    {
        "sample_id": "syn_p2_v5_g6_0449",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe an electronic device you use.",
        "transcript_cleaned": "I use my smartphone every day. It is very useful for my life. I can use it to call my friends and send messages. I also use it to browse the internet and find information. It has a good camera, so I take many photos. I listen to music on my phone when I am on the bus. It helps me pass the time. I bought it last year with my savings. Although the screen is small, it is clear. I would be lost without my phone. It is essential for communication.",
        "word_count": 100,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR5] Vocabulary: 'smartphone', 'useful', 'messages', 'browse', 'internet', 'information', 'camera', 'photos', 'music', 'pass the time', 'savings', 'screen', 'clear', 'lost', 'essential', 'communication'. Functional vocabulary relevant to the topic. >Band 4: Uses specific words ('browse', 'essential'). Not Band 6: Simple vocabulary.",
        "grammar_reason": "[GRA6] Uses a mix of simple and complex structures. 'When I am on the bus' (Time clause). 'Although the screen is small...' (Concessive clause). 'So I take many photos' (Result clause). Generally error-free. >Band 5: Uses complex structures accurately. Not Band 7: Limited range.",
        "vocabulary": 5,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe an electronic device you use.\n\nTranscript: I use my smartphone every day. It is very useful for my life. I can use it to call my friends and send messages. I also use it to browse the internet and find information. It has a good camera, so I take many photos. I listen to music on my phone when I am on the bus. It helps me pass the time. I bought it last year with my savings. Although the screen is small, it is clear. I would be lost without my phone. It is essential for communication.\n\nWord Count: 100 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses topic words: 'browse', 'essential', 'communication'. Meaning is clear.\n\n>Band 4: Adequate vocabulary.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** Yes ('pass the time')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Uses a mix of simple and complex structures accurately. Includes time clauses and concessive clauses.\n\n>Band 5: Good control of complex forms.\n\nNot Band 7: Range is limited.\n\n**Micro flaws identified:**\n- None."
    },
    # 450. V5/G6 - Event (Success)
    {
        "sample_id": "syn_p2_v5_g6_0450",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a success you achieved.",
        "transcript_cleaned": "I was very happy when I passed my driving test. I practiced for three months. It was difficult at first because I was nervous. My father taught me how to drive. I had to learn the traffic rules and how to park. On the day of the test, I was worried. However, I drove carefully and did not make any mistakes. The examiner told me that I passed. I felt very proud of myself. Getting my license was important because now I can drive to work. It was a big achievement for me.",
        "word_count": 100,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR5] Vocabulary: 'success', 'achieved', 'driving test', 'practiced', 'difficult', 'nervous', 'traffic rules', 'park', 'worried', 'carefully', 'mistakes', 'examiner', 'passed', 'proud', 'license', 'achievement'. Functional vocabulary relevant to the topic. >Band 4: Uses specific words ('license', 'achievement'). Not Band 6: Simple vocabulary.",
        "grammar_reason": "[GRA6] Uses a mix of simple and complex structures. 'Because I was nervous' (Reason clause). 'The examiner told me that...' (Noun clause). 'Because now I can drive...' (Reason clause). Generally error-free. >Band 5: Uses complex structures accurately. Not Band 7: Limited range.",
        "vocabulary": 5,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a success you achieved.\n\nTranscript: I was very happy when I passed my driving test. I practiced for three months. It was difficult at first because I was nervous. My father taught me how to drive. I had to learn the traffic rules and how to park. On the day of the test, I was worried. However, I drove carefully and did not make any mistakes. The examiner told me that I passed. I felt very proud of myself. Getting my license was important because now I can drive to work. It was a big achievement for me.\n\nWord Count: 100 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses topic words: 'license', 'examiner', 'achievement'. Meaning is clear.\n\n>Band 4: Adequate vocabulary.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Uses a mix of simple and complex structures accurately. Includes noun clauses and reason clauses.\n\n>Band 5: Good control of complex forms.\n\nNot Band 7: Range is limited.\n\n**Micro flaws identified:**\n- None."
    }
]

with open(OUTPUT_FILE, 'a', encoding='utf-8') as f:
    for sample in samples:
        f.write(json.dumps(sample) + '\n')
