import json

OUTPUT_FILE = "ielts-data/phase3/v76_review_output/synthetic_batches/batch_p2_15.jsonl"

samples = [
    # 701. V7/G7 - Book (Childhood)
    {
        "sample_id": "syn_p2_v7_g7_0701",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a book you loved as a child.",
        "transcript_cleaned": "I vividly remember reading 'Charlotte's Web' when I was a child. It is a heartwarming story about a pig named Wilbur and his friendship with a spider. The narrative explores themes of loyalty, mortality, and the cycle of life. I was captivated by the anthropomorphic characters and their emotional depth. Charlotte, the spider, uses her web-spinning skills to save Wilbur from slaughter. Her intelligence and kindness left a lasting impression on me. The ending is bittersweet, but it teaches valuable lessons about sacrifice. It is a classic of children's literature that remains relevant today.",
        "word_count": 96,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR7] Vocabulary: 'vividly remember', 'heartwarming', 'narrative', 'explores themes', 'loyalty', 'mortality', 'cycle of life', 'captivated', 'anthropomorphic', 'emotional depth', 'slaughter', 'impression', 'bittersweet', 'valuable lessons', 'sacrifice', 'literature', 'relevant'. Sophisticated descriptors. >Band 6: Precise vocabulary. Not Band 8: Some phrases are common.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'When I was a child' (Time clause). 'Named Wilbur' (Participle phrase). 'Uses her web-spinning skills to save...' (Infinitive of purpose). 'That remains relevant today' (Relative clause). Accurate.",
        "vocabulary": 7,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a book you loved as a child.\n\nTranscript: I vividly remember reading 'Charlotte's Web' when I was a child. It is a heartwarming story about a pig named Wilbur and his friendship with a spider. The narrative explores themes of loyalty, mortality, and the cycle of life. I was captivated by the anthropomorphic characters and their emotional depth. Charlotte, the spider, uses her web-spinning skills to save Wilbur from slaughter. Her intelligence and kindness left a lasting impression on me. The ending is bittersweet, but it teaches valuable lessons about sacrifice. It is a classic of children's literature that remains relevant today.\n\nWord Count: 96 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses topic words: 'anthropomorphic', 'bittersweet', 'sacrifice'. Meaning is clear.\n\n>Band 6: Advanced vocabulary.\n\nNot Band 8: Lacks native-like flow.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures accurately (participle phrases, infinitives). Sentences are error-free.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Limited variety.\n\n**Micro flaws identified:**\n- None."
    },
    # 702. V7/G7 - Place (City)
    {
        "sample_id": "syn_p2_v7_g7_0702",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a city you would like to live in for a short time.",
        "transcript_cleaned": "I would love to live in Edinburgh for a few months. It is a city steeped in history, with a dramatic skyline dominated by an ancient castle. I am drawn to its Gothic architecture and cobblestone streets. The city hosts the world's largest arts festival, the Edinburgh Fringe, which creates a vibrant atmosphere. I imagine myself exploring the hidden closes and literary pubs. The combination of cultural richness and stunning scenery is very appealing. Although the weather can be gloomy, the warmth of the people makes up for it. It would be an inspiring environment for a writer or artist.",
        "word_count": 100,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR7] Vocabulary: 'steeped in history', 'dramatic skyline', 'dominated', 'ancient castle', 'drawn to', 'Gothic architecture', 'cobblestone streets', 'vibrant atmosphere', 'exploring', 'hidden closes', 'literary pubs', 'cultural richness', 'stunning scenery', 'appealing', 'gloomy', 'warmth', 'inspiring environment'. Good range. >Band 6: Uses specific words ('steeped', 'closes'). Not Band 8: Lacks idiomatic flair.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'Dominated by an ancient castle' (Participle phrase). 'Which creates a vibrant atmosphere' (Relative clause). 'I imagine myself exploring...' (Gerund phrase). 'Although the weather can be gloomy...' (Concessive clause). Accurate.",
        "vocabulary": 7,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a city you would like to live in for a short time.\n\nTranscript: I would love to live in Edinburgh for a few months. It is a city steeped in history, with a dramatic skyline dominated by an ancient castle. I am drawn to its Gothic architecture and cobblestone streets. The city hosts the world's largest arts festival, the Edinburgh Fringe, which creates a vibrant atmosphere. I imagine myself exploring the hidden closes and literary pubs. The combination of cultural richness and stunning scenery is very appealing. Although the weather can be gloomy, the warmth of the people makes up for it. It would be an inspiring environment for a writer or artist.\n\nWord Count: 100 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses descriptive words: 'steeped', 'dramatic', 'vibrant', 'gloomy'. Clear meaning.\n\n>Band 6: Advanced vocabulary.\n\nNot Band 8: Lacks native-like flow.\n\n**Idiom present:** Yes ('steeped in history')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures accurately (participle phrases, relative clauses). Good control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Limited variety.\n\n**Micro flaws identified:**\n- None."
    },
    # 703. V7/G7 - Event (Party)
    {
        "sample_id": "syn_p2_v7_g7_0703",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a party you organized.",
        "transcript_cleaned": "I organized a farewell party for a colleague who was moving abroad. It was a bittersweet occasion, mixed with joy and sadness. I booked a private room at a cozy restaurant and decorated it with photos and messages. The planning required attention to detail, from the menu to the music playlist. I wanted to create a memorable send-off for her. We shared anecdotes and toasted to her future success. Seeing her emotional reaction made all the effort worthwhile. It was a meaningful way to show our appreciation for her friendship.",
        "word_count": 91,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR7] Vocabulary: 'farewell party', 'colleague', 'abroad', 'bittersweet occasion', 'booked', 'private room', 'cozy', 'planning', 'attention to detail', 'playlist', 'memorable send-off', 'anecdotes', 'toasted', 'future success', 'emotional reaction', 'worthwhile', 'meaningful', 'appreciation'. Sophisticated descriptors. >Band 6: Precise vocabulary. Not Band 8: Lacks idiomatic depth.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'Who was moving abroad' (Relative clause). 'Mixed with joy and sadness' (Participle phrase). 'To create a memorable send-off' (Infinitive of purpose). 'Seeing her emotional reaction...' (Gerund subject). Accurate.",
        "vocabulary": 7,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a party you organized.\n\nTranscript: I organized a farewell party for a colleague who was moving abroad. It was a bittersweet occasion, mixed with joy and sadness. I booked a private room at a cozy restaurant and decorated it with photos and messages. The planning required attention to detail, from the menu to the music playlist. I wanted to create a memorable send-off for her. We shared anecdotes and toasted to her future success. Seeing her emotional reaction made all the effort worthwhile. It was a meaningful way to show our appreciation for her friendship.\n\nWord Count: 91 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses topic words: 'bittersweet', 'anecdotes', 'send-off'. Meaning is clear.\n\n>Band 6: Advanced vocabulary.\n\nNot Band 8: Lacks sophistication.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures accurately. Includes relative clauses and gerund subjects. Good control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Limited variety.\n\n**Micro flaws identified:**\n- None."
    },
    # 704. V7/G7 - Person (Teacher)
    {
        "sample_id": "syn_p2_v7_g7_0704",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a teacher who had a strong impact on you.",
        "transcript_cleaned": "I would like to talk about Mrs. Thompson, my high school art teacher. She was an eccentric and inspiring figure who encouraged creativity. Unlike other teachers, she prioritized individual expression over strict rules. She introduced us to various artistic movements, from Impressionism to Surrealism. I was fascinated by her passion for art history. She taught me to see the world from different perspectives. Her constructive criticism helped me refine my skills and build confidence. Because of her influence, I decided to pursue a degree in graphic design. She truly shaped my career path.",
        "word_count": 94,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR7] Vocabulary: 'eccentric', 'inspiring figure', 'encouraged creativity', 'prioritized', 'individual expression', 'strict rules', 'artistic movements', 'Impressionism', 'Surrealism', 'fascinated', 'passion', 'perspectives', 'constructive criticism', 'refine skills', 'build confidence', 'influence', 'pursue', 'degree', 'shaped', 'career path'. Very sophisticated. >Band 6: Precise vocabulary. Not Band 8: Some phrases are common.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'Who encouraged creativity' (Relative clause). 'Unlike other teachers...' (Contrast phrase). 'To see the world from different perspectives' (Infinitive phrase). 'Because of her influence' (Reason phrase). Accurate.",
        "vocabulary": 7,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a teacher who had a strong impact on you.\n\nTranscript: I would like to talk about Mrs. Thompson, my high school art teacher. She was an eccentric and inspiring figure who encouraged creativity. Unlike other teachers, she prioritized individual expression over strict rules. She introduced us to various artistic movements, from Impressionism to Surrealism. I was fascinated by her passion for art history. She taught me to see the world from different perspectives. Her constructive criticism helped me refine my skills and build confidence. Because of her influence, I decided to pursue a degree in graphic design. She truly shaped my career path.\n\nWord Count: 94 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses descriptive words: 'eccentric', 'constructive', 'refine'. Clear meaning.\n\n>Band 6: Advanced vocabulary.\n\nNot Band 8: Lacks native-like flow.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures accurately (relative clauses, contrast). Sentences are error-free.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Limited variety.\n\n**Micro flaws identified:**\n- None."
    },
    # 705. V7/G7 - Object (Technology)
    {
        "sample_id": "syn_p2_v7_g7_0705",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a piece of technology you couldn't live without.",
        "transcript_cleaned": "I could not live without my laptop, which is an essential tool for both work and leisure. It is a sleek, high-performance machine that allows me to multitask efficiently. I rely on it for drafting reports, attending virtual meetings, and managing my finances. The portability means I can work from anywhere, whether at a cafe or on a train. I also use it to stream movies and edit photos in my free time. It stores all my important documents and memories. Without it, I would feel disconnected and unproductive. It is the hub of my digital life.",
        "word_count": 98,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR7] Vocabulary: 'essential tool', 'leisure', 'sleek', 'high-performance', 'multitask efficiently', 'rely on', 'drafting reports', 'virtual meetings', 'managing finances', 'portability', 'stream movies', 'edit photos', 'stores', 'documents', 'disconnected', 'unproductive', 'hub', 'digital life'. Good range. >Band 6: Uses specific words ('sleek', 'hub'). Not Band 8: Lacks idiomatic flair.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'Which is an essential tool' (Relative clause). 'That allows me to multitask' (Relative clause). 'Whether at a cafe or on a train' (Correlative). 'Without it, I would feel...' (Second conditional). Accurate.",
        "vocabulary": 7,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a piece of technology you couldn't live without.\n\nTranscript: I could not live without my laptop, which is an essential tool for both work and leisure. It is a sleek, high-performance machine that allows me to multitask efficiently. I rely on it for drafting reports, attending virtual meetings, and managing my finances. The portability means I can work from anywhere, whether at a cafe or on a train. I also use it to stream movies and edit photos in my free time. It stores all my important documents and memories. Without it, I would feel disconnected and unproductive. It is the hub of my digital life.\n\nWord Count: 98 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses descriptive words: 'sleek', 'multitask', 'unproductive'. Clear meaning.\n\n>Band 6: Advanced vocabulary.\n\nNot Band 8: Lacks sophistication.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures accurately. Includes relative clauses and conditionals. Good control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Limited variety.\n\n**Micro flaws identified:**\n- None."
    },
    # 706. V7/G7 - Activity (Exercise)
    {
        "sample_id": "syn_p2_v7_g7_0706",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe an exercise you do regularly.",
        "transcript_cleaned": "I regularly practice kickboxing to maintain my physical fitness. It is a high-intensity workout that combines martial arts techniques with cardio. I attend classes at a local gym three times a week. The routine involves punching, kicking, and various defensive moves. It is an excellent way to relieve stress and aggression. I find it empowering to learn self-defense skills. After each session, I feel exhausted but invigorated. It has improved my stamina and coordination significantly. It is a challenging activity that keeps me motivated.",
        "word_count": 86,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR7] Vocabulary: 'practice kickboxing', 'maintain fitness', 'high-intensity workout', 'martial arts techniques', 'cardio', 'routine', 'defensive moves', 'relieve stress', 'aggression', 'empowering', 'self-defense skills', 'exhausted', 'invigorated', 'stamina', 'coordination', 'significantly', 'challenging', 'motivated'. Very sophisticated. >Band 6: Precise vocabulary. Not Band 8: Some phrases are common.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'To maintain my physical fitness' (Infinitive of purpose). 'That combines martial arts...' (Relative clause). 'To learn self-defense skills' (Infinitive phrase). 'That keeps me motivated' (Relative clause). Accurate.",
        "vocabulary": 7,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe an exercise you do regularly.\n\nTranscript: I regularly practice kickboxing to maintain my physical fitness. It is a high-intensity workout that combines martial arts techniques with cardio. I attend classes at a local gym three times a week. The routine involves punching, kicking, and various defensive moves. It is an excellent way to relieve stress and aggression. I find it empowering to learn self-defense skills. After each session, I feel exhausted but invigorated. It has improved my stamina and coordination significantly. It is a challenging activity that keeps me motivated.\n\nWord Count: 86 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses topic words: 'empowering', 'invigorated', 'coordination'. Meaning is clear.\n\n>Band 6: Advanced vocabulary.\n\nNot Band 8: Lacks native-like flow.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures accurately. Includes relative clauses and infinitives. Good control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Limited variety.\n\n**Micro flaws identified:**\n- None."
    },
    # 707. V7/G7 - Book (Read)
    {
        "sample_id": "syn_p2_v7_g7_0707",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a biography you read.",
        "transcript_cleaned": "I read a fascinating biography of Albert Einstein, the renowned physicist. It detailed his early life, his struggles in school, and his groundbreaking scientific discoveries. I was intrigued by his unconventional approach to problem-solving. The book explained his theory of relativity in a way that was accessible to laypeople. It also delved into his personal life and humanitarian work. Reading about his persistence in the face of skepticism was inspiring. It gave me a deeper appreciation for his contributions to humanity. He was truly a genius who changed our understanding of the universe.",
        "word_count": 95,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR7] Vocabulary: 'fascinating biography', 'renowned physicist', 'detailed', 'struggles', 'groundbreaking', 'scientific discoveries', 'intrigued', 'unconventional approach', 'problem-solving', 'theory of relativity', 'accessible', 'laypeople', 'delved into', 'humanitarian work', 'persistence', 'skepticism', 'inspiring', 'appreciation', 'contributions', 'humanity', 'genius', 'universe'. Very sophisticated. >Band 6: Precise vocabulary. Not Band 8: Some phrases are common.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'Detailed his early life...' (List structure). 'That was accessible to laypeople' (Relative clause). 'Reading about his persistence... was...' (Gerund subject). 'Who changed our understanding' (Relative clause). Accurate.",
        "vocabulary": 7,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a biography you read.\n\nTranscript: I read a fascinating biography of Albert Einstein, the renowned physicist. It detailed his early life, his struggles in school, and his groundbreaking scientific discoveries. I was intrigued by his unconventional approach to problem-solving. The book explained his theory of relativity in a way that was accessible to laypeople. It also delved into his personal life and humanitarian work. Reading about his persistence in the face of skepticism was inspiring. It gave me a deeper appreciation for his contributions to humanity. He was truly a genius who changed our understanding of the universe.\n\nWord Count: 95 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses descriptive words: 'groundbreaking', 'unconventional', 'skepticism'. Clear meaning.\n\n>Band 6: Advanced vocabulary.\n\nNot Band 8: Lacks native-like flow.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures accurately. Includes relative clauses and gerund subjects. Good control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Limited variety.\n\n**Micro flaws identified:**\n- None."
    },
    # 708. V7/G7 - Place (Nature)
    {
        "sample_id": "syn_p2_v7_g7_0708",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a place near water you like.",
        "transcript_cleaned": "I love visiting a serene lake located in the national park. The water is pristine, reflecting the surrounding pine trees like a mirror. I often go there to kayak or simply sit on the dock. The tranquility of the place is a welcome respite from city noise. I enjoy watching the wildlife, such as ducks and herons. In the autumn, the changing leaves create a spectacular display of colors. It is a perfect spot for meditation and reflection. Being near the water always calms my mind.",
        "word_count": 88,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR7] Vocabulary: 'serene lake', 'national park', 'pristine', 'reflecting', 'surrounding', 'mirror', 'kayak', 'dock', 'tranquility', 'welcome respite', 'wildlife', 'herons', 'autumn', 'spectacular display', 'perfect spot', 'meditation', 'reflection', 'calms my mind'. Very sophisticated. >Band 6: Precise vocabulary. Not Band 8: Some phrases are common.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'Located in the national park' (Participle phrase). 'Reflecting the surrounding pine trees' (Participle phrase). 'To kayak or simply sit' (Infinitive of purpose). 'Such as ducks and herons' (Example phrase). Accurate.",
        "vocabulary": 7,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a place near water you like.\n\nTranscript: I love visiting a serene lake located in the national park. The water is pristine, reflecting the surrounding pine trees like a mirror. I often go there to kayak or simply sit on the dock. The tranquility of the place is a welcome respite from city noise. I enjoy watching the wildlife, such as ducks and herons. In the autumn, the changing leaves create a spectacular display of colors. It is a perfect spot for meditation and reflection. Being near the water always calms my mind.\n\nWord Count: 88 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses descriptive words: 'serene', 'pristine', 'respite'. Clear meaning.\n\n>Band 6: Advanced vocabulary.\n\nNot Band 8: Lacks native-like flow.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures accurately. Includes participle phrases and infinitives. Good control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Limited variety.\n\n**Micro flaws identified:**\n- None."
    },
    # 709. V7/G7 - Activity (Project)
    {
        "sample_id": "syn_p2_v7_g7_0709",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a piece of work you did with others.",
        "transcript_cleaned": "I collaborated with two classmates on a science presentation last month. Our task was to explain the effects of global warming. We divided the work equally to ensure efficiency. I was responsible for researching the data and creating the slides. We met frequently to discuss our progress and rehearse. It was challenging to coordinate our schedules, but we managed. Working in a team taught me the value of compromise and communication. Our presentation was well-received by the teacher and the class. I felt a sense of accomplishment.",
        "word_count": 88,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR7] Vocabulary: 'collaborated', 'classmates', 'presentation', 'task', 'effects', 'global warming', 'divided', 'ensure efficiency', 'responsible for', 'researching', 'data', 'slides', 'discuss progress', 'rehearse', 'challenging', 'coordinate schedules', 'compromise', 'communication', 'well-received', 'accomplishment'. Very sophisticated. >Band 6: Precise vocabulary. Not Band 8: Lacks idiomatic depth.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'To explain the effects...' (Infinitive of purpose). 'To ensure efficiency' (Infinitive of purpose). 'Responsible for researching...' (Adjective + Preposition + Gerund). 'Working in a team taught me...' (Gerund subject). Accurate.",
        "vocabulary": 7,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a piece of work you did with others.\n\nTranscript: I collaborated with two classmates on a science presentation last month. Our task was to explain the effects of global warming. We divided the work equally to ensure efficiency. I was responsible for researching the data and creating the slides. We met frequently to discuss our progress and rehearse. It was challenging to coordinate our schedules, but we managed. Working in a team taught me the value of compromise and communication. Our presentation was well-received by the teacher and the class. I felt a sense of accomplishment.\n\nWord Count: 88 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses topic words: 'collaborated', 'efficiency', 'compromise'. Meaning is clear.\n\n>Band 6: Advanced vocabulary.\n\nNot Band 8: Lacks sophistication.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures accurately. Includes infinitives and gerund subjects. Good control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Limited variety.\n\n**Micro flaws identified:**\n- None."
    },
    # 710. V7/G7 - Object (Old)
    {
        "sample_id": "syn_p2_v7_g7_0710",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe an antique you like.",
        "transcript_cleaned": "I am fond of an antique vase that sits in our hallway. It is a porcelain vase from the Ming Dynasty, painted with delicate blue patterns. My parents bought it at an auction years ago. It has a graceful shape and a glossy finish. I admire the artistry and skill required to create such an object. It adds a touch of elegance to our home decor. We are very careful with it because it is fragile and valuable. It serves as a conversation starter when guests visit.",
        "word_count": 88,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR7] Vocabulary: 'fond of', 'antique vase', 'hallway', 'porcelain', 'Ming Dynasty', 'delicate patterns', 'auction', 'graceful shape', 'glossy finish', 'admire', 'artistry', 'skill', 'elegance', 'decor', 'fragile', 'valuable', 'conversation starter'. Very sophisticated. >Band 6: Precise vocabulary. Not Band 8: Some phrases are common.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'That sits in our hallway' (Relative clause). 'Painted with delicate blue patterns' (Participle phrase). 'Required to create...' (Participle phrase). 'Because it is fragile' (Reason clause). Accurate.",
        "vocabulary": 7,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe an antique you like.\n\nTranscript: I am fond of an antique vase that sits in our hallway. It is a porcelain vase from the Ming Dynasty, painted with delicate blue patterns. My parents bought it at an auction years ago. It has a graceful shape and a glossy finish. I admire the artistry and skill required to create such an object. It adds a touch of elegance to our home decor. We are very careful with it because it is fragile and valuable. It serves as a conversation starter when guests visit.\n\nWord Count: 88 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses descriptive words: 'graceful', 'artistry', 'elegance'. Clear meaning.\n\n>Band 6: Advanced vocabulary.\n\nNot Band 8: Lacks native-like flow.\n\n**Idiom present:** Yes ('conversation starter')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures accurately (relative clauses, participle phrases). Good control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Limited variety.\n\n**Micro flaws identified:**\n- None."
    }
]

with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
    for sample in samples:
        f.write(json.dumps(sample) + '\n')
