import json

OUTPUT_FILE = "ielts-data/phase3/v76_review_output/synthetic_batches/batch_p2_08.jsonl"

samples = [
    # 381. V6/G8 - Job (Future)
    {
        "sample_id": "syn_p2_v6_g8_0381",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a job you would like to have in the future.",
        "transcript_cleaned": "I would like to work as a software developer for a big tech company. This job involves writing code and creating new programs for computers. I have always been interested in technology since I was a child. If I were to get this job, I would be able to solve interesting problems every day. It is important to me because I want to make things that help people in their daily lives. Although it requires a lot of study, I am willing to put in the effort. I believe that working in a team of smart people would be very motivating. I hope to achieve this goal within the next five years.",
        "word_count": 122,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR6] Vocabulary: 'software developer', 'tech company', 'writing code', 'programs', 'technology', 'solve', 'daily lives', 'effort', 'motivating', 'achieve'. Adequate and relevant but lacks less common vocabulary. >Band 5: Good range for the topic. Not Band 7: Lacks style and precision.",
        "grammar_reason": "[GRA8] Wide range of structures used accurately. 'If I were to get this job...' (Second conditional). 'Although it requires...' (Concessive clause). 'I believe that working... would be...' (Noun clause + Gerund subject). Error-free.",
        "vocabulary": 6,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a job you would like to have in the future.\n\nTranscript: I would like to work as a software developer for a big tech company. This job involves writing code and creating new programs for computers. I have always been interested in technology since I was a child. If I were to get this job, I would be able to solve interesting problems every day. It is important to me because I want to make things that help people in their daily lives. Although it requires a lot of study, I am willing to put in the effort. I believe that working in a team of smart people would be very motivating. I hope to achieve this goal within the next five years.\n\nWord Count: 122 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses relevant vocabulary like 'software developer', 'motivating'. Meaning is clear but vocabulary is not complex.\n\n>Band 5: Good range.\n\nNot Band 7: Lacks sophisticated words.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Uses a wide range of complex structures accurately (conditionals, concessive clauses). Sentences are error-free.\n\n>Band 7: More flexibility.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    },
    # 382. V6/G8 - Event (Music)
    {
        "sample_id": "syn_p2_v6_g8_0382",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a music event you attended.",
        "transcript_cleaned": "I went to a pop concert last year which was held in a large stadium. My favorite singer was performing, so I bought tickets months in advance. The atmosphere was exciting, with thousands of fans cheering and singing along. I was impressed by the stage lights and the sound quality. During the concert, the singer performed all her famous songs, which everyone enjoyed. Had I not gone to this concert, I would have regretted it deeply. It was a memorable night that I will never forget. Even though it was crowded, I felt safe and happy. The experience made me appreciate live music even more than before.",
        "word_count": 121,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR6] Vocabulary: 'pop concert', 'stadium', 'performing', 'advance', 'atmosphere', 'exciting', 'cheering', 'stage lights', 'sound quality', 'regretted', 'memorable', 'appreciate'. Adequate range. >Band 5: Clear descriptions. Not Band 7: Vocabulary is standard.",
        "grammar_reason": "[GRA8] Wide range. 'Which was held...' (Relative clause). 'With thousands of fans cheering...' (Prepositional phrase + Participle). 'Had I not gone..., I would have regretted...' (Third conditional inversion). Error-free.",
        "vocabulary": 6,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a music event you attended.\n\nTranscript: I went to a pop concert last year which was held in a large stadium. My favorite singer was performing, so I bought tickets months in advance. The atmosphere was exciting, with thousands of fans cheering and singing along. I was impressed by the stage lights and the sound quality. During the concert, the singer performed all her famous songs, which everyone enjoyed. Had I not gone to this concert, I would have regretted it deeply. It was a memorable night that I will never forget. Even though it was crowded, I felt safe and happy. The experience made me appreciate live music even more than before.\n\nWord Count: 121 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses relevant vocabulary: 'atmosphere', 'memorable', 'appreciate'. Clear but standard.\n\n>Band 5: Good range.\n\nNot Band 7: Lacks idiomatic or precise language.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Uses complex structures like inverted third conditionals accurately. Good control of grammar.\n\n>Band 7: High accuracy.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    },
    # 383. V6/G8 - Item (Bought)
    {
        "sample_id": "syn_p2_v6_g8_0383",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe something you bought recently.",
        "transcript_cleaned": "I recently purchased a new pair of running shoes from a sports shop. I needed them because my old ones were worn out and uncomfortable. These shoes are designed to support my feet while running long distances. I chose a bright blue color because it looks energetic. Before buying them, I tried them on to ensure they fit perfectly. Since getting them, I have been running every morning in the park. Running is a habit that keeps me healthy and relieves stress. I believe that investing in good quality shoes is important for avoiding injuries. I am very satisfied with my purchase as they are very durable.",
        "word_count": 121,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR6] Vocabulary: 'purchased', 'running shoes', 'worn out', 'uncomfortable', 'support', 'distances', 'energetic', 'fit perfectly', 'habit', 'relieves stress', 'investing', 'injuries', 'satisfied', 'durable'. Adequate range. >Band 5: Good topic vocabulary. Not Band 7: Vocabulary is functional.",
        "grammar_reason": "[GRA8] Wide range. 'Designed to support...' (Participle phrase). 'Before buying them...' (Prepositional phrase + Gerund). 'Running is a habit that keeps...' (Gerund subject + Relative clause). 'Investing... is important' (Gerund subject). Error-free.",
        "vocabulary": 6,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe something you bought recently.\n\nTranscript: I recently purchased a new pair of running shoes from a sports shop. I needed them because my old ones were worn out and uncomfortable. These shoes are designed to support my feet while running long distances. I chose a bright blue color because it looks energetic. Before buying them, I tried them on to ensure they fit perfectly. Since getting them, I have been running every morning in the park. Running is a habit that keeps me healthy and relieves stress. I believe that investing in good quality shoes is important for avoiding injuries. I am very satisfied with my purchase as they are very durable.\n\nWord Count: 121 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses 'worn out', 'investing', 'durable'. Clear and functional.\n\n>Band 5: Good range.\n\nNot Band 7: Lacks sophistication.\n\n**Idiom present:** Yes ('worn out')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Uses complex structures accurately, including gerunds and relative clauses. Error-free sentences.\n\n>Band 7: High accuracy.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    },
    # 384. V6/G8 - Skill (Cooking)
    {
        "sample_id": "syn_p2_v6_g8_0384",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a skill you would like to learn.",
        "transcript_cleaned": "I am interested in learning how to bake bread, which is a culinary skill I admire. I love the smell of fresh bread, but I have never made it myself. It involves mixing ingredients like flour, water, and yeast in the right amounts. I would like to learn this because homemade bread is healthier than store-bought bread. If I knew how to bake, I would make different types of bread for my family. Watching dough rise in the oven seems like a magical process to me. I plan to take a cooking class next month to start learning. It will require patience, but the result will be delicious.",
        "word_count": 122,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR6] Vocabulary: 'bake bread', 'culinary skill', 'admire', 'ingredients', 'yeast', 'homemade', 'store-bought', 'dough', 'rise', 'oven', 'magical', 'patience', 'delicious'. Adequate range. >Band 5: Uses specific words ('yeast', 'dough'). Not Band 7: Lacks depth.",
        "grammar_reason": "[GRA8] Wide range. 'Which is a culinary skill I admire' (Relative clause). 'Mixing ingredients...' (Gerund phrase). 'If I knew..., I would make...' (Second conditional). 'Watching dough rise... seems...' (Gerund subject). Error-free.",
        "vocabulary": 6,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a skill you would like to learn.\n\nTranscript: I am interested in learning how to bake bread, which is a culinary skill I admire. I love the smell of fresh bread, but I have never made it myself. It involves mixing ingredients like flour, water, and yeast in the right amounts. I would like to learn this because homemade bread is healthier than store-bought bread. If I knew how to bake, I would make different types of bread for my family. Watching dough rise in the oven seems like a magical process to me. I plan to take a cooking class next month to start learning. It will require patience, but the result will be delicious.\n\nWord Count: 122 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses relevant vocabulary: 'culinary', 'yeast', 'homemade'. Clear descriptions.\n\n>Band 5: Good range.\n\nNot Band 7: Vocabulary is standard.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Uses complex structures like second conditionals and gerund phrases accurately. Good control.\n\n>Band 7: High accuracy.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    },
    # 385. V6/G8 - News (Interesting)
    {
        "sample_id": "syn_p2_v6_g8_0385",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe an interesting piece of news you heard recently.",
        "transcript_cleaned": "I heard a news story about a new park opening in my city, which is very exciting. The park is located near the river and has a lot of green space. It was built to provide a place for people to relax and exercise outdoors. I read about it in the local newspaper yesterday morning. What interests me is that it has a special area for children to play safely. The city council spent a lot of money to create this beautiful environment. Since I live nearby, I will be able to visit it often. I think this development will improve the quality of life for residents significantly.",
        "word_count": 123,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR6] Vocabulary: 'opening', 'located', 'green space', 'relax', 'exercise', 'local newspaper', 'safely', 'city council', 'environment', 'development', 'improve', 'quality of life', 'residents', 'significantly'. Adequate range. >Band 5: Clear meaning. Not Band 7: Lacks precise lexical items.",
        "grammar_reason": "[GRA8] Wide range. 'Which is very exciting' (Relative clause). 'Built to provide...' (Participle phrase). 'What interests me is that...' (Pseudo-cleft). 'Since I live nearby...' (Reason clause). Error-free.",
        "vocabulary": 6,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe an interesting piece of news you heard recently.\n\nTranscript: I heard a news story about a new park opening in my city, which is very exciting. The park is located near the river and has a lot of green space. It was built to provide a place for people to relax and exercise outdoors. I read about it in the local newspaper yesterday morning. What interests me is that it has a special area for children to play safely. The city council spent a lot of money to create this beautiful environment. Since I live nearby, I will be able to visit it often. I think this development will improve the quality of life for residents significantly.\n\nWord Count: 123 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses functional vocabulary: 'green space', 'development', 'residents'. Clear but not complex.\n\n>Band 5: Good range.\n\nNot Band 7: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Uses complex structures like pseudo-cleft sentences and reason clauses accurately. High accuracy.\n\n>Band 7: Good control.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    },
    # 386. V6/G8 - Trip (Planning)
    {
        "sample_id": "syn_p2_v6_g8_0386",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a trip you are planning to take.",
        "transcript_cleaned": "I am planning a trip to Italy next summer with my family. We want to visit Rome and Florence to see the famous historical sites. I am excited about tasting authentic Italian food, especially pizza and pasta. To prepare for the trip, I have been reading guidebooks about the best places to visit. We are also saving money because traveling in Europe can be quite expensive. If we book our flights early, we might get a discount. I hope to visit the Colosseum, which is an ancient amphitheater. Exploring a new culture is something I always enjoy. I believe this holiday will be a wonderful experience for us all.",
        "word_count": 123,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR6] Vocabulary: 'planning', 'historical sites', 'tasting', 'authentic', 'guidebooks', 'saving money', 'expensive', 'book', 'discount', 'ancient', 'amphitheater', 'exploring', 'culture', 'wonderful'. Adequate range. >Band 5: Uses some specific words ('authentic', 'amphitheater'). Not Band 7: Vocabulary is standard.",
        "grammar_reason": "[GRA8] Wide range. 'To see the famous historical sites' (Infinitive of purpose). 'To prepare for the trip...' (Infinitive of purpose). 'If we book..., we might get...' (First conditional). 'Which is an ancient amphitheater' (Relative clause). Error-free.",
        "vocabulary": 6,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a trip you are planning to take.\n\nTranscript: I am planning a trip to Italy next summer with my family. We want to visit Rome and Florence to see the famous historical sites. I am excited about tasting authentic Italian food, especially pizza and pasta. To prepare for the trip, I have been reading guidebooks about the best places to visit. We are also saving money because traveling in Europe can be quite expensive. If we book our flights early, we might get a discount. I hope to visit the Colosseum, which is an ancient amphitheater. Exploring a new culture is something I always enjoy. I believe this holiday will be a wonderful experience for us all.\n\nWord Count: 123 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses relevant vocabulary: 'authentic', 'guidebooks', 'amphitheater'. Clear descriptions.\n\n>Band 5: Good range.\n\nNot Band 7: Lacks sophistication.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Uses complex structures like conditionals and relative clauses accurately. Good grammatical control.\n\n>Band 7: High accuracy.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    },
    # 387. V6/G8 - Gift (Buying)
    {
        "sample_id": "syn_p2_v6_g8_0387",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a gift you bought for someone.",
        "transcript_cleaned": "I bought a watch for my father's birthday last month. He had been using his old watch for many years, and it was starting to break. I went to a large department store to find a suitable one. I chose a classic design with a leather strap because he likes traditional styles. Although it was a bit expensive, I wanted to give him something special. When he opened the box, he was very surprised and happy. He put it on immediately and said it fit perfectly. Giving gifts makes me feel good because I like seeing people smile. It was a small way to show my appreciation for him.",
        "word_count": 121,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR6] Vocabulary: 'suitable', 'classic design', 'leather strap', 'traditional styles', 'expensive', 'surprised', 'immediately', 'fit perfectly', 'appreciation'. Adequate range. >Band 5: Clear meaning. Not Band 7: Vocabulary is simple.",
        "grammar_reason": "[GRA8] Wide range. 'He had been using...' (Past Perfect Continuous). 'To find a suitable one' (Infinitive of purpose). 'Because he likes...' (Reason clause). 'Although it was...' (Concessive clause). Error-free.",
        "vocabulary": 6,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a gift you bought for someone.\n\nTranscript: I bought a watch for my father's birthday last month. He had been using his old watch for many years, and it was starting to break. I went to a large department store to find a suitable one. I chose a classic design with a leather strap because he likes traditional styles. Although it was a bit expensive, I wanted to give him something special. When he opened the box, he was very surprised and happy. He put it on immediately and said it fit perfectly. Giving gifts makes me feel good because I like seeing people smile. It was a small way to show my appreciation for him.\n\nWord Count: 121 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses functional vocabulary: 'suitable', 'leather strap', 'appreciation'. Clear and correct.\n\n>Band 5: Good range.\n\nNot Band 7: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Uses complex structures like past perfect continuous and concessive clauses accurately. High accuracy.\n\n>Band 7: Good control.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    },
    # 388. V6/G8 - Person (Helpful)
    {
        "sample_id": "syn_p2_v6_g8_0388",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a person who helped you.",
        "transcript_cleaned": "I would like to talk about my neighbor, Mrs. Green, who helped me when I was sick. I live alone, so when I got the flu, I could not go out to buy medicine or food. She noticed that I had not been outside for a few days and came to check on me. Seeing that I was unwell, she offered to go to the pharmacy for me. She also cooked some soup, which made me feel much better. I was very grateful for her kindness during that difficult time. If she had not helped me, I would have struggled to recover. It showed me that having good neighbors is very important.",
        "word_count": 125,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR6] Vocabulary: 'neighbor', 'flu', 'medicine', 'pharmacy', 'unwell', 'offered', 'grateful', 'kindness', 'struggled', 'recover'. Adequate range. >Band 5: Clear descriptions. Not Band 7: Vocabulary is standard.",
        "grammar_reason": "[GRA8] Wide range. 'Who helped me...' (Relative clause). 'Seeing that I was unwell...' (Participle phrase). 'Which made me feel...' (Relative clause). 'If she had not helped..., I would have struggled...' (Third conditional). Error-free.",
        "vocabulary": 6,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a person who helped you.\n\nTranscript: I would like to talk about my neighbor, Mrs. Green, who helped me when I was sick. I live alone, so when I got the flu, I could not go out to buy medicine or food. She noticed that I had not been outside for a few days and came to check on me. Seeing that I was unwell, she offered to go to the pharmacy for me. She also cooked some soup, which made me feel much better. I was very grateful for her kindness during that difficult time. If she had not helped me, I would have struggled to recover. It showed me that having good neighbors is very important.\n\nWord Count: 125 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses relevant vocabulary: 'pharmacy', 'grateful', 'recover'. Clear meaning.\n\n>Band 5: Good range.\n\nNot Band 7: Lacks sophisticated words.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Uses complex structures like third conditionals and participle phrases accurately. Good control.\n\n>Band 7: High accuracy.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    },
    # 389. V6/G8 - Room (Change)
    {
        "sample_id": "syn_p2_v6_g8_0389",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a change you want to make to your room.",
        "transcript_cleaned": "I want to redecorate my bedroom to make it look more modern. Currently, the walls are painted a dull yellow, which I do not like anymore. I plan to paint them white to make the room look brighter and larger. I also want to replace my old bed with a new, comfortable one. Installing some shelves on the wall would be useful for storing my books. I think changing the curtains to a lighter color will also help. The reason I want to do this is that I spend a lot of time in my room studying. A nice environment helps me concentrate better. I have saved enough money to start this project soon.",
        "word_count": 125,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR6] Vocabulary: 'redecorate', 'modern', 'dull', 'replace', 'installing', 'shelves', 'storing', 'curtains', 'environment', 'concentrate', 'project'. Adequate range. >Band 5: Uses some specific words ('redecorate', 'shelves'). Not Band 7: Lacks depth.",
        "grammar_reason": "[GRA8] Wide range. 'To make it look more modern' (Infinitive of purpose). 'Which I do not like anymore' (Relative clause). 'Installing some shelves... would be...' (Gerund subject). 'The reason I want... is that...' (Noun clause). Error-free.",
        "vocabulary": 6,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a change you want to make to your room.\n\nTranscript: I want to redecorate my bedroom to make it look more modern. Currently, the walls are painted a dull yellow, which I do not like anymore. I plan to paint them white to make the room look brighter and larger. I also want to replace my old bed with a new, comfortable one. Installing some shelves on the wall would be useful for storing my books. I think changing the curtains to a lighter color will also help. The reason I want to do this is that I spend a lot of time in my room studying. A nice environment helps me concentrate better. I have saved enough money to start this project soon.\n\nWord Count: 125 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses relevant vocabulary: 'redecorate', 'shelves', 'concentrate'. Clear descriptions.\n\n>Band 5: Good range.\n\nNot Band 7: Vocabulary is standard.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Uses complex structures like gerund subjects and noun clauses accurately. High accuracy.\n\n>Band 7: Good control.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    },
    # 390. V6/G8 - Event (Sports)
    {
        "sample_id": "syn_p2_v6_g8_0390",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a sports event you watched.",
        "transcript_cleaned": "I watched a football match on television last weekend between two famous teams. It was the final game of the season, so it was very important. I watched it with my friends at home, and we had some snacks. The match was very exciting because both teams played well. One player scored a goal in the last minute, which made us all cheer loudly. I was amazed by the skill of the players and their speed. Although my favorite team did not win, I still enjoyed watching the game. It is fun to watch sports because anything can happen. I look forward to the next season starting so I can watch more matches.",
        "word_count": 123,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR6] Vocabulary: 'football match', 'season', 'exciting', 'scored a goal', 'cheer', 'amazed', 'skill', 'speed', 'look forward'. Adequate range. >Band 5: Clear meaning. Not Band 7: Lacks variety.",
        "grammar_reason": "[GRA8] Wide range. 'Between two famous teams' (Prepositional phrase). 'Which made us all cheer' (Relative clause). 'Although my favorite team did not win...' (Concessive clause). 'So I can watch...' (Result clause). Error-free.",
        "vocabulary": 6,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a sports event you watched.\n\nTranscript: I watched a football match on television last weekend between two famous teams. It was the final game of the season, so it was very important. I watched it with my friends at home, and we had some snacks. The match was very exciting because both teams played well. One player scored a goal in the last minute, which made us all cheer loudly. I was amazed by the skill of the players and their speed. Although my favorite team did not win, I still enjoyed watching the game. It is fun to watch sports because anything can happen. I look forward to the next season starting so I can watch more matches.\n\nWord Count: 123 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses relevant vocabulary: 'season', 'cheer', 'skill'. Clear descriptions.\n\n>Band 5: Good range.\n\nNot Band 7: Standard vocabulary.\n\n**Idiom present:** Yes ('look forward')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Uses complex structures like concessive clauses and relative clauses accurately. Good control.\n\n>Band 7: High accuracy.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    }
]

with open(OUTPUT_FILE, 'a', encoding='utf-8') as f:
    for sample in samples:
        f.write(json.dumps(sample) + '\n')
