import json

OUTPUT_FILE = "ielts-data/phase3/v76_review_output/synthetic_batches/batch_p2_08.jsonl"

samples = [
    # 351. V9/G9 - Gift (Received)
    {
        "sample_id": "syn_p2_v9_g9_0351",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a gift you received that you really liked.",
        "transcript_cleaned": "I was deeply touched by a bespoke fountain pen I received from my grandfather on my graduation day. It was an exquisite writing instrument, crafted from ebony wood with gold accents, and my initials were engraved on the cap. The weight and balance of the pen were perfect, making writing a sheer pleasure. He presented it with a handwritten note expressing his pride in my achievements, which moved me to tears. This gift was not merely a functional object but a symbol of his wisdom and the legacy he wished to pass on. I cherish it as a tangible reminder of his love and support. Using it inspires me to uphold the values he instilled in me.",
        "word_count": 121,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR9] Vocabulary: 'bespoke', 'exquisite', 'crafted', 'ebony', 'accents', 'engraved', 'sheer', 'presented', 'achievements', 'merely', 'functional', 'symbol', 'legacy', 'cherish', 'tangible', 'reminder', 'inspires', 'uphold', 'instilled'.",
        "grammar_reason": "[GRA9] Full range. 'Crafted from ebony wood...' (Participle phrase). 'Making writing a sheer pleasure' (Participle phrase). 'Which moved me to tears' (Relative clause). 'Not merely... but...' (Correlative). Error-free.",
        "vocabulary": 9,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a gift you received that you really liked.\n\nTranscript: I was deeply touched by a bespoke fountain pen I received from my grandfather on my graduation day. It was an exquisite writing instrument, crafted from ebony wood with gold accents, and my initials were engraved on the cap. The weight and balance of the pen were perfect, making writing a sheer pleasure. He presented it with a handwritten note expressing his pride in my achievements, which moved me to tears. This gift was not merely a functional object but a symbol of his wisdom and the legacy he wished to pass on. I cherish it as a tangible reminder of his love and support. Using it inspires me to uphold the values he instilled in me.\n\nWord Count: 121 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 9\n\n**Reasoning:** [LR9] Uses 'bespoke', 'exquisite', 'legacy', 'cherish', 'tangible', 'uphold', 'instilled'. Extremely precise and sophisticated.\n\n>Band 8: Wide range of vocabulary.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Full range of structures used naturally. Participle phrases, relative clauses, and correlative structures are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    },
    # 352. V9/G9 - Place (Historic)
    {
        "sample_id": "syn_p2_v9_g9_0352",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a historical place you visited.",
        "transcript_cleaned": "I was utterly captivated by the ancient ruins of Machu Picchu in Peru, a site shrouded in mystery and grandeur. Perched high in the Andes Mountains, the citadel is a testament to the ingenuity of the Inca civilization. Wandering through the stone structures, I marveled at the precision of the masonry, which has withstood centuries of seismic activity. The panoramic views of the surrounding peaks were breathtaking, evoking a sense of awe and insignificance. The atmosphere was ethereal, especially as the morning mist lifted to reveal the sun-drenched terraces. It was a profound experience that deepened my appreciation for human history and architectural brilliance. Visiting this UNESCO World Heritage site was the fulfillment of a lifelong dream.",
        "word_count": 120,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR9] Vocabulary: 'utterly', 'captivated', 'ancient', 'ruins', 'shrouded', 'mystery', 'grandeur', 'perched', 'citadel', 'testament', 'ingenuity', 'civilization', 'wandering', 'marveled', 'precision', 'masonry', 'withstood', 'seismic', 'panoramic', 'breathtaking', 'evoking', 'awe', 'insignificance', 'atmosphere', 'ethereal', 'mist', 'terraces', 'profound', 'appreciation', 'architectural', 'brilliance', 'fulfillment'.",
        "grammar_reason": "[GRA9] Full range. 'A site shrouded in mystery' (Appositive). 'Perched high in the Andes...' (Participle phrase). 'Which has withstood...' (Relative clause). 'Especially as the morning mist lifted' (Time clause). Error-free.",
        "vocabulary": 9,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a historical place you visited.\n\nTranscript: I was utterly captivated by the ancient ruins of Machu Picchu in Peru, a site shrouded in mystery and grandeur. Perched high in the Andes Mountains, the citadel is a testament to the ingenuity of the Inca civilization. Wandering through the stone structures, I marveled at the precision of the masonry, which has withstood centuries of seismic activity. The panoramic views of the surrounding peaks were breathtaking, evoking a sense of awe and insignificance. The atmosphere was ethereal, especially as the morning mist lifted to reveal the sun-drenched terraces. It was a profound experience that deepened my appreciation for human history and architectural brilliance. Visiting this UNESCO World Heritage site was the fulfillment of a lifelong dream.\n\nWord Count: 120 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 9\n\n**Reasoning:** [LR9] Uses 'captivated', 'shrouded', 'grandeur', 'ingenuity', 'masonry', 'ethereal', 'fulfillment'. Extremely precise and sophisticated.\n\n>Band 8: Wide range of vocabulary.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Full range of structures used naturally. Appositives, participle phrases, and relative clauses are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    },
    # 353. V9/G9 - Activity (Water)
    {
        "sample_id": "syn_p2_v9_g9_0353",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a water sport you would like to try.",
        "transcript_cleaned": "I have always harbored a desire to attempt scuba diving, specifically in the Great Barrier Reef. The prospect of exploring the subterranean aquatic world is incredibly enticing to me. I imagine descending into the depths, surrounded by a kaleidoscope of coral and vibrant marine life. It would be a surreal experience to witness the symbiotic relationships within that ecosystem firsthand. Although the technical aspects of breathing underwater are somewhat daunting, the potential for discovery outweighs the fear. I am particularly keen to observe sea turtles in their natural habitat. Mastering buoyancy control and navigating the currents would be a challenging yet rewarding endeavor. It represents the ultimate immersion in nature.",
        "word_count": 120,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR9] Vocabulary: 'harbored', 'desire', 'attempt', 'prospect', 'subterranean', 'aquatic', 'enticing', 'descending', 'depths', 'kaleidoscope', 'vibrant', 'surreal', 'witness', 'symbiotic', 'ecosystem', 'technical', 'daunting', 'potential', 'discovery', 'outweighs', 'keen', 'observe', 'habitat', 'mastering', 'buoyancy', 'navigating', 'currents', 'endeavor', 'ultimate', 'immersion'.",
        "grammar_reason": "[GRA9] Full range. 'Specifically in the Great Barrier Reef' (Prepositional phrase). 'Surrounded by a kaleidoscope...' (Participle phrase). 'Although the technical aspects... are...' (Concessive clause). 'Mastering... and navigating... would be...' (Gerund subjects). Error-free.",
        "vocabulary": 9,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a water sport you would like to try.\n\nTranscript: I have always harbored a desire to attempt scuba diving, specifically in the Great Barrier Reef. The prospect of exploring the subterranean aquatic world is incredibly enticing to me. I imagine descending into the depths, surrounded by a kaleidoscope of coral and vibrant marine life. It would be a surreal experience to witness the symbiotic relationships within that ecosystem firsthand. Although the technical aspects of breathing underwater are somewhat daunting, the potential for discovery outweighs the fear. I am particularly keen to observe sea turtles in their natural habitat. Mastering buoyancy control and navigating the currents would be a challenging yet rewarding endeavor. It represents the ultimate immersion in nature.\n\nWord Count: 120 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 9\n\n**Reasoning:** [LR9] Uses 'harbored', 'subterranean', 'kaleidoscope', 'symbiotic', 'daunting', 'buoyancy', 'immersion'. Extremely precise and sophisticated.\n\n>Band 8: Wide range of vocabulary.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Full range of structures used naturally. Participle phrases, concessive clauses, and gerund subjects are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    },
    # 354. V9/G9 - Music (Song)
    {
        "sample_id": "syn_p2_v9_g9_0354",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a song that has a special meaning for you.",
        "transcript_cleaned": "A song that resonates deeply with me is 'Imagine' by John Lennon, an anthem for peace and unity. Its minimalist melody and profound lyrics have a timeless quality that transcends generations. The song envisions a utopian world devoid of borders, religion, and possessions, which I find incredibly moving. Whenever I feel disheartened by global conflicts, listening to this track restores my faith in humanity. It encourages listeners to dream of a harmonious existence, free from the shackles of greed and division. The simplicity of the piano accompaniment allows the message to take center stage. It is not just a song; it is a poignant manifesto for a better future.",
        "word_count": 120,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR9] Vocabulary: 'resonates', 'anthem', 'minimalist', 'melody', 'profound', 'lyrics', 'timeless', 'transcends', 'generations', 'envisions', 'utopian', 'devoid', 'borders', 'possessions', 'disheartened', 'conflicts', 'restores', 'faith', 'humanity', 'encourages', 'harmonious', 'existence', 'shackles', 'greed', 'division', 'simplicity', 'accompaniment', 'center stage', 'poignant', 'manifesto'.",
        "grammar_reason": "[GRA9] Full range. 'An anthem for peace and unity' (Appositive). 'Devoid of borders...' (Adjective phrase). 'Which I find incredibly moving' (Relative clause). 'Free from the shackles...' (Adjective phrase). Error-free.",
        "vocabulary": 9,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a song that has a special meaning for you.\n\nTranscript: A song that resonates deeply with me is 'Imagine' by John Lennon, an anthem for peace and unity. Its minimalist melody and profound lyrics have a timeless quality that transcends generations. The song envisions a utopian world devoid of borders, religion, and possessions, which I find incredibly moving. Whenever I feel disheartened by global conflicts, listening to this track restores my faith in humanity. It encourages listeners to dream of a harmonious existence, free from the shackles of greed and division. The simplicity of the piano accompaniment allows the message to take center stage. It is not just a song; it is a poignant manifesto for a better future.\n\nWord Count: 120 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 9\n\n**Reasoning:** [LR9] Uses 'resonates', 'anthem', 'utopian', 'devoid', 'disheartened', 'shackles', 'manifesto'. Extremely precise and sophisticated.\n\n>Band 8: Wide range of vocabulary.\n\n**Idiom present:** Yes ('center stage')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Full range of structures used naturally. Appositives, relative clauses, and adjective phrases are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    },
    # 355. V9/G9 - Decision (Change)
    {
        "sample_id": "syn_p2_v9_g9_0355",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a time you changed your mind about something.",
        "transcript_cleaned": "I previously held a rigid stance against remote work, believing it would stifle collaboration and productivity. However, the global pandemic necessitated a paradigm shift, forcing me to adapt to a virtual environment. Initially, I was skeptical and resistant to the change. Yet, as weeks turned into months, I began to appreciate the flexibility and autonomy it offered. I realized that with the right digital tools, communication could be just as effective, if not more so. The absence of a daily commute significantly improved my work-life balance. This experience compelled me to reevaluate my preconceived notions. I now advocate for a hybrid model, recognizing that adaptability is crucial in the modern professional landscape.",
        "word_count": 121,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR9] Vocabulary: 'rigid', 'stance', 'stifle', 'collaboration', 'productivity', 'necessitated', 'paradigm', 'shift', 'adapt', 'virtual', 'skeptical', 'resistant', 'appreciate', 'flexibility', 'autonomy', 'commute', 'compelled', 'reevaluate', 'preconceived', 'notions', 'advocate', 'hybrid', 'recognizing', 'adaptability', 'crucial', 'landscape'.",
        "grammar_reason": "[GRA9] Full range. 'Believing it would stifle...' (Participle phrase). 'Forcing me to adapt...' (Participle phrase). 'I realized that... communication could be...' (Noun clause). 'Recognizing that adaptability is crucial' (Participle phrase). Error-free.",
        "vocabulary": 9,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a time you changed your mind about something.\n\nTranscript: I previously held a rigid stance against remote work, believing it would stifle collaboration and productivity. However, the global pandemic necessitated a paradigm shift, forcing me to adapt to a virtual environment. Initially, I was skeptical and resistant to the change. Yet, as weeks turned into months, I began to appreciate the flexibility and autonomy it offered. I realized that with the right digital tools, communication could be just as effective, if not more so. The absence of a daily commute significantly improved my work-life balance. This experience compelled me to reevaluate my preconceived notions. I now advocate for a hybrid model, recognizing that adaptability is crucial in the modern professional landscape.\n\nWord Count: 121 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 9\n\n**Reasoning:** [LR9] Uses 'rigid', 'stifle', 'paradigm', 'autonomy', 'reevaluate', 'preconceived', 'landscape'. Extremely precise and sophisticated.\n\n>Band 8: Wide range of vocabulary.\n\n**Idiom present:** Yes ('paradigm shift')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Full range of structures used naturally. Participle phrases and noun clauses are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    },
    # 356. V9/G9 - Animal (Wild)
    {
        "sample_id": "syn_p2_v9_g9_0356",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a wild animal you are interested in.",
        "transcript_cleaned": "I am endlessly fascinated by the snow leopard, an elusive predator indigenous to the mountain ranges of Central Asia. Often referred to as the 'ghost of the mountains', it is a master of camouflage, blending seamlessly into the rocky terrain. Its solitary nature and nocturnal habits make it incredibly difficult to observe in the wild. I am captivated by its physical adaptations, such as its thick fur and large paws, which allow it to traverse deep snow with agility. Sadly, this majestic creature is endangered due to habitat loss and poaching. The efforts to conserve its population are vital for maintaining the ecological balance of the region. Studying this animal offers a glimpse into the resilience of life in extreme environments.",
        "word_count": 129,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR9] Vocabulary: 'endlessly', 'fascinated', 'elusive', 'predator', 'indigenous', 'ranges', 'referred', 'camouflage', 'blending', 'seamlessly', 'terrain', 'solitary', 'nocturnal', 'habits', 'observe', 'captivated', 'adaptations', 'traverse', 'agility', 'majestic', 'creature', 'endangered', 'habitat loss', 'poaching', 'conserve', 'vital', 'ecological', 'balance', 'glimpse', 'resilience'.",
        "grammar_reason": "[GRA9] Full range. 'Indigenous to the mountain ranges...' (Adjective phrase). 'Often referred to as...' (Participle phrase). 'Blending seamlessly into...' (Participle phrase). 'Which allow it to traverse...' (Relative clause). Error-free.",
        "vocabulary": 9,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a wild animal you are interested in.\n\nTranscript: I am endlessly fascinated by the snow leopard, an elusive predator indigenous to the mountain ranges of Central Asia. Often referred to as the 'ghost of the mountains', it is a master of camouflage, blending seamlessly into the rocky terrain. Its solitary nature and nocturnal habits make it incredibly difficult to observe in the wild. I am captivated by its physical adaptations, such as its thick fur and large paws, which allow it to traverse deep snow with agility. Sadly, this majestic creature is endangered due to habitat loss and poaching. The efforts to conserve its population are vital for maintaining the ecological balance of the region. Studying this animal offers a glimpse into the resilience of life in extreme environments.\n\nWord Count: 129 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 9\n\n**Reasoning:** [LR9] Uses 'elusive', 'indigenous', 'camouflage', 'seamlessly', 'solitary', 'nocturnal', 'traverse'. Extremely precise and sophisticated.\n\n>Band 8: Wide range of vocabulary.\n\n**Idiom present:** Yes ('ghost of the mountains')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Full range of structures used naturally. Participle phrases, adjective phrases, and relative clauses are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    },
    # 357. V9/G9 - News (Science)
    {
        "sample_id": "syn_p2_v9_g9_0357",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a piece of scientific news you read about.",
        "transcript_cleaned": "I recently read a groundbreaking article about the successful deployment of the James Webb Space Telescope. This technological marvel promises to revolutionize our understanding of the cosmos by capturing images of the earliest galaxies formed after the Big Bang. The precision required to unfold the telescope in space was described as an engineering feat of unprecedented complexity. What intrigued me most was its ability to analyze the atmospheres of exoplanets, potentially detecting signs of life. This mission represents a monumental leap forward for humanity, expanding the frontiers of our knowledge. The images it has already returned are breathtakingly detailed, revealing the universe in infrared light. It is a testament to what international collaboration and scientific inquiry can achieve.",
        "word_count": 125,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR9] Vocabulary: 'groundbreaking', 'deployment', 'technological', 'marvel', 'revolutionize', 'cosmos', 'capturing', 'precision', 'unfold', 'feat', 'unprecedented', 'complexity', 'intrigued', 'analyze', 'atmospheres', 'exoplanets', 'detecting', 'monumental', 'leap', 'frontiers', 'breathtakingly', 'revealing', 'infrared', 'testament', 'collaboration', 'inquiry'.",
        "grammar_reason": "[GRA9] Full range. 'Formed after the Big Bang' (Participle phrase). 'Required to unfold...' (Participle phrase). 'What intrigued me most was...' (Cleft sentence). 'Potentially detecting signs of life' (Participle phrase). Error-free.",
        "vocabulary": 9,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a piece of scientific news you read about.\n\nTranscript: I recently read a groundbreaking article about the successful deployment of the James Webb Space Telescope. This technological marvel promises to revolutionize our understanding of the cosmos by capturing images of the earliest galaxies formed after the Big Bang. The precision required to unfold the telescope in space was described as an engineering feat of unprecedented complexity. What intrigued me most was its ability to analyze the atmospheres of exoplanets, potentially detecting signs of life. This mission represents a monumental leap forward for humanity, expanding the frontiers of our knowledge. The images it has already returned are breathtakingly detailed, revealing the universe in infrared light. It is a testament to what international collaboration and scientific inquiry can achieve.\n\nWord Count: 125 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 9\n\n**Reasoning:** [LR9] Uses 'groundbreaking', 'revolutionize', 'unprecedented', 'exoplanets', 'frontiers', 'breathtakingly', 'testament'. Extremely precise and sophisticated.\n\n>Band 8: Wide range of vocabulary.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Full range of structures used naturally. Participle phrases and cleft sentences are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    },
    # 358. V9/G9 - Neighbor
    {
        "sample_id": "syn_p2_v9_g9_0358",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a neighbor you get along well with.",
        "transcript_cleaned": "I am fortunate to reside next to Mrs. Higgins, an elderly widow who is the epitome of kindness and grace. She possesses a wealth of life experience and is an exceptional storyteller. We often converse over the garden fence, where she imparts wisdom garnered from her travels. Despite the generational gap, we share a mutual love for gardening, often exchanging tips and produce. She is incredibly considerate, always accepting packages on my behalf when I am at work. Her vibrant spirit and positive outlook on life are truly infectious. I regard her not merely as a neighbor but as a cherished friend and mentor. Her presence significantly enhances the sense of community in our neighborhood.",
        "word_count": 123,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR9] Vocabulary: 'fortunate', 'reside', 'widow', 'epitome', 'grace', 'possesses', 'wealth', 'exceptional', 'converse', 'imparts', 'wisdom', 'garnered', 'generational gap', 'mutual', 'exchanging', 'considerate', 'behalf', 'vibrant', 'infectious', 'regard', 'cherished', 'mentor', 'enhances', 'community'.",
        "grammar_reason": "[GRA9] Full range. 'Who is the epitome...' (Relative clause). 'Where she imparts wisdom...' (Relative clause). 'Garnered from her travels' (Participle phrase). 'Not merely... but...' (Correlative). Error-free.",
        "vocabulary": 9,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a neighbor you get along well with.\n\nTranscript: I am fortunate to reside next to Mrs. Higgins, an elderly widow who is the epitome of kindness and grace. She possesses a wealth of life experience and is an exceptional storyteller. We often converse over the garden fence, where she imparts wisdom garnered from her travels. Despite the generational gap, we share a mutual love for gardening, often exchanging tips and produce. She is incredibly considerate, always accepting packages on my behalf when I am at work. Her vibrant spirit and positive outlook on life are truly infectious. I regard her not merely as a neighbor but as a cherished friend and mentor. Her presence significantly enhances the sense of community in our neighborhood.\n\nWord Count: 123 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 9\n\n**Reasoning:** [LR9] Uses 'epitome', 'possesses', 'imparts', 'garnered', 'mutual', 'infectious', 'cherished'. Extremely precise and sophisticated.\n\n>Band 8: Wide range of vocabulary.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Full range of structures used naturally. Relative clauses, participle phrases, and correlative structures are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    },
    # 359. V9/G9 - Celebration (National)
    {
        "sample_id": "syn_p2_v9_g9_0359",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a national celebration in your country.",
        "transcript_cleaned": "Independence Day is a pivotal celebration in my nation, commemorated with immense patriotic fervor. It marks our liberation from colonial rule, a historic milestone that defines our identity. The day commences with the solemn hoisting of the national flag, followed by a grand military parade showcasing our defense capabilities. Citizens adorn their homes with flags and lights, creating a festive tapestry across the country. Cultural programs featuring traditional music and dance are organized to celebrate our diverse heritage. It is a day of collective reflection on the sacrifices made by our freedom fighters. The festivities culminate in spectacular fireworks displays that illuminate the night sky. This event fosters a profound sense of unity and national pride among the populace.",
        "word_count": 126,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR9] Vocabulary: 'pivotal', 'commemorated', 'immense', 'patriotic', 'fervor', 'liberation', 'colonial', 'milestone', 'defines', 'identity', 'commences', 'solemn', 'hoisting', 'showcasing', 'capabilities', 'adorn', 'tapestry', 'cultural', 'heritage', 'collective', 'reflection', 'sacrifices', 'culminate', 'spectacular', 'illuminate', 'fosters', 'profound', 'unity', 'populace'.",
        "grammar_reason": "[GRA9] Full range. 'Commemorated with immense patriotic fervor' (Participle phrase). 'A historic milestone that defines...' (Appositive + Relative clause). 'Showcasing our defense capabilities' (Participle phrase). 'Made by our freedom fighters' (Participle phrase). Error-free.",
        "vocabulary": 9,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a national celebration in your country.\n\nTranscript: Independence Day is a pivotal celebration in my nation, commemorated with immense patriotic fervor. It marks our liberation from colonial rule, a historic milestone that defines our identity. The day commences with the solemn hoisting of the national flag, followed by a grand military parade showcasing our defense capabilities. Citizens adorn their homes with flags and lights, creating a festive tapestry across the country. Cultural programs featuring traditional music and dance are organized to celebrate our diverse heritage. It is a day of collective reflection on the sacrifices made by our freedom fighters. The festivities culminate in spectacular fireworks displays that illuminate the night sky. This event fosters a profound sense of unity and national pride among the populace.\n\nWord Count: 126 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 9\n\n**Reasoning:** [LR9] Uses 'pivotal', 'fervor', 'commences', 'tapestry', 'culminate', 'illuminate', 'populace'. Extremely precise and sophisticated.\n\n>Band 8: Wide range of vocabulary.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Full range of structures used naturally. Participle phrases, appositives, and relative clauses are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    },
    # 360. V9/G9 - Rule (School)
    {
        "sample_id": "syn_p2_v9_g9_0360",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a rule at your school that you agreed with.",
        "transcript_cleaned": "My secondary school enforced a strict policy prohibiting the use of mobile phones during academic hours, a rule I wholeheartedly endorsed. While many students viewed it as draconian, I recognized its merit in fostering a focused learning environment. The absence of digital distractions encouraged face-to-face interaction and active participation in class discussions. It prevented the pervasive issue of cyberbullying within the school premises. Furthermore, it compelled us to engage with our peers during breaks rather than being glued to our screens. This policy significantly enhanced the social cohesion of the student body. I believe that by eliminating this source of disruption, the school prioritized our academic and social development. It was a necessary measure to maintain discipline.",
        "word_count": 126,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR9] Vocabulary: 'enforced', 'strict', 'policy', 'prohibiting', 'academic', 'wholeheartedly', 'endorsed', 'draconian', 'recognized', 'merit', 'fostering', 'distractions', 'encouraged', 'interaction', 'participation', 'pervasive', 'cyberbullying', 'premises', 'compelled', 'engage', 'peers', 'glued', 'enhanced', 'social cohesion', 'eliminating', 'disruption', 'prioritized', 'measure', 'discipline'.",
        "grammar_reason": "[GRA9] Full range. 'Prohibiting the use...' (Participle phrase). 'While many students viewed it...' (Concessive clause). 'Rather than being glued...' (Prepositional phrase). 'By eliminating this source...' (Prepositional phrase). Error-free.",
        "vocabulary": 9,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a rule at your school that you agreed with.\n\nTranscript: My secondary school enforced a strict policy prohibiting the use of mobile phones during academic hours, a rule I wholeheartedly endorsed. While many students viewed it as draconian, I recognized its merit in fostering a focused learning environment. The absence of digital distractions encouraged face-to-face interaction and active participation in class discussions. It prevented the pervasive issue of cyberbullying within the school premises. Furthermore, it compelled us to engage with our peers during breaks rather than being glued to our screens. This policy significantly enhanced the social cohesion of the student body. I believe that by eliminating this source of disruption, the school prioritized our academic and social development. It was a necessary measure to maintain discipline.\n\nWord Count: 126 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 9\n\n**Reasoning:** [LR9] Uses 'endorsed', 'draconian', 'pervasive', 'compelled', 'cohesion', 'prioritized'. Extremely precise and sophisticated.\n\n>Band 8: Wide range of vocabulary.\n\n**Idiom present:** Yes ('glued to our screens')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Full range of structures used naturally. Participle phrases, concessive clauses, and prepositional phrases are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    }
]

with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
    for sample in samples:
        f.write(json.dumps(sample) + '\n')
