import json

OUTPUT_FILE = "ielts-data/phase3/v76_review_output/synthetic_batches/batch_p2_13.jsonl"

samples = [
    # 631. V4/G6 - Person (Neighbor)
    {
        "sample_id": "syn_p2_v4_g6_0631",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a neighbor you know.",
        "transcript_cleaned": "I have a neighbor called Mr. Brown. He lives next to my house. He is an old man. I see him every day when I go to school. He is very kind and friendly. He has a dog that barks a lot. Sometimes, I help him carry his bags. He gives me candy. I like him because he tells funny stories. If he needs help, I will help him. He is a good neighbor.",
        "word_count": 80,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR4] Limited range: 'neighbor', 'house', 'old man', 'school', 'kind', 'friendly', 'dog', 'barks', 'carry bags', 'candy', 'funny stories', 'help', 'good'. Basic vocabulary. >Band 3: Clear description. Not Band 5: Minimal variation.",
        "grammar_reason": "[GRA6] Uses a mix of simple and complex structures accurately. 'When I go to school' (Time clause). 'That barks a lot' (Relative clause). 'Because he tells funny stories' (Reason clause). 'If he needs help...' (First conditional). Generally error-free. >Band 5: Uses complex structures accurately. Not Band 7: Limited range.",
        "vocabulary": 4,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a neighbor you know.\n\nTranscript: I have a neighbor called Mr. Brown. He lives next to my house. He is an old man. I see him every day when I go to school. He is very kind and friendly. He has a dog that barks a lot. Sometimes, I help him carry his bags. He gives me candy. I like him because he tells funny stories. If he needs help, I will help him. He is a good neighbor.\n\nWord Count: 80 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Basic vocabulary: 'kind', 'friendly', 'funny'. Simple description. No range.\n\n>Band 3: Basic meaning.\n\nNot Band 5: Lacks descriptive words.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Uses a mix of simple and complex structures accurately. Includes time clauses and conditionals.\n\n>Band 5: Good control of complex forms.\n\nNot Band 7: Range is limited.\n\n**Micro flaws identified:**\n- None."
    },
    # 632. V6/G4 - Book (Gift)
    {
        "sample_id": "syn_p2_v6_g4_0632",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a book you received as a gift.",
        "transcript_cleaned": "I receive a book from my friend last month. It was for my birthday. The book called 'The Travel Guide'. It has many pictures of different countries. I like travel, so it is perfect gift. The photos is very colorful and beautiful. I read about Japan and France. It make me want to visit there. The information is very useful. I keep it on my desk. I show it to my family. They likes it too. It is best present I get.",
        "word_count": 87,
        "response_type": "long_turn",
        "micro_flaws": ["tense: 'I receive' should be 'I received'", "article: 'The book called' should be 'The book was called'", "article: 'perfect gift' should be 'a perfect gift'", "agreement: 'photos is' should be 'photos are'", "agreement: 'It make' should be 'It makes'", "agreement: 'They likes' should be 'They like'", "article: 'is best present' should be 'is the best present'", "tense: 'I get' should be 'I got'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR6] Vocabulary: 'received', 'gift', 'birthday', 'Travel Guide', 'pictures', 'countries', 'perfect', 'colorful', 'beautiful', 'visit', 'information', 'useful', 'desk', 'present'. Adequate range. >Band 5: Uses specific words ('useful', 'information'). Not Band 7: Lacks sophistication.",
        "grammar_reason": "[GRA4] Only simple sentences. Systematic errors in tense ('receive', 'get'), agreement ('photos is', 'It make'), and articles. >Band 3: Basic meaning clear. Not Band 5: Errors are pervasive.",
        "vocabulary": 6,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a book you received as a gift.\n\nTranscript: I receive a book from my friend last month. It was for my birthday. The book called 'The Travel Guide'. It has many pictures of different countries. I like travel, so it is perfect gift. The photos is very colorful and beautiful. I read about Japan and France. It make me want to visit there. The information is very useful. I keep it on my desk. I show it to my family. They likes it too. It is best present I get.\n\nWord Count: 87 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses relevant vocabulary: 'guide', 'information', 'useful'. Clear description.\n\n>Band 5: Good range.\n\nNot Band 7: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Simple sentences only. Frequent errors in tense and agreement ('photos is'). Missing articles.\n\n>Band 3: Simple structures.\n\nNot Band 5: Systematic errors.\n\n**Micro flaws identified:**\n- 'I receive' should be 'I received'\n- 'The book called' should be 'The book was called'\n- 'perfect gift' should be 'a perfect gift'\n- 'photos is' should be 'photos are'\n- 'It make' should be 'It makes'\n- 'They likes' should be 'They like'\n- 'is best present' should be 'is the best present'\n- 'I get' should be 'I got'"
    },
    # 633. V4/G7 - Activity (Daily)
    {
        "sample_id": "syn_p2_v4_g7_0633",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe your evening routine.",
        "transcript_cleaned": "In the evening, I usually go home at 6 pm. I am often tired, so I rest for a while. Then, I help my mother cook dinner. We eat together at 7 pm. After dinner, I wash the dishes. I like to watch TV or read a book before bed. Sometimes, I listen to music. I go to sleep at 10 pm because I have to wake up early. Although I am busy, I like my evening time. It is quiet and nice.",
        "word_count": 89,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR4] Limited range: 'evening', 'home', 'tired', 'rest', 'help', 'cook', 'dinner', 'eat', 'wash dishes', 'watch TV', 'read', 'bed', 'music', 'sleep', 'wake up', 'busy', 'quiet', 'nice'. Basic routine vocabulary. >Band 3: Clear sequence. Not Band 5: Minimal variation.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'So I rest for a while' (Result clause). 'Before bed' (Prepositional phrase). 'Because I have to wake up early' (Reason clause). 'Although I am busy...' (Concessive clause). Accurate.",
        "vocabulary": 4,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe your evening routine.\n\nTranscript: In the evening, I usually go home at 6 pm. I am often tired, so I rest for a while. Then, I help my mother cook dinner. We eat together at 7 pm. After dinner, I wash the dishes. I like to watch TV or read a book before bed. Sometimes, I listen to music. I go to sleep at 10 pm because I have to wake up early. Although I am busy, I like my evening time. It is quiet and nice.\n\nWord Count: 89 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Basic vocabulary: 'rest', 'cook', 'wash'. Simple description. No range.\n\n>Band 3: Basic routine.\n\nNot Band 5: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures like concessive clauses and reason clauses correctly. Good grammatical control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Limited by vocabulary.\n\n**Micro flaws identified:**\n- None."
    },
    # 634. V7/G4 - Place (Holiday)
    {
        "sample_id": "syn_p2_v7_g4_0634",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a holiday destination you like.",
        "transcript_cleaned": "I like Bali, which is island in Indonesia. It is exotic destination. I go there two years ago. The beaches is pristine and beautiful. I swim in turquoise water. It was rejuvenating experience. I visit ancient temples. The architecture is unique. I try local cuisine, which is spicy. The people is hospitable. I buy souvenirs from local market. The landscape is lush and green. I want go back because it is paradise. The sunset is spectacular.",
        "word_count": 81,
        "response_type": "long_turn",
        "micro_flaws": ["article: 'is island' should be 'is an island'", "article: 'exotic destination' should be 'an exotic destination'", "tense: 'I go' should be 'I went'", "agreement: 'beaches is' should be 'beaches are'", "tense: 'I swim' should be 'I swam'", "article: 'rejuvenating experience' should be 'a rejuvenating experience'", "tense: 'I visit' should be 'I visited'", "tense: 'I try' should be 'I tried'", "agreement: 'people is' should be 'people are'", "tense: 'I buy' should be 'I bought'", "article: 'local market' should be 'a local market'", "grammar: 'want go' should be 'want to go'", "article: 'is paradise' should be 'is a paradise'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR7] Vocabulary: 'exotic destination', 'pristine', 'turquoise', 'rejuvenating', 'ancient temples', 'architecture', 'unique', 'local cuisine', 'spicy', 'hospitable', 'souvenirs', 'landscape', 'lush', 'paradise', 'spectacular'. Sophisticated descriptors. >Band 6: Precise vocabulary. Not Band 8: Errors in usage.",
        "grammar_reason": "[GRA4] Only simple sentences. Systematic errors in tense ('go', 'swim', 'visit'), agreement ('beaches is', 'people is'), and articles. >Band 3: Basic meaning clear. Not Band 5: Errors are pervasive.",
        "vocabulary": 7,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a holiday destination you like.\n\nTranscript: I like Bali, which is island in Indonesia. It is exotic destination. I go there two years ago. The beaches is pristine and beautiful. I swim in turquoise water. It was rejuvenating experience. I visit ancient temples. The architecture is unique. I try local cuisine, which is spicy. The people is hospitable. I buy souvenirs from local market. The landscape is lush and green. I want go back because it is paradise. The sunset is spectacular.\n\nWord Count: 81 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses sophisticated words: 'pristine', 'rejuvenating', 'hospitable'. Good range.\n\n>Band 6: Advanced vocabulary.\n\nNot Band 8: Lacks native flow.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Simple sentences. Frequent errors in tense and articles. Strain for listener.\n\n>Band 3: Simple structures.\n\nNot Band 5: Systematic errors.\n\n**Micro flaws identified:**\n- 'is island' should be 'is an island'\n- 'exotic destination' should be 'an exotic destination'\n- 'I go' should be 'I went'\n- 'beaches is' should be 'beaches are'\n- 'I swim' should be 'I swam'\n- 'rejuvenating experience' should be 'a rejuvenating experience'\n- 'I visit' should be 'I visited'\n- 'I try' should be 'I tried'\n- 'people is' should be 'people are'\n- 'I buy' should be 'I bought'\n- 'want go' should be 'want to go'\n- 'is paradise' should be 'is a paradise'"
    },
    # 635. V5/G8 - Activity (Exercise)
    {
        "sample_id": "syn_p2_v5_g8_0635",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a sport you played in school.",
        "transcript_cleaned": "I played badminton in my high school team, which was a great experience. We practiced twice a week after classes finished. Our coach was very strict but taught us many skills. I learned how to serve and smash the shuttlecock. It was a fast game that required quick reactions. I enjoyed playing doubles because I could work with a partner. We participated in several tournaments against other schools. Although we did not always win, we had a lot of fun. Playing sports helped me stay healthy and make new friends.",
        "word_count": 96,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR5] Vocabulary: 'badminton', 'team', 'experience', 'practiced', 'coach', 'strict', 'skills', 'serve', 'smash', 'shuttlecock', 'fast game', 'reactions', 'doubles', 'partner', 'tournaments', 'participated', 'healthy'. Functional vocabulary relevant to the topic. >Band 4: Uses specific words ('shuttlecock', 'doubles'). Not Band 6: Simple vocabulary.",
        "grammar_reason": "[GRA8] Wide range of structures used accurately. 'Which was a great experience' (Relative clause). 'Strict but taught us...' (Conjunction). 'That required quick reactions' (Relative clause). 'Because I could work...' (Reason clause). 'Although we did not always win...' (Concessive clause). Error-free. >Band 7: More variety.",
        "vocabulary": 5,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a sport you played in school.\n\nTranscript: I played badminton in my high school team, which was a great experience. We practiced twice a week after classes finished. Our coach was very strict but taught us many skills. I learned how to serve and smash the shuttlecock. It was a fast game that required quick reactions. I enjoyed playing doubles because I could work with a partner. We participated in several tournaments against other schools. Although we did not always win, we had a lot of fun. Playing sports helped me stay healthy and make new friends.\n\nWord Count: 96 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses topic words: 'smash', 'shuttlecock', 'tournaments'. Meaning is clear.\n\n>Band 4: Adequate vocabulary.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Uses complex structures accurately (relative clauses, concessive clauses). Sentences are error-free.\n\n>Band 7: High accuracy.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    },
    # 636. V4/G6 - Activity (Hobby)
    {
        "sample_id": "syn_p2_v4_g6_0636",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a hobby you have.",
        "transcript_cleaned": "I like cooking. It is my hobby. I cook every day for my family. I make dinner. My favorite food to cook is chicken. I learned from my mother. She is a good cook. I use vegetables and meat. The food tastes good. My family likes it. Cooking makes me happy. If I have time, I make cake. It is sweet. I want to learn more recipes. Cooking is fun for me.",
        "word_count": 80,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR4] Limited range: 'cooking', 'hobby', 'cook', 'family', 'dinner', 'favorite food', 'chicken', 'mother', 'vegetables', 'meat', 'tastes', 'happy', 'cake', 'sweet', 'recipes', 'fun'. Basic vocabulary. >Band 3: Clear description. Not Band 5: Minimal variation.",
        "grammar_reason": "[GRA6] Uses a mix of simple and complex structures. 'Favorite food to cook is chicken' (Infinitive). 'If I have time, I make cake' (First conditional). 'My family likes it' (Simple sentence). Generally error-free. >Band 5: Uses complex structures accurately. Not Band 7: Limited range.",
        "vocabulary": 4,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a hobby you have.\n\nTranscript: I like cooking. It is my hobby. I cook every day for my family. I make dinner. My favorite food to cook is chicken. I learned from my mother. She is a good cook. I use vegetables and meat. The food tastes good. My family likes it. Cooking makes me happy. If I have time, I make cake. It is sweet. I want to learn more recipes. Cooking is fun for me.\n\nWord Count: 80 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Basic vocabulary: 'cook', 'good', 'happy'. Repetitive. No descriptive language.\n\n>Band 3: Basic meaning.\n\nNot Band 5: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Uses a mix of simple and complex structures accurately. Includes conditionals and infinitives.\n\n>Band 5: Good control of complex forms.\n\nNot Band 7: Range is limited.\n\n**Micro flaws identified:**\n- None."
    },
    # 637. V6/G4 - Object (Technology)
    {
        "sample_id": "syn_p2_v6_g4_0637",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a piece of technology you use.",
        "transcript_cleaned": "I use laptop for my work. It is powerful machine. It has fast processor. I install many software on it. I use it to edit photos. The screen is high definition. The colors is very bright. It help me be productive. I can multitasking easily. The keyboard is comfortable. I connect to internet with Wi-Fi. It is essential device for me. I buy it last year. It cost a lot of money, but it is reliable.",
        "word_count": 84,
        "response_type": "long_turn",
        "micro_flaws": ["article: 'use laptop' should be 'use a laptop'", "article: 'powerful machine' should be 'a powerful machine'", "article: 'fast processor' should be 'a fast processor'", "plural: 'many software' should be 'much software' or 'many software programs'", "agreement: 'colors is' should be 'colors are'", "agreement: 'It help' should be 'It helps'", "grammar: 'can multitasking' should be 'can multitask'", "article: 'connect to internet' should be 'connect to the internet'", "article: 'essential device' should be 'an essential device'", "tense: 'I buy' should be 'I bought'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR6] Vocabulary: 'laptop', 'powerful', 'processor', 'install', 'software', 'edit photos', 'high definition', 'productive', 'multitasking', 'keyboard', 'internet', 'Wi-Fi', 'essential', 'reliable'. Adequate range. >Band 5: Uses specific words ('processor', 'multitasking'). Not Band 7: Lacks depth.",
        "grammar_reason": "[GRA4] Only simple sentences. Systematic errors in articles ('a powerful machine'), agreement ('colors is', 'It help'), and tense ('buy'). >Band 3: Basic meaning clear. Not Band 5: Errors are pervasive.",
        "vocabulary": 6,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a piece of technology you use.\n\nTranscript: I use laptop for my work. It is powerful machine. It has fast processor. I install many software on it. I use it to edit photos. The screen is high definition. The colors is very bright. It help me be productive. I can multitasking easily. The keyboard is comfortable. I connect to internet with Wi-Fi. It is essential device for me. I buy it last year. It cost a lot of money, but it is reliable.\n\nWord Count: 84 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses relevant vocabulary: 'processor', 'definition', 'productive'. Clear description.\n\n>Band 5: Good range.\n\nNot Band 7: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Simple sentences only. Frequent errors in articles, agreement, and tense ('buy').\n\n>Band 3: Simple structures.\n\nNot Band 5: Systematic errors.\n\n**Micro flaws identified:**\n- 'use laptop' should be 'use a laptop'\n- 'powerful machine' should be 'a powerful machine'\n- 'fast processor' should be 'a fast processor'\n- 'many software' should be 'many software programs'\n- 'colors is' should be 'colors are'\n- 'It help' should be 'It helps'\n- 'can multitasking' should be 'can multitask'\n- 'connect to internet' should be 'connect to the internet'\n- 'essential device' should be 'an essential device'\n- 'I buy' should be 'I bought'"
    },
    # 638. V4/G7 - Place (Park)
    {
        "sample_id": "syn_p2_v4_g7_0638",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a park you visit.",
        "transcript_cleaned": "I visit a park near my home. It is a big place with trees and grass. I go there to walk and relax. The air is good there. I see many birds and flowers. Sometimes, I go with my friends. We sit and talk. If the weather is nice, we stay for a long time. I like this park because it is quiet. It makes me feel happy. I think parks are good for people.",
        "word_count": 82,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR4] Limited range: 'park', 'home', 'big place', 'trees', 'grass', 'walk', 'relax', 'air', 'good', 'birds', 'flowers', 'friends', 'sit', 'talk', 'weather', 'nice', 'time', 'quiet', 'happy', 'people'. Basic vocabulary. >Band 3: Clear description. Not Band 5: Minimal variation.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'To walk and relax' (Infinitive of purpose). 'If the weather is nice...' (First conditional). 'Because it is quiet' (Reason clause). 'I think parks are...' (Noun clause). Accurate. >Band 6: Good control. Not Band 8: Limited by vocabulary.",
        "vocabulary": 4,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a park you visit.\n\nTranscript: I visit a park near my home. It is a big place with trees and grass. I go there to walk and relax. The air is good there. I see many birds and flowers. Sometimes, I go with my friends. We sit and talk. If the weather is nice, we stay for a long time. I like this park because it is quiet. It makes me feel happy. I think parks are good for people.\n\nWord Count: 82 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Basic vocabulary: 'park', 'grass', 'nice'. Simple description. No range.\n\n>Band 3: Basic meaning.\n\nNot Band 5: Lacks descriptive words.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures like conditionals and reason clauses correctly. Good grammatical control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Limited by vocabulary.\n\n**Micro flaws identified:**\n- None."
    },
    # 639. V7/G4 - Event (Celebration)
    {
        "sample_id": "syn_p2_v7_g4_0639",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a celebration you attended.",
        "transcript_cleaned": "I attend wedding of my cousin last week. It was lavish ceremony. The venue was decorated with exquisite flowers. The bride wear stunning gown. The groom look very dashing. There was many guests. The atmosphere was festive and joyous. We enjoy a gourmet feast. The food was delectable. I participating in traditional dances. It was memorable occasion. I congratulate the couple. They looks very happy. I giving them a generous gift. It was wonderful celebration.",
        "word_count": 82,
        "response_type": "long_turn",
        "micro_flaws": ["tense: 'I attend' should be 'I attended'", "article: 'wedding of' should be 'the wedding of'", "article: 'lavish ceremony' should be 'a lavish ceremony'", "agreement: 'bride wear' should be 'bride wore'", "article: 'stunning gown' should be 'a stunning gown'", "agreement: 'groom look' should be 'groom looked'", "agreement: 'There was many' should be 'There were many'", "tense: 'We enjoy' should be 'We enjoyed'", "article: 'gourmet feast' should be 'a gourmet feast'", "grammar: 'I participating' should be 'I participated'", "article: 'memorable occasion' should be 'a memorable occasion'", "tense: 'I congratulate' should be 'I congratulated'", "agreement: 'They looks' should be 'They looked'", "grammar: 'I giving' should be 'I gave'", "article: 'wonderful celebration' should be 'a wonderful celebration'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR7] Vocabulary: 'lavish', 'ceremony', 'venue', 'exquisite', 'bride', 'stunning gown', 'groom', 'dashing', 'festive', 'joyous', 'gourmet feast', 'delectable', 'traditional', 'memorable occasion', 'congratulate', 'generous'. Sophisticated descriptors. >Band 6: Precise vocabulary. Not Band 8: Errors in usage.",
        "grammar_reason": "[GRA4] Only simple sentences. Systematic errors in tense ('attend', 'wear', 'look', 'enjoy'), agreement ('There was many'), and articles. >Band 3: Basic meaning clear. Not Band 5: Errors are pervasive.",
        "vocabulary": 7,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a celebration you attended.\n\nTranscript: I attend wedding of my cousin last week. It was lavish ceremony. The venue was decorated with exquisite flowers. The bride wear stunning gown. The groom look very dashing. There was many guests. The atmosphere was festive and joyous. We enjoy a gourmet feast. The food was delectable. I participating in traditional dances. It was memorable occasion. I congratulate the couple. They looks very happy. I giving them a generous gift. It was wonderful celebration.\n\nWord Count: 82 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses sophisticated words: 'lavish', 'exquisite', 'delectable', 'generous'. Good range.\n\n>Band 6: Advanced vocabulary.\n\nNot Band 8: Lacks native flow.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Simple sentences. Frequent errors in tense and articles. Strain for listener.\n\n>Band 3: Simple structures.\n\nNot Band 5: Systematic errors.\n\n**Micro flaws identified:**\n- 'I attend' should be 'I attended'\n- 'lavish ceremony' should be 'a lavish ceremony'\n- 'bride wear' should be 'bride wore'\n- 'groom look' should be 'groom looked'\n- 'There was many' should be 'There were many'\n- 'We enjoy' should be 'We enjoyed'\n- 'I participating' should be 'I participated'\n- 'I congratulate' should be 'I congratulated'\n- 'They looks' should be 'They looked'\n- 'I giving' should be 'I gave'"
    },
    # 640. V5/G8 - Object (Gift)
    {
        "sample_id": "syn_p2_v5_g8_0640",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a gift you would like to give.",
        "transcript_cleaned": "I would like to give my mother a new handbag for her birthday. She has been using her old one for a long time, and it is starting to look worn. I want to find a bag that is both stylish and practical. It should be large enough to carry her things but not too heavy. I plan to save money from my part-time job to buy it. Although good bags can be expensive, she deserves the best. I think she will be very happy when she receives it. It is a small way to say thank you.",
        "word_count": 105,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR5] Vocabulary: 'handbag', 'birthday', 'using', 'worn', 'stylish', 'practical', 'carry', 'heavy', 'save money', 'part-time job', 'expensive', 'deserves', 'happy', 'receives', 'thank you'. Functional vocabulary relevant to the topic. >Band 4: Uses specific words ('stylish', 'practical'). Not Band 6: Simple vocabulary.",
        "grammar_reason": "[GRA8] Wide range of structures used accurately. 'Has been using...' (Present Perfect Continuous). 'Starting to look worn' (Infinitive). 'That is both stylish and practical' (Relative clause). 'Although good bags can be expensive...' (Concessive clause). 'When she receives it' (Time clause). Error-free. >Band 7: More variety.",
        "vocabulary": 5,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a gift you would like to give.\n\nTranscript: I would like to give my mother a new handbag for her birthday. She has been using her old one for a long time, and it is starting to look worn. I want to find a bag that is both stylish and practical. It should be large enough to carry her things but not too heavy. I plan to save money from my part-time job to buy it. Although good bags can be expensive, she deserves the best. I think she will be very happy when she receives it. It is a small way to say thank you.\n\nWord Count: 105 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses topic words: 'stylish', 'practical', 'deserves'. Meaning is clear.\n\n>Band 4: Adequate vocabulary.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Uses complex structures accurately (present perfect continuous, concessive clauses). Sentences are error-free.\n\n>Band 7: High accuracy.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    }
]

with open(OUTPUT_FILE, 'a', encoding='utf-8') as f:
    for sample in samples:
        f.write(json.dumps(sample) + '\n')
