import json

OUTPUT_FILE = "ielts-data/phase3/v76_review_output/synthetic_batches/batch_p2_07.jsonl"

samples = [
    # 311. V7/G8 - Event (Late)
    {
        "sample_id": "syn_p2_v7_g8_0311",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a time you were late for an important event.",
        "transcript_cleaned": "I remember a stressful incident when I was late for a university entrance interview. I had prepared meticulously for weeks, but on the day, I overslept due to a faulty alarm clock. Waking up an hour late, I was instantly seized by panic. I rushed to get dressed and skipped breakfast. To make matters worse, there was an unexpected traffic jam on the highway. I sat in the taxi, anxiously checking my watch every minute. I eventually arrived thirty minutes late, breathless and disheveled. Fortunately, the interviewers were understanding and allowed me to proceed. Although I performed well, the experience taught me to always have a backup plan. I now set multiple alarms to ensure punctuality.",
        "word_count": 128,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "high", "flexibility": "very_high"},
        "vocab_reason": "[LR7] Vocabulary: 'stressful', 'incident', 'meticulously', 'overslept', 'faulty', 'seized', 'panic', 'unexpected', 'traffic jam', 'anxiously', 'breathless', 'disheveled', 'understanding', 'backup plan', 'punctuality'.",
        "grammar_reason": "[GRA8] Wide range. 'Waking up an hour late...' (Participle phrase). 'To make matters worse...' (Infinitive phrase). 'Although I performed well, the experience taught me...' (Concessive clause). Accurate.",
        "vocabulary": 7,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a time you were late for an important event.\n\nTranscript: I remember a stressful incident when I was late for a university entrance interview. I had prepared meticulously for weeks, but on the day, I overslept due to a faulty alarm clock. Waking up an hour late, I was instantly seized by panic. I rushed to get dressed and skipped breakfast. To make matters worse, there was an unexpected traffic jam on the highway. I sat in the taxi, anxiously checking my watch every minute. I eventually arrived thirty minutes late, breathless and disheveled. Fortunately, the interviewers were understanding and allowed me to proceed. Although I performed well, the experience taught me to always have a backup plan. I now set multiple alarms to ensure punctuality.\n\nWord Count: 128 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses 'meticulously', 'faulty', 'seized', 'disheveled', 'punctuality'. Shows awareness of style.\n\n>Band 6: More precise and varied.\n\nNot Band 8: Lacks sophistication.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Wide range of structures used flexibly. Uses participle phrases, infinitive phrases, and concessive clauses correctly. Majority of sentences are error-free.\n\n>Band 7: More flexibility.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    },
    # 312. V7/G8 - News (Bad)
    {
        "sample_id": "syn_p2_v7_g8_0312",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a piece of bad news you received.",
        "transcript_cleaned": "I received some disheartening news last year regarding my application for a summer internship. I had applied to a prestigious company and was confident about my chances. However, I received an email stating that they had selected another candidate. I was initially crushed, as I had invested a lot of effort into the process. The rejection letter was polite but firm. It was a significant setback for my career plans at the time. I spent a few days reflecting on what went wrong. Eventually, I realized that failure is part of the learning curve. This experience motivated me to improve my skills and resume. I am now more resilient when facing professional rejection.",
        "word_count": 122,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "high", "flexibility": "very_high"},
        "vocab_reason": "[LR7] Vocabulary: 'disheartening', 'prestigious', 'selected', 'candidate', 'crushed', 'invested', 'rejection', 'setback', 'reflecting', 'learning curve', 'motivated', 'resilient', 'professional'.",
        "grammar_reason": "[GRA8] Wide range. 'Stating that they had selected...' (Reported speech + Past Perfect). 'As I had invested...' (Reason clause + Past Perfect). 'Reflecting on what went wrong' (Gerund + Noun clause). Accurate.",
        "vocabulary": 7,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a piece of bad news you received.\n\nTranscript: I received some disheartening news last year regarding my application for a summer internship. I had applied to a prestigious company and was confident about my chances. However, I received an email stating that they had selected another candidate. I was initially crushed, as I had invested a lot of effort into the process. The rejection letter was polite but firm. It was a significant setback for my career plans at the time. I spent a few days reflecting on what went wrong. Eventually, I realized that failure is part of the learning curve. This experience motivated me to improve my skills and resume. I am now more resilient when facing professional rejection.\n\nWord Count: 122 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses 'disheartening', 'prestigious', 'crushed', 'setback', 'resilient'. Shows awareness of style.\n\n>Band 6: More precise and varied.\n\nNot Band 8: Lacks sophistication.\n\n**Idiom present:** Yes ('learning curve')\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Wide range of structures used flexibly. Uses reported speech, past perfect, and complex gerund phrases correctly. Majority of sentences are error-free.\n\n>Band 7: More flexibility.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    },
    # 313. V7/G8 - Decision (Difficult)
    {
        "sample_id": "syn_p2_v7_g8_0313",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a difficult decision you had to make.",
        "transcript_cleaned": "One of the most challenging decisions I have faced was choosing my university major. I was torn between studying fine arts, my passion, and computer science, a more practical choice. My parents advised me to consider future job stability, which weighed heavily on my mind. I spent weeks agonizing over the pros and cons of each path. I consulted with career counselors and spoke to professionals in both fields. Ultimately, I decided to pursue computer science but keep art as a serious hobby. It was a compromise between my heart and my head. Looking back, I believe I made the right choice as it offers financial security. However, it was emotionally draining at the time.",
        "word_count": 121,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "high", "flexibility": "very_high"},
        "vocab_reason": "[LR7] Vocabulary: 'challenging', 'torn between', 'practical', 'stability', 'weighed heavily', 'agonizing', 'pros and cons', 'consulted', 'pursue', 'compromise', 'financial security', 'draining'.",
        "grammar_reason": "[GRA8] Wide range. 'One of the most challenging decisions... was choosing...' (Superlative + Gerund). 'My parents advised me to consider...' (Infinitive pattern). 'Looking back, I believe...' (Participle phrase). Accurate.",
        "vocabulary": 7,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a difficult decision you had to make.\n\nTranscript: One of the most challenging decisions I have faced was choosing my university major. I was torn between studying fine arts, my passion, and computer science, a more practical choice. My parents advised me to consider future job stability, which weighed heavily on my mind. I spent weeks agonizing over the pros and cons of each path. I consulted with career counselors and spoke to professionals in both fields. Ultimately, I decided to pursue computer science but keep art as a serious hobby. It was a compromise between my heart and my head. Looking back, I believe I made the right choice as it offers financial security. However, it was emotionally draining at the time.\n\nWord Count: 121 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses 'torn between', 'stability', 'agonizing', 'compromise', 'draining'. Shows awareness of style.\n\n>Band 6: More precise and varied.\n\nNot Band 8: Lacks sophistication.\n\n**Idiom present:** Yes ('pros and cons', 'weighed heavily')\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Wide range of structures used flexibly. Uses superlatives, infinitive patterns, and participle phrases correctly. Majority of sentences are error-free.\n\n>Band 7: More flexibility.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    },
    # 314. V7/G8 - Help (Given)
    {
        "sample_id": "syn_p2_v7_g8_0314",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a time you helped someone.",
        "transcript_cleaned": "I remember helping an elderly neighbor who had fallen in her garden. I was walking past her house when I heard a faint cry for help. I immediately rushed over and found her on the ground, unable to get up. She was visibly shaken and in pain. I carefully helped her into a chair and called her daughter. While we waited, I made her some tea to calm her nerves. I stayed with her until her family arrived to ensure she was safe. It was a frightening situation, but I was glad I could be of assistance. She was incredibly grateful for my intervention. This incident reinforced the value of community and looking out for one another.",
        "word_count": 121,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "high", "flexibility": "very_high"},
        "vocab_reason": "[LR7] Vocabulary: 'elderly', 'faint', 'visibly shaken', 'calm her nerves', 'assistance', 'grateful', 'intervention', 'reinforced', 'community'.",
        "grammar_reason": "[GRA8] Wide range. 'Who had fallen...' (Relative clause + Past Perfect). 'Unable to get up' (Adjective phrase). 'While we waited...' (Time clause). 'To ensure she was safe' (Infinitive of purpose). Accurate.",
        "vocabulary": 7,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a time you helped someone.\n\nTranscript: I remember helping an elderly neighbor who had fallen in her garden. I was walking past her house when I heard a faint cry for help. I immediately rushed over and found her on the ground, unable to get up. She was visibly shaken and in pain. I carefully helped her into a chair and called her daughter. While we waited, I made her some tea to calm her nerves. I stayed with her until her family arrived to ensure she was safe. It was a frightening situation, but I was glad I could be of assistance. She was incredibly grateful for my intervention. This incident reinforced the value of community and looking out for one another.\n\nWord Count: 121 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses 'visibly shaken', 'assistance', 'intervention', 'reinforced'. Shows awareness of style.\n\n>Band 6: More precise and varied.\n\nNot Band 8: Lacks sophistication.\n\n**Idiom present:** Yes ('calm her nerves')\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Wide range of structures used flexibly. Uses relative clauses, past perfect, and infinitives of purpose correctly. Majority of sentences are error-free.\n\n>Band 7: More flexibility.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    },
    # 315. V7/G8 - Item (Broken)
    {
        "sample_id": "syn_p2_v7_g8_0315",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe something you own that is broken or does not work.",
        "transcript_cleaned": "I have an old laptop that is currently non-functional. It was a reliable device for many years, but recently the hard drive failed completely. Now, when I try to turn it on, the screen remains black and it makes a loud whirring noise. I was quite upset because I had some important photos stored on it. I took it to a repair shop, but they said the cost of fixing it would exceed its value. It is now sitting in my drawer gathering dust. I keep it because I am hopeful I might retrieve the data someday. It is a reminder of how fragile technology can be. I really should have backed up my files.",
        "word_count": 115,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "high", "flexibility": "very_high"},
        "vocab_reason": "[LR7] Vocabulary: 'non-functional', 'reliable', 'whirring', 'stored', 'exceed', 'gathering dust', 'retrieve', 'fragile', 'backed up'.",
        "grammar_reason": "[GRA8] Wide range. 'That is currently non-functional' (Relative clause). 'The cost of fixing it' (Gerund phrase). 'I keep it because I am hopeful...' (Reason clause). 'I really should have backed up' (Modal perfect). Accurate.",
        "vocabulary": 7,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe something you own that is broken or does not work.\n\nTranscript: I have an old laptop that is currently non-functional. It was a reliable device for many years, but recently the hard drive failed completely. Now, when I try to turn it on, the screen remains black and it makes a loud whirring noise. I was quite upset because I had some important photos stored on it. I took it to a repair shop, but they said the cost of fixing it would exceed its value. It is now sitting in my drawer gathering dust. I keep it because I am hopeful I might retrieve the data someday. It is a reminder of how fragile technology can be. I really should have backed up my files.\n\nWord Count: 115 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses 'non-functional', 'whirring', 'retrieve', 'fragile'. Shows awareness of style.\n\n>Band 6: More precise and varied.\n\nNot Band 8: Lacks sophistication.\n\n**Idiom present:** Yes ('gathering dust')\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Wide range of structures used flexibly. Uses modal perfects, gerund phrases, and reason clauses correctly. Majority of sentences are error-free.\n\n>Band 7: More flexibility.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    },
    # 316. V7/G8 - Room (Favorite)
    {
        "sample_id": "syn_p2_v7_g8_0316",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe your favorite room in your house.",
        "transcript_cleaned": "My favorite room is undoubtedly the living room, which serves as the heart of our home. It is a spacious area with large windows that allow natural light to flood in during the day. We have decorated it with comfortable sofas and vibrant paintings. I spend most of my leisure time there, reading or watching movies with my family. What I love most is the cozy atmosphere, especially in the evenings when we light the lamps. It is the place where we gather to discuss our day and unwind. The room also features a bookshelf filled with my favorite novels. It feels like a sanctuary where I can relax completely. I wouldn't change anything about it.",
        "word_count": 115,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "high", "flexibility": "very_high"},
        "vocab_reason": "[LR7] Vocabulary: 'undoubtedly', 'spacious', 'flood in', 'vibrant', 'leisure', 'cozy', 'atmosphere', 'unwind', 'sanctuary'.",
        "grammar_reason": "[GRA8] Wide range. 'Which serves as...' (Relative clause). 'That allow natural light to flood in' (Relative clause). 'What I love most is...' (Pseudo-cleft). 'Where we gather...' (Relative clause). Accurate.",
        "vocabulary": 7,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe your favorite room in your house.\n\nTranscript: My favorite room is undoubtedly the living room, which serves as the heart of our home. It is a spacious area with large windows that allow natural light to flood in during the day. We have decorated it with comfortable sofas and vibrant paintings. I spend most of my leisure time there, reading or watching movies with my family. What I love most is the cozy atmosphere, especially in the evenings when we light the lamps. It is the place where we gather to discuss our day and unwind. The room also features a bookshelf filled with my favorite novels. It feels like a sanctuary where I can relax completely. I wouldn't change anything about it.\n\nWord Count: 115 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses 'spacious', 'vibrant', 'unwind', 'sanctuary'. Shows awareness of style.\n\n>Band 6: More precise and varied.\n\nNot Band 8: Lacks sophistication.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Wide range of structures used flexibly. Uses relative clauses and pseudo-cleft sentences correctly. Majority of sentences are error-free.\n\n>Band 7: More flexibility.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    },
    # 317. V7/G8 - Photograph
    {
        "sample_id": "syn_p2_v7_g8_0317",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a photograph you like.",
        "transcript_cleaned": "I would like to describe a photograph that holds great sentimental value for me. It is a candid shot taken during my graduation ceremony. In the photo, I am throwing my cap in the air, surrounded by my smiling classmates. The lighting is perfect, capturing the joy and relief of that moment. I keep it framed on my desk because it reminds me of my achievements. Looking at it evokes feelings of nostalgia and pride. It marks the culmination of four years of hard work. The composition is dynamic, conveying a sense of movement and celebration. It is not just a picture; it is a frozen memory of a significant milestone in my life.",
        "word_count": 112,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "high", "flexibility": "very_high"},
        "vocab_reason": "[LR7] Vocabulary: 'sentimental value', 'candid', 'surrounded', 'capturing', 'evokes', 'nostalgia', 'culmination', 'composition', 'dynamic', 'conveying', 'milestone'.",
        "grammar_reason": "[GRA8] Wide range. 'That holds great sentimental value' (Relative clause). 'Taken during my graduation' (Past participle phrase). 'Surrounded by my smiling classmates' (Past participle phrase). 'Capturing the joy...' (Present participle phrase). Accurate.",
        "vocabulary": 7,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a photograph you like.\n\nTranscript: I would like to describe a photograph that holds great sentimental value for me. It is a candid shot taken during my graduation ceremony. In the photo, I am throwing my cap in the air, surrounded by my smiling classmates. The lighting is perfect, capturing the joy and relief of that moment. I keep it framed on my desk because it reminds me of my achievements. Looking at it evokes feelings of nostalgia and pride. It marks the culmination of four years of hard work. The composition is dynamic, conveying a sense of movement and celebration. It is not just a picture; it is a frozen memory of a significant milestone in my life.\n\nWord Count: 112 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses 'sentimental', 'candid', 'evokes', 'culmination', 'dynamic', 'milestone'. Shows awareness of style.\n\n>Band 6: More precise and varied.\n\nNot Band 8: Lacks sophistication.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Wide range of structures used flexibly. Uses relative clauses and various participle phrases correctly. Majority of sentences are error-free.\n\n>Band 7: More flexibility.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    },
    # 318. V7/G8 - Teacher (Favorite)
    {
        "sample_id": "syn_p2_v7_g8_0318",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a teacher who has influenced you.",
        "transcript_cleaned": "I would like to talk about Mr. Thompson, my high school history teacher. He was a charismatic individual who brought history to life with his storytelling. Unlike other teachers who relied on textbooks, he used props and role-playing activities. He encouraged us to think critically about historical events rather than just memorizing dates. His passion for the subject was infectious, inspiring many students to pursue history at university. I remember him staying after class to help me with my essays. He taught me the importance of analyzing different perspectives. I owe my academic success largely to his guidance. He was truly an exceptional educator who cared deeply about his students' development.",
        "word_count": 115,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "high", "flexibility": "very_high"},
        "vocab_reason": "[LR7] Vocabulary: 'charismatic', 'brought history to life', 'relied on', 'props', 'critically', 'infectious', 'inspiring', 'pursue', 'analyzing', 'perspectives', 'guidance', 'exceptional', 'educator'.",
        "grammar_reason": "[GRA8] Wide range. 'Who brought history to life' (Relative clause). 'Unlike other teachers who relied...' (Contrast + Relative). 'Rather than just memorizing' (Prepositional phrase). 'Staying after class to help' (Participle phrase). Accurate.",
        "vocabulary": 7,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a teacher who has influenced you.\n\nTranscript: I would like to talk about Mr. Thompson, my high school history teacher. He was a charismatic individual who brought history to life with his storytelling. Unlike other teachers who relied on textbooks, he used props and role-playing activities. He encouraged us to think critically about historical events rather than just memorizing dates. His passion for the subject was infectious, inspiring many students to pursue history at university. I remember him staying after class to help me with my essays. He taught me the importance of analyzing different perspectives. I owe my academic success largely to his guidance. He was truly an exceptional educator who cared deeply about his students' development.\n\nWord Count: 115 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses 'charismatic', 'infectious', 'perspectives', 'educator'. Shows awareness of style.\n\n>Band 6: More precise and varied.\n\nNot Band 8: Lacks sophistication.\n\n**Idiom present:** Yes ('brought history to life')\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Wide range of structures used flexibly. Uses relative clauses, contrast markers, and participle phrases correctly. Majority of sentences are error-free.\n\n>Band 7: More flexibility.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    },
    # 319. V7/G8 - Gift (Handmade)
    {
        "sample_id": "syn_p2_v7_g8_0319",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a handmade gift you gave to a friend.",
        "transcript_cleaned": "I decided to make a scrapbook for my best friend's birthday. It was a labor of love that took me several weeks to complete. I gathered photos from our travels together and arranged them chronologically. I also included tickets, notes, and other memorabilia we had collected. Decorating the pages with stickers and drawings was the most fun part. When I gave it to her, she was moved to tears. She said it was the most thoughtful gift she had ever received. I believe handmade gifts are more meaningful because they show personal effort. It was a way to celebrate our friendship and preserve our precious memories.",
        "word_count": 111,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "high", "flexibility": "very_high"},
        "vocab_reason": "[LR7] Vocabulary: 'labor of love', 'gathered', 'chronologically', 'memorabilia', 'moved to tears', 'thoughtful', 'meaningful', 'preserve', 'precious'.",
        "grammar_reason": "[GRA8] Wide range. 'That took me several weeks' (Relative clause). 'Memorabilia we had collected' (Relative clause + Past Perfect). 'Decorating the pages... was...' (Gerund subject). 'Because they show...' (Reason clause). Accurate.",
        "vocabulary": 7,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a handmade gift you gave to a friend.\n\nTranscript: I decided to make a scrapbook for my best friend's birthday. It was a labor of love that took me several weeks to complete. I gathered photos from our travels together and arranged them chronologically. I also included tickets, notes, and other memorabilia we had collected. Decorating the pages with stickers and drawings was the most fun part. When I gave it to her, she was moved to tears. She said it was the most thoughtful gift she had ever received. I believe handmade gifts are more meaningful because they show personal effort. It was a way to celebrate our friendship and preserve our precious memories.\n\nWord Count: 111 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses 'chronologically', 'memorabilia', 'preserve'. Shows awareness of style.\n\n>Band 6: More precise and varied.\n\nNot Band 8: Lacks sophistication.\n\n**Idiom present:** Yes ('labor of love')\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Wide range of structures used flexibly. Uses relative clauses, past perfect, and gerund subjects correctly. Majority of sentences are error-free.\n\n>Band 7: More flexibility.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    },
    # 320. V7/G8 - Place (Noisy)
    {
        "sample_id": "syn_p2_v7_g8_0320",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a noisy place you have been to.",
        "transcript_cleaned": "I recently visited a construction site near my office, which was deafening. The sound of jackhammers and heavy machinery was constant and overwhelming. Dust filled the air, and workers were shouting instructions to each other. It was chaotic, with trucks moving in every direction. I had to cover my ears because the decibel level was unbearable. The vibration from the drilling could be felt in the ground. I stayed only for a few minutes as I found the environment extremely stressful. It made me appreciate the quiet of my own home. Such noise pollution is a major drawback of urban development.",
        "word_count": 103,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "high", "flexibility": "very_high"},
        "vocab_reason": "[LR7] Vocabulary: 'deafening', 'jackhammers', 'machinery', 'overwhelming', 'chaotic', 'decibel level', 'unbearable', 'vibration', 'stressful', 'noise pollution', 'drawback', 'urban development'.",
        "grammar_reason": "[GRA8] Wide range. 'Which was deafening' (Relative clause). 'Moving in every direction' (Participle phrase). 'Because the decibel level was...' (Reason clause). 'Could be felt' (Passive). Accurate.",
        "vocabulary": 7,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a noisy place you have been to.\n\nTranscript: I recently visited a construction site near my office, which was deafening. The sound of jackhammers and heavy machinery was constant and overwhelming. Dust filled the air, and workers were shouting instructions to each other. It was chaotic, with trucks moving in every direction. I had to cover my ears because the decibel level was unbearable. The vibration from the drilling could be felt in the ground. I stayed only for a few minutes as I found the environment extremely stressful. It made me appreciate the quiet of my own home. Such noise pollution is a major drawback of urban development.\n\nWord Count: 103 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses 'deafening', 'chaotic', 'decibel', 'unbearable', 'drawback'. Shows awareness of style.\n\n>Band 6: More precise and varied.\n\nNot Band 8: Lacks sophistication.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Wide range of structures used flexibly. Uses relative clauses, participle phrases, and passive voice correctly. Majority of sentences are error-free.\n\n>Band 7: More flexibility.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    }
]

with open(OUTPUT_FILE, 'a', encoding='utf-8') as f:
    for sample in samples:
        f.write(json.dumps(sample) + '\n')
