import json

OUTPUT_FILE = "ielts-data/phase3/v76_review_output/synthetic_batches/batch_p2_13.jsonl"

samples = [
    # 611. V6/G4 - Book (Read)
    {
        "sample_id": "syn_p2_v6_g4_0611",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a magazine you read.",
        "transcript_cleaned": "I read magazine called 'Nature World'. It is about environment and animals. I buy it every month. It has beautiful photos. I like reading articles about climate change. It is very educational. The writers are experts. However, the language is little difficult. I use dictionary to understand. I learn many new words. It help me improve English. I recommend it to my friends. It is informative magazine.",
        "word_count": 83,
        "response_type": "long_turn",
        "micro_flaws": ["article: 'read magazine' should be 'read a magazine'", "article: 'about environment' should be 'about the environment'", "article: 'use dictionary' should be 'use a dictionary'", "agreement: 'It help' should be 'It helps'", "article: 'improve English' should be 'improve my English'", "article: 'informative magazine' should be 'an informative magazine'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR6] Vocabulary: 'magazine', 'environment', 'articles', 'climate change', 'educational', 'experts', 'dictionary', 'improve', 'recommend', 'informative'. Good range of topic vocabulary. >Band 5: Uses specific words ('educational', 'informative'). Not Band 7: Lacks depth.",
        "grammar_reason": "[GRA4] Only simple sentences. Systematic errors in articles ('read magazine', 'use dictionary') and agreement ('It help'). >Band 3: Basic structures. Not Band 5: Errors are pervasive.",
        "vocabulary": 6,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a magazine you read.\n\nTranscript: I read magazine called 'Nature World'. It is about environment and animals. I buy it every month. It has beautiful photos. I like reading articles about climate change. It is very educational. The writers are experts. However, the language is little difficult. I use dictionary to understand. I learn many new words. It help me improve English. I recommend it to my friends. It is informative magazine.\n\nWord Count: 83 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses relevant vocabulary: 'educational', 'climate change', 'informative'. Clear descriptions.\n\n>Band 5: Good range.\n\nNot Band 7: Lacks sophistication.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Simple sentences only. Frequent errors in articles and agreement ('It help').\n\n>Band 3: Simple structures.\n\nNot Band 5: Systematic errors.\n\n**Micro flaws identified:**\n- 'read magazine' should be 'read a magazine'\n- 'about environment' should be 'about the environment'\n- 'use dictionary' should be 'use a dictionary'\n- 'It help' should be 'It helps'\n- 'improve English' should be 'improve my English'\n- 'informative magazine' should be 'an informative magazine'"
    },
    # 612. V6/G4 - Place (Town)
    {
        "sample_id": "syn_p2_v6_g4_0612",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a town you visited.",
        "transcript_cleaned": "I visit small town called Hoi An in Vietnam. It is historic place. There are many old houses. The streets is narrow and colorful. I see many lanterns at night. It look very beautiful. Tourists likes to take photos there. I eat traditional food, which is delicious. The people is friendly and helpful. I buy some souvenirs for my family. I want go back there again. It is peaceful town.",
        "word_count": 85,
        "response_type": "long_turn",
        "micro_flaws": ["tense: 'I visit' should be 'I visited'", "article: 'small town' should be 'a small town'", "article: 'historic place' should be 'a historic place'", "agreement: 'streets is' should be 'streets are'", "tense: 'I see' should be 'I saw'", "agreement: 'It look' should be 'It looked'", "agreement: 'Tourists likes' should be 'Tourist like'", "tense: 'I eat' should be 'I ate'", "agreement: 'people is' should be 'people are'", "tense: 'I buy' should be 'I bought'", "grammar: 'want go' should be 'want to go'", "article: 'peaceful town' should be 'a peaceful town'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR6] Vocabulary: 'historic', 'narrow', 'colorful', 'lanterns', 'tourists', 'traditional food', 'delicious', 'friendly', 'souvenirs', 'peaceful'. Adequate range. >Band 5: Uses specific adjectives ('historic', 'peaceful'). Not Band 7: Vocabulary is standard.",
        "grammar_reason": "[GRA4] Only simple sentences. Systematic errors in tense ('visit', 'see', 'eat'), agreement ('streets is', 'It look'), and articles. >Band 3: Basic meaning conveyed. Not Band 5: Errors are very frequent.",
        "vocabulary": 6,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a town you visited.\n\nTranscript: I visit small town called Hoi An in Vietnam. It is historic place. There are many old houses. The streets is narrow and colorful. I see many lanterns at night. It look very beautiful. Tourists likes to take photos there. I eat traditional food, which is delicious. The people is friendly and helpful. I buy some souvenirs for my family. I want go back there again. It is peaceful town.\n\nWord Count: 85 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses descriptive words: 'historic', 'lanterns', 'traditional'. Clear meaning.\n\n>Band 5: Good range.\n\nNot Band 7: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Simple sentences only. Frequent errors in past tense and agreement ('streets is'). Missing articles.\n\n>Band 3: Simple structures.\n\nNot Band 5: Systematic errors.\n\n**Micro flaws identified:**\n- 'I visit' should be 'I visited'\n- 'small town' should be 'a small town'\n- 'historic place' should be 'a historic place'\n- 'streets is' should be 'streets are'\n- 'I see' should be 'I saw'\n- 'It look' should be 'It looked'\n- 'Tourists likes' should be 'Tourists like'\n- 'I eat' should be 'I ate'\n- 'people is' should be 'people are'\n- 'I buy' should be 'I bought'\n- 'want go' should be 'want to go'\n- 'peaceful town' should be 'a peaceful town'"
    },
    # 613. V6/G4 - Event (Concert)
    {
        "sample_id": "syn_p2_v6_g4_0613",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a live performance you watched.",
        "transcript_cleaned": "I watch dance performance last month. It was ballet show. The dancers wear beautiful costumes. They move very gracefully. The music is classical and relaxing. I go with my sister. She like ballet very much. The stage have many lights. It look magical. I feel happy when I watch it. The performance last two hours. We clap loudly at end. It is memorable experience. I want learn dance in future.",
        "word_count": 87,
        "response_type": "long_turn",
        "micro_flaws": ["tense: 'I watch' should be 'I watched'", "article: 'ballet show' should be 'a ballet show'", "agreement: 'dancers wear' should be 'dancers wore'", "agreement: 'They move' should be 'They moved'", "tense: 'music is' should be 'music was'", "tense: 'I go' should be 'I went'", "agreement: 'She like' should be 'She likes' (or liked)", "agreement: 'stage have' should be 'stage had'", "agreement: 'It look' should be 'It looked'", "tense: 'I feel' should be 'I felt'", "agreement: 'performance last' should be 'performance lasted'", "tense: 'We clap' should be 'We clapped'", "article: 'at end' should be 'at the end'", "article: 'memorable experience' should be 'a memorable experience'", "grammar: 'want learn' should be 'want to learn'", "article: 'in future' should be 'in the future'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR6] Vocabulary: 'dance performance', 'ballet', 'costumes', 'gracefully', 'classical', 'relaxing', 'stage', 'magical', 'memorable experience'. Adequate range. >Band 5: Uses specific adverbs ('gracefully'). Not Band 7: Lacks depth.",
        "grammar_reason": "[GRA4] Only simple sentences. Systematic errors in tense ('watch', 'is', 'go'), agreement ('She like', 'stage have'), and articles. >Band 3: Basic structures. Not Band 5: Errors are very frequent.",
        "vocabulary": 6,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a live performance you watched.\n\nTranscript: I watch dance performance last month. It was ballet show. The dancers wear beautiful costumes. They move very gracefully. The music is classical and relaxing. I go with my sister. She like ballet very much. The stage have many lights. It look magical. I feel happy when I watch it. The performance last two hours. We clap loudly at end. It is memorable experience. I want learn dance in future.\n\nWord Count: 87 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses relevant vocabulary: 'ballet', 'gracefully', 'classical'. Clear description.\n\n>Band 5: Good range.\n\nNot Band 7: Lacks sophistication.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Simple sentences only. Frequent errors in tense ('watch', 'go') and agreement. Missing articles.\n\n>Band 3: Simple structures.\n\nNot Band 5: Systematic errors.\n\n**Micro flaws identified:**\n- 'I watch' should be 'I watched'\n- 'ballet show' should be 'a ballet show'\n- 'dancers wear' should be 'dancers wore'\n- 'They move' should be 'They moved'\n- 'music is' should be 'music was'\n- 'I go' should be 'I went'\n- 'She like' should be 'She likes'\n- 'stage have' should be 'stage had'\n- 'It look' should be 'It looked'\n- 'I feel' should be 'I felt'\n- 'performance last' should be 'performance lasted'\n- 'We clap' should be 'We clapped'\n- 'at end' should be 'at the end'\n- 'memorable experience' should be 'a memorable experience'\n- 'want learn' should be 'want to learn'\n- 'in future' should be 'in the future'"
    },
    # 614. V6/G4 - Person (Family)
    {
        "sample_id": "syn_p2_v6_g4_0614",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a family member you admire.",
        "transcript_cleaned": "I admire my father. He is engineer. He work very hard. He design bridges and roads. He is very intelligent man. He solve difficult problems every day. He also help me with math homework. He is patient and kind. I want be like him. He teach me to play chess. We play on weekends. He always win. He tell me stories about his job. It sound interesting. He is role model for me.",
        "word_count": 87,
        "response_type": "long_turn",
        "micro_flaws": ["article: 'is engineer' should be 'is an engineer'", "agreement: 'He work' should be 'He works'", "agreement: 'He design' should be 'He designs'", "article: 'intelligent man' should be 'an intelligent man'", "agreement: 'He solve' should be 'He solves'", "agreement: 'He also help' should be 'He also helps'", "grammar: 'want be' should be 'want to be'", "agreement: 'He teach' should be 'He teaches'", "agreement: 'He always win' should be 'He always wins'", "agreement: 'He tell' should be 'He tells'", "agreement: 'It sound' should be 'It sounds'", "article: 'is role model' should be 'is a role model'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR6] Vocabulary: 'admire', 'engineer', 'design', 'bridges', 'roads', 'intelligent', 'difficult problems', 'math homework', 'patient', 'chess', 'interesting', 'role model'. Adequate range. >Band 5: Uses specific words ('role model', 'intelligent'). Not Band 7: Vocabulary is standard.",
        "grammar_reason": "[GRA4] Only simple sentences. Systematic errors in agreement ('He work', 'He design', 'He solve', 'He teach'). Missing articles and prepositions. >Band 3: Basic structures. Not Band 5: Errors are pervasive.",
        "vocabulary": 6,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a family member you admire.\n\nTranscript: I admire my father. He is engineer. He work very hard. He design bridges and roads. He is very intelligent man. He solve difficult problems every day. He also help me with math homework. He is patient and kind. I want be like him. He teach me to play chess. We play on weekends. He always win. He tell me stories about his job. It sound interesting. He is role model for me.\n\nWord Count: 87 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses relevant vocabulary: 'engineer', 'intelligent', 'patient'. Clear description.\n\n>Band 5: Good range.\n\nNot Band 7: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Simple sentences only. Frequent errors in agreement ('He work', 'He design'). Missing articles.\n\n>Band 3: Simple structures.\n\nNot Band 5: Systematic errors.\n\n**Micro flaws identified:**\n- 'is engineer' should be 'is an engineer'\n- 'He work' should be 'He works'\n- 'He design' should be 'He designs'\n- 'intelligent man' should be 'an intelligent man'\n- 'He solve' should be 'He solves'\n- 'He also help' should be 'He also helps'\n- 'want be' should be 'want to be'\n- 'He teach' should be 'He teaches'\n- 'He always win' should be 'He always wins'\n- 'He tell' should be 'He tells'\n- 'It sound' should be 'It sounds'\n- 'is role model' should be 'is a role model'"
    },
    # 615. V6/G4 - Activity (Exercise)
    {
        "sample_id": "syn_p2_v6_g4_0615",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a sport you played.",
        "transcript_cleaned": "I play basketball in school team last year. It is popular sport. I am tall, so I am good at it. We practice three times week. The coach is strict but good. He teach us how to dribble and shoot. We play match against other schools. It is very competitive. I score many points. My team win trophy. I feel very proud. Basketball help me stay fit. I like play with my teammates. It is good exercise.",
        "word_count": 92,
        "response_type": "long_turn",
        "micro_flaws": ["tense: 'I play' should be 'I played'", "article: 'in school team' should be 'in the school team'", "article: 'popular sport' should be 'a popular sport'", "article: 'three times week' should be 'three times a week'", "agreement: 'He teach' should be 'He taught'", "article: 'play match' should be 'played matches'", "tense: 'I score' should be 'I scored'", "tense: 'team win' should be 'team won'", "article: 'win trophy' should be 'won the trophy'", "tense: 'I feel' should be 'I felt'", "agreement: 'Basketball help' should be 'Basketball helps'", "verb: 'like play' should be 'like playing'", "article: 'good exercise' should be 'good exercise' (ok but simple)"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR6] Vocabulary: 'basketball', 'team', 'popular', 'practice', 'coach', 'strict', 'dribble', 'shoot', 'competitive', 'score points', 'trophy', 'proud', 'stay fit', 'teammates'. Adequate range. >Band 5: Uses specific words ('dribble', 'shoot'). Not Band 7: Vocabulary is standard.",
        "grammar_reason": "[GRA4] Only simple sentences. Systematic errors in tense ('play', 'teach', 'score', 'win') and agreement. Missing articles. >Band 3: Basic meaning clear. Not Band 5: Errors are pervasive.",
        "vocabulary": 6,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a sport you played.\n\nTranscript: I play basketball in school team last year. It is popular sport. I am tall, so I am good at it. We practice three times week. The coach is strict but good. He teach us how to dribble and shoot. We play match against other schools. It is very competitive. I score many points. My team win trophy. I feel very proud. Basketball help me stay fit. I like play with my teammates. It is good exercise.\n\nWord Count: 92 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses topic words: 'dribble', 'shoot', 'competitive'. Meaning is clear.\n\n>Band 5: Good range.\n\nNot Band 7: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Simple sentences only. Frequent errors in past tense and agreement. Missing articles.\n\n>Band 3: Simple structures.\n\nNot Band 5: Systematic errors.\n\n**Micro flaws identified:**\n- 'I play' should be 'I played'\n- 'in school team' should be 'in the school team'\n- 'popular sport' should be 'a popular sport'\n- 'three times week' should be 'three times a week'\n- 'He teach' should be 'He taught'\n- 'play match' should be 'played matches'\n- 'I score' should be 'I scored'\n- 'team win' should be 'team won'\n- 'win trophy' should be 'won the trophy'\n- 'I feel' should be 'I felt'\n- 'Basketball help' should be 'Basketball helps'\n- 'like play' should be 'like playing'"
    },
    # 616. V4/G7 - Book (Childhood)
    {
        "sample_id": "syn_p2_v4_g7_0616",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a story you liked as a child.",
        "transcript_cleaned": "I remember a story about a bear. It was a brown bear who lived in a forest. One day, he found a pot of honey. Although he was hungry, he did not eat it. He wanted to share it with his friends. He walked for a long time to find them. When he found them, they were very happy. They ate the honey together. It is a nice story because it teaches about sharing. If I have children, I will tell them this story.",
        "word_count": 103,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR4] Limited range: 'story', 'bear', 'forest', 'honey', 'hungry', 'eat', 'share', 'friends', 'walked', 'happy', 'nice', 'teaches'. Basic vocabulary. >Band 3: Communicates plot. Not Band 5: Minimal descriptive language.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'Who lived in a forest' (Relative clause). 'Although he was hungry...' (Concessive clause). 'When he found them' (Time clause). 'If I have children...' (First conditional). Accurate. >Band 6: Good control. Not Band 8: Vocabulary limits complexity.",
        "vocabulary": 4,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a story you liked as a child.\n\nTranscript: I remember a story about a bear. It was a brown bear who lived in a forest. One day, he found a pot of honey. Although he was hungry, he did not eat it. He wanted to share it with his friends. He walked for a long time to find them. When he found them, they were very happy. They ate the honey together. It is a nice story because it teaches about sharing. If I have children, I will tell them this story.\n\nWord Count: 103 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Basic vocabulary: 'bear', 'honey', 'share'. Simple narrative. No range.\n\n>Band 3: Basic story.\n\nNot Band 5: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures like relative clauses and concessive clauses correctly. Good grammatical control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Limited by vocabulary.\n\n**Micro flaws identified:**\n- None."
    },
    # 617. V4/G7 - Place (City)
    {
        "sample_id": "syn_p2_v4_g7_0617",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a place you like.",
        "transcript_cleaned": "I like the beach near my house. It is a big place with lots of sand. I go there when the weather is hot. I like to swim in the water, which is blue. Sometimes, I see fish swimming. If I am tired, I sit on the sand. It is very quiet there. I like it because it makes me happy. Although it is far, I walk there. It is a good place for me.",
        "word_count": 92,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR4] Limited range: 'beach', 'house', 'big', 'sand', 'weather', 'hot', 'swim', 'water', 'blue', 'fish', 'tired', 'quiet', 'happy', 'far', 'walk', 'good'. Basic vocabulary. >Band 3: Clear description. Not Band 5: Minimal variation.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'When the weather is hot' (Time clause). 'Which is blue' (Relative clause). 'If I am tired...' (First conditional). 'Because it makes me happy' (Reason clause). 'Although it is far...' (Concessive clause). Accurate.",
        "vocabulary": 4,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a place you like.\n\nTranscript: I like the beach near my house. It is a big place with lots of sand. I go there when the weather is hot. I like to swim in the water, which is blue. Sometimes, I see fish swimming. If I am tired, I sit on the sand. It is very quiet there. I like it because it makes me happy. Although it is far, I walk there. It is a good place for me.\n\nWord Count: 92 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Basic vocabulary: 'beach', 'sand', 'water'. Simple description. No range.\n\n>Band 3: Basic meaning.\n\nNot Band 5: Lacks descriptive words.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures like relative clauses and conditionals correctly. Good control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Limited by vocabulary.\n\n**Micro flaws identified:**\n- None."
    },
    # 618. V4/G7 - Event (Party)
    {
        "sample_id": "syn_p2_v4_g7_0618",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a party you went to.",
        "transcript_cleaned": "I went to a birthday party last week. It was for my friend. We ate pizza and cake, which were very good. We played games in the garden. I was happy because I saw my friends. If we had more time, we would have played more. Although it rained, we stayed outside. The party finished late. It was a fun day. I gave my friend a book. He liked it very much.",
        "word_count": 88,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR4] Limited range: 'party', 'birthday', 'friend', 'pizza', 'cake', 'good', 'games', 'garden', 'happy', 'rain', 'outside', 'finished', 'fun', 'book', 'liked'. Basic vocabulary. >Band 3: Clear narrative. Not Band 5: Minimal variation.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'Which were very good' (Relative clause). 'Because I saw my friends' (Reason clause). 'If we had more time, we would have played' (Second conditional - mixed). 'Although it rained...' (Concessive clause). Accurate.",
        "vocabulary": 4,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a party you went to.\n\nTranscript: I went to a birthday party last week. It was for my friend. We ate pizza and cake, which were very good. We played games in the garden. I was happy because I saw my friends. If we had more time, we would have played more. Although it rained, we stayed outside. The party finished late. It was a fun day. I gave my friend a book. He liked it very much.\n\nWord Count: 88 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Basic vocabulary: 'party', 'games', 'fun'. Simple story. No range.\n\n>Band 3: Basic narrative.\n\nNot Band 5: Lacks descriptive words.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures like relative clauses and conditionals correctly. Good control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Limited by vocabulary.\n\n**Micro flaws identified:**\n- None."
    },
    # 619. V4/G7 - Object (Toy)
    {
        "sample_id": "syn_p2_v4_g7_0619",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a toy you liked.",
        "transcript_cleaned": "I had a toy car when I was a boy. It was red and fast. I played with it every day. I liked it because it had big wheels. If I pushed it, it went very far. I kept it in a box so it would not break. Although I have many toys, this was my favorite. My father gave it to me. I still have it in my room. It is a good memory.",
        "word_count": 92,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR4] Limited range: 'toy car', 'boy', 'red', 'fast', 'played', 'wheels', 'pushed', 'far', 'box', 'break', 'toys', 'favorite', 'room', 'memory'. Basic vocabulary. >Band 3: Clear description. Not Band 5: Minimal variation.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'When I was a boy' (Time clause). 'Because it had big wheels' (Reason clause). 'If I pushed it...' (Zero/First conditional in past context). 'So it would not break' (Purpose clause). 'Although I have...' (Concessive clause). Accurate.",
        "vocabulary": 4,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a toy you liked.\n\nTranscript: I had a toy car when I was a boy. It was red and fast. I played with it every day. I liked it because it had big wheels. If I pushed it, it went very far. I kept it in a box so it would not break. Although I have many toys, this was my favorite. My father gave it to me. I still have it in my room. It is a good memory.\n\nWord Count: 92 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Basic vocabulary: 'toy', 'wheels', 'box'. Simple description. No range.\n\n>Band 3: Basic meaning.\n\nNot Band 5: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures like purpose clauses and conditionals correctly. Good control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Limited by vocabulary.\n\n**Micro flaws identified:**\n- None."
    },
    # 620. V4/G7 - Person (Friend)
    {
        "sample_id": "syn_p2_v4_g7_0620",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a friend you like.",
        "transcript_cleaned": "I have a friend called Tom. We go to school together. He is a good boy. I like him because he is funny. He makes me laugh when I am sad. We play football in the park, which is near my house. If I need help, he helps me. Although he is small, he is strong. We talk every day. I hope we will be friends for a long time. He is important to me.",
        "word_count": 91,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR4] Limited range: 'friend', 'school', 'good', 'funny', 'laugh', 'sad', 'football', 'park', 'house', 'help', 'small', 'strong', 'talk', 'important'. Basic vocabulary. >Band 3: Clear description. Not Band 5: Minimal variation.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'Because he is funny' (Reason clause). 'When I am sad' (Time clause). 'Which is near my house' (Relative clause). 'If I need help...' (First conditional). 'Although he is small...' (Concessive clause). Accurate.",
        "vocabulary": 4,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a friend you like.\n\nTranscript: I have a friend called Tom. We go to school together. He is a good boy. I like him because he is funny. He makes me laugh when I am sad. We play football in the park, which is near my house. If I need help, he helps me. Although he is small, he is strong. We talk every day. I hope we will be friends for a long time. He is important to me.\n\nWord Count: 91 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Basic vocabulary: 'friend', 'funny', 'strong'. Simple description. No range.\n\n>Band 3: Basic meaning.\n\nNot Band 5: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures like relative clauses and conditionals correctly. Good control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Limited by vocabulary.\n\n**Micro flaws identified:**\n- None."
    }
]

with open(OUTPUT_FILE, 'a', encoding='utf-8') as f:
    for sample in samples:
        f.write(json.dumps(sample) + '\n')
