import json

OUTPUT_FILE = "ielts-data/phase3/v76_review_output/synthetic_batches/batch_p2_07.jsonl"

samples = [
    # 341. V9/G8 - Goal (Achieved)
    {
        "sample_id": "syn_p2_v9_g8_0341",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a goal you set for yourself and achieved.",
        "transcript_cleaned": "I harbored a fervent ambition to master the piano, specifically aiming to perform a Chopin nocturne. The piece's intricate melodic lines and emotive depth were intimidating at first, yet I was resolutely determined to succeed. I committed to a rigorous practice regimen, dedicating several hours each evening to hone my technique and expression. There were moments of exasperation when my fingers fumbled over complex passages, but I persevered through the frustration. The culmination of this arduous endeavor was a small recital where I played the piece flawlessly. The applause was thunderous, and the sense of accomplishment I felt was truly euphoric. It taught me that diligence and tenacity are the cornerstones of success in any field. achieving this goal has imbued me with a newfound confidence to tackle other challenges.",
        "word_count": 139,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "high", "flexibility": "very_high"},
        "vocab_reason": "[LR9] Vocabulary: 'harbored', 'fervent', 'ambition', 'nocturne', 'intricate', 'emotive', 'resolutely', 'rigorous', 'regimen', 'hone', 'exasperation', 'fumbled', 'persevered', 'culmination', 'endeavor', 'flawlessly', 'thunderous', 'euphoric', 'diligence', 'tenacity', 'cornerstones', 'imbued'.",
        "grammar_reason": "[GRA8] Wide range. 'Specifically to perform...' (Infinitive phrase). 'Yet I was resolutely determined' (Conjunction). 'Dedicating hours each evening' (Participle phrase). 'Where I played...' (Relative clause). Occasional very minor slips possible in less controlled speech, but here error-free.",
        "vocabulary": 9,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a goal you set for yourself and achieved.\n\nTranscript: I harbored a fervent ambition to master the piano, specifically aiming to perform a Chopin nocturne. The piece's intricate melodic lines and emotive depth were intimidating at first, yet I was resolutely determined to succeed. I committed to a rigorous practice regimen, dedicating several hours each evening to hone my technique and expression. There were moments of exasperation when my fingers fumbled over complex passages, but I persevered through the frustration. The culmination of this arduous endeavor was a small recital where I played the piece flawlessly. The applause was thunderous, and the sense of accomplishment I felt was truly euphoric. It taught me that diligence and tenacity are the cornerstones of success in any field. achieving this goal has imbued me with a newfound confidence to tackle other challenges.\n\nWord Count: 139 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 9\n\n**Reasoning:** [LR9] Uses 'harbored', 'fervent', 'rigorous', 'exasperation', 'culmination', 'euphoric', 'imbued'. Extremely precise and sophisticated.\n\n>Band 8: Wide range of vocabulary.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Wide range of structures used accurately. Participle phrases and relative clauses are well-formed.\n\n>Band 7: Good control.\n\nNot Band 9: While excellent, lacks the full native-like flexibility across all contexts.\n\n**Micro flaws identified:**\n- None."
    },
    # 342. V9/G8 - Subject (Science)
    {
        "sample_id": "syn_p2_v9_g8_0342",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a science subject you found interesting.",
        "transcript_cleaned": "I was perpetually fascinated by astrophysics during my secondary education, a field that explores the universe. The sheer magnitude of the cosmos and the enigmatic nature of black holes captivated my imagination completely. I vividly remember a module on stellar evolution, detailing the life cycle of stars from nebulae to supernovae. It was mind-bending to comprehend the vast distances and timescales involved in cosmic events. The concept that we are literally made of stardust resonated deeply with me on a philosophical level. Although the mathematical components were arduous and demanding, the theoretical aspects were exhilarating to study. Exploring the fundamental laws governing the universe provided a sense of awe and insignificance simultaneously. It remains a subject of enduring intrigue for me.",
        "word_count": 133,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "high", "flexibility": "very_high"},
        "vocab_reason": "[LR9] Vocabulary: 'perpetually', 'fascinated', 'astrophysics', 'magnitude', 'cosmos', 'enigmatic', 'captivated', 'module', 'stellar', 'evolution', 'nebulae', 'supernovae', 'mind-bending', 'comprehend', 'stardust', 'resonated', 'arduous', 'exhilarating', 'fundamental', 'insignificance', 'enduring', 'intrigue'.",
        "grammar_reason": "[GRA8] Wide range. 'Detailing the life cycle...' (Participle phrase). 'From nebulae to supernovae' (Prepositional phrase). 'Although the mathematical components were arduous' (Concessive clause). 'Exploring... provided...' (Gerund subject). Error-free.",
        "vocabulary": 9,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a science subject you found interesting.\n\nTranscript: I was perpetually fascinated by astrophysics during my secondary education, a field that explores the universe. The sheer magnitude of the cosmos and the enigmatic nature of black holes captivated my imagination completely. I vividly remember a module on stellar evolution, detailing the life cycle of stars from nebulae to supernovae. It was mind-bending to comprehend the vast distances and timescales involved in cosmic events. The concept that we are literally made of stardust resonated deeply with me on a philosophical level. Although the mathematical components were arduous and demanding, the theoretical aspects were exhilarating to study. Exploring the fundamental laws governing the universe provided a sense of awe and insignificance simultaneously. It remains a subject of enduring intrigue for me.\n\nWord Count: 133 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 9\n\n**Reasoning:** [LR9] Uses 'perpetually', 'enigmatic', 'mind-bending', 'arduous', 'insignificance', 'enduring'. Extremely precise and sophisticated.\n\n>Band 8: Wide range of vocabulary.\n\n**Idiom present:** Yes ('mind-bending')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Wide range of structures used accurately. Participle phrases and concessive clauses are well-formed.\n\n>Band 7: Good control.\n\nNot Band 9: Lacks full native-like flexibility.\n\n**Micro flaws identified:**\n- None."
    },
    # 343. V9/G8 - Advertisement
    {
        "sample_id": "syn_p2_v9_g8_0343",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe an advertisement you remember well.",
        "transcript_cleaned": "A particularly memorable advertisement was a sophisticated campaign for an electric vehicle that aired during the Super Bowl. It cleverly juxtaposed the silence of the car with the chaotic noise of urban life to create contrast. The cinematography was stunning, utilizing a monochromatic palette to emphasize the sleek design of the vehicle. What struck me most was the subtlety; it eschewed the typical aggressive marketing for a more nuanced approach. The tagline was minimalist yet profound, leaving a lasting impression on the viewer. It effectively conveyed a sense of serenity and technological innovation. I found myself researching the vehicle immediately after seeing it, which is a testament to the ad's persuasive power. It was a masterclass in visual storytelling.",
        "word_count": 133,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "high", "flexibility": "very_high"},
        "vocab_reason": "[LR9] Vocabulary: 'memorable', 'campaign', 'juxtaposed', 'chaotic', 'cinematography', 'monochromatic', 'palette', 'emphasize', 'sleek', 'subtlety', 'eschewed', 'aggressive', 'nuanced', 'minimalist', 'profound', 'impression', 'conveyed', 'serenity', 'innovation', 'testament', 'persuasive', 'masterclass'.",
        "grammar_reason": "[GRA8] Wide range. 'That aired during...' (Relative clause). 'Utilizing a monochromatic palette...' (Participle phrase). 'What struck me was...' (Cleft sentence). 'Leaving a lasting impression' (Participle phrase). Error-free.",
        "vocabulary": 9,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe an advertisement you remember well.\n\nTranscript: A particularly memorable advertisement was a sophisticated campaign for an electric vehicle that aired during the Super Bowl. It cleverly juxtaposed the silence of the car with the chaotic noise of urban life to create contrast. The cinematography was stunning, utilizing a monochromatic palette to emphasize the sleek design of the vehicle. What struck me most was the subtlety; it eschewed the typical aggressive marketing for a more nuanced approach. The tagline was minimalist yet profound, leaving a lasting impression on the viewer. It effectively conveyed a sense of serenity and technological innovation. I found myself researching the vehicle immediately after seeing it, which is a testament to the ad's persuasive power. It was a masterclass in visual storytelling.\n\nWord Count: 133 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 9\n\n**Reasoning:** [LR9] Uses 'juxtaposed', 'cinematography', 'eschewed', 'nuanced', 'minimalist', 'testament'. Extremely precise and sophisticated.\n\n>Band 8: Wide range of vocabulary.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Wide range of structures used accurately. Participle phrases and cleft sentences are well-formed.\n\n>Band 7: Good control.\n\nNot Band 9: Lacks full native-like flexibility.\n\n**Micro flaws identified:**\n- None."
    },
    # 344. V9/G8 - Job (Ideal)
    {
        "sample_id": "syn_p2_v9_g8_0344",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe your ideal job.",
        "transcript_cleaned": "My quintessential career path would be that of a conservation biologist, specifically working in vulnerable marine ecosystems. I have always held a profound reverence for the ocean and its myriad inhabitants, from the smallest plankton to whales. The role would entail conducting extensive field research to monitor coral reef health and mitigate the detrimental effects of climate change. It would require a unique synthesis of analytical rigor and physical endurance to succeed. I envision myself collaborating with international teams to formulate sustainable policies for ocean protection. The prospect of contributing to the preservation of global biodiversity is incredibly motivating for me. It is not merely a job but a vocation, aligning my professional aspirations with my ethical values. To leave a tangible legacy of environmental stewardship is my ultimate ambition.",
        "word_count": 141,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "high", "flexibility": "very_high"},
        "vocab_reason": "[LR9] Vocabulary: 'quintessential', 'conservation', 'biologist', 'ecosystems', 'profound', 'reverence', 'myriad', 'inhabitants', 'entail', 'monitor', 'mitigate', 'detrimental', 'synthesis', 'analytical', 'rigor', 'endurance', 'envision', 'collaborating', 'formulate', 'sustainable', 'preservation', 'biodiversity', 'motivating', 'vocation', 'aligning', 'aspirations', 'ethical', 'tangible', 'legacy', 'stewardship'.",
        "grammar_reason": "[GRA8] Wide range. 'Specifically working in...' (Participle phrase). 'To monitor... and mitigate...' (Infinitive of purpose). 'Collaborating with...' (Participle phrase). 'Aligning my professional aspirations...' (Participle phrase). Error-free.",
        "vocabulary": 9,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe your ideal job.\n\nTranscript: My quintessential career path would be that of a conservation biologist, specifically working in vulnerable marine ecosystems. I have always held a profound reverence for the ocean and its myriad inhabitants, from the smallest plankton to whales. The role would entail conducting extensive field research to monitor coral reef health and mitigate the detrimental effects of climate change. It would require a unique synthesis of analytical rigor and physical endurance to succeed. I envision myself collaborating with international teams to formulate sustainable policies for ocean protection. The prospect of contributing to the preservation of global biodiversity is incredibly motivating for me. It is not merely a job but a vocation, aligning my professional aspirations with my ethical values. To leave a tangible legacy of environmental stewardship is my ultimate ambition.\n\nWord Count: 141 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 9\n\n**Reasoning:** [LR9] Uses 'quintessential', 'reverence', 'mitigate', 'detrimental', 'synthesis', 'vocation', 'stewardship'. Extremely precise and sophisticated.\n\n>Band 8: Wide range of vocabulary.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Wide range of structures used accurately. Participle phrases and infinitives are well-formed.\n\n>Band 7: Good control.\n\nNot Band 9: Lacks full native-like flexibility.\n\n**Micro flaws identified:**\n- None."
    },
    # 345. V9/G8 - Toy (Childhood)
    {
        "sample_id": "syn_p2_v9_g8_0345",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a toy you liked as a child.",
        "transcript_cleaned": "I cherished a rudimentary yet intricate construction set given to me by my grandfather when I was a young boy. It was a precursor to modern Lego, consisting of metal beams, nuts, and bolts. I would spend countless hours engrossed in assembling elaborate structures, from towering cranes to suspension bridges. This toy was pivotal in fostering my spatial awareness and mechanical curiosity from an early age. It allowed me to manifest my imagination into tangible forms I could hold. I remember the immense satisfaction of tightening the final screw on a complex model. It wasn't just a plaything; it was an educational tool that laid the foundation for my lifelong interest in engineering. I still possess it, a nostalgic relic of my formative years.",
        "word_count": 137,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "high", "flexibility": "very_high"},
        "vocab_reason": "[LR9] Vocabulary: 'cherished', 'rudimentary', 'intricate', 'precursor', 'consisting', 'engrossed', 'assembling', 'elaborate', 'pivotal', 'fostering', 'spatial', 'awareness', 'mechanical', 'curiosity', 'manifest', 'tangible', 'immense', 'satisfaction', 'plaything', 'foundation', 'engineering', 'possess', 'nostalgic', 'relic', 'formative'.",
        "grammar_reason": "[GRA8] Wide range. 'Given to me by...' (Participle phrase). 'Consisting of...' (Participle phrase). 'From cranes to bridges' (Prepositional phrase). 'Tightening the final screw' (Gerund phrase). Error-free.",
        "vocabulary": 9,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a toy you liked as a child.\n\nTranscript: I cherished a rudimentary yet intricate construction set given to me by my grandfather when I was a young boy. It was a precursor to modern Lego, consisting of metal beams, nuts, and bolts. I would spend countless hours engrossed in assembling elaborate structures, from towering cranes to suspension bridges. This toy was pivotal in fostering my spatial awareness and mechanical curiosity from an early age. It allowed me to manifest my imagination into tangible forms I could hold. I remember the immense satisfaction of tightening the final screw on a complex model. It wasn't just a plaything; it was an educational tool that laid the foundation for my lifelong interest in engineering. I still possess it, a nostalgic relic of my formative years.\n\nWord Count: 137 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 9\n\n**Reasoning:** [LR9] Uses 'rudimentary', 'intricate', 'precursor', 'engrossed', 'pivotal', 'manifest', 'relic'. Extremely precise and sophisticated.\n\n>Band 8: Wide range of vocabulary.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Wide range of structures used accurately. Participle phrases and gerund phrases are well-formed.\n\n>Band 7: Good control.\n\nNot Band 9: Lacks full native-like flexibility.\n\n**Micro flaws identified:**\n- None."
    },
    # 346. V9/G8 - Place (Quiet)
    {
        "sample_id": "syn_p2_v9_g8_0346",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a quiet place you like to go to.",
        "transcript_cleaned": "I frequently retreat to a secluded alcove in the municipal library, which serves as a haven of tranquility amidst the urban cacophony. It is situated in the archives section, a dusty corner where the scent of aging paper permeates the air. The silence there is profound, broken only by the occasional turning of a page or a distant footstep. I go there to immerse myself in classic literature or to contemplate complex problems without any distraction. The atmosphere is incredibly conducive to introspection and deep thought. Surrounded by centuries of knowledge, I feel a sense of humility and inner peace. It is my personal sanctuary where I can recharge my mental faculties and escape the relentless pace of modern life.",
        "word_count": 133,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "high", "flexibility": "very_high"},
        "vocab_reason": "[LR9] Vocabulary: 'retreat', 'secluded', 'alcove', 'municipal', 'haven', 'tranquility', 'cacophony', 'situated', 'archives', 'permeates', 'profound', 'occasional', 'immerse', 'contemplate', 'distraction', 'atmosphere', 'conducive', 'introspection', 'humility', 'sanctuary', 'recharge', 'faculties', 'relentless'.",
        "grammar_reason": "[GRA8] Wide range. 'Situated in the archives...' (Participle phrase). 'Where the scent... permeates' (Relative clause). 'Broken only by...' (Participle phrase). 'Surrounded by centuries...' (Participle phrase). Error-free.",
        "vocabulary": 9,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a quiet place you like to go to.\n\nTranscript: I frequently retreat to a secluded alcove in the municipal library, which serves as a haven of tranquility amidst the urban cacophony. It is situated in the archives section, a dusty corner where the scent of aging paper permeates the air. The silence there is profound, broken only by the occasional turning of a page or a distant footstep. I go there to immerse myself in classic literature or to contemplate complex problems without any distraction. The atmosphere is incredibly conducive to introspection and deep thought. Surrounded by centuries of knowledge, I feel a sense of humility and inner peace. It is my personal sanctuary where I can recharge my mental faculties and escape the relentless pace of modern life.\n\nWord Count: 133 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 9\n\n**Reasoning:** [LR9] Uses 'secluded', 'alcove', 'cacophony', 'permeates', 'conducive', 'introspection', 'faculties'. Extremely precise and sophisticated.\n\n>Band 8: Wide range of vocabulary.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Wide range of structures used accurately. Participle phrases and relative clauses are well-formed.\n\n>Band 7: Good control.\n\nNot Band 9: Lacks full native-like flexibility.\n\n**Micro flaws identified:**\n- None."
    },
    # 347. V9/G8 - Journey (Car)
    {
        "sample_id": "syn_p2_v9_g8_0347",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a car journey you enjoyed.",
        "transcript_cleaned": "I embarked on a scenic road trip along the Pacific Coast Highway, a famous route renowned for its breathtaking vistas. The journey was entirely spontaneous, allowing for serendipitous discoveries along the way. Driving with the convertible top down, I felt an exhilarating sense of liberation as the wind rushed past. The juxtaposition of the rugged cliffs and the azure ocean was visually arresting and unforgettable. We stopped at quaint coastal towns, indulging in local culinary delights like fresh seafood. The winding roads demanded attentive driving, which I found surprisingly meditative and calming. Watching the sunset over the horizon was the pinnacle of the experience. That trip was a perfect amalgamation of adventure and relaxation, leaving me with indelible memories.",
        "word_count": 131,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "high", "flexibility": "very_high"},
        "vocab_reason": "[LR9] Vocabulary: 'embarked', 'scenic', 'renowned', 'breathtaking', 'vistas', 'spontaneous', 'serendipitous', 'convertible', 'exhilarating', 'liberation', 'juxtaposition', 'rugged', 'azure', 'arresting', 'quaint', 'indulging', 'culinary', 'delights', 'meditative', 'pinnacle', 'amalgamation', 'indelible'.",
        "grammar_reason": "[GRA8] Wide range. 'Renowned for its...' (Participle phrase). 'Allowing for serendipitous discoveries' (Participle phrase). 'Driving with the convertible top down' (Participle phrase). 'Which I found surprisingly meditative' (Relative clause). Error-free.",
        "vocabulary": 9,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a car journey you enjoyed.\n\nTranscript: I embarked on a scenic road trip along the Pacific Coast Highway, a famous route renowned for its breathtaking vistas. The journey was entirely spontaneous, allowing for serendipitous discoveries along the way. Driving with the convertible top down, I felt an exhilarating sense of liberation as the wind rushed past. The juxtaposition of the rugged cliffs and the azure ocean was visually arresting and unforgettable. We stopped at quaint coastal towns, indulging in local culinary delights like fresh seafood. The winding roads demanded attentive driving, which I found surprisingly meditative and calming. Watching the sunset over the horizon was the pinnacle of the experience. That trip was a perfect amalgamation of adventure and relaxation, leaving me with indelible memories.\n\nWord Count: 131 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 9\n\n**Reasoning:** [LR9] Uses 'serendipitous', 'exhilarating', 'juxtaposition', 'arresting', 'amalgamation', 'indelible'. Extremely precise and sophisticated.\n\n>Band 8: Wide range of vocabulary.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Wide range of structures used accurately. Participle phrases and relative clauses are well-formed.\n\n>Band 7: Good control.\n\nNot Band 9: Lacks full native-like flexibility.\n\n**Micro flaws identified:**\n- None."
    },
    # 348. V9/G8 - Festival
    {
        "sample_id": "syn_p2_v9_g8_0348",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a festival you have attended.",
        "transcript_cleaned": "I attended the Lantern Festival in Taiwan, a spectacle of light and artistry that was truly mesmerizing to witness. Thousands of intricate paper lanterns were released into the night sky, creating a constellation of warm, glowing orbs. The atmosphere was charged with a palpable sense of hope and renewal among the crowd. It is a tradition steeped in folklore, symbolizing the release of past burdens and the welcoming of the future. I was particularly struck by the craftsmanship of the larger floats, which depicted mythical creatures with astonishing detail. Being part of such a collective cultural expression was a profound experience for me. The visual grandeur combined with the communal spirit made it an unforgettable event.",
        "word_count": 128,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "high", "flexibility": "very_high"},
        "vocab_reason": "[LR9] Vocabulary: 'spectacle', 'artistry', 'mesmerizing', 'intricate', 'constellation', 'orbs', 'charged', 'palpable', 'renewal', 'tradition', 'steeped', 'folklore', 'symbolizing', 'burdens', 'craftsmanship', 'depicted', 'mythical', 'astonishing', 'collective', 'cultural', 'expression', 'profound', 'grandeur', 'communal'.",
        "grammar_reason": "[GRA8] Wide range. 'That was truly mesmerizing' (Relative clause). 'Creating a constellation...' (Participle phrase). 'Steeped in folklore' (Participle phrase). 'Symbolizing the release...' (Participle phrase). 'Which depicted mythical creatures' (Relative clause). Error-free.",
        "vocabulary": 9,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a festival you have attended.\n\nTranscript: I attended the Lantern Festival in Taiwan, a spectacle of light and artistry that was truly mesmerizing to witness. Thousands of intricate paper lanterns were released into the night sky, creating a constellation of warm, glowing orbs. The atmosphere was charged with a palpable sense of hope and renewal among the crowd. It is a tradition steeped in folklore, symbolizing the release of past burdens and the welcoming of the future. I was particularly struck by the craftsmanship of the larger floats, which depicted mythical creatures with astonishing detail. Being part of such a collective cultural expression was a profound experience for me. The visual grandeur combined with the communal spirit made it an unforgettable event.\n\nWord Count: 128 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 9\n\n**Reasoning:** [LR9] Uses 'spectacle', 'mesmerizing', 'palpable', 'steeped', 'folklore', 'craftsmanship', 'grandeur'. Extremely precise and sophisticated.\n\n>Band 8: Wide range of vocabulary.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Wide range of structures used accurately. Participle phrases and relative clauses are well-formed.\n\n>Band 7: Good control.\n\nNot Band 9: Lacks full native-like flexibility.\n\n**Micro flaws identified:**\n- None."
    },
    # 349. V9/G8 - Advice (Received)
    {
        "sample_id": "syn_p2_v9_g8_0349",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a piece of advice you received.",
        "transcript_cleaned": "A mentor once imparted a piece of wisdom that has resonated with me ever since: 'Perfection is the enemy of progress.' At the time, I was paralyzed by a meticulous attention to detail that hindered my productivity significantly. His counsel illuminated the futility of chasing an unattainable standard in my work. He encouraged me to embrace an iterative process, viewing mistakes as pedagogical opportunities rather than personal failures. This paradigm shift was liberating and changed my approach completely. I learned to prioritize pragmatic execution over flawless theoretical planning. Applying this philosophy has exponentially increased my output and reduced my anxiety levels. It was a transformative insight that I now pass on to others.",
        "word_count": 125,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "high", "flexibility": "very_high"},
        "vocab_reason": "[LR9] Vocabulary: 'mentor', 'imparted', 'wisdom', 'resonated', 'paralyzed', 'meticulous', 'hindered', 'productivity', 'counsel', 'illuminated', 'futility', 'unattainable', 'encouraged', 'embrace', 'iterative', 'pedagogical', 'paradigm', 'shift', 'liberating', 'prioritize', 'pragmatic', 'execution', 'flawless', 'theoretical', 'exponentially', 'transformative', 'insight'.",
        "grammar_reason": "[GRA8] Wide range. 'That has resonated with me...' (Relative clause). 'Paralyzed by a meticulous attention...' (Participle phrase). 'Viewing mistakes as...' (Participle phrase). 'Applying this philosophy has...' (Gerund subject). Error-free.",
        "vocabulary": 9,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a piece of advice you received.\n\nTranscript: A mentor once imparted a piece of wisdom that has resonated with me ever since: 'Perfection is the enemy of progress.' At the time, I was paralyzed by a meticulous attention to detail that hindered my productivity significantly. His counsel illuminated the futility of chasing an unattainable standard in my work. He encouraged me to embrace an iterative process, viewing mistakes as pedagogical opportunities rather than personal failures. This paradigm shift was liberating and changed my approach completely. I learned to prioritize pragmatic execution over flawless theoretical planning. Applying this philosophy has exponentially increased my output and reduced my anxiety levels. It was a transformative insight that I now pass on to others.\n\nWord Count: 125 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 9\n\n**Reasoning:** [LR9] Uses 'imparted', 'meticulous', 'futility', 'iterative', 'pedagogical', 'paradigm', 'pragmatic'. Extremely precise and sophisticated.\n\n>Band 8: Wide range of vocabulary.\n\n**Idiom present:** Yes ('paradigm shift')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Wide range of structures used accurately. Participle phrases and gerund subjects are well-formed.\n\n>Band 7: Good control.\n\nNot Band 9: Lacks full native-like flexibility.\n\n**Micro flaws identified:**\n- None."
    },
    # 350. V9/G8 - Skill (Learned)
    {
        "sample_id": "syn_p2_v9_g8_0350",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a practical skill you learned.",
        "transcript_cleaned": "I acquired the skill of digital photography, which is a perfect blend of technical proficiency and artistic vision. Initially, the array of settings on a DSLR camera was bewildering, but I was eager to decipher them. I diligently studied the nuances of aperture, shutter speed, and ISO to manipulate light and composition. Mastering the 'rule of thirds' significantly enhanced the aesthetic quality of my images. The process of capturing ephemeral moments and rendering them into permanent visual records is deeply satisfying to me. It has sharpened my observational skills, compelling me to notice details I previously overlooked. Photography has become a vital medium for my creative expression and a way to document my life's journey.",
        "word_count": 130,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "high", "flexibility": "very_high"},
        "vocab_reason": "[LR9] Vocabulary: 'acquired', 'proficiency', 'vision', 'array', 'bewildering', 'decipher', 'nuances', 'aperture', 'manipulate', 'composition', 'mastering', 'aesthetic', 'ephemeral', 'rendering', 'permanent', 'observational', 'compelling', 'overlooked', 'vital', 'medium'.",
        "grammar_reason": "[GRA8] Wide range. 'A blend of...' (Appositive). 'To manipulate light...' (Infinitive of purpose). 'Mastering the rule of thirds' (Gerund subject). 'Compelling me to notice...' (Participle phrase). Error-free.",
        "vocabulary": 9,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a practical skill you learned.\n\nTranscript: I acquired the skill of digital photography, which is a perfect blend of technical proficiency and artistic vision. Initially, the array of settings on a DSLR camera was bewildering, but I was eager to decipher them. I diligently studied the nuances of aperture, shutter speed, and ISO to manipulate light and composition. Mastering the 'rule of thirds' significantly enhanced the aesthetic quality of my images. The process of capturing ephemeral moments and rendering them into permanent visual records is deeply satisfying to me. It has sharpened my observational skills, compelling me to notice details I previously overlooked. Photography has become a vital medium for my creative expression and a way to document my life's journey.\n\nWord Count: 130 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 9\n\n**Reasoning:** [LR9] Uses 'proficiency', 'bewildering', 'nuances', 'aesthetic', 'ephemeral', 'rendering', 'compelling'. Extremely precise and sophisticated.\n\n>Band 8: Wide range of vocabulary.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Wide range of structures used accurately. Appositives, gerund subjects, and participle phrases are well-formed.\n\n>Band 7: Good control.\n\nNot Band 9: Lacks full native-like flexibility.\n\n**Micro flaws identified:**\n- None."
    }
]

with open(OUTPUT_FILE, 'a', encoding='utf-8') as f:
    for sample in samples:
        f.write(json.dumps(sample) + '\n')
