import json

OUTPUT_FILE = "ielts-data/phase3/v76_review_output/synthetic_batches/batch_p2_09.jsonl"

samples = [
    # 421. V5/G4 - Job (Describe)
    {
        "sample_id": "syn_p2_v5_g4_0421",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a job you think is interesting.",
        "transcript_cleaned": "I think being a pilot is very interesting job. They fly plane to many different countries. It is exciting because they see world from sky. Pilot wear nice uniform. They meet many people every day. I think they earn good salary. But it is difficult job. They must study hard. Also they work long hours. Sometimes they sleep in hotels. It is dangerous if plane have problem. I want to be pilot when I grow up. My parents say it is good career. I like travel very much.",
        "word_count": 101,
        "response_type": "long_turn",
        "micro_flaws": ["article: 'is very interesting job' should be 'is a very interesting job'", "article: 'fly plane' should be 'fly planes'", "article: 'see world' should be 'see the world'", "article: 'from sky' should be 'from the sky'", "agreement: 'Pilot wear' should be 'Pilots wear'", "article: 'nice uniform' should be 'nice uniforms'", "article: 'earn good salary' should be 'earn a good salary'", "article: 'is difficult job' should be 'is a difficult job'", "agreement: 'plane have' should be 'the plane has'", "article: 'have problem' should be 'has a problem'", "article: 'be pilot' should be 'be a pilot'", "article: 'is good career' should be 'is a good career'", "verb: 'like travel' should be 'like traveling'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR5] Vocabulary: 'pilot', 'interesting', 'fly plane', 'countries', 'exciting', 'sky', 'uniform', 'earn', 'salary', 'difficult', 'study hard', 'dangerous', 'problem', 'grow up', 'career', 'travel'. Functional vocabulary relevant to the topic. >Band 4: Uses some specific words ('career', 'salary'). Not Band 6: Repetitive and basic.",
        "grammar_reason": "[GRA4] Only simple sentences. Systematic errors in articles ('a interesting job', 'fly plane') and subject-verb agreement ('Pilot wear', 'plane have'). >Band 3: Basic structures recognizable. Not Band 5: Errors are pervasive.",
        "vocabulary": 5,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a job you think is interesting.\n\nTranscript: I think being a pilot is very interesting job. They fly plane to many different countries. It is exciting because they see world from sky. Pilot wear nice uniform. They meet many people every day. I think they earn good salary. But it is difficult job. They must study hard. Also they work long hours. Sometimes they sleep in hotels. It is dangerous if plane have problem. I want to be pilot when I grow up. My parents say it is good career. I like travel very much.\n\nWord Count: 101 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses topic-specific words: 'salary', 'career', 'uniform'. Vocabulary is adequate for the task.\n\n>Band 4: Clear meaning.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Simple sentences only. Frequent errors in articles and agreement ('Pilot wear', 'plane have').\n\n>Band 3: Simple structures.\n\nNot Band 5: Errors are systematic.\n\n**Micro flaws identified:**\n- 'is very interesting job' should be 'is a very interesting job'\n- 'fly plane' should be 'fly planes'\n- 'see world' should be 'see the world'\n- 'from sky' should be 'from the sky'\n- 'Pilot wear' should be 'Pilots wear'\n- 'nice uniform' should be 'nice uniforms'\n- 'earn good salary' should be 'earn a good salary'\n- 'is difficult job' should be 'is a difficult job'\n- 'plane have' should be 'the plane has'\n- 'have problem' should be 'has a problem'\n- 'be pilot' should be 'be a pilot'\n- 'is good career' should be 'is a good career'\n- 'like travel' should be 'like traveling'"
    },
    # 422. V5/G4 - Place (Museum)
    {
        "sample_id": "syn_p2_v5_g4_0422",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a museum you visited.",
        "transcript_cleaned": "I visit History Museum in London last summer. It is very huge building. It has many old things inside. I see dinosaur bones there. They was very big. I learn about history of world. There are many tourists in museum. I take many photos with my camera. The ticket price is cheap. I like museum because it is educational. I spend three hours there. My favorite part is Egyptian room. It has mummies. I want to go back there again. It is famous place.",
        "word_count": 100,
        "response_type": "long_turn",
        "micro_flaws": ["tense: 'I visit' should be 'I visited'", "article: 'History Museum' should be 'the History Museum'", "article: 'huge building' should be 'a huge building'", "tense: 'I see' should be 'I saw'", "agreement: 'They was' should be 'They were'", "tense: 'I learn' should be 'I learned'", "article: 'history of world' should be 'the history of the world'", "article: 'in museum' should be 'in the museum'", "tense: 'I take' should be 'I took'", "article: 'like museum' should be 'like the museum'", "tense: 'I spend' should be 'I spent'", "article: 'Egyptian room' should be 'the Egyptian room'", "article: 'famous place' should be 'a famous place'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR5] Vocabulary: 'History Museum', 'huge', 'building', 'dinosaur bones', 'tourists', 'camera', 'ticket price', 'cheap', 'educational', 'Egyptian room', 'mummies', 'famous'. Functional vocabulary relevant to the topic. >Band 4: Uses specific words ('mummies', 'dinosaur'). Not Band 6: Simple descriptions.",
        "grammar_reason": "[GRA4] Only simple sentences. Systematic errors in past tense ('I visit', 'I see', 'I learn') and articles. Agreement error ('They was'). >Band 3: Basic meaning conveyed. Not Band 5: Errors are very frequent.",
        "vocabulary": 5,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a museum you visited.\n\nTranscript: I visit History Museum in London last summer. It is very huge building. It has many old things inside. I see dinosaur bones there. They was very big. I learn about history of world. There are many tourists in museum. I take many photos with my camera. The ticket price is cheap. I like museum because it is educational. I spend three hours there. My favorite part is Egyptian room. It has mummies. I want to go back there again. It is famous place.\n\nWord Count: 100 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses topic words: 'dinosaur', 'educational', 'mummies'. Meaning is clear and relevant.\n\n>Band 4: Adequate vocabulary.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Simple sentences. Frequent errors in past tense and articles ('I visit', 'They was').\n\n>Band 3: Simple structures.\n\nNot Band 5: Systematic errors.\n\n**Micro flaws identified:**\n- 'I visit' should be 'I visited'\n- 'History Museum' should be 'the History Museum'\n- 'huge building' should be 'a huge building'\n- 'I see' should be 'I saw'\n- 'They was' should be 'They were'\n- 'I learn' should be 'I learned'\n- 'history of world' should be 'the history of the world'\n- 'in museum' should be 'in the museum'\n- 'I take' should be 'I took'\n- 'like museum' should be 'like the museum'\n- 'I spend' should be 'I spent'\n- 'Egyptian room' should be 'the Egyptian room'\n- 'famous place' should be 'a famous place'"
    },
    # 423. V5/G4 - Event (Festival)
    {
        "sample_id": "syn_p2_v5_g4_0423",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a festival in your country.",
        "transcript_cleaned": "In my country, we celebrate Moon Festival. It happen in autumn. It is important festival for family. We eat mooncakes, which is very sweet. Children carry lantern in street. They look very beautiful. We watch lion dance performance. It is very loud and exciting. People give gift to each other. I like this festival because I meet my cousins. We play games together. The moon is very round and bright. It signify reunion. Everyone is happy on this day. I wait for it every year.",
        "word_count": 101,
        "response_type": "long_turn",
        "micro_flaws": ["article: 'celebrate Moon Festival' should be 'celebrate the Moon Festival'", "agreement: 'It happen' should be 'It happens'", "article: 'important festival' should be 'an important festival'", "agreement: 'which is' should be 'which are' (mooncakes)", "plural: 'carry lantern' should be 'carry lanterns'", "article: 'in street' should be 'in the street'", "article: 'lion dance performance' should be 'a lion dance performance'", "plural: 'give gift' should be 'give gifts'", "agreement: 'It signify' should be 'It signifies'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR5] Vocabulary: 'celebrate', 'Moon Festival', 'autumn', 'mooncakes', 'sweet', 'lantern', 'beautiful', 'lion dance', 'performance', 'loud', 'exciting', 'cousins', 'round', 'bright', 'signify', 'reunion'. Functional vocabulary relevant to the topic. >Band 4: Uses specific words ('mooncakes', 'lantern', 'reunion'). Not Band 6: Simple vocabulary.",
        "grammar_reason": "[GRA4] Only simple sentences. Systematic errors in agreement ('It happen', 'It signify') and articles. >Band 3: Basic structures. Not Band 5: Errors are pervasive.",
        "vocabulary": 5,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a festival in your country.\n\nTranscript: In my country, we celebrate Moon Festival. It happen in autumn. It is important festival for family. We eat mooncakes, which is very sweet. Children carry lantern in street. They look very beautiful. We watch lion dance performance. It is very loud and exciting. People give gift to each other. I like this festival because I meet my cousins. We play games together. The moon is very round and bright. It signify reunion. Everyone is happy on this day. I wait for it every year.\n\nWord Count: 101 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses topic words: 'mooncakes', 'lantern', 'reunion'. Meaning is clear.\n\n>Band 4: Adequate vocabulary.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Simple sentences only. Frequent errors in agreement ('It happen', 'It signify') and articles.\n\n>Band 3: Simple structures.\n\nNot Band 5: Systematic errors.\n\n**Micro flaws identified:**\n- 'celebrate Moon Festival' should be 'celebrate the Moon Festival'\n- 'It happen' should be 'It happens'\n- 'important festival' should be 'an important festival'\n- 'which is' should be 'which are'\n- 'carry lantern' should be 'carry lanterns'\n- 'in street' should be 'in the street'\n- 'lion dance performance' should be 'a lion dance performance'\n- 'give gift' should be 'give gifts'\n- 'It signify' should be 'It signifies'"
    },
    # 424. V5/G4 - Book (Recommend)
    {
        "sample_id": "syn_p2_v5_g4_0424",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a book you would recommend.",
        "transcript_cleaned": "I recommend book called 'The Alchemist'. It is famous novel by Paulo Coelho. It tell story of shepherd boy named Santiago. He want to find treasure. He travel to Egypt. On his journey, he meet many people. They teach him about life. The book is very inspiring. It teach us to follow dream. I read it in English. It was easy to understand. The language is simple but beautiful. I think everyone should read this book. It is not long book. You can finish it quickly.",
        "word_count": 103,
        "response_type": "long_turn",
        "micro_flaws": ["article: 'recommend book' should be 'recommend a book'", "article: 'famous novel' should be 'a famous novel'", "agreement: 'It tell' should be 'It tells'", "article: 'story of' should be 'the story of a'", "agreement: 'He want' should be 'He wants'", "agreement: 'He travel' should be 'He travels'", "agreement: 'he meet' should be 'he meets'", "agreement: 'It teach' should be 'It teaches'", "article: 'follow dream' should be 'follow our dreams'", "article: 'long book' should be 'a long book'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR5] Vocabulary: 'recommend', 'novel', 'shepherd', 'treasure', 'journey', 'inspiring', 'follow dream', 'language', 'simple', 'beautiful'. Functional vocabulary relevant to the topic. >Band 4: Uses specific words ('shepherd', 'treasure'). Not Band 6: Simple vocabulary.",
        "grammar_reason": "[GRA4] Only simple sentences. Systematic errors in agreement ('It tell', 'He want', 'he meet', 'It teach') and articles. >Band 3: Basic structures. Not Band 5: Errors are pervasive.",
        "vocabulary": 5,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a book you would recommend.\n\nTranscript: I recommend book called 'The Alchemist'. It is famous novel by Paulo Coelho. It tell story of shepherd boy named Santiago. He want to find treasure. He travel to Egypt. On his journey, he meet many people. They teach him about life. The book is very inspiring. It teach us to follow dream. I read it in English. It was easy to understand. The language is simple but beautiful. I think everyone should read this book. It is not long book. You can finish it quickly.\n\nWord Count: 103 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses topic words: 'novel', 'shepherd', 'treasure'. Meaning is clear.\n\n>Band 4: Adequate vocabulary.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Simple sentences only. Frequent errors in agreement ('It tell', 'He want') and articles.\n\n>Band 3: Simple structures.\n\nNot Band 5: Systematic errors.\n\n**Micro flaws identified:**\n- 'recommend book' should be 'recommend a book'\n- 'famous novel' should be 'a famous novel'\n- 'It tell' should be 'It tells'\n- 'story of' should be 'the story of a'\n- 'He want' should be 'He wants'\n- 'He travel' should be 'He travels'\n- 'he meet' should be 'he meets'\n- 'It teach' should be 'It teaches'\n- 'follow dream' should be 'follow our dreams'\n- 'long book' should be 'a long book'"
    },
    # 425. V5/G4 - Activity (Sport)
    {
        "sample_id": "syn_p2_v5_g4_0425",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a sport you like to watch.",
        "transcript_cleaned": "I like watch tennis on TV. It is exciting sport. My favorite player is Rafael Nadal. He is very strong and fast. I watch Wimbledon tournament every year. The match can be very long. Sometimes it take five hours. I like see how they hit ball. It requires skill and stamina. Tennis players runs very much. I played tennis when I was child. But I am not good at it. I prefer watch professional player. It is interesting to see who win trophy. The crowd cheer loudly.",
        "word_count": 104,
        "response_type": "long_turn",
        "micro_flaws": ["verb: 'like watch' should be 'like watching'", "article: 'exciting sport' should be 'an exciting sport'", "article: 'Wimbledon tournament' should be 'the Wimbledon tournament'", "plural: 'The match' should be 'The matches'", "agreement: 'it take' should be 'it takes'", "verb: 'like see' should be 'like seeing'", "article: 'hit ball' should be 'hit the ball'", "agreement: 'players runs' should be 'players run'", "article: 'was child' should be 'was a child'", "verb: 'prefer watch' should be 'prefer watching'", "plural: 'professional player' should be 'professional players'", "agreement: 'who win' should be 'who wins'", "article: 'win trophy' should be 'wins the trophy'", "agreement: 'crowd cheer' should be 'crowd cheers'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR5] Vocabulary: 'tennis', 'exciting', 'player', 'tournament', 'match', 'skill', 'stamina', 'professional', 'trophy', 'crowd', 'cheer', 'loudly'. Functional vocabulary relevant to the topic. >Band 4: Uses specific words ('stamina', 'tournament'). Not Band 6: Simple vocabulary.",
        "grammar_reason": "[GRA4] Only simple sentences. Systematic errors in verb forms ('like watch', 'prefer watch'), agreement ('it take', 'players runs'), and articles. >Band 3: Basic structures. Not Band 5: Errors are pervasive.",
        "vocabulary": 5,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a sport you like to watch.\n\nTranscript: I like watch tennis on TV. It is exciting sport. My favorite player is Rafael Nadal. He is very strong and fast. I watch Wimbledon tournament every year. The match can be very long. Sometimes it take five hours. I like see how they hit ball. It requires skill and stamina. Tennis players runs very much. I played tennis when I was child. But I am not good at it. I prefer watch professional player. It is interesting to see who win trophy. The crowd cheer loudly.\n\nWord Count: 104 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses topic words: 'tournament', 'stamina', 'trophy'. Meaning is clear.\n\n>Band 4: Adequate vocabulary.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Simple sentences only. Frequent errors in verb forms ('like watch') and agreement ('it take').\n\n>Band 3: Simple structures.\n\nNot Band 5: Systematic errors.\n\n**Micro flaws identified:**\n- 'like watch' should be 'like watching'\n- 'exciting sport' should be 'an exciting sport'\n- 'Wimbledon tournament' should be 'the Wimbledon tournament'\n- 'The match' should be 'The matches'\n- 'it take' should be 'it takes'\n- 'like see' should be 'like seeing'\n- 'hit ball' should be 'hit the ball'\n- 'players runs' should be 'players run'\n- 'was child' should be 'was a child'\n- 'prefer watch' should be 'prefer watching'\n- 'professional player' should be 'professional players'\n- 'who win' should be 'who wins'\n- 'win trophy' should be 'wins the trophy'\n- 'crowd cheer' should be 'crowd cheers'"
    },
    # 426. V5/G4 - Object (Important)
    {
        "sample_id": "syn_p2_v5_g4_0426",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe an important object you own.",
        "transcript_cleaned": "My laptop is very important thing for me. I use it every day for work and study. It is black laptop from Dell. I buy it two years ago. It help me connect with internet. I can send email and find information. I also store many photo and document on it. It is portable so I carry it in my bag. Without my laptop, I cannot do my job. It is indispensable tool. I take care of it very well. If it break, I will be sad. It cost a lot of money.",
        "word_count": 106,
        "response_type": "long_turn",
        "micro_flaws": ["article: 'is very important thing' should be 'is a very important thing'", "article: 'is black laptop' should be 'is a black laptop'", "tense: 'I buy' should be 'I bought'", "agreement: 'It help' should be 'It helps'", "article: 'connect with internet' should be 'connect with the internet'", "plural: 'send email' should be 'send emails'", "plural: 'many photo and document' should be 'many photos and documents'", "article: 'is portable' should be 'is portable'", "article: 'is indispensable tool' should be 'is an indispensable tool'", "agreement: 'it break' should be 'it breaks'", "agreement: 'It cost' should be 'It costs'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR5] Vocabulary: 'laptop', 'important', 'study', 'connect', 'internet', 'email', 'information', 'store', 'document', 'portable', 'bag', 'indispensable', 'tool', 'cost'. Functional vocabulary relevant to the topic. >Band 4: Uses specific words ('indispensable', 'portable'). Not Band 6: Simple vocabulary.",
        "grammar_reason": "[GRA4] Only simple sentences. Systematic errors in articles ('a important thing'), tense ('I buy'), and agreement ('It help', 'it break'). >Band 3: Basic structures. Not Band 5: Errors are pervasive.",
        "vocabulary": 5,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe an important object you own.\n\nTranscript: My laptop is very important thing for me. I use it every day for work and study. It is black laptop from Dell. I buy it two years ago. It help me connect with internet. I can send email and find information. I also store many photo and document on it. It is portable so I carry it in my bag. Without my laptop, I cannot do my job. It is indispensable tool. I take care of it very well. If it break, I will be sad. It cost a lot of money.\n\nWord Count: 106 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses topic words: 'portable', 'indispensable', 'document'. Meaning is clear.\n\n>Band 4: Adequate vocabulary.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Simple sentences only. Frequent errors in articles and agreement ('It help', 'it break').\n\n>Band 3: Simple structures.\n\nNot Band 5: Systematic errors.\n\n**Micro flaws identified:**\n- 'is very important thing' should be 'is a very important thing'\n- 'is black laptop' should be 'is a black laptop'\n- 'I buy' should be 'I bought'\n- 'It help' should be 'It helps'\n- 'connect with internet' should be 'connect with the internet'\n- 'send email' should be 'send emails'\n- 'many photo and document' should be 'many photos and documents'\n- 'is indispensable tool' should be 'is an indispensable tool'\n- 'it break' should be 'it breaks'\n- 'It cost' should be 'It costs'"
    },
    # 427. V5/G4 - Place (Restaurant)
    {
        "sample_id": "syn_p2_v5_g4_0427",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a restaurant you like.",
        "transcript_cleaned": "I like Italian restaurant in city center. It called 'Bella Napoli'. I go there with my friends. The food is very tasty. They serve pizza and pasta. My favorite dish is spaghetti. The waiter is very polite. They wear black uniform. The restaurant have nice decoration. It is comfortable place. We usually go there on Friday night. It is crowded, so we wait for table. The price is reasonable. I like atmosphere there. It is romantic. I recommend this place to everyone.",
        "word_count": 100,
        "response_type": "long_turn",
        "micro_flaws": ["article: 'like Italian restaurant' should be 'like an Italian restaurant'", "article: 'in city center' should be 'in the city center'", "verb: 'It called' should be 'It is called'", "agreement: 'restaurant have' should be 'restaurant has'", "article: 'comfortable place' should be 'a comfortable place'", "article: 'wait for table' should be 'wait for a table'", "article: 'like atmosphere' should be 'like the atmosphere'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR5] Vocabulary: 'restaurant', 'city center', 'tasty', 'serve', 'dish', 'spaghetti', 'waiter', 'polite', 'uniform', 'decoration', 'comfortable', 'crowded', 'reasonable', 'atmosphere', 'romantic', 'recommend'. Functional vocabulary relevant to the topic. >Band 4: Uses specific words ('atmosphere', 'reasonable'). Not Band 6: Simple vocabulary.",
        "grammar_reason": "[GRA4] Only simple sentences. Systematic errors in articles ('Italian restaurant', 'comfortable place') and verbs ('It called', 'restaurant have'). >Band 3: Basic structures. Not Band 5: Errors are pervasive.",
        "vocabulary": 5,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a restaurant you like.\n\nTranscript: I like Italian restaurant in city center. It called 'Bella Napoli'. I go there with my friends. The food is very tasty. They serve pizza and pasta. My favorite dish is spaghetti. The waiter is very polite. They wear black uniform. The restaurant have nice decoration. It is comfortable place. We usually go there on Friday night. It is crowded, so we wait for table. The price is reasonable. I like atmosphere there. It is romantic. I recommend this place to everyone.\n\nWord Count: 100 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses topic words: 'atmosphere', 'reasonable', 'recommend'. Meaning is clear.\n\n>Band 4: Adequate vocabulary.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Simple sentences only. Frequent errors in articles and verbs ('It called', 'restaurant have').\n\n>Band 3: Simple structures.\n\nNot Band 5: Systematic errors.\n\n**Micro flaws identified:**\n- 'like Italian restaurant' should be 'like an Italian restaurant'\n- 'in city center' should be 'in the city center'\n- 'It called' should be 'It is called'\n- 'restaurant have' should be 'restaurant has'\n- 'comfortable place' should be 'a comfortable place'\n- 'wait for table' should be 'wait for a table'\n- 'like atmosphere' should be 'like the atmosphere'"
    },
    # 428. V5/G4 - Person (Child)
    {
        "sample_id": "syn_p2_v5_g4_0428",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a child you know.",
        "transcript_cleaned": "I know little boy named Tom. He is my neighbor's son. He is five years old. He is very cute and energetic. He like play with cars. He has many toy in his room. He always smile when he see me. Sometimes I look after him. He is intelligent boy. He can count to 100. He also speak little English. His mother dress him nicely. He is naughty sometimes, but I like him. He want to be policeman. He run very fast. He is joy for his parents.",
        "word_count": 103,
        "response_type": "long_turn",
        "micro_flaws": ["article: 'know little boy' should be 'know a little boy'", "agreement: 'He like' should be 'He likes'", "verb: 'like play' should be 'like playing'", "plural: 'many toy' should be 'many toys'", "agreement: 'always smile' should be 'always smiles'", "agreement: 'he see' should be 'he sees'", "article: 'intelligent boy' should be 'an intelligent boy'", "agreement: 'speak little' should be 'speaks a little'", "agreement: 'mother dress' should be 'mother dresses'", "agreement: 'He want' should be 'He wants'", "article: 'be policeman' should be 'be a policeman'", "agreement: 'He run' should be 'He runs'", "article: 'is joy' should be 'is a joy'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR5] Vocabulary: 'neighbor', 'energetic', 'toy', 'smile', 'look after', 'intelligent', 'count', 'naughty', 'policeman', 'joy'. Functional vocabulary relevant to the topic. >Band 4: Uses specific words ('naughty', 'energetic'). Not Band 6: Simple vocabulary.",
        "grammar_reason": "[GRA4] Only simple sentences. Systematic errors in agreement ('He like', 'He smile', 'He run') and articles. >Band 3: Basic structures. Not Band 5: Errors are pervasive.",
        "vocabulary": 5,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a child you know.\n\nTranscript: I know little boy named Tom. He is my neighbor's son. He is five years old. He is very cute and energetic. He like play with cars. He has many toy in his room. He always smile when he see me. Sometimes I look after him. He is intelligent boy. He can count to 100. He also speak little English. His mother dress him nicely. He is naughty sometimes, but I like him. He want to be policeman. He run very fast. He is joy for his parents.\n\nWord Count: 103 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses topic words: 'energetic', 'naughty', 'intelligent'. Meaning is clear.\n\n>Band 4: Adequate vocabulary.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Simple sentences only. Frequent errors in agreement ('He like', 'He smile') and articles.\n\n>Band 3: Simple structures.\n\nNot Band 5: Systematic errors.\n\n**Micro flaws identified:**\n- 'know little boy' should be 'know a little boy'\n- 'He like' should be 'He likes'\n- 'like play' should be 'like playing'\n- 'many toy' should be 'many toys'\n- 'always smile' should be 'always smiles'\n- 'he see' should be 'he sees'\n- 'intelligent boy' should be 'an intelligent boy'\n- 'speak little' should be 'speaks a little'\n- 'mother dress' should be 'mother dresses'\n- 'He want' should be 'He wants'\n- 'be policeman' should be 'be a policeman'\n- 'He run' should be 'He runs'\n- 'is joy' should be 'is a joy'"
    },
    # 429. V5/G4 - Activity (Creative)
    {
        "sample_id": "syn_p2_v5_g4_0429",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a creative activity you enjoy.",
        "transcript_cleaned": "I enjoy painting pictures in my free time. It is creative hobby. I use watercolor to paint. I paint nature, like trees and flowers. It make me feel relax. I started painting two years ago. I am not professional artist, but I like it. I buy paint and brush in art shop. Sometimes I paint with my friend. We show our picture to each other. Painting help me express my feeling. I hang my painting on wall in my room. It is colorful and nice. I want to improve my skill. It is good way to spend time.",
        "word_count": 103,
        "response_type": "long_turn",
        "micro_flaws": ["article: 'is creative hobby' should be 'is a creative hobby'", "agreement: 'It make' should be 'It makes'", "adjective: 'feel relax' should be 'feel relaxed'", "article: 'professional artist' should be 'a professional artist'", "plural: 'paint and brush' should be 'paints and brushes'", "article: 'in art shop' should be 'in an art shop'", "plural: 'our picture' should be 'our pictures'", "agreement: 'Painting help' should be 'Painting helps'", "plural: 'feeling' should be 'feelings'", "plural: 'my painting' should be 'my paintings'", "article: 'on wall' should be 'on the wall'", "article: 'good way' should be 'a good way'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR5] Vocabulary: 'painting', 'creative', 'hobby', 'watercolor', 'nature', 'artist', 'brush', 'art shop', 'express', 'feeling', 'hang', 'colorful', 'improve', 'skill'. Functional vocabulary relevant to the topic. >Band 4: Uses specific words ('watercolor', 'express'). Not Band 6: Simple vocabulary.",
        "grammar_reason": "[GRA4] Only simple sentences. Systematic errors in agreement ('It make', 'Painting help'), articles, and plurals. >Band 3: Basic structures. Not Band 5: Errors are pervasive.",
        "vocabulary": 5,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a creative activity you enjoy.\n\nTranscript: I enjoy painting pictures in my free time. It is creative hobby. I use watercolor to paint. I paint nature, like trees and flowers. It make me feel relax. I started painting two years ago. I am not professional artist, but I like it. I buy paint and brush in art shop. Sometimes I paint with my friend. We show our picture to each other. Painting help me express my feeling. I hang my painting on wall in my room. It is colorful and nice. I want to improve my skill. It is good way to spend time.\n\nWord Count: 103 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses topic words: 'watercolor', 'express', 'skill'. Meaning is clear.\n\n>Band 4: Adequate vocabulary.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Simple sentences only. Frequent errors in agreement ('It make'), articles, and plurals.\n\n>Band 3: Simple structures.\n\nNot Band 5: Systematic errors.\n\n**Micro flaws identified:**\n- 'is creative hobby' should be 'is a creative hobby'\n- 'It make' should be 'It makes'\n- 'feel relax' should be 'feel relaxed'\n- 'professional artist' should be 'a professional artist'\n- 'paint and brush' should be 'paints and brushes'\n- 'in art shop' should be 'in an art shop'\n- 'our picture' should be 'our pictures'\n- 'Painting help' should be 'Painting helps'\n- 'express my feeling' should be 'express my feelings'\n- 'my painting' should be 'my paintings'\n- 'on wall' should be 'on the wall'\n- 'good way' should be 'a good way'"
    },
    # 430. V5/G4 - Gift (Received)
    {
        "sample_id": "syn_p2_v5_g4_0430",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a gift you liked.",
        "transcript_cleaned": "I receive bicycle for my 10th birthday. My father buy it for me. It was red bicycle. I was very excited. It have two wheels and a bell. I learn to ride it in the park. My father teach me how to balance. At first, I fall down many time. But I not give up. Finally, I can ride it well. I ride to school every day. It is faster than walking. I keep it clean. It is special gift because my father give it. I still have this bicycle. It remind me of my childhood.",
        "word_count": 102,
        "response_type": "long_turn",
        "micro_flaws": ["tense: 'I receive' should be 'I received'", "article: 'receive bicycle' should be 'received a bicycle'", "tense: 'My father buy' should be 'My father bought'", "article: 'red bicycle' should be 'a red bicycle'", "agreement: 'It have' should be 'It had'", "tense: 'I learn' should be 'I learned'", "tense: 'My father teach' should be 'My father taught'", "tense: 'I fall' should be 'I fell'", "plural: 'many time' should be 'many times'", "grammar: 'I not give up' should be 'I did not give up'", "agreement: 'It remind' should be 'It reminds'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR5] Vocabulary: 'bicycle', 'birthday', 'wheels', 'bell', 'ride', 'balance', 'fall down', 'give up', 'faster', 'clean', 'special', 'remind', 'childhood'. Functional vocabulary relevant to the topic. >Band 4: Uses specific words ('balance', 'remind'). Not Band 6: Simple vocabulary.",
        "grammar_reason": "[GRA4] Only simple sentences. Systematic errors in tense ('I receive', 'buy', 'teach', 'fall'), agreement, and articles. >Band 3: Basic structures. Not Band 5: Errors are pervasive.",
        "vocabulary": 5,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a gift you liked.\n\nTranscript: I receive bicycle for my 10th birthday. My father buy it for me. It was red bicycle. I was very excited. It have two wheels and a bell. I learn to ride it in the park. My father teach me how to balance. At first, I fall down many time. But I not give up. Finally, I can ride it well. I ride to school every day. It is faster than walking. I keep it clean. It is special gift because my father give it. I still have this bicycle. It remind me of my childhood.\n\nWord Count: 102 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses topic words: 'balance', 'remind', 'childhood'. Meaning is clear.\n\n>Band 4: Adequate vocabulary.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Simple sentences only. Frequent errors in past tense ('receive', 'buy') and articles.\n\n>Band 3: Simple structures.\n\nNot Band 5: Systematic errors.\n\n**Micro flaws identified:**\n- 'I receive' should be 'I received'\n- 'receive bicycle' should be 'received a bicycle'\n- 'My father buy' should be 'My father bought'\n- 'red bicycle' should be 'a red bicycle'\n- 'It have' should be 'It had'\n- 'I learn' should be 'I learned'\n- 'My father teach' should be 'My father taught'\n- 'I fall' should be 'I fell'\n- 'many time' should be 'many times'\n- 'I not give up' should be 'I did not give up'\n- 'It remind' should be 'It reminds'"
    }
]

with open(OUTPUT_FILE, 'a', encoding='utf-8') as f:
    for sample in samples:
        f.write(json.dumps(sample) + '\n')
