import json

OUTPUT_FILE = "ielts-data/phase3/v76_review_output/synthetic_batches/batch_p2_14.jsonl"

samples = [
    # 671. V9/G6 - Book (Read)
    {
        "sample_id": "syn_p2_v9_g6_0671",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a book you enjoyed.",
        "transcript_cleaned": "I recently devoured a novel called 'The Night Circus', which is an enchanting tale. The narrative is intricate, weaving together multiple timelines. I was mesmerized by the ethereal descriptions of the magical circus. The prose is lyrical and evocative, painting vivid images in my mind. However, the plot were sometimes confusing. I struggling to keep track of the characters. The ending feeling a bit rushed to me. Despite these flaws, the book resonate with me deeply. It is a masterpiece of imagination. I would recommending it to anyone who loves fantasy.",
        "word_count": 91,
        "response_type": "long_turn",
        "micro_flaws": ["agreement: 'plot were' should be 'was'", "grammar: 'I struggling' should be 'I struggled'", "grammar: 'ending feeling' should be 'felt'", "agreement: 'book resonate' should be 'resonates'", "grammar: 'would recommending' should be 'would recommend'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR9] Vocabulary: 'devoured', 'enchanting tale', 'intricate', 'weaving', 'timelines', 'mesmerized', 'ethereal descriptions', 'prose', 'lyrical', 'evocative', 'vivid images', 'masterpiece', 'imagination'. Extremely precise and sophisticated. >Band 8: Wide range of vocabulary. **Idiom present:** No.",
        "grammar_reason": "[GRA6] Uses complex structures but has frequent errors. Agreement errors ('plot were', 'book resonate'). Verb form errors ('struggling', 'feeling', 'recommending'). >Band 5: Attempts complex sentences. Not Band 7: Errors are noticeable.",
        "vocabulary": 9,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a book you enjoyed.\n\nTranscript: I recently devoured a novel called 'The Night Circus', which is an enchanting tale. The narrative is intricate, weaving together multiple timelines. I was mesmerized by the ethereal descriptions of the magical circus. The prose is lyrical and evocative, painting vivid images in my mind. However, the plot were sometimes confusing. I struggling to keep track of the characters. The ending feeling a bit rushed to me. Despite these flaws, the book resonate with me deeply. It is a masterpiece of imagination. I would recommending it to anyone who loves fantasy.\n\nWord Count: 91 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 9\n\n**Reasoning:** [LR9] Uses 'devoured', 'ethereal', 'evocative'. Extremely precise and sophisticated.\n\n>Band 8: Wide range of vocabulary.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Frequent errors in verb forms ('struggling', 'feeling') and agreement ('plot were'). Complex structures used but flawed.\n\n>Band 5: Complex sentences attempted.\n\nNot Band 7: Systematic errors.\n\n**Micro flaws identified:**\n- 'plot were' should be 'plot was'\n- 'I struggling' should be 'I struggled'\n- 'ending feeling' should be 'ending felt'\n- 'book resonate' should be 'book resonates'\n- 'would recommending' should be 'would recommend'"
    },
    # 672. V9/G6 - Place (City)
    {
        "sample_id": "syn_p2_v9_g6_0672",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a city you like.",
        "transcript_cleaned": "I am enamored with Florence, a city that epitomizes the Renaissance spirit. It is a treasure trove of art and architecture, boasting masterpieces by Michelangelo. I was awestruck by the grandeur of the Duomo, which dominate the skyline. Walking through the cobbled streets felt like a journey back in time. The Uffizi Gallery housing an unparalleled collection of paintings. I spending hours admiring the details. The culinary scene is also exquisite, with authentic Tuscan cuisine. However, the city are very crowded with tourists. I wishing it was quieter. It is a destination that captivate the senses.",
        "word_count": 96,
        "response_type": "long_turn",
        "micro_flaws": ["agreement: 'Duomo, which dominate' should be 'dominates'", "grammar: 'Gallery housing' should be 'houses'", "grammar: 'I spending' should be 'I spent'", "agreement: 'city are' should be 'is'", "grammar: 'I wishing' should be 'I wish'", "agreement: 'destination that captivate' should be 'captivates'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR9] Vocabulary: 'enamored', 'epitomizes', 'Renaissance spirit', 'treasure trove', 'boasting masterpieces', 'awestruck', 'grandeur', 'skyline', 'cobbled streets', 'unparalleled collection', 'culinary scene', 'exquisite', 'authentic', 'Tuscan cuisine', 'captivate', 'senses'. Extremely precise and sophisticated. >Band 8: Wide range of vocabulary. **Idiom present:** Yes ('treasure trove').",
        "grammar_reason": "[GRA6] Uses complex structures but has frequent errors. Verb form errors ('housing', 'spending', 'wishing'). Agreement errors ('dominate', 'city are', 'captivate'). >Band 5: Attempts complex sentences. Not Band 7: Errors are noticeable.",
        "vocabulary": 9,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a city you like.\n\nTranscript: I am enamored with Florence, a city that epitomizes the Renaissance spirit. It is a treasure trove of art and architecture, boasting masterpieces by Michelangelo. I was awestruck by the grandeur of the Duomo, which dominate the skyline. Walking through the cobbled streets felt like a journey back in time. The Uffizi Gallery housing an unparalleled collection of paintings. I spending hours admiring the details. The culinary scene is also exquisite, with authentic Tuscan cuisine. However, the city are very crowded with tourists. I wishing it was quieter. It is a destination that captivate the senses.\n\nWord Count: 96 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 9\n\n**Reasoning:** [LR9] Uses 'enamored', 'epitomizes', 'awestruck', 'exquisite'. Extremely precise and sophisticated.\n\n>Band 8: Wide range of vocabulary.\n\n**Idiom present:** Yes ('treasure trove')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Frequent errors in verb forms and agreement ('dominate', 'housing'). Complex structures used but flawed.\n\n>Band 5: Complex sentences attempted.\n\nNot Band 7: Systematic errors.\n\n**Micro flaws identified:**\n- 'Duomo, which dominate' should be 'dominates'\n- 'Gallery housing' should be 'houses'\n- 'I spending' should be 'I spent'\n- 'city are' should be 'city is'\n- 'I wishing' should be 'I wish'\n- 'destination that captivate' should be 'captivates'"
    },
    # 673. V9/G6 - Event (Concert)
    {
        "sample_id": "syn_p2_v9_g6_0673",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a music event you attended.",
        "transcript_cleaned": "I attended a recital by a virtuoso pianist, which was a transcendent experience. The musician displayed impeccable technique and emotional depth. I was spellbound by the intricate melodies he weaving. The acoustics of the concert hall was phenomenal, amplifying every nuance. The crescendo of the final piece evoking a powerful response from the audience. Everyone were moved to tears. It was a testament to the power of music to unite people. I have never witnessing such a flawless performance. It solidified my passion for classical music. I anticipating the next concert eagerly.",
        "word_count": 93,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'he weaving' should be 'he wove' or 'he was weaving'", "agreement: 'acoustics... was' should be 'were'", "grammar: 'piece evoking' should be 'evoked'", "agreement: 'Everyone were' should be 'was'", "grammar: 'never witnessing' should be 'never witnessed'", "grammar: 'I anticipating' should be 'I am anticipating'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR9] Vocabulary: 'recital', 'virtuoso pianist', 'transcendent', 'impeccable technique', 'emotional depth', 'spellbound', 'intricate melodies', 'acoustics', 'phenomenal', 'amplifying', 'nuance', 'crescendo', 'testament', 'unite', 'flawless', 'solidified', 'passion', 'anticipating'. Extremely precise and sophisticated. >Band 8: Wide range of vocabulary. **Idiom present:** No.",
        "grammar_reason": "[GRA6] Uses complex structures but has frequent errors. Verb form errors ('weaving', 'evoking', 'witnessing', 'anticipating'). Agreement errors ('acoustics was', 'Everyone were'). >Band 5: Attempts complex sentences. Not Band 7: Errors are noticeable.",
        "vocabulary": 9,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a music event you attended.\n\nTranscript: I attended a recital by a virtuoso pianist, which was a transcendent experience. The musician displayed impeccable technique and emotional depth. I was spellbound by the intricate melodies he weaving. The acoustics of the concert hall was phenomenal, amplifying every nuance. The crescendo of the final piece evoking a powerful response from the audience. Everyone were moved to tears. It was a testament to the power of music to unite people. I have never witnessing such a flawless performance. It solidified my passion for classical music. I anticipating the next concert eagerly.\n\nWord Count: 93 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 9\n\n**Reasoning:** [LR9] Uses 'virtuoso', 'transcendent', 'nuance', 'solidified'. Extremely precise and sophisticated.\n\n>Band 8: Wide range of vocabulary.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Frequent errors in verb forms ('weaving', 'evoking', 'witnessing'). Complex structures used but flawed.\n\n>Band 5: Complex sentences attempted.\n\nNot Band 7: Systematic errors.\n\n**Micro flaws identified:**\n- 'he weaving' should be 'he wove'\n- 'acoustics... was' should be 'acoustics... were'\n- 'piece evoking' should be 'piece evoked'\n- 'Everyone were' should be 'Everyone was'\n- 'never witnessing' should be 'never witnessed'\n- 'I anticipating' should be 'I am anticipating'"
    },
    # 674. V9/G6 - Person (Friend)
    {
        "sample_id": "syn_p2_v9_g6_0674",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a friend you admire.",
        "transcript_cleaned": "I deeply admire my friend, Elena, who is a polyglot and a scholar. She possesses an insatiable curiosity about the world. Her ability to articulate complex ideas is remarkable. We often engaging in intellectual discourse on various topics. She has a magnetic personality that draw people to her. I am always astounded by her breadth of knowledge. However, she sometimes forgetting to eat or sleep when studying. Her dedication to her academic pursuits are inspiring. She exemplify the value of lifelong learning. I am fortunate to having her as a friend.",
        "word_count": 92,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'We often engaging' should be 'engage'", "agreement: 'personality that draw' should be 'draws'", "grammar: 'she sometimes forgetting' should be 'forgets'", "agreement: 'dedication... are' should be 'is'", "agreement: 'She exemplify' should be 'exemplifies'", "grammar: 'to having' should be 'to have'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR9] Vocabulary: 'deeply admire', 'polyglot', 'scholar', 'possesses', 'insatiable curiosity', 'articulate', 'intellectual discourse', 'magnetic personality', 'astounded', 'breadth of knowledge', 'dedication', 'academic pursuits', 'exemplify', 'lifelong learning', 'fortunate'. Extremely precise and sophisticated. >Band 8: Wide range of vocabulary. **Idiom present:** No.",
        "grammar_reason": "[GRA6] Uses complex structures but has frequent errors. Verb form errors ('engaging', 'forgetting', 'having'). Agreement errors ('draw', 'dedication are', 'exemplify'). >Band 5: Attempts complex sentences. Not Band 7: Errors are noticeable.",
        "vocabulary": 9,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a friend you admire.\n\nTranscript: I deeply admire my friend, Elena, who is a polyglot and a scholar. She possesses an insatiable curiosity about the world. Her ability to articulate complex ideas is remarkable. We often engaging in intellectual discourse on various topics. She has a magnetic personality that draw people to her. I am always astounded by her breadth of knowledge. However, she sometimes forgetting to eat or sleep when studying. Her dedication to her academic pursuits are inspiring. She exemplify the value of lifelong learning. I am fortunate to having her as a friend.\n\nWord Count: 92 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 9\n\n**Reasoning:** [LR9] Uses 'polyglot', 'insatiable', 'discourse', 'magnetic'. Extremely precise and sophisticated.\n\n>Band 8: Wide range of vocabulary.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Frequent errors in verb forms ('engaging', 'forgetting') and agreement ('draw', 'are'). Complex structures used but flawed.\n\n>Band 5: Complex sentences attempted.\n\nNot Band 7: Systematic errors.\n\n**Micro flaws identified:**\n- 'We often engaging' should be 'We often engage'\n- 'personality that draw' should be 'personality that draws'\n- 'she sometimes forgetting' should be 'she sometimes forgets'\n- 'dedication... are' should be 'dedication... is'\n- 'She exemplify' should be 'She exemplifies'\n- 'to having' should be 'to have'"
    },
    # 675. V9/G6 - Activity (Skill)
    {
        "sample_id": "syn_p2_v9_g6_0675",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a skill you learned.",
        "transcript_cleaned": "I learned the art of negotiation, which is an invaluable skill in business. It involves navigating conflicting interests to reach a mutually beneficial agreement. I attended a seminar to mastering the techniques of persuasion. The instructor emphasizing the importance of active listening. I practiced role-playing scenarios, which was challenging. Initially, I finding it difficult to remain assertive. However, my confidence growing with each session. Now, I can defusing tense situations effectively. This competency have empowered me in my career. It is a strategic asset that I utilize frequently.",
        "word_count": 90,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'to mastering' should be 'to master'", "grammar: 'instructor emphasizing' should be 'emphasized'", "agreement: 'scenarios, which was' should be 'were'", "grammar: 'I finding' should be 'I found'", "grammar: 'confidence growing' should be 'grew'", "grammar: 'can defusing' should be 'can defuse'", "agreement: 'competency have' should be 'has'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR9] Vocabulary: 'art of negotiation', 'invaluable skill', 'navigating', 'conflicting interests', 'mutually beneficial agreement', 'seminar', 'techniques of persuasion', 'active listening', 'assertive', 'defusing', 'tense situations', 'competency', 'empowered', 'strategic asset', 'utilize'. Extremely precise and sophisticated. >Band 8: Wide range of vocabulary. **Idiom present:** No.",
        "grammar_reason": "[GRA6] Uses complex structures but has frequent errors. Verb form errors ('mastering', 'emphasizing', 'finding', 'growing', 'defusing'). Agreement errors ('was', 'have'). >Band 5: Attempts complex sentences. Not Band 7: Errors are frequent.",
        "vocabulary": 9,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a skill you learned.\n\nTranscript: I learned the art of negotiation, which is an invaluable skill in business. It involves navigating conflicting interests to reach a mutually beneficial agreement. I attended a seminar to mastering the techniques of persuasion. The instructor emphasizing the importance of active listening. I practiced role-playing scenarios, which was challenging. Initially, I finding it difficult to remain assertive. However, my confidence growing with each session. Now, I can defusing tense situations effectively. This competency have empowered me in my career. It is a strategic asset that I utilize frequently.\n\nWord Count: 90 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 9\n\n**Reasoning:** [LR9] Uses 'negotiation', 'beneficial', 'persuasion', 'assertive'. Extremely precise and sophisticated.\n\n>Band 8: Wide range of vocabulary.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Frequent errors in verb forms ('mastering', 'emphasizing', 'finding') and agreement. Complex structures used but flawed.\n\n>Band 5: Complex sentences attempted.\n\nNot Band 7: Systematic errors.\n\n**Micro flaws identified:**\n- 'to mastering' should be 'to master'\n- 'instructor emphasizing' should be 'emphasized'\n- 'scenarios, which was' should be 'were'\n- 'I finding' should be 'I found'\n- 'confidence growing' should be 'grew'\n- 'can defusing' should be 'can defuse'\n- 'competency have' should be 'has'"
    },
    # 676. V5/G5 - Job (Work)
    {
        "sample_id": "syn_p2_v5_g5_0676",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a job you have done.",
        "transcript_cleaned": "I worked as a waiter in a restaurant last summer. It was my first job. I had to take orders and serve food to customers. The restaurant was very busy, especially on weekends. I learned how to be polite and patient. Sometimes, customers were angry if the food was late. I tried to stay calm and apologize. I liked my colleagues because they were friendly. We helped each other when it was crowded. Although the work was tiring, I earned some money. It was a good experience for me.",
        "word_count": 92,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR5] Vocabulary: 'waiter', 'restaurant', 'orders', 'serve food', 'customers', 'busy', 'polite', 'patient', 'angry', 'late', 'calm', 'apologize', 'colleagues', 'friendly', 'crowded', 'tiring', 'earned', 'experience'. Functional vocabulary relevant to the topic. >Band 4: Uses specific words ('colleagues', 'apologize'). Not Band 6: Simple vocabulary.",
        "grammar_reason": "[GRA5] Basic sentence forms are accurate. Uses 'because', 'if', and 'although' clauses correctly. Past tense used correctly ('worked', 'had', 'learned'). >Band 4: Accuracy is good. Not Band 6: Limited complexity.",
        "vocabulary": 5,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a job you have done.\n\nTranscript: I worked as a waiter in a restaurant last summer. It was my first job. I had to take orders and serve food to customers. The restaurant was very busy, especially on weekends. I learned how to be polite and patient. Sometimes, customers were angry if the food was late. I tried to stay calm and apologize. I liked my colleagues because they were friendly. We helped each other when it was crowded. Although the work was tiring, I earned some money. It was a good experience for me.\n\nWord Count: 92 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses topic words: 'waiter', 'colleagues', 'apologize'. Meaning is clear.\n\n>Band 4: Adequate vocabulary.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Uses basic sentences accurately. Connectors like 'because' and 'although' are used correctly.\n\n>Band 4: Frequent error-free sentences.\n\nNot Band 6: Limited range of structures.\n\n**Micro flaws identified:**\n- None."
    },
    # 677. V5/G5 - Place (Room)
    {
        "sample_id": "syn_p2_v5_g5_0677",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe your favorite room.",
        "transcript_cleaned": "My favorite room is my bedroom because it is very comfortable. I have a big bed with soft pillows. The walls are painted blue, which is my favorite color. I have a desk where I study and use my computer. There is a bookshelf with many books. I like to read there in the evening. My room is quiet, so I can relax after school. I keep my room clean and tidy. It is my private space where I can be alone. I feel safe and happy in my room.",
        "word_count": 93,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR5] Vocabulary: 'bedroom', 'comfortable', 'pillows', 'painted', 'desk', 'study', 'bookshelf', 'read', 'evening', 'quiet', 'relax', 'clean', 'tidy', 'private space', 'alone', 'safe'. Functional vocabulary relevant to the topic. >Band 4: Uses specific words ('bookshelf', 'tidy'). Not Band 6: Simple vocabulary.",
        "grammar_reason": "[GRA5] Basic sentence forms are accurate. Uses 'because', 'where', and 'so' clauses correctly. Present tense used correctly ('is', 'have', 'do'). >Band 4: Accuracy is good. Not Band 6: Limited complexity.",
        "vocabulary": 5,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe your favorite room.\n\nTranscript: My favorite room is my bedroom because it is very comfortable. I have a big bed with soft pillows. The walls are painted blue, which is my favorite color. I have a desk where I study and use my computer. There is a bookshelf with many books. I like to read there in the evening. My room is quiet, so I can relax after school. I keep my room clean and tidy. It is my private space where I can be alone. I feel safe and happy in my room.\n\nWord Count: 93 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses topic words: 'comfortable', 'tidy', 'private space'. Meaning is clear.\n\n>Band 4: Adequate vocabulary.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Uses basic sentences accurately. 'Because' clause and relative clauses used correctly.\n\n>Band 4: Frequent error-free sentences.\n\nNot Band 6: Limited range of structures.\n\n**Micro flaws identified:**\n- None."
    },
    # 678. V5/G5 - Event (Party)
    {
        "sample_id": "syn_p2_v5_g5_0678",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a party you threw.",
        "transcript_cleaned": "I threw a surprise party for my sister last month. It was her 18th birthday. I invited her friends and our family. We decorated the living room with balloons and lights. My mother baked a chocolate cake. I bought some snacks and drinks. We hid in the room and turned off the lights. When she came in, we shouted 'Surprise!'. She was very shocked and happy. We played music and danced all night. It was a successful party because everyone had fun. My sister thanked me for the wonderful surprise.",
        "word_count": 93,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR5] Vocabulary: 'surprise party', 'invited', 'decorated', 'living room', 'balloons', 'lights', 'baked', 'chocolate cake', 'snacks', 'drinks', 'hid', 'shouted', 'shocked', 'successful', 'fun', 'thanked'. Functional vocabulary relevant to the topic. >Band 4: Uses specific words ('decorated', 'successful'). Not Band 6: Simple vocabulary.",
        "grammar_reason": "[GRA5] Basic sentence forms are accurate. Uses 'when' and 'because' clauses correctly. Past tense used correctly ('threw', 'invited', 'was'). >Band 4: Accuracy is good. Not Band 6: Limited complexity.",
        "vocabulary": 5,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a party you threw.\n\nTranscript: I threw a surprise party for my sister last month. It was her 18th birthday. I invited her friends and our family. We decorated the living room with balloons and lights. My mother baked a chocolate cake. I bought some snacks and drinks. We hid in the room and turned off the lights. When she came in, we shouted 'Surprise!'. She was very shocked and happy. We played music and danced all night. It was a successful party because everyone had fun. My sister thanked me for the wonderful surprise.\n\nWord Count: 93 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses topic words: 'decorated', 'successful', 'surprise'. Meaning is clear.\n\n>Band 4: Adequate vocabulary.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Uses basic sentences accurately. Past tense and time clauses used correctly.\n\n>Band 4: Frequent error-free sentences.\n\nNot Band 6: Limited range of structures.\n\n**Micro flaws identified:**\n- None."
    },
    # 679. V5/G5 - Object (Gift)
    {
        "sample_id": "syn_p2_v5_g5_0679",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a gift you bought.",
        "transcript_cleaned": "I bought a watch for my father's birthday. I went to a shopping mall to find it. There were many shops, so it was hard to choose. I wanted to buy something useful. The watch was silver and looked very nice. It was a bit expensive, but I had saved money. The shop assistant wrapped it in a nice box. When I gave it to my father, he was very pleased. He wears it every day now. I felt happy because he liked the gift. It was a good choice.",
        "word_count": 94,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR5] Vocabulary: 'bought', 'watch', 'shopping mall', 'choose', 'useful', 'silver', 'nice', 'expensive', 'saved money', 'shop assistant', 'wrapped', 'pleased', 'wears', 'choice'. Functional vocabulary relevant to the topic. >Band 4: Uses specific words ('assistant', 'wrapped'). Not Band 6: Simple vocabulary.",
        "grammar_reason": "[GRA5] Basic sentence forms are accurate. Uses 'so', 'but', and 'when' clauses correctly. Past tense used correctly ('went', 'was', 'gave'). >Band 4: Accuracy is good. Not Band 6: Limited complexity.",
        "vocabulary": 5,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a gift you bought.\n\nTranscript: I bought a watch for my father's birthday. I went to a shopping mall to find it. There were many shops, so it was hard to choose. I wanted to buy something useful. The watch was silver and looked very nice. It was a bit expensive, but I had saved money. The shop assistant wrapped it in a nice box. When I gave it to my father, he was very pleased. He wears it every day now. I felt happy because he liked the gift. It was a good choice.\n\nWord Count: 94 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses topic words: 'useful', 'wrapped', 'pleased'. Meaning is clear.\n\n>Band 4: Adequate vocabulary.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Uses basic sentences accurately. Connectors and past tense used correctly.\n\n>Band 4: Frequent error-free sentences.\n\nNot Band 6: Limited range of structures.\n\n**Micro flaws identified:**\n- None."
    },
    # 680. V5/G5 - Activity (Hobby)
    {
        "sample_id": "syn_p2_v5_g5_0680",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a hobby you enjoy.",
        "transcript_cleaned": "I enjoy cycling in my free time. I have a blue bicycle that I ride on weekends. I usually cycle in the park or along the river. It is good exercise for my legs. I like it because I can enjoy the fresh air and scenery. Sometimes I go with my friends, which is more fun. We race each other and laugh. Cycling helps me relax after a busy week. I always wear a helmet for safety. I want to participate in a cycling race next year. It is my passion.",
        "word_count": 93,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR5] Vocabulary: 'cycling', 'bicycle', 'ride', 'weekends', 'park', 'river', 'exercise', 'legs', 'fresh air', 'scenery', 'race', 'relax', 'helmet', 'safety', 'participate', 'passion'. Functional vocabulary relevant to the topic. >Band 4: Uses specific words ('scenery', 'participate'). Not Band 6: Simple vocabulary.",
        "grammar_reason": "[GRA5] Basic sentence forms are accurate. Uses relative clause ('that I ride') and 'because' clause correctly. Present tense used correctly ('enjoy', 'have', 'like'). >Band 4: Accuracy is good. Not Band 6: Limited complexity.",
        "vocabulary": 5,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a hobby you enjoy.\n\nTranscript: I enjoy cycling in my free time. I have a blue bicycle that I ride on weekends. I usually cycle in the park or along the river. It is good exercise for my legs. I like it because I can enjoy the fresh air and scenery. Sometimes I go with my friends, which is more fun. We race each other and laugh. Cycling helps me relax after a busy week. I always wear a helmet for safety. I want to participate in a cycling race next year. It is my passion.\n\nWord Count: 93 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses topic words: 'scenery', 'helmet', 'passion'. Meaning is clear.\n\n>Band 4: Adequate vocabulary.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Uses basic sentences accurately. Relative clauses and present tense used correctly.\n\n>Band 4: Frequent error-free sentences.\n\nNot Band 6: Limited range of structures.\n\n**Micro flaws identified:**\n- None."
    }
]

with open(OUTPUT_FILE, 'a', encoding='utf-8') as f:
    for sample in samples:
        f.write(json.dumps(sample) + '\n')
