import json

OUTPUT_FILE = "ielts-data/phase3/v76_review_output/synthetic_batches/batch_p2_07.jsonl"

samples = [
    # 331. V8/G9 - Interesting Person
    {
        "sample_id": "syn_p2_v8_g9_0331",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe an interesting person you have met.",
        "transcript_cleaned": "I recently encountered a renowned anthropologist at a lecture who left a lasting impression on me. He was a figure of immense intellect and charisma, commanding the room with his presence. What struck me most was his unconventional perspective on human evolution; he argues that our social structures are primarily driven by cooperation rather than competition. His insights were profound, challenging the established Darwinian narrative I had always accepted. We engaged in a spirited debate about the implications of his theory for modern society. He articulated his arguments with such eloquence and conviction that I found myself reassessing my own beliefs. Despite his academic stature, he was remarkably humble and open to discourse. That interaction was intellectually stimulating and has left an indelible mark on my worldview. I aspire to cultivate such open-mindedness.",
        "word_count": 139,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR8] Vocabulary: 'encountered', 'renowned', 'intellect', 'charisma', 'unconventional', 'perspective', 'structures', 'profound', 'established', 'narrative', 'spirited', 'implications', 'articulated', 'eloquence', 'conviction', 'reassessing', 'stature', 'discourse', 'indelible', 'cultivate'.",
        "grammar_reason": "[GRA9] Full range. 'What struck me most was...' (Cleft). 'He argues that...' (Noun clause). 'Driven by cooperation rather than competition' (Participle phrase). 'So... that...' (Result). Error-free.",
        "vocabulary": 8,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe an interesting person you have met.\n\nTranscript: I recently encountered a renowned anthropologist at a lecture who left a lasting impression on me. He was a figure of immense intellect and charisma, commanding the room with his presence. What struck me most was his unconventional perspective on human evolution; he argues that our social structures are primarily driven by cooperation rather than competition. His insights were profound, challenging the established Darwinian narrative I had always accepted. We engaged in a spirited debate about the implications of his theory for modern society. He articulated his arguments with such eloquence and conviction that I found myself reassessing my own beliefs. Despite his academic stature, he was remarkably humble and open to discourse. That interaction was intellectually stimulating and has left an indelible mark on my worldview. I aspire to cultivate such open-mindedness.\n\nWord Count: 139 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses 'renowned', 'unconventional', 'articulated', 'eloquence', 'indelible', 'cultivate'. Very sophisticated.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Excellent usage.\n\n**Idiom present:** Yes ('indelible mark')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Full range of structures used naturally. Cleft sentences, noun clauses, and participle phrases are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    },
    # 332. V8/G9 - Historical Event
    {
        "sample_id": "syn_p2_v8_g9_0332",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a historical event that interests you.",
        "transcript_cleaned": "I am captivated by the fall of the Berlin Wall, a monumental event in 20th-century history that reshaped Europe. The sheer symbolism of the wall's destruction is mind-boggling, representing the collapse of the Iron Curtain and the end of the Cold War. It marked the pinnacle of people power and the yearning for freedom against oppressive regimes. I often ponder the immense relief and joy the citizens of East Berlin must have felt as they crossed the border for the first time. The footage of people chipping away at the concrete is iconic, evoking a sense of collective euphoria. It was a unifying moment for Europe, transcending ideological divides. The geopolitical consequences were far-reaching, reshaping the modern world. I believe this event serves as a timeless reminder that oppression cannot withstand the human spirit.",
        "word_count": 139,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR8] Vocabulary: 'captivated', 'monumental', 'symbolism', 'mind-boggling', 'collapse', 'pinnacle', 'yearning', 'relief', 'footage', 'iconic', 'evoking', 'collective', 'euphoria', 'unifying', 'transcending', 'ideological', 'geopolitical', 'reshaping', 'oppression', 'withstand'.",
        "grammar_reason": "[GRA9] Full range. 'Representing the collapse...' (Participle phrase). 'Must have felt' (Modal deduction). 'As they crossed...' (Time clause). 'Chipping away at the concrete' (Participle phrase). Error-free.",
        "vocabulary": 8,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a historical event that interests you.\n\nTranscript: I am captivated by the fall of the Berlin Wall, a monumental event in 20th-century history that reshaped Europe. The sheer symbolism of the wall's destruction is mind-boggling, representing the collapse of the Iron Curtain and the end of the Cold War. It marked the pinnacle of people power and the yearning for freedom against oppressive regimes. I often ponder the immense relief and joy the citizens of East Berlin must have felt as they crossed the border for the first time. The footage of people chipping away at the concrete is iconic, evoking a sense of collective euphoria. It was a unifying moment for Europe, transcending ideological divides. The geopolitical consequences were far-reaching, reshaping the modern world. I believe this event serves as a timeless reminder that oppression cannot withstand the human spirit.\n\nWord Count: 139 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses 'monumental', 'mind-boggling', 'pinnacle', 'euphoria', 'transcending', 'geopolitical'. Very sophisticated.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Excellent usage.\n\n**Idiom present:** Yes ('mind-boggling')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Full range of structures used naturally. Participle phrases and modals of deduction are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    },
    # 333. V8/G9 - Gift (Given)
    {
        "sample_id": "syn_p2_v8_g9_0333",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a gift you gave to someone that was well received.",
        "transcript_cleaned": "I presented a rare, first-edition copy of 'Pride and Prejudice' to my mother for her 60th birthday. Knowing her penchant for classic literature, I wanted something that would truly resonate with her refined literary taste. I scoured rare bookshops across the city until I finally found a copy in pristine condition. It was an exquisite find that I knew she would treasure. When she unwrapped it, she was visibly moved; she gasped in disbelief and tears filled her eyes. She immediately began reading the preface, praising the texture of the pages and the smell of the old paper. It was gratifying to see her so appreciative of the gesture. This gift was not merely a book but a token of my understanding of her passions. It symbolized our shared love for reading.",
        "word_count": 138,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR8] Vocabulary: 'presented', 'first-edition', 'penchant', 'classic', 'resonate', 'literary', 'scoured', 'pristine', 'exquisite', 'unwrapped', 'visibly moved', 'gasped', 'disbelief', 'preface', 'texture', 'gratifying', 'appreciative', 'token'.",
        "grammar_reason": "[GRA9] Full range. 'Knowing her penchant...' (Participle phrase). 'That would resonate...' (Relative clause). 'Until I found...' (Time clause). 'Not merely... but...' (Correlative). Error-free.",
        "vocabulary": 8,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a gift you gave to someone that was well received.\n\nTranscript: I presented a rare, first-edition copy of 'Pride and Prejudice' to my mother for her 60th birthday. Knowing her penchant for classic literature, I wanted something that would truly resonate with her refined literary taste. I scoured rare bookshops across the city until I finally found a copy in pristine condition. It was an exquisite find that I knew she would treasure. When she unwrapped it, she was visibly moved; she gasped in disbelief and tears filled her eyes. She immediately began reading the preface, praising the texture of the pages and the smell of the old paper. It was gratifying to see her so appreciative of the gesture. This gift was not merely a book but a token of my understanding of her passions. It symbolized our shared love for reading.\n\nWord Count: 138 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses 'penchant', 'resonate', 'scoured', 'pristine', 'exquisite', 'gratifying'. Very precise.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Excellent usage.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Full range of structures used naturally. Participle phrases and correlative structures are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    },
    # 334. V8/G9 - Place (Study)
    {
        "sample_id": "syn_p2_v8_g9_0334",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a place where you like to study.",
        "transcript_cleaned": "My preferred sanctuary for study is a quiet botanical greenhouse located near the university campus. It is a horticultural gem, meticulously designed to maximize natural light and maintain a tranquil, humid climate. The ambiance is incredibly conducive to deep concentration, with the subtle scent of blooming flowers permeating the air. Surrounded by lush vegetation and towering palms, I feel a sense of intellectual immersion. I usually go there to review complex theories or write essays without interruption. The gentle sound of the fountain ensures that stress is non-existent. Whenever I hit a mental block, gazing at the exotic plants provides a refreshing respite for my eyes. Having access to such a serene environment significantly enhances my cognitive retention and focus. It is my personal haven of productivity.",
        "word_count": 133,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR8] Vocabulary: 'sanctuary', 'horticultural', 'gem', 'maximize', 'tranquil', 'ambiance', 'conducive', 'permeating', 'lush', 'immersion', 'complex', 'non-existent', 'mental block', 'exotic', 'respite', 'serene', 'cognitive', 'retention', 'haven'.",
        "grammar_reason": "[GRA9] Full range. 'Designed to maximize...' (Participle phrase). 'Surrounded by lush vegetation...' (Participle phrase). 'Whenever I hit...' (Time clause). 'Gazing at... provides...' (Gerund subject). Error-free.",
        "vocabulary": 8,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a place where you like to study.\n\nTranscript: My preferred sanctuary for study is a quiet botanical greenhouse located near the university campus. It is a horticultural gem, meticulously designed to maximize natural light and maintain a tranquil, humid climate. The ambiance is incredibly conducive to deep concentration, with the subtle scent of blooming flowers permeating the air. Surrounded by lush vegetation and towering palms, I feel a sense of intellectual immersion. I usually go there to review complex theories or write essays without interruption. The gentle sound of the fountain ensures that stress is non-existent. Whenever I hit a mental block, gazing at the exotic plants provides a refreshing respite for my eyes. Having access to such a serene environment significantly enhances my cognitive retention and focus. It is my personal haven of productivity.\n\nWord Count: 133 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses 'sanctuary', 'horticultural', 'conducive', 'permeating', 'immersion', 'respite', 'cognitive'. Very sophisticated.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Excellent usage.\n\n**Idiom present:** Yes ('hit a mental block')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Full range of structures used naturally. Participle phrases and gerund subjects are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    },
    # 335. V8/G9 - Party (Family)
    {
        "sample_id": "syn_p2_v8_g9_0335",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a family party you enjoyed.",
        "transcript_cleaned": "I fondly recall a massive reunion dinner we held last summer to celebrate my parents' silver wedding anniversary. It was a momentous occasion, bringing together relatives from across the country who hadn't seen each other in years. The venue was a cozy banquet hall, beautifully adorned with silver balloons and family portraits from the past. The culinary spread was exquisite, featuring a fusion of our family's favorite traditional dishes. What made it truly special was the palpable sense of kinship and nostalgia in the room. We shared anecdotes, toasted to their longevity, and watched a slide show of their life together. My father's speech, recounting their enduring love story, moved everyone to tears. It was a poignant reminder of the strength of familial bonds. That evening remains etched in my memory.",
        "word_count": 139,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR8] Vocabulary: 'fondly', 'reunion', 'silver anniversary', 'momentous', 'venue', 'banquet', 'adorned', 'culinary', 'exquisite', 'fusion', 'palpable', 'kinship', 'nostalgia', 'anecdotes', 'longevity', 'enduring', 'poignant', 'etched'.",
        "grammar_reason": "[GRA9] Full range. 'Bringing together...' (Participle phrase). 'Adorned with...' (Participle phrase). 'What made it truly special was...' (Cleft sentence). 'Recounting their enduring love story' (Participle phrase). Error-free.",
        "vocabulary": 8,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a family party you enjoyed.\n\nTranscript: I fondly recall a massive reunion dinner we held last summer to celebrate my parents' silver wedding anniversary. It was a momentous occasion, bringing together relatives from across the country who hadn't seen each other in years. The venue was a cozy banquet hall, beautifully adorned with silver balloons and family portraits from the past. The culinary spread was exquisite, featuring a fusion of our family's favorite traditional dishes. What made it truly special was the palpable sense of kinship and nostalgia in the room. We shared anecdotes, toasted to their longevity, and watched a slide show of their life together. My father's speech, recounting their enduring love story, moved everyone to tears. It was a poignant reminder of the strength of familial bonds. That evening remains etched in my memory.\n\nWord Count: 139 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses 'momentous', 'exquisite', 'palpable', 'kinship', 'anecdotes', 'poignant', 'etched'. Very sophisticated.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Excellent usage.\n\n**Idiom present:** Yes ('etched in my memory')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Full range of structures used naturally. Participle phrases and cleft sentences are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    },
    # 336. V8/G9 - News (Good)
    {
        "sample_id": "syn_p2_v8_g9_0336",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a piece of good news you received.",
        "transcript_cleaned": "I was absolutely ecstatic to receive the official notification that my scholarship application for a master's program had been approved. Having toiled over the essays for weeks, facing intense self-doubt and anxiety, this validation was incredibly gratifying. The email arrived early in the morning, and I initially questioned its authenticity, thinking I might be dreaming. Upon confirmation, a wave of relief and euphoria washed over me. This scholarship represents a significant milestone in my academic career, eliminating the crushing financial burden of tuition fees. It vindicated my hard work and persistence throughout my undergraduate studies. I immediately shared the news with my parents, whose support had been unwavering. This accomplishment has bolstered my confidence and renewed my determination to excel in my future studies.",
        "word_count": 133,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR8] Vocabulary: 'ecstatic', 'notification', 'toiled', 'self-doubt', 'validation', 'gratifying', 'authenticity', 'confirmation', 'euphoria', 'milestone', 'eliminating', 'burden', 'vindicated', 'persistence', 'unwavering', 'bolstered', 'determination'.",
        "grammar_reason": "[GRA9] Full range. 'Having toiled...' (Perfect Participle). 'Thinking I might be dreaming' (Implied). 'Whose support had been unwavering' (Relative clause). 'Had been approved' (Passive Perfect). Error-free.",
        "vocabulary": 8,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a piece of good news you received.\n\nTranscript: I was absolutely ecstatic to receive the official notification that my scholarship application for a master's program had been approved. Having toiled over the essays for weeks, facing intense self-doubt and anxiety, this validation was incredibly gratifying. The email arrived early in the morning, and I initially questioned its authenticity, thinking I might be dreaming. Upon confirmation, a wave of relief and euphoria washed over me. This scholarship represents a significant milestone in my academic career, eliminating the crushing financial burden of tuition fees. It vindicated my hard work and persistence throughout my undergraduate studies. I immediately shared the news with my parents, whose support had been unwavering. This accomplishment has bolstered my confidence and renewed my determination to excel in my future studies.\n\nWord Count: 133 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses 'ecstatic', 'toiled', 'validation', 'authenticity', 'euphoria', 'vindicated', 'bolstered'. Very sophisticated.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Excellent usage.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Full range of structures used naturally. Perfect participles, relative clauses, and passive structures are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    },
    # 337. V8/G9 - Game (Sport)
    {
        "sample_id": "syn_p2_v8_g9_0337",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a sport you enjoy playing.",
        "transcript_cleaned": "I am an avid enthusiast of badminton, a sport that demands both physical agility and lightning-fast reflexes. I took it up during university as a hobby and have been hooked ever since. The dynamism of the game, with its rapid rallies and precise smashes, provides an unparalleled adrenaline rush that I find addictive. It is not merely a test of stamina but a tactical battle, requiring one to outsmart the opponent with deceptive shots. I relish the sensation of hitting a perfect drop shot or executing a powerful smash to win a point. Beyond the physical benefits, badminton has taught me resilience and mental focus. Dealing with defeat is as important as celebrating victory. It is a fantastic outlet for stress relief.",
        "word_count": 133,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR8] Vocabulary: 'avid', 'enthusiast', 'agility', 'reflexes', 'hooked', 'dynamism', 'rallies', 'smashes', 'unparalleled', 'adrenaline', 'stamina', 'tactical', 'outsmart', 'relish', 'executing', 'resilience', 'outlet'.",
        "grammar_reason": "[GRA9] Full range. 'A sport that demands...' (Relative clause). 'With its rapid rallies...' (Prepositional phrase). 'Requiring one to outsmart...' (Participle phrase). 'Not merely... but...' (Correlative). Error-free.",
        "vocabulary": 8,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a sport you enjoy playing.\n\nTranscript: I am an avid enthusiast of badminton, a sport that demands both physical agility and lightning-fast reflexes. I took it up during university as a hobby and have been hooked ever since. The dynamism of the game, with its rapid rallies and precise smashes, provides an unparalleled adrenaline rush that I find addictive. It is not merely a test of stamina but a tactical battle, requiring one to outsmart the opponent with deceptive shots. I relish the sensation of hitting a perfect drop shot or executing a powerful smash to win a point. Beyond the physical benefits, badminton has taught me resilience and mental focus. Dealing with defeat is as important as celebrating victory. It is a fantastic outlet for stress relief.\n\nWord Count: 133 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses 'avid', 'agility', 'dynamism', 'unparalleled', 'tactical', 'relish', 'resilience'. Very sophisticated.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Excellent usage.\n\n**Idiom present:** Yes ('hooked', 'lightning-fast')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Full range of structures used naturally. Participle phrases, relative clauses, and correlative structures are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    },
    # 338. V8/G9 - Decision (Quick)
    {
        "sample_id": "syn_p2_v8_g9_0338",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a decision you made quickly.",
        "transcript_cleaned": "I once made a split-second decision to help a neighbor extinguish a small fire that had started in their kitchen. I was walking home when I spotted dark smoke billowing from their open window. Without hesitation or thought for my own safety, I rushed over and grabbed a garden hose lying nearby. It was an impulsive act, driven by adrenaline rather than logic. I had never fought a fire before and was completely unprepared. However, realizing the immediate danger, I knew I couldn't wait for the fire brigade to arrive. That decision, though risky, turned out to be crucial in saving their home. I managed to contain the flames until help arrived. It taught me that in emergencies, instinct transcends rationale, and quick action can avert disaster.",
        "word_count": 136,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR8] Vocabulary: 'split-second', 'extinguish', 'billowing', 'hesitation', 'impulsive', 'adrenaline', 'logic', 'unprepared', 'crucial', 'contain', 'instinct', 'transcends', 'rationale', 'avert', 'disaster'.",
        "grammar_reason": "[GRA9] Full range. 'Billowing from...' (Participle phrase). 'Driven by adrenaline...' (Participle phrase). 'Realizing the danger, I knew...' (Participle phrase). 'Though risky' (Elliptical clause). Error-free.",
        "vocabulary": 8,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a decision you made quickly.\n\nTranscript: I once made a split-second decision to help a neighbor extinguish a small fire that had started in their kitchen. I was walking home when I spotted dark smoke billowing from their open window. Without hesitation or thought for my own safety, I rushed over and grabbed a garden hose lying nearby. It was an impulsive act, driven by adrenaline rather than logic. I had never fought a fire before and was completely unprepared. However, realizing the immediate danger, I knew I couldn't wait for the fire brigade to arrive. That decision, though risky, turned out to be crucial in saving their home. I managed to contain the flames until help arrived. It taught me that in emergencies, instinct transcends rationale, and quick action can avert disaster.\n\nWord Count: 136 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses 'split-second', 'billowing', 'impulsive', 'crucial', 'transcends', 'rationale', 'avert'. Very sophisticated.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Excellent usage.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Full range of structures used naturally. Participle phrases and elliptical clauses are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    },
    # 339. V8/G9 - Friend (Old)
    {
        "sample_id": "syn_p2_v8_g9_0339",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe an old friend you got in contact with again.",
        "transcript_cleaned": "I recently reconnected with my best friend from primary school, Ben, thanks to the serendipity of the internet. We had been inseparable during our childhood but drifted apart when he moved away to another country. Seeing his name pop up on a social media site was a pleasant shock. We arranged a video call, and despite the twenty-year hiatus, the conversation flowed effortlessly. We reminisced about our shared pranks and caught up on our respective life journeys. It was heartening to discover that our bond remained intact despite the distance and time. This reunion rekindled a dormant friendship, proving that true connections can withstand the test of time. We are now planning a trip together next year. It feels as though we were never separated.",
        "word_count": 133,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR8] Vocabulary: 'reconnected', 'serendipity', 'drifted apart', 'pleasant', 'hiatus', 'effortlessly', 'reminisced', 'pranks', 'respective', 'journeys', 'heartening', 'intact', 'rekindled', 'dormant', 'withstand', 'connections'.",
        "grammar_reason": "[GRA9] Full range. 'Thanks to the serendipity...' (Prepositional phrase). 'We had been close...' (Past Perfect). 'Seeing his name... was...' (Gerund subject). 'It feels as though...' (Subjunctive mood). Error-free.",
        "vocabulary": 8,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe an old friend you got in contact with again.\n\nTranscript: I recently reconnected with my best friend from primary school, Ben, thanks to the serendipity of the internet. We had been inseparable during our childhood but drifted apart when he moved away to another country. Seeing his name pop up on a social media site was a pleasant shock. We arranged a video call, and despite the twenty-year hiatus, the conversation flowed effortlessly. We reminisced about our shared pranks and caught up on our respective life journeys. It was heartening to discover that our bond remained intact despite the distance and time. This reunion rekindled a dormant friendship, proving that true connections can withstand the test of time. We are now planning a trip together next year. It feels as though we were never separated.\n\nWord Count: 133 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses 'serendipity', 'hiatus', 'reminisced', 'rekindled', 'dormant'. Very sophisticated.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Excellent usage.\n\n**Idiom present:** Yes ('drifted apart', 'test of time')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Full range of structures used naturally. Past perfect, gerund subjects, and subjunctive mood are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    },
    # 340. V8/G9 - Activity (Indoor)
    {
        "sample_id": "syn_p2_v8_g9_0340",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe an indoor game you played.",
        "transcript_cleaned": "I thoroughly enjoy playing Scrabble, a classic board game of linguistic skill and strategy. I was introduced to it by my mother, a wordsmith in her own right, when I was very young. It is a battle of vocabulary that requires quick thinking and extensive knowledge of the English language. Each tile has a point value, and placing them on the board to maximize points is an intellectual puzzle. I vividly recall a match where I managed to use all my tiles in one go, scoring a 'bingo'. The excitement in the room was palpable. Scrabble teaches patience and spelling. It is not merely a pastime but a mental exercise. I find it incredibly stimulating to challenge my family members and learn new obscure words. It keeps the mind sharp.",
        "word_count": 139,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR8] Vocabulary: 'linguistic', 'strategy', 'wordsmith', 'extensive', 'maximize', 'intellectual', 'vividly', 'palpable', 'pastime', 'exercise', 'stimulating', 'obscure', 'sharp'.",
        "grammar_reason": "[GRA9] Full range. 'A game of linguistic skill' (Appositive). 'Placing them... is...' (Gerund subject). 'Where I managed to use...' (Relative clause). 'Not merely... but...' (Correlative). Error-free.",
        "vocabulary": 8,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe an indoor game you played.\n\nTranscript: I thoroughly enjoy playing Scrabble, a classic board game of linguistic skill and strategy. I was introduced to it by my mother, a wordsmith in her own right, when I was very young. It is a battle of vocabulary that requires quick thinking and extensive knowledge of the English language. Each tile has a point value, and placing them on the board to maximize points is an intellectual puzzle. I vividly recall a match where I managed to use all my tiles in one go, scoring a 'bingo'. The excitement in the room was palpable. Scrabble teaches patience and spelling. It is not merely a pastime but a mental exercise. I find it incredibly stimulating to challenge my family members and learn new obscure words. It keeps the mind sharp.\n\nWord Count: 139 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses 'wordsmith', 'maximize', 'palpable', 'obscure'. Very sophisticated.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Excellent usage.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Full range of structures used naturally. Appositives, gerund subjects, and correlative structures are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    }
]

with open(OUTPUT_FILE, 'a', encoding='utf-8') as f:
    for sample in samples:
        f.write(json.dumps(sample) + '\n')
