import json

OUTPUT_FILE = "ielts-data/phase3/v76_review_output/synthetic_batches/batch_p2_10.jsonl"

samples = [
    # 451. V6/G5 - Book (Childhood)
    {
        "sample_id": "syn_p2_v6_g5_0451",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a book you read as a child.",
        "transcript_cleaned": "I remember reading 'Alice in Wonderland' when I was young. It is a famous fantasy novel. The story is about a girl who fall into a rabbit hole. She meeting many strange creatures there. I liked the Cheshire Cat because he disappearing and leaving only his smile. The book was very imaginative and colorful. I reading it many times. It help me improve my reading skills. Although some parts was scary, it was mostly fun. I think every child should read this book. It teach us to be curious.",
        "word_count": 89,
        "response_type": "long_turn",
        "micro_flaws": ["agreement: 'girl who fall' should be 'falls'", "tense: 'She meeting' should be 'She met'", "tense: 'he disappearing' should be 'he disappeared'", "tense: 'I reading' should be 'I read'", "agreement: 'It help' should be 'It helped'", "agreement: 'parts was' should be 'were'", "agreement: 'It teach' should be 'It teaches'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR6] Vocabulary: 'fantasy novel', 'rabbit hole', 'creatures', 'imaginative', 'colorful', 'improve', 'skills', 'curious', 'scary', 'famous'. Adequate range. >Band 5: Clear meaning. Not Band 7: Lacks depth.",
        "grammar_reason": "[GRA5] Frequent grammatical errors. Tense errors ('reading', 'meeting', 'disappearing') and agreement errors ('fall', 'help', 'was', 'teach'). >Band 4: Basic meaning clear. Not Band 6: Errors are systematic.",
        "vocabulary": 6,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a book you read as a child.\n\nTranscript: I remember reading 'Alice in Wonderland' when I was young. It is a famous fantasy novel. The story is about a girl who fall into a rabbit hole. She meeting many strange creatures there. I liked the Cheshire Cat because he disappearing and leaving only his smile. The book was very imaginative and colorful. I reading it many times. It help me improve my reading skills. Although some parts was scary, it was mostly fun. I think every child should read this book. It teach us to be curious.\n\nWord Count: 89 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses relevant vocabulary: 'fantasy novel', 'imaginative'. Clear descriptions.\n\n>Band 5: Good range.\n\nNot Band 7: Vocabulary is standard.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Frequent errors in verb tenses and agreement. Incorrect use of continuous forms ('meeting', 'reading').\n\n>Band 4: Basic sentences are recognizable.\n\nNot Band 6: Errors are frequent and noticeable.\n\n**Micro flaws identified:**\n- 'girl who fall' should be 'falls'\n- 'She meeting' should be 'She met'\n- 'he disappearing' should be 'he disappeared'\n- 'I reading' should be 'I read'\n- 'It help' should be 'It helped'\n- 'parts was' should be 'parts were'\n- 'It teach' should be 'It teaches'"
    },
    # 452. V6/G5 - Place (Cafe)
    {
        "sample_id": "syn_p2_v6_g5_0452",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a cafe you know well.",
        "transcript_cleaned": "There is a small cafe near my university called 'The Coffee Bean'. I going there almost every day. It has a cozy atmosphere with comfortable chairs. I usually ordering a latte and a muffin. The coffee taste delicious and fresh. Many students comes here to study. It is a popular spot for meeting friends. The staff are friendly and helpful. I like sitting by the window and watching people outside. Sometimes it get very crowded in the afternoon. However, I still enjoying going there because it is cheap.",
        "word_count": 89,
        "response_type": "long_turn",
        "micro_flaws": ["tense: 'I going' should be 'I go'", "tense: 'I usually ordering' should be 'order'", "agreement: 'coffee taste' should be 'tastes'", "agreement: 'students comes' should be 'come'", "agreement: 'it get' should be 'gets'", "tense: 'I still enjoying' should be 'enjoy'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR6] Vocabulary: 'cozy atmosphere', 'comfortable', 'latte', 'muffin', 'delicious', 'fresh', 'popular spot', 'meeting friends', 'staff', 'friendly', 'helpful', 'crowded'. Adequate range. >Band 5: Good topic vocabulary. Not Band 7: Lacks sophistication.",
        "grammar_reason": "[GRA5] Frequent grammatical errors. Continuous tense used incorrectly for habits ('going', 'ordering', 'enjoying'). Subject-verb agreement errors ('taste', 'comes', 'get'). >Band 4: Basic meaning clear. Not Band 6: Errors are systematic.",
        "vocabulary": 6,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a cafe you know well.\n\nTranscript: There is a small cafe near my university called 'The Coffee Bean'. I going there almost every day. It has a cozy atmosphere with comfortable chairs. I usually ordering a latte and a muffin. The coffee taste delicious and fresh. Many students comes here to study. It is a popular spot for meeting friends. The staff are friendly and helpful. I like sitting by the window and watching people outside. Sometimes it get very crowded in the afternoon. However, I still enjoying going there because it is cheap.\n\nWord Count: 89 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses functional vocabulary: 'cozy', 'popular spot', 'crowded'. Clear meaning.\n\n>Band 5: Good range.\n\nNot Band 7: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Frequent errors in verb tenses and agreement. 'I going', 'coffee taste' are incorrect.\n\n>Band 4: Basic sentences are recognizable.\n\nNot Band 6: Errors are frequent and noticeable.\n\n**Micro flaws identified:**\n- 'I going' should be 'I go'\n- 'I usually ordering' should be 'I usually order'\n- 'coffee taste' should be 'coffee tastes'\n- 'students comes' should be 'students come'\n- 'it get' should be 'it gets'\n- 'I still enjoying' should be 'I still enjoy'"
    },
    # 453. V6/G5 - Event (Festival)
    {
        "sample_id": "syn_p2_v6_g5_0453",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a festival you enjoy.",
        "transcript_cleaned": "I really enjoy the Music Festival in my city. It happen every summer in the park. Many famous bands playing there. I went last year with my friends. The music were very loud and exciting. We dancing for hours. There was also many food stalls selling delicious snacks. I trying different types of food. The atmosphere was electric. Everyone were happy and smiling. It is a great way to celebrate summer. I planning to go again this year. It is the highlight of my summer.",
        "word_count": 86,
        "response_type": "long_turn",
        "micro_flaws": ["agreement: 'It happen' should be 'It happens'", "tense: 'bands playing' should be 'play' (or played)", "agreement: 'music were' should be 'was'", "tense: 'We dancing' should be 'danced'", "agreement: 'There was also many' should be 'were'", "tense: 'I trying' should be 'tried'", "agreement: 'Everyone were' should be 'was'", "tense: 'I planning' should be 'am planning'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR6] Vocabulary: 'Music Festival', 'famous bands', 'loud', 'exciting', 'food stalls', 'delicious snacks', 'atmosphere', 'electric', 'celebrate', 'highlight'. Adequate range. >Band 5: Clear descriptions. Not Band 7: Vocabulary is standard.",
        "grammar_reason": "[GRA5] Frequent grammatical errors. Agreement errors ('happen', 'music were', 'There was', 'Everyone were'). Tense errors ('playing', 'dancing', 'trying', 'planning'). >Band 4: Basic meaning clear. Not Band 6: Errors are systematic.",
        "vocabulary": 6,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a festival you enjoy.\n\nTranscript: I really enjoy the Music Festival in my city. It happen every summer in the park. Many famous bands playing there. I went last year with my friends. The music were very loud and exciting. We dancing for hours. There was also many food stalls selling delicious snacks. I trying different types of food. The atmosphere was electric. Everyone were happy and smiling. It is a great way to celebrate summer. I planning to go again this year. It is the highlight of my summer.\n\nWord Count: 86 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses descriptive vocabulary: 'food stalls', 'electric', 'highlight'. Good range.\n\n>Band 5: Adequate vocabulary.\n\nNot Band 7: Lacks sophistication.\n\n**Idiom present:** Yes ('highlight of my summer')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Frequent errors in verb forms and agreement. 'It happen', 'music were' are incorrect.\n\n>Band 4: Basic sentences are recognizable.\n\nNot Band 6: Errors are frequent and noticeable.\n\n**Micro flaws identified:**\n- 'It happen' should be 'It happens'\n- 'bands playing' should be 'bands play'\n- 'music were' should be 'music was'\n- 'We dancing' should be 'We danced'\n- 'There was also many' should be 'There were also many'\n- 'I trying' should be 'I tried'\n- 'Everyone were' should be 'Everyone was'\n- 'I planning' should be 'I am planning'"
    },
    # 454. V6/G5 - Object (Old)
    {
        "sample_id": "syn_p2_v6_g5_0454",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe an old object your family has kept.",
        "transcript_cleaned": "My family have an old radio that belonged to my grandfather. It is made of wood and look very vintage. It sitting in our living room. My father say it is very valuable. We do not use it to listen to music anymore. However, it still working. Sometimes we turning it on to hear the static sound. It remind me of the past. My grandfather buying it fifty years ago. It is a precious family heirloom. I hope to keeping it for my children.",
        "word_count": 86,
        "response_type": "long_turn",
        "micro_flaws": ["agreement: 'family have' should be 'has'", "agreement: 'look very' should be 'looks'", "tense: 'It sitting' should be 'sits' or 'is sitting'", "agreement: 'father say' should be 'says'", "tense: 'it still working' should be 'works' or 'is working'", "tense: 'we turning' should be 'turn'", "agreement: 'It remind' should be 'reminds'", "tense: 'grandfather buying' should be 'bought'", "grammar: 'hope to keeping' should be 'hope to keep'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR6] Vocabulary: 'radio', 'belonged', 'wood', 'vintage', 'valuable', 'static sound', 'precious', 'heirloom'. Adequate range. >Band 5: Uses specific words ('heirloom', 'vintage'). Not Band 7: Lacks depth.",
        "grammar_reason": "[GRA5] Frequent grammatical errors. Agreement errors ('family have', 'look', 'father say', 'remind'). Tense errors ('sitting', 'working', 'turning', 'buying'). >Band 4: Basic meaning clear. Not Band 6: Errors are systematic.",
        "vocabulary": 6,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe an old object your family has kept.\n\nTranscript: My family have an old radio that belonged to my grandfather. It is made of wood and look very vintage. It sitting in our living room. My father say it is very valuable. We do not use it to listen to music anymore. However, it still working. Sometimes we turning it on to hear the static sound. It remind me of the past. My grandfather buying it fifty years ago. It is a precious family heirloom. I hope to keeping it for my children.\n\nWord Count: 86 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses topic words: 'vintage', 'valuable', 'heirloom'. Meaning is clear.\n\n>Band 5: Adequate vocabulary.\n\nNot Band 7: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Frequent errors in verb tenses and agreement. 'Family have', 'It sitting' are incorrect.\n\n>Band 4: Basic sentences are recognizable.\n\nNot Band 6: Errors are frequent and noticeable.\n\n**Micro flaws identified:**\n- 'family have' should be 'family has'\n- 'look very' should be 'looks very'\n- 'It sitting' should be 'It sits'\n- 'father say' should be 'father says'\n- 'it still working' should be 'it still works'\n- 'we turning' should be 'we turn'\n- 'It remind' should be 'It reminds'\n- 'grandfather buying' should be 'grandfather bought'\n- 'hope to keeping' should be 'hope to keep'"
    },
    # 455. V6/G5 - Job (Ideal)
    {
        "sample_id": "syn_p2_v6_g5_0455",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe your ideal job.",
        "transcript_cleaned": "I wanting to be a travel writer. This job involving traveling to different countries and writing about them. I love exploring new cultures and trying exotic food. It would be a dream come true for me. I could sharing my experiences with readers. However, it require good writing skills. I practicing writing every day. I also needing to learn photography. Although it might be unstable, I think it is exciting. I hoping to work for a famous magazine one day. It is my passion.",
        "word_count": 86,
        "response_type": "long_turn",
        "micro_flaws": ["tense: 'I wanting' should be 'want'", "agreement: 'job involving' should be 'involves'", "grammar: 'could sharing' should be 'could share'", "agreement: 'it require' should be 'requires'", "tense: 'I practicing' should be 'practice'", "tense: 'I also needing' should be 'need'", "tense: 'I hoping' should be 'hope'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR6] Vocabulary: 'travel writer', 'exploring', 'cultures', 'exotic food', 'dream come true', 'experiences', 'readers', 'unstable', 'exciting', 'magazine', 'passion'. Adequate range. >Band 5: Good topic vocabulary. Not Band 7: Lacks sophistication.",
        "grammar_reason": "[GRA5] Frequent grammatical errors. Incorrect use of continuous forms ('wanting', 'involving', 'practicing', 'needing', 'hoping'). Agreement error ('require'). Modal error ('could sharing'). >Band 4: Basic meaning clear. Not Band 6: Errors are systematic.",
        "vocabulary": 6,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe your ideal job.\n\nTranscript: I wanting to be a travel writer. This job involving traveling to different countries and writing about them. I love exploring new cultures and trying exotic food. It would be a dream come true for me. I could sharing my experiences with readers. However, it require good writing skills. I practicing writing every day. I also needing to learn photography. Although it might be unstable, I think it is exciting. I hoping to work for a famous magazine one day. It is my passion.\n\nWord Count: 86 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses descriptive vocabulary: 'exotic', 'unstable', 'passion'. Good range.\n\n>Band 5: Adequate vocabulary.\n\nNot Band 7: Lacks variety.\n\n**Idiom present:** Yes ('dream come true')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Frequent errors in verb forms. 'I wanting', 'job involving' are incorrect.\n\n>Band 4: Basic sentences are recognizable.\n\nNot Band 6: Errors are frequent and noticeable.\n\n**Micro flaws identified:**\n- 'I wanting' should be 'I want'\n- 'job involving' should be 'job involves'\n- 'could sharing' should be 'could share'\n- 'it require' should be 'it requires'\n- 'I practicing' should be 'I practice'\n- 'I also needing' should be 'I also need'\n- 'I hoping' should be 'I hope'"
    },
    # 456. V6/G5 - Activity (Sport)
    {
        "sample_id": "syn_p2_v6_g5_0456",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a sport you would like to try.",
        "transcript_cleaned": "I would like to try surfing. It looking very exciting and challenging. I see people surfing on TV, and they makes it look easy. I know it requiring good balance and strength. I want to learn it because I love the ocean. Riding the waves feeling amazing, I think. I needing to buy a surfboard and a wetsuit. I planning to take lessons next summer. It might be dangerous, but I am not afraid. I hope I can standing on the board quickly.",
        "word_count": 87,
        "response_type": "long_turn",
        "micro_flaws": ["tense: 'It looking' should be 'It looks'", "agreement: 'they makes' should be 'make'", "tense: 'it requiring' should be 'requires'", "tense: 'waves feeling' should be 'feels' or 'must feel'", "tense: 'I needing' should be 'need'", "tense: 'I planning' should be 'am planning'", "grammar: 'can standing' should be 'can stand'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR6] Vocabulary: 'surfing', 'challenging', 'balance', 'strength', 'ocean', 'riding the waves', 'surfboard', 'wetsuit', 'lessons', 'dangerous', 'afraid'. Adequate range. >Band 5: Clear descriptions. Not Band 7: Vocabulary is standard.",
        "grammar_reason": "[GRA5] Frequent grammatical errors. Incorrect use of continuous forms ('looking', 'requiring', 'needing'). Agreement error ('they makes'). Modal error ('can standing'). >Band 4: Basic meaning clear. Not Band 6: Errors are systematic.",
        "vocabulary": 6,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a sport you would like to try.\n\nTranscript: I would like to try surfing. It looking very exciting and challenging. I see people surfing on TV, and they makes it look easy. I know it requiring good balance and strength. I want to learn it because I love the ocean. Riding the waves feeling amazing, I think. I needing to buy a surfboard and a wetsuit. I planning to take lessons next summer. It might be dangerous, but I am not afraid. I hope I can standing on the board quickly.\n\nWord Count: 87 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses topic words: 'balance', 'wetsuit', 'dangerous'. Meaning is clear.\n\n>Band 5: Adequate vocabulary.\n\nNot Band 7: Lacks sophistication.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Frequent errors in verb forms. 'It looking', 'can standing' are incorrect.\n\n>Band 4: Basic sentences are recognizable.\n\nNot Band 6: Errors are frequent and noticeable.\n\n**Micro flaws identified:**\n- 'It looking' should be 'It looks'\n- 'they makes' should be 'they make'\n- 'it requiring' should be 'it requires'\n- 'waves feeling' should be 'waves feel'\n- 'I needing' should be 'I need'\n- 'I planning' should be 'I am planning'\n- 'can standing' should be 'can stand'"
    },
    # 457. V6/G5 - Friend (Best)
    {
        "sample_id": "syn_p2_v6_g5_0457",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe your best friend.",
        "transcript_cleaned": "My best friend is named Anna. We meeting in kindergarten when we was five. She is very loyal and trustworthy. She always listen to my problems. We have similar interests, like fashion and music. We spending a lot of time together on weekends. Anna is very funny; she always making me laugh. She having a positive attitude towards life. I admire her because she is hardworking. We planning to go to the same university. I know our friendship will lasting forever.",
        "word_count": 83,
        "response_type": "long_turn",
        "micro_flaws": ["tense: 'We meeting' should be 'met'", "agreement: 'we was' should be 'were'", "agreement: 'She always listen' should be 'listens'", "tense: 'We spending' should be 'spend'", "tense: 'she always making' should be 'makes'", "tense: 'She having' should be 'has'", "tense: 'We planning' should be 'are planning'", "grammar: 'will lasting' should be 'will last'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR6] Vocabulary: 'kindergarten', 'loyal', 'trustworthy', 'similar interests', 'fashion', 'positive attitude', 'admire', 'hardworking', 'university', 'friendship', 'forever'. Adequate range. >Band 5: Uses specific adjectives ('loyal', 'trustworthy'). Not Band 7: Lacks depth.",
        "grammar_reason": "[GRA5] Frequent grammatical errors. Tense errors ('meeting', 'spending', 'making', 'having'). Agreement errors ('we was', 'She listen'). Verb form error ('will lasting'). >Band 4: Basic meaning clear. Not Band 6: Errors are systematic.",
        "vocabulary": 6,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe your best friend.\n\nTranscript: My best friend is named Anna. We meeting in kindergarten when we was five. She is very loyal and trustworthy. She always listen to my problems. We have similar interests, like fashion and music. We spending a lot of time together on weekends. Anna is very funny; she always making me laugh. She having a positive attitude towards life. I admire her because she is hardworking. We planning to go to the same university. I know our friendship will lasting forever.\n\nWord Count: 83 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses adjectives: 'loyal', 'trustworthy', 'hardworking'. Clear description.\n\n>Band 5: Adequate vocabulary.\n\nNot Band 7: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Frequent errors in verb tenses and agreement. 'We meeting', 'will lasting' are incorrect.\n\n>Band 4: Basic sentences are recognizable.\n\nNot Band 6: Errors are frequent and noticeable.\n\n**Micro flaws identified:**\n- 'We meeting' should be 'We met'\n- 'we was' should be 'we were'\n- 'She always listen' should be 'She always listens'\n- 'We spending' should be 'We spend'\n- 'she always making' should be 'she always makes'\n- 'She having' should be 'She has'\n- 'We planning' should be 'We are planning'\n- 'will lasting' should be 'will last'"
    },
    # 458. V6/G5 - Event (Party)
    {
        "sample_id": "syn_p2_v6_g5_0458",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a party you enjoyed.",
        "transcript_cleaned": "I enjoyed my graduation party last month. All my friends and family was there. We decorating the house with balloons and streamers. My mother cooking a lot of delicious food. I receiving many gifts, which made me happy. We playing music and dancing all night. It were a very special occasion for me. I feeling proud of my achievement. My father giving a speech about me. Everyone were clapping and cheering. I will remembering this night for a long time.",
        "word_count": 83,
        "response_type": "long_turn",
        "micro_flaws": ["agreement: 'family was' should be 'were'", "tense: 'We decorating' should be 'decorated'", "tense: 'mother cooking' should be 'cooked'", "tense: 'I receiving' should be 'received'", "tense: 'We playing' should be 'played'", "agreement: 'It were' should be 'was'", "tense: 'I feeling' should be 'felt'", "tense: 'father giving' should be 'gave'", "agreement: 'Everyone were' should be 'was'", "grammar: 'will remembering' should be 'will remember'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR6] Vocabulary: 'graduation party', 'balloons', 'streamers', 'delicious', 'gifts', 'occasion', 'proud', 'achievement', 'speech', 'clapping', 'cheering'. Adequate range. >Band 5: Clear descriptions. Not Band 7: Vocabulary is standard.",
        "grammar_reason": "[GRA5] Frequent grammatical errors. Tense errors ('decorating', 'cooking', 'receiving', 'playing', 'feeling', 'giving'). Agreement errors ('family was', 'It were', 'Everyone were'). >Band 4: Basic meaning clear. Not Band 6: Errors are systematic.",
        "vocabulary": 6,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a party you enjoyed.\n\nTranscript: I enjoyed my graduation party last month. All my friends and family was there. We decorating the house with balloons and streamers. My mother cooking a lot of delicious food. I receiving many gifts, which made me happy. We playing music and dancing all night. It were a very special occasion for me. I feeling proud of my achievement. My father giving a speech about me. Everyone were clapping and cheering. I will remembering this night for a long time.\n\nWord Count: 83 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses topic words: 'graduation', 'streamers', 'achievement'. Meaning is clear.\n\n>Band 5: Adequate vocabulary.\n\nNot Band 7: Lacks sophistication.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Frequent errors in verb forms and agreement. 'We decorating', 'It were' are incorrect.\n\n>Band 4: Basic sentences are recognizable.\n\nNot Band 6: Errors are frequent and noticeable.\n\n**Micro flaws identified:**\n- 'family was' should be 'family were'\n- 'We decorating' should be 'We decorated'\n- 'mother cooking' should be 'mother cooked'\n- 'I receiving' should be 'I received'\n- 'We playing' should be 'We played'\n- 'It were' should be 'It was'\n- 'I feeling' should be 'I felt'\n- 'father giving' should be 'father gave'\n- 'Everyone were' should be 'Everyone was'\n- 'will remembering' should be 'will remember'"
    },
    # 459. V6/G5 - Place (School)
    {
        "sample_id": "syn_p2_v6_g5_0459",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe your primary school.",
        "transcript_cleaned": "My primary school were small but colorful. It located near my home. I walking to school every morning. The teachers was very kind and patient. I learning many subjects like math and science. My favorite place were the playground. We playing games during recess. I made many friends there. The classrooms was decorated with our drawings. I having many happy memories of that school. It providing a good foundation for my education. I missing my teachers and friends from that time.",
        "word_count": 83,
        "response_type": "long_turn",
        "micro_flaws": ["agreement: 'school were' should be 'was'", "grammar: 'It located' should be 'It was located'", "tense: 'I walking' should be 'walked'", "agreement: 'teachers was' should be 'were'", "tense: 'I learning' should be 'learned'", "agreement: 'place were' should be 'was'", "tense: 'We playing' should be 'played'", "agreement: 'classrooms was' should be 'were'", "tense: 'I having' should be 'have'", "tense: 'It providing' should be 'provided'", "tense: 'I missing' should be 'miss'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR6] Vocabulary: 'primary school', 'colorful', 'located', 'patient', 'subjects', 'playground', 'recess', 'decorated', 'drawings', 'memories', 'foundation', 'education'. Adequate range. >Band 5: Clear descriptions. Not Band 7: Vocabulary is standard.",
        "grammar_reason": "[GRA5] Frequent grammatical errors. Agreement errors ('school were', 'teachers was', 'place were', 'classrooms was'). Tense errors ('walking', 'learning', 'playing', 'having'). >Band 4: Basic meaning clear. Not Band 6: Errors are systematic.",
        "vocabulary": 6,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe your primary school.\n\nTranscript: My primary school were small but colorful. It located near my home. I walking to school every morning. The teachers was very kind and patient. I learning many subjects like math and science. My favorite place were the playground. We playing games during recess. I made many friends there. The classrooms was decorated with our drawings. I having many happy memories of that school. It providing a good foundation for my education. I missing my teachers and friends from that time.\n\nWord Count: 83 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses topic words: 'recess', 'decorated', 'foundation'. Meaning is clear.\n\n>Band 5: Adequate vocabulary.\n\nNot Band 7: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Frequent errors in verb tenses and agreement. 'School were', 'I walking' are incorrect.\n\n>Band 4: Basic sentences are recognizable.\n\nNot Band 6: Errors are frequent and noticeable.\n\n**Micro flaws identified:**\n- 'school were' should be 'school was'\n- 'It located' should be 'It was located'\n- 'I walking' should be 'I walked'\n- 'teachers was' should be 'teachers were'\n- 'I learning' should be 'I learned'\n- 'place were' should be 'place was'\n- 'We playing' should be 'We played'\n- 'classrooms was' should be 'classrooms were'\n- 'I having' should be 'I have'\n- 'It providing' should be 'It provided'\n- 'I missing' should be 'I miss'"
    },
    # 460. V6/G5 - Activity (Hobby)
    {
        "sample_id": "syn_p2_v6_g5_0460",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a hobby you have.",
        "transcript_cleaned": "I enjoy gardening in my free time. I have a small garden in my backyard. I growing many types of flowers and vegetables. It is very relaxing activity. I watering the plants every morning. I also removing the weeds to keep it clean. My favorite flower are the rose. It smelling very sweet. Gardening help me connect with nature. I started this hobby two years ago. I learning a lot about plants from my mother. I hoping to expand my garden next year.",
        "word_count": 86,
        "response_type": "long_turn",
        "micro_flaws": ["tense: 'I growing' should be 'grow'", "article: 'is very relaxing activity' should be 'is a very relaxing activity'", "tense: 'I watering' should be 'water'", "tense: 'I also removing' should be 'remove'", "agreement: 'flower are' should be 'is'", "agreement: 'It smelling' should be 'smells'", "agreement: 'Gardening help' should be 'helps'", "tense: 'I learning' should be 'learned' (or am learning)", "tense: 'I hoping' should be 'hope'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR6] Vocabulary: 'gardening', 'backyard', 'relaxing', 'weeds', 'connect', 'nature', 'expand', 'plants', 'flowers', 'vegetables'. Adequate range. >Band 5: Clear descriptions. Not Band 7: Vocabulary is standard.",
        "grammar_reason": "[GRA5] Frequent grammatical errors. Tense errors ('growing', 'watering', 'removing', 'learning', 'hoping'). Agreement errors ('flower are', 'smelling', 'help'). >Band 4: Basic meaning clear. Not Band 6: Errors are systematic.",
        "vocabulary": 6,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a hobby you have.\n\nTranscript: I enjoy gardening in my free time. I have a small garden in my backyard. I growing many types of flowers and vegetables. It is very relaxing activity. I watering the plants every morning. I also removing the weeds to keep it clean. My favorite flower are the rose. It smelling very sweet. Gardening help me connect with nature. I started this hobby two years ago. I learning a lot about plants from my mother. I hoping to expand my garden next year.\n\nWord Count: 86 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses topic words: 'weeds', 'backyard', 'connect'. Meaning is clear.\n\n>Band 5: Adequate vocabulary.\n\nNot Band 7: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Frequent errors in verb forms and agreement. 'I growing', 'flower are' are incorrect.\n\n>Band 4: Basic sentences are recognizable.\n\nNot Band 6: Errors are frequent and noticeable.\n\n**Micro flaws identified:**\n- 'I growing' should be 'I grow'\n- 'is very relaxing activity' should be 'is a very relaxing activity'\n- 'I watering' should be 'I water'\n- 'I also removing' should be 'I also remove'\n- 'flower are' should be 'flower is'\n- 'It smelling' should be 'It smells'\n- 'Gardening help' should be 'Gardening helps'\n- 'I learning' should be 'I learned'\n- 'I hoping' should be 'I hope'"
    }
]

with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
    for sample in samples:
        f.write(json.dumps(sample) + '\n')
