import json

OUTPUT_FILE = "ielts-data/phase3/v76_review_output/synthetic_batches/batch_p2_08.jsonl"

samples = [
    # 361. V5/G7 - Hobby (Collecting)
    {
        "sample_id": "syn_p2_v5_g7_0361",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a hobby you enjoy collecting.",
        "transcript_cleaned": "I would like to talk about collecting coins, which is a hobby I have had since I was young. I started doing this when my uncle gave me some old money from different countries. Although my collection is not very big, it is important to me because each coin has a story. I keep them in a special book so they do not get damaged. If I had more money, I would buy rarer coins from online shops. The reason I like this hobby is that it teaches me about history and geography. Sometimes, I spend hours looking at the details on the coins. It is a simple hobby, but it gives me a lot of happiness.",
        "word_count": 121,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR5] Vocabulary: 'collecting coins', 'old money', 'different countries', 'special book', 'damaged', 'rarer', 'online shops', 'history', 'geography', 'details', 'simple hobby', 'happiness'. Functional but limited range. >Band 4: Uses some less common words ('rarer', 'geography') but mostly basic. Not Band 6: Lacks variety and precision.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'Which is a hobby I have had...' (Relative clause). 'Although my collection is not very big...' (Concessive clause). 'If I had more money, I would buy...' (Second conditional). Accurate.",
        "vocabulary": 5,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a hobby you enjoy collecting.\n\nTranscript: I would like to talk about collecting coins, which is a hobby I have had since I was young. I started doing this when my uncle gave me some old money from different countries. Although my collection is not very big, it is important to me because each coin has a story. I keep them in a special book so they do not get damaged. If I had more money, I would buy rarer coins from online shops. The reason I like this hobby is that it teaches me about history and geography. Sometimes, I spend hours looking at the details on the coins. It is a simple hobby, but it gives me a lot of happiness.\n\nWord Count: 121 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses basic vocabulary accurately: 'collecting', 'damaged', 'history'. Limited range of less common lexical items.\n\n>Band 4: Can discuss the topic.\n\nNot Band 6: Lack of variety and sophistication.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses a variety of complex structures (relative clauses, conditionals) with good control. Sentences are error-free.\n\n>Band 6: More flexibility and accuracy.\n\nNot Band 8: Structures are correct but not highly sophisticated.\n\n**Micro flaws identified:**\n- None."
    },
    # 362. V5/G7 - Animal (Pet)
    {
        "sample_id": "syn_p2_v5_g7_0362",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a pet you would like to have.",
        "transcript_cleaned": "I have always wanted to have a dog, specifically a Golden Retriever. This type of dog is known for being friendly and good with families. If I lived in a house with a big garden, I would get one immediately. I think dogs are the best pets because they are loyal and can protect the home. I would name him Max and take him for walks in the park every morning. Although taking care of a dog is hard work, I believe it is worth it. Having a dog would make me feel less lonely when I am at home. It would be great to have a companion who is always happy to see me.",
        "word_count": 121,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR5] Vocabulary: 'specifically', 'friendly', 'families', 'garden', 'immediately', 'loyal', 'protect', 'hard work', 'worth it', 'lonely', 'companion'. Functional but limited range. >Band 4: Uses some topic vocabulary. Not Band 6: Repetitive and basic.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'If I lived..., I would get...' (Second conditional). 'Because they are loyal...' (Reason clause). 'Although taking care of a dog is hard work...' (Concessive clause). Accurate.",
        "vocabulary": 5,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a pet you would like to have.\n\nTranscript: I have always wanted to have a dog, specifically a Golden Retriever. This type of dog is known for being friendly and good with families. If I lived in a house with a big garden, I would get one immediately. I think dogs are the best pets because they are loyal and can protect the home. I would name him Max and take him for walks in the park every morning. Although taking care of a dog is hard work, I believe it is worth it. Having a dog would make me feel less lonely when I am at home. It would be great to have a companion who is always happy to see me.\n\nWord Count: 121 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses basic vocabulary: 'friendly', 'loyal', 'protect', 'companion'. Limited range.\n\n>Band 4: Clear meaning.\n\nNot Band 6: Lacks precision.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures like conditionals and concessive clauses correctly. Good control of grammar.\n\n>Band 6: Error-free sentences.\n\nNot Band 8: Not enough range of structures.\n\n**Micro flaws identified:**\n- None."
    },
    # 363. V5/G7 - Job (Dislike)
    {
        "sample_id": "syn_p2_v5_g7_0363",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a job you would not like to do.",
        "transcript_cleaned": "I would really hate to be a doctor, which might surprise some people. The main reason is that I am afraid of blood and seeing people in pain. Working in a hospital seems very stressful to me because you have to make important decisions quickly. Also, doctors have to work long hours, often at night, which would make me very tired. If I were a doctor, I think I would be worried all the time about making a mistake. Although the salary is high, the pressure is too much for me. I prefer a job that is more creative and relaxed. Helping people is good, but I would choose a different way to do it.",
        "word_count": 121,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR5] Vocabulary: 'hate', 'surprise', 'afraid', 'pain', 'hospital', 'stressful', 'decisions', 'long hours', 'worried', 'mistake', 'salary', 'pressure', 'creative', 'relaxed'. Functional but basic. >Band 4: Uses some relevant words ('pressure', 'creative'). Not Band 6: Simple language.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'Which might surprise some people' (Relative clause). 'The main reason is that...' (Noun clause). 'If I were a doctor, I think I would be...' (Second conditional). Accurate.",
        "vocabulary": 5,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a job you would not like to do.\n\nTranscript: I would really hate to be a doctor, which might surprise some people. The main reason is that I am afraid of blood and seeing people in pain. Working in a hospital seems very stressful to me because you have to make important decisions quickly. Also, doctors have to work long hours, often at night, which would make me very tired. If I were a doctor, I think I would be worried all the time about making a mistake. Although the salary is high, the pressure is too much for me. I prefer a job that is more creative and relaxed. Helping people is good, but I would choose a different way to do it.\n\nWord Count: 121 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses basic vocabulary: 'afraid', 'pain', 'stressful', 'pressure'. Limited range.\n\n>Band 4: Adequate for task.\n\nNot Band 6: Lacks lexical variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures correctly, including relative clauses and conditionals. Good grammatical control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Structure variety is limited.\n\n**Micro flaws identified:**\n- None."
    },
    # 364. V5/G7 - Place (Crowded)
    {
        "sample_id": "syn_p2_v5_g7_0364",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a crowded place you went to.",
        "transcript_cleaned": "Last month, I went to a shopping mall in the city center during a holiday sale. It was incredibly crowded, with people pushing each other to get into the shops. I went there to buy some new clothes, but it was difficult to move around. The noise was very loud because everyone was talking at the same time. Although I found some good things to buy, I did not enjoy the experience very much. If I had known it would be so busy, I would have stayed at home. Waiting in line to pay took a long time, which was boring. I think next time I will go shopping on a weekday when it is quieter.",
        "word_count": 122,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR5] Vocabulary: 'shopping mall', 'holiday sale', 'incredibly', 'crowded', 'pushing', 'difficult', 'move around', 'noise', 'loud', 'experience', 'busy', 'stayed at home', 'waiting in line', 'boring', 'weekday', 'quieter'. Functional but basic. >Band 4: Adequate vocabulary. Not Band 6: Lacks sophistication.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'With people pushing...' (Prepositional phrase). 'Although I found...' (Concessive clause). 'If I had known..., I would have stayed...' (Third conditional). 'Which was boring' (Relative clause). Accurate.",
        "vocabulary": 5,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a crowded place you went to.\n\nTranscript: Last month, I went to a shopping mall in the city center during a holiday sale. It was incredibly crowded, with people pushing each other to get into the shops. I went there to buy some new clothes, but it was difficult to move around. The noise was very loud because everyone was talking at the same time. Although I found some good things to buy, I did not enjoy the experience very much. If I had known it would be so busy, I would have stayed at home. Waiting in line to pay took a long time, which was boring. I think next time I will go shopping on a weekday when it is quieter.\n\nWord Count: 122 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses basic vocabulary: 'crowded', 'pushing', 'noise', 'boring'. Limited range.\n\n>Band 4: Understandable.\n\nNot Band 6: Simple word choices.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures like third conditionals and relative clauses correctly. Good control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Limited range of complex structures.\n\n**Micro flaws identified:**\n- None."
    },
    # 365. V5/G7 - Website (Entertainment)
    {
        "sample_id": "syn_p2_v5_g7_0365",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a website you visit for entertainment.",
        "transcript_cleaned": "I often visit YouTube when I have free time, which is a website for watching videos. I like it because you can find videos about almost anything, from music to cooking. I usually watch funny videos or travel vlogs to relax after work. It is easy to use because you just search for what you want. Sometimes, I spend too much time on it because there are so many interesting things to watch. If I am bored, YouTube is the first place I go. The reason it is popular is that it is free and has a lot of content. I have learned how to cook some new dishes by watching videos on this site.",
        "word_count": 121,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR5] Vocabulary: 'visit', 'free time', 'videos', 'music', 'cooking', 'funny', 'travel vlogs', 'relax', 'search', 'interesting', 'bored', 'popular', 'content', 'dishes'. Functional but basic. >Band 4: Uses some relevant words ('vlogs', 'content'). Not Band 6: Repetitive.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'Which is a website...' (Relative clause). 'Because you can find...' (Reason clause). 'The reason it is popular is that...' (Noun clause). 'If I am bored...' (First conditional). Accurate.",
        "vocabulary": 5,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a website you visit for entertainment.\n\nTranscript: I often visit YouTube when I have free time, which is a website for watching videos. I like it because you can find videos about almost anything, from music to cooking. I usually watch funny videos or travel vlogs to relax after work. It is easy to use because you just search for what you want. Sometimes, I spend too much time on it because there are so many interesting things to watch. If I am bored, YouTube is the first place I go. The reason it is popular is that it is free and has a lot of content. I have learned how to cook some new dishes by watching videos on this site.\n\nWord Count: 121 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses basic vocabulary: 'videos', 'cooking', 'search', 'popular'. Limited range.\n\n>Band 4: Clear meaning.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures correctly, including noun clauses and conditionals. Good grammatical control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Structure variety is limited.\n\n**Micro flaws identified:**\n- None."
    },
    # 366. V5/G7 - Story (Childhood)
    {
        "sample_id": "syn_p2_v5_g7_0366",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a story someone told you when you were a child.",
        "transcript_cleaned": "I remember a story my grandmother told me about a magical forest. It was about a young boy who got lost in the woods and met talking animals. The story was very exciting because the animals helped him find his way home. She told me this story every night before I went to sleep. Although I knew the ending, I always liked hearing it again. If I closed my eyes, I could imagine the forest and the animals. This story taught me that being kind to others is important. Even now, when I think about my childhood, I remember her voice telling the story. It is a happy memory that I will keep for a long time.",
        "word_count": 121,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR5] Vocabulary: 'magical forest', 'lost', 'woods', 'talking animals', 'exciting', 'find his way', 'ending', 'imagine', 'kind', 'childhood', 'voice', 'happy memory'. Functional but basic. >Band 4: Adequate vocabulary. Not Band 6: Simple descriptions.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'Who got lost...' (Relative clause). 'Because the animals helped him...' (Reason clause). 'Although I knew the ending...' (Concessive clause). 'That being kind... is important' (Noun clause). Accurate.",
        "vocabulary": 5,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a story someone told you when you were a child.\n\nTranscript: I remember a story my grandmother told me about a magical forest. It was about a young boy who got lost in the woods and met talking animals. The story was very exciting because the animals helped him find his way home. She told me this story every night before I went to sleep. Although I knew the ending, I always liked hearing it again. If I closed my eyes, I could imagine the forest and the animals. This story taught me that being kind to others is important. Even now, when I think about my childhood, I remember her voice telling the story. It is a happy memory that I will keep for a long time.\n\nWord Count: 121 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses basic vocabulary: 'magical', 'lost', 'exciting', 'imagine'. Limited range.\n\n>Band 4: Clear meaning.\n\nNot Band 6: Lacks lexical variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures correctly, including relative clauses and noun clauses. Good control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Limited range of complex structures.\n\n**Micro flaws identified:**\n- None."
    },
    # 367. V5/G7 - Time (Busy)
    {
        "sample_id": "syn_p2_v5_g7_0367",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a time when you were very busy.",
        "transcript_cleaned": "I was very busy last year when I was preparing for my final exams at university. I had to study for five different subjects in one month, which was very hard. I spent all my time in the library reading books and writing notes. Because I had so much work to do, I stopped going out with my friends. I felt very tired and stressed during that time. If I had not studied so hard, I might have failed the exams. However, I managed to finish everything on time. After the exams were over, I slept for a whole day. It was a difficult time, but I am happy that I got good grades in the end.",
        "word_count": 121,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR5] Vocabulary: 'preparing', 'final exams', 'subjects', 'library', 'notes', 'stopped going out', 'tired', 'stressed', 'failed', 'managed', 'grades'. Functional but basic. >Band 4: Uses some relevant words ('stressed', 'grades'). Not Band 6: Simple language.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'When I was preparing...' (Time clause). 'Which was very hard' (Relative clause). 'Because I had so much work...' (Reason clause). 'If I had not studied..., I might have failed...' (Third conditional). Accurate.",
        "vocabulary": 5,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a time when you were very busy.\n\nTranscript: I was very busy last year when I was preparing for my final exams at university. I had to study for five different subjects in one month, which was very hard. I spent all my time in the library reading books and writing notes. Because I had so much work to do, I stopped going out with my friends. I felt very tired and stressed during that time. If I had not studied so hard, I might have failed the exams. However, I managed to finish everything on time. After the exams were over, I slept for a whole day. It was a difficult time, but I am happy that I got good grades in the end.\n\nWord Count: 121 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses basic vocabulary: 'preparing', 'study', 'tired', 'stressed'. Limited range.\n\n>Band 4: Adequate vocabulary.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures like third conditionals and time clauses correctly. Good grammatical control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Limited range of complex structures.\n\n**Micro flaws identified:**\n- None."
    },
    # 368. V5/G7 - Photo (Family)
    {
        "sample_id": "syn_p2_v5_g7_0368",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a photo of your family that you like.",
        "transcript_cleaned": "I have a photo of my family that was taken during a picnic last summer. In the picture, we are all sitting on a blanket in the park, smiling at the camera. My parents are in the middle, and my brother and I are on the sides. I like this photo because everyone looks happy and relaxed. The weather was sunny, which made the colors in the photo very bright. Whenever I look at it, I remember the fun day we had together. It is in a frame on my desk in my bedroom. If my house was on fire, this is one of the things I would save. It reminds me how important family is to me.",
        "word_count": 122,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR5] Vocabulary: 'picnic', 'blanket', 'smiling', 'camera', 'middle', 'sides', 'relaxed', 'weather', 'sunny', 'bright', 'frame', 'desk', 'save', 'reminds'. Functional but basic. >Band 4: Clear meaning. Not Band 6: Simple descriptions.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'That was taken...' (Relative clause). 'Which made the colors...' (Relative clause). 'Whenever I look at it...' (Time clause). 'If my house was on fire, ... I would save' (Second conditional). Accurate.",
        "vocabulary": 5,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a photo of your family that you like.\n\nTranscript: I have a photo of my family that was taken during a picnic last summer. In the picture, we are all sitting on a blanket in the park, smiling at the camera. My parents are in the middle, and my brother and I are on the sides. I like this photo because everyone looks happy and relaxed. The weather was sunny, which made the colors in the photo very bright. Whenever I look at it, I remember the fun day we had together. It is in a frame on my desk in my bedroom. If my house was on fire, this is one of the things I would save. It reminds me how important family is to me.\n\nWord Count: 122 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses basic vocabulary: 'picnic', 'blanket', 'smiling', 'bright'. Limited range.\n\n>Band 4: Adequate for task.\n\nNot Band 6: Lacks sophistication.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures correctly, including relative clauses and conditionals. Good control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Limited range of complex structures.\n\n**Micro flaws identified:**\n- None."
    },
    # 369. V5/G7 - App (Mobile)
    {
        "sample_id": "syn_p2_v5_g7_0369",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a mobile app you use often.",
        "transcript_cleaned": "I use a messaging app called WhatsApp every day to talk to my friends and family. It is very useful because I can send messages, photos, and even make video calls for free. I started using it a few years ago when I got my first smartphone. The best thing about it is that I can create groups to chat with many people at once. For example, I have a group for my family and another one for my classmates. If I did not have this app, it would be expensive to call people who live far away. It helps me stay connected with everyone easily. I check it many times a day to see if I have new messages.",
        "word_count": 124,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR5] Vocabulary: 'messaging app', 'useful', 'send messages', 'video calls', 'free', 'smartphone', 'create groups', 'chat', 'classmates', 'expensive', 'connected', 'check'. Functional but basic. >Band 4: Uses some relevant words ('groups', 'connected'). Not Band 6: Simple language.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'Called WhatsApp' (Participle phrase). 'Because I can send...' (Reason clause). 'The best thing about it is that...' (Noun clause). 'If I did not have..., it would be...' (Second conditional). Accurate.",
        "vocabulary": 5,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a mobile app you use often.\n\nTranscript: I use a messaging app called WhatsApp every day to talk to my friends and family. It is very useful because I can send messages, photos, and even make video calls for free. I started using it a few years ago when I got my first smartphone. The best thing about it is that I can create groups to chat with many people at once. For example, I have a group for my family and another one for my classmates. If I did not have this app, it would be expensive to call people who live far away. It helps me stay connected with everyone easily. I check it many times a day to see if I have new messages.\n\nWord Count: 124 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses basic vocabulary: 'messaging', 'video calls', 'groups', 'connected'. Limited range.\n\n>Band 4: Clear meaning.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures correctly, including noun clauses and conditionals. Good grammatical control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Limited range of complex structures.\n\n**Micro flaws identified:**\n- None."
    },
    # 370. V5/G7 - Weather
    {
        "sample_id": "syn_p2_v5_g7_0370",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe your favorite type of weather.",
        "transcript_cleaned": "I really like sunny weather, especially when it is not too hot. When the sun is shining, I feel happy and full of energy. It is the perfect weather for going outside and doing activities like swimming or playing football. I usually go to the beach with my friends on sunny days. I do not like rain because it makes everything wet and I have to stay inside. If it rains for a long time, I feel a bit sad. Sunny days are also good for taking photos because the light is nice. I think most people prefer sunny weather because it is cheerful. It reminds me of summer holidays when I was a child.",
        "word_count": 118,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR5] Vocabulary: 'sunny', 'shining', 'happy', 'energy', 'perfect', 'activities', 'swimming', 'beach', 'rain', 'wet', 'inside', 'sad', 'light', 'cheerful', 'holidays'. Functional but basic. >Band 4: Uses some adjectives ('cheerful', 'perfect'). Not Band 6: Simple vocabulary.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'Especially when it is not too hot' (Time clause). 'Because it makes everything wet' (Reason clause). 'If it rains..., I feel...' (First conditional). 'Because it is cheerful' (Reason clause). Accurate.",
        "vocabulary": 5,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe your favorite type of weather.\n\nTranscript: I really like sunny weather, especially when it is not too hot. When the sun is shining, I feel happy and full of energy. It is the perfect weather for going outside and doing activities like swimming or playing football. I usually go to the beach with my friends on sunny days. I do not like rain because it makes everything wet and I have to stay inside. If it rains for a long time, I feel a bit sad. Sunny days are also good for taking photos because the light is nice. I think most people prefer sunny weather because it is cheerful. It reminds me of summer holidays when I was a child.\n\nWord Count: 118 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses basic vocabulary: 'shining', 'energy', 'perfect', 'cheerful'. Limited range.\n\n>Band 4: Adequate vocabulary.\n\nNot Band 6: Lacks sophistication.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures correctly, including time clauses and conditionals. Good control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Limited range of complex structures.\n\n**Micro flaws identified:**\n- None."
    }
]

with open(OUTPUT_FILE, 'a', encoding='utf-8') as f:
    for sample in samples:
        f.write(json.dumps(sample) + '\n')
