import json

OUTPUT_FILE = "ielts-data/phase3/v76_review_output/synthetic_batches/batch_p2_13.jsonl"

samples = [
    # 601. V4/G6 - Book (Read)
    {
        "sample_id": "syn_p2_v4_g6_0601",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a book you read recently.",
        "transcript_cleaned": "I read a book called 'Animal Farm' last week. It is a famous book. It is about animals on a farm. The pigs want to be leaders. They are bad animals. The other animals work hard. I liked the story because it was interesting. I think the writer is very clever. Although the language was simple, the meaning was deep. If I have time, I will read it again. It taught me about power and people. I recommend this book to my friends.",
        "word_count": 94,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR4] Limited range: 'book', 'famous', 'animals', 'farm', 'pigs', 'leaders', 'bad', 'work hard', 'story', 'interesting', 'clever', 'simple', 'deep', 'time', 'power', 'people', 'recommend'. Basic and repetitive. >Band 3: Basic meaning. Not Band 5: Minimal variation.",
        "grammar_reason": "[GRA6] Uses a mix of simple and complex structures. 'Although the language was simple...' (Concessive clause). 'If I have time, I will read...' (First conditional). 'Because it was interesting' (Reason clause). Generally error-free. >Band 5: Uses complex structures accurately. Not Band 7: Limited range.",
        "vocabulary": 4,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a book you read recently.\n\nTranscript: I read a book called 'Animal Farm' last week. It is a famous book. It is about animals on a farm. The pigs want to be leaders. They are bad animals. The other animals work hard. I liked the story because it was interesting. I think the writer is very clever. Although the language was simple, the meaning was deep. If I have time, I will read it again. It taught me about power and people. I recommend this book to my friends.\n\nWord Count: 94 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Basic vocabulary: 'animals', 'farm', 'bad'. Simple adjectives. No complex words.\n\n>Band 3: Basic description.\n\nNot Band 5: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Uses a mix of simple and complex structures accurately. Includes concessive clauses and conditionals.\n\n>Band 5: Good control of complex forms.\n\nNot Band 7: Range is limited.\n\n**Micro flaws identified:**\n- None."
    },
    # 602. V4/G6 - Place (City)
    {
        "sample_id": "syn_p2_v4_g6_0602",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a city you want to visit.",
        "transcript_cleaned": "I want to visit New York City in America. It is a very big city. I see it in movies many times. I want to see the tall buildings and the park. I think it is a busy place with many people. If I go there, I will visit the Statue of Liberty. I also want to eat American food, like burgers. Although it is far away, I hope to go there one day. It looks like an exciting place to be. I will take many photos.",
        "word_count": 99,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR4] Limited range: 'visit', 'big city', 'movies', 'tall buildings', 'park', 'busy', 'people', 'food', 'burgers', 'far away', 'exciting', 'photos'. Basic travel vocabulary. >Band 3: Communicates desire. Not Band 5: Minimal description.",
        "grammar_reason": "[GRA6] Uses a mix of simple and complex structures. 'If I go there, I will visit...' (First conditional). 'Although it is far away...' (Concessive clause). 'It looks like...' (Comparative structure). Generally error-free. >Band 5: Uses complex structures accurately. Not Band 7: Limited range.",
        "vocabulary": 4,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a city you want to visit.\n\nTranscript: I want to visit New York City in America. It is a very big city. I see it in movies many times. I want to see the tall buildings and the park. I think it is a busy place with many people. If I go there, I will visit the Statue of Liberty. I also want to eat American food, like burgers. Although it is far away, I hope to go there one day. It looks like an exciting place to be. I will take many photos.\n\nWord Count: 99 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Basic vocabulary: 'big city', 'movies', 'busy'. Repetitive. No descriptive variety.\n\n>Band 3: Basic meaning.\n\nNot Band 5: Lacks range.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Uses a mix of simple and complex structures accurately. Includes conditionals and concessive clauses.\n\n>Band 5: Good control of complex forms.\n\nNot Band 7: Range is limited.\n\n**Micro flaws identified:**\n- None."
    },
    # 603. V4/G6 - Event (Holiday)
    {
        "sample_id": "syn_p2_v4_g6_0603",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a holiday you enjoyed.",
        "transcript_cleaned": "I enjoyed my summer holiday last year. I went to the beach with my family. We stayed in a hotel for five days. The weather was hot and sunny. We swam in the sea every day, which was fun. I also played football on the sand. My mother cooked good food for us. We ate fish and fruit. Although I was tired, I was very happy. It was a good time for me. I want to go back there again next year.",
        "word_count": 91,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR4] Limited range: 'summer holiday', 'beach', 'family', 'hotel', 'weather', 'hot', 'sunny', 'swam', 'sea', 'fun', 'football', 'sand', 'cooked', 'food', 'fish', 'fruit', 'tired', 'happy', 'good time'. Basic holiday vocabulary. >Band 3: Clear narrative. Not Band 5: Minimal variation.",
        "grammar_reason": "[GRA6] Uses a mix of simple and complex structures. 'Which was fun' (Relative clause). 'Although I was tired...' (Concessive clause). Past tense used correctly throughout. Generally error-free. >Band 5: Uses complex structures accurately. Not Band 7: Limited range.",
        "vocabulary": 4,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a holiday you enjoyed.\n\nTranscript: I enjoyed my summer holiday last year. I went to the beach with my family. We stayed in a hotel for five days. The weather was hot and sunny. We swam in the sea every day, which was fun. I also played football on the sand. My mother cooked good food for us. We ate fish and fruit. Although I was tired, I was very happy. It was a good time for me. I want to go back there again next year.\n\nWord Count: 91 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Basic vocabulary: 'beach', 'hotel', 'happy'. Simple description. No range.\n\n>Band 3: Basic story.\n\nNot Band 5: Lacks descriptive words.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Uses a mix of simple and complex structures accurately. Includes relative clauses and concessive clauses. Good past tense usage.\n\n>Band 5: Good control of complex forms.\n\nNot Band 7: Range is limited.\n\n**Micro flaws identified:**\n- None."
    },
    # 604. V4/G6 - Object (Gift)
    {
        "sample_id": "syn_p2_v4_g6_0604",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a gift you received.",
        "transcript_cleaned": "I received a new phone for my birthday. My father gave it to me. It is a black phone. I like it because it is very fast. I use it to call my friends and play games. It has a good camera, so I take many photos. I was very surprised when I got it. It was expensive, but my father said I am a good student. I will keep it safe. It is the best gift I have ever received.",
        "word_count": 92,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR4] Limited range: 'phone', 'birthday', 'father', 'black', 'fast', 'call', 'friends', 'games', 'camera', 'photos', 'surprised', 'expensive', 'student', 'safe', 'best gift'. Basic vocabulary. >Band 3: Communicates meaning. Not Band 5: Minimal description.",
        "grammar_reason": "[GRA6] Uses a mix of simple and complex structures. 'Because it is very fast' (Reason clause). 'So I take many photos' (Result clause). 'When I got it' (Time clause). 'Best gift I have ever received' (Relative clause). Generally error-free. >Band 5: Uses complex structures accurately. Not Band 7: Limited range.",
        "vocabulary": 4,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a gift you received.\n\nTranscript: I received a new phone for my birthday. My father gave it to me. It is a black phone. I like it because it is very fast. I use it to call my friends and play games. It has a good camera, so I take many photos. I was very surprised when I got it. It was expensive, but my father said I am a good student. I will keep it safe. It is the best gift I have ever received.\n\nWord Count: 92 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Basic vocabulary: 'phone', 'fast', 'surprised'. Simple words. No variety.\n\n>Band 3: Basic description.\n\nNot Band 5: Lacks range.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Uses a mix of simple and complex structures accurately. Includes reason clauses and time clauses.\n\n>Band 5: Good control of complex forms.\n\nNot Band 7: Range is limited.\n\n**Micro flaws identified:**\n- None."
    },
    # 605. V4/G6 - Person (Friend)
    {
        "sample_id": "syn_p2_v4_g6_0605",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a friend you like.",
        "transcript_cleaned": "I like my friend Tom. We go to the same school. He is tall and has brown hair. He is very funny and makes me laugh. We play football together every day after school. I like him because he is kind to me. If I have a problem, he helps me. Last week, I was sad, and he talked to me. He is a good listener. I think he is my best friend. I hope we will be friends for a long time.",
        "word_count": 92,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR4] Limited range: 'friend', 'school', 'tall', 'brown hair', 'funny', 'laugh', 'football', 'kind', 'problem', 'helps', 'sad', 'talked', 'listener', 'best friend'. Basic vocabulary. >Band 3: Meaning clear. Not Band 5: Minimal variation.",
        "grammar_reason": "[GRA6] Uses a mix of simple and complex structures. 'Because he is kind to me' (Reason clause). 'If I have a problem, he helps me' (First conditional). 'I think he is...' (Noun clause). Generally error-free. >Band 5: Uses complex structures accurately. Not Band 7: Limited range.",
        "vocabulary": 4,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a friend you like.\n\nTranscript: I like my friend Tom. We go to the same school. He is tall and has brown hair. He is very funny and makes me laugh. We play football together every day after school. I like him because he is kind to me. If I have a problem, he helps me. Last week, I was sad, and he talked to me. He is a good listener. I think he is my best friend. I hope we will be friends for a long time.\n\nWord Count: 92 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Basic vocabulary: 'funny', 'kind', 'sad'. Simple adjectives. No complex words.\n\n>Band 3: Basic description.\n\nNot Band 5: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Uses a mix of simple and complex structures accurately. Includes conditionals and reason clauses.\n\n>Band 5: Good control of complex forms.\n\nNot Band 7: Range is limited.\n\n**Micro flaws identified:**\n- None."
    },
    # 606. V4/G6 - Activity (Daily)
    {
        "sample_id": "syn_p2_v4_g6_0606",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe something you do every day.",
        "transcript_cleaned": "Every day, I cook dinner for my family. I start cooking at 6 pm. I usually make rice and vegetables. Sometimes I cook chicken or fish. I like cooking because it is fun. My mother taught me how to cook. I chop the vegetables and boil the water. While the food is cooking, I listen to music. It makes me feel happy. After we eat, I clean the kitchen. My family says the food is tasty. I enjoy doing this for them.",
        "word_count": 91,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR4] Limited range: 'cook dinner', 'family', 'rice', 'vegetables', 'chicken', 'fish', 'fun', 'taught', 'chop', 'boil', 'water', 'music', 'happy', 'clean', 'kitchen', 'tasty', 'enjoy'. Basic cooking vocabulary. >Band 3: Clear sequence. Not Band 5: Minimal variation.",
        "grammar_reason": "[GRA6] Uses a mix of simple and complex structures. 'Because it is fun' (Reason clause). 'How to cook' (Noun phrase). 'While the food is cooking' (Time clause). 'After we eat' (Time clause). Generally error-free. >Band 5: Uses complex structures accurately. Not Band 7: Limited range.",
        "vocabulary": 4,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe something you do every day.\n\nTranscript: Every day, I cook dinner for my family. I start cooking at 6 pm. I usually make rice and vegetables. Sometimes I cook chicken or fish. I like cooking because it is fun. My mother taught me how to cook. I chop the vegetables and boil the water. While the food is cooking, I listen to music. It makes me feel happy. After we eat, I clean the kitchen. My family says the food is tasty. I enjoy doing this for them.\n\nWord Count: 91 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Basic vocabulary: 'cook', 'vegetables', 'tasty'. Repetitive. No descriptive language.\n\n>Band 3: Can describe routine.\n\nNot Band 5: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Uses a mix of simple and complex structures accurately. Includes time clauses and reason clauses.\n\n>Band 5: Good control of complex forms.\n\nNot Band 7: Range is limited.\n\n**Micro flaws identified:**\n- None."
    },
    # 607. V4/G6 - Place (Home)
    {
        "sample_id": "syn_p2_v4_g6_0607",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe your home.",
        "transcript_cleaned": "I live in a small apartment with my parents. It has two bedrooms and one living room. The kitchen is small but clean. I like my room because it is quiet. I have a bed and a desk there. I do my homework at the desk. The walls are white and blue. We have a TV in the living room where we watch movies. Although the apartment is small, it is comfortable. I feel safe there. It is a good place to live.",
        "word_count": 91,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR4] Limited range: 'apartment', 'parents', 'bedrooms', 'living room', 'kitchen', 'clean', 'quiet', 'bed', 'desk', 'homework', 'walls', 'white', 'blue', 'TV', 'movies', 'comfortable', 'safe', 'good place'. Basic home vocabulary. >Band 3: Communicates basic info. Not Band 5: Minimal variation.",
        "grammar_reason": "[GRA6] Uses a mix of simple and complex structures. 'Because it is quiet' (Reason clause). 'Where we watch movies' (Relative clause). 'Although the apartment is small...' (Concessive clause). Generally error-free. >Band 5: Uses complex structures accurately. Not Band 7: Limited range.",
        "vocabulary": 4,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe your home.\n\nTranscript: I live in a small apartment with my parents. It has two bedrooms and one living room. The kitchen is small but clean. I like my room because it is quiet. I have a bed and a desk there. I do my homework at the desk. The walls are white and blue. We have a TV in the living room where we watch movies. Although the apartment is small, it is comfortable. I feel safe there. It is a good place to live.\n\nWord Count: 91 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Basic vocabulary: 'apartment', 'room', 'clean'. Simple description. No range.\n\n>Band 3: Basic meaning.\n\nNot Band 5: Limited vocabulary.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Uses a mix of simple and complex structures accurately. Includes relative clauses and concessive clauses.\n\n>Band 5: Good control of complex forms.\n\nNot Band 7: Range is limited.\n\n**Micro flaws identified:**\n- None."
    },
    # 608. V4/G6 - Activity (Hobby)
    {
        "sample_id": "syn_p2_v4_g6_0608",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a hobby you enjoy.",
        "transcript_cleaned": "My hobby is drawing pictures. I like drawing animals and trees. I use pencils and paper. I started drawing when I was a child. It is very fun. I draw every weekend in my room. Sometimes I draw with my sister. She is good at drawing too. I like it because it makes me relax. I have many pictures on my wall. I want to be an artist one day. Drawing is my favorite thing to do.",
        "word_count": 87,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR4] Limited range: 'drawing pictures', 'animals', 'trees', 'pencils', 'paper', 'child', 'fun', 'weekend', 'room', 'sister', 'relax', 'wall', 'artist', 'favorite thing'. Basic hobby vocabulary. >Band 3: Clear meaning. Not Band 5: Minimal variation.",
        "grammar_reason": "[GRA6] Uses a mix of simple and complex structures. 'When I was a child' (Time clause). 'Because it makes me relax' (Reason clause). 'I want to be...' (Verb pattern). Generally error-free. >Band 5: Uses complex structures accurately. Not Band 7: Limited range.",
        "vocabulary": 4,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a hobby you enjoy.\n\nTranscript: My hobby is drawing pictures. I like drawing animals and trees. I use pencils and paper. I started drawing when I was a child. It is very fun. I draw every weekend in my room. Sometimes I draw with my sister. She is good at drawing too. I like it because it makes me relax. I have many pictures on my wall. I want to be an artist one day. Drawing is my favorite thing to do.\n\nWord Count: 87 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Basic vocabulary: 'drawing', 'pencils', 'fun'. Repetitive. No complex words.\n\n>Band 3: Basic description.\n\nNot Band 5: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Uses a mix of simple and complex structures accurately. Includes time clauses and reason clauses.\n\n>Band 5: Good control of complex forms.\n\nNot Band 7: Range is limited.\n\n**Micro flaws identified:**\n- None."
    },
    # 609. V4/G6 - Place (Park)
    {
        "sample_id": "syn_p2_v4_g6_0609",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a park you like.",
        "transcript_cleaned": "I like the park near my house. It is a big place with green grass. There are many trees and flowers there. I go there to play with my dog. He likes to run. I also see other people walking. It is very quiet and nice. I go there on Sunday morning. The air is clean. I feel happy when I am there. If it rains, I do not go. It is a good place for families. I like sitting on the bench.",
        "word_count": 91,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR4] Limited range: 'park', 'house', 'big place', 'green grass', 'trees', 'flowers', 'play', 'dog', 'run', 'walking', 'quiet', 'nice', 'clean', 'happy', 'rains', 'families', 'bench'. Basic nature vocabulary. >Band 3: Clear description. Not Band 5: Minimal variation.",
        "grammar_reason": "[GRA6] Uses a mix of simple and complex structures. 'To play with my dog' (Infinitive of purpose). 'When I am there' (Time clause). 'If it rains...' (First conditional). Generally error-free. >Band 5: Uses complex structures accurately. Not Band 7: Limited range.",
        "vocabulary": 4,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a park you like.\n\nTranscript: I like the park near my house. It is a big place with green grass. There are many trees and flowers there. I go there to play with my dog. He likes to run. I also see other people walking. It is very quiet and nice. I go there on Sunday morning. The air is clean. I feel happy when I am there. If it rains, I do not go. It is a good place for families. I like sitting on the bench.\n\nWord Count: 91 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Basic vocabulary: 'park', 'grass', 'happy'. Simple description. No range.\n\n>Band 3: Basic meaning.\n\nNot Band 5: Limited vocabulary.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Uses a mix of simple and complex structures accurately. Includes conditionals and time clauses.\n\n>Band 5: Good control of complex forms.\n\nNot Band 7: Range is limited.\n\n**Micro flaws identified:**\n- None."
    },
    # 610. V4/G6 - Event (Family)
    {
        "sample_id": "syn_p2_v4_g6_0610",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a meal you had with your family.",
        "transcript_cleaned": "I remember a dinner with my family last month. We went to a restaurant for my father's birthday. The restaurant was very big and clean. We ordered chicken and rice. The food was tasty. We drank juice too. My father was very happy. We talked and laughed a lot. I gave him a card. It was a special night. Although I was tired, I enjoyed it. We went home late. It is a good memory for me.",
        "word_count": 87,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR4] Limited range: 'dinner', 'family', 'restaurant', 'birthday', 'big', 'clean', 'ordered', 'chicken', 'rice', 'tasty', 'drank', 'juice', 'happy', 'talked', 'laughed', 'card', 'special night', 'tired', 'enjoyed', 'home', 'memory'. Basic food/family vocabulary. >Band 3: Clear narrative. Not Band 5: Minimal variation.",
        "grammar_reason": "[GRA6] Uses a mix of simple and complex structures. 'For my father's birthday' (Prepositional phrase). 'Although I was tired...' (Concessive clause). Past tense used correctly throughout. Generally error-free. >Band 5: Uses complex structures accurately. Not Band 7: Limited range.",
        "vocabulary": 4,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a meal you had with your family.\n\nTranscript: I remember a dinner with my family last month. We went to a restaurant for my father's birthday. The restaurant was very big and clean. We ordered chicken and rice. The food was tasty. We drank juice too. My father was very happy. We talked and laughed a lot. I gave him a card. It was a special night. Although I was tired, I enjoyed it. We went home late. It is a good memory for me.\n\nWord Count: 87 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Basic vocabulary: 'dinner', 'tasty', 'happy'. Simple words. No complex vocabulary.\n\n>Band 3: Basic story.\n\nNot Band 5: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Uses a mix of simple and complex structures accurately. Includes concessive clauses and correct past tense.\n\n>Band 5: Good control of complex forms.\n\nNot Band 7: Range is limited.\n\n**Micro flaws identified:**\n- None."
    }
]

with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
    for sample in samples:
        f.write(json.dumps(sample) + '\n')
