import json

OUTPUT_FILE = "ielts-data/phase3/v76_review_output/synthetic_batches/batch_p2_02.jsonl"

samples = [
    # 61. V6/G6 - Travel
    {
        "sample_id": "syn_p2_v6_g6_0061",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a place you would like to travel to.",
        "transcript_cleaned": "I have always dreamed of visiting Japan. It is a fascinating country with a rich culture. I want to see the cherry blossoms in spring. I heard they are beautiful. I also want to visit Tokyo, the capital city. It is a modern city with many skyscrapers. But I also like traditional places. Kyoto has many old temples and shrines. I would like to try authentic Japanese food like sushi and ramen. I think the people there are very polite and disciplined. I plan to go there next year if I have enough money. I will save money from now. I will travel with my best friend. We share the same interest. We love anime and manga. It will be an unforgettable trip for us. I can't wait to go.",
        "word_count": 139,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'share the same interest' → 'share the same interests'", "grammar: 'It is a fascinating country' → 'It is a fascinating country' (Correct)", "grammar: 'I heard they are beautiful' → 'I have heard they are beautiful'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR6] Vocabulary: 'dreamed', 'fascinating', 'rich culture', 'cherry blossoms', 'skyscrapers', 'traditional', 'shrines', 'authentic', 'disciplined', 'unforgettable'.",
        "grammar_reason": "[GRA6] Mix of simple and complex structures. 'I plan to go there next year if I have enough money' (First conditional). 'I heard they are beautiful' (Reported speech implied). Generally accurate with minor errors.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a place you would like to travel to.\n\nTranscript: I have always dreamed of visiting Japan. It is a fascinating country with a rich culture. I want to see the cherry blossoms in spring. I heard they are beautiful. I also want to visit Tokyo, the capital city. It is a modern city with many skyscrapers. But I also like traditional places. Kyoto has many old temples and shrines. I would like to try authentic Japanese food like sushi and ramen. I think the people there are very polite and disciplined. I plan to go there next year if I have enough money. I will save money from now. I will travel with my best friend. We share the same interest. We love anime and manga. It will be an unforgettable trip for us. I can't wait to go.\n\nWord Count: 139 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses 'fascinating', 'cherry blossoms', 'skyscrapers', 'authentic', 'disciplined', 'unforgettable'.\n\n>Band 5: Uses less common words.\n\nNot Band 7: Vocabulary is functional.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Mix of structures. 'I plan to go there... if...'. Generally accurate.\n\n>Band 5: More complex structures.\n\nNot Band 7: Simple sentences still common.\n\n**Micro flaws identified:**\n- 'share the same interest' should be 'share the same interests'"
    },
    # 62. V6/G6 - Event
    {
        "sample_id": "syn_p2_v6_g6_0062",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe an important event in your life.",
        "transcript_cleaned": "An important event in my life was my university graduation. It happened two years ago. I studied engineering for four years. It was a challenging course. I had to study very hard to pass the exams. On the graduation day, my parents came to the university. They were very proud of me. I wore a graduation gown and a cap. I felt a sense of accomplishment. I received my degree on the stage. The ceremony was formal and solemn. Many students were there with their families. We took many photos together. It was a turning point in my life. After that, I started looking for a job. I became an adult. Responsible. I realized that education is the key to success. I will never forget that day. It was a milestone for me.",
        "word_count": 139,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'graduation day' → 'graduation day'", "grammar: 'graduation gown' → 'graduation gown'", "grammar: 'sense of accomplishment' → 'sense of accomplishment'", "grammar: 'turning point' → 'turning point'", "grammar: 'key to success' → 'key to success'", "grammar: 'milestone' → 'milestone'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR6] Vocabulary: 'graduation', 'engineering', 'challenging', 'accomplishment', 'degree', 'ceremony', 'solemn', 'turning point', 'responsible', 'milestone'.",
        "grammar_reason": "[GRA6] Mix of structures. 'I had to study very hard to pass...' (Infinitive of purpose). 'I realized that education is the key...' (Noun clause). Accurate usage of past tenses.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe an important event in your life.\n\nTranscript: An important event in my life was my university graduation. It happened two years ago. I studied engineering for four years. It was a challenging course. I had to study very hard to pass the exams. On the graduation day, my parents came to the university. They were very proud of me. I wore a graduation gown and a cap. I felt a sense of accomplishment. I received my degree on the stage. The ceremony was formal and solemn. Many students were there with their families. We took many photos together. It was a turning point in my life. After that, I started looking for a job. I became an adult. Responsible. I realized that education is the key to success. I will never forget that day. It was a milestone for me.\n\nWord Count: 139 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses 'challenging', 'accomplishment', 'ceremony', 'solemn', 'turning point', 'milestone'.\n\n>Band 5: Uses topic-specific words.\n\nNot Band 7: Limited precision.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Mix of structures. 'I had to study...'. 'I realized that...'. Accurate past tenses.\n\n>Band 5: More complex structures.\n\nNot Band 7: Simple sentences still common.\n\n**Micro flaws identified:**\n- None significant."
    },
    # 63. V6/G6 - Advice
    {
        "sample_id": "syn_p2_v6_g6_0063",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a piece of advice you received.",
        "transcript_cleaned": "I received a valuable piece of advice from my high school teacher. I was stressed about my exams. I was afraid of failure. My teacher noticed my anxiety. She called me to her office. She told me, 'Don't worry about the result, just focus on the process'. She explained that if I do my best, I should not regret anything. This advice changed my mindset. I stopped worrying and started studying calmly. I created a study plan. I followed it strictly. In the end, I did well in the exams. I was very grateful to her. Now, whenever I face a challenge, I remember her words. It helps me stay positive. I think good advice can guide us in the right direction. It is like a light in the dark. Encouraging.",
        "word_count": 139,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'valuable piece of advice' → 'valuable piece of advice'", "grammar: 'afraid of failure' → 'afraid of failure'", "grammar: 'noticed my anxiety' → 'noticed my anxiety'", "grammar: 'focus on the process' → 'focus on the process'", "grammar: 'changed my mindset' → 'changed my mindset'", "grammar: 'stay positive' → 'stay positive'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR6] Vocabulary: 'valuable', 'stressed', 'failure', 'anxiety', 'process', 'regret', 'mindset', 'calmly', 'grateful', 'challenge', 'positive', 'guide', 'encouraging'.",
        "grammar_reason": "[GRA6] Mix of structures. 'She explained that if I do my best, I should not regret...' (Reported speech + Conditional). 'Whenever I face a challenge, I remember...' (Time clause). Accurate.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a piece of advice you received.\n\nTranscript: I received a valuable piece of advice from my high school teacher. I was stressed about my exams. I was afraid of failure. My teacher noticed my anxiety. She called me to her office. She told me, 'Don't worry about the result, just focus on the process'. She explained that if I do my best, I should not regret anything. This advice changed my mindset. I stopped worrying and started studying calmly. I created a study plan. I followed it strictly. In the end, I did well in the exams. I was very grateful to her. Now, whenever I face a challenge, I remember her words. It helps me stay positive. I think good advice can guide us in the right direction. It is like a light in the dark. Encouraging.\n\nWord Count: 139 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses 'valuable', 'anxiety', 'process', 'mindset', 'grateful', 'challenge'.\n\n>Band 5: Uses less common words.\n\nNot Band 7: Functional vocabulary.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Mix of structures. 'She explained that if...'. 'Whenever I face...'. Generally accurate.\n\n>Band 5: More complex structures.\n\nNot Band 7: Simple sentences still common.\n\n**Micro flaws identified:**\n- None significant."
    },
    # 64. V6/G6 - Lost Item
    {
        "sample_id": "syn_p2_v6_g6_0064",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe an item you lost that was important to you.",
        "transcript_cleaned": "I lost my wallet last month. It was a leather wallet that my girlfriend gave me. It was very important to me because it was a gift. I think I dropped it on the bus. I was listening to music and didn't notice. When I got off the bus, I realized it was gone. I checked my pockets but it wasn't there. I felt panic. My ID card, credit card, and some cash were inside. I called the bus company immediately. They said they would check the bus. I also went to the police station to report it. Unfortunately, no one found it. I had to cancel my credit card. It was a hassle. Inconvenient. I felt guilty because I was careless. I learned a lesson to be more careful with my belongings. Valuable lesson.",
        "word_count": 139,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'leather wallet' → 'leather wallet'", "grammar: 'dropped it on the bus' → 'dropped it on the bus'", "grammar: 'didn't notice' → 'didn't notice'", "grammar: 'felt panic' → 'felt panicked/panicked'", "grammar: 'report it' → 'report it'", "grammar: 'hassle' → 'hassle'", "grammar: 'Inconvenient' → 'Inconvenient'", "grammar: 'felt guilty' → 'felt guilty'", "grammar: 'belongings' → 'belongings'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR6] Vocabulary: 'leather', 'gift', 'realized', 'panic', 'immediately', 'unfortunately', 'cancel', 'hassle', 'inconvenient', 'guilty', 'careless', 'belongings'. 'Hassle' is a good colloquial word.",
        "grammar_reason": "[GRA6] Mix of structures. 'I think I dropped it...' (Noun clause). 'When I got off the bus, I realized...' (Time clause). 'I felt guilty because I was careless' (Reason). Accurate past tenses.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe an item you lost that was important to you.\n\nTranscript: I lost my wallet last month. It was a leather wallet that my girlfriend gave me. It was very important to me because it was a gift. I think I dropped it on the bus. I was listening to music and didn't notice. When I got off the bus, I realized it was gone. I checked my pockets but it wasn't there. I felt panic. My ID card, credit card, and some cash were inside. I called the bus company immediately. They said they would check the bus. I also went to the police station to report it. Unfortunately, no one found it. I had to cancel my credit card. It was a hassle. Inconvenient. I felt guilty because I was careless. I learned a lesson to be more careful with my belongings. Valuable lesson.\n\nWord Count: 139 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses 'leather', 'panic', 'unfortunately', 'cancel', 'hassle', 'inconvenient', 'guilty', 'belongings'.\n\n>Band 5: Uses less common words.\n\nNot Band 7: Limited precision.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Mix of structures. 'When I got off...'. 'I felt guilty because...'. Generally accurate.\n\n>Band 5: More complex structures.\n\nNot Band 7: Simple sentences still common.\n\n**Micro flaws identified:**\n- 'felt panic' should be 'felt panicked' or 'panicked'"
    },
    # 65. V6/G6 - Team
    {
        "sample_id": "syn_p2_v6_g6_0065",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a team project you worked on.",
        "transcript_cleaned": "I worked on a team project in my marketing class last semester. We had to create a marketing plan for a new product. There were four members in my team. We divided the work equally. I was responsible for market research. I conducted a survey to understand customer needs. My teammates worked on product design and promotion. We met every week to discuss our progress. It was not easy because we had different opinions. Arguments. But we learned to compromise and listen to each other. Teamwork is about collaboration. Finally, we finished the project on time and presented it to the class. The professor gave us a high grade. I was very happy. I learned that working in a team requires communication and patience. It was a valuable experience for my future career.",
        "word_count": 139,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'marketing plan' → 'marketing plan'", "grammar: 'conducted a survey' → 'conducted a survey'", "grammar: 'customer needs' → 'customer needs'", "grammar: 'product design' → 'product design'", "grammar: 'different opinions' → 'different opinions'", "grammar: 'compromise' → 'compromise'", "grammar: 'collaboration' → 'collaboration'", "grammar: 'presented it' → 'presented it'", "grammar: 'requires communication' → 'requires communication'", "grammar: 'valuable experience' → 'valuable experience'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR6] Vocabulary: 'marketing', 'conducted', 'survey', 'promotion', 'progress', 'compromise', 'collaboration', 'presented', 'communication', 'patience', 'valuable', 'career'.",
        "grammar_reason": "[GRA6] Mix of structures. 'We had to create...' (Modals). 'I was responsible for...' (Adjective phrase). 'I learned that working in a team requires...' (Noun clause + Gerund). Accurate.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a team project you worked on.\n\nTranscript: I worked on a team project in my marketing class last semester. We had to create a marketing plan for a new product. There were four members in my team. We divided the work equally. I was responsible for market research. I conducted a survey to understand customer needs. My teammates worked on product design and promotion. We met every week to discuss our progress. It was not easy because we had different opinions. Arguments. But we learned to compromise and listen to each other. Teamwork is about collaboration. Finally, we finished the project on time and presented it to the class. The professor gave us a high grade. I was very happy. I learned that working in a team requires communication and patience. It was a valuable experience for my future career.\n\nWord Count: 139 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses 'conducted', 'survey', 'promotion', 'compromise', 'collaboration', 'communication'.\n\n>Band 5: Uses topic-specific words.\n\nNot Band 7: Limited precision.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Mix of structures. 'I was responsible for...'. 'I learned that working...'. Generally accurate.\n\n>Band 5: More complex structures.\n\nNot Band 7: Simple sentences still common.\n\n**Micro flaws identified:**\n- None significant."
    },
    # 66. V6/G6 - Changed Mind
    {
        "sample_id": "syn_p2_v6_g6_0066",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a time you changed your opinion/mind.",
        "transcript_cleaned": "I used to think that online learning was ineffective. I preferred traditional classroom learning. Face-to-face interaction. However, during the pandemic, I had to take online classes. At first, I was skeptical. I thought it would be boring and difficult to focus. But after a few weeks, I changed my mind. I found that online learning has many advantages. It is flexible and convenient. I can study from anywhere. I also saved time on commuting. The teachers used many digital tools to make the lessons interesting. Interactive quizzes. Videos. I realized that the quality of learning depends on the student's attitude, not just the mode of delivery. Now, I am more open to online education. It is a good alternative. I admit I was wrong before.",
        "word_count": 136,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'ineffective' → 'ineffective'", "grammar: 'skeptical' → 'skeptical'", "grammar: 'saved time on commuting' → 'saved time commuting/on commuting'", "grammar: 'digital tools' → 'digital tools'", "grammar: 'interactive quizzes' → 'interactive quizzes'", "grammar: 'student's attitude' → 'student's attitude'", "grammar: 'mode of delivery' → 'mode of delivery'", "grammar: 'alternative' → 'alternative'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR6] Vocabulary: 'ineffective', 'preferred', 'interaction', 'skeptical', 'flexible', 'convenient', 'commuting', 'digital tools', 'interactive', 'attitude', 'mode of delivery', 'alternative', 'admit'. Good range.",
        "grammar_reason": "[GRA6] Mix of structures. 'I used to think that...' (Used to + Noun clause). 'I thought it would be...' (Future in past). 'I found that online learning has...' (Reported speech). Accurate.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a time you changed your opinion/mind.\n\nTranscript: I used to think that online learning was ineffective. I preferred traditional classroom learning. Face-to-face interaction. However, during the pandemic, I had to take online classes. At first, I was skeptical. I thought it would be boring and difficult to focus. But after a few weeks, I changed my mind. I found that online learning has many advantages. It is flexible and convenient. I can study from anywhere. I also saved time on commuting. The teachers used many digital tools to make the lessons interesting. Interactive quizzes. Videos. I realized that the quality of learning depends on the student's attitude, not just the mode of delivery. Now, I am more open to online education. It is a good alternative. I admit I was wrong before.\n\nWord Count: 136 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses 'ineffective', 'skeptical', 'flexible', 'convenient', 'interactive', 'attitude', 'alternative'.\n\n>Band 5: Uses less common words.\n\nNot Band 7: Limited precision.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Mix of structures. 'I used to think...'. 'I realized that...'. Generally accurate.\n\n>Band 5: More complex structures.\n\nNot Band 7: Simple sentences still common.\n\n**Micro flaws identified:**\n- None significant."
    },
    # 67. V6/G6 - Celebration
    {
        "sample_id": "syn_p2_v6_g6_0067",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a celebration you attended.",
        "transcript_cleaned": "I attended a wedding celebration of my cousin last month. It was held in a luxury hotel. The venue was decorated beautifully with flowers and lights. It looked like a fairytale. There were many guests. Relatives and friends. The bride and groom looked stunning. They wore traditional costumes. The atmosphere was joyful and festive. We enjoyed a delicious banquet. Many courses. There was also live music and dancing. I danced with my family. It was fun. The most touching moment was when the groom gave a speech. He thanked his parents and expressed his love for his wife. Everyone was moved. Some people cried tears of joy. I think weddings are special occasions because they bring families together to celebrate love. It was a memorable night.",
        "word_count": 136,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'luxury hotel' → 'luxury hotel'", "grammar: 'fairytale' → 'fairytale'", "grammar: 'stunning' → 'stunning'", "grammar: 'festive' → 'festive'", "grammar: 'banquet' → 'banquet'", "grammar: 'touching moment' → 'touching moment'", "grammar: 'tears of joy' → 'tears of joy'", "grammar: 'special occasions' → 'special occasions'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR6] Vocabulary: 'luxury', 'venue', 'decorated', 'fairytale', 'stunning', 'costumes', 'atmosphere', 'festive', 'banquet', 'touching', 'occasion', 'memorable'.",
        "grammar_reason": "[GRA6] Mix of structures. 'The most touching moment was when...' (Cleft sentence/Time clause). 'He thanked his parents and expressed...' (Compound verb). 'I think weddings are special occasions because...' (Reason). Accurate.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a celebration you attended.\n\nTranscript: I attended a wedding celebration of my cousin last month. It was held in a luxury hotel. The venue was decorated beautifully with flowers and lights. It looked like a fairytale. There were many guests. Relatives and friends. The bride and groom looked stunning. They wore traditional costumes. The atmosphere was joyful and festive. We enjoyed a delicious banquet. Many courses. There was also live music and dancing. I danced with my family. It was fun. The most touching moment was when the groom gave a speech. He thanked his parents and expressed his love for his wife. Everyone was moved. Some people cried tears of joy. I think weddings are special occasions because they bring families together to celebrate love. It was a memorable night.\n\nWord Count: 136 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses 'venue', 'fairytale', 'stunning', 'festive', 'banquet', 'touching', 'moved'.\n\n>Band 5: Uses topic-specific words.\n\nNot Band 7: Limited precision.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Mix of structures. 'The most touching moment was when...'. 'I think... because...'. Generally accurate.\n\n>Band 5: More complex structures.\n\nNot Band 7: Simple sentences still common.\n\n**Micro flaws identified:**\n- None significant."
    },
    # 68. V6/G6 - Surprise
    {
        "sample_id": "syn_p2_v6_g6_0068",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a surprise that made you happy.",
        "transcript_cleaned": "I received a surprise birthday party from my friends last year. I thought they forgot my birthday because no one wished me in the morning. I felt a bit sad and lonely. After work, I went home. When I opened the door, the lights were off. Suddenly, the lights turned on and my friends jumped out. They shouted 'Happy Birthday!'. I was shocked. Speechless. They decorated my room with balloons and banners. They bought a big chocolate cake. My favorite. They also gave me many gifts. I was very touched by their effort. We had a great party. Ate pizza, drank soda, and played games. It was the best birthday ever. I realized that I have amazing friends who care about me. It was a wonderful surprise.",
        "word_count": 139,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'wished me' → 'wished me happy birthday'", "grammar: 'speechless' → 'speechless'", "grammar: 'touched by their effort' → 'touched by their effort'", "grammar: 'amazing friends' → 'amazing friends'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR6] Vocabulary: 'surprise', 'forgot', 'lonely', 'shocked', 'speechless', 'decorated', 'banners', 'touched', 'effort', 'realized', 'amazing', 'wonderful'.",
        "grammar_reason": "[GRA6] Mix of structures. 'I thought they forgot my birthday because...' (Noun clause + Reason). 'When I opened the door, the lights...' (Time clause). 'I realized that I have amazing friends who care...' (Noun clause + Relative clause). Accurate.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a surprise that made you happy.\n\nTranscript: I received a surprise birthday party from my friends last year. I thought they forgot my birthday because no one wished me in the morning. I felt a bit sad and lonely. After work, I went home. When I opened the door, the lights were off. Suddenly, the lights turned on and my friends jumped out. They shouted 'Happy Birthday!'. I was shocked. Speechless. They decorated my room with balloons and banners. They bought a big chocolate cake. My favorite. They also gave me many gifts. I was very touched by their effort. We had a great party. Ate pizza, drank soda, and played games. It was the best birthday ever. I realized that I have amazing friends who care about me. It was a wonderful surprise.\n\nWord Count: 139 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses 'shocked', 'speechless', 'decorated', 'banners', 'touched', 'effort'.\n\n>Band 5: Uses less common words.\n\nNot Band 7: Vocabulary is functional.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Mix of structures. 'I realized that...'. 'When I opened...'. Generally accurate.\n\n>Band 5: More complex structures.\n\nNot Band 7: Simple sentences still common.\n\n**Micro flaws identified:**\n- 'wished me' should be 'wished me happy birthday' (minor)"
    },
    # 69. V6/G6 - Old Object
    {
        "sample_id": "syn_p2_v6_g6_0069",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe an old object which your family has kept for a long time.",
        "transcript_cleaned": "My family has kept an old clock for over 50 years. It belonged to my grandfather. It is a grandfather clock. Tall and wooden. It stands in our living room. The wood is dark brown. Mahogany. It has a pendulum that swings back and forth. Tick-tock. Every hour, it chimes. The sound is deep and loud. My grandfather bought it when he got married. It is a family heirloom. Valuable antique. My father takes care of it now. He cleans it and winds it up every week. It still works perfectly. I like this clock because it has history. It witnessed many events in our family. Births, weddings, gatherings. It reminds us of our ancestors. We will keep it for the next generation. It is a treasure for us.",
        "word_count": 139,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'grandfather clock' → 'grandfather clock'", "grammar: 'pendulum' → 'pendulum'", "grammar: 'swings back and forth' → 'swings back and forth'", "grammar: 'chimes' → 'chimes'", "grammar: 'family heirloom' → 'family heirloom'", "grammar: 'valuable antique' → 'valuable antique'", "grammar: 'witnessed' → 'witnessed'", "grammar: 'ancestors' → 'ancestors'", "grammar: 'generation' → 'generation'", "grammar: 'treasure' → 'treasure'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR6] Vocabulary: 'grandfather clock', 'mahogany', 'pendulum', 'swings', 'chimes', 'heirloom', 'antique', 'witnessed', 'ancestors', 'generation', 'treasure'. Good range.",
        "grammar_reason": "[GRA6] Mix of structures. 'It has a pendulum that swings...' (Relative clause). 'My grandfather bought it when he got married' (Time clause). 'It reminds us of our ancestors' (Verb pattern). Accurate.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe an old object which your family has kept for a long time.\n\nTranscript: My family has kept an old clock for over 50 years. It belonged to my grandfather. It is a grandfather clock. Tall and wooden. It stands in our living room. The wood is dark brown. Mahogany. It has a pendulum that swings back and forth. Tick-tock. Every hour, it chimes. The sound is deep and loud. My grandfather bought it when he got married. It is a family heirloom. Valuable antique. My father takes care of it now. He cleans it and winds it up every week. It still works perfectly. I like this clock because it has history. It witnessed many events in our family. Births, weddings, gatherings. It reminds us of our ancestors. We will keep it for the next generation. It is a treasure for us.\n\nWord Count: 139 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses 'mahogany', 'pendulum', 'chimes', 'heirloom', 'antique', 'ancestors'.\n\n>Band 5: Uses less common words.\n\nNot Band 7: Limited precision.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Mix of structures. 'It has a pendulum that...'. 'My grandfather bought it when...'. Generally accurate.\n\n>Band 5: More complex structures.\n\nNot Band 7: Simple sentences still common.\n\n**Micro flaws identified:**\n- None significant."
    },
    # 70. V6/G6 - Science
    {
        "sample_id": "syn_p2_v6_g6_0070",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe an area of science that interests you.",
        "transcript_cleaned": "I am interested in astronomy. The study of stars and planets. I have been fascinated by the universe since I was a child. I used to look at the night sky and wonder what is out there. I like this subject because it is mysterious and vast. There are billions of galaxies in the universe. It makes me feel small but curious. I often watch documentaries about space exploration. NASA missions. Black holes. It is mind-blowing. I also like to read news about new discoveries. For example, finding water on Mars. It suggests that there might be life on other planets. Aliens. I think astronomy is important because it helps us understand our origin. Where we come from. I hope to buy a telescope one day to observe the stars more clearly.",
        "word_count": 139,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'wonder what is out there' → 'wonder what was out there'", "grammar: 'mind-blowing' → 'mind-blowing'", "grammar: 'suggests that there might be' → 'suggests that there might be'", "grammar: 'observe' → 'observe'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR6] Vocabulary: 'astronomy', 'fascinated', 'universe', 'mysterious', 'vast', 'galaxies', 'curious', 'exploration', 'mind-blowing', 'discoveries', 'aliens', 'origin', 'telescope', 'observe'.",
        "grammar_reason": "[GRA6] Mix of structures. 'I have been fascinated... since...' (Present Perfect). 'It suggests that there might be...' (Noun clause). 'I hope to buy... to observe...' (Infinitive of purpose). Accurate.",
        "vocabulary": 6,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe an area of science that interests you.\n\nTranscript: I am interested in astronomy. The study of stars and planets. I have been fascinated by the universe since I was a child. I used to look at the night sky and wonder what is out there. I like this subject because it is mysterious and vast. There are billions of galaxies in the universe. It makes me feel small but curious. I often watch documentaries about space exploration. NASA missions. Black holes. It is mind-blowing. I also like to read news about new discoveries. For example, finding water on Mars. It suggests that there might be life on other planets. Aliens. I think astronomy is important because it helps us understand our origin. Where we come from. I hope to buy a telescope one day to observe the stars more clearly.\n\nWord Count: 139 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses 'astronomy', 'fascinated', 'universe', 'galaxies', 'exploration', 'mind-blowing', 'origin', 'telescope'.\n\n>Band 5: Uses topic-specific words.\n\nNot Band 7: Limited precision.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Mix of structures. 'I have been fascinated...'. 'It suggests that...'. Generally accurate.\n\n>Band 5: More complex structures.\n\nNot Band 7: Simple sentences still common.\n\n**Micro flaws identified:**\n- 'wonder what is out there' should be 'wonder what was out there'"
    }
]

with open(OUTPUT_FILE, 'a', encoding='utf-8') as f:
    for sample in samples:
        f.write(json.dumps(sample) + '\n')
