import json

OUTPUT_FILE = "ielts-data/phase3/v76_review_output/synthetic_batches/batch_p2_12.jsonl"

samples = [
    # 551. V9/G9 - Job (Future)
    {
        "sample_id": "syn_p2_v9_g9_0551",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a job you would like to have.",
        "transcript_cleaned": "I aspire to become a neurosurgeon, a profession that demands unparalleled precision and dedication. The intricacy of the human brain has always fascinated me, and the prospect of alleviating suffering through surgical intervention is profoundly motivating. This role requires a synthesis of extensive medical knowledge, steady hands, and the ability to make critical decisions under immense pressure. I envision myself working in a cutting-edge hospital, collaborating with a multidisciplinary team to tackle complex neurological disorders. Although the path is arduous, involving years of rigorous training, the potential to restore quality of life to patients is a reward beyond measure. It is a vocation that aligns perfectly with my intellectual curiosity and altruistic nature.",
        "word_count": 115,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR9] Vocabulary: 'aspire', 'neurosurgeon', 'unparalleled precision', 'intricacy', 'alleviating', 'surgical intervention', 'profoundly motivating', 'synthesis', 'extensive', 'critical decisions', 'immense pressure', 'envision', 'cutting-edge', 'multidisciplinary', 'neurological disorders', 'arduous', 'rigorous', 'restore', 'vocation', 'aligns', 'altruistic'. Extremely precise and sophisticated. >Band 8: Wide range of vocabulary. **Idiom present:** Yes ('beyond measure').",
        "grammar_reason": "[GRA9] Full range of structures used naturally. 'A profession that demands...' (Appositive + Relative). 'The prospect of alleviating...' (Noun phrase). 'Collaborating with...' (Participle phrase). 'Although the path is arduous...' (Concessive clause). Error-free. >Band 8: Native-like control.",
        "vocabulary": 9,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a job you would like to have.\n\nTranscript: I aspire to become a neurosurgeon, a profession that demands unparalleled precision and dedication. The intricacy of the human brain has always fascinated me, and the prospect of alleviating suffering through surgical intervention is profoundly motivating. This role requires a synthesis of extensive medical knowledge, steady hands, and the ability to make critical decisions under immense pressure. I envision myself working in a cutting-edge hospital, collaborating with a multidisciplinary team to tackle complex neurological disorders. Although the path is arduous, involving years of rigorous training, the potential to restore quality of life to patients is a reward beyond measure. It is a vocation that aligns perfectly with my intellectual curiosity and altruistic nature.\n\nWord Count: 115 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 9\n\n**Reasoning:** [LR9] Uses 'intricacy', 'alleviating', 'multidisciplinary', 'altruistic'. Extremely precise and sophisticated.\n\n>Band 8: Wide range of vocabulary.\n\n**Idiom present:** Yes ('beyond measure')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Uses a full range of structures naturally and accurately. Appositives and participle phrases are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    },
    # 552. V9/G9 - Place (City)
    {
        "sample_id": "syn_p2_v9_g9_0552",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a city you would like to visit.",
        "transcript_cleaned": "I have a fervent desire to visit Kyoto, the cultural heart of Japan. I am captivated by its reputation as a custodian of traditional architecture, with its myriad temples and shrines. The juxtaposition of ancient wooden structures against the backdrop of changing seasons is visually arresting. I imagine strolling through the Arashiyama Bamboo Grove, immersing myself in the ethereal atmosphere. I am also keen to experience a traditional tea ceremony, appreciating the meticulous attention to detail and Zen aesthetics. Kyoto represents a harmonious blend of history and nature that appeals to my sensibilities. It would be a transformative journey into a world of refined beauty.",
        "word_count": 105,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR9] Vocabulary: 'fervent desire', 'cultural heart', 'captivated', 'custodian', 'myriad', 'juxtaposition', 'backdrop', 'visually arresting', 'strolling', 'immersing', 'ethereal', 'keen', 'tea ceremony', 'meticulous', 'Zen aesthetics', 'harmonious blend', 'sensibilities', 'transformative', 'refined beauty'. Extremely precise and sophisticated. >Band 8: Wide range of vocabulary. **Idiom present:** No.",
        "grammar_reason": "[GRA9] Full range of structures used naturally. 'The cultural heart of Japan' (Appositive). 'With its myriad temples...' (Prepositional phrase). 'Immersing myself...' (Participle phrase). 'Appreciating the meticulous...' (Participle phrase). Error-free. >Band 8: Native-like control.",
        "vocabulary": 9,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a city you would like to visit.\n\nTranscript: I have a fervent desire to visit Kyoto, the cultural heart of Japan. I am captivated by its reputation as a custodian of traditional architecture, with its myriad temples and shrines. The juxtaposition of ancient wooden structures against the backdrop of changing seasons is visually arresting. I imagine strolling through the Arashiyama Bamboo Grove, immersing myself in the ethereal atmosphere. I am also keen to experience a traditional tea ceremony, appreciating the meticulous attention to detail and Zen aesthetics. Kyoto represents a harmonious blend of history and nature that appeals to my sensibilities. It would be a transformative journey into a world of refined beauty.\n\nWord Count: 105 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 9\n\n**Reasoning:** [LR9] Uses 'custodian', 'myriad', 'juxtaposition', 'ethereal', 'sensibilities'. Extremely precise and sophisticated.\n\n>Band 8: Wide range of vocabulary.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Uses a full range of structures naturally and accurately. Participle phrases and appositives are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    },
    # 553. V9/G9 - Event (Festival)
    {
        "sample_id": "syn_p2_v9_g9_0553",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a festival you want to attend.",
        "transcript_cleaned": "I am eager to attend the Rio Carnival in Brazil, widely regarded as the greatest show on Earth. The sheer scale and exuberance of the festivities are legendary. I envision myself amidst the pulsating crowds, swept up in the infectious rhythm of samba music. The parade, featuring elaborate floats and flamboyant costumes, promises to be a sensory overload of color and motion. It is a celebration of life and uninhibited joy that transcends cultural boundaries. Participating in such a collective outpouring of euphoria would be an electrifying experience. It represents the pinnacle of communal celebration.",
        "word_count": 96,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR9] Vocabulary: 'eager', 'widely regarded', 'sheer scale', 'exuberance', 'legendary', 'envision', 'pulsating', 'swept up', 'infectious rhythm', 'elaborate floats', 'flamboyant costumes', 'sensory overload', 'uninhibited', 'transcends', 'cultural boundaries', 'collective outpouring', 'euphoria', 'electrifying', 'pinnacle', 'communal'. Extremely precise and sophisticated. >Band 8: Wide range of vocabulary. **Idiom present:** Yes ('swept up').",
        "grammar_reason": "[GRA9] Full range of structures used naturally. 'Widely regarded as...' (Participle phrase). 'Amidst the pulsating crowds' (Prepositional phrase). 'Featuring elaborate floats...' (Participle phrase). 'Participating in such... would be...' (Gerund subject). Error-free. >Band 8: Native-like control.",
        "vocabulary": 9,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a festival you want to attend.\n\nTranscript: I am eager to attend the Rio Carnival in Brazil, widely regarded as the greatest show on Earth. The sheer scale and exuberance of the festivities are legendary. I envision myself amidst the pulsating crowds, swept up in the infectious rhythm of samba music. The parade, featuring elaborate floats and flamboyant costumes, promises to be a sensory overload of color and motion. It is a celebration of life and uninhibited joy that transcends cultural boundaries. Participating in such a collective outpouring of euphoria would be an electrifying experience. It represents the pinnacle of communal celebration.\n\nWord Count: 96 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 9\n\n**Reasoning:** [LR9] Uses 'exuberance', 'flamboyant', 'uninhibited', 'transcends', 'euphoria'. Extremely precise and sophisticated.\n\n>Band 8: Wide range of vocabulary.\n\n**Idiom present:** Yes ('swept up')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Uses a full range of structures naturally and accurately. Gerund subjects and participle phrases are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    },
    # 554. V9/G9 - Object (Old)
    {
        "sample_id": "syn_p2_v9_g9_0554",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe an old object you have.",
        "transcript_cleaned": "I possess a vintage typewriter that belonged to my great-grandfather, a cherished heirloom. It is a mechanical marvel from the mid-20th century, encased in a sturdy metal frame. Despite its age, the keys still strike the ribbon with a satisfying clack, producing crisp, ink-stained letters. I often marvel at the tactile experience of writing on it, which forces a deliberate pace of thought. It serves as a tangible link to a bygone era of analog communication. Preserving this artifact allows me to honor my family's literary history. It is a testament to the durability of old-world craftsmanship.",
        "word_count": 98,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR9] Vocabulary: 'possess', 'vintage', 'cherished heirloom', 'mechanical marvel', 'encased', 'sturdy', 'strike', 'satisfying clack', 'crisp', 'tactile', 'deliberate pace', 'tangible link', 'bygone era', 'analog', 'preserving', 'artifact', 'honor', 'literary history', 'testament', 'durability', 'old-world craftsmanship'. Extremely precise and sophisticated. >Band 8: Wide range of vocabulary. **Idiom present:** Yes ('bygone era').",
        "grammar_reason": "[GRA9] Full range of structures used naturally. 'That belonged to...' (Relative clause). 'Encased in a sturdy metal frame' (Participle phrase). 'Producing crisp...' (Participle phrase). 'Which forces a deliberate pace' (Relative clause). Error-free. >Band 8: Native-like control.",
        "vocabulary": 9,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe an old object you have.\n\nTranscript: I possess a vintage typewriter that belonged to my great-grandfather, a cherished heirloom. It is a mechanical marvel from the mid-20th century, encased in a sturdy metal frame. Despite its age, the keys still strike the ribbon with a satisfying clack, producing crisp, ink-stained letters. I often marvel at the tactile experience of writing on it, which forces a deliberate pace of thought. It serves as a tangible link to a bygone era of analog communication. Preserving this artifact allows me to honor my family's literary history. It is a testament to the durability of old-world craftsmanship.\n\nWord Count: 98 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 9\n\n**Reasoning:** [LR9] Uses 'heirloom', 'tactile', 'deliberate', 'analog', 'craftsmanship'. Extremely precise and sophisticated.\n\n>Band 8: Wide range of vocabulary.\n\n**Idiom present:** Yes ('bygone era')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Uses a full range of structures naturally and accurately. Participle phrases and relative clauses are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    },
    # 555. V9/G9 - Person (Friend)
    {
        "sample_id": "syn_p2_v9_g9_0555",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a friend who is intelligent.",
        "transcript_cleaned": "I am fortunate to have a friend named David, who is a veritable polymath. He possesses an insatiable curiosity that drives him to explore diverse fields, from astrophysics to ancient history. His ability to synthesize complex information and explain it lucidly is nothing short of remarkable. We often engage in stimulating debates that challenge my preconceived notions. Despite his intellectual prowess, he remains humble and approachable. He utilizes his knowledge to solve practical problems, demonstrating a pragmatic application of his intelligence. His company is intellectually invigorating, constantly pushing me to expand my own horizons.",
        "word_count": 94,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR9] Vocabulary: 'fortunate', 'veritable polymath', 'possesses', 'insatiable curiosity', 'diverse fields', 'synthesize', 'lucidly', 'remarkable', 'stimulating debates', 'preconceived notions', 'intellectual prowess', 'humble', 'approachable', 'utilizes', 'pragmatic application', 'invigorating', 'expand horizons'. Extremely precise and sophisticated. >Band 8: Wide range of vocabulary. **Idiom present:** Yes ('nothing short of').",
        "grammar_reason": "[GRA9] Full range of structures used naturally. 'Who is a veritable polymath' (Relative clause). 'That drives him to explore...' (Relative clause). 'Demonstrating a pragmatic application...' (Participle phrase). 'Pushing me to expand...' (Participle phrase). Error-free. >Band 8: Native-like control.",
        "vocabulary": 9,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a friend who is intelligent.\n\nTranscript: I am fortunate to have a friend named David, who is a veritable polymath. He possesses an insatiable curiosity that drives him to explore diverse fields, from astrophysics to ancient history. His ability to synthesize complex information and explain it lucidly is nothing short of remarkable. We often engage in stimulating debates that challenge my preconceived notions. Despite his intellectual prowess, he remains humble and approachable. He utilizes his knowledge to solve practical problems, demonstrating a pragmatic application of his intelligence. His company is intellectually invigorating, constantly pushing me to expand my own horizons.\n\nWord Count: 94 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 9\n\n**Reasoning:** [LR9] Uses 'polymath', 'insatiable', 'synthesize', 'lucidly', 'prowess', 'pragmatic'. Extremely precise and sophisticated.\n\n>Band 8: Wide range of vocabulary.\n\n**Idiom present:** Yes ('nothing short of')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Uses a full range of structures naturally and accurately. Relative clauses and participle phrases are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    },
    # 556. V9/G9 - Activity (Skill)
    {
        "sample_id": "syn_p2_v9_g9_0556",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a skill you have learned.",
        "transcript_cleaned": "I recently acquired the skill of coding in Python, a journey that has been intellectually rigorously yet rewarding. It involved mastering the syntax and logic required to communicate instructions to a machine. Initially, debugging errors felt like solving a cryptic puzzle, frustrating but addictive. I persevered, driven by the desire to automate mundane tasks and analyze data. The ability to build functional programs from scratch has empowered me significantly. It has sharpened my problem-solving faculties and taught me to think algorithmically. This proficiency opens up a plethora of opportunities in the digital economy.",
        "word_count": 94,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR9] Vocabulary: 'acquired', 'coding', 'intellectually rigorously', 'rewarding', 'mastering', 'syntax', 'communicate instructions', 'debugging', 'cryptic puzzle', 'addictive', 'persevered', 'automate', 'mundane', 'analyze', 'functional programs', 'scratch', 'empowered', 'sharpened', 'faculties', 'algorithmically', 'proficiency', 'plethora'. Extremely precise and sophisticated. >Band 8: Wide range of vocabulary. **Idiom present:** No.",
        "grammar_reason": "[GRA9] Full range of structures used naturally. 'A journey that has been...' (Appositive + Relative). 'Required to communicate...' (Participle phrase). 'Driven by the desire...' (Participle phrase). 'From scratch' (Idiomatic phrase). Error-free. >Band 8: Native-like control.",
        "vocabulary": 9,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a skill you have learned.\n\nTranscript: I recently acquired the skill of coding in Python, a journey that has been intellectually rigorously yet rewarding. It involved mastering the syntax and logic required to communicate instructions to a machine. Initially, debugging errors felt like solving a cryptic puzzle, frustrating but addictive. I persevered, driven by the desire to automate mundane tasks and analyze data. The ability to build functional programs from scratch has empowered me significantly. It has sharpened my problem-solving faculties and taught me to think algorithmically. This proficiency opens up a plethora of opportunities in the digital economy.\n\nWord Count: 94 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 9\n\n**Reasoning:** [LR9] Uses 'syntax', 'cryptic', 'mundane', 'faculties', 'algorithmically', 'plethora'. Extremely precise and sophisticated.\n\n>Band 8: Wide range of vocabulary.\n\n**Idiom present:** Yes ('from scratch')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Uses a full range of structures naturally and accurately. Participle phrases and relative clauses are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    },
    # 557. V9/G9 - Place (Nature)
    {
        "sample_id": "syn_p2_v9_g9_0557",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a natural place you want to visit.",
        "transcript_cleaned": "I yearn to visit the Aurora Borealis in Norway, a celestial phenomenon of ethereal beauty. The prospect of witnessing the night sky illuminated by dancing ribbons of green and violet is mesmerizing. It is a reminder of the magnetic forces that shield our planet, invisible yet vital. I imagine standing in the snow-covered wilderness, embraced by the profound silence of the Arctic. Such an encounter with the sublime would undoubtedly evoke a deep sense of humility. It represents a communion with the cosmos that I find spiritually compelling.",
        "word_count": 90,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR9] Vocabulary: 'yearn', 'Aurora Borealis', 'celestial phenomenon', 'ethereal beauty', 'prospect', 'witnessing', 'illuminated', 'ribbons', 'mesmerizing', 'magnetic forces', 'shield', 'vital', 'wilderness', 'embraced', 'profound silence', 'encounter', 'sublime', 'undoubtedly', 'evoke', 'humility', 'communion', 'cosmos', 'spiritually compelling'. Extremely precise and sophisticated. >Band 8: Wide range of vocabulary. **Idiom present:** No.",
        "grammar_reason": "[GRA9] Full range of structures used naturally. 'A celestial phenomenon...' (Appositive). 'Illuminated by dancing ribbons' (Participle phrase). 'Embraced by the profound silence' (Participle phrase). 'That I find spiritually compelling' (Relative clause). Error-free. >Band 8: Native-like control.",
        "vocabulary": 9,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a natural place you want to visit.\n\nTranscript: I yearn to visit the Aurora Borealis in Norway, a celestial phenomenon of ethereal beauty. The prospect of witnessing the night sky illuminated by dancing ribbons of green and violet is mesmerizing. It is a reminder of the magnetic forces that shield our planet, invisible yet vital. I imagine standing in the snow-covered wilderness, embraced by the profound silence of the Arctic. Such an encounter with the sublime would undoubtedly evoke a deep sense of humility. It represents a communion with the cosmos that I find spiritually compelling.\n\nWord Count: 90 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 9\n\n**Reasoning:** [LR9] Uses 'yearn', 'celestial', 'ethereal', 'sublime', 'communion'. Extremely precise and sophisticated.\n\n>Band 8: Wide range of vocabulary.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Uses a full range of structures naturally and accurately. Appositives and participle phrases are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    },
    # 558. V9/G9 - Activity (Hobby)
    {
        "sample_id": "syn_p2_v9_g9_0558",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a hobby you have.",
        "transcript_cleaned": "I am an ardent practitioner of mindfulness meditation, a discipline that cultivates mental clarity. It involves training the mind to focus on the present moment, acknowledging thoughts without judgment. I dedicate time each morning to this practice, creating a sanctuary of stillness amidst the daily chaos. It has heightened my emotional intelligence and resilience against stress. The ability to detach from negative thought patterns is liberating. I view it not merely as a relaxation technique but as a profound tool for self-transformation. It has fundamentally altered my perception of reality.",
        "word_count": 92,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR9] Vocabulary: 'ardent practitioner', 'mindfulness meditation', 'discipline', 'cultivates', 'clarity', 'acknowledging', 'judgment', 'dedicate', 'sanctuary', 'stillness', 'chaos', 'heightened', 'emotional intelligence', 'resilience', 'detach', 'negative thought patterns', 'liberating', 'relaxation technique', 'profound tool', 'self-transformation', 'fundamentally altered', 'perception'. Extremely precise and sophisticated. >Band 8: Wide range of vocabulary. **Idiom present:** No.",
        "grammar_reason": "[GRA9] Full range of structures used naturally. 'A discipline that cultivates...' (Appositive + Relative). 'Creating a sanctuary...' (Participle phrase). 'Acknowledging thoughts without judgment' (Participle phrase). 'Not merely... but as...' (Correlative). Error-free. >Band 8: Native-like control.",
        "vocabulary": 9,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a hobby you have.\n\nTranscript: I am an ardent practitioner of mindfulness meditation, a discipline that cultivates mental clarity. It involves training the mind to focus on the present moment, acknowledging thoughts without judgment. I dedicate time each morning to this practice, creating a sanctuary of stillness amidst the daily chaos. It has heightened my emotional intelligence and resilience against stress. The ability to detach from negative thought patterns is liberating. I view it not merely as a relaxation technique but as a profound tool for self-transformation. It has fundamentally altered my perception of reality.\n\nWord Count: 92 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 9\n\n**Reasoning:** [LR9] Uses 'ardent', 'cultivates', 'sanctuary', 'detach', 'perception'. Extremely precise and sophisticated.\n\n>Band 8: Wide range of vocabulary.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Uses a full range of structures naturally and accurately. Participle phrases and correlative structures are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    },
    # 559. V9/G9 - Object (Art)
    {
        "sample_id": "syn_p2_v9_g9_0559",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a sculpture you like.",
        "transcript_cleaned": "I am deeply moved by Michelangelo's 'David', a masterpiece of Renaissance sculpture. The marble statue depicts the biblical hero in a moment of contemplation before his battle with Goliath. The anatomical precision, from the tensed muscles to the protruding veins, is breathtakingly realistic. It embodies the humanist ideal of physical perfection and intellectual strength. Standing before it, one feels the latent energy and determination captured in stone. It is a testament to the artist's unparalleled genius and mastery of the medium. The work evokes a sense of awe that transcends centuries.",
        "word_count": 94,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR9] Vocabulary: 'deeply moved', 'masterpiece', 'Renaissance', 'depicts', 'contemplation', 'anatomical precision', 'tensed muscles', 'protruding veins', 'breathtakingly realistic', 'embodies', 'humanist ideal', 'physical perfection', 'intellectual strength', 'latent energy', 'determination', 'captured', 'testament', 'unparalleled genius', 'mastery', 'medium', 'evokes', 'awe', 'transcends'. Extremely precise and sophisticated. >Band 8: Wide range of vocabulary. **Idiom present:** No.",
        "grammar_reason": "[GRA9] Full range of structures used naturally. 'A masterpiece of...' (Appositive). 'Standing before it...' (Participle phrase). 'Captured in stone' (Participle phrase). 'That transcends centuries' (Relative clause). Error-free. >Band 8: Native-like control.",
        "vocabulary": 9,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a sculpture you like.\n\nTranscript: I am deeply moved by Michelangelo's 'David', a masterpiece of Renaissance sculpture. The marble statue depicts the biblical hero in a moment of contemplation before his battle with Goliath. The anatomical precision, from the tensed muscles to the protruding veins, is breathtakingly realistic. It embodies the humanist ideal of physical perfection and intellectual strength. Standing before it, one feels the latent energy and determination captured in stone. It is a testament to the artist's unparalleled genius and mastery of the medium. The work evokes a sense of awe that transcends centuries.\n\nWord Count: 94 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 9\n\n**Reasoning:** [LR9] Uses 'contemplation', 'anatomical', 'protruding', 'latent', 'transcends'. Extremely precise and sophisticated.\n\n>Band 8: Wide range of vocabulary.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Uses a full range of structures naturally and accurately. Participle phrases and appositives are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    },
    # 560. V9/G9 - Event (Celebration)
    {
        "sample_id": "syn_p2_v9_g9_0560",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a memorable celebration.",
        "transcript_cleaned": "I recently attended a centennial celebration for our local library, a cornerstone of our community. The event was a dignified homage to a century of literacy and learning. It featured a retrospective exhibition showcasing rare manuscripts and archival photographs. I was particularly touched by the testimonials from residents whose lives were transformed by the library's resources. The gala dinner was an elegant affair, facilitating discourse among local intellectuals and dignitaries. It reinforced the vital role of public institutions in fostering civic engagement. Being present for such a historic milestone was a privilege.",
        "word_count": 94,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR9] Vocabulary: 'centennial', 'cornerstone', 'dignified homage', 'literacy', 'retrospective exhibition', 'showcasing', 'manuscripts', 'archival', 'testimonials', 'transformed', 'resources', 'gala dinner', 'elegant affair', 'facilitating discourse', 'intellectuals', 'dignitaries', 'reinforced', 'vital role', 'public institutions', 'fostering', 'civic engagement', 'historic milestone', 'privilege'. Extremely precise and sophisticated. >Band 8: Wide range of vocabulary. **Idiom present:** No.",
        "grammar_reason": "[GRA9] Full range of structures used naturally. 'A cornerstone of our community' (Appositive). 'Showcasing rare manuscripts...' (Participle phrase). 'Whose lives were transformed...' (Relative clause). 'Facilitating discourse...' (Participle phrase). Error-free. >Band 8: Native-like control.",
        "vocabulary": 9,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a memorable celebration.\n\nTranscript: I recently attended a centennial celebration for our local library, a cornerstone of our community. The event was a dignified homage to a century of literacy and learning. It featured a retrospective exhibition showcasing rare manuscripts and archival photographs. I was particularly touched by the testimonials from residents whose lives were transformed by the library's resources. The gala dinner was an elegant affair, facilitating discourse among local intellectuals and dignitaries. It reinforced the vital role of public institutions in fostering civic engagement. Being present for such a historic milestone was a privilege.\n\nWord Count: 94 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 9\n\n**Reasoning:** [LR9] Uses 'cornerstone', 'homage', 'retrospective', 'discourse', 'milestone'. Extremely precise and sophisticated.\n\n>Band 8: Wide range of vocabulary.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Uses a full range of structures naturally and accurately. Appositives and relative clauses are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    }
]

with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
    for sample in samples:
        f.write(json.dumps(sample) + '\n')
