import json

OUTPUT_FILE = "ielts-data/phase3/v76_review_output/synthetic_batches/batch_p2_11.jsonl"

samples = [
    # 541. V9/G8 - Job (Future)
    {
        "sample_id": "syn_p2_v9_g8_0541",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a job you would like to have.",
        "transcript_cleaned": "I aspire to become a bioethicist, a profession that sits at the intersection of medicine, law, and philosophy. This role involves navigating the complex moral dilemmas arising from advancements in biotechnology, such as gene editing and artificial intelligence. I am deeply intrigued by the ethical implications of these technologies and their potential impact on humanity. The job would entail advising policymakers and medical institutions on responsible practices. It requires a synthesis of analytical rigor and compassionate reasoning. I envision myself contributing to the development of frameworks that ensure scientific progress aligns with human values. It is a intellectually stimulating career path that I am eager to pursue.",
        "word_count": 105,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "high", "flexibility": "very_high"},
        "vocab_reason": "[LR9] Vocabulary: 'aspire', 'bioethicist', 'intersection', 'navigating', 'moral dilemmas', 'advancements', 'biotechnology', 'gene editing', 'artificial intelligence', 'intrigued', 'ethical implications', 'entail', 'policymakers', 'institutions', 'synthesis', 'analytical rigor', 'compassionate reasoning', 'envision', 'frameworks', 'aligns', 'intellectually stimulating'. Extremely precise and sophisticated. >Band 8: Wide range of vocabulary. **Idiom present:** No.",
        "grammar_reason": "[GRA8] Wide range of structures used accurately. 'That sits at the intersection...' (Relative clause). 'Arising from advancements...' (Participle phrase). 'Advising policymakers...' (Gerund phrase). 'Ensure scientific progress aligns...' (Noun clause). Error-free. >Band 7: Good control. Not Band 9: Lacks full native-like flexibility.",
        "vocabulary": 9,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a job you would like to have.\n\nTranscript: I aspire to become a bioethicist, a profession that sits at the intersection of medicine, law, and philosophy. This role involves navigating the complex moral dilemmas arising from advancements in biotechnology, such as gene editing and artificial intelligence. I am deeply intrigued by the ethical implications of these technologies and their potential impact on humanity. The job would entail advising policymakers and medical institutions on responsible practices. It requires a synthesis of analytical rigor and compassionate reasoning. I envision myself contributing to the development of frameworks that ensure scientific progress aligns with human values. It is a intellectually stimulating career path that I am eager to pursue.\n\nWord Count: 105 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 9\n\n**Reasoning:** [LR9] Uses 'bioethicist', 'intersection', 'dilemmas', 'synthesis', 'rigor'. Extremely precise and sophisticated.\n\n>Band 8: Wide range of vocabulary.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Wide range of structures used accurately. Participle phrases and noun clauses are well-formed.\n\n>Band 7: Good control.\n\nNot Band 9: Lacks full native-like flexibility.\n\n**Micro flaws identified:**\n- None."
    },
    # 542. V9/G8 - Place (City)
    {
        "sample_id": "syn_p2_v9_g8_0542",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a city you would like to live in.",
        "transcript_cleaned": "I would love to reside in Vienna, a city renowned for its imperial heritage and cultural vibrancy. It is often cited as the world's most livable city, a distinction that stems from its exemplary public services and green spaces. I am captivated by the juxtaposition of Baroque architecture and modern design. The city's coffee house culture, recognized by UNESCO, appeals to my love for intellectual discourse and relaxation. I imagine myself strolling along the Ringstrasse, soaking in the grandeur of the historic buildings. Living in a hub of classical music and art would be an enriching experience for my soul.",
        "word_count": 101,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "high", "flexibility": "very_high"},
        "vocab_reason": "[LR9] Vocabulary: 'reside', 'renowned', 'imperial heritage', 'cultural vibrancy', 'cited', 'livable', 'distinction', 'stems from', 'exemplary', 'captivated', 'juxtaposition', 'Baroque architecture', 'recognized', 'appeals', 'intellectual discourse', 'strolling', 'soaking in', 'grandeur', 'hub', 'enriching'. Extremely precise and sophisticated. >Band 8: Wide range of vocabulary. **Idiom present:** No.",
        "grammar_reason": "[GRA8] Wide range of structures used accurately. 'Renowned for its...' (Participle phrase). 'That stems from...' (Relative clause). 'Recognized by UNESCO' (Participle phrase). 'Living in a hub... would be...' (Gerund subject). Error-free. >Band 7: Good control. Not Band 9: Lacks full native-like flexibility.",
        "vocabulary": 9,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a city you would like to live in.\n\nTranscript: I would love to reside in Vienna, a city renowned for its imperial heritage and cultural vibrancy. It is often cited as the world's most livable city, a distinction that stems from its exemplary public services and green spaces. I am captivated by the juxtaposition of Baroque architecture and modern design. The city's coffee house culture, recognized by UNESCO, appeals to my love for intellectual discourse and relaxation. I imagine myself strolling along the Ringstrasse, soaking in the grandeur of the historic buildings. Living in a hub of classical music and art would be an enriching experience for my soul.\n\nWord Count: 101 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 9\n\n**Reasoning:** [LR9] Uses 'reside', 'vibrancy', 'juxtaposition', 'discourse', 'grandeur'. Extremely precise and sophisticated.\n\n>Band 8: Wide range of vocabulary.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Wide range of structures used accurately. Participle phrases and gerund subjects are well-formed.\n\n>Band 7: Good control.\n\nNot Band 9: Lacks full native-like flexibility.\n\n**Micro flaws identified:**\n- None."
    },
    # 543. V9/G8 - Event (Historical)
    {
        "sample_id": "syn_p2_v9_g8_0543",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a historical period you are interested in.",
        "transcript_cleaned": "I am fascinated by the Renaissance, a period of profound cultural rebirth that bridged the Middle Ages and modern history. It was characterized by a surge of interest in classical learning, art, and humanism. The era produced polymaths like Leonardo da Vinci, whose genius transcended disciplinary boundaries. I am particularly intrigued by the shift from a theocentric worldview to one centered on human potential. The artistic innovations, such as the use of perspective, revolutionized visual representation. Studying this epoch offers insights into the foundations of Western civilization. It was a time when curiosity and creativity flourished, reshaping the course of human progress.",
        "word_count": 103,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "high", "flexibility": "very_high"},
        "vocab_reason": "[LR9] Vocabulary: 'fascinated', 'Renaissance', 'profound', 'rebirth', 'bridged', 'characterized', 'surge', 'classical learning', 'humanism', 'polymaths', 'transcended', 'disciplinary boundaries', 'intrigued', 'theocentric worldview', 'innovations', 'perspective', 'revolutionized', 'visual representation', 'epoch', 'foundations', 'flourished', 'reshaping'. Extremely precise and sophisticated. >Band 8: Wide range of vocabulary. **Idiom present:** No.",
        "grammar_reason": "[GRA8] Wide range of structures used accurately. 'That bridged the Middle Ages' (Relative clause). 'Whose genius transcended...' (Relative clause). 'Centered on human potential' (Participle phrase). 'Studying this epoch offers...' (Gerund subject). Error-free. >Band 7: Good control. Not Band 9: Lacks full native-like flexibility.",
        "vocabulary": 9,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a historical period you are interested in.\n\nTranscript: I am fascinated by the Renaissance, a period of profound cultural rebirth that bridged the Middle Ages and modern history. It was characterized by a surge of interest in classical learning, art, and humanism. The era produced polymaths like Leonardo da Vinci, whose genius transcended disciplinary boundaries. I am particularly intrigued by the shift from a theocentric worldview to one centered on human potential. The artistic innovations, such as the use of perspective, revolutionized visual representation. Studying this epoch offers insights into the foundations of Western civilization. It was a time when curiosity and creativity flourished, reshaping the course of human progress.\n\nWord Count: 103 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 9\n\n**Reasoning:** [LR9] Uses 'polymaths', 'transcended', 'theocentric', 'epoch'. Extremely precise and sophisticated.\n\n>Band 8: Wide range of vocabulary.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Wide range of structures used accurately. Relative clauses and gerund subjects are well-formed.\n\n>Band 7: Good control.\n\nNot Band 9: Lacks full native-like flexibility.\n\n**Micro flaws identified:**\n- None."
    },
    # 544. V9/G8 - Person (Leader)
    {
        "sample_id": "syn_p2_v9_g8_0544",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a leader you admire.",
        "transcript_cleaned": "I deeply respect Nelson Mandela, an iconic figure whose legacy of forgiveness and reconciliation is unparalleled. He endured decades of incarceration for his anti-apartheid activism without succumbing to bitterness. His transition from a prisoner to the president of a unified South Africa is a testament to his indomitable spirit. I am awestruck by his ability to bridge deep racial divides and dismantle systemic oppression peacefully. He exemplified the qualities of a servant leader, prioritizing the well-being of his nation above all else. His philosophy of Ubuntu, emphasizing our shared humanity, resonates powerfully in today's polarized world. He remains a moral compass for leaders everywhere.",
        "word_count": 105,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "high", "flexibility": "very_high"},
        "vocab_reason": "[LR9] Vocabulary: 'deeply respect', 'iconic figure', 'legacy', 'reconciliation', 'unparalleled', 'endured', 'incarceration', 'anti-apartheid', 'succumbing', 'bitterness', 'transition', 'unified', 'testament', 'indomitable spirit', 'awestruck', 'bridge', 'racial divides', 'dismantle', 'systemic oppression', 'exemplified', 'servant leader', 'prioritizing', 'philosophy', 'Ubuntu', 'shared humanity', 'resonates', 'polarized', 'moral compass'. Extremely precise and sophisticated. >Band 8: Wide range of vocabulary. **Idiom present:** Yes ('moral compass').",
        "grammar_reason": "[GRA8] Wide range of structures used accurately. 'Whose legacy... is unparalleled' (Relative clause). 'Without succumbing to bitterness' (Preposition + Gerund). 'Prioritizing the well-being...' (Participle phrase). 'Emphasizing our shared humanity' (Participle phrase). Error-free. >Band 7: Good control. Not Band 9: Lacks full native-like flexibility.",
        "vocabulary": 9,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a leader you admire.\n\nTranscript: I deeply respect Nelson Mandela, an iconic figure whose legacy of forgiveness and reconciliation is unparalleled. He endured decades of incarceration for his anti-apartheid activism without succumbing to bitterness. His transition from a prisoner to the president of a unified South Africa is a testament to his indomitable spirit. I am awestruck by his ability to bridge deep racial divides and dismantle systemic oppression peacefully. He exemplified the qualities of a servant leader, prioritizing the well-being of his nation above all else. His philosophy of Ubuntu, emphasizing our shared humanity, resonates powerfully in today's polarized world. He remains a moral compass for leaders everywhere.\n\nWord Count: 105 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 9\n\n**Reasoning:** [LR9] Uses 'incarceration', 'indomitable', 'systemic', 'exemplified', 'polarized'. Extremely precise and sophisticated.\n\n>Band 8: Wide range of vocabulary.\n\n**Idiom present:** Yes ('moral compass')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Wide range of structures used accurately. Participle phrases and prepositional gerunds are well-formed.\n\n>Band 7: Good control.\n\nNot Band 9: Lacks full native-like flexibility.\n\n**Micro flaws identified:**\n- None."
    },
    # 545. V9/G8 - Object (Art)
    {
        "sample_id": "syn_p2_v9_g8_0545",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a piece of art you like.",
        "transcript_cleaned": "I am mesmerized by 'The Starry Night' by Vincent van Gogh, a masterpiece of Post-Impressionism. The painting depicts a swirling, turbulent night sky over a quiescent village, rendered in bold impasto strokes. I am captivated by the emotional intensity conveyed through the vibrant color palette of blues and yellows. The cypress tree in the foreground acts as a bridge between the terrestrial and the celestial realms. It evokes a sense of awe and melancholy simultaneously. Viewing it offers a glimpse into the artist's tormented yet brilliant psyche. It is a timeless expression of the human connection to the cosmos.",
        "word_count": 101,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "high", "flexibility": "very_high"},
        "vocab_reason": "[LR9] Vocabulary: 'mesmerized', 'masterpiece', 'Post-Impressionism', 'depicts', 'swirling', 'turbulent', 'quiescent', 'rendered', 'bold impasto strokes', 'captivated', 'emotional intensity', 'conveyed', 'vibrant color palette', 'foreground', 'terrestrial', 'celestial realms', 'evokes', 'awe', 'melancholy', 'simultaneously', 'glimpse', 'tormented', 'psyche', 'timeless expression', 'cosmos'. Extremely precise and sophisticated. >Band 8: Wide range of vocabulary. **Idiom present:** No.",
        "grammar_reason": "[GRA8] Wide range of structures used accurately. 'Rendered in bold impasto strokes' (Participle phrase). 'Conveyed through the vibrant...' (Participle phrase). 'Viewing it offers...' (Gerund subject). 'Yet brilliant psyche' (Adjective phrase). Error-free. >Band 7: Good control. Not Band 9: Lacks full native-like flexibility.",
        "vocabulary": 9,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a piece of art you like.\n\nTranscript: I am mesmerized by 'The Starry Night' by Vincent van Gogh, a masterpiece of Post-Impressionism. The painting depicts a swirling, turbulent night sky over a quiescent village, rendered in bold impasto strokes. I am captivated by the emotional intensity conveyed through the vibrant color palette of blues and yellows. The cypress tree in the foreground acts as a bridge between the terrestrial and the celestial realms. It evokes a sense of awe and melancholy simultaneously. Viewing it offers a glimpse into the artist's tormented yet brilliant psyche. It is a timeless expression of the human connection to the cosmos.\n\nWord Count: 101 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 9\n\n**Reasoning:** [LR9] Uses 'quiescent', 'impasto', 'terrestrial', 'psyche'. Extremely precise and sophisticated.\n\n>Band 8: Wide range of vocabulary.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Wide range of structures used accurately. Participle phrases and gerund subjects are well-formed.\n\n>Band 7: Good control.\n\nNot Band 9: Lacks full native-like flexibility.\n\n**Micro flaws identified:**\n- None."
    },
    # 546. V9/G8 - Activity (Skill)
    {
        "sample_id": "syn_p2_v9_g8_0546",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a new skill you want to learn.",
        "transcript_cleaned": "I am eager to acquire the skill of data visualization, which is indispensable in the information age. It involves transforming complex datasets into intuitive graphical representations. I am drawn to the ability to uncover hidden patterns and communicate insights effectively. Mastering tools like Tableau and Python would significantly enhance my analytical capabilities. I envision myself creating compelling narratives that drive data-informed decision-making. The process of distilling raw numbers into visual stories is intellectually satisfying. It represents a fusion of art and science that I find irresistible. Developing this proficiency would be a strategic investment in my future career.",
        "word_count": 98,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "high", "flexibility": "very_high"},
        "vocab_reason": "[LR9] Vocabulary: 'eager', 'acquire', 'data visualization', 'indispensable', 'information age', 'transforming', 'datasets', 'intuitive', 'graphical representations', 'uncover', 'hidden patterns', 'communicate insights', 'mastering', 'analytical capabilities', 'envision', 'compelling narratives', 'data-informed', 'distilling', 'raw numbers', 'visual stories', 'intellectually satisfying', 'fusion', 'irresistible', 'proficiency', 'strategic investment'. Extremely precise and sophisticated. >Band 8: Wide range of vocabulary. **Idiom present:** No.",
        "grammar_reason": "[GRA8] Wide range of structures used accurately. 'Which is indispensable...' (Relative clause). 'Transforming complex datasets...' (Gerund phrase). 'Creating compelling narratives...' (Participle phrase). 'Developing this proficiency would be...' (Gerund subject + Modal). Error-free. >Band 7: Good control. Not Band 9: Lacks full native-like flexibility.",
        "vocabulary": 9,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a new skill you want to learn.\n\nTranscript: I am eager to acquire the skill of data visualization, which is indispensable in the information age. It involves transforming complex datasets into intuitive graphical representations. I am drawn to the ability to uncover hidden patterns and communicate insights effectively. Mastering tools like Tableau and Python would significantly enhance my analytical capabilities. I envision myself creating compelling narratives that drive data-informed decision-making. The process of distilling raw numbers into visual stories is intellectually satisfying. It represents a fusion of art and science that I find irresistible. Developing this proficiency would be a strategic investment in my future career.\n\nWord Count: 98 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 9\n\n**Reasoning:** [LR9] Uses 'indispensable', 'intuitive', 'distilling', 'proficiency'. Extremely precise and sophisticated.\n\n>Band 8: Wide range of vocabulary.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Wide range of structures used accurately. Gerund phrases and participle phrases are well-formed.\n\n>Band 7: Good control.\n\nNot Band 9: Lacks full native-like flexibility.\n\n**Micro flaws identified:**\n- None."
    },
    # 547. V9/G8 - Book (Recommended)
    {
        "sample_id": "syn_p2_v9_g8_0547",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a book you recommend.",
        "transcript_cleaned": "I unequivocally recommend 'Thinking, Fast and Slow' by Daniel Kahneman, a seminal work in behavioral psychology. It elucidates the dichotomy between two systems of thought: the intuitive and the analytical. The book exposes the cognitive biases that plague our decision-making processes. I was astounded by the revelations about how easily our minds can be deceived. Kahneman's insights have profound implications for economics, policy, and personal life. The prose is dense but accessible, filled with illuminating experiments. Reading it was a paradigm-shifting experience that enhanced my critical thinking. It is essential reading for anyone seeking to understand human nature.",
        "word_count": 99,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "high", "flexibility": "very_high"},
        "vocab_reason": "[LR9] Vocabulary: 'unequivocally', 'seminal work', 'behavioral psychology', 'elucidates', 'dichotomy', 'intuitive', 'analytical', 'exposes', 'cognitive biases', 'plague', 'decision-making', 'astounded', 'revelations', 'deceived', 'profound implications', 'dense', 'accessible', 'illuminating', 'paradigm-shifting', 'critical thinking', 'essential'. Extremely precise and sophisticated. >Band 8: Wide range of vocabulary. **Idiom present:** No.",
        "grammar_reason": "[GRA8] Wide range of structures used accurately. 'That plague our decision-making...' (Relative clause). 'About how easily our minds can be deceived' (Noun clause + Passive). 'Filled with illuminating experiments' (Participle phrase). 'Seeking to understand...' (Participle phrase). Error-free. >Band 7: Good control. Not Band 9: Lacks full native-like flexibility.",
        "vocabulary": 9,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a book you recommend.\n\nTranscript: I unequivocally recommend 'Thinking, Fast and Slow' by Daniel Kahneman, a seminal work in behavioral psychology. It elucidates the dichotomy between two systems of thought: the intuitive and the analytical. The book exposes the cognitive biases that plague our decision-making processes. I was astounded by the revelations about how easily our minds can be deceived. Kahneman's insights have profound implications for economics, policy, and personal life. The prose is dense but accessible, filled with illuminating experiments. Reading it was a paradigm-shifting experience that enhanced my critical thinking. It is essential reading for anyone seeking to understand human nature.\n\nWord Count: 99 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 9\n\n**Reasoning:** [LR9] Uses 'unequivocally', 'elucidates', 'dichotomy', 'paradigm-shifting'. Extremely precise and sophisticated.\n\n>Band 8: Wide range of vocabulary.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Wide range of structures used accurately. Relative clauses and participle phrases are well-formed.\n\n>Band 7: Good control.\n\nNot Band 9: Lacks full native-like flexibility.\n\n**Micro flaws identified:**\n- None."
    },
    # 548. V9/G8 - Event (Celebration)
    {
        "sample_id": "syn_p2_v9_g8_0548",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a celebration you attended.",
        "transcript_cleaned": "I attended a Golden Jubilee celebration for my university, which was a momentous and dignified occasion. It marked fifty years of academic excellence and scholarly contribution. The campus was adorned with festive banners and illuminated by thousands of fairy lights. The itinerary included speeches by distinguished alumni and a retrospective exhibition. I was particularly moved by the keynote address, which highlighted the transformative power of education. The gala dinner was a lavish affair, facilitating networking among generations of graduates. It fostered a palpable sense of pride and institutional loyalty. Being part of this historic milestone was truly an honor.",
        "word_count": 99,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "high", "flexibility": "very_high"},
        "vocab_reason": "[LR9] Vocabulary: 'Golden Jubilee', 'momentous', 'dignified', 'occasion', 'academic excellence', 'scholarly contribution', 'adorned', 'illuminated', 'itinerary', 'distinguished alumni', 'retrospective exhibition', 'keynote address', 'highlighted', 'transformative power', 'gala dinner', 'lavish affair', 'facilitating', 'fostered', 'palpable', 'institutional loyalty', 'historic milestone'. Extremely precise and sophisticated. >Band 8: Wide range of vocabulary. **Idiom present:** No.",
        "grammar_reason": "[GRA8] Wide range of structures used accurately. 'Which was a momentous...' (Relative clause). 'Adorned with festive banners...' (Participle phrase). 'Which highlighted the transformative power' (Relative clause). 'Being part of this... was...' (Gerund subject). Error-free. >Band 7: Good control. Not Band 9: Lacks full native-like flexibility.",
        "vocabulary": 9,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a celebration you attended.\n\nTranscript: I attended a Golden Jubilee celebration for my university, which was a momentous and dignified occasion. It marked fifty years of academic excellence and scholarly contribution. The campus was adorned with festive banners and illuminated by thousands of fairy lights. The itinerary included speeches by distinguished alumni and a retrospective exhibition. I was particularly moved by the keynote address, which highlighted the transformative power of education. The gala dinner was a lavish affair, facilitating networking among generations of graduates. It fostered a palpable sense of pride and institutional loyalty. Being part of this historic milestone was truly an honor.\n\nWord Count: 99 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 9\n\n**Reasoning:** [LR9] Uses 'momentous', 'retrospective', 'palpable', 'milestone'. Extremely precise and sophisticated.\n\n>Band 8: Wide range of vocabulary.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Wide range of structures used accurately. Relative clauses and participle phrases are well-formed.\n\n>Band 7: Good control.\n\nNot Band 9: Lacks full native-like flexibility.\n\n**Micro flaws identified:**\n- None."
    },
    # 549. V9/G8 - Place (Nature)
    {
        "sample_id": "syn_p2_v9_g8_0549",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a natural landscape you like.",
        "transcript_cleaned": "I am captivated by the stark beauty of the Sahara Desert, a landscape of infinite vastness. The rolling dunes, sculpted by the wind, create a mesmerizing interplay of light and shadow. It is an environment of extremes, where scorching heat gives way to freezing nights. I am drawn to the profound silence and solitude it offers, far from the cacophony of civilization. The clear night sky, unpolluted by artificial light, reveals a breathtaking tapestry of stars. This pristine wilderness evokes a sense of humility and awe. It is a testament to nature's raw and untamed power.",
        "word_count": 98,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "high", "flexibility": "very_high"},
        "vocab_reason": "[LR9] Vocabulary: 'captivated', 'stark beauty', 'infinite vastness', 'rolling dunes', 'sculpted', 'mesmerizing interplay', 'extremes', 'scorching heat', 'freezing', 'drawn to', 'profound silence', 'solitude', 'cacophony', 'civilization', 'unpolluted', 'artificial light', 'breathtaking tapestry', 'pristine wilderness', 'evokes', 'humility', 'awe', 'testament', 'raw', 'untamed'. Extremely precise and sophisticated. >Band 8: Wide range of vocabulary. **Idiom present:** No.",
        "grammar_reason": "[GRA8] Wide range of structures used accurately. 'Sculpted by the wind' (Participle phrase). 'Where scorching heat gives way...' (Relative clause). 'Unpolluted by artificial light' (Participle phrase). 'Reveals a breathtaking tapestry' (Verb phrase). Error-free. >Band 7: Good control. Not Band 9: Lacks full native-like flexibility.",
        "vocabulary": 9,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a natural landscape you like.\n\nTranscript: I am captivated by the stark beauty of the Sahara Desert, a landscape of infinite vastness. The rolling dunes, sculpted by the wind, create a mesmerizing interplay of light and shadow. It is an environment of extremes, where scorching heat gives way to freezing nights. I am drawn to the profound silence and solitude it offers, far from the cacophony of civilization. The clear night sky, unpolluted by artificial light, reveals a breathtaking tapestry of stars. This pristine wilderness evokes a sense of humility and awe. It is a testament to nature's raw and untamed power.\n\nWord Count: 98 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 9\n\n**Reasoning:** [LR9] Uses 'stark', 'sculpted', 'cacophony', 'untamed'. Extremely precise and sophisticated.\n\n>Band 8: Wide range of vocabulary.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Wide range of structures used accurately. Participle phrases and relative clauses are well-formed.\n\n>Band 7: Good control.\n\nNot Band 9: Lacks full native-like flexibility.\n\n**Micro flaws identified:**\n- None."
    },
    # 550. V9/G8 - Activity (Relax)
    {
        "sample_id": "syn_p2_v9_g8_0550",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a relaxing activity you enjoy.",
        "transcript_cleaned": "I find immense solace in the practice of forest bathing, a Japanese concept known as Shinrin-yoku. It involves immersing oneself in a forest atmosphere to enhance well-being. I wander aimlessly through the woods, engaging all my senses to connect with the environment. The inhalation of phytoncides, emitted by trees, is scientifically proven to reduce stress hormones. I observe the fractal patterns in the leaves and listen to the rustling wind. This mindful communion with nature acts as a powerful antidote to digital burnout. It rejuvenates my spirit and restores my cognitive equilibrium. It is a therapeutic ritual I cherish deeply.",
        "word_count": 101,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "high", "flexibility": "very_high"},
        "vocab_reason": "[LR9] Vocabulary: 'immense solace', 'forest bathing', 'concept', 'immersing', 'enhance', 'well-being', 'wander aimlessly', 'engaging', 'inhalation', 'phytoncides', 'emitted', 'scientifically proven', 'reduce stress hormones', 'fractal patterns', 'rustling', 'mindful communion', 'antidote', 'digital burnout', 'rejuvenates', 'restores', 'cognitive equilibrium', 'therapeutic ritual', 'cherish'. Extremely precise and sophisticated. >Band 8: Wide range of vocabulary. **Idiom present:** No.",
        "grammar_reason": "[GRA8] Wide range of structures used accurately. 'Known as Shinrin-yoku' (Participle phrase). 'Involves immersing oneself...' (Gerund phrase). 'Emitted by trees' (Participle phrase). 'Proven to reduce...' (Infinitive phrase). Error-free. >Band 7: Good control. Not Band 9: Lacks full native-like flexibility.",
        "vocabulary": 9,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a relaxing activity you enjoy.\n\nTranscript: I find immense solace in the practice of forest bathing, a Japanese concept known as Shinrin-yoku. It involves immersing oneself in a forest atmosphere to enhance well-being. I wander aimlessly through the woods, engaging all my senses to connect with the environment. The inhalation of phytoncides, emitted by trees, is scientifically proven to reduce stress hormones. I observe the fractal patterns in the leaves and listen to the rustling wind. This mindful communion with nature acts as a powerful antidote to digital burnout. It rejuvenates my spirit and restores my cognitive equilibrium. It is a therapeutic ritual I cherish deeply.\n\nWord Count: 101 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 9\n\n**Reasoning:** [LR9] Uses 'solace', 'phytoncides', 'communion', 'equilibrium'. Extremely precise and sophisticated.\n\n>Band 8: Wide range of vocabulary.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Wide range of structures used accurately. Participle phrases and gerund phrases are well-formed.\n\n>Band 7: Good control.\n\nNot Band 9: Lacks full native-like flexibility.\n\n**Micro flaws identified:**\n- None."
    }
]

with open(OUTPUT_FILE, 'a', encoding='utf-8') as f:
    for sample in samples:
        f.write(json.dumps(sample) + '\n')
