import json

OUTPUT_FILE = "ielts-data/phase3/v76_review_output/synthetic_batches/batch_p2_10.jsonl"

samples = [
    # 471. V6/G7 - Book (Favorite)
    {
        "sample_id": "syn_p2_v6_g7_0471",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a book that had a major influence on you.",
        "transcript_cleaned": "I would like to talk about a book called 'The Little Prince', which I read when I was a teenager. It is a famous story about a young prince who travels to different planets. Although it looks like a children's book, it has a deep meaning. The story taught me that what is essential is invisible to the eye. This means that we should look at people's hearts, not just their appearance. If I had not read this book, I might not have understood the importance of friendship. It is written in a simple style, but the message is powerful. I have recommended it to many of my friends.",
        "word_count": 105,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR6] Vocabulary: 'famous story', 'travels', 'planets', 'deep meaning', 'essential', 'invisible', 'appearance', 'importance', 'friendship', 'style', 'message', 'recommended'. Adequate range. >Band 5: Uses some less common words ('essential', 'invisible'). Not Band 7: Lacks depth and style.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'Which I read when I was a teenager' (Relative clause). 'Who travels to different planets' (Relative clause). 'That what is essential is invisible' (Noun clause). 'If I had not read..., I might not have understood...' (Third conditional). Accurate.",
        "vocabulary": 6,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a book that had a major influence on you.\n\nTranscript: I would like to talk about a book called 'The Little Prince', which I read when I was a teenager. It is a famous story about a young prince who travels to different planets. Although it looks like a children's book, it has a deep meaning. The story taught me that what is essential is invisible to the eye. This means that we should look at people's hearts, not just their appearance. If I had not read this book, I might not have understood the importance of friendship. It is written in a simple style, but the message is powerful. I have recommended it to many of my friends.\n\nWord Count: 105 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses relevant vocabulary: 'essential', 'invisible', 'appearance'. Clear meaning.\n\n>Band 5: Good range.\n\nNot Band 7: Lacks sophisticated phrasing.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses a variety of complex structures correctly (relative clauses, third conditional). Sentences are error-free.\n\n>Band 6: More flexibility and accuracy.\n\nNot Band 8: Not highly sophisticated.\n\n**Micro flaws identified:**\n- None."
    },
    # 472. V6/G7 - Place (Historic)
    {
        "sample_id": "syn_p2_v6_g7_0472",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a historic place you visited.",
        "transcript_cleaned": "I visited the Great Wall of China a few years ago, which is a very famous landmark. It was built many centuries ago to protect the country. The wall is incredibly long, stretching across mountains and valleys. Walking on it was tiring because it is very steep in some parts. However, the view from the top was spectacular. I could see the landscape for miles. I was amazed by how the ancient people built such a massive structure without modern machines. It is a place that everyone should visit at least once. Being there made me feel connected to history.",
        "word_count": 100,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR6] Vocabulary: 'landmark', 'protect', 'stretching', 'valleys', 'steep', 'spectacular', 'landscape', 'amazed', 'ancient', 'massive structure', 'modern machines', 'connected'. Adequate range. >Band 5: Uses descriptive words ('spectacular', 'massive'). Not Band 7: Vocabulary is standard.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'Which is a very famous landmark' (Relative clause). 'Stretching across mountains...' (Participle phrase). 'Because it is very steep...' (Reason clause). 'How the ancient people built...' (Noun clause). Accurate.",
        "vocabulary": 6,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a historic place you visited.\n\nTranscript: I visited the Great Wall of China a few years ago, which is a very famous landmark. It was built many centuries ago to protect the country. The wall is incredibly long, stretching across mountains and valleys. Walking on it was tiring because it is very steep in some parts. However, the view from the top was spectacular. I could see the landscape for miles. I was amazed by how the ancient people built such a massive structure without modern machines. It is a place that everyone should visit at least once. Being there made me feel connected to history.\n\nWord Count: 100 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses descriptive vocabulary: 'spectacular', 'massive', 'landscape'. Good range.\n\n>Band 5: Adequate vocabulary.\n\nNot Band 7: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures accurately, including participle phrases and noun clauses. Good grammatical control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Limited variety.\n\n**Micro flaws identified:**\n- None."
    },
    # 473. V6/G7 - Activity (Project)
    {
        "sample_id": "syn_p2_v6_g7_0473",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a project you worked on.",
        "transcript_cleaned": "I worked on a group project at university last semester. We had to create a marketing plan for a new product. It was challenging because we had a tight deadline. My role was to research the target market. I spent a lot of time analyzing data and writing reports. Although we had some disagreements, we managed to work together effectively. The presentation we gave was successful, and we got a high grade. This project taught me the importance of teamwork and communication. I am proud of what we achieved.",
        "word_count": 89,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR6] Vocabulary: 'group project', 'marketing plan', 'product', 'challenging', 'tight deadline', 'research', 'target market', 'analyzing data', 'reports', 'disagreements', 'effectively', 'presentation', 'high grade', 'teamwork', 'communication'. Adequate range. >Band 5: Uses specific words ('target market', 'deadline'). Not Band 7: Lacks depth.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'Because we had a tight deadline' (Reason clause). 'My role was to research...' (Infinitive phrase). 'Although we had some disagreements...' (Concessive clause). 'The presentation we gave...' (Relative clause). Accurate.",
        "vocabulary": 6,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a project you worked on.\n\nTranscript: I worked on a group project at university last semester. We had to create a marketing plan for a new product. It was challenging because we had a tight deadline. My role was to research the target market. I spent a lot of time analyzing data and writing reports. Although we had some disagreements, we managed to work together effectively. The presentation we gave was successful, and we got a high grade. This project taught me the importance of teamwork and communication. I am proud of what we achieved.\n\nWord Count: 89 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses relevant vocabulary: 'marketing plan', 'deadline', 'analyzing'. Clear meaning.\n\n>Band 5: Good range.\n\nNot Band 7: Lacks sophistication.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures accurately (concessive clauses, relative clauses). Good control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Limited range of complex structures.\n\n**Micro flaws identified:**\n- None."
    },
    # 474. V6/G7 - Person (Neighbor)
    {
        "sample_id": "syn_p2_v6_g7_0474",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a neighbor you like.",
        "transcript_cleaned": "I have a neighbor named Mrs. Smith who lives next door. She is an elderly lady who lives alone. I like her because she is always friendly and cheerful. Whenever I see her in the garden, we have a chat. She loves gardening and has many beautiful flowers. Sometimes, she gives me some vegetables she has grown. I help her with heavy shopping bags when she comes home. It is nice to have good neighbors. If everyone were as kind as her, the world would be a better place.",
        "word_count": 90,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR6] Vocabulary: 'neighbor', 'elderly lady', 'friendly', 'cheerful', 'gardening', 'vegetables', 'shopping bags', 'kind', 'better place'. Adequate range. >Band 5: Clear descriptions. Not Band 7: Vocabulary is standard.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'Who lives next door' (Relative clause). 'Because she is always friendly' (Reason clause). 'She gives me some vegetables she has grown' (Relative clause). 'If everyone were as kind as her...' (Second conditional). Accurate.",
        "vocabulary": 6,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a neighbor you like.\n\nTranscript: I have a neighbor named Mrs. Smith who lives next door. She is an elderly lady who lives alone. I like her because she is always friendly and cheerful. Whenever I see her in the garden, we have a chat. She loves gardening and has many beautiful flowers. Sometimes, she gives me some vegetables she has grown. I help her with heavy shopping bags when she comes home. It is nice to have good neighbors. If everyone were as kind as her, the world would be a better place.\n\nWord Count: 90 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses functional vocabulary: 'elderly', 'cheerful', 'gardening'. Clear meaning.\n\n>Band 5: Good range.\n\nNot Band 7: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures accurately, including second conditional and relative clauses. Error-free sentences.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Limited variety.\n\n**Micro flaws identified:**\n- None."
    },
    # 475. V6/G7 - Event (Wedding)
    {
        "sample_id": "syn_p2_v6_g7_0475",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a wedding you attended.",
        "transcript_cleaned": "I attended my cousin's wedding last year, which was a very grand event. It took place in a large hotel in the city center. The bride wore a stunning white dress, and the groom looked handsome in his suit. There were hundreds of guests there to celebrate with them. The ceremony was beautiful and emotional. After that, we had a delicious dinner with many courses. We danced until late at night. I really enjoyed catching up with my relatives. It was a memorable day for everyone in our family.",
        "word_count": 89,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR6] Vocabulary: 'grand event', 'bride', 'stunning', 'groom', 'handsome', 'guests', 'celebrate', 'ceremony', 'emotional', 'delicious dinner', 'courses', 'catching up', 'relatives', 'memorable'. Adequate range. >Band 5: Uses specific words ('bride', 'groom'). Not Band 7: Lacks sophistication.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'Which was a very grand event' (Relative clause). 'To celebrate with them' (Infinitive of purpose). 'After that, we had...' (Time phrase). 'Until late at night' (Prepositional phrase). Accurate.",
        "vocabulary": 6,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a wedding you attended.\n\nTranscript: I attended my cousin's wedding last year, which was a very grand event. It took place in a large hotel in the city center. The bride wore a stunning white dress, and the groom looked handsome in his suit. There were hundreds of guests there to celebrate with them. The ceremony was beautiful and emotional. After that, we had a delicious dinner with many courses. We danced until late at night. I really enjoyed catching up with my relatives. It was a memorable day for everyone in our family.\n\nWord Count: 89 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses topic words: 'ceremony', 'emotional', 'memorable'. Meaning is clear.\n\n>Band 5: Good range.\n\nNot Band 7: Lacks variety.\n\n**Idiom present:** Yes ('catching up')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures accurately. Relative clauses and time phrases used correctly. Good control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Limited range of complex structures.\n\n**Micro flaws identified:**\n- None."
    },
    # 476. V6/G7 - Object (Technology)
    {
        "sample_id": "syn_p2_v6_g7_0476",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a piece of technology you find difficult to use.",
        "transcript_cleaned": "I find using my new digital camera quite difficult. It has so many buttons and settings that I get confused. Although I read the instruction manual, I still do not understand all the functions. I wanted to take high-quality photos, but they often turn out blurry. My friend, who is a photographer, tried to explain it to me. He said I need to practice more. I think modern technology can be too complicated for ordinary people. I prefer using my phone camera because it is much simpler. I hope I will master this camera eventually.",
        "word_count": 96,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR6] Vocabulary: 'digital camera', 'buttons', 'settings', 'confused', 'instruction manual', 'functions', 'high-quality', 'blurry', 'photographer', 'complicated', 'ordinary people', 'simpler', 'master'. Adequate range. >Band 5: Uses specific words ('manual', 'blurry'). Not Band 7: Lacks depth.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'That I get confused' (Result clause). 'Although I read...' (Concessive clause). 'Who is a photographer' (Relative clause). 'He said I need to practice' (Reported speech). Accurate.",
        "vocabulary": 6,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a piece of technology you find difficult to use.\n\nTranscript: I find using my new digital camera quite difficult. It has so many buttons and settings that I get confused. Although I read the instruction manual, I still do not understand all the functions. I wanted to take high-quality photos, but they often turn out blurry. My friend, who is a photographer, tried to explain it to me. He said I need to practice more. I think modern technology can be too complicated for ordinary people. I prefer using my phone camera because it is much simpler. I hope I will master this camera eventually.\n\nWord Count: 96 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses relevant vocabulary: 'manual', 'blurry', 'complicated'. Clear description.\n\n>Band 5: Good range.\n\nNot Band 7: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures accurately (concessive clauses, reported speech). Sentences are error-free.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Limited variety.\n\n**Micro flaws identified:**\n- None."
    },
    # 477. V6/G7 - Activity (Exercise)
    {
        "sample_id": "syn_p2_v6_g7_0477",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe an exercise you enjoy doing.",
        "transcript_cleaned": "I enjoy swimming, which is a great full-body workout. I go to the local swimming pool twice a week. I usually swim for about an hour to stay fit. I like it because the water makes me feel weightless and relaxed. It is also good for my back, which sometimes hurts from sitting too long. After swimming, I feel refreshed and energetic. I have been swimming since I was a child. I think it is the best exercise for people of all ages. It is a healthy habit that I plan to keep.",
        "word_count": 96,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR6] Vocabulary: 'swimming', 'full-body workout', 'local', 'stay fit', 'weightless', 'relaxed', 'hurts', 'refreshed', 'energetic', 'healthy habit'. Adequate range. >Band 5: Uses specific words ('workout', 'weightless'). Not Band 7: Vocabulary is standard.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'Which is a great full-body workout' (Relative clause). 'To stay fit' (Infinitive of purpose). 'Which sometimes hurts...' (Relative clause). 'Since I was a child' (Time clause). Accurate.",
        "vocabulary": 6,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe an exercise you enjoy doing.\n\nTranscript: I enjoy swimming, which is a great full-body workout. I go to the local swimming pool twice a week. I usually swim for about an hour to stay fit. I like it because the water makes me feel weightless and relaxed. It is also good for my back, which sometimes hurts from sitting too long. After swimming, I feel refreshed and energetic. I have been swimming since I was a child. I think it is the best exercise for people of all ages. It is a healthy habit that I plan to keep.\n\nWord Count: 96 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses topic words: 'workout', 'weightless', 'refreshed'. Meaning is clear.\n\n>Band 5: Adequate vocabulary.\n\nNot Band 7: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures accurately. Includes relative clauses and time clauses. Good control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Limited range of complex structures.\n\n**Micro flaws identified:**\n- None."
    },
    # 478. V6/G7 - Book (Gift)
    {
        "sample_id": "syn_p2_v6_g7_0478",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a book you received as a gift.",
        "transcript_cleaned": "I received a cookbook as a gift from my sister last Christmas. It has many recipes for Italian food, which is my favorite. The book is filled with beautiful photos of the dishes. I was very excited to try cooking some of them. So far, I have made lasagna and tiramisu. They turned out delicious, although the instructions were a bit complicated. I keep the book in my kitchen so I can use it easily. It was a thoughtful gift because she knows I love cooking. I have learned a lot from it.",
        "word_count": 96,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR6] Vocabulary: 'cookbook', 'recipes', 'dishes', 'lasagna', 'tiramisu', 'delicious', 'instructions', 'complicated', 'thoughtful'. Adequate range. >Band 5: Uses specific words ('recipes', 'tiramisu'). Not Band 7: Lacks sophistication.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'Which is my favorite' (Relative clause). 'Filled with beautiful photos' (Participle phrase). 'Although the instructions were...' (Concessive clause). 'So I can use it' (Result clause). Accurate.",
        "vocabulary": 6,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a book you received as a gift.\n\nTranscript: I received a cookbook as a gift from my sister last Christmas. It has many recipes for Italian food, which is my favorite. The book is filled with beautiful photos of the dishes. I was very excited to try cooking some of them. So far, I have made lasagna and tiramisu. They turned out delicious, although the instructions were a bit complicated. I keep the book in my kitchen so I can use it easily. It was a thoughtful gift because she knows I love cooking. I have learned a lot from it.\n\nWord Count: 96 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses topic words: 'recipes', 'instructions', 'thoughtful'. Meaning is clear.\n\n>Band 5: Adequate vocabulary.\n\nNot Band 7: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures accurately. Includes relative clauses and concessive clauses. Good control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Limited variety.\n\n**Micro flaws identified:**\n- None."
    },
    # 479. V6/G7 - Place (Quiet)
    {
        "sample_id": "syn_p2_v6_g7_0479",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a quiet place you know.",
        "transcript_cleaned": "I know a small library in my town that is very quiet. It is located in an old building with high ceilings. I go there when I need to study or read without distractions. The atmosphere is peaceful, and everyone whispers. There are comfortable armchairs where you can sit for hours. I like the smell of old books there. It is a stark contrast to the noisy streets outside. Finding a place like this is rare in a busy city. It is my favorite spot to escape and relax.",
        "word_count": 92,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR6] Vocabulary: 'library', 'ceilings', 'distractions', 'atmosphere', 'peaceful', 'whispers', 'armchairs', 'stark contrast', 'noisy', 'rare', 'escape'. Adequate range. >Band 5: Uses specific words ('distractions', 'whispers'). Not Band 7: Lacks depth.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'That is very quiet' (Relative clause). 'When I need to study' (Time clause). 'Where you can sit' (Relative clause). 'Finding a place like this is...' (Gerund subject). Accurate.",
        "vocabulary": 6,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a quiet place you know.\n\nTranscript: I know a small library in my town that is very quiet. It is located in an old building with high ceilings. I go there when I need to study or read without distractions. The atmosphere is peaceful, and everyone whispers. There are comfortable armchairs where you can sit for hours. I like the smell of old books there. It is a stark contrast to the noisy streets outside. Finding a place like this is rare in a busy city. It is my favorite spot to escape and relax.\n\nWord Count: 92 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses descriptive vocabulary: 'distractions', 'stark contrast', 'rare'. Good range.\n\n>Band 5: Adequate vocabulary.\n\nNot Band 7: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures accurately. Includes relative clauses and gerund subjects. Good control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Limited range of complex structures.\n\n**Micro flaws identified:**\n- None."
    },
    # 480. V6/G7 - Person (Child)
    {
        "sample_id": "syn_p2_v6_g7_0480",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a child that made you laugh.",
        "transcript_cleaned": "I want to describe my nephew, who is three years old. He is a very energetic and curious boy. Last week, he tried to put on my shoes, which were much too big for him. He walked around the room stumbling, pretending to be a giant. It looked so funny that everyone burst out laughing. He has a great imagination and tells silly stories. Although he can be naughty sometimes, he is very lovable. His innocence and joy are contagious. Spending time with him always cheers me up.",
        "word_count": 89,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR6] Vocabulary: 'nephew', 'energetic', 'curious', 'stumbling', 'pretending', 'giant', 'burst out laughing', 'imagination', 'silly', 'naughty', 'lovable', 'innocence', 'contagious', 'cheers me up'. Adequate range. >Band 5: Uses specific words ('stumbling', 'contagious'). Not Band 7: Vocabulary is standard.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'Who is three years old' (Relative clause). 'Which were much too big' (Relative clause). 'Pretending to be a giant' (Participle phrase). 'Although he can be naughty...' (Concessive clause). Accurate.",
        "vocabulary": 6,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a child that made you laugh.\n\nTranscript: I want to describe my nephew, who is three years old. He is a very energetic and curious boy. Last week, he tried to put on my shoes, which were much too big for him. He walked around the room stumbling, pretending to be a giant. It looked so funny that everyone burst out laughing. He has a great imagination and tells silly stories. Although he can be naughty sometimes, he is very lovable. His innocence and joy are contagious. Spending time with him always cheers me up.\n\nWord Count: 89 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses descriptive vocabulary: 'stumbling', 'contagious', 'cheers me up'. Good range.\n\n>Band 5: Adequate vocabulary.\n\nNot Band 7: Lacks variety.\n\n**Idiom present:** Yes ('burst out laughing')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures accurately. Includes relative clauses and participle phrases. Good control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Limited range of complex structures.\n\n**Micro flaws identified:**\n- None."
    }
]

with open(OUTPUT_FILE, 'a', encoding='utf-8') as f:
    for sample in samples:
        f.write(json.dumps(sample) + '\n')
