import json

OUTPUT_FILE = "ielts-data/phase3/v76_review_output/synthetic_batches/batch_p2_12.jsonl"

samples = [
    # 591. V8/G6 - Event (Success)
    {
        "sample_id": "syn_p2_v8_g6_0591",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a personal achievement.",
        "transcript_cleaned": "Completing a marathon was a grueling yet rewarding achievement for me. I had to adhere to a strict training regimen for six months. It requiring immense physical stamina and mental fortitude. I battled fatigue and self-doubt throughout the process. Crossing the finish line was a euphoric moment. I was proud of my perseverance and determination. The camaraderie among the runners were inspiring. It taught me that I can overcoming any obstacle. This accomplishment have boosted my self-confidence significantly. It is a milestone I will cherish forever.",
        "word_count": 86,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'It requiring' should be 'It required'", "agreement: 'runners were' should be 'was'", "grammar: 'can overcoming' should be 'can overcome'", "agreement: 'accomplishment have' should be 'has'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR8] Vocabulary: 'grueling', 'rewarding', 'achievement', 'adhere', 'regimen', 'immense', 'stamina', 'fortitude', 'battled', 'fatigue', 'euphoric', 'perseverance', 'determination', 'camaraderie', 'obstacle', 'boosted', 'self-confidence', 'milestone', 'cherish'. Very sophisticated. >Band 7: Precise vocabulary. Not Band 9: Errors in usage.",
        "grammar_reason": "[GRA6] Uses complex structures but has frequent errors. Verb form errors ('requiring', 'overcoming'). Agreement errors ('runners were', 'accomplishment have'). >Band 5: Attempts complex sentences. Not Band 7: Errors are frequent.",
        "vocabulary": 8,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a personal achievement.\n\nTranscript: Completing a marathon was a grueling yet rewarding achievement for me. I had to adhere to a strict training regimen for six months. It requiring immense physical stamina and mental fortitude. I battled fatigue and self-doubt throughout the process. Crossing the finish line was a euphoric moment. I was proud of my perseverance and determination. The camaraderie among the runners were inspiring. It taught me that I can overcoming any obstacle. This accomplishment have boosted my self-confidence significantly. It is a milestone I will cherish forever.\n\nWord Count: 86 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses sophisticated vocabulary: 'grueling', 'regimen', 'fortitude', 'euphoric'. Precise.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Errors affect accuracy.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Frequent errors in verb forms and agreement ('requiring', 'runners were'). Complex structures used but flawed.\n\n>Band 5: Complex sentences attempted.\n\nNot Band 7: Systematic errors.\n\n**Micro flaws identified:**\n- 'It requiring' should be 'It required'\n- 'runners were' should be 'runners was'\n- 'can overcoming' should be 'can overcome'\n- 'accomplishment have' should be 'accomplishment has'"
    },
    # 592. V8/G6 - Place (Home)
    {
        "sample_id": "syn_p2_v8_g6_0592",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe your dream house.",
        "transcript_cleaned": "I envision my dream house as a sustainable eco-villa nestled in the mountains. It would be constructed from renewable materials like bamboo and recycled glass. I desire a minimalist interior that promoting tranquility and mindfulness. Large panoramic windows would offering breathtaking views of the surrounding landscape. I am keen on integrating smart home technology to optimize energy efficiency. A solar-powered heating system are essential. The garden would be a sanctuary for native flora and fauna. Living there would be a blissful escape from the rat race.",
        "word_count": 86,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'that promoting' should be 'promotes'", "grammar: 'would offering' should be 'would offer'", "agreement: 'system are' should be 'is'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR8] Vocabulary: 'envision', 'sustainable', 'eco-villa', 'nestled', 'constructed', 'renewable materials', 'minimalist', 'tranquility', 'mindfulness', 'panoramic', 'breathtaking', 'integrating', 'optimize', 'efficiency', 'solar-powered', 'sanctuary', 'native flora', 'fauna', 'blissful', 'rat race'. Very sophisticated. >Band 7: Precise vocabulary. Not Band 9: Errors in usage.",
        "grammar_reason": "[GRA6] Uses complex structures but has frequent errors. Verb form errors ('promoting', 'offering'). Agreement error ('system are'). >Band 5: Attempts complex sentences. Not Band 7: Errors are noticeable.",
        "vocabulary": 8,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe your dream house.\n\nTranscript: I envision my dream house as a sustainable eco-villa nestled in the mountains. It would be constructed from renewable materials like bamboo and recycled glass. I desire a minimalist interior that promoting tranquility and mindfulness. Large panoramic windows would offering breathtaking views of the surrounding landscape. I am keen on integrating smart home technology to optimize energy efficiency. A solar-powered heating system are essential. The garden would be a sanctuary for native flora and fauna. Living there would be a blissful escape from the rat race.\n\nWord Count: 86 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses sophisticated vocabulary: 'envision', 'sustainable', 'panoramic', 'sanctuary'. Precise.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Errors affect accuracy.\n\n**Idiom present:** Yes ('rat race')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Frequent errors in verb forms ('promoting', 'offering'). Complex structures used but flawed.\n\n>Band 5: Complex sentences attempted.\n\nNot Band 7: Systematic errors.\n\n**Micro flaws identified:**\n- 'that promoting' should be 'promotes'\n- 'would offering' should be 'would offer'\n- 'system are' should be 'is'"
    },
    # 593. V8/G6 - Activity (Study)
    {
        "sample_id": "syn_p2_v8_g6_0593",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a subject you found interesting.",
        "transcript_cleaned": "I found psychology to be an intriguing subject during my university years. It delves into the complexities of human behavior and cognition. I was fascinated by the theories regarding personality development. Learning about cognitive biases were eye-opening. I enjoying conducting experiments to test hypotheses. The coursework requiring critical thinking and analytical skills. It provided me with valuable insights into my own motivations. Although the statistics module was challenging, I persevering. It is a field that constantly evolving, which makes it exciting.",
        "word_count": 81,
        "response_type": "long_turn",
        "micro_flaws": ["agreement: 'biases were' should be 'was' (learning was)", "tense: 'I enjoying' should be 'enjoyed'", "tense: 'coursework requiring' should be 'required'", "tense: 'I persevering' should be 'persevered'", "grammar: 'that constantly evolving' should be 'that is constantly evolving'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR8] Vocabulary: 'intriguing', 'delves into', 'complexities', 'cognition', 'fascinated', 'theories', 'personality development', 'cognitive biases', 'eye-opening', 'experiments', 'hypotheses', 'critical thinking', 'analytical skills', 'insights', 'motivations', 'statistics', 'persevering', 'evolving'. Very sophisticated. >Band 7: Precise vocabulary. Not Band 9: Errors in usage.",
        "grammar_reason": "[GRA6] Uses complex structures but has frequent errors. Verb form errors ('enjoying', 'requiring', 'persevering'). Agreement error ('biases were'). >Band 5: Attempts complex sentences. Not Band 7: Errors are noticeable.",
        "vocabulary": 8,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a subject you found interesting.\n\nTranscript: I found psychology to be an intriguing subject during my university years. It delves into the complexities of human behavior and cognition. I was fascinated by the theories regarding personality development. Learning about cognitive biases were eye-opening. I enjoying conducting experiments to test hypotheses. The coursework requiring critical thinking and analytical skills. It provided me with valuable insights into my own motivations. Although the statistics module was challenging, I persevering. It is a field that constantly evolving, which makes it exciting.\n\nWord Count: 81 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses sophisticated vocabulary: 'intriguing', 'delves into', 'cognition', 'hypotheses'. Precise.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Errors affect accuracy.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Frequent errors in verb forms ('enjoying', 'requiring'). Complex structures used but flawed.\n\n>Band 5: Complex sentences attempted.\n\nNot Band 7: Systematic errors.\n\n**Micro flaws identified:**\n- 'biases were' should be 'was'\n- 'I enjoying' should be 'I enjoyed'\n- 'coursework requiring' should be 'required'\n- 'I persevering' should be 'persevered'\n- 'that constantly evolving' should be 'that is constantly evolving'"
    },
    # 594. V8/G6 - Object (Technology)
    {
        "sample_id": "syn_p2_v8_g6_0594",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a useful app on your phone.",
        "transcript_cleaned": "I rely heavily on a productivity app called Notion, which is an all-in-one workspace. It allows me to organize my tasks, notes, and projects seamlessly. The interface is intuitive, making it easy to navigate. I customizing the layout to suit my workflow. It integrating with other tools, which boost efficiency. I use it to track my habits and goals. The collaboration features is excellent for team projects. It has streamlined my life and reduced digital clutter. I cannot imagine managing my schedule without it.",
        "word_count": 86,
        "response_type": "long_turn",
        "micro_flaws": ["tense: 'I customizing' should be 'customize'", "grammar: 'It integrating' should be 'It integrates'", "agreement: 'which boost' should be 'boosts'", "agreement: 'features is' should be 'are'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR8] Vocabulary: 'rely heavily', 'productivity app', 'workspace', 'organize', 'seamlessly', 'interface', 'intuitive', 'navigate', 'customizing', 'layout', 'workflow', 'integrating', 'boost efficiency', 'track', 'collaboration', 'streamlined', 'digital clutter', 'managing'. Very sophisticated. >Band 7: Precise vocabulary. Not Band 9: Errors in usage.",
        "grammar_reason": "[GRA6] Uses complex structures but has frequent errors. Verb form errors ('customizing', 'integrating'). Agreement errors ('boost', 'features is'). >Band 5: Attempts complex sentences. Not Band 7: Errors are frequent.",
        "vocabulary": 8,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a useful app on your phone.\n\nTranscript: I rely heavily on a productivity app called Notion, which is an all-in-one workspace. It allows me to organize my tasks, notes, and projects seamlessly. The interface is intuitive, making it easy to navigate. I customizing the layout to suit my workflow. It integrating with other tools, which boost efficiency. I use it to track my habits and goals. The collaboration features is excellent for team projects. It has streamlined my life and reduced digital clutter. I cannot imagine managing my schedule without it.\n\nWord Count: 86 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses sophisticated vocabulary: 'intuitive', 'workflow', 'streamlined', 'clutter'. Precise.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Errors affect accuracy.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Frequent errors in verb forms and agreement ('customizing', 'boost'). Complex structures used but flawed.\n\n>Band 5: Complex sentences attempted.\n\nNot Band 7: Systematic errors.\n\n**Micro flaws identified:**\n- 'I customizing' should be 'I customize'\n- 'It integrating' should be 'It integrates'\n- 'which boost' should be 'boosts'\n- 'features is' should be 'features are'"
    },
    # 595. V8/G6 - Event (Tradition)
    {
        "sample_id": "syn_p2_v8_g6_0595",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a traditional meal.",
        "transcript_cleaned": "I want to describe a traditional feast called Thanksgiving, which is celebrated with gusto. The centerpiece is a roasted turkey, seasoned with aromatic herbs. It is accompanied by savory side dishes like stuffing and cranberry sauce. The preparation is a labor of love, involving the whole family. We gathering around the table to express gratitude. The aroma wafting from the kitchen is mouth-watering. It is a time for bonding and creating cherished memories. I indulging in the pumpkin pie, which is my weakness. It is a culinary tradition that I holding dear.",
        "word_count": 92,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'We gathering' should be 'We gather'", "grammar: 'I indulging' should be 'I indulge'", "grammar: 'that I holding' should be 'that I hold'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR8] Vocabulary: 'feast', 'celebrated', 'gusto', 'centerpiece', 'seasoned', 'aromatic herbs', 'savory', 'side dishes', 'labor of love', 'gratitude', 'aroma', 'wafting', 'mouth-watering', 'bonding', 'cherished memories', 'indulging', 'weakness', 'culinary tradition'. Very sophisticated. >Band 7: Precise vocabulary. Not Band 9: Errors in usage.",
        "grammar_reason": "[GRA6] Uses complex structures but has frequent errors. Verb form errors ('gathering', 'indulging', 'holding'). >Band 5: Attempts complex sentences. Not Band 7: Errors are noticeable.",
        "vocabulary": 8,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a traditional meal.\n\nTranscript: I want to describe a traditional feast called Thanksgiving, which is celebrated with gusto. The centerpiece is a roasted turkey, seasoned with aromatic herbs. It is accompanied by savory side dishes like stuffing and cranberry sauce. The preparation is a labor of love, involving the whole family. We gathering around the table to express gratitude. The aroma wafting from the kitchen is mouth-watering. It is a time for bonding and creating cherished memories. I indulging in the pumpkin pie, which is my weakness. It is a culinary tradition that I holding dear.\n\nWord Count: 92 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses sophisticated vocabulary: 'gusto', 'aromatic', 'wafting', 'culinary'. Precise.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Errors affect accuracy.\n\n**Idiom present:** Yes ('labor of love')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Frequent errors in verb forms ('gathering', 'holding'). Complex structures used but flawed.\n\n>Band 5: Complex sentences attempted.\n\nNot Band 7: Systematic errors.\n\n**Micro flaws identified:**\n- 'We gathering' should be 'We gather'\n- 'I indulging' should be 'I indulge'\n- 'that I holding' should be 'that I hold'"
    },
    # 596. V8/G6 - Activity (Creative)
    {
        "sample_id": "syn_p2_v8_g6_0596",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a photo you took.",
        "transcript_cleaned": "I took a candid photograph of my grandmother that capture her essence perfectly. She is sitting by the window, bathed in soft afternoon light. The expression on her face is one of serenity and wisdom. I managed to freezing a fleeting moment of contemplation. The composition highlight the texture of her weathered hands. It evoke a sense of nostalgia and deep affection. I developed the photo in black and white to enhancing the contrast. It is a portrait that speak volumes about her life. I treasure it as a keepsake.",
        "word_count": 92,
        "response_type": "long_turn",
        "micro_flaws": ["agreement: 'that capture' should be 'captures'", "grammar: 'to freezing' should be 'to freeze'", "agreement: 'composition highlight' should be 'highlights'", "agreement: 'It evoke' should be 'evokes'", "grammar: 'to enhancing' should be 'to enhance'", "agreement: 'portrait that speak' should be 'speaks'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR8] Vocabulary: 'candid photograph', 'capture', 'essence', 'bathed', 'serenity', 'wisdom', 'freezing', 'fleeting moment', 'contemplation', 'composition', 'texture', 'weathered', 'evoke', 'nostalgia', 'affection', 'developed', 'enhancing', 'contrast', 'portrait', 'speak volumes', 'keepsake'. Very sophisticated. >Band 7: Precise vocabulary. Not Band 9: Errors in usage.",
        "grammar_reason": "[GRA6] Uses complex structures but has frequent errors. Agreement errors ('capture', 'highlight', 'evoke', 'speak'). Verb form errors ('freezing', 'enhancing'). >Band 5: Attempts complex sentences. Not Band 7: Errors are frequent.",
        "vocabulary": 8,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a photo you took.\n\nTranscript: I took a candid photograph of my grandmother that capture her essence perfectly. She is sitting by the window, bathed in soft afternoon light. The expression on her face is one of serenity and wisdom. I managed to freezing a fleeting moment of contemplation. The composition highlight the texture of her weathered hands. It evoke a sense of nostalgia and deep affection. I developed the photo in black and white to enhancing the contrast. It is a portrait that speak volumes about her life. I treasure it as a keepsake.\n\nWord Count: 92 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses sophisticated vocabulary: 'candid', 'essence', 'contemplation', 'keepsake'. Precise.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Errors affect accuracy.\n\n**Idiom present:** Yes ('speak volumes')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Frequent errors in verb forms and agreement ('capture', 'freezing'). Complex structures used but flawed.\n\n>Band 5: Complex sentences attempted.\n\nNot Band 7: Systematic errors.\n\n**Micro flaws identified:**\n- 'that capture' should be 'that captures'\n- 'to freezing' should be 'to freeze'\n- 'composition highlight' should be 'highlights'\n- 'It evoke' should be 'evokes'\n- 'to enhancing' should be 'to enhance'\n- 'portrait that speak' should be 'speaks'"
    },
    # 597. V8/G6 - Object (Gift)
    {
        "sample_id": "syn_p2_v8_g6_0597",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a gift you bought for yourself.",
        "transcript_cleaned": "I treated myself to a high-end espresso machine, which is a luxury item. I am a coffee aficionado, so I appreciate the nuances of flavor. The machine allow me to brew barista-quality coffee at home. It has a sleek design that complement my kitchen decor. Mastering the steam wand were a bit tricky at first. However, I now crafting intricate latte art with ease. It saves me a fortune on daily coffee runs. This indulgence bring me joy every morning. It was a worthwhile investment in my daily ritual.",
        "word_count": 93,
        "response_type": "long_turn",
        "micro_flaws": ["agreement: 'machine allow' should be 'allows'", "agreement: 'design that complement' should be 'complements'", "agreement: 'wand were' should be 'was'", "grammar: 'I now crafting' should be 'craft'", "agreement: 'indulgence bring' should be 'brings'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR8] Vocabulary: 'treated myself', 'high-end', 'luxury item', 'aficionado', 'nuances', 'brew', 'barista-quality', 'sleek design', 'complement', 'decor', 'mastering', 'intricate', 'latte art', 'fortune', 'indulgence', 'worthwhile investment', 'ritual'. Very sophisticated. >Band 7: Precise vocabulary. Not Band 9: Errors in usage.",
        "grammar_reason": "[GRA6] Uses complex structures but has frequent errors. Agreement errors ('allow', 'complement', 'bring'). Verb form errors ('were', 'crafting'). >Band 5: Attempts complex sentences. Not Band 7: Errors are frequent.",
        "vocabulary": 8,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a gift you bought for yourself.\n\nTranscript: I treated myself to a high-end espresso machine, which is a luxury item. I am a coffee aficionado, so I appreciate the nuances of flavor. The machine allow me to brew barista-quality coffee at home. It has a sleek design that complement my kitchen decor. Mastering the steam wand were a bit tricky at first. However, I now crafting intricate latte art with ease. It saves me a fortune on daily coffee runs. This indulgence bring me joy every morning. It was a worthwhile investment in my daily ritual.\n\nWord Count: 93 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses sophisticated vocabulary: 'aficionado', 'nuances', 'sleek', 'indulgence'. Precise.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Errors affect accuracy.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Frequent errors in verb forms and agreement ('allow', 'complement'). Complex structures used but flawed.\n\n>Band 5: Complex sentences attempted.\n\nNot Band 7: Systematic errors.\n\n**Micro flaws identified:**\n- 'machine allow' should be 'allows'\n- 'design that complement' should be 'complements'\n- 'wand were' should be 'was'\n- 'I now crafting' should be 'craft'\n- 'indulgence bring' should be 'brings'"
    },
    # 598. V8/G6 - Place (Park)
    {
        "sample_id": "syn_p2_v8_g6_0598",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a park you know.",
        "transcript_cleaned": "There is a sprawling urban park in my city that is a haven for nature lovers. It features manicured lawns and vibrant flower beds. I go there to escape the concrete jungle and breathe fresh air. The park offering a multitude of recreational activities. I enjoy jogging along the winding paths, which is invigorating. The lake in the center reflect the skyline beautifully. It is a communal space where people from all walks of life gathers. I finding the tranquility there very restorative. It is an indispensable part of the city's infrastructure.",
        "word_count": 94,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'park offering' should be 'offers'", "agreement: 'paths, which is' should be 'are'", "agreement: 'lake... reflect' should be 'reflects'", "agreement: 'people... gathers' should be 'gather'", "grammar: 'I finding' should be 'find'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR8] Vocabulary: 'sprawling', 'urban park', 'haven', 'manicured lawns', 'vibrant', 'escape', 'concrete jungle', 'multitude', 'recreational activities', 'winding', 'invigorating', 'skyline', 'communal space', 'walks of life', 'tranquility', 'restorative', 'indispensable', 'infrastructure'. Very sophisticated. >Band 7: Precise vocabulary. Not Band 9: Errors in usage.",
        "grammar_reason": "[GRA6] Uses complex structures but has frequent errors. Verb form errors ('offering', 'finding'). Agreement errors ('is', 'reflect', 'gathers'). >Band 5: Attempts complex sentences. Not Band 7: Errors are frequent.",
        "vocabulary": 8,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a park you know.\n\nTranscript: There is a sprawling urban park in my city that is a haven for nature lovers. It features manicured lawns and vibrant flower beds. I go there to escape the concrete jungle and breathe fresh air. The park offering a multitude of recreational activities. I enjoy jogging along the winding paths, which is invigorating. The lake in the center reflect the skyline beautifully. It is a communal space where people from all walks of life gathers. I finding the tranquility there very restorative. It is an indispensable part of the city's infrastructure.\n\nWord Count: 94 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses sophisticated vocabulary: 'sprawling', 'manicured', 'restorative', 'indispensable'. Precise.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Errors affect accuracy.\n\n**Idiom present:** Yes ('concrete jungle', 'walks of life')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Frequent errors in verb forms and agreement ('offering', 'reflect'). Complex structures used but flawed.\n\n>Band 5: Complex sentences attempted.\n\nNot Band 7: Systematic errors.\n\n**Micro flaws identified:**\n- 'park offering' should be 'offers'\n- 'paths, which is' should be 'are'\n- 'lake... reflect' should be 'reflects'\n- 'people... gathers' should be 'gather'\n- 'I finding' should be 'find'"
    },
    # 599. V8/G6 - Person (Neighbor)
    {
        "sample_id": "syn_p2_v8_g6_0599",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a neighbor you dislike.",
        "transcript_cleaned": "I have a neighbor who is incredibly inconsiderate and disruptive. He play loud music late at night, which disturbs my sleep. He has a boisterous personality that I find grating. He often parking his car in front of my driveway, blocking my exit. I have tried to reasoning with him, but he is dismissive. His lack of empathy is infuriating. He also neglecting his garden, which is an eyesore. Living next to him is a constant source of frustration. I wishing he would move somewhere else.",
        "word_count": 87,
        "response_type": "long_turn",
        "micro_flaws": ["agreement: 'He play' should be 'plays'", "grammar: 'He often parking' should be 'parks'", "grammar: 'tried to reasoning' should be 'reason'", "grammar: 'He also neglecting' should be 'neglects'", "grammar: 'I wishing' should be 'wish'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR8] Vocabulary: 'inconsiderate', 'disruptive', 'disturbs', 'boisterous', 'grating', 'blocking', 'reasoning', 'dismissive', 'lack of empathy', 'infuriating', 'neglecting', 'eyesore', 'constant source', 'frustration'. Very sophisticated. >Band 7: Precise vocabulary. Not Band 9: Errors in usage.",
        "grammar_reason": "[GRA6] Uses complex structures but has frequent errors. Verb form errors ('play', 'parking', 'reasoning', 'neglecting', 'wishing'). >Band 5: Attempts complex sentences. Not Band 7: Errors are frequent.",
        "vocabulary": 8,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a neighbor you dislike.\n\nTranscript: I have a neighbor who is incredibly inconsiderate and disruptive. He play loud music late at night, which disturbs my sleep. He has a boisterous personality that I find grating. He often parking his car in front of my driveway, blocking my exit. I have tried to reasoning with him, but he is dismissive. His lack of empathy is infuriating. He also neglecting his garden, which is an eyesore. Living next to him is a constant source of frustration. I wishing he would move somewhere else.\n\nWord Count: 87 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses sophisticated vocabulary: 'inconsiderate', 'boisterous', 'dismissive', 'eyesore'. Precise.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Errors affect accuracy.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Frequent errors in verb forms ('parking', 'reasoning'). Complex structures used but flawed.\n\n>Band 5: Complex sentences attempted.\n\nNot Band 7: Systematic errors.\n\n**Micro flaws identified:**\n- 'He play' should be 'plays'\n- 'He often parking' should be 'parks'\n- 'tried to reasoning' should be 'reason'\n- 'He also neglecting' should be 'neglects'\n- 'I wishing' should be 'wish'"
    },
    # 600. V8/G6 - Activity (Daily)
    {
        "sample_id": "syn_p2_v8_g6_0600",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a chore you do.",
        "transcript_cleaned": "I am responsible for maintaining the garden, a task that is both laborious and rewarding. It involves pruning the hedges, mowing the lawn, and weeding the flower beds. I find the physical exertion to be cathartic. However, it requiring a significant time commitment. I often battling with pests that damage the plants. Keeping the garden pristine take a lot of effort. Despite the hard work, I take pride in the aesthetic appeal of my garden. It is a tranquil retreat that I cherishing. It connects me with the cycle of nature.",
        "word_count": 93,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'it requiring' should be 'requires'", "grammar: 'I often battling' should be 'battle'", "agreement: 'pristine take' should be 'takes'", "grammar: 'that I cherishing' should be 'cherish'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "vocab_reason": "[LR8] Vocabulary: 'responsible', 'maintaining', 'laborious', 'rewarding', 'pruning', 'hedges', 'mowing', 'weeding', 'exertion', 'cathartic', 'commitment', 'battling', 'pests', 'pristine', 'aesthetic appeal', 'tranquil retreat', 'cherishing', 'cycle of nature'. Very sophisticated. >Band 7: Precise vocabulary. Not Band 9: Errors in usage.",
        "grammar_reason": "[GRA6] Uses complex structures but has frequent errors. Verb form errors ('requiring', 'battling', 'cherishing'). Agreement error ('take'). >Band 5: Attempts complex sentences. Not Band 7: Errors are frequent.",
        "vocabulary": 8,
        "grammar": 6,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a chore you do.\n\nTranscript: I am responsible for maintaining the garden, a task that is both laborious and rewarding. It involves pruning the hedges, mowing the lawn, and weeding the flower beds. I find the physical exertion to be cathartic. However, it requiring a significant time commitment. I often battling with pests that damage the plants. Keeping the garden pristine take a lot of effort. Despite the hard work, I take pride in the aesthetic appeal of my garden. It is a tranquil retreat that I cherishing. It connects me with the cycle of nature.\n\nWord Count: 93 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses sophisticated vocabulary: 'laborious', 'cathartic', 'pristine', 'aesthetic'. Precise.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Errors affect accuracy.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Frequent errors in verb forms and agreement ('requiring', 'take'). Complex structures used but flawed.\n\n>Band 5: Complex sentences attempted.\n\nNot Band 7: Systematic errors.\n\n**Micro flaws identified:**\n- 'it requiring' should be 'it requires'\n- 'I often battling' should be 'battle'\n- 'pristine take' should be 'takes'\n- 'that I cherishing' should be 'cherish'"
    }
]

with open(OUTPUT_FILE, 'a', encoding='utf-8') as f:
    for sample in samples:
        f.write(json.dumps(sample) + '\n')
