import json

OUTPUT_FILE = "ielts-data/phase3/v76_review_output/synthetic_batches/batch_p2_13.jsonl"

samples = [
    # 621. V7/G4 - Book (Read)
    {
        "sample_id": "syn_p2_v7_g4_0621",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a book you read.",
        "transcript_cleaned": "I read interesting book called 'The Hobbit'. It is fantasy novel. It tell story of Bilbo Baggins. He go on adventure with dwarves. They want reclaim their homeland. There is dragon called Smaug. The book have many mythical creatures. I like the descriptions of landscapes. The protagonist is very brave. It is classic literature. I enjoy reading it. It take me long time to finish. The plot is compelling. I recommend it to people who likes adventure.",
        "word_count": 87,
        "response_type": "long_turn",
        "micro_flaws": ["article: 'read interesting book' should be 'read an interesting book'", "article: 'is fantasy novel' should be 'is a fantasy novel'", "agreement: 'It tell' should be 'It tells'", "agreement: 'He go' should be 'He goes'", "article: 'on adventure' should be 'on an adventure'", "grammar: 'want reclaim' should be 'want to reclaim'", "article: 'is dragon' should be 'is a dragon'", "agreement: 'book have' should be 'book has'", "article: 'is classic literature' should be 'is classic literature' (ok) or 'is a classic of literature'", "agreement: 'It take' should be 'It took'", "article: 'long time' should be 'a long time'", "agreement: 'people who likes' should be 'people who like'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR7] Vocabulary: 'fantasy novel', 'adventure', 'dwarves', 'reclaim', 'homeland', 'mythical creatures', 'descriptions', 'landscapes', 'protagonist', 'brave', 'classic literature', 'compelling', 'recommend'. Sophisticated words. >Band 6: Precise vocabulary. Not Band 8: Some errors in usage.",
        "grammar_reason": "[GRA4] Only simple sentences. Systematic errors in agreement ('It tell', 'He go', 'book have'), articles, and verbs. >Band 3: Basic meaning clear. Not Band 5: Errors are pervasive.",
        "vocabulary": 7,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a book you read.\n\nTranscript: I read interesting book called 'The Hobbit'. It is fantasy novel. It tell story of Bilbo Baggins. He go on adventure with dwarves. They want reclaim their homeland. There is dragon called Smaug. The book have many mythical creatures. I like the descriptions of landscapes. The protagonist is very brave. It is classic literature. I enjoy reading it. It take me long time to finish. The plot is compelling. I recommend it to people who likes adventure.\n\nWord Count: 87 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses sophisticated words: 'mythical', 'protagonist', 'compelling'. Good range.\n\n>Band 6: Advanced vocabulary.\n\nNot Band 8: Lacks native flow.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Simple sentences. Frequent errors in agreement ('It tell') and articles. Strain for listener.\n\n>Band 3: Simple structures.\n\nNot Band 5: Systematic errors.\n\n**Micro flaws identified:**\n- 'read interesting book' should be 'read an interesting book'\n- 'is fantasy novel' should be 'is a fantasy novel'\n- 'It tell' should be 'It tells'\n- 'He go' should be 'He goes'\n- 'on adventure' should be 'on an adventure'\n- 'want reclaim' should be 'want to reclaim'\n- 'is dragon' should be 'is a dragon'\n- 'book have' should be 'book has'\n- 'It take' should be 'It took'\n- 'long time' should be 'a long time'\n- 'people who likes' should be 'people who like'"
    },
    # 622. V7/G4 - Place (Travel)
    {
        "sample_id": "syn_p2_v7_g4_0622",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a place you want to go.",
        "transcript_cleaned": "I want go to Santorini in Greece. It is stunning island. The architecture is unique. I see pictures of white houses with blue domes. It look picturesque. I want to explore the volcanic beaches. The scenery is breathtaking. I think the sunset is spectacular. The local cuisine is delicious. I want try fresh seafood. It is popular destination. However, it is expensive place. I need save money. It is dream vacation for me. The atmosphere seem serene.",
        "word_count": 87,
        "response_type": "long_turn",
        "micro_flaws": ["grammar: 'want go' should be 'want to go'", "article: 'stunning island' should be 'a stunning island'", "agreement: 'It look' should be 'It looks'", "grammar: 'want try' should be 'want to try'", "article: 'popular destination' should be 'a popular destination'", "article: 'expensive place' should be 'an expensive place'", "grammar: 'need save' should be 'need to save'", "article: 'dream vacation' should be 'a dream vacation'", "agreement: 'atmosphere seem' should be 'atmosphere seems'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR7] Vocabulary: 'stunning', 'architecture', 'unique', 'domes', 'picturesque', 'explore', 'volcanic beaches', 'scenery', 'breathtaking', 'sunset', 'spectacular', 'cuisine', 'delicious', 'destination', 'expensive', 'dream vacation', 'atmosphere', 'serene'. Sophisticated descriptors. >Band 6: Precise vocabulary. Not Band 8: Errors in usage.",
        "grammar_reason": "[GRA4] Only simple sentences. Systematic errors in verbs ('want go', 'need save'), agreement ('It look'), and articles. >Band 3: Basic meaning clear. Not Band 5: Errors are very frequent.",
        "vocabulary": 7,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a place you want to go.\n\nTranscript: I want go to Santorini in Greece. It is stunning island. The architecture is unique. I see pictures of white houses with blue domes. It look picturesque. I want to explore the volcanic beaches. The scenery is breathtaking. I think the sunset is spectacular. The local cuisine is delicious. I want try fresh seafood. It is popular destination. However, it is expensive place. I need save money. It is dream vacation for me. The atmosphere seem serene.\n\nWord Count: 87 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses sophisticated words: 'picturesque', 'breathtaking', 'cuisine', 'serene'. Good range.\n\n>Band 6: Advanced vocabulary.\n\nNot Band 8: Lacks native flow.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Simple sentences only. Frequent errors in verbs and articles. Strain for listener.\n\n>Band 3: Simple structures.\n\nNot Band 5: Systematic errors.\n\n**Micro flaws identified:**\n- 'want go' should be 'want to go'\n- 'stunning island' should be 'a stunning island'\n- 'It look' should be 'It looks'\n- 'want try' should be 'want to try'\n- 'popular destination' should be 'a popular destination'\n- 'expensive place' should be 'an expensive place'\n- 'need save' should be 'need to save'\n- 'dream vacation' should be 'a dream vacation'\n- 'atmosphere seem' should be 'atmosphere seems'"
    },
    # 623. V7/G4 - Event (Concert)
    {
        "sample_id": "syn_p2_v7_g4_0623",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a concert you enjoyed.",
        "transcript_cleaned": "I go to concert last month. It was rock band called Coldplay. The venue was massive stadium. The atmosphere was electric. There was thousands of fans. The band play energetic songs. I know lyrics to all songs. The light show was dazzling. It was memorable experience. The lead singer is very charismatic. I was mesmerizing by performance. It was exhilarating night. I feel ecstatic. I recommend their concert to everyone.",
        "word_count": 82,
        "response_type": "long_turn",
        "micro_flaws": ["tense: 'I go' should be 'I went'", "article: 'to concert' should be 'to a concert'", "article: 'rock band' should be 'a rock band'", "article: 'massive stadium' should be 'a massive stadium'", "agreement: 'There was thousands' should be 'There were thousands'", "agreement: 'band play' should be 'band played'", "article: 'know lyrics' should be 'know the lyrics'", "article: 'memorable experience' should be 'a memorable experience'", "grammar: 'was mesmerizing' should be 'was mesmerized'", "article: 'by performance' should be 'by the performance'", "article: 'exhilarating night' should be 'an exhilarating night'", "tense: 'I feel' should be 'I felt'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR7] Vocabulary: 'concert', 'rock band', 'venue', 'massive', 'atmosphere', 'electric', 'energetic', 'lyrics', 'dazzling', 'memorable', 'charismatic', 'mesmerized', 'performance', 'exhilarating', 'ecstatic', 'recommend'. Sophisticated descriptors. >Band 6: Precise vocabulary. Not Band 8: Errors in word form.",
        "grammar_reason": "[GRA4] Only simple sentences. Systematic errors in tense ('go', 'play', 'feel'), agreement ('was thousands'), and articles. >Band 3: Basic meaning clear. Not Band 5: Errors are pervasive.",
        "vocabulary": 7,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a concert you enjoyed.\n\nTranscript: I go to concert last month. It was rock band called Coldplay. The venue was massive stadium. The atmosphere was electric. There was thousands of fans. The band play energetic songs. I know lyrics to all songs. The light show was dazzling. It was memorable experience. The lead singer is very charismatic. I was mesmerizing by performance. It was exhilarating night. I feel ecstatic. I recommend their concert to everyone.\n\nWord Count: 82 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses sophisticated words: 'venue', 'electric', 'dazzling', 'exhilarating'. Good range.\n\n>Band 6: Advanced vocabulary.\n\nNot Band 8: Word form error ('mesmerizing').\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Simple sentences. Frequent errors in tense and articles. Strain for listener.\n\n>Band 3: Simple structures.\n\nNot Band 5: Systematic errors.\n\n**Micro flaws identified:**\n- 'I go' should be 'I went'\n- 'to concert' should be 'to a concert'\n- 'rock band' should be 'a rock band'\n- 'massive stadium' should be 'a massive stadium'\n- 'There was thousands' should be 'There were thousands'\n- 'band play' should be 'band played'\n- 'know lyrics' should be 'know the lyrics'\n- 'memorable experience' should be 'a memorable experience'\n- 'was mesmerizing' should be 'was mesmerized'\n- 'by performance' should be 'by the performance'\n- 'exhilarating night' should be 'an exhilarating night'\n- 'I feel' should be 'I felt'"
    },
    # 624. V7/G4 - Person (Admire)
    {
        "sample_id": "syn_p2_v7_g4_0624",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a person you admire.",
        "transcript_cleaned": "I admire Elon Musk. He is famous entrepreneur. He create many companies like Tesla. He is visionary leader. He want to change world. I like his innovation and determination. He work very hard. He encounter many failure, but he never give up. His resilience is inspiring. He is also very wealthy. He invest in space travel. I think he is genius. He motivate me to work hard. I want be successful like him.",
        "word_count": 86,
        "response_type": "long_turn",
        "micro_flaws": ["article: 'famous entrepreneur' should be 'a famous entrepreneur'", "agreement: 'He create' should be 'He created' or 'He creates'", "article: 'visionary leader' should be 'a visionary leader'", "agreement: 'He want' should be 'He wants'", "article: 'change world' should be 'change the world'", "agreement: 'He work' should be 'He works'", "agreement: 'He encounter' should be 'He encountered'", "plural: 'many failure' should be 'many failures'", "agreement: 'he never give up' should be 'he never gives up'", "agreement: 'He invest' should be 'He invests'", "article: 'is genius' should be 'is a genius'", "agreement: 'He motivate' should be 'He motivates'", "grammar: 'want be' should be 'want to be'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR7] Vocabulary: 'admire', 'entrepreneur', 'create', 'visionary', 'innovation', 'determination', 'encounter', 'failure', 'resilience', 'inspiring', 'wealthy', 'invest', 'space travel', 'genius', 'motivate', 'successful'. Sophisticated words. >Band 6: Precise vocabulary. Not Band 8: Errors in usage.",
        "grammar_reason": "[GRA4] Only simple sentences. Systematic errors in agreement ('He create', 'He want', 'He work', 'He invest'). Missing articles and prepositions. >Band 3: Basic structures. Not Band 5: Errors are pervasive.",
        "vocabulary": 7,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a person you admire.\n\nTranscript: I admire Elon Musk. He is famous entrepreneur. He create many companies like Tesla. He is visionary leader. He want to change world. I like his innovation and determination. He work very hard. He encounter many failure, but he never give up. His resilience is inspiring. He is also very wealthy. He invest in space travel. I think he is genius. He motivate me to work hard. I want be successful like him.\n\nWord Count: 86 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses sophisticated words: 'visionary', 'innovation', 'resilience', 'entrepreneur'. Good range.\n\n>Band 6: Advanced vocabulary.\n\nNot Band 8: Lacks native flow.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Simple sentences. Frequent errors in agreement ('He work') and articles. Strain for listener.\n\n>Band 3: Simple structures.\n\nNot Band 5: Systematic errors.\n\n**Micro flaws identified:**\n- 'famous entrepreneur' should be 'a famous entrepreneur'\n- 'He create' should be 'He created'\n- 'visionary leader' should be 'a visionary leader'\n- 'He want' should be 'He wants'\n- 'change world' should be 'change the world'\n- 'He work' should be 'He works'\n- 'He encounter' should be 'He encountered'\n- 'many failure' should be 'many failures'\n- 'he never give up' should be 'he never gives up'\n- 'He invest' should be 'He invests'\n- 'is genius' should be 'is a genius'\n- 'He motivate' should be 'He motivates'\n- 'want be' should be 'want to be'"
    },
    # 625. V7/G4 - Object (Technology)
    {
        "sample_id": "syn_p2_v7_g4_0625",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a piece of technology you use.",
        "transcript_cleaned": "I use tablet every day. It is versatile device. I use it for work and entertainment. It has high-resolution screen. The display is vibrant. I can edit documents on it. It is portable and lightweight. I carry it in my bag. The battery life is impressive. It last for long time. However, software sometimes glitch. It can be frustrating. But it is indispensable tool for me. It enhance my productivity. I cannot imagine life without it.",
        "word_count": 90,
        "response_type": "long_turn",
        "micro_flaws": ["article: 'use tablet' should be 'use a tablet'", "article: 'versatile device' should be 'a versatile device'", "article: 'high-resolution screen' should be 'a high-resolution screen'", "agreement: 'It last' should be 'It lasts'", "article: 'long time' should be 'a long time'", "article: 'software sometimes glitch' should be 'the software sometimes glitches'", "article: 'indispensable tool' should be 'an indispensable tool'", "agreement: 'It enhance' should be 'It enhances'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR7] Vocabulary: 'tablet', 'versatile', 'entertainment', 'high-resolution', 'display', 'vibrant', 'edit documents', 'portable', 'lightweight', 'battery life', 'impressive', 'software', 'glitch', 'frustrating', 'indispensable', 'enhance', 'productivity'. Very sophisticated. >Band 6: Precise vocabulary. Not Band 8: Errors in usage.",
        "grammar_reason": "[GRA4] Only simple sentences. Systematic errors in agreement ('It last', 'It enhance') and articles. >Band 3: Basic meaning clear. Not Band 5: Errors are pervasive.",
        "vocabulary": 7,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a piece of technology you use.\n\nTranscript: I use tablet every day. It is versatile device. I use it for work and entertainment. It has high-resolution screen. The display is vibrant. I can edit documents on it. It is portable and lightweight. I carry it in my bag. The battery life is impressive. It last for long time. However, software sometimes glitch. It can be frustrating. But it is indispensable tool for me. It enhance my productivity. I cannot imagine life without it.\n\nWord Count: 90 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses sophisticated words: 'versatile', 'high-resolution', 'indispensable', 'productivity'. Good range.\n\n>Band 6: Advanced vocabulary.\n\nNot Band 8: Lacks native flow.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Simple sentences. Frequent errors in agreement and articles. Strain for listener.\n\n>Band 3: Simple structures.\n\nNot Band 5: Systematic errors.\n\n**Micro flaws identified:**\n- 'use tablet' should be 'use a tablet'\n- 'versatile device' should be 'a versatile device'\n- 'high-resolution screen' should be 'a high-resolution screen'\n- 'It last' should be 'It lasts'\n- 'long time' should be 'a long time'\n- 'software sometimes glitch' should be 'the software sometimes glitches'\n- 'indispensable tool' should be 'an indispensable tool'\n- 'It enhance' should be 'It enhances'"
    },
    # 626. V5/G8 - Activity (Daily)
    {
        "sample_id": "syn_p2_v5_g8_0626",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a typical day in your life.",
        "transcript_cleaned": "My typical day begins early, around 6 am. I usually start with a light breakfast before going to work. My job involves checking emails and attending meetings. Although it can be tiring, I enjoy the routine. After work, I often go to the gym to exercise. Staying healthy is important to me. In the evening, I cook dinner for myself. I like to make simple meals like pasta. Before bed, I read a book to relax. This routine helps me stay organized and focused. I believe that having a schedule is beneficial.",
        "word_count": 92,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR5] Vocabulary: 'typical day', 'begins', 'light breakfast', 'checking emails', 'meetings', 'tiring', 'routine', 'exercise', 'healthy', 'simple meals', 'relax', 'organized', 'focused', 'schedule', 'beneficial'. Functional vocabulary relevant to the topic. >Band 4: Uses some specific words ('schedule', 'beneficial'). Not Band 6: Simple vocabulary.",
        "grammar_reason": "[GRA8] Wide range of structures used accurately. 'Before going to work' (Prepositional phrase). 'My job involves checking...' (Gerund phrase). 'Although it can be tiring...' (Concessive clause). 'I believe that having...' (Noun clause + Gerund subject). Error-free. >Band 7: More variety.",
        "vocabulary": 5,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a typical day in your life.\n\nTranscript: My typical day begins early, around 6 am. I usually start with a light breakfast before going to work. My job involves checking emails and attending meetings. Although it can be tiring, I enjoy the routine. After work, I often go to the gym to exercise. Staying healthy is important to me. In the evening, I cook dinner for myself. I like to make simple meals like pasta. Before bed, I read a book to relax. This routine helps me stay organized and focused. I believe that having a schedule is beneficial.\n\nWord Count: 92 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses topic words: 'routine', 'organized', 'beneficial'. Meaning is clear.\n\n>Band 4: Adequate vocabulary.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Uses complex structures accurately (gerund phrases, concessive clauses). Sentences are error-free.\n\n>Band 7: High accuracy.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    },
    # 627. V5/G8 - Place (Home)
    {
        "sample_id": "syn_p2_v5_g8_0627",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe the house you grew up in.",
        "transcript_cleaned": "I grew up in a small house in the countryside. It was a comfortable home with a big garden. We had many fruit trees, which I loved climbing. My favorite room was the kitchen because it was always warm. My mother cooked delicious meals there every day. Although the house was old, it was very cozy. I have many happy memories of playing in the garden with my siblings. Living there taught me to appreciate nature. If I could, I would buy that house again.",
        "word_count": 92,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR5] Vocabulary: 'countryside', 'comfortable', 'garden', 'fruit trees', 'climbing', 'kitchen', 'warm', 'delicious meals', 'old', 'cozy', 'memories', 'siblings', 'appreciate nature', 'buy'. Functional vocabulary relevant to the topic. >Band 4: Uses some specific words ('cozy', 'appreciate'). Not Band 6: Simple vocabulary.",
        "grammar_reason": "[GRA8] Wide range of structures used accurately. 'Which I loved climbing' (Relative clause). 'Because it was always warm' (Reason clause). 'Although the house was old...' (Concessive clause). 'Playing in the garden...' (Participle phrase). 'If I could, I would buy...' (Second conditional). Error-free. >Band 7: More variety.",
        "vocabulary": 5,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe the house you grew up in.\n\nTranscript: I grew up in a small house in the countryside. It was a comfortable home with a big garden. We had many fruit trees, which I loved climbing. My favorite room was the kitchen because it was always warm. My mother cooked delicious meals there every day. Although the house was old, it was very cozy. I have many happy memories of playing in the garden with my siblings. Living there taught me to appreciate nature. If I could, I would buy that house again.\n\nWord Count: 92 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses topic words: 'countryside', 'cozy', 'appreciate'. Meaning is clear.\n\n>Band 4: Adequate vocabulary.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Uses complex structures accurately (conditionals, relative clauses). Sentences are error-free.\n\n>Band 7: High accuracy.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    },
    # 628. V5/G8 - Person (Teacher)
    {
        "sample_id": "syn_p2_v5_g8_0628",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a teacher you liked.",
        "transcript_cleaned": "I really liked my English teacher, Mrs. Brown. She was very kind and patient with all her students. She made learning fun by using games and songs. I remember her classes being the highlight of my day. She always encouraged us to speak English, even if we made mistakes. Because of her, I became more confident in my language skills. She explained grammar rules clearly, which helped me understand better. I think she is the best teacher I have ever had. I am grateful for her help.",
        "word_count": 93,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR5] Vocabulary: 'English teacher', 'kind', 'patient', 'students', 'learning', 'fun', 'games', 'songs', 'highlight', 'encouraged', 'mistakes', 'confident', 'language skills', 'grammar rules', 'clearly', 'grateful'. Functional vocabulary relevant to the topic. >Band 4: Uses some specific words ('confident', 'grateful'). Not Band 6: Simple vocabulary.",
        "grammar_reason": "[GRA8] Wide range of structures used accurately. 'By using games and songs' (Prepositional phrase). 'Classes being the highlight...' (Participle phrase). 'Even if we made mistakes' (Concessive clause). 'Which helped me understand' (Relative clause). 'Best teacher I have ever had' (Superlative + Relative). Error-free. >Band 7: More variety.",
        "vocabulary": 5,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a teacher you liked.\n\nTranscript: I really liked my English teacher, Mrs. Brown. She was very kind and patient with all her students. She made learning fun by using games and songs. I remember her classes being the highlight of my day. She always encouraged us to speak English, even if we made mistakes. Because of her, I became more confident in my language skills. She explained grammar rules clearly, which helped me understand better. I think she is the best teacher I have ever had. I am grateful for her help.\n\nWord Count: 93 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses topic words: 'patient', 'confident', 'grateful'. Meaning is clear.\n\n>Band 4: Adequate vocabulary.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** Yes ('highlight of my day')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Uses complex structures accurately (participle phrases, relative clauses). Sentences are error-free.\n\n>Band 7: High accuracy.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    },
    # 629. V5/G8 - Event (Festival)
    {
        "sample_id": "syn_p2_v5_g8_0629",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a festival you enjoy.",
        "transcript_cleaned": "I enjoy the Spring Festival, which is the most important holiday in my country. It is a time for family reunions and celebrating the new year. We clean our houses to sweep away bad luck. I love the red decorations and lanterns everywhere. Eating special food like dumplings is my favorite part. We also watch fireworks at night, which are very beautiful. Children receive money in red envelopes, which makes them happy. Although it is crowded, the atmosphere is very lively. It is a tradition that brings everyone together.",
        "word_count": 96,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR5] Vocabulary: 'Spring Festival', 'important holiday', 'family reunions', 'celebrating', 'clean', 'sweep away', 'bad luck', 'decorations', 'lanterns', 'dumplings', 'favorite part', 'fireworks', 'red envelopes', 'crowded', 'atmosphere', 'lively', 'tradition'. Functional vocabulary relevant to the topic. >Band 4: Uses some specific words ('reunions', 'tradition'). Not Band 6: Simple vocabulary.",
        "grammar_reason": "[GRA8] Wide range of structures used accurately. 'Which is the most important holiday' (Relative clause). 'To sweep away bad luck' (Infinitive of purpose). 'Like dumplings' (Prepositional phrase). 'Which makes them happy' (Relative clause). 'Although it is crowded...' (Concessive clause). Error-free. >Band 7: More variety.",
        "vocabulary": 5,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a festival you enjoy.\n\nTranscript: I enjoy the Spring Festival, which is the most important holiday in my country. It is a time for family reunions and celebrating the new year. We clean our houses to sweep away bad luck. I love the red decorations and lanterns everywhere. Eating special food like dumplings is my favorite part. We also watch fireworks at night, which are very beautiful. Children receive money in red envelopes, which makes them happy. Although it is crowded, the atmosphere is very lively. It is a tradition that brings everyone together.\n\nWord Count: 96 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses topic words: 'reunions', 'decorations', 'lively'. Meaning is clear.\n\n>Band 4: Adequate vocabulary.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Uses complex structures accurately (relative clauses, concessive clauses). Sentences are error-free.\n\n>Band 7: High accuracy.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    },
    # 630. V5/G8 - Object (Gift)
    {
        "sample_id": "syn_p2_v5_g8_0630",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a gift you liked.",
        "transcript_cleaned": "I received a bicycle for my birthday when I was ten. It was the best gift I have ever received. My parents bought it for me because I did well in school. It was red and had shiny wheels. I learned to ride it in the park near my house. Riding my bike gave me a sense of freedom. I used it to go to school every day. Even though I fell off a few times, I never gave up. I still keep it in my garage as a memory.",
        "word_count": 97,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR5] Vocabulary: 'bicycle', 'birthday', 'best gift', 'received', 'bought', 'shiny wheels', 'ride', 'park', 'sense of freedom', 'fell off', 'gave up', 'garage', 'memory'. Functional vocabulary relevant to the topic. >Band 4: Uses some specific words ('freedom', 'memory'). Not Band 6: Simple vocabulary.",
        "grammar_reason": "[GRA8] Wide range of structures used accurately. 'When I was ten' (Time clause). 'Best gift I have ever received' (Superlative + Relative). 'Because I did well...' (Reason clause). 'Even though I fell off...' (Concessive clause). Error-free. >Band 7: More variety.",
        "vocabulary": 5,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a gift you liked.\n\nTranscript: I received a bicycle for my birthday when I was ten. It was the best gift I have ever received. My parents bought it for me because I did well in school. It was red and had shiny wheels. I learned to ride it in the park near my house. Riding my bike gave me a sense of freedom. I used it to go to school every day. Even though I fell off a few times, I never gave up. I still keep it in my garage as a memory.\n\nWord Count: 97 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses topic words: 'shiny', 'freedom', 'memory'. Meaning is clear.\n\n>Band 4: Adequate vocabulary.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** Yes ('gave up')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Uses complex structures accurately (superlatives, concessive clauses). Sentences are error-free.\n\n>Band 7: High accuracy.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    }
]

with open(OUTPUT_FILE, 'a', encoding='utf-8') as f:
    for sample in samples:
        f.write(json.dumps(sample) + '\n')
