import json

OUTPUT_FILE = "ielts-data/phase3/v76_review_output/synthetic_batches/batch_p2_09.jsonl"

samples = [
    # 401. V4/G4 - Friend (Describe)
    {
        "sample_id": "syn_p2_v4_g4_0401",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a friend you spend a lot of time with.",
        "transcript_cleaned": "I want to talk about my friend John. He is my best friend. We know each other for 10 years. We live near same street. John is very kind and funny. He tall and has black hair. We like play football together on weekend. Also we watch movie in cinema. I like him because he always help me. Last week, my car broken, and he help me fix it. We talk every day on phone. Sometimes we go eat food in restaurant. He is like my brother. I happy to have friend like him. We want to travel together next year. It will be very good.",
        "word_count": 105,
        "response_type": "long_turn",
        "micro_flaws": ["tense: 'We know' should be 'We have known'", "article: 'near same street' should be 'near the same street'", "verb: 'He tall' should be 'He is tall'", "verb: 'like play' should be 'like playing'", "article: 'on weekend' should be 'on the weekend'", "article: 'watch movie' should be 'watch movies'", "agreement: 'he always help' should be 'helps'", "tense: 'car broken' should be 'car broke' or 'was broken'", "tense: 'he help' should be 'he helped'", "article: 'on phone' should be 'on the phone'", "article: 'in restaurant' should be 'in a restaurant'", "verb: 'I happy' should be 'I am happy'", "article: 'have friend' should be 'have a friend'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR4] Limited range: 'best friend', 'street', 'kind', 'funny', 'tall', 'black hair', 'football', 'cinema', 'help', 'fix', 'food', 'restaurant', 'travel', 'good'. Repetitive and basic. Cannot paraphrase. >Band 3: Can convey basic meaning. Not Band 5: Minimal use of less common words.",
        "grammar_reason": "[GRA4] Only simple sentences. Systematic errors: missing verbs ('He tall', 'I happy'), missing articles ('same street', 'weekend', 'movie', 'cinema', 'phone', 'restaurant'), incorrect tenses ('We know', 'car broken'). >Band 3: Basic structures recognizable. Not Band 5: Errors are very frequent.",
        "vocabulary": 4,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a friend you spend a lot of time with.\n\nTranscript: I want to talk about my friend John. He is my best friend. We know each other for 10 years. We live near same street. John is very kind and funny. He tall and has black hair. We like play football together on weekend. Also we watch movie in cinema. I like him because he always help me. Last week, my car broken, and he help me fix it. We talk every day on phone. Sometimes we go eat food in restaurant. He is like my brother. I happy to have friend like him. We want to travel together next year. It will be very good.\n\nWord Count: 105 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Basic vocabulary only. Heavy repetition of simple words ('friend', 'help', 'good'). No attempt at complex language.\n\n>Band 3: Can talk about familiar topic.\n\nNot Band 5: Vocabulary is too limited.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Simple sentences only. Frequent errors in articles, verb forms ('He tall', 'I happy'), and tenses. Causes some strain.\n\n>Band 3: Can produce simple forms.\n\nNot Band 5: Errors are systematic.\n\n**Micro flaws identified:**\n- 'We know' should be 'We have known'\n- 'near same street' should be 'near the same street'\n- 'He tall' should be 'He is tall'\n- 'like play' should be 'like playing'\n- 'on weekend' should be 'on the weekend'\n- 'watch movie' should be 'watch movies'\n- 'he always help' should be 'helps'\n- 'car broken' should be 'car broke'\n- 'he help' should be 'he helped'\n- 'on phone' should be 'on the phone'\n- 'in restaurant' should be 'in a restaurant'\n- 'I happy' should be 'I am happy'\n- 'have friend' should be 'have a friend'"
    },
    # 402. V4/G4 - City (Hometown)
    {
        "sample_id": "syn_p2_v4_g4_0402",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe your hometown.",
        "transcript_cleaned": "My hometown is small city called Da Nang. It is in Vietnam. I live there all my life. It is very beautiful place. It has big beach and many mountain. People in my hometown is very friendly. They always smile to me. The weather is hot in summer. I like swim in the sea. The food is delicious, specially seafood. There are many restaurant near the beach. Tourists come to my city every year. I love my hometown because it quiet and safe. My family live there too. I want to live there in future. It is good place for live.",
        "word_count": 103,
        "response_type": "long_turn",
        "micro_flaws": ["article: 'is small city' should be 'is a small city'", "tense: 'I live there' should be 'I have lived there'", "article: 'beautiful place' should be 'a beautiful place'", "article: 'big beach' should be 'a big beach'", "plural: 'many mountain' should be 'many mountains'", "agreement: 'People... is' should be 'are'", "preposition: 'smile to' should be 'smile at'", "verb: 'like swim' should be 'like swimming'", "spelling: 'specially' should be 'especially'", "plural: 'many restaurant' should be 'many restaurants'", "verb: 'it quiet' should be 'it is quiet'", "agreement: 'family live' should be 'lives' (or live)", "article: 'in future' should be 'in the future'", "article: 'good place' should be 'a good place'", "preposition: 'for live' should be 'to live'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR4] Limited range: 'small city', 'beautiful', 'big beach', 'mountain', 'friendly', 'smile', 'hot', 'swim', 'sea', 'food', 'delicious', 'restaurant', 'tourists', 'quiet', 'safe', 'good'. Basic and repetitive. >Band 3: Communicates meaning. Not Band 5: No variation.",
        "grammar_reason": "[GRA4] Simple structures used. Systematic errors in articles ('a small city', 'a beautiful place'), plurals ('mountain', 'restaurant'), and verb 'to be' ('it quiet', 'People is'). >Band 3: Meaning clear. Not Band 5: Frequent basic errors.",
        "vocabulary": 4,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe your hometown.\n\nTranscript: My hometown is small city called Da Nang. It is in Vietnam. I live there all my life. It is very beautiful place. It has big beach and many mountain. People in my hometown is very friendly. They always smile to me. The weather is hot in summer. I like swim in the sea. The food is delicious, specially seafood. There are many restaurant near the beach. Tourists come to my city every year. I love my hometown because it quiet and safe. My family live there too. I want to live there in future. It is good place for live.\n\nWord Count: 103 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Only basic words used. 'Beautiful', 'big', 'good' repeated. No range.\n\n>Band 3: Basic communication.\n\nNot Band 5: Very limited vocabulary.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Simple sentences predominant. Errors in 'be' verb ('it quiet', 'People is'), articles, and plurals are constant.\n\n>Band 3: Can form simple sentences.\n\nNot Band 5: Errors are pervasive.\n\n**Micro flaws identified:**\n- 'is small city' should be 'is a small city'\n- 'I live there' should be 'I have lived there'\n- 'beautiful place' should be 'a beautiful place'\n- 'big beach' should be 'a big beach'\n- 'many mountain' should be 'many mountains'\n- 'People... is' should be 'People... are'\n- 'smile to' should be 'smile at'\n- 'like swim' should be 'like swimming'\n- 'specially' should be 'especially'\n- 'many restaurant' should be 'many restaurants'\n- 'it quiet' should be 'it is quiet'\n- 'family live' should be 'family lives'\n- 'in future' should be 'in the future'\n- 'good place' should be 'a good place'\n- 'for live' should be 'to live'"
    },
    # 403. V4/G4 - Person (Famous)
    {
        "sample_id": "syn_p2_v4_g4_0403",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a famous person you like.",
        "transcript_cleaned": "I like Cristiano Ronaldo. He is famous football player. He play for Portugal team. I see him on TV many time. He very strong and fast. He score many goal in matches. I like him because he work very hard. He help poor people also. I want to meet him one day. He is hero for me. He has many fan in the world. I buy his shirt last year. He look very handsome. I think he is best player. He inspire me to play sport. I watch all his game. He is very good man.",
        "word_count": 103,
        "response_type": "long_turn",
        "micro_flaws": ["article: 'famous football player' should be 'a famous football player'", "agreement: 'He play' should be 'He plays'", "plural: 'many time' should be 'many times'", "verb: 'He very strong' should be 'He is very strong'", "agreement: 'He score' should be 'He scores'", "plural: 'many goal' should be 'many goals'", "agreement: 'he work' should be 'he works'", "agreement: 'He help' should be 'He helps'", "article: 'is hero' should be 'is a hero'", "plural: 'many fan' should be 'many fans'", "tense: 'I buy' should be 'I bought'", "agreement: 'He look' should be 'He looks'", "article: 'is best player' should be 'is the best player'", "agreement: 'He inspire' should be 'He inspires'", "plural: 'all his game' should be 'all his games'", "article: 'good man' should be 'a good man'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR4] Limited range: 'famous', 'football player', 'team', 'strong', 'fast', 'score', 'goal', 'hard', 'poor', 'meet', 'hero', 'fan', 'shirt', 'handsome', 'best', 'good'. Basic adjectives and nouns. >Band 3: Basic meaning conveyed. Not Band 5: Minimal range.",
        "grammar_reason": "[GRA4] Only simple sentences. systematic Subject-verb agreement errors ('He play', 'He score', 'he work', 'He help', 'He look'). Missing articles and verbs ('He very strong', 'is hero'). >Band 3: Simple forms recognizable. Not Band 5: Errors are very frequent.",
        "vocabulary": 4,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a famous person you like.\n\nTranscript: I like Cristiano Ronaldo. He is famous football player. He play for Portugal team. I see him on TV many time. He very strong and fast. He score many goal in matches. I like him because he work very hard. He help poor people also. I want to meet him one day. He is hero for me. He has many fan in the world. I buy his shirt last year. He look very handsome. I think he is best player. He inspire me to play sport. I watch all his game. He is very good man.\n\nWord Count: 103 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Basic vocabulary: 'famous', 'strong', 'fast', 'good'. Very repetitive. No complex words.\n\n>Band 3: Can identify person.\n\nNot Band 5: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Simple sentences only. Agreement errors are constant ('He play', 'He score'). Missing verbs and articles.\n\n>Band 3: Simple sentences attempted.\n\nNot Band 5: Errors cause strain.\n\n**Micro flaws identified:**\n- 'famous football player' should be 'a famous football player'\n- 'He play' should be 'He plays'\n- 'many time' should be 'many times'\n- 'He very strong' should be 'He is very strong'\n- 'He score' should be 'He scores'\n- 'many goal' should be 'many goals'\n- 'he work' should be 'he works'\n- 'He help' should be 'He helps'\n- 'is hero' should be 'is a hero'\n- 'many fan' should be 'many fans'\n- 'I buy' should be 'I bought'\n- 'He look' should be 'He looks'\n- 'is best player' should be 'is the best player'\n- 'He inspire' should be 'He inspires'\n- 'all his game' should be 'all his games'\n- 'good man' should be 'a good man'"
    },
    # 404. V4/G4 - Object (Gift)
    {
        "sample_id": "syn_p2_v4_g4_0404",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a gift you received.",
        "transcript_cleaned": "I receive a watch for my birthday last month. My mother give it to me. It is silver watch. It look very nice. I wear it every day. It help me know time. I happy when I see it. It is expensive gift. My mother buy it in big shop. I say thank you to her. I keep it in box when I sleep. It is my favorite thing. I never lose it. I like watch very much. It make me feel good. I want to buy gift for my mother too next time.",
        "word_count": 101,
        "response_type": "long_turn",
        "micro_flaws": ["tense: 'I receive' should be 'I received'", "tense: 'My mother give' should be 'My mother gave'", "article: 'silver watch' should be 'a silver watch'", "agreement: 'It look' should be 'It looks'", "agreement: 'It help' should be 'It helps'", "verb: 'I happy' should be 'I am happy'", "article: 'expensive gift' should be 'an expensive gift'", "tense: 'My mother buy' should be 'My mother bought'", "article: 'in big shop' should be 'in a big shop'", "article: 'in box' should be 'in a box'", "article: 'like watch' should be 'like the watch'", "agreement: 'It make' should be 'It makes'", "article: 'buy gift' should be 'buy a gift'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR4] Limited range: 'watch', 'birthday', 'mother', 'silver', 'nice', 'time', 'happy', 'expensive', 'shop', 'box', 'favorite', 'lose', 'good'. Basic and repetitive. >Band 3: Communicates basic idea. Not Band 5: No descriptive variety.",
        "grammar_reason": "[GRA4] Only simple sentences. Systematic tense errors ('I receive', 'mother give', 'mother buy'). Subject-verb agreement errors ('It look', 'It help', 'It make'). Missing articles. >Band 3: Basic structures. Not Band 5: Errors are pervasive.",
        "vocabulary": 4,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a gift you received.\n\nTranscript: I receive a watch for my birthday last month. My mother give it to me. It is silver watch. It look very nice. I wear it every day. It help me know time. I happy when I see it. It is expensive gift. My mother buy it in big shop. I say thank you to her. I keep it in box when I sleep. It is my favorite thing. I never lose it. I like watch very much. It make me feel good. I want to buy gift for my mother too next time.\n\nWord Count: 101 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Basic words: 'watch', 'nice', 'good'. Very simple description. No range.\n\n>Band 3: Basic meaning.\n\nNot Band 5: Too repetitive.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Simple sentences only. Frequent tense and agreement errors ('I receive', 'It look'). Missing articles.\n\n>Band 3: Can produce simple phrases.\n\nNot Band 5: Systematic errors.\n\n**Micro flaws identified:**\n- 'I receive' should be 'I received'\n- 'My mother give' should be 'My mother gave'\n- 'silver watch' should be 'a silver watch'\n- 'It look' should be 'It looks'\n- 'It help' should be 'It helps'\n- 'I happy' should be 'I am happy'\n- 'expensive gift' should be 'an expensive gift'\n- 'My mother buy' should be 'My mother bought'\n- 'in big shop' should be 'in a big shop'\n- 'in box' should be 'in a box'\n- 'like watch' should be 'like the watch'\n- 'It make' should be 'It makes'\n- 'buy gift' should be 'buy a gift'"
    },
    # 405. V4/G4 - Activity (Weekend)
    {
        "sample_id": "syn_p2_v4_g4_0405",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe what you do on weekends.",
        "transcript_cleaned": "On weekend, I usually stay at home. I sleep late in morning. Then I eat breakfast with family. We eat egg and bread. After that, I watch TV. I like watch cartoon. In afternoon, I play game on phone. Sometimes I go park with friend. We play football there. It is fun. In evening, my mother cook dinner. The food is very tasty. I help her clean dish. Then I do homework. I go sleep at 10 pm. I like weekend because no school. It is relax time for me. I happy on Saturday and Sunday.",
        "word_count": 104,
        "response_type": "long_turn",
        "micro_flaws": ["article: 'On weekend' should be 'On the weekend'", "article: 'in morning' should be 'in the morning'", "plural: 'eat egg' should be 'eat eggs'", "verb: 'like watch' should be 'like watching'", "cartoon: 'cartoon' should be 'cartoons'", "article: 'In afternoon' should be 'In the afternoon'", "game: 'play game' should be 'play games'", "preposition: 'go park' should be 'go to the park'", "article: 'In evening' should be 'In the evening'", "agreement: 'mother cook' should be 'cooks'", "plural: 'clean dish' should be 'clean the dishes'", "verb: 'go sleep' should be 'go to sleep'", "verb: 'no school' should be 'there is no school'", "adjective: 'relax time' should be 'relaxing time'", "verb: 'I happy' should be 'I am happy'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR4] Limited range: 'stay at home', 'sleep', 'breakfast', 'family', 'egg', 'bread', 'watch TV', 'cartoon', 'game', 'phone', 'park', 'football', 'fun', 'dinner', 'tasty', 'clean', 'homework', 'school', 'relax', 'happy'. Basic daily routine vocabulary. >Band 3: Understandable. Not Band 5: Very limited.",
        "grammar_reason": "[GRA4] Simple sentences. Frequent errors in articles ('in morning', 'in afternoon'), verb forms ('like watch', 'go sleep'), and agreement ('mother cook'). >Band 3: Basic structures recognizable. Not Band 5: Errors are frequent.",
        "vocabulary": 4,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe what you do on weekends.\n\nTranscript: On weekend, I usually stay at home. I sleep late in morning. Then I eat breakfast with family. We eat egg and bread. After that, I watch TV. I like watch cartoon. In afternoon, I play game on phone. Sometimes I go park with friend. We play football there. It is fun. In evening, my mother cook dinner. The food is very tasty. I help her clean dish. Then I do homework. I go sleep at 10 pm. I like weekend because no school. It is relax time for me. I happy on Saturday and Sunday.\n\nWord Count: 104 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Basic vocabulary: 'sleep', 'eat', 'play'. No variation. Frequent repetition.\n\n>Band 3: Can describe routine.\n\nNot Band 5: Vocabulary is too simple.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Simple sentences only. Systematic errors in articles, plurals, and verbs ('like watch', 'mother cook').\n\n>Band 3: Simple structures.\n\nNot Band 5: Errors are systematic.\n\n**Micro flaws identified:**\n- 'On weekend' should be 'On the weekend'\n- 'in morning' should be 'in the morning'\n- 'eat egg' should be 'eat eggs'\n- 'like watch' should be 'like watching'\n- 'watch cartoon' should be 'watch cartoons'\n- 'In afternoon' should be 'In the afternoon'\n- 'play game' should be 'play games'\n- 'go park' should be 'go to the park'\n- 'In evening' should be 'In the evening'\n- 'mother cook' should be 'mother cooks'\n- 'clean dish' should be 'clean the dishes'\n- 'go sleep' should be 'go to sleep'\n- 'no school' should be 'there is no school'\n- 'relax time' should be 'relaxing time'\n- 'I happy' should be 'I am happy'"
    },
    # 406. V4/G4 - Book (Favorite)
    {
        "sample_id": "syn_p2_v4_g4_0406",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a book you like.",
        "transcript_cleaned": "I like book called Harry Potter. It is story about magic boy. He go to magic school. He have two friend, Ron and Hermione. They learn magic together. The book is very big. I read it many time. It is exciting story. Bad man want to kill Harry. But Harry is strong and brave. He fight bad man. I like this book because it interesting. I saw movie also. But book is better. I want to be wizard like Harry. I read it in my room. It take me one month to finish. It is good book.",
        "word_count": 101,
        "response_type": "long_turn",
        "micro_flaws": ["article: 'like book' should be 'like a book'", "article: 'is story' should be 'is a story'", "article: 'magic boy' should be 'a magic boy'", "agreement: 'He go' should be 'He goes'", "agreement: 'He have' should be 'He has'", "plural: 'two friend' should be 'two friends'", "plural: 'many time' should be 'many times'", "article: 'exciting story' should be 'an exciting story'", "article: 'Bad man' should be 'The bad man'", "agreement: 'want to' should be 'wants to'", "agreement: 'He fight' should be 'He fights'", "verb: 'it interesting' should be 'it is interesting'", "article: 'saw movie' should be 'saw the movie'", "article: 'book is' should be 'the book is'", "article: 'be wizard' should be 'be a wizard'", "agreement: 'It take' should be 'It took'", "article: 'good book' should be 'a good book'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR4] Limited range: 'book', 'magic', 'boy', 'school', 'friend', 'big', 'read', 'story', 'bad man', 'kill', 'strong', 'brave', 'fight', 'interesting', 'movie', 'better', 'wizard', 'room'. Basic and repetitive. >Band 3: Basic meaning conveyed. Not Band 5: Minimal descriptive language.",
        "grammar_reason": "[GRA4] Only simple sentences. Constant errors in agreement ('He go', 'He have', 'He fight', 'It take'), articles, and plurals. >Band 3: Can produce simple forms. Not Band 5: Errors are pervasive.",
        "vocabulary": 4,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a book you like.\n\nTranscript: I like book called Harry Potter. It is story about magic boy. He go to magic school. He have two friend, Ron and Hermione. They learn magic together. The book is very big. I read it many time. It is exciting story. Bad man want to kill Harry. But Harry is strong and brave. He fight bad man. I like this book because it interesting. I saw movie also. But book is better. I want to be wizard like Harry. I read it in my room. It take me one month to finish. It is good book.\n\nWord Count: 101 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Basic words: 'book', 'magic', 'friend', 'bad'. Very limited range. Repetitive.\n\n>Band 3: Basic story told.\n\nNot Band 5: No variation.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Simple sentences only. Frequent errors in agreement ('He go', 'He have'), articles, and plurals. Strain for listener.\n\n>Band 3: Basic structures.\n\nNot Band 5: Systematic errors.\n\n**Micro flaws identified:**\n- 'like book' should be 'like a book'\n- 'is story' should be 'is a story'\n- 'magic boy' should be 'a magic boy'\n- 'He go' should be 'He goes'\n- 'He have' should be 'He has'\n- 'two friend' should be 'two friends'\n- 'many time' should be 'many times'\n- 'exciting story' should be 'an exciting story'\n- 'Bad man' should be 'The bad man'\n- 'want to' should be 'wants to'\n- 'He fight' should be 'He fights'\n- 'it interesting' should be 'it is interesting'\n- 'saw movie' should be 'saw the movie'\n- 'book is' should be 'the book is'\n- 'be wizard' should be 'be a wizard'\n- 'It take' should be 'It took'\n- 'good book' should be 'a good book'"
    },
    # 407. V4/G4 - Place (Shop)
    {
        "sample_id": "syn_p2_v4_g4_0407",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a shop you often go to.",
        "transcript_cleaned": "I often go to supermarket near my house. It is big shop. It sell many things. I go there with my mother. We buy food for dinner. They have vegetable, fruit, and meat. The price is cheap. I like buy chocolate there. The shop is very clean. People who work there is nice. Sometimes it is crowded. We wait in line long time. I go there every Sunday. It is easy for me to walk there. I like this shop because it have everything I need. It is good place for shopping.",
        "word_count": 103,
        "response_type": "long_turn",
        "micro_flaws": ["article: 'go to supermarket' should be 'go to a/the supermarket'", "article: 'big shop' should be 'a big shop'", "agreement: 'It sell' should be 'It sells'", "plural: 'vegetable' should be 'vegetables'", "plural: 'fruit' should be 'fruits'", "verb: 'like buy' should be 'like buying'", "agreement: 'work there is' should be 'work there are'", "preposition: 'wait in line long time' should be 'wait in line for a long time'", "agreement: 'it have' should be 'it has'", "article: 'good place' should be 'a good place'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR4] Limited range: 'supermarket', 'house', 'big', 'shop', 'sell', 'food', 'dinner', 'vegetable', 'fruit', 'meat', 'price', 'cheap', 'chocolate', 'clean', 'crowded', 'wait', 'line', 'walk'. Basic shopping vocabulary. >Band 3: Communicates meaning. Not Band 5: Minimal range.",
        "grammar_reason": "[GRA4] Only simple sentences. Frequent errors in agreement ('It sell', 'it have', 'People is'), articles, and plurals. >Band 3: Simple structures recognizable. Not Band 5: Errors are frequent.",
        "vocabulary": 4,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a shop you often go to.\n\nTranscript: I often go to supermarket near my house. It is big shop. It sell many things. I go there with my mother. We buy food for dinner. They have vegetable, fruit, and meat. The price is cheap. I like buy chocolate there. The shop is very clean. People who work there is nice. Sometimes it is crowded. We wait in line long time. I go there every Sunday. It is easy for me to walk there. I like this shop because it have everything I need. It is good place for shopping.\n\nWord Count: 103 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Basic vocabulary: 'shop', 'sell', 'buy', 'food'. Repetitive. No descriptive language.\n\n>Band 3: Basic meaning.\n\nNot Band 5: Limited range.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Simple sentences only. Agreement errors ('It sell', 'People is', 'it have'). Missing articles and prepositions.\n\n>Band 3: Simple structures.\n\nNot Band 5: Errors are systematic.\n\n**Micro flaws identified:**\n- 'go to supermarket' should be 'go to the supermarket'\n- 'big shop' should be 'a big shop'\n- 'It sell' should be 'It sells'\n- 'vegetable' should be 'vegetables'\n- 'fruit' should be 'fruits'\n- 'like buy' should be 'like buying'\n- 'work there is' should be 'work there are'\n- 'wait in line long time' should be 'wait in line for a long time'\n- 'it have' should be 'it has'\n- 'good place' should be 'a good place'"
    },
    # 408. V4/G4 - Movie (Seen)
    {
        "sample_id": "syn_p2_v4_g4_0408",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a movie you saw recently.",
        "transcript_cleaned": "I saw movie called Spider-Man last week. I go with my friend to cinema. It is action movie. Spider-Man is very strong man. He wear red and blue suit. He jump very high. He fight bad guys. The movie is very exciting. There are many explosion. I like when he fly in city. He save people from danger. My friend also like it. We eat popcorn and drink cola. The movie is two hour long. I want watch it again. It is best movie I see. Spider-Man is my favorite hero.",
        "word_count": 104,
        "response_type": "long_turn",
        "micro_flaws": ["article: 'saw movie' should be 'saw a movie'", "tense: 'I go' should be 'I went'", "article: 'to cinema' should be 'to the cinema'", "article: 'action movie' should be 'an action movie'", "article: 'strong man' should be 'a strong man'", "agreement: 'He wear' should be 'He wears'", "article: 'red and blue suit' should be 'a red and blue suit'", "agreement: 'He jump' should be 'He jumps'", "agreement: 'He fight' should be 'He fights'", "plural: 'many explosion' should be 'many explosions'", "verb: 'like when' should be 'liked it when'", "agreement: 'he fly' should be 'he flies'", "article: 'in city' should be 'in the city'", "agreement: 'He save' should be 'He saves'", "agreement: 'friend also like' should be 'friend also liked'", "plural: 'two hour' should be 'two hours'", "verb: 'want watch' should be 'want to watch'", "article: 'is best movie' should be 'is the best movie'", "tense: 'I see' should be 'I have seen'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR4] Limited range: 'movie', 'cinema', 'action', 'strong', 'suit', 'jump', 'fight', 'bad guys', 'exciting', 'explosion', 'fly', 'save', 'danger', 'popcorn', 'drink', 'long', 'best', 'hero'. Basic and repetitive. >Band 3: Basic idea conveyed. Not Band 5: Minimal description.",
        "grammar_reason": "[GRA4] Only simple sentences. Systematic errors in tense ('I go', 'He wear', 'He fight'), agreement, and articles. >Band 3: Simple structures. Not Band 5: Errors are pervasive.",
        "vocabulary": 4,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a movie you saw recently.\n\nTranscript: I saw movie called Spider-Man last week. I go with my friend to cinema. It is action movie. Spider-Man is very strong man. He wear red and blue suit. He jump very high. He fight bad guys. The movie is very exciting. There are many explosion. I like when he fly in city. He save people from danger. My friend also like it. We eat popcorn and drink cola. The movie is two hour long. I want watch it again. It is best movie I see. Spider-Man is my favorite hero.\n\nWord Count: 104 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Basic vocabulary: 'movie', 'strong', 'fight', 'exciting'. Very simple. No complex words.\n\n>Band 3: Basic plot described.\n\nNot Band 5: Lack of variety.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Simple sentences only. Frequent errors in tense ('I go', 'He fight') and agreement. Missing articles.\n\n>Band 3: Simple structures.\n\nNot Band 5: Errors are systematic.\n\n**Micro flaws identified:**\n- 'saw movie' should be 'saw a movie'\n- 'I go' should be 'I went'\n- 'to cinema' should be 'to the cinema'\n- 'action movie' should be 'an action movie'\n- 'strong man' should be 'a strong man'\n- 'He wear' should be 'He wears'\n- 'red and blue suit' should be 'a red and blue suit'\n- 'He jump' should be 'He jumps'\n- 'He fight' should be 'He fights'\n- 'many explosion' should be 'many explosions'\n- 'like when' should be 'liked it when'\n- 'he fly' should be 'he flies'\n- 'in city' should be 'in the city'\n- 'He save' should be 'He saves'\n- 'friend also like' should be 'friend also liked'\n- 'two hour' should be 'two hours'\n- 'want watch' should be 'want to watch'\n- 'is best movie' should be 'is the best movie'\n- 'I see' should be 'I have seen'"
    },
    # 409. V4/G4 - Exercise (Daily)
    {
        "sample_id": "syn_p2_v4_g4_0409",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe an exercise you do daily.",
        "transcript_cleaned": "I do running every morning. It is good exercise. I wake up at 6 am. I put on my shoe. I run in park near my house. I run for 30 minute. It make me feel tired but happy. I see many people running too. We smile to each other. Running make my leg strong. It is good for health. I listen music when I run. It help me run fast. After run, I go home and take shower. Then I eat breakfast. I do this every day. I want to lose weight. It is hard but I try.",
        "word_count": 105,
        "response_type": "long_turn",
        "micro_flaws": ["verb: 'do running' should be 'go running' or 'run'", "plural: 'my shoe' should be 'my shoes'", "article: 'in park' should be 'in the park'", "plural: '30 minute' should be '30 minutes'", "agreement: 'It make' should be 'It makes'", "preposition: 'smile to' should be 'smile at'", "agreement: 'Running make' should be 'Running makes'", "plural: 'my leg' should be 'my legs'", "verb: 'listen music' should be 'listen to music'", "agreement: 'It help' should be 'It helps'", "article: 'After run' should be 'After running' or 'After the run'", "article: 'take shower' should be 'take a shower'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR4] Limited range: 'running', 'exercise', 'wake up', 'shoe', 'park', 'tired', 'happy', 'smile', 'leg', 'strong', 'health', 'music', 'fast', 'shower', 'breakfast', 'lose weight', 'hard'. Basic vocabulary. >Band 3: Basic meaning. Not Band 5: Minimal range.",
        "grammar_reason": "[GRA4] Only simple sentences. Frequent errors in agreement ('It make', 'Running make', 'It help'), plurals ('shoe', 'leg'), and prepositions ('listen music', 'smile to'). >Band 3: Simple structures. Not Band 5: Errors are frequent.",
        "vocabulary": 4,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe an exercise you do daily.\n\nTranscript: I do running every morning. It is good exercise. I wake up at 6 am. I put on my shoe. I run in park near my house. I run for 30 minute. It make me feel tired but happy. I see many people running too. We smile to each other. Running make my leg strong. It is good for health. I listen music when I run. It help me run fast. After run, I go home and take shower. Then I eat breakfast. I do this every day. I want to lose weight. It is hard but I try.\n\nWord Count: 105 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Basic vocabulary: 'running', 'exercise', 'happy', 'strong'. Repetitive. No complex words.\n\n>Band 3: Routine described.\n\nNot Band 5: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Simple sentences only. Systematic errors in agreement ('It make', 'It help'), plurals, and prepositions.\n\n>Band 3: Simple forms.\n\nNot Band 5: Errors are pervasive.\n\n**Micro flaws identified:**\n- 'do running' should be 'go running'\n- 'my shoe' should be 'my shoes'\n- 'in park' should be 'in the park'\n- '30 minute' should be '30 minutes'\n- 'It make' should be 'It makes'\n- 'smile to' should be 'smile at'\n- 'Running make' should be 'Running makes'\n- 'my leg' should be 'my legs'\n- 'listen music' should be 'listen to music'\n- 'It help' should be 'It helps'\n- 'After run' should be 'After running'\n- 'take shower' should be 'take a shower'"
    },
    # 410. V4/G4 - Family (Describe)
    {
        "sample_id": "syn_p2_v4_g4_0410",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe your family.",
        "transcript_cleaned": "I have small family. There are four people: father, mother, sister, and me. My father is teacher. He work in school. He is very tall and kind. My mother is nurse. She work in hospital. She cook very good food. My sister is student. She study at university. We live in house in Hanoi. We love each other very much. On Sunday, we go out together. We eat lunch in restaurant. Sometimes we watch TV at home. My family is very important to me. They help me when I have problem. I want to make them happy. We are happy family.",
        "word_count": 103,
        "response_type": "long_turn",
        "micro_flaws": ["article: 'have small family' should be 'have a small family'", "article: 'is teacher' should be 'is a teacher'", "agreement: 'He work' should be 'He works'", "article: 'is nurse' should be 'is a nurse'", "agreement: 'She work' should be 'She works'", "article: 'in hospital' should be 'in a hospital'", "agreement: 'She cook' should be 'She cooks'", "article: 'is student' should be 'is a student'", "agreement: 'She study' should be 'She studies'", "article: 'in house' should be 'in a house'", "article: 'in restaurant' should be 'in a restaurant'", "plural: 'have problem' should be 'have problems'", "article: 'are happy family' should be 'are a happy family'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "vocab_reason": "[LR4] Limited range: 'family', 'father', 'mother', 'sister', 'teacher', 'school', 'tall', 'kind', 'nurse', 'hospital', 'cook', 'food', 'student', 'university', 'house', 'love', 'lunch', 'restaurant', 'watch TV', 'important', 'problem', 'happy'. Basic family vocabulary. >Band 3: Communicates basic info. Not Band 5: No variation.",
        "grammar_reason": "[GRA4] Only simple sentences. Systematic errors in agreement ('He work', 'She work', 'She cook', 'She study') and articles. >Band 3: Simple structures recognizable. Not Band 5: Errors are very frequent.",
        "vocabulary": 4,
        "grammar": 4,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe your family.\n\nTranscript: I have small family. There are four people: father, mother, sister, and me. My father is teacher. He work in school. He is very tall and kind. My mother is nurse. She work in hospital. She cook very good food. My sister is student. She study at university. We live in house in Hanoi. We love each other very much. On Sunday, we go out together. We eat lunch in restaurant. Sometimes we watch TV at home. My family is very important to me. They help me when I have problem. I want to make them happy. We are happy family.\n\nWord Count: 103 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Basic words: 'family', 'teacher', 'nurse', 'house'. Repetitive simple sentences. No range.\n\n>Band 3: Basic info.\n\nNot Band 5: Limited vocabulary.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Simple sentences only. Systematic agreement errors ('He work', 'She cook') and missing articles.\n\n>Band 3: Simple sentences.\n\nNot Band 5: Errors are pervasive.\n\n**Micro flaws identified:**\n- 'have small family' should be 'have a small family'\n- 'is teacher' should be 'is a teacher'\n- 'He work' should be 'He works'\n- 'is nurse' should be 'is a nurse'\n- 'She work' should be 'She works'\n- 'in hospital' should be 'in a hospital'\n- 'She cook' should be 'She cooks'\n- 'is student' should be 'is a student'\n- 'She study' should be 'She studies'\n- 'in house' should be 'in a house'\n- 'in restaurant' should be 'in a restaurant'\n- 'have problem' should be 'have problems'\n- 'are happy family' should be 'are a happy family'"
    }
]

with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
    for sample in samples:
        f.write(json.dumps(sample) + '\n')
