import json

OUTPUT_FILE = "ielts-data/phase3/v76_review_output/synthetic_batches/batch_p2_11.jsonl"

samples = [
    # 531. V8/G9 - Book (Read)
    {
        "sample_id": "syn_p2_v8_g9_0531",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a book you read recently.",
        "transcript_cleaned": "I recently finished reading 'Educated' by Tara Westover, a memoir that left an indelible mark on me. It chronicles her upbringing in a survivalist family in rural Idaho, isolated from mainstream society. What struck me most was her thirst for knowledge despite the overwhelming obstacles she faced. Her journey from having no formal education to earning a PhD from Cambridge is nothing short of miraculous. The prose is evocative and poignant, capturing the complexity of family dynamics. It compelled me to reflect on the transformative power of education. This book is a testament to the resilience of the human spirit.",
        "word_count": 99,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR8] Vocabulary: 'memoir', 'indelible mark', 'chronicles', 'upbringing', 'survivalist', 'isolated', 'mainstream society', 'thirst for knowledge', 'overwhelming obstacles', 'formal education', 'miraculous', 'prose', 'evocative', 'poignant', 'complexity', 'dynamics', 'compelled', 'reflect', 'transformative power', 'testament', 'resilience'. Very sophisticated. >Band 7: Precise vocabulary. Not Band 9: Some phrases are common.",
        "grammar_reason": "[GRA9] Full range of structures used naturally. 'A memoir that left...' (Appositive + Relative). 'Isolated from mainstream society' (Participle phrase). 'What struck me most was...' (Cleft sentence). 'Despite the overwhelming obstacles...' (Prepositional phrase). Error-free. >Band 8: Native-like control.",
        "vocabulary": 8,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a book you read recently.\n\nTranscript: I recently finished reading 'Educated' by Tara Westover, a memoir that left an indelible mark on me. It chronicles her upbringing in a survivalist family in rural Idaho, isolated from mainstream society. What struck me most was her thirst for knowledge despite the overwhelming obstacles she faced. Her journey from having no formal education to earning a PhD from Cambridge is nothing short of miraculous. The prose is evocative and poignant, capturing the complexity of family dynamics. It compelled me to reflect on the transformative power of education. This book is a testament to the resilience of the human spirit.\n\nWord Count: 99 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses sophisticated vocabulary: 'indelible', 'chronicles', 'evocative', 'testament'. Precise.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Lacks native-like flow.\n\n**Idiom present:** Yes ('nothing short of')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Uses a full range of structures naturally and accurately. Cleft sentences and participle phrases are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    },
    # 532. V8/G9 - Place (Travel)
    {
        "sample_id": "syn_p2_v8_g9_0532",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a place you would like to travel to.",
        "transcript_cleaned": "I have always dreamed of visiting the Galapagos Islands, a unique archipelago renowned for its biodiversity. I am fascinated by the idea of observing wildlife that has evolved in isolation, unafraid of humans. It would be a surreal experience to swim with marine iguanas and sea lions. The prospect of walking on volcanic landscapes that look prehistoric is incredibly enticing. I want to immerse myself in the pristine natural environment, far removed from urban chaos. This trip would be a pilgrimage for any nature enthusiast. It represents the ultimate adventure in ecological discovery.",
        "word_count": 94,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR8] Vocabulary: 'archipelago', 'renowned', 'biodiversity', 'observing', 'wildlife', 'evolved', 'isolation', 'unafraid', 'surreal', 'marine iguanas', 'prospect', 'volcanic landscapes', 'prehistoric', 'enticing', 'immerse', 'pristine', 'urban chaos', 'pilgrimage', 'enthusiast', 'ecological discovery'. Very sophisticated. >Band 7: Precise vocabulary. Not Band 9: Some phrases are common.",
        "grammar_reason": "[GRA9] Full range of structures used naturally. 'Renowned for its biodiversity' (Participle phrase). 'That has evolved in isolation' (Relative clause). 'Unafraid of humans' (Adjective phrase). 'Far removed from urban chaos' (Adjective phrase). Error-free. >Band 8: Native-like control.",
        "vocabulary": 8,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a place you would like to travel to.\n\nTranscript: I have always dreamed of visiting the Galapagos Islands, a unique archipelago renowned for its biodiversity. I am fascinated by the idea of observing wildlife that has evolved in isolation, unafraid of humans. It would be a surreal experience to swim with marine iguanas and sea lions. The prospect of walking on volcanic landscapes that look prehistoric is incredibly enticing. I want to immerse myself in the pristine natural environment, far removed from urban chaos. This trip would be a pilgrimage for any nature enthusiast. It represents the ultimate adventure in ecological discovery.\n\nWord Count: 94 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses sophisticated vocabulary: 'archipelago', 'surreal', 'enticing', 'pilgrimage'. Precise.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Lacks native-like flow.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Uses a full range of structures naturally and accurately. Participle phrases and relative clauses are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    },
    # 533. V8/G9 - Event (Festival)
    {
        "sample_id": "syn_p2_v8_g9_0533",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a festival you have attended.",
        "transcript_cleaned": "I attended the Holi Festival in India, which was a kaleidoscope of color and joy. It is a celebration of spring, signifying the triumph of good over evil. The streets were awash with vibrant powders, thrown by enthusiastic revelers. I was swept up in the contagious energy of the crowd, dancing to traditional drums. Strangers embraced each other, dissolving social barriers in a cloud of pink and blue dust. The atmosphere was electrifying, filled with laughter and song. It was a liberating experience that allowed me to let go of my inhibitions completely.",
        "word_count": 96,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR8] Vocabulary: 'kaleidoscope', 'signifying', 'triumph', 'awash', 'vibrant powders', 'revelers', 'swept up', 'contagious energy', 'embraced', 'dissolving', 'social barriers', 'electrifying', 'liberating', 'inhibitions'. Very sophisticated. >Band 7: Precise vocabulary. Not Band 9: Some phrases are common.",
        "grammar_reason": "[GRA9] Full range of structures used naturally. 'Which was a kaleidoscope...' (Relative clause). 'Signifying the triumph...' (Participle phrase). 'Thrown by enthusiastic revelers' (Participle phrase). 'Dissolving social barriers' (Participle phrase). Error-free. >Band 8: Native-like control.",
        "vocabulary": 8,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a festival you have attended.\n\nTranscript: I attended the Holi Festival in India, which was a kaleidoscope of color and joy. It is a celebration of spring, signifying the triumph of good over evil. The streets were awash with vibrant powders, thrown by enthusiastic revelers. I was swept up in the contagious energy of the crowd, dancing to traditional drums. Strangers embraced each other, dissolving social barriers in a cloud of pink and blue dust. The atmosphere was electrifying, filled with laughter and song. It was a liberating experience that allowed me to let go of my inhibitions completely.\n\nWord Count: 96 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses sophisticated vocabulary: 'kaleidoscope', 'revelers', 'electrifying', 'inhibitions'. Precise.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Lacks native-like flow.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Uses a full range of structures naturally and accurately. Participle phrases are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    },
    # 534. V8/G9 - Object (Old)
    {
        "sample_id": "syn_p2_v8_g9_0534",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe an antique you possess.",
        "transcript_cleaned": "I possess a vintage pocket watch that has been passed down through four generations of my family. It is an exquisite artifact, encased in engraved silver with a porcelain face. Despite its age, the mechanical movement still functions with remarkable precision. I often marvel at the intricate craftsmanship required to assemble such a delicate instrument. It holds immense sentimental value, serving as a tangible link to my ancestors. Every time I wind it, I feel a sense of continuity and history. It is a treasured heirloom that I intend to preserve for my own descendants.",
        "word_count": 97,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR8] Vocabulary: 'possess', 'vintage', 'passed down', 'generations', 'exquisite artifact', 'encased', 'engraved', 'porcelain', 'mechanical movement', 'precision', 'marvel', 'intricate craftsmanship', 'assemble', 'delicate', 'immense sentimental value', 'tangible link', 'ancestors', 'continuity', 'treasured heirloom', 'preserve', 'descendants'. Very sophisticated. >Band 7: Precise vocabulary. Not Band 9: Some phrases are common.",
        "grammar_reason": "[GRA9] Full range of structures used naturally. 'That has been passed down...' (Relative clause + Passive). 'Encased in engraved silver' (Participle phrase). 'Required to assemble...' (Participle phrase). 'Serving as a tangible link' (Participle phrase). Error-free. >Band 8: Native-like control.",
        "vocabulary": 8,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe an antique you possess.\n\nTranscript: I possess a vintage pocket watch that has been passed down through four generations of my family. It is an exquisite artifact, encased in engraved silver with a porcelain face. Despite its age, the mechanical movement still functions with remarkable precision. I often marvel at the intricate craftsmanship required to assemble such a delicate instrument. It holds immense sentimental value, serving as a tangible link to my ancestors. Every time I wind it, I feel a sense of continuity and history. It is a treasured heirloom that I intend to preserve for my own descendants.\n\nWord Count: 97 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses sophisticated vocabulary: 'artifact', 'craftsmanship', 'heirloom', 'descendants'. Precise.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Lacks native-like flow.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Uses a full range of structures naturally and accurately. Passive voice and participle phrases are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    },
    # 535. V8/G9 - Person (Admire)
    {
        "sample_id": "syn_p2_v8_g9_0535",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a person you admire.",
        "transcript_cleaned": "I have profound admiration for Malala Yousafzai, a champion of education and women's rights. Her story of surviving an assassination attempt and continuing her advocacy is awe-inspiring. She articulates her vision for a world where every girl can learn and lead with such eloquence. Despite her youth, she possesses a wisdom and maturity that belies her age. Her unwavering courage in the face of extremism serves as a beacon of hope. I am deeply moved by her resilience and her ability to forgive. She exemplifies the power of one voice to change the world.",
        "word_count": 96,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR8] Vocabulary: 'profound admiration', 'champion', 'assassination attempt', 'advocacy', 'awe-inspiring', 'articulates', 'vision', 'eloquence', 'maturity', 'belies', 'unwavering courage', 'extremism', 'beacon of hope', 'resilience', 'exemplifies'. Very sophisticated. >Band 7: Precise vocabulary. Not Band 9: Some phrases are common.",
        "grammar_reason": "[GRA9] Full range of structures used naturally. 'Where every girl can learn...' (Relative clause). 'That belies her age' (Relative clause). 'In the face of extremism' (Prepositional phrase). 'To change the world' (Infinitive of purpose). Error-free. >Band 8: Native-like control.",
        "vocabulary": 8,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a person you admire.\n\nTranscript: I have profound admiration for Malala Yousafzai, a champion of education and women's rights. Her story of surviving an assassination attempt and continuing her advocacy is awe-inspiring. She articulates her vision for a world where every girl can learn and lead with such eloquence. Despite her youth, she possesses a wisdom and maturity that belies her age. Her unwavering courage in the face of extremism serves as a beacon of hope. I am deeply moved by her resilience and her ability to forgive. She exemplifies the power of one voice to change the world.\n\nWord Count: 96 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses sophisticated vocabulary: 'articulates', 'belies', 'unwavering', 'exemplifies'. Precise.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Lacks native-like flow.\n\n**Idiom present:** Yes ('beacon of hope')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Uses a full range of structures naturally and accurately. Relative clauses and prepositional phrases are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    },
    # 536. V8/G9 - Activity (Skill)
    {
        "sample_id": "syn_p2_v8_g9_0536",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a skill you want to learn.",
        "transcript_cleaned": "I am keen to acquire the skill of public speaking, which I consider invaluable for professional success. The ability to articulate ideas persuasively and command an audience is a powerful asset. I envision myself delivering compelling presentations that inspire and motivate others. Mastering the nuances of body language, tone, and pacing would require dedicated practice. I plan to join a Toastmasters club to receive constructive feedback and overcome my stage fright. Developing this skill would boost my self-confidence and open doors to new leadership opportunities. It is a challenge I am eager to embrace.",
        "word_count": 96,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR8] Vocabulary: 'keen', 'acquire', 'invaluable', 'articulate', 'persuasively', 'command', 'asset', 'envision', 'compelling', 'inspire', 'motivate', 'mastering', 'nuances', 'dedicated practice', 'constructive feedback', 'stage fright', 'self-confidence', 'leadership opportunities', 'embrace'. Very sophisticated. >Band 7: Precise vocabulary. Not Band 9: Some phrases are common.",
        "grammar_reason": "[GRA9] Full range of structures used naturally. 'Which I consider invaluable...' (Relative clause). 'Delivering compelling presentations...' (Participle phrase). 'Mastering the nuances... would require...' (Gerund subject + Modal). Error-free. >Band 8: Native-like control.",
        "vocabulary": 8,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a skill you want to learn.\n\nTranscript: I am keen to acquire the skill of public speaking, which I consider invaluable for professional success. The ability to articulate ideas persuasively and command an audience is a powerful asset. I envision myself delivering compelling presentations that inspire and motivate others. Mastering the nuances of body language, tone, and pacing would require dedicated practice. I plan to join a Toastmasters club to receive constructive feedback and overcome my stage fright. Developing this skill would boost my self-confidence and open doors to new leadership opportunities. It is a challenge I am eager to embrace.\n\nWord Count: 96 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses sophisticated vocabulary: 'invaluable', 'articulate', 'nuances', 'constructive'. Precise.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Lacks native-like flow.\n\n**Idiom present:** Yes ('open doors')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Uses a full range of structures naturally and accurately. Gerund subjects and relative clauses are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    },
    # 537. V8/G9 - Place (Nature)
    {
        "sample_id": "syn_p2_v8_g9_0537",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a natural place you enjoy.",
        "transcript_cleaned": "I often retreat to a secluded forest trail near my home to find solace in nature. It is a sanctuary of ancient oaks and vibrant ferns, untouched by urban sprawl. The dappled sunlight filtering through the canopy creates an ethereal atmosphere. I enjoy listening to the symphony of birdsong and the rustling leaves. Walking there allows me to disconnect from digital distractions and practice mindfulness. The fresh, earthy scent of the woods is incredibly grounding. This connection with the natural world rejuvenates my spirit and restores my mental equilibrium.",
        "word_count": 91,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR8] Vocabulary: 'retreat', 'secluded', 'solace', 'sanctuary', 'ancient oaks', 'urban sprawl', 'dappled sunlight', 'filtering', 'canopy', 'ethereal', 'symphony', 'birdsong', 'rustling', 'disconnect', 'distractions', 'mindfulness', 'earthy scent', 'grounding', 'rejuvenates', 'equilibrium'. Very sophisticated. >Band 7: Precise vocabulary. Not Band 9: Some phrases are common.",
        "grammar_reason": "[GRA9] Full range of structures used naturally. 'Untouched by urban sprawl' (Participle phrase). 'Filtering through the canopy' (Participle phrase). 'Allows me to disconnect...' (Infinitive structure). Error-free. >Band 8: Native-like control.",
        "vocabulary": 8,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a natural place you enjoy.\n\nTranscript: I often retreat to a secluded forest trail near my home to find solace in nature. It is a sanctuary of ancient oaks and vibrant ferns, untouched by urban sprawl. The dappled sunlight filtering through the canopy creates an ethereal atmosphere. I enjoy listening to the symphony of birdsong and the rustling leaves. Walking there allows me to disconnect from digital distractions and practice mindfulness. The fresh, earthy scent of the woods is incredibly grounding. This connection with the natural world rejuvenates my spirit and restores my mental equilibrium.\n\nWord Count: 91 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses sophisticated vocabulary: 'solace', 'dappled', 'ethereal', 'equilibrium'. Precise.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Lacks native-like flow.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Uses a full range of structures naturally and accurately. Participle phrases are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    },
    # 538. V8/G9 - Activity (Creative)
    {
        "sample_id": "syn_p2_v8_g9_0538",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a creative activity you do.",
        "transcript_cleaned": "I engage in digital illustration as a means of artistic expression. Using a tablet and stylus, I create intricate character designs and landscapes. I enjoy the versatility of the medium, which allows for endless experimentation with color and texture. The process of bringing an abstract concept to life on the screen is deeply satisfying. I often lose track of time when I am in the flow state, focused entirely on my art. Sharing my work with an online community and receiving constructive critique helps me refine my skills. It is a passion that fuels my imagination.",
        "word_count": 98,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR8] Vocabulary: 'engage', 'digital illustration', 'artistic expression', 'stylus', 'intricate', 'versatility', 'experimentation', 'texture', 'abstract concept', 'satisfying', 'lose track of time', 'flow state', 'constructive critique', 'refine', 'passion', 'fuels', 'imagination'. Very sophisticated. >Band 7: Precise vocabulary. Not Band 9: Some phrases are common.",
        "grammar_reason": "[GRA9] Full range of structures used naturally. 'Using a tablet and stylus' (Participle phrase). 'Which allows for endless experimentation' (Relative clause). 'The process of bringing... is...' (Gerund phrase subject). 'Focused entirely on my art' (Participle phrase). Error-free. >Band 8: Native-like control.",
        "vocabulary": 8,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a creative activity you do.\n\nTranscript: I engage in digital illustration as a means of artistic expression. Using a tablet and stylus, I create intricate character designs and landscapes. I enjoy the versatility of the medium, which allows for endless experimentation with color and texture. The process of bringing an abstract concept to life on the screen is deeply satisfying. I often lose track of time when I am in the flow state, focused entirely on my art. Sharing my work with an online community and receiving constructive critique helps me refine my skills. It is a passion that fuels my imagination.\n\nWord Count: 98 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses sophisticated vocabulary: 'versatility', 'experimentation', 'critique', 'fuels'. Precise.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Lacks native-like flow.\n\n**Idiom present:** Yes ('lose track of time')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Uses a full range of structures naturally and accurately. Participle phrases and gerund phrases are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    },
    # 539. V8/G9 - Object (Technology)
    {
        "sample_id": "syn_p2_v8_g9_0539",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a piece of technology you like.",
        "transcript_cleaned": "I am enamored with my noise-cancelling headphones, which have revolutionized my daily commute. The technology employs sophisticated algorithms to filter out ambient noise, creating a bubble of silence. This allows me to immerse myself fully in podcasts or audiobooks without distraction. The audio quality is crystal clear, delivering rich bass and crisp highs. I appreciate the ergonomic design, which ensures comfort during prolonged use. They have become an indispensable tool for maintaining my focus and mental well-being in noisy environments. I frankly cannot imagine navigating the city without them.",
        "word_count": 91,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR8] Vocabulary: 'enamored', 'noise-cancelling', 'revolutionized', 'daily commute', 'employs', 'sophisticated algorithms', 'filter out', 'ambient noise', 'bubble of silence', 'immerse', 'distraction', 'crystal clear', 'rich bass', 'crisp highs', 'appreciate', 'ergonomic design', 'prolonged use', 'indispensable', 'maintaining', 'mental well-being'. Very sophisticated. >Band 7: Precise vocabulary. Not Band 9: Some phrases are common.",
        "grammar_reason": "[GRA9] Full range of structures used naturally. 'Which have revolutionized...' (Relative clause). 'Creating a bubble of silence' (Participle phrase). 'Allows me to immerse myself' (Infinitive structure). 'Which ensures comfort' (Relative clause). Error-free. >Band 8: Native-like control.",
        "vocabulary": 8,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a piece of technology you like.\n\nTranscript: I am enamored with my noise-cancelling headphones, which have revolutionized my daily commute. The technology employs sophisticated algorithms to filter out ambient noise, creating a bubble of silence. This allows me to immerse myself fully in podcasts or audiobooks without distraction. The audio quality is crystal clear, delivering rich bass and crisp highs. I appreciate the ergonomic design, which ensures comfort during prolonged use. They have become an indispensable tool for maintaining my focus and mental well-being in noisy environments. I frankly cannot imagine navigating the city without them.\n\nWord Count: 91 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses sophisticated vocabulary: 'enamored', 'ambient', 'ergonomic', 'indispensable'. Precise.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Lacks native-like flow.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Uses a full range of structures naturally and accurately. Relative clauses and participle phrases are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    },
    # 540. V8/G9 - Event (Sports)
    {
        "sample_id": "syn_p2_v8_g9_0540",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a sports match you enjoyed.",
        "transcript_cleaned": "I vividly recall watching the Olympic 100-meter sprint final, a spectacle of human speed and power. The tension in the stadium was palpable as the athletes took their positions. When the gun fired, they exploded from the blocks with incredible force. The race was a blur of motion, lasting less than ten seconds, yet it felt like an eternity. Seeing the winner cross the finish line and break the world record was electrifying. The crowd's roar was deafening, celebrating the pinnacle of athletic achievement. It was a historic moment that I felt privileged to witness.",
        "word_count": 99,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "vocab_reason": "[LR8] Vocabulary: 'vividly recall', 'spectacle', 'tension', 'palpable', 'exploded', 'blocks', 'incredible force', 'blur of motion', 'eternity', 'electrifying', 'deafening', 'pinnacle', 'athletic achievement', 'historic moment', 'privileged', 'witness'. Very sophisticated. >Band 7: Precise vocabulary. Not Band 9: Some phrases are common.",
        "grammar_reason": "[GRA9] Full range of structures used naturally. 'As the athletes took their positions' (Time clause). 'Lasting less than ten seconds' (Participle phrase). 'Seeing the winner... was...' (Gerund subject). 'Celebrating the pinnacle...' (Participle phrase). Error-free. >Band 8: Native-like control.",
        "vocabulary": 8,
        "grammar": 9,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a sports match you enjoyed.\n\nTranscript: I vividly recall watching the Olympic 100-meter sprint final, a spectacle of human speed and power. The tension in the stadium was palpable as the athletes took their positions. When the gun fired, they exploded from the blocks with incredible force. The race was a blur of motion, lasting less than ten seconds, yet it felt like an eternity. Seeing the winner cross the finish line and break the world record was electrifying. The crowd's roar was deafening, celebrating the pinnacle of athletic achievement. It was a historic moment that I felt privileged to witness.\n\nWord Count: 99 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses sophisticated vocabulary: 'spectacle', 'palpable', 'pinnacle', 'privileged'. Precise.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Lacks native-like flow.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Uses a full range of structures naturally and accurately. Gerund subjects and participle phrases are flawless.\n\n>Band 8: Native-like control.\n\n**Micro flaws identified:**\n- None."
    }
]

with open(OUTPUT_FILE, 'a', encoding='utf-8') as f:
    for sample in samples:
        f.write(json.dumps(sample) + '\n')
