import json

OUTPUT_FILE = "ielts-data/phase3/v76_review_output/synthetic_batches/batch_p2_10.jsonl"

samples = [
    # 491. V7/G7 - Book (Influence)
    {
        "sample_id": "syn_p2_v7_g7_0491",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a book that changed your opinion.",
        "transcript_cleaned": "I read a book called 'Sapiens' which profoundly impacted my worldview. It explores the history of humankind from a unique perspective. The author challenges conventional beliefs about society and progress. Before reading it, I assumed that history was a linear progression. However, the book argues that many modern developments are actually detrimental to our happiness. It made me question the value of consumerism and technology. The writing style is engaging and accessible, even for non-experts. I have recommended it to several friends who are interested in anthropology. It is a thought-provoking read that encourages critical thinking.",
        "word_count": 99,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR7] Vocabulary: 'profoundly impacted', 'worldview', 'unique perspective', 'conventional beliefs', 'linear progression', 'detrimental', 'consumerism', 'engaging', 'accessible', 'non-experts', 'anthropology', 'thought-provoking', 'critical thinking'. Very sophisticated. >Band 6: Precise vocabulary. Not Band 8: Some phrases are common.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'Which profoundly impacted my worldview' (Relative clause). 'Before reading it...' (Prepositional phrase). 'That many modern developments are...' (Noun clause). 'Who are interested in...' (Relative clause). Accurate.",
        "vocabulary": 7,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a book that changed your opinion.\n\nTranscript: I read a book called 'Sapiens' which profoundly impacted my worldview. It explores the history of humankind from a unique perspective. The author challenges conventional beliefs about society and progress. Before reading it, I assumed that history was a linear progression. However, the book argues that many modern developments are actually detrimental to our happiness. It made me question the value of consumerism and technology. The writing style is engaging and accessible, even for non-experts. I have recommended it to several friends who are interested in anthropology. It is a thought-provoking read that encourages critical thinking.\n\nWord Count: 99 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses sophisticated vocabulary: 'conventional', 'detrimental', 'consumerism'. Clear meaning.\n\n>Band 6: Advanced vocabulary.\n\nNot Band 8: Lacks native-like flow.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures accurately (relative clauses, noun clauses). Sentences are error-free.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Limited variety.\n\n**Micro flaws identified:**\n- None."
    },
    # 492. V7/G7 - Place (Historical)
    {
        "sample_id": "syn_p2_v7_g7_0492",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a historical building you admire.",
        "transcript_cleaned": "I admire the Taj Mahal in India, which is an architectural masterpiece. It was built in the 17th century as a mausoleum for the emperor's wife. The structure is made of white marble that changes color with the light. I am fascinated by the intricate carvings and precious stones embedded in the walls. It is a symbol of eternal love and devotion. Millions of tourists visit it annually to marvel at its beauty. The symmetry of the building and the surrounding gardens is breathtaking. It stands as a testament to the artistic achievements of the Mughal era.",
        "word_count": 99,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR7] Vocabulary: 'architectural masterpiece', 'mausoleum', 'emperor', 'structure', 'marble', 'intricate carvings', 'embedded', 'symbol', 'eternal love', 'devotion', 'annually', 'marvel', 'symmetry', 'breathtaking', 'testament', 'artistic achievements', 'era'. Very sophisticated. >Band 6: Precise vocabulary. Not Band 8: Some phrases are common.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'Which is an architectural masterpiece' (Relative clause). 'That changes color...' (Relative clause). 'Embedded in the walls' (Participle phrase). 'To marvel at its beauty' (Infinitive of purpose). Accurate.",
        "vocabulary": 7,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a historical building you admire.\n\nTranscript: I admire the Taj Mahal in India, which is an architectural masterpiece. It was built in the 17th century as a mausoleum for the emperor's wife. The structure is made of white marble that changes color with the light. I am fascinated by the intricate carvings and precious stones embedded in the walls. It is a symbol of eternal love and devotion. Millions of tourists visit it annually to marvel at its beauty. The symmetry of the building and the surrounding gardens is breathtaking. It stands as a testament to the artistic achievements of the Mughal era.\n\nWord Count: 99 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses topic words: 'mausoleum', 'intricate', 'symmetry', 'testament'. Meaning is clear.\n\n>Band 6: Advanced vocabulary.\n\nNot Band 8: Lacks native-like flow.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures accurately. Includes relative clauses and participle phrases. Good control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Limited variety.\n\n**Micro flaws identified:**\n- None."
    },
    # 493. V7/G7 - Activity (Project)
    {
        "sample_id": "syn_p2_v7_g7_0493",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a difficult task you completed.",
        "transcript_cleaned": "Completing my final year thesis was the most arduous task I have ever undertaken. It required extensive research and critical analysis of complex data. I spent months in the library, sifting through academic journals. The main challenge was organizing my arguments coherently. I had to revise my draft multiple times based on my supervisor's feedback. There were moments of frustration where I wanted to give up. However, I persevered and submitted it on time. Receiving a high grade was incredibly rewarding. It taught me the value of discipline and resilience in the face of adversity.",
        "word_count": 96,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR7] Vocabulary: 'arduous task', 'undertaken', 'extensive research', 'critical analysis', 'sifting', 'academic journals', 'organizing', 'coherently', 'revise', 'draft', 'supervisor', 'feedback', 'frustration', 'persevered', 'rewarding', 'discipline', 'resilience', 'adversity'. Very sophisticated. >Band 6: Precise vocabulary. Not Band 8: Some phrases are common.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'The most arduous task I have ever undertaken' (Superlative + Relative). 'Sifting through academic journals' (Participle phrase). 'Where I wanted to give up' (Relative clause). 'Based on my supervisor's feedback' (Participle phrase). Accurate.",
        "vocabulary": 7,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a difficult task you completed.\n\nTranscript: Completing my final year thesis was the most arduous task I have ever undertaken. It required extensive research and critical analysis of complex data. I spent months in the library, sifting through academic journals. The main challenge was organizing my arguments coherently. I had to revise my draft multiple times based on my supervisor's feedback. There were moments of frustration where I wanted to give up. However, I persevered and submitted it on time. Receiving a high grade was incredibly rewarding. It taught me the value of discipline and resilience in the face of adversity.\n\nWord Count: 96 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses sophisticated vocabulary: 'arduous', 'coherently', 'persevered', 'resilience'. Precise.\n\n>Band 6: Advanced vocabulary.\n\nNot Band 8: Lacks native-like flow.\n\n**Idiom present:** Yes ('in the face of adversity')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures accurately. Includes superlatives and participle phrases. Good control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Limited variety.\n\n**Micro flaws identified:**\n- None."
    },
    # 494. V7/G7 - Person (Friend)
    {
        "sample_id": "syn_p2_v7_g7_0494",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a friend who is important to you.",
        "transcript_cleaned": "I would like to describe my close friend, Sarah, whom I have known since kindergarten. She is a compassionate person who always puts others before herself. We share a deep bond based on mutual trust and understanding. Whenever I face a dilemma, she provides insightful advice that helps me gain clarity. She is also incredibly talented artistically, often creating beautiful paintings. I admire her ability to stay positive even in difficult situations. Her optimism is contagious and lifts my spirits. I cherish our friendship because it is authentic and supportive. She is truly a gem in my life.",
        "word_count": 100,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR7] Vocabulary: 'compassionate', 'puts others before herself', 'deep bond', 'mutual trust', 'dilemma', 'insightful', 'clarity', 'talented', 'artistically', 'admire', 'optimism', 'contagious', 'lifts my spirits', 'cherish', 'authentic', 'supportive', 'gem'. Very sophisticated. >Band 6: Precise vocabulary. Not Band 8: Some phrases are common.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'Whom I have known...' (Relative clause). 'Who always puts others...' (Relative clause). 'Based on mutual trust...' (Participle phrase). 'That helps me gain clarity' (Relative clause). Accurate.",
        "vocabulary": 7,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a friend who is important to you.\n\nTranscript: I would like to describe my close friend, Sarah, whom I have known since kindergarten. She is a compassionate person who always puts others before herself. We share a deep bond based on mutual trust and understanding. Whenever I face a dilemma, she provides insightful advice that helps me gain clarity. She is also incredibly talented artistically, often creating beautiful paintings. I admire her ability to stay positive even in difficult situations. Her optimism is contagious and lifts my spirits. I cherish our friendship because it is authentic and supportive. She is truly a gem in my life.\n\nWord Count: 100 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses descriptive words: 'compassionate', 'dilemma', 'contagious', 'authentic'. Clear meaning.\n\n>Band 6: Advanced vocabulary.\n\nNot Band 8: Lacks native-like flow.\n\n**Idiom present:** Yes ('lifts my spirits')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures accurately. Includes relative clauses and participle phrases. Good control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Limited variety.\n\n**Micro flaws identified:**\n- None."
    },
    # 495. V7/G7 - Event (Sport)
    {
        "sample_id": "syn_p2_v7_g7_0495",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a sports match you watched.",
        "transcript_cleaned": "I watched the World Cup final last year, which was an exhilarating experience. The atmosphere in the stadium was electric, with fans chanting and waving flags. The match itself was intensely competitive, with both teams displaying exceptional skill. It was a nail-biting finish as the game went into penalty shootouts. I was on the edge of my seat the entire time. When my favorite team won, the crowd erupted in celebration. It was a historic victory that united the nation. Witnessing such a momentous event live is something I will never forget. It was truly a spectacle.",
        "word_count": 100,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR7] Vocabulary: 'exhilarating', 'atmosphere', 'electric', 'chanting', 'intensely competitive', 'displaying', 'exceptional skill', 'nail-biting finish', 'penalty shootouts', 'edge of my seat', 'erupted', 'historic victory', 'united', 'witnessing', 'momentous', 'spectacle'. Very sophisticated. >Band 6: Precise vocabulary. Not Band 8: Some phrases are common.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'Which was an exhilarating experience' (Relative clause). 'With fans chanting...' (Prepositional phrase + Participle). 'As the game went...' (Time clause). 'Witnessing such a momentous event...' (Gerund subject). Accurate.",
        "vocabulary": 7,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a sports match you watched.\n\nTranscript: I watched the World Cup final last year, which was an exhilarating experience. The atmosphere in the stadium was electric, with fans chanting and waving flags. The match itself was intensely competitive, with both teams displaying exceptional skill. It was a nail-biting finish as the game went into penalty shootouts. I was on the edge of my seat the entire time. When my favorite team won, the crowd erupted in celebration. It was a historic victory that united the nation. Witnessing such a momentous event live is something I will never forget. It was truly a spectacle.\n\nWord Count: 100 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses topic words: 'exhilarating', 'electric', 'nail-biting', 'spectacle'. Meaning is clear.\n\n>Band 6: Advanced vocabulary.\n\nNot Band 8: Lacks native-like flow.\n\n**Idiom present:** Yes ('edge of my seat')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures accurately. Includes relative clauses and gerund subjects. Good control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Limited variety.\n\n**Micro flaws identified:**\n- None."
    },
    # 496. V7/G7 - Object (Technology)
    {
        "sample_id": "syn_p2_v7_g7_0496",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a useful electronic device you own.",
        "transcript_cleaned": "My tablet is an incredibly versatile device that I use daily. It serves as a portable workstation, allowing me to edit documents and create presentations on the go. The high-resolution screen is perfect for consuming media like movies and e-books. I also use it for digital art, as the stylus offers precision and control. Its battery life is impressive, lasting through long flights. I appreciate its sleek design and lightweight build. It has replaced my bulky laptop for most tasks. This gadget has significantly enhanced my productivity and creativity. It is an essential tool in my modern lifestyle.",
        "word_count": 100,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR7] Vocabulary: 'versatile', 'portable workstation', 'edit documents', 'presentations', 'high-resolution', 'consuming media', 'digital art', 'stylus', 'precision', 'battery life', 'impressive', 'sleek design', 'lightweight', 'replaced', 'bulky', 'gadget', 'enhanced', 'productivity', 'creativity', 'essential tool'. Very sophisticated. >Band 6: Precise vocabulary. Not Band 8: Some phrases are common.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'That I use daily' (Relative clause). 'Allowing me to edit...' (Participle phrase). 'As the stylus offers...' (Reason clause). 'Lasting through long flights' (Participle phrase). Accurate.",
        "vocabulary": 7,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a useful electronic device you own.\n\nTranscript: My tablet is an incredibly versatile device that I use daily. It serves as a portable workstation, allowing me to edit documents and create presentations on the go. The high-resolution screen is perfect for consuming media like movies and e-books. I also use it for digital art, as the stylus offers precision and control. Its battery life is impressive, lasting through long flights. I appreciate its sleek design and lightweight build. It has replaced my bulky laptop for most tasks. This gadget has significantly enhanced my productivity and creativity. It is an essential tool in my modern lifestyle.\n\nWord Count: 100 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses topic words: 'versatile', 'workstation', 'sleek', 'enhanced'. Meaning is clear.\n\n>Band 6: Advanced vocabulary.\n\nNot Band 8: Lacks native-like flow.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures accurately. Includes relative clauses and participle phrases. Good control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Limited variety.\n\n**Micro flaws identified:**\n- None."
    },
    # 497. V7/G7 - Activity (Exercise)
    {
        "sample_id": "syn_p2_v7_g7_0497",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a healthy activity you do.",
        "transcript_cleaned": "I practice yoga regularly to maintain my physical and mental well-being. It involves a series of postures and breathing exercises designed to increase flexibility and strength. I attend a class twice a week, which helps me stay disciplined. The meditation aspect is particularly beneficial for reducing stress and anxiety. It allows me to disconnect from the chaotic world and find inner peace. I have noticed a significant improvement in my posture and energy levels. Yoga teaches mindfulness and self-awareness. It is a holistic practice that nurtures the body and soul. I would recommend it to anyone seeking balance.",
        "word_count": 100,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR7] Vocabulary: 'maintain', 'mental well-being', 'postures', 'breathing exercises', 'flexibility', 'strength', 'disciplined', 'meditation', 'beneficial', 'reducing stress', 'anxiety', 'disconnect', 'chaotic', 'inner peace', 'significant improvement', 'posture', 'mindfulness', 'self-awareness', 'holistic', 'nurtures', 'seeking balance'. Very sophisticated. >Band 6: Precise vocabulary. Not Band 8: Some phrases are common.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'Designed to increase...' (Participle phrase). 'Which helps me stay disciplined' (Relative clause). 'Allows me to disconnect...' (Infinitive structure). 'That nurtures the body' (Relative clause). Accurate.",
        "vocabulary": 7,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a healthy activity you do.\n\nTranscript: I practice yoga regularly to maintain my physical and mental well-being. It involves a series of postures and breathing exercises designed to increase flexibility and strength. I attend a class twice a week, which helps me stay disciplined. The meditation aspect is particularly beneficial for reducing stress and anxiety. It allows me to disconnect from the chaotic world and find inner peace. I have noticed a significant improvement in my posture and energy levels. Yoga teaches mindfulness and self-awareness. It is a holistic practice that nurtures the body and soul. I would recommend it to anyone seeking balance.\n\nWord Count: 100 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses topic words: 'mindfulness', 'holistic', 'nurtures'. Meaning is clear.\n\n>Band 6: Advanced vocabulary.\n\nNot Band 8: Lacks native-like flow.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures accurately. Includes relative clauses and participle phrases. Good control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Limited variety.\n\n**Micro flaws identified:**\n- None."
    },
    # 498. V7/G7 - Book (Recommend)
    {
        "sample_id": "syn_p2_v7_g7_0498",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a book you think is interesting.",
        "transcript_cleaned": "I recently read a captivating novel called 'The Kite Runner', which is set in Afghanistan. It tells the poignant story of two friends from different social classes. The themes of betrayal and redemption are woven intricately into the narrative. I was deeply moved by the emotional struggles of the protagonist. The author's vivid descriptions transport the reader to a different time and place. Although some parts are heartbreaking, the message of forgiveness is uplifting. It offers a glimpse into a culture that was previously unfamiliar to me. It is a literary gem that stays with you long after reading.",
        "word_count": 100,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR7] Vocabulary: 'captivating novel', 'set in', 'poignant', 'social classes', 'themes', 'betrayal', 'redemption', 'woven intricately', 'narrative', 'deeply moved', 'emotional struggles', 'protagonist', 'vivid descriptions', 'transport', 'heartbreaking', 'forgiveness', 'uplifting', 'glimpse', 'unfamiliar', 'literary gem'. Very sophisticated. >Band 6: Precise vocabulary. Not Band 8: Some phrases are common.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'Which is set in Afghanistan' (Relative clause). 'From different social classes' (Prepositional phrase). 'Although some parts are heartbreaking...' (Concessive clause). 'That was previously unfamiliar' (Relative clause). Accurate.",
        "vocabulary": 7,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a book you think is interesting.\n\nTranscript: I recently read a captivating novel called 'The Kite Runner', which is set in Afghanistan. It tells the poignant story of two friends from different social classes. The themes of betrayal and redemption are woven intricately into the narrative. I was deeply moved by the emotional struggles of the protagonist. The author's vivid descriptions transport the reader to a different time and place. Although some parts are heartbreaking, the message of forgiveness is uplifting. It offers a glimpse into a culture that was previously unfamiliar to me. It is a literary gem that stays with you long after reading.\n\nWord Count: 100 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses descriptive words: 'poignant', 'intricately', 'protagonist', 'literary gem'. Clear meaning.\n\n>Band 6: Advanced vocabulary.\n\nNot Band 8: Lacks native-like flow.\n\n**Idiom present:** Yes ('stays with you')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures accurately. Includes relative clauses and concessive clauses. Good control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Limited variety.\n\n**Micro flaws identified:**\n- None."
    },
    # 499. V7/G7 - Place (Quiet)
    {
        "sample_id": "syn_p2_v7_g7_0499",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a place where you can relax.",
        "transcript_cleaned": "There is a botanical garden in my city that serves as my personal sanctuary. It is a sprawling oasis filled with exotic plants and serene water features. I go there to escape the hustle and bustle of daily life. The air is fragrant with the scent of blooming flowers. I enjoy sitting on a bench, listening to the soothing sound of the fountain. It is the perfect place for introspection and meditation. Surrounded by nature, I feel my stress melt away. It rejuvenates my mind and body, preparing me for the challenges ahead.",
        "word_count": 95,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR7] Vocabulary: 'botanical garden', 'personal sanctuary', 'sprawling oasis', 'exotic plants', 'serene', 'water features', 'hustle and bustle', 'fragrant', 'scent', 'blooming', 'soothing', 'introspection', 'meditation', 'melt away', 'rejuvenates', 'challenges ahead'. Very sophisticated. >Band 6: Precise vocabulary. Not Band 8: Some phrases are common.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'That serves as my personal sanctuary' (Relative clause). 'Filled with exotic plants' (Participle phrase). 'Listening to the soothing sound' (Participle phrase). 'Surrounded by nature' (Participle phrase). Accurate.",
        "vocabulary": 7,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a place where you can relax.\n\nTranscript: There is a botanical garden in my city that serves as my personal sanctuary. It is a sprawling oasis filled with exotic plants and serene water features. I go there to escape the hustle and bustle of daily life. The air is fragrant with the scent of blooming flowers. I enjoy sitting on a bench, listening to the soothing sound of the fountain. It is the perfect place for introspection and meditation. Surrounded by nature, I feel my stress melt away. It rejuvenates my mind and body, preparing me for the challenges ahead.\n\nWord Count: 95 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses topic words: 'sanctuary', 'oasis', 'introspection', 'rejuvenates'. Meaning is clear.\n\n>Band 6: Advanced vocabulary.\n\nNot Band 8: Lacks native-like flow.\n\n**Idiom present:** Yes ('hustle and bustle')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures accurately. Includes relative clauses and participle phrases. Good control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Limited variety.\n\n**Micro flaws identified:**\n- None."
    },
    # 500. V7/G7 - Person (Child)
    {
        "sample_id": "syn_p2_v7_g7_0500",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a child you know well.",
        "transcript_cleaned": "I would like to talk about my niece, Lily, who is an exceptionally bright six-year-old. She possesses an insatiable curiosity about the world around her. She is always asking insightful questions that surprise me. Lily has a vivid imagination and loves inventing stories. She is also quite empathetic, often sharing her toys with other children. Her infectious laughter brings joy to our entire family. I enjoy spending time with her because she reminds me of the innocence of childhood. Watching her grow and develop is a privilege. She has a promising future ahead of her.",
        "word_count": 97,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR7] Vocabulary: 'niece', 'exceptionally bright', 'possesses', 'insatiable curiosity', 'insightful', 'vivid imagination', 'inventing', 'empathetic', 'infectious laughter', 'innocence', 'childhood', 'privilege', 'promising future'. Very sophisticated. >Band 6: Precise vocabulary. Not Band 8: Some phrases are common.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'Who is an exceptionally bright six-year-old' (Relative clause). 'That surprise me' (Relative clause). 'Often sharing her toys' (Participle phrase). 'Because she reminds me...' (Reason clause). Accurate.",
        "vocabulary": 7,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a child you know well.\n\nTranscript: I would like to talk about my niece, Lily, who is an exceptionally bright six-year-old. She possesses an insatiable curiosity about the world around her. She is always asking insightful questions that surprise me. Lily has a vivid imagination and loves inventing stories. She is also quite empathetic, often sharing her toys with other children. Her infectious laughter brings joy to our entire family. I enjoy spending time with her because she reminds me of the innocence of childhood. Watching her grow and develop is a privilege. She has a promising future ahead of her.\n\nWord Count: 97 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses descriptive words: 'insatiable', 'insightful', 'empathetic', 'infectious'. Clear meaning.\n\n>Band 6: Advanced vocabulary.\n\nNot Band 8: Lacks native-like flow.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures accurately. Includes relative clauses and participle phrases. Good control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Limited variety.\n\n**Micro flaws identified:**\n- None."
    }
]

with open(OUTPUT_FILE, 'a', encoding='utf-8') as f:
    for sample in samples:
        f.write(json.dumps(sample) + '\n')
