import json

OUTPUT_FILE = "ielts-data/phase3/v76_review_output/synthetic_batches/batch_p2_09.jsonl"

samples = [
    # 411. V4/G5 - Hobby (Reading)
    {
        "sample_id": "syn_p2_v4_g5_0411",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a hobby you have.",
        "transcript_cleaned": "I like reading books very much. It is my favorite hobby. I usually read books in my free time. I have many books in my room. My favorite book is about history. I read it every day before I go to sleep. Reading helps me learn new things. It also makes me feel relax. Sometimes I go to the library to borrow books. The library is near my house, so it is easy to go there. I think reading is good for everyone. If I have money, I will buy more books. I want to read English books to learn English better.",
        "word_count": 105,
        "response_type": "long_turn",
        "micro_flaws": ["verb: 'feel relax' should be 'feel relaxed'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "controlled", "flexibility": "limited"},
        "vocab_reason": "[LR4] Limited range: 'reading books', 'hobby', 'free time', 'room', 'history', 'sleep', 'learn', 'relax', 'library', 'borrow', 'house', 'easy', 'good', 'money', 'buy', 'English'. Basic and repetitive. >Band 3: Basic meaning. Not Band 5: Minimal variation.",
        "grammar_reason": "[GRA5] Basic sentence forms are mostly accurate. Some attempts at complex sentences ('before I go', 'so it is easy', 'If I have money'). >Band 4: Accuracy is better than Band 4. Not Band 6: Complex structures are simple and limited.",
        "vocabulary": 4,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a hobby you have.\n\nTranscript: I like reading books very much. It is my favorite hobby. I usually read books in my free time. I have many books in my room. My favorite book is about history. I read it every day before I go to sleep. Reading helps me learn new things. It also makes me feel relax. Sometimes I go to the library to borrow books. The library is near my house, so it is easy to go there. I think reading is good for everyone. If I have money, I will buy more books. I want to read English books to learn English better.\n\nWord Count: 105 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Basic vocabulary: 'books', 'read', 'library'. Repetitive. No descriptive adjectives.\n\n>Band 3: Communicates topic.\n\nNot Band 5: Limited range.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Uses basic sentences accurately. Attempts some complex structures with conjunctions ('so', 'if', 'before').\n\n>Band 4: More accurate than Band 4.\n\nNot Band 6: Limited flexibility.\n\n**Micro flaws identified:**\n- 'feel relax' should be 'feel relaxed'"
    },
    # 412. V4/G5 - Place (Park)
    {
        "sample_id": "syn_p2_v4_g5_0412",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a park you like.",
        "transcript_cleaned": "There is a park near my school that I like very much. It is a big park with many trees and flowers. I often go there after school with my friends. We like to play football on the grass. The park is very quiet and clean. Sometimes, old people do exercise there in the morning. I like this park because the air is fresh. It is a good place to relax. On weekends, many families come here for a picnic. I think parks are important for the city. If I have time, I will go there tomorrow.",
        "word_count": 101,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "basic", "accuracy": "controlled", "flexibility": "limited"},
        "vocab_reason": "[LR4] Limited range: 'park', 'school', 'big', 'trees', 'flowers', 'friends', 'football', 'grass', 'quiet', 'clean', 'exercise', 'morning', 'fresh', 'relax', 'families', 'picnic', 'city', 'time'. Basic and repetitive. >Band 3: Clear meaning. Not Band 5: Minimal description.",
        "grammar_reason": "[GRA5] Basic sentence forms are accurate. Uses 'that' relative clause ('that I like'). Uses 'because' and 'if' clauses correctly. >Band 4: Accuracy is good for simple sentences. Not Band 6: Complex structures are limited.",
        "vocabulary": 4,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a park you like.\n\nTranscript: There is a park near my school that I like very much. It is a big park with many trees and flowers. I often go there after school with my friends. We like to play football on the grass. The park is very quiet and clean. Sometimes, old people do exercise there in the morning. I like this park because the air is fresh. It is a good place to relax. On weekends, many families come here for a picnic. I think parks are important for the city. If I have time, I will go there tomorrow.\n\nWord Count: 101 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Basic vocabulary: 'park', 'trees', 'clean'. Simple descriptions. No variety.\n\n>Band 3: Can describe place.\n\nNot Band 5: Lacks descriptive language.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Produces accurate basic sentences. Uses some complex structures ('that', 'because', 'if') correctly.\n\n>Band 4: Frequent error-free sentences.\n\nNot Band 6: Range is limited.\n\n**Micro flaws identified:**\n- None."
    },
    # 413. V4/G5 - Person (Teacher)
    {
        "sample_id": "syn_p2_v4_g5_0413",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a teacher you like.",
        "transcript_cleaned": "I want to talk about my English teacher, Mr. Smith. He is very kind and funny. He teaches me at high school. I like him because he makes the lessons interesting. He always helps me when I have a problem with my homework. He speaks English very well. He encourages us to speak English in class. Sometimes he tells us funny stories. I think he is a good teacher because he cares about his students. I learned a lot from him. I hope I can meet him again in the future. He is my favorite teacher.",
        "word_count": 100,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "basic", "accuracy": "controlled", "flexibility": "limited"},
        "vocab_reason": "[LR4] Limited range: 'teacher', 'kind', 'funny', 'high school', 'lessons', 'interesting', 'helps', 'problem', 'homework', 'speaks', 'encourages', 'stories', 'good', 'cares', 'students', 'learned', 'future', 'favorite'. Basic vocabulary. >Band 3: Meaning clear. Not Band 5: Minimal variation.",
        "grammar_reason": "[GRA5] Basic sentence forms are mostly accurate. Uses 'because' and 'when' correctly. Past tense used correctly ('learned'). >Band 4: Accuracy is maintained in simple sentences. Not Band 6: Structure variety is limited.",
        "vocabulary": 4,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a teacher you like.\n\nTranscript: I want to talk about my English teacher, Mr. Smith. He is very kind and funny. He teaches me at high school. I like him because he makes the lessons interesting. He always helps me when I have a problem with my homework. He speaks English very well. He encourages us to speak English in class. Sometimes he tells us funny stories. I think he is a good teacher because he cares about his students. I learned a lot from him. I hope I can meet him again in the future. He is my favorite teacher.\n\nWord Count: 100 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Basic words: 'teacher', 'kind', 'funny'. Repetitive sentences. No complex vocabulary.\n\n>Band 3: Basic description.\n\nNot Band 5: Lacks range.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Uses basic sentences accurately. Connectors like 'because' and 'when' are used correctly.\n\n>Band 4: Frequent error-free sentences.\n\nNot Band 6: Limited complex structures.\n\n**Micro flaws identified:**\n- None."
    },
    # 414. V4/G5 - Event (Party)
    {
        "sample_id": "syn_p2_v4_g5_0414",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a party you went to.",
        "transcript_cleaned": "Last week, I went to my friend's birthday party. It was at his house. Many people came to the party. We ate a lot of food, like pizza and cake. The food was very delicious. We also drank soda and juice. We played some games together, which was fun. My friend received many gifts. He was very happy. We sang the birthday song for him. I talked to many new friends there. The party finished at 9 pm. I went home with my brother. I enjoyed the party very much. It was a good time for me.",
        "word_count": 101,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "basic", "accuracy": "controlled", "flexibility": "limited"},
        "vocab_reason": "[LR4] Limited range: 'party', 'birthday', 'house', 'people', 'food', 'pizza', 'cake', 'delicious', 'drank', 'soda', 'games', 'fun', 'gifts', 'happy', 'sang', 'song', 'talked', 'finished', 'enjoyed', 'time'. Basic party vocabulary. >Band 3: Clear narrative. Not Band 5: Minimal descriptive language.",
        "grammar_reason": "[GRA5] Basic sentence forms are accurate. Uses past tense correctly ('went', 'came', 'ate', 'was', 'played'). Uses relative clause ('which was fun'). >Band 4: Past tense is consistent. Not Band 6: Mostly simple sentences.",
        "vocabulary": 4,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a party you went to.\n\nTranscript: Last week, I went to my friend's birthday party. It was at his house. Many people came to the party. We ate a lot of food, like pizza and cake. The food was very delicious. We also drank soda and juice. We played some games together, which was fun. My friend received many gifts. He was very happy. We sang the birthday song for him. I talked to many new friends there. The party finished at 9 pm. I went home with my brother. I enjoyed the party very much. It was a good time for me.\n\nWord Count: 101 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Basic vocabulary: 'party', 'food', 'fun'. Very simple narrative. No variety.\n\n>Band 3: Basic story.\n\nNot Band 5: Lacks descriptive words.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Uses past tense accurately throughout the response. Some simple complex structures ('which was fun').\n\n>Band 4: Consistent accuracy in basic forms.\n\nNot Band 6: Limited range of structures.\n\n**Micro flaws identified:**\n- None."
    },
    # 415. V4/G5 - Food (Favorite)
    {
        "sample_id": "syn_p2_v4_g5_0415",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe your favorite food.",
        "transcript_cleaned": "My favorite food is chicken soup. It is a traditional dish in my country. My mother cooks it very well. I usually eat it for lunch on Sunday. It has chicken, vegetables, and noodles in it. The taste is very good and salty. I like it because it is hot and healthy. When I am sick, my mother makes this soup for me. It makes me feel better. I can also cook it, but my mother's soup is the best. I think everyone likes this food. It is easy to make and not expensive. I love eating it with my family.",
        "word_count": 105,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "basic", "accuracy": "controlled", "flexibility": "limited"},
        "vocab_reason": "[LR4] Limited range: 'favorite food', 'chicken soup', 'traditional dish', 'cooks', 'lunch', 'vegetables', 'noodles', 'taste', 'salty', 'hot', 'healthy', 'sick', 'better', 'best', 'easy', 'expensive'. Basic food vocabulary. >Band 3: Communicates preferences. Not Band 5: Minimal range.",
        "grammar_reason": "[GRA5] Basic sentence forms are accurate. Uses 'because' and 'when' clauses correctly. Comparisons used correctly ('better', 'best'). >Band 4: Accuracy is maintained. Not Band 6: Structure variety is limited.",
        "vocabulary": 4,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe your favorite food.\n\nTranscript: My favorite food is chicken soup. It is a traditional dish in my country. My mother cooks it very well. I usually eat it for lunch on Sunday. It has chicken, vegetables, and noodles in it. The taste is very good and salty. I like it because it is hot and healthy. When I am sick, my mother makes this soup for me. It makes me feel better. I can also cook it, but my mother's soup is the best. I think everyone likes this food. It is easy to make and not expensive. I love eating it with my family.\n\nWord Count: 105 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Basic vocabulary: 'soup', 'cook', 'good'. Simple adjectives. No complex words.\n\n>Band 3: Basic description.\n\nNot Band 5: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Produces accurate basic sentences. Uses 'because' and 'when' correctly to link ideas.\n\n>Band 4: Frequent error-free sentences.\n\nNot Band 6: Limited complex structures.\n\n**Micro flaws identified:**\n- None."
    },
    # 416. V4/G5 - Activity (Daily)
    {
        "sample_id": "syn_p2_v4_g5_0416",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe something you do every day.",
        "transcript_cleaned": "Every day, I go for a walk in the morning. I wake up at 6 am and wash my face. Then I put on my shoes and go outside. I walk in the park near my house for 30 minutes. The air is fresh and cool. I see many people walking there too. Sometimes I listen to music while I walk. It helps me wake up and feel energetic. After walking, I go home and eat breakfast. I think walking is good exercise for my health. I have done this for one year. I will continue to do it every day.",
        "word_count": 105,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "basic", "accuracy": "controlled", "flexibility": "limited"},
        "vocab_reason": "[LR4] Limited range: 'walk', 'morning', 'wake up', 'wash face', 'shoes', 'outside', 'park', 'fresh', 'cool', 'people', 'listen to music', 'energetic', 'breakfast', 'exercise', 'health'. Basic routine vocabulary. >Band 3: Clear sequence. Not Band 5: Minimal variation.",
        "grammar_reason": "[GRA5] Basic sentence forms are accurate. Uses 'while' clause correctly. Present perfect used correctly ('have done'). >Band 4: Good control of simple sentences. Not Band 6: Sentences are mostly simple.",
        "vocabulary": 4,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe something you do every day.\n\nTranscript: Every day, I go for a walk in the morning. I wake up at 6 am and wash my face. Then I put on my shoes and go outside. I walk in the park near my house for 30 minutes. The air is fresh and cool. I see many people walking there too. Sometimes I listen to music while I walk. It helps me wake up and feel energetic. After walking, I go home and eat breakfast. I think walking is good exercise for my health. I have done this for one year. I will continue to do it every day.\n\nWord Count: 105 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Basic vocabulary: 'walk', 'morning', 'shoes'. Repetitive. No descriptive language.\n\n>Band 3: Can describe routine.\n\nNot Band 5: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Uses basic sentences accurately. 'While' clause and present perfect used correctly.\n\n>Band 4: Frequent error-free sentences.\n\nNot Band 6: Limited range of structures.\n\n**Micro flaws identified:**\n- None."
    },
    # 417. V4/G5 - City (Like)
    {
        "sample_id": "syn_p2_v4_g5_0417",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a city you like.",
        "transcript_cleaned": "I like Tokyo, which is the capital of Japan. I went there last year for a holiday. It is a very big and busy city. There are many tall buildings and shops. I visited a famous temple, which was very beautiful. The food in Tokyo is amazing, especially sushi. I also liked riding the trains because they are fast and clean. The people are very polite and helpful. Although it is crowded, I felt safe there. I want to go back to Tokyo again one day. It is the most interesting city I have visited. I have many photos of my trip.",
        "word_count": 105,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "basic", "accuracy": "controlled", "flexibility": "limited"},
        "vocab_reason": "[LR4] Limited range: 'capital', 'holiday', 'big', 'busy', 'tall buildings', 'shops', 'famous temple', 'beautiful', 'food', 'amazing', 'sushi', 'trains', 'fast', 'clean', 'polite', 'helpful', 'crowded', 'safe', 'interesting', 'photos'. Basic travel vocabulary. >Band 3: Communicates experience. Not Band 5: Minimal description.",
        "grammar_reason": "[GRA5] Basic sentence forms are accurate. Uses relative clauses ('which is', 'which was') and 'although' correctly. Comparisons used correctly ('most interesting'). >Band 4: Accuracy is good. Not Band 6: Limited complexity.",
        "vocabulary": 4,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a city you like.\n\nTranscript: I like Tokyo, which is the capital of Japan. I went there last year for a holiday. It is a very big and busy city. There are many tall buildings and shops. I visited a famous temple, which was very beautiful. The food in Tokyo is amazing, especially sushi. I also liked riding the trains because they are fast and clean. The people are very polite and helpful. Although it is crowded, I felt safe there. I want to go back to Tokyo again one day. It is the most interesting city I have visited. I have many photos of my trip.\n\nWord Count: 105 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Basic vocabulary: 'big', 'busy', 'beautiful'. Simple adjectives. No complex words.\n\n>Band 3: Can describe city.\n\nNot Band 5: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Uses accurate basic sentences. Uses relative clauses and 'although' correctly to connect ideas.\n\n>Band 4: Frequent error-free sentences.\n\nNot Band 6: Limited range of structures.\n\n**Micro flaws identified:**\n- None."
    },
    # 418. V4/G5 - Game (Computer)
    {
        "sample_id": "syn_p2_v4_g5_0418",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a computer game you play.",
        "transcript_cleaned": "I play a game called Minecraft on my computer. It is a very popular game. I play it with my friends online. In the game, we build houses and find food. We can also fight monsters at night. I like this game because I can be creative. I built a big castle last week. It took me a long time to finish. The game has nice music and colors. I usually play it on the weekend when I have free time. My parents think I play too much, but I enjoy it. It is a good way to relax for me.",
        "word_count": 104,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "basic", "accuracy": "controlled", "flexibility": "limited"},
        "vocab_reason": "[LR4] Limited range: 'game', 'computer', 'popular', 'friends', 'online', 'build houses', 'find food', 'fight monsters', 'creative', 'castle', 'finish', 'music', 'colors', 'weekend', 'free time', 'parents', 'enjoy', 'relax'. Basic gaming vocabulary. >Band 3: Clear description. Not Band 5: Minimal range.",
        "grammar_reason": "[GRA5] Basic sentence forms are accurate. Uses 'because' and 'when' clauses correctly. 'Called Minecraft' (Participle phrase) used correctly. >Band 4: Good control of simple sentences. Not Band 6: Mostly simple sentences.",
        "vocabulary": 4,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a computer game you play.\n\nTranscript: I play a game called Minecraft on my computer. It is a very popular game. I play it with my friends online. In the game, we build houses and find food. We can also fight monsters at night. I like this game because I can be creative. I built a big castle last week. It took me a long time to finish. The game has nice music and colors. I usually play it on the weekend when I have free time. My parents think I play too much, but I enjoy it. It is a good way to relax for me.\n\nWord Count: 104 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Basic vocabulary: 'game', 'play', 'build'. Very simple description. No variety.\n\n>Band 3: Basic meaning.\n\nNot Band 5: Limited vocabulary.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Uses basic sentences accurately. Connectors like 'because' and 'but' are used correctly.\n\n>Band 4: Frequent error-free sentences.\n\nNot Band 6: Limited complex structures.\n\n**Micro flaws identified:**\n- None."
    },
    # 419. V4/G5 - Clothes (Uniform)
    {
        "sample_id": "syn_p2_v4_g5_0419",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a uniform you wear.",
        "transcript_cleaned": "I wear a uniform to school every day. It consists of a white shirt and blue trousers. I also have to wear a tie and black shoes. I like my uniform because it is comfortable. It saves me time in the morning because I do not have to choose clothes. However, in summer, it can be very hot. Most students in my school wear the same uniform. It makes us look neat and tidy. I keep my uniform clean and wash it every weekend. When I finish school, I will not wear a uniform anymore. I prefer wearing jeans and T-shirts.",
        "word_count": 105,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "basic", "accuracy": "controlled", "flexibility": "limited"},
        "vocab_reason": "[LR4] Limited range: 'uniform', 'school', 'white shirt', 'blue trousers', 'tie', 'black shoes', 'comfortable', 'saves time', 'choose clothes', 'summer', 'hot', 'students', 'neat', 'tidy', 'clean', 'wash', 'weekend', 'finish', 'jeans', 'T-shirts'. Basic clothing vocabulary. >Band 3: Communicates basic info. Not Band 5: Minimal variation.",
        "grammar_reason": "[GRA5] Basic sentence forms are accurate. Uses 'because' and 'when' clauses correctly. 'Consists of' used correctly. >Band 4: Accuracy is maintained. Not Band 6: Structure variety is limited.",
        "vocabulary": 4,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a uniform you wear.\n\nTranscript: I wear a uniform to school every day. It consists of a white shirt and blue trousers. I also have to wear a tie and black shoes. I like my uniform because it is comfortable. It saves me time in the morning because I do not have to choose clothes. However, in summer, it can be very hot. Most students in my school wear the same uniform. It makes us look neat and tidy. I keep my uniform clean and wash it every weekend. When I finish school, I will not wear a uniform anymore. I prefer wearing jeans and T-shirts.\n\nWord Count: 105 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Basic vocabulary: 'uniform', 'shirt', 'shoes'. Simple description. No complex words.\n\n>Band 3: Basic description.\n\nNot Band 5: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Produces accurate basic sentences. Uses 'because' and 'however' correctly to link ideas.\n\n>Band 4: Frequent error-free sentences.\n\nNot Band 6: Limited complex structures.\n\n**Micro flaws identified:**\n- None."
    },
    # 420. V4/G5 - Weather (Rain)
    {
        "sample_id": "syn_p2_v4_g5_0420",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a type of weather you dislike.",
        "transcript_cleaned": "I do not like rainy weather. It makes me feel sad and lazy. When it rains, I cannot go outside to play sports. The sky is dark and grey, which is not nice. I have to carry an umbrella everywhere, which is annoying. The streets become wet and dirty. Sometimes, my shoes get wet, and I hate that. I prefer sunny days when the light is bright. Rain is good for plants, but I do not like it. If it rains on the weekend, I stay home and watch movies. I hope it will be sunny tomorrow so I can go out.",
        "word_count": 106,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "basic", "accuracy": "controlled", "flexibility": "limited"},
        "vocab_reason": "[LR4] Limited range: 'rainy weather', 'sad', 'lazy', 'go outside', 'play sports', 'sky', 'dark', 'grey', 'nice', 'umbrella', 'annoying', 'streets', 'wet', 'dirty', 'shoes', 'hate', 'sunny', 'light', 'bright', 'plants', 'weekend', 'movies'. Basic weather vocabulary. >Band 3: Clear meaning. Not Band 5: Minimal description.",
        "grammar_reason": "[GRA5] Basic sentence forms are accurate. Uses 'when', 'which', and 'if' clauses correctly. >Band 4: Accuracy is good. Not Band 6: Limited complexity.",
        "vocabulary": 4,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a type of weather you dislike.\n\nTranscript: I do not like rainy weather. It makes me feel sad and lazy. When it rains, I cannot go outside to play sports. The sky is dark and grey, which is not nice. I have to carry an umbrella everywhere, which is annoying. The streets become wet and dirty. Sometimes, my shoes get wet, and I hate that. I prefer sunny days when the light is bright. Rain is good for plants, but I do not like it. If it rains on the weekend, I stay home and watch movies. I hope it will be sunny tomorrow so I can go out.\n\nWord Count: 106 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Basic vocabulary: 'rainy', 'wet', 'sad'. Simple adjectives. No variety.\n\n>Band 3: Basic description.\n\nNot Band 5: Limited vocabulary.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Uses basic sentences accurately. Uses relative clauses ('which is not nice') correctly.\n\n>Band 4: Frequent error-free sentences.\n\nNot Band 6: Limited range of structures.\n\n**Micro flaws identified:**\n- None."
    }
]

with open(OUTPUT_FILE, 'a', encoding='utf-8') as f:
    for sample in samples:
        f.write(json.dumps(sample) + '\n')
