import json

OUTPUT_FILE = "ielts-data/phase3/v76_review_output/synthetic_batches/batch_p2_11.jsonl"

samples = [
    # 501. V7/G8 - Job (Dream)
    {
        "sample_id": "syn_p2_v7_g8_0501",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a job you would like to do in the future.",
        "transcript_cleaned": "I aspire to become an environmental architect, focusing on sustainable urban design. This profession involves creating buildings that are both aesthetically pleasing and eco-friendly. I have always been passionate about conservation, and I believe architecture plays a pivotal role in mitigating climate change. If I were to pursue this career, I would specialize in integrating green spaces into city landscapes. The reason I find this job appealing is that it combines artistic creativity with technical engineering. Moreover, designing structures that reduce carbon footprints would be incredibly fulfilling. Although it requires extensive education and licensing, I am committed to achieving this goal. I envision a future where our cities live in harmony with nature.",
        "word_count": 115,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "high", "flexibility": "very_high"},
        "vocab_reason": "[LR7] Vocabulary: 'aspire', 'sustainable', 'eco-friendly', 'conservation', 'pivotal', 'mitigating', 'specialize', 'integrating', 'landscapes', 'appealing', 'carbon footprints', 'fulfilling', 'extensive', 'harmony'. Adequate range and precision. >Band 6: Uses less common items like 'mitigating'. Not Band 8: Some collocations are standard.",
        "grammar_reason": "[GRA8] Wide range of structures used accurately. 'If I were to pursue..., I would specialize...' (Second conditional). 'The reason I find... is that...' (Cleft sentence). 'Designing structures... would be...' (Gerund subject). Error-free. >Band 7: More complex structures. Not Band 9: Not fully native-like.",
        "vocabulary": 7,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a job you would like to do in the future.\n\nTranscript: I aspire to become an environmental architect, focusing on sustainable urban design. This profession involves creating buildings that are both aesthetically pleasing and eco-friendly. I have always been passionate about conservation, and I believe architecture plays a pivotal role in mitigating climate change. If I were to pursue this career, I would specialize in integrating green spaces into city landscapes. The reason I find this job appealing is that it combines artistic creativity with technical engineering. Moreover, designing structures that reduce carbon footprints would be incredibly fulfilling. Although it requires extensive education and licensing, I am committed to achieving this goal. I envision a future where our cities live in harmony with nature.\n\nWord Count: 115 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses precise vocabulary: 'sustainable', 'mitigating', 'integrating'. Good range.\n\n>Band 6: Clear meaning.\n\nNot Band 8: Lacks full sophistication.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Uses complex structures accurately (conditionals, cleft sentences). Error-free.\n\n>Band 7: High accuracy.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    },
    # 502. V7/G8 - Place (Quiet)
    {
        "sample_id": "syn_p2_v7_g8_0502",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a quiet place you like to go to.",
        "transcript_cleaned": "I frequently visit a secluded library in the city center to escape the noise. It is an old building with high ceilings and rows of wooden bookshelves. The atmosphere is serene, broken only by the sound of turning pages. I go there to study or read classic literature without distractions. What I appreciate most is the stillness; it allows me to concentrate deeply. Surrounded by knowledge, I feel a sense of peace and humility. It is my personal sanctuary where I can recharge my mental energy. Finding such a tranquil spot in a busy metropolis is rare.",
        "word_count": 98,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "high", "flexibility": "very_high"},
        "vocab_reason": "[LR7] Vocabulary: 'secluded', 'escape', 'ceilings', 'serene', 'distractions', 'appreciate', 'stillness', 'concentrate', 'humility', 'sanctuary', 'recharge', 'tranquil', 'metropolis'. Good range. >Band 6: Uses specific adjectives ('secluded', 'tranquil'). Not Band 8: Lacks idiomatic flair.",
        "grammar_reason": "[GRA8] Wide range of structures used accurately. 'Broken only by...' (Participle phrase). 'What I appreciate most is...' (Pseudo-cleft). 'Surrounded by knowledge...' (Participle phrase). 'Finding such a tranquil spot... is...' (Gerund subject). Error-free. >Band 7: More variety.",
        "vocabulary": 7,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a quiet place you like to go to.\n\nTranscript: I frequently visit a secluded library in the city center to escape the noise. It is an old building with high ceilings and rows of wooden bookshelves. The atmosphere is serene, broken only by the sound of turning pages. I go there to study or read classic literature without distractions. What I appreciate most is the stillness; it allows me to concentrate deeply. Surrounded by knowledge, I feel a sense of peace and humility. It is my personal sanctuary where I can recharge my mental energy. Finding such a tranquil spot in a busy metropolis is rare.\n\nWord Count: 98 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses descriptive words: 'secluded', 'serene', 'sanctuary'. Clear meaning.\n\n>Band 6: Advanced vocabulary.\n\nNot Band 8: Lacks sophistication.\n\n**Idiom present:** Yes ('recharge my mental energy')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Uses complex structures accurately (participle phrases, pseudo-cleft). Error-free.\n\n>Band 7: High accuracy.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    },
    # 503. V7/G8 - Event (Festival)
    {
        "sample_id": "syn_p2_v7_g8_0503",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a festival you celebrate.",
        "transcript_cleaned": "I celebrate the Lantern Festival, which marks the end of the Lunar New Year. It is a vibrant occasion filled with light and color. People gather in parks to release paper lanterns into the night sky, creating a mesmerizing spectacle. The lanterns symbolize letting go of the past and welcoming new beginnings. We also eat sweet rice balls, which represent family reunion. The atmosphere is festive, with dragon dances and fireworks illuminating the dark. I love this festival because it fosters a sense of community and hope. It is a cherished tradition that connects us to our cultural heritage.",
        "word_count": 100,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "high", "flexibility": "very_high"},
        "vocab_reason": "[LR7] Vocabulary: 'celebrate', 'vibrant', 'occasion', 'mesmerizing', 'spectacle', 'symbolize', 'welcoming', 'reunion', 'festive', 'illuminating', 'fosters', 'community', 'cherished', 'tradition', 'heritage'. Good range. >Band 6: Uses specific words ('mesmerizing', 'fosters'). Not Band 8: Lacks idiomatic depth.",
        "grammar_reason": "[GRA8] Wide range of structures used accurately. 'Which marks the end...' (Relative clause). 'Creating a mesmerizing spectacle' (Participle phrase). 'With dragon dances... illuminating...' (Prepositional phrase + Participle). 'Because it fosters...' (Reason clause). Error-free. >Band 7: More variety.",
        "vocabulary": 7,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a festival you celebrate.\n\nTranscript: I celebrate the Lantern Festival, which marks the end of the Lunar New Year. It is a vibrant occasion filled with light and color. People gather in parks to release paper lanterns into the night sky, creating a mesmerizing spectacle. The lanterns symbolize letting go of the past and welcoming new beginnings. We also eat sweet rice balls, which represent family reunion. The atmosphere is festive, with dragon dances and fireworks illuminating the dark. I love this festival because it fosters a sense of community and hope. It is a cherished tradition that connects us to our cultural heritage.\n\nWord Count: 100 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses topic words: 'mesmerizing', 'symbolize', 'heritage'. Meaning is clear.\n\n>Band 6: Advanced vocabulary.\n\nNot Band 8: Lacks sophistication.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Uses complex structures accurately (relative clauses, participle phrases). Error-free.\n\n>Band 7: High accuracy.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    },
    # 504. V7/G8 - Person (Teacher)
    {
        "sample_id": "syn_p2_v7_g8_0504",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a teacher who influenced you.",
        "transcript_cleaned": "I would like to talk about my high school history teacher, Mr. Thompson. He was a charismatic educator who brought the past to life with his storytelling. Unlike other teachers who relied on textbooks, he encouraged critical thinking and debate. He possessed an encyclopedic knowledge of world events, which was inspiring. I was particularly impressed by his ability to explain complex political concepts simply. He challenged me to look at history from different perspectives. Because of his guidance, I decided to study political science at university. He is a role model who I look up to greatly.",
        "word_count": 98,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "high", "flexibility": "very_high"},
        "vocab_reason": "[LR7] Vocabulary: 'charismatic', 'educator', 'relied on', 'textbooks', 'critical thinking', 'encyclopedic', 'inspiring', 'impressed', 'complex', 'concepts', 'perspectives', 'guidance', 'role model'. Good range. >Band 6: Uses specific words ('encyclopedic', 'perspectives'). Not Band 8: Lacks idiomatic flair.",
        "grammar_reason": "[GRA8] Wide range of structures used accurately. 'Who brought the past to life' (Relative clause). 'Unlike other teachers who relied...' (Contrast + Relative). 'Which was inspiring' (Relative clause). 'Because of his guidance' (Reason phrase). Error-free. >Band 7: More variety.",
        "vocabulary": 7,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a teacher who influenced you.\n\nTranscript: I would like to talk about my high school history teacher, Mr. Thompson. He was a charismatic educator who brought the past to life with his storytelling. Unlike other teachers who relied on textbooks, he encouraged critical thinking and debate. He possessed an encyclopedic knowledge of world events, which was inspiring. I was particularly impressed by his ability to explain complex political concepts simply. He challenged me to look at history from different perspectives. Because of his guidance, I decided to study political science at university. He is a role model who I look up to greatly.\n\nWord Count: 98 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses descriptive words: 'charismatic', 'encyclopedic', 'perspectives'. Clear meaning.\n\n>Band 6: Advanced vocabulary.\n\nNot Band 8: Lacks sophistication.\n\n**Idiom present:** Yes ('look up to')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Uses complex structures accurately (relative clauses, contrast). Error-free.\n\n>Band 7: High accuracy.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    },
    # 505. V7/G8 - Object (Gift)
    {
        "sample_id": "syn_p2_v7_g8_0505",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a gift you received that was special.",
        "transcript_cleaned": "I received a handmade quilt from my grandmother for my 18th birthday. It is an exquisite piece of craftsmanship, stitched with vibrant fabrics she had collected over years. Each patch tells a story, representing different memories from our family history. I was deeply touched by the time and effort she invested in making it. It is not just a blanket but a tangible expression of her love. I keep it on my bed, and it provides warmth and comfort. This heirloom is invaluable to me, and I hope to pass it on to future generations.",
        "word_count": 98,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "high", "flexibility": "very_high"},
        "vocab_reason": "[LR7] Vocabulary: 'handmade', 'quilt', 'exquisite', 'craftsmanship', 'stitched', 'vibrant', 'fabrics', 'patch', 'representing', 'memories', 'touched', 'invested', 'tangible', 'expression', 'warmth', 'comfort', 'heirloom', 'invaluable'. Good range. >Band 6: Uses specific words ('exquisite', 'heirloom'). Not Band 8: Lacks idiomatic depth.",
        "grammar_reason": "[GRA8] Wide range of structures used accurately. 'Stitched with vibrant fabrics...' (Participle phrase). 'She had collected over years' (Past Perfect). 'Representing different memories...' (Participle phrase). 'Not just... but...' (Correlative). Error-free. >Band 7: More variety.",
        "vocabulary": 7,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a gift you received that was special.\n\nTranscript: I received a handmade quilt from my grandmother for my 18th birthday. It is an exquisite piece of craftsmanship, stitched with vibrant fabrics she had collected over years. Each patch tells a story, representing different memories from our family history. I was deeply touched by the time and effort she invested in making it. It is not just a blanket but a tangible expression of her love. I keep it on my bed, and it provides warmth and comfort. This heirloom is invaluable to me, and I hope to pass it on to future generations.\n\nWord Count: 98 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses topic words: 'exquisite', 'tangible', 'heirloom'. Meaning is clear.\n\n>Band 6: Advanced vocabulary.\n\nNot Band 8: Lacks sophistication.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Uses complex structures accurately (participle phrases, past perfect). Error-free.\n\n>Band 7: High accuracy.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    },
    # 506. V7/G8 - Activity (Skill)
    {
        "sample_id": "syn_p2_v7_g8_0506",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a skill you learned that was difficult.",
        "transcript_cleaned": "Learning to play the violin was an arduous journey that tested my patience. The instrument requires precise finger placement and bowing technique to produce a pleasant sound. Initially, the noise I made was screeching and discordant. I struggled to read the complex musical notation and keep the rhythm. My teacher was strict, demanding perfection in every lesson. There were moments of frustration when I wanted to quit. However, my persistence paid off when I finally played a concerto without errors. Mastering this skill has instilled a sense of discipline in me. It is a rewarding accomplishment.",
        "word_count": 97,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "high", "flexibility": "very_high"},
        "vocab_reason": "[LR7] Vocabulary: 'arduous', 'journey', 'tested', 'patience', 'precise', 'placement', 'technique', 'pleasant', 'screeching', 'discordant', 'struggled', 'notation', 'rhythm', 'demanding', 'perfection', 'frustration', 'persistence', 'concerto', 'mastering', 'instilled', 'discipline', 'rewarding'. Good range. >Band 6: Uses specific words ('discordant', 'instilled'). Not Band 8: Lacks idiomatic flair.",
        "grammar_reason": "[GRA8] Wide range of structures used accurately. 'That tested my patience' (Relative clause). 'To produce a pleasant sound' (Infinitive of purpose). 'Demanding perfection...' (Participle phrase). 'When I wanted to quit' (Time clause). Error-free. >Band 7: More variety.",
        "vocabulary": 7,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a skill you learned that was difficult.\n\nTranscript: Learning to play the violin was an arduous journey that tested my patience. The instrument requires precise finger placement and bowing technique to produce a pleasant sound. Initially, the noise I made was screeching and discordant. I struggled to read the complex musical notation and keep the rhythm. My teacher was strict, demanding perfection in every lesson. There were moments of frustration when I wanted to quit. However, my persistence paid off when I finally played a concerto without errors. Mastering this skill has instilled a sense of discipline in me. It is a rewarding accomplishment.\n\nWord Count: 97 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses descriptive words: 'arduous', 'discordant', 'instilled'. Clear meaning.\n\n>Band 6: Advanced vocabulary.\n\nNot Band 8: Lacks sophistication.\n\n**Idiom present:** Yes ('paid off')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Uses complex structures accurately (relative clauses, participle phrases). Error-free.\n\n>Band 7: High accuracy.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    },
    # 507. V7/G8 - Book (Read)
    {
        "sample_id": "syn_p2_v7_g8_0507",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a book you read recently.",
        "transcript_cleaned": "I recently finished a biography of Steve Jobs, which was an inspiring read. It details his life from his humble beginnings to becoming a tech mogul. I was fascinated by his visionary approach to innovation and design. The book describes how he revolutionized multiple industries, including personal computing and music. However, it also reveals his difficult personality and how he treated his employees. I found the narrative compelling, although some parts were a bit slow. Reading about his failures was as interesting as his successes. It taught me that perseverance is crucial for achieving greatness.",
        "word_count": 96,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "high", "flexibility": "very_high"},
        "vocab_reason": "[LR7] Vocabulary: 'biography', 'inspiring', 'humble beginnings', 'mogul', 'fascinated', 'visionary', 'innovation', 'revolutionized', 'industries', 'reveals', 'narrative', 'compelling', 'failures', 'successes', 'perseverance', 'crucial', 'greatness'. Good range. >Band 6: Uses specific words ('mogul', 'visionary'). Not Band 8: Lacks idiomatic depth.",
        "grammar_reason": "[GRA8] Wide range of structures used accurately. 'Which was an inspiring read' (Relative clause). 'How he treated his employees' (Noun clause). 'Although some parts were...' (Concessive clause). 'Reading about his failures was...' (Gerund subject). Error-free. >Band 7: More variety.",
        "vocabulary": 7,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a book you read recently.\n\nTranscript: I recently finished a biography of Steve Jobs, which was an inspiring read. It details his life from his humble beginnings to becoming a tech mogul. I was fascinated by his visionary approach to innovation and design. The book describes how he revolutionized multiple industries, including personal computing and music. However, it also reveals his difficult personality and how he treated his employees. I found the narrative compelling, although some parts were a bit slow. Reading about his failures was as interesting as his successes. It taught me that perseverance is crucial for achieving greatness.\n\nWord Count: 96 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses topic words: 'visionary', 'revolutionized', 'compelling'. Meaning is clear.\n\n>Band 6: Advanced vocabulary.\n\nNot Band 8: Lacks sophistication.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Uses complex structures accurately (relative clauses, gerund subjects). Error-free.\n\n>Band 7: High accuracy.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    },
    # 508. V7/G8 - Place (City)
    {
        "sample_id": "syn_p2_v7_g8_0508",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a city you enjoyed visiting.",
        "transcript_cleaned": "I thoroughly enjoyed my visit to Kyoto, a city steeped in history and culture. It is renowned for its stunning temples and traditional wooden houses. I was captivated by the serene atmosphere, which is a stark contrast to Tokyo. I spent days wandering through the historic streets, admiring the architecture. One highlight was the Golden Pavilion, a structure that gleams in the sunlight. Although the city was crowded with tourists, I managed to find quiet spots. The local cuisine was also exceptional; I tasted many delicacies. It is a place that offers a unique blend of ancient and modern.",
        "word_count": 100,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "high", "flexibility": "very_high"},
        "vocab_reason": "[LR7] Vocabulary: 'thoroughly', 'steeped', 'renowned', 'stunning', 'captivated', 'serene', 'stark contrast', 'wandering', 'historic', 'architecture', 'highlight', 'structure', 'gleams', 'crowded', 'exceptional', 'delicacies', 'unique blend'. Good range. >Band 6: Uses specific words ('steeped', 'delicacies'). Not Band 8: Lacks idiomatic flair.",
        "grammar_reason": "[GRA8] Wide range of structures used accurately. 'Steeped in history...' (Participle phrase). 'Which is a stark contrast...' (Relative clause). 'That gleams in the sunlight' (Relative clause). 'Although the city was crowded...' (Concessive clause). Error-free. >Band 7: More variety.",
        "vocabulary": 7,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a city you enjoyed visiting.\n\nTranscript: I thoroughly enjoyed my visit to Kyoto, a city steeped in history and culture. It is renowned for its stunning temples and traditional wooden houses. I was captivated by the serene atmosphere, which is a stark contrast to Tokyo. I spent days wandering through the historic streets, admiring the architecture. One highlight was the Golden Pavilion, a structure that gleams in the sunlight. Although the city was crowded with tourists, I managed to find quiet spots. The local cuisine was also exceptional; I tasted many delicacies. It is a place that offers a unique blend of ancient and modern.\n\nWord Count: 100 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses descriptive words: 'steeped', 'captivated', 'delicacies'. Clear meaning.\n\n>Band 6: Advanced vocabulary.\n\nNot Band 8: Lacks sophistication.\n\n**Idiom present:** Yes ('stark contrast')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Uses complex structures accurately (relative clauses, concessive clauses). Error-free.\n\n>Band 7: High accuracy.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    },
    # 509. V7/G8 - Activity (Hobby)
    {
        "sample_id": "syn_p2_v7_g8_0509",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a hobby you have.",
        "transcript_cleaned": "I am an avid photographer, a hobby that allows me to capture fleeting moments. I carry my camera everywhere, looking for interesting subjects. I am particularly drawn to landscape photography, as it connects me with nature. Mastering the technical aspects, like exposure and composition, was challenging but rewarding. I enjoy editing my photos to enhance their visual appeal. Sharing my work online and receiving feedback is motivating. Photography has taught me to observe the world with a keener eye. It is a creative outlet that brings me immense joy and satisfaction.",
        "word_count": 92,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "high", "flexibility": "very_high"},
        "vocab_reason": "[LR7] Vocabulary: 'avid', 'capture', 'fleeting', 'subjects', 'drawn to', 'landscape', 'connects', 'mastering', 'technical aspects', 'exposure', 'composition', 'challenging', 'rewarding', 'editing', 'enhance', 'visual appeal', 'motivating', 'observe', 'keener eye', 'creative outlet', 'immense'. Good range. >Band 6: Uses specific words ('exposure', 'composition'). Not Band 8: Lacks idiomatic depth.",
        "grammar_reason": "[GRA8] Wide range of structures used accurately. 'A hobby that allows me...' (Appositive + Relative). 'Looking for interesting subjects' (Participle phrase). 'As it connects me...' (Reason clause). 'Mastering the technical aspects... was...' (Gerund subject). Error-free. >Band 7: More variety.",
        "vocabulary": 7,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a hobby you have.\n\nTranscript: I am an avid photographer, a hobby that allows me to capture fleeting moments. I carry my camera everywhere, looking for interesting subjects. I am particularly drawn to landscape photography, as it connects me with nature. Mastering the technical aspects, like exposure and composition, was challenging but rewarding. I enjoy editing my photos to enhance their visual appeal. Sharing my work online and receiving feedback is motivating. Photography has taught me to observe the world with a keener eye. It is a creative outlet that brings me immense joy and satisfaction.\n\nWord Count: 92 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses topic words: 'fleeting', 'composition', 'outlet'. Meaning is clear.\n\n>Band 6: Advanced vocabulary.\n\nNot Band 8: Lacks sophistication.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Uses complex structures accurately (gerund subjects, appositives). Error-free.\n\n>Band 7: High accuracy.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    },
    # 510. V7/G8 - Person (Friend)
    {
        "sample_id": "syn_p2_v7_g8_0510",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a friend you spend time with.",
        "transcript_cleaned": "I spend a lot of time with my colleague, Mark, who is a very charismatic person. We met at work three years ago and bonded over our shared love of sports. He is incredibly supportive, always willing to lend a listening ear when I have problems. We often go hiking on weekends, which is a great way to unwind. Mark has a great sense of humor and always keeps me entertained. I value his honesty and integrity. He is someone I can rely on implicitly. Our friendship is built on mutual respect and trust.",
        "word_count": 96,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "high", "flexibility": "very_high"},
        "vocab_reason": "[LR7] Vocabulary: 'colleague', 'charismatic', 'bonded', 'supportive', 'listening ear', 'unwind', 'sense of humor', 'entertained', 'value', 'honesty', 'integrity', 'rely on', 'implicitly', 'mutual', 'respect'. Good range. >Band 6: Uses specific words ('charismatic', 'implicitly'). Not Band 8: Lacks idiomatic flair.",
        "grammar_reason": "[GRA8] Wide range of structures used accurately. 'Who is a very charismatic person' (Relative clause). 'Always willing to lend...' (Adjective phrase). 'When I have problems' (Time clause). 'Which is a great way...' (Relative clause). Error-free. >Band 7: More variety.",
        "vocabulary": 7,
        "grammar": 8,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a friend you spend time with.\n\nTranscript: I spend a lot of time with my colleague, Mark, who is a very charismatic person. We met at work three years ago and bonded over our shared love of sports. He is incredibly supportive, always willing to lend a listening ear when I have problems. We often go hiking on weekends, which is a great way to unwind. Mark has a great sense of humor and always keeps me entertained. I value his honesty and integrity. He is someone I can rely on implicitly. Our friendship is built on mutual respect and trust.\n\nWord Count: 96 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Uses descriptive words: 'charismatic', 'integrity', 'implicitly'. Clear meaning.\n\n>Band 6: Advanced vocabulary.\n\nNot Band 8: Lacks sophistication.\n\n**Idiom present:** Yes ('lend a listening ear')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Uses complex structures accurately (relative clauses, adjective phrases). Error-free.\n\n>Band 7: High accuracy.\n\nNot Band 9: Not fully native-like.\n\n**Micro flaws identified:**\n- None."
    }
]

with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
    for sample in samples:
        f.write(json.dumps(sample) + '\n')
