import json

OUTPUT_FILE = "ielts-data/phase3/v76_review_output/synthetic_batches/batch_p2_09.jsonl"

samples = [
    # 431. V5/G5 - Activity (Hobby)
    {
        "sample_id": "syn_p2_v5_g5_0431",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a hobby you have.",
        "transcript_cleaned": "My hobby is playing the guitar. I started learning it three years ago. I have a brown guitar in my room. I practice every day for one hour. I like playing pop songs because they are easy. My favorite singer is Ed Sheeran. I want to play like him. Sometimes I play for my family. They say I am good. Playing guitar makes me happy. It helps me relax after school. I also watch videos on YouTube to learn new chords. It is difficult but fun. I hope to join a band in the future. Music is very important to me.",
        "word_count": 104,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "basic", "accuracy": "controlled", "flexibility": "limited"},
        "vocab_reason": "[LR5] Vocabulary: 'hobby', 'guitar', 'practice', 'pop songs', 'singer', 'relax', 'chords', 'band', 'important', 'difficult', 'fun'. Functional vocabulary relevant to the topic. >Band 4: Uses specific words ('chords'). Not Band 6: Simple vocabulary.",
        "grammar_reason": "[GRA5] Basic sentence forms are accurate. Uses 'because' and 'to' clauses correctly. Present tense used correctly ('practice', 'like', 'want'). >Band 4: Accuracy is good. Not Band 6: Limited complexity.",
        "vocabulary": 5,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a hobby you have.\n\nTranscript: My hobby is playing the guitar. I started learning it three years ago. I have a brown guitar in my room. I practice every day for one hour. I like playing pop songs because they are easy. My favorite singer is Ed Sheeran. I want to play like him. Sometimes I play for my family. They say I am good. Playing guitar makes me happy. It helps me relax after school. I also watch videos on YouTube to learn new chords. It is difficult but fun. I hope to join a band in the future. Music is very important to me.\n\nWord Count: 104 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses topic words: 'chords', 'band', 'practice'. Meaning is clear.\n\n>Band 4: Adequate vocabulary.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Uses basic sentences accurately. Connectors like 'because' and infinitives of purpose are used correctly.\n\n>Band 4: Frequent error-free sentences.\n\nNot Band 6: Limited range of structures.\n\n**Micro flaws identified:**\n- None."
    },
    # 432. V5/G5 - Place (Park)
    {
        "sample_id": "syn_p2_v5_g5_0432",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a park you like to visit.",
        "transcript_cleaned": "I like going to Central Park in my city. It is a very large and beautiful place. There are many trees and a big lake. People go there to walk and run. I usually go there on weekends with my dog. He loves to run on the grass. The park is clean and quiet. It is a good place to escape the noise of the city. In the summer, there are concerts in the park. I went to one last year, and it was great. I like this park because it makes me feel peaceful. I think every city needs a park like this.",
        "word_count": 109,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "basic", "accuracy": "controlled", "flexibility": "limited"},
        "vocab_reason": "[LR5] Vocabulary: 'large', 'beautiful', 'lake', 'walk', 'run', 'grass', 'clean', 'quiet', 'escape', 'noise', 'concerts', 'peaceful'. Functional vocabulary relevant to the topic. >Band 4: Uses specific words ('concerts', 'escape'). Not Band 6: Simple vocabulary.",
        "grammar_reason": "[GRA5] Basic sentence forms are accurate. Uses 'because' clause correctly. Past tense used correctly ('went', 'was'). >Band 4: Accuracy is good. Not Band 6: Limited complexity.",
        "vocabulary": 5,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a park you like to visit.\n\nTranscript: I like going to Central Park in my city. It is a very large and beautiful place. There are many trees and a big lake. People go there to walk and run. I usually go there on weekends with my dog. He loves to run on the grass. The park is clean and quiet. It is a good place to escape the noise of the city. In the summer, there are concerts in the park. I went to one last year, and it was great. I like this park because it makes me feel peaceful. I think every city needs a park like this.\n\nWord Count: 109 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses topic words: 'escape', 'concerts', 'peaceful'. Meaning is clear.\n\n>Band 4: Adequate vocabulary.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Uses basic sentences accurately. 'Because' clause and past tense used correctly.\n\n>Band 4: Frequent error-free sentences.\n\nNot Band 6: Limited range of structures.\n\n**Micro flaws identified:**\n- None."
    },
    # 433. V5/G5 - Person (Friend)
    {
        "sample_id": "syn_p2_v5_g5_0433",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a friend you like.",
        "transcript_cleaned": "My best friend is called Sarah. We met in high school five years ago. She is very kind and helpful. She has long brown hair and blue eyes. We like to do many things together, like shopping and watching movies. Sarah is very funny and always makes me laugh. She is also a good listener. When I have a problem, she gives me good advice. We talk on the phone every day. I trust her completely. She is like a sister to me. I hope we will be friends forever. Having a good friend is important for a happy life.",
        "word_count": 103,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "basic", "accuracy": "controlled", "flexibility": "limited"},
        "vocab_reason": "[LR5] Vocabulary: 'best friend', 'high school', 'kind', 'helpful', 'shopping', 'movies', 'funny', 'laugh', 'listener', 'advice', 'trust', 'forever', 'happy life'. Functional vocabulary relevant to the topic. >Band 4: Uses specific words ('listener', 'advice'). Not Band 6: Simple vocabulary.",
        "grammar_reason": "[GRA5] Basic sentence forms are accurate. Uses 'when' clause correctly. Present tense used correctly ('is', 'has', 'gives'). >Band 4: Accuracy is good. Not Band 6: Limited complexity.",
        "vocabulary": 5,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a friend you like.\n\nTranscript: My best friend is called Sarah. We met in high school five years ago. She is very kind and helpful. She has long brown hair and blue eyes. We like to do many things together, like shopping and watching movies. Sarah is very funny and always makes me laugh. She is also a good listener. When I have a problem, she gives me good advice. We talk on the phone every day. I trust her completely. She is like a sister to me. I hope we will be friends forever. Having a good friend is important for a happy life.\n\nWord Count: 103 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses topic words: 'listener', 'advice', 'trust'. Meaning is clear.\n\n>Band 4: Adequate vocabulary.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Uses basic sentences accurately. 'When' clause used correctly.\n\n>Band 4: Frequent error-free sentences.\n\nNot Band 6: Limited range of structures.\n\n**Micro flaws identified:**\n- None."
    },
    # 434. V5/G5 - Event (Holiday)
    {
        "sample_id": "syn_p2_v5_g5_0434",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a holiday you enjoyed.",
        "transcript_cleaned": "Last summer, I went on a holiday to Thailand with my family. We stayed in a hotel near the beach in Phuket. The weather was very hot and sunny. We swam in the sea every day. The water was clear and blue. We also visited some temples, which were very beautiful. I tried Thai food for the first time. It was spicy but delicious. We took a boat trip to an island. It was very exciting. I bought some souvenirs for my friends. We stayed there for one week. It was the best holiday of my life because I was with my family.",
        "word_count": 105,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "basic", "accuracy": "controlled", "flexibility": "limited"},
        "vocab_reason": "[LR5] Vocabulary: 'holiday', 'hotel', 'beach', 'weather', 'sunny', 'swam', 'sea', 'temples', 'spicy', 'delicious', 'boat trip', 'island', 'souvenirs'. Functional vocabulary relevant to the topic. >Band 4: Uses specific words ('souvenirs', 'spicy'). Not Band 6: Simple vocabulary.",
        "grammar_reason": "[GRA5] Basic sentence forms are accurate. Uses relative clause ('which were') and 'because' clause correctly. Past tense used correctly ('went', 'stayed', 'swam'). >Band 4: Accuracy is good. Not Band 6: Limited complexity.",
        "vocabulary": 5,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a holiday you enjoyed.\n\nTranscript: Last summer, I went on a holiday to Thailand with my family. We stayed in a hotel near the beach in Phuket. The weather was very hot and sunny. We swam in the sea every day. The water was clear and blue. We also visited some temples, which were very beautiful. I tried Thai food for the first time. It was spicy but delicious. We took a boat trip to an island. It was very exciting. I bought some souvenirs for my friends. We stayed there for one week. It was the best holiday of my life because I was with my family.\n\nWord Count: 105 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses topic words: 'souvenirs', 'spicy', 'temples'. Meaning is clear.\n\n>Band 4: Adequate vocabulary.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Uses basic sentences accurately. Relative clause and past tense used correctly.\n\n>Band 4: Frequent error-free sentences.\n\nNot Band 6: Limited range of structures.\n\n**Micro flaws identified:**\n- None."
    },
    # 435. V5/G5 - Food (Cooking)
    {
        "sample_id": "syn_p2_v5_g5_0435",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a meal you cooked.",
        "transcript_cleaned": "I cooked spaghetti for my family last Sunday. It is my favorite dish to make. I bought the ingredients at the supermarket. I needed pasta, tomatoes, onions, and meat. First, I boiled the water for the pasta. Then, I cut the vegetables and cooked the meat in a pan. I added the tomatoes to make the sauce. It smelled very good. I mixed everything together. My family liked it very much. They said it was delicious. I felt proud of myself. Cooking is fun, but cleaning up is boring. I want to learn how to cook more dishes in the future.",
        "word_count": 104,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "basic", "accuracy": "controlled", "flexibility": "limited"},
        "vocab_reason": "[LR5] Vocabulary: 'cooked', 'spaghetti', 'dish', 'ingredients', 'supermarket', 'pasta', 'tomatoes', 'onions', 'meat', 'boiled', 'sauce', 'mixed', 'delicious', 'proud', 'cleaning up'. Functional vocabulary relevant to the topic. >Band 4: Uses specific words ('ingredients', 'sauce'). Not Band 6: Simple vocabulary.",
        "grammar_reason": "[GRA5] Basic sentence forms are accurate. Uses sequence markers ('First', 'Then') correctly. Past tense used correctly ('bought', 'needed', 'boiled'). >Band 4: Accuracy is good. Not Band 6: Limited complexity.",
        "vocabulary": 5,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a meal you cooked.\n\nTranscript: I cooked spaghetti for my family last Sunday. It is my favorite dish to make. I bought the ingredients at the supermarket. I needed pasta, tomatoes, onions, and meat. First, I boiled the water for the pasta. Then, I cut the vegetables and cooked the meat in a pan. I added the tomatoes to make the sauce. It smelled very good. I mixed everything together. My family liked it very much. They said it was delicious. I felt proud of myself. Cooking is fun, but cleaning up is boring. I want to learn how to cook more dishes in the future.\n\nWord Count: 104 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses topic words: 'ingredients', 'boiled', 'sauce'. Meaning is clear.\n\n>Band 4: Adequate vocabulary.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Uses basic sentences accurately. Sequence markers and past tense used correctly.\n\n>Band 4: Frequent error-free sentences.\n\nNot Band 6: Limited range of structures.\n\n**Micro flaws identified:**\n- None."
    },
    # 436. V5/G5 - Activity (Daily)
    {
        "sample_id": "syn_p2_v5_g5_0436",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe your morning routine.",
        "transcript_cleaned": "I wake up at 7 am every day. I usually feel tired, so I stay in bed for ten minutes. Then I get up and brush my teeth. I wash my face with cold water to wake up. I get dressed for school. I wear my uniform. After that, I eat breakfast in the kitchen. I usually have toast and milk. I check my phone for messages. I leave my house at 8 am to catch the bus. The bus is often crowded. I listen to music on the bus. I arrive at school at 8:30 am. This is what I do every morning.",
        "word_count": 107,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "basic", "accuracy": "controlled", "flexibility": "limited"},
        "vocab_reason": "[LR5] Vocabulary: 'wake up', 'tired', 'stay in bed', 'brush teeth', 'wash face', 'get dressed', 'uniform', 'breakfast', 'toast', 'messages', 'catch the bus', 'crowded', 'arrive'. Functional vocabulary relevant to the topic. >Band 4: Uses specific words ('uniform', 'crowded'). Not Band 6: Simple vocabulary.",
        "grammar_reason": "[GRA5] Basic sentence forms are accurate. Uses 'so' clause correctly. Present tense used correctly ('wake', 'feel', 'get'). >Band 4: Accuracy is good. Not Band 6: Limited complexity.",
        "vocabulary": 5,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe your morning routine.\n\nTranscript: I wake up at 7 am every day. I usually feel tired, so I stay in bed for ten minutes. Then I get up and brush my teeth. I wash my face with cold water to wake up. I get dressed for school. I wear my uniform. After that, I eat breakfast in the kitchen. I usually have toast and milk. I check my phone for messages. I leave my house at 8 am to catch the bus. The bus is often crowded. I listen to music on the bus. I arrive at school at 8:30 am. This is what I do every morning.\n\nWord Count: 107 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses topic words: 'uniform', 'crowded', 'arrive'. Meaning is clear.\n\n>Band 4: Adequate vocabulary.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Uses basic sentences accurately. 'So' clause and present tense used correctly.\n\n>Band 4: Frequent error-free sentences.\n\nNot Band 6: Limited range of structures.\n\n**Micro flaws identified:**\n- None."
    },
    # 437. V5/G5 - City (Live)
    {
        "sample_id": "syn_p2_v5_g5_0437",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe the city you live in.",
        "transcript_cleaned": "I live in Manchester, which is a big city in England. It is famous for its football teams. I have lived here for ten years. The city is very busy and noisy. There are many shops and restaurants in the center. I like living here because there is a lot to do. We have cinemas, museums, and parks. However, the weather is often rainy and cold. The traffic is also very bad in the morning. Despite this, the people are friendly. I have many friends here. I think it is a good place for young people to live and work.",
        "word_count": 103,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "basic", "accuracy": "controlled", "flexibility": "limited"},
        "vocab_reason": "[LR5] Vocabulary: 'big city', 'famous', 'football teams', 'busy', 'noisy', 'shops', 'restaurants', 'cinemas', 'museums', 'weather', 'rainy', 'traffic', 'friendly'. Functional vocabulary relevant to the topic. >Band 4: Uses specific words ('museums', 'traffic'). Not Band 6: Simple vocabulary.",
        "grammar_reason": "[GRA5] Basic sentence forms are accurate. Uses relative clause ('which is') and 'because' clause correctly. Present perfect used correctly ('have lived'). >Band 4: Accuracy is good. Not Band 6: Limited complexity.",
        "vocabulary": 5,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe the city you live in.\n\nTranscript: I live in Manchester, which is a big city in England. It is famous for its football teams. I have lived here for ten years. The city is very busy and noisy. There are many shops and restaurants in the center. I like living here because there is a lot to do. We have cinemas, museums, and parks. However, the weather is often rainy and cold. The traffic is also very bad in the morning. Despite this, the people are friendly. I have many friends here. I think it is a good place for young people to live and work.\n\nWord Count: 103 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses topic words: 'museums', 'traffic', 'friendly'. Meaning is clear.\n\n>Band 4: Adequate vocabulary.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Uses basic sentences accurately. Relative clause and present perfect used correctly.\n\n>Band 4: Frequent error-free sentences.\n\nNot Band 6: Limited range of structures.\n\n**Micro flaws identified:**\n- None."
    },
    # 438. V5/G5 - Game (Childhood)
    {
        "sample_id": "syn_p2_v5_g5_0438",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a game you played as a child.",
        "transcript_cleaned": "When I was a child, I played hide and seek with my friends. It was my favorite game. We played it in the park or in my house. One person had to count to ten, and the others had to hide. I was very good at hiding. I usually hid behind a tree or under a bed. It was very exciting to wait. Sometimes, my friends could not find me. We played this game for hours. It made us laugh a lot. I miss playing games like this. Now I am too old, but I have good memories of it.",
        "word_count": 103,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "basic", "accuracy": "controlled", "flexibility": "limited"},
        "vocab_reason": "[LR5] Vocabulary: 'child', 'hide and seek', 'favorite game', 'count', 'hide', 'hiding', 'hid', 'exciting', 'wait', 'find', 'laugh', 'memories'. Functional vocabulary relevant to the topic. >Band 4: Uses specific words ('hide and seek'). Not Band 6: Simple vocabulary.",
        "grammar_reason": "[GRA5] Basic sentence forms are accurate. Uses past tense correctly ('was', 'played', 'had', 'hid'). >Band 4: Accuracy is good. Not Band 6: Limited complexity.",
        "vocabulary": 5,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a game you played as a child.\n\nTranscript: When I was a child, I played hide and seek with my friends. It was my favorite game. We played it in the park or in my house. One person had to count to ten, and the others had to hide. I was very good at hiding. I usually hid behind a tree or under a bed. It was very exciting to wait. Sometimes, my friends could not find me. We played this game for hours. It made us laugh a lot. I miss playing games like this. Now I am too old, but I have good memories of it.\n\nWord Count: 103 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses topic words: 'hide and seek', 'count', 'memories'. Meaning is clear.\n\n>Band 4: Adequate vocabulary.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Uses basic sentences accurately. Past tense used correctly throughout.\n\n>Band 4: Frequent error-free sentences.\n\nNot Band 6: Limited range of structures.\n\n**Micro flaws identified:**\n- None."
    },
    # 439. V5/G5 - Clothes (Favorite)
    {
        "sample_id": "syn_p2_v5_g5_0439",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe your favorite piece of clothing.",
        "transcript_cleaned": "My favorite piece of clothing is my blue jacket. I bought it last winter. It is made of wool, so it is very warm. I wear it when the weather is cold. It has a hood and two big pockets. I like the color because it matches my jeans. It was a bit expensive, but good quality. I wear it to school and when I go out with friends. My mother says it looks good on me. I have washed it many times, but it still looks new. I want to keep this jacket for a long time.",
        "word_count": 102,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "basic", "accuracy": "controlled", "flexibility": "limited"},
        "vocab_reason": "[LR5] Vocabulary: 'clothing', 'jacket', 'winter', 'wool', 'warm', 'weather', 'hood', 'pockets', 'matches', 'expensive', 'quality', 'washed'. Functional vocabulary relevant to the topic. >Band 4: Uses specific words ('wool', 'hood'). Not Band 6: Simple vocabulary.",
        "grammar_reason": "[GRA5] Basic sentence forms are accurate. Uses 'so' and 'because' clauses correctly. Present perfect used correctly ('have washed'). >Band 4: Accuracy is good. Not Band 6: Limited complexity.",
        "vocabulary": 5,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe your favorite piece of clothing.\n\nTranscript: My favorite piece of clothing is my blue jacket. I bought it last winter. It is made of wool, so it is very warm. I wear it when the weather is cold. It has a hood and two big pockets. I like the color because it matches my jeans. It was a bit expensive, but good quality. I wear it to school and when I go out with friends. My mother says it looks good on me. I have washed it many times, but it still looks new. I want to keep this jacket for a long time.\n\nWord Count: 102 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses topic words: 'wool', 'hood', 'pockets'. Meaning is clear.\n\n>Band 4: Adequate vocabulary.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Uses basic sentences accurately. 'So' clause and present perfect used correctly.\n\n>Band 4: Frequent error-free sentences.\n\nNot Band 6: Limited range of structures.\n\n**Micro flaws identified:**\n- None."
    },
    # 440. V5/G5 - Weather (Winter)
    {
        "sample_id": "syn_p2_v5_g5_0440",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe the weather in winter in your country.",
        "transcript_cleaned": "In my country, winter is very cold. It usually starts in December and ends in February. The temperature can drop below zero. Sometimes it snows, which is very beautiful. Everything turns white. Children like to play in the snow and make snowmen. I have to wear warm clothes like a coat and gloves. I prefer to stay inside where it is warm. We drink hot chocolate to keep warm. The days are short, and it gets dark early. I do not like winter very much because I cannot do outdoor activities. I wait for spring to come.",
        "word_count": 102,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "basic", "accuracy": "controlled", "flexibility": "limited"},
        "vocab_reason": "[LR5] Vocabulary: 'winter', 'cold', 'December', 'February', 'temperature', 'drop', 'zero', 'snows', 'white', 'snowmen', 'coat', 'gloves', 'hot chocolate', 'short', 'dark', 'outdoor activities'. Functional vocabulary relevant to the topic. >Band 4: Uses specific words ('temperature', 'gloves'). Not Band 6: Simple vocabulary.",
        "grammar_reason": "[GRA5] Basic sentence forms are accurate. Uses relative clause ('which is') and 'because' clause correctly. >Band 4: Accuracy is good. Not Band 6: Limited complexity.",
        "vocabulary": 5,
        "grammar": 5,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe the weather in winter in your country.\n\nTranscript: In my country, winter is very cold. It usually starts in December and ends in February. The temperature can drop below zero. Sometimes it snows, which is very beautiful. Everything turns white. Children like to play in the snow and make snowmen. I have to wear warm clothes like a coat and gloves. I prefer to stay inside where it is warm. We drink hot chocolate to keep warm. The days are short, and it gets dark early. I do not like winter very much because I cannot do outdoor activities. I wait for spring to come.\n\nWord Count: 102 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Uses topic words: 'temperature', 'snowmen', 'gloves'. Meaning is clear.\n\n>Band 4: Adequate vocabulary.\n\nNot Band 6: Lacks variety.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Uses basic sentences accurately. Relative clause used correctly.\n\n>Band 4: Frequent error-free sentences.\n\nNot Band 6: Limited range of structures.\n\n**Micro flaws identified:**\n- None."
    }
]

with open(OUTPUT_FILE, 'a', encoding='utf-8') as f:
    for sample in samples:
        f.write(json.dumps(sample) + '\n')
