import json

OUTPUT_FILE = "ielts-data/phase3/v76_review_output/synthetic_batches/batch_p2_11.jsonl"

samples = [
    # 511. V8/G7 - Book (Childhood)
    {
        "sample_id": "syn_p2_v8_g7_0511",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a book you enjoyed as a child.",
        "transcript_cleaned": "I fondly remember reading 'The Chronicles of Narnia', a fantasy series that captivated my imagination. The narrative transported me to a magical realm filled with mythical creatures and epic battles. I was particularly enamored with the character of Aslan, a majestic lion who symbolized wisdom and courage. The vivid descriptions of the wintry landscapes were mesmerizing. Although the language was sometimes archaic, I found the plot compelling. It instilled in me a love for literature that has persisted into adulthood. Reading it felt like embarking on a grand adventure. It remains a cherished part of my childhood memories.",
        "word_count": 99,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR8] Vocabulary: 'fondly', 'captivated', 'narrative', 'transported', 'magical realm', 'mythical creatures', 'epic', 'enamored', 'majestic', 'symbolized', 'vivid descriptions', 'mesmerizing', 'archaic', 'compelling', 'instilled', 'persisted', 'embarking', 'cherished'. Sophisticated and precise. >Band 7: Wide range of less common words. Not Band 9: Some phrases are slightly formulaic.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'That captivated my imagination' (Relative clause). 'Filled with mythical creatures' (Participle phrase). 'Who symbolized wisdom...' (Relative clause). 'Although the language was...' (Concessive clause). Accurate. >Band 6: Good control. Not Band 8: Sentences are somewhat standard in structure.",
        "vocabulary": 8,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a book you enjoyed as a child.\n\nTranscript: I fondly remember reading 'The Chronicles of Narnia', a fantasy series that captivated my imagination. The narrative transported me to a magical realm filled with mythical creatures and epic battles. I was particularly enamored with the character of Aslan, a majestic lion who symbolized wisdom and courage. The vivid descriptions of the wintry landscapes were mesmerizing. Although the language was sometimes archaic, I found the plot compelling. It instilled in me a love for literature that has persisted into adulthood. Reading it felt like embarking on a grand adventure. It remains a cherished part of my childhood memories.\n\nWord Count: 99 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses sophisticated vocabulary: 'enamored', 'archaic', 'instilled', 'persisted'. Precise meaning.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Lacks native-like flow.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures accurately. Relative clauses and participle phrases used correctly. Good control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Limited variety.\n\n**Micro flaws identified:**\n- None."
    },
    # 512. V8/G7 - Place (City)
    {
        "sample_id": "syn_p2_v8_g7_0512",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a city you would like to work in.",
        "transcript_cleaned": "I would love to work in Singapore, a cosmopolitan metropolis known for its efficiency and innovation. It is a melting pot of cultures, which I find incredibly appealing. The city boasts a robust economy and cutting-edge infrastructure. I am drawn to the prospect of working in such a dynamic environment. The skyline, dominated by futuristic architecture, is visually striking. Although the cost of living is exorbitant, the career opportunities are unparalleled. I believe working there would accelerate my professional growth significantly. It is a hub for international business and networking.",
        "word_count": 92,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR8] Vocabulary: 'cosmopolitan metropolis', 'efficiency', 'innovation', 'melting pot', 'appealing', 'boasts', 'robust economy', 'cutting-edge infrastructure', 'drawn to', 'prospect', 'dynamic', 'skyline', 'futuristic architecture', 'visually striking', 'exorbitant', 'unparalleled', 'accelerate', 'professional growth', 'hub'. Very sophisticated. >Band 7: Precise vocabulary. Not Band 9: Slightly dense.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'Known for its efficiency...' (Participle phrase). 'Which I find incredibly appealing' (Relative clause). 'Dominated by futuristic architecture' (Participle phrase). 'Although the cost... is...' (Concessive clause). Accurate. >Band 6: Good control. Not Band 8: Structure is a bit repetitive.",
        "vocabulary": 8,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a city you would like to work in.\n\nTranscript: I would love to work in Singapore, a cosmopolitan metropolis known for its efficiency and innovation. It is a melting pot of cultures, which I find incredibly appealing. The city boasts a robust economy and cutting-edge infrastructure. I am drawn to the prospect of working in such a dynamic environment. The skyline, dominated by futuristic architecture, is visually striking. Although the cost of living is exorbitant, the career opportunities are unparalleled. I believe working there would accelerate my professional growth significantly. It is a hub for international business and networking.\n\nWord Count: 92 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses sophisticated vocabulary: 'cosmopolitan', 'exorbitant', 'unparalleled'. Precise.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: A bit list-like.\n\n**Idiom present:** Yes ('melting pot')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures accurately. Participle phrases and relative clauses are correct. Good control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Limited variety.\n\n**Micro flaws identified:**\n- None."
    },
    # 513. V8/G7 - Event (Concert)
    {
        "sample_id": "syn_p2_v8_g7_0513",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a musical event you watched on TV.",
        "transcript_cleaned": "I watched a rebroadcast of the Glastonbury Festival, which was a spectacular auditory experience. The lineup featured an eclectic mix of genres, from rock to electronic music. I was captivated by the headlining act's stage presence and vocal prowess. The energy of the crowd was palpable, even through the screen. The visual effects and pyrotechnics added to the grandeur of the performance. It was a immersive experience that transported me to the venue. Although I wasn't there in person, I felt a sense of camaraderie with the audience. It was a testament to the unifying power of music.",
        "word_count": 98,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR8] Vocabulary: 'rebroadcast', 'spectacular', 'auditory experience', 'lineup', 'eclectic mix', 'genres', 'captivated', 'headlining act', 'stage presence', 'vocal prowess', 'palpable', 'pyrotechnics', 'grandeur', 'immersive', 'transported', 'camaraderie', 'testament', 'unifying power'. Very sophisticated. >Band 7: Precise vocabulary. Not Band 9: Some phrases are common.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'Which was a spectacular auditory experience' (Relative clause). 'Featured an eclectic mix...' (Participle phrase implied). 'Although I wasn't there...' (Concessive clause). Accurate. >Band 6: Good control. Not Band 8: Structure is standard.",
        "vocabulary": 8,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a musical event you watched on TV.\n\nTranscript: I watched a rebroadcast of the Glastonbury Festival, which was a spectacular auditory experience. The lineup featured an eclectic mix of genres, from rock to electronic music. I was captivated by the headlining act's stage presence and vocal prowess. The energy of the crowd was palpable, even through the screen. The visual effects and pyrotechnics added to the grandeur of the performance. It was a immersive experience that transported me to the venue. Although I wasn't there in person, I felt a sense of camaraderie with the audience. It was a testament to the unifying power of music.\n\nWord Count: 98 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses sophisticated vocabulary: 'eclectic', 'prowess', 'palpable', 'camaraderie'. Precise.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Lacks native-like flow.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures accurately. Relative clauses and concessive clauses used correctly. Good control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Limited variety.\n\n**Micro flaws identified:**\n- None."
    },
    # 514. V8/G7 - Person (Famous)
    {
        "sample_id": "syn_p2_v8_g7_0514",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a famous scientist.",
        "transcript_cleaned": "I deeply admire Marie Curie, a physicist whose contributions to science were revolutionary. She is renowned for her pioneering research on radioactivity, a term she coined herself. Her dedication to her work was unwavering, despite facing immense prejudice as a female scientist. She remains the only person to win Nobel Prizes in two different scientific fields. I am inspired by her tenacity and intellectual brilliance. Her discovery of radium and polonium paved the way for modern medical treatments. She is an enduring icon of female empowerment and scientific inquiry.",
        "word_count": 89,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR8] Vocabulary: 'deeply admire', 'physicist', 'contributions', 'revolutionary', 'renowned', 'pioneering research', 'radioactivity', 'coined', 'dedication', 'unwavering', 'immense prejudice', 'tenacity', 'intellectual brilliance', 'discovery', 'paved the way', 'enduring icon', 'empowerment', 'scientific inquiry'. Very sophisticated. >Band 7: Precise vocabulary. Not Band 9: Some collocations are standard.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'Whose contributions... were revolutionary' (Relative clause). 'Despite facing immense prejudice...' (Prepositional phrase + Participle). 'To win Nobel Prizes...' (Infinitive phrase). Accurate. >Band 6: Good control. Not Band 8: Structure is standard.",
        "vocabulary": 8,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a famous scientist.\n\nTranscript: I deeply admire Marie Curie, a physicist whose contributions to science were revolutionary. She is renowned for her pioneering research on radioactivity, a term she coined herself. Her dedication to her work was unwavering, despite facing immense prejudice as a female scientist. She remains the only person to win Nobel Prizes in two different scientific fields. I am inspired by her tenacity and intellectual brilliance. Her discovery of radium and polonium paved the way for modern medical treatments. She is an enduring icon of female empowerment and scientific inquiry.\n\nWord Count: 89 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses sophisticated vocabulary: 'pioneering', 'unwavering', 'tenacity', 'inquiry'. Precise.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Lacks native-like flow.\n\n**Idiom present:** Yes ('paved the way')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures accurately. Relative clauses and prepositional phrases used correctly. Good control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Limited variety.\n\n**Micro flaws identified:**\n- None."
    },
    # 515. V8/G7 - Activity (Hobby)
    {
        "sample_id": "syn_p2_v8_g7_0515",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a creative hobby you would like to try.",
        "transcript_cleaned": "I am intrigued by the art of calligraphy, which I consider to be a meditative practice. It involves creating elegant lettering using a dip pen and ink. I am drawn to the aesthetic beauty and precision required for each stroke. Mastering this skill would demand patience and a steady hand. I visualize myself writing personalized invitations or greeting cards for my friends. It would be a therapeutic way to disconnect from digital devices. The idea of transforming mundane words into visual art is captivating. I hope to enroll in a workshop soon to learn the fundamentals.",
        "word_count": 96,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR8] Vocabulary: 'intrigued', 'calligraphy', 'meditative practice', 'elegant lettering', 'dip pen', 'drawn to', 'aesthetic beauty', 'precision', 'stroke', 'mastering', 'demand patience', 'steady hand', 'visualize', 'personalized', 'therapeutic', 'disconnect', 'transforming', 'mundane', 'captivating', 'enroll', 'fundamentals'. Very sophisticated. >Band 7: Precise vocabulary. Not Band 9: Slightly list-like.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'Which I consider to be...' (Relative clause). 'Involves creating...' (Gerund phrase). 'Required for each stroke' (Participle phrase). 'The idea of transforming...' (Gerund phrase). Accurate. >Band 6: Good control. Not Band 8: Structure is standard.",
        "vocabulary": 8,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a creative hobby you would like to try.\n\nTranscript: I am intrigued by the art of calligraphy, which I consider to be a meditative practice. It involves creating elegant lettering using a dip pen and ink. I am drawn to the aesthetic beauty and precision required for each stroke. Mastering this skill would demand patience and a steady hand. I visualize myself writing personalized invitations or greeting cards for my friends. It would be a therapeutic way to disconnect from digital devices. The idea of transforming mundane words into visual art is captivating. I hope to enroll in a workshop soon to learn the fundamentals.\n\nWord Count: 96 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses sophisticated vocabulary: 'meditative', 'aesthetic', 'mundane', 'fundamentals'. Precise.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Lacks native-like flow.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures accurately. Gerund phrases and relative clauses used correctly. Good control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Limited variety.\n\n**Micro flaws identified:**\n- None."
    },
    # 516. V8/G7 - Object (Clothes)
    {
        "sample_id": "syn_p2_v8_g7_0516",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a piece of clothing you wear on special occasions.",
        "transcript_cleaned": "I cherish a silk saree that was bequeathed to me by my mother. It is a garment of exquisite beauty, featuring intricate embroidery and gold thread work. The fabric is luxurious and drapes elegantly, enhancing my silhouette. I wear it exclusively for weddings and major festivals. It holds immense sentimental value, serving as a tangible connection to my heritage. Whenever I don this attire, I feel a sense of pride and elegance. It is timeless fashion that transcends trends. Preserving its pristine condition requires careful maintenance, but it is worth the effort.",
        "word_count": 93,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR8] Vocabulary: 'cherish', 'silk saree', 'bequeathed', 'garment', 'exquisite beauty', 'intricate embroidery', 'luxurious', 'drapes elegantly', 'enhancing', 'silhouette', 'exclusively', 'immense', 'sentimental value', 'tangible connection', 'heritage', 'don', 'attire', 'timeless', 'transcends trends', 'preserving', 'pristine condition', 'maintenance'. Very sophisticated. >Band 7: Precise vocabulary. Not Band 9: Slightly formal.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'That was bequeathed to me' (Relative clause). 'Featuring intricate embroidery' (Participle phrase). 'Serving as a tangible connection' (Participle phrase). 'Whenever I don this attire' (Time clause). Accurate. >Band 6: Good control. Not Band 8: Structure is standard.",
        "vocabulary": 8,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a piece of clothing you wear on special occasions.\n\nTranscript: I cherish a silk saree that was bequeathed to me by my mother. It is a garment of exquisite beauty, featuring intricate embroidery and gold thread work. The fabric is luxurious and drapes elegantly, enhancing my silhouette. I wear it exclusively for weddings and major festivals. It holds immense sentimental value, serving as a tangible connection to my heritage. Whenever I don this attire, I feel a sense of pride and elegance. It is timeless fashion that transcends trends. Preserving its pristine condition requires careful maintenance, but it is worth the effort.\n\nWord Count: 93 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses sophisticated vocabulary: 'bequeathed', 'exquisite', 'silhouette', 'transcends'. Precise.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Slightly stiff tone.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures accurately. Participle phrases and relative clauses used correctly. Good control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Limited variety.\n\n**Micro flaws identified:**\n- None."
    },
    # 517. V8/G7 - Place (Cafe)
    {
        "sample_id": "syn_p2_v8_g7_0517",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a cafe you enjoyed visiting.",
        "transcript_cleaned": "I stumbled upon a quaint bohemian cafe in Paris that captivated me instantly. It had an eclectic decor, filled with vintage furniture and quirky artwork. The aroma of freshly ground coffee and baked pastries was intoxicating. I savored a croissant that was flaky and buttery perfection. The ambiance was convivial yet relaxed, perfect for people-watching. I was charmed by the barista's warm hospitality and expertise. It felt like a hidden gem away from the tourist traps. Spending an afternoon there was a delightful indulgence that I look back on fondly.",
        "word_count": 91,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR8] Vocabulary: 'stumbled upon', 'quaint', 'bohemian', 'captivated', 'eclectic decor', 'vintage', 'quirky', 'aroma', 'intoxicating', 'savored', 'flaky', 'buttery', 'ambiance', 'convivial', 'charmed', 'barista', 'hospitality', 'expertise', 'hidden gem', 'tourist traps', 'delightful indulgence', 'fondly'. Very sophisticated. >Band 7: Precise vocabulary. Not Band 9: Some phrases are common.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'That captivated me instantly' (Relative clause). 'Filled with vintage furniture' (Participle phrase). 'That was flaky...' (Relative clause). 'Spending an afternoon there was...' (Gerund subject). Accurate. >Band 6: Good control. Not Band 8: Structure is standard.",
        "vocabulary": 8,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a cafe you enjoyed visiting.\n\nTranscript: I stumbled upon a quaint bohemian cafe in Paris that captivated me instantly. It had an eclectic decor, filled with vintage furniture and quirky artwork. The aroma of freshly ground coffee and baked pastries was intoxicating. I savored a croissant that was flaky and buttery perfection. The ambiance was convivial yet relaxed, perfect for people-watching. I was charmed by the barista's warm hospitality and expertise. It felt like a hidden gem away from the tourist traps. Spending an afternoon there was a delightful indulgence that I look back on fondly.\n\nWord Count: 91 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses sophisticated vocabulary: 'eclectic', 'intoxicating', 'convivial', 'indulgence'. Precise.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Lacks native-like flow.\n\n**Idiom present:** Yes ('hidden gem')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures accurately. Relative clauses and gerund subjects used correctly. Good control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Limited variety.\n\n**Micro flaws identified:**\n- None."
    },
    # 518. V8/G7 - Event (Sports)
    {
        "sample_id": "syn_p2_v8_g7_0518",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a sports event you enjoyed watching.",
        "transcript_cleaned": "I witnessed an exhilarating tennis match at Wimbledon that kept me on the edge of my seat. It was a clash of titans between two legendary players. The rallies were intense and protracted, showcasing their incredible stamina and agility. I was astounded by the precision of their shots and their strategic gameplay. The atmosphere in the stadium was electric, with the crowd erupting after every point. It culminated in a tie-break that was nerve-wracking to watch. Seeing the victor lift the trophy was a momentous occasion. It was a display of sheer athleticism and sportsmanship.",
        "word_count": 97,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR8] Vocabulary: 'witnessed', 'exhilarating', 'edge of my seat', 'clash of titans', 'legendary', 'rallies', 'protracted', 'showcasing', 'stamina', 'agility', 'astounded', 'precision', 'strategic', 'gameplay', 'electric', 'erupting', 'culminated', 'nerve-wracking', 'victor', 'momentous', 'sheer athleticism', 'sportsmanship'. Very sophisticated. >Band 7: Precise vocabulary. Not Band 9: Some phrases are common.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'That kept me on the edge...' (Relative clause). 'Showcasing their incredible stamina' (Participle phrase). 'That was nerve-wracking to watch' (Relative clause). 'Seeing the victor... was...' (Gerund subject). Accurate. >Band 6: Good control. Not Band 8: Structure is standard.",
        "vocabulary": 8,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a sports event you enjoyed watching.\n\nTranscript: I witnessed an exhilarating tennis match at Wimbledon that kept me on the edge of my seat. It was a clash of titans between two legendary players. The rallies were intense and protracted, showcasing their incredible stamina and agility. I was astounded by the precision of their shots and their strategic gameplay. The atmosphere in the stadium was electric, with the crowd erupting after every point. It culminated in a tie-break that was nerve-wracking to watch. Seeing the victor lift the trophy was a momentous occasion. It was a display of sheer athleticism and sportsmanship.\n\nWord Count: 97 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses sophisticated vocabulary: 'exhilarating', 'protracted', 'culminated', 'momentous'. Precise.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Lacks native-like flow.\n\n**Idiom present:** Yes ('clash of titans', 'edge of my seat')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures accurately. Relative clauses and participle phrases used correctly. Good control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Limited variety.\n\n**Micro flaws identified:**\n- None."
    },
    # 519. V8/G7 - Activity (Daily)
    {
        "sample_id": "syn_p2_v8_g7_0519",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe something you do to stay healthy.",
        "transcript_cleaned": "I adhere to a rigorous fitness regimen that includes high-intensity interval training. It is an efficient way to boost cardiovascular endurance and burn calories. I perform these exercises at home, utilizing minimal equipment. The routine is grueling but invigorating, releasing a flood of endorphins. I also prioritize nutritional balance by consuming a diet rich in whole foods. Staying hydrated is another crucial aspect of my lifestyle. This discipline has enhanced my physical vitality and mental clarity significantly. It is a proactive approach to preventing lifestyle-related diseases.",
        "word_count": 86,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR8] Vocabulary: 'adhere', 'rigorous', 'regimen', 'high-intensity interval training', 'efficient', 'boost', 'cardiovascular endurance', 'utilizing', 'minimal equipment', 'grueling', 'invigorating', 'flood of endorphins', 'prioritize', 'nutritional balance', 'consuming', 'hydrated', 'crucial aspect', 'discipline', 'enhanced', 'vitality', 'mental clarity', 'proactive', 'preventing'. Very sophisticated. >Band 7: Precise vocabulary. Not Band 9: Slightly formal.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'That includes...' (Relative clause). 'Utilizing minimal equipment' (Participle phrase). 'Releasing a flood of endorphins' (Participle phrase). 'By consuming a diet...' (Prepositional phrase + Gerund). Accurate. >Band 6: Good control. Not Band 8: Structure is standard.",
        "vocabulary": 8,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": False,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe something you do to stay healthy.\n\nTranscript: I adhere to a rigorous fitness regimen that includes high-intensity interval training. It is an efficient way to boost cardiovascular endurance and burn calories. I perform these exercises at home, utilizing minimal equipment. The routine is grueling but invigorating, releasing a flood of endorphins. I also prioritize nutritional balance by consuming a diet rich in whole foods. Staying hydrated is another crucial aspect of my lifestyle. This discipline has enhanced my physical vitality and mental clarity significantly. It is a proactive approach to preventing lifestyle-related diseases.\n\nWord Count: 86 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses sophisticated vocabulary: 'rigorous', 'endurance', 'invigorating', 'proactive'. Precise.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Lacks native-like flow.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures accurately. Participle phrases and relative clauses used correctly. Good control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Limited variety.\n\n**Micro flaws identified:**\n- None."
    },
    # 520. V8/G7 - Person (Family)
    {
        "sample_id": "syn_p2_v8_g7_0520",
        "video_id": "synthetic",
        "part": 2,
        "question": "Describe a family member you admire.",
        "transcript_cleaned": "I hold my grandfather in high esteem; he is a paragon of resilience and integrity. He endured significant hardships during his youth but never succumbed to bitterness. Instead, he cultivated a compassionate outlook and a generous spirit. He possesses an encyclopedic memory and regales us with fascinating anecdotes from the past. His wisdom is a guiding light for our family during turbulent times. I admire his unwavering commitment to his principles and his work ethic. He has aged gracefully, maintaining a sharp wit and zest for life. He is truly an inspiration to me.",
        "word_count": 96,
        "response_type": "long_turn",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "vocab_reason": "[LR8] Vocabulary: 'hold in high esteem', 'paragon', 'resilience', 'integrity', 'endured', 'hardships', 'succumbed', 'bitterness', 'cultivated', 'compassionate outlook', 'generous spirit', 'encyclopedic memory', 'regales', 'anecdotes', 'guiding light', 'turbulent', 'unwavering commitment', 'principles', 'work ethic', 'aged gracefully', 'sharp wit', 'zest for life'. Very sophisticated. >Band 7: Precise vocabulary. Not Band 9: Some phrases are common.",
        "grammar_reason": "[GRA7] Frequent error-free complex structures. 'Who is a paragon...' (Relative clause implied). 'During his youth but never...' (Conjunction). 'Maintaining a sharp wit...' (Participle phrase). Accurate. >Band 6: Good control. Not Band 8: Structure is standard.",
        "vocabulary": 8,
        "grammar": 7,
        "is_valid": True,
        "dataset_source": "synthetic",
        "idiom_present": True,
        "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": "Part: 2\nQuestion: Describe a family member you admire.\n\nTranscript: I hold my grandfather in high esteem; he is a paragon of resilience and integrity. He endured significant hardships during his youth but never succumbed to bitterness. Instead, he cultivated a compassionate outlook and a generous spirit. He possesses an encyclopedic memory and regales us with fascinating anecdotes from the past. His wisdom is a guiding light for our family during turbulent times. I admire his unwavering commitment to his principles and his work ethic. He has aged gracefully, maintaining a sharp wit and zest for life. He is truly an inspiration to me.\n\nWord Count: 96 words\nResponse Type: long_turn",
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Uses sophisticated vocabulary: 'paragon', 'succumbed', 'regales', 'unwavering'. Precise.\n\n>Band 7: Advanced vocabulary.\n\nNot Band 9: Lacks native-like flow.\n\n**Idiom present:** Yes ('guiding light', 'zest for life')\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Uses complex structures accurately. Participle phrases used correctly. Good control.\n\n>Band 6: Frequent error-free sentences.\n\nNot Band 8: Limited variety.\n\n**Micro flaws identified:**\n- None."
    }
]

with open(OUTPUT_FILE, 'a', encoding='utf-8') as f:
    for sample in samples:
        f.write(json.dumps(sample) + '\n')
