import json

batch_num = 42
filename = f"ielts-data/phase3/v76_review_output/synthetic_batches/batch_p3_10.jsonl"
# Batch 42: V8/G5(10) V6/G9(10) V9/G6(10) V5/G5(10) V6/G6(10) | 0451–0500
start_id = 451
samples = []

# V8 / G5
c1_q = "How do historical landmarks contribute to a nation's identity?"
c1_t = [
    "I believing that these architectural marvels they functions as tangible repositories of a nation's collective memory. When citizens visiting these awe-inspiring monuments, they feels a profound connection to their ancestral heritage. However, maintaining these indispensable cultural artifacts it demanding exorbitant municipal expenditure. Many cash-strapped local authorities they prioritizing lucrative commercial developments over heritage conservation, which precipitating the gradual erosion of our unique national character.",
    "These majestic ancient edifices they unequivocally embodying the resilience and ingenuity of our forebears. By preserving these meticulously crafted structures, we ensures that future generations can comprehending their historical trajectory. But unfortunately, rampant urban gentrification it frequently marginalizing the indigenous communities living near these landmarks. The resultant socioeconomic displacement it severely undermining the authentic cultural vibrancy that these monuments supposedly representing.",
    "I'd argue that historic monuments they serving as potent symbols of civic pride and unyielding national solidarity. They frequently commemorating pivotal triumphs or profound tragedies that shaping the nation's contemporary geopolitical landscape. Yet, some controversial statues they glorifying historical figures whose actions is now deemed ethically reprehensible. This igniting fierce dialectical debates regarding whether we should completely eradicating these polarizing symbols from public spaces.",
    "Preserving these indispensable antiquities it significantly bolstering the lucrative international tourism sector. Millions of enthusiastic globetrotters they flocking annually to admire our distinctive architectural vernacular. But this relentless influx of tourists it often accelerating the structural degradation of these fragile ancient sites. Consequently, governments they must implementing stringent, highly sophisticated conservation protocols to mitigate this catastrophic environmental wear and tear.",
    "These monumental structures they providing an immersive, visceral educational experience that sterile textbooks simply cannot replicating. Students they wandering through these archaic corridors and gaining a profound, multi-sensory understanding of bygone historical epochs. However, adapting these centuries-old buildings to accommodate modern accessibility standards it posing a formidable engineering conundrum. Many architectural conservationists they struggling to integrate necessary modern amenities without compromising the building's authentic structural integrity.",
    "I asserting that iconic landmarks they actively cultivating a cohesive, unified national narrative. They standing as enduring testaments to our shared cultural evolution, transcending transient political ideologies. But the astronomical financial burden of sourcing period-accurate restoration materials it frequently deterring comprehensive conservation efforts. If wealthy philanthropic organizations they not intervening with substantial grants, many of these irreplaceable structures is destined for irreversible ruin.",
    "These awe-inspiring historical sites they fundamentally anchoring our increasingly transient, highly globalized modern society. In an era dominated by homogenous, sterile corporate architecture, these ancient monuments they radiating a profoundly authentic, unique local charm. Yet, some cynical pragmatic economists they arguing that these dilapidated buildings is occupying prime urban real estate unnecessarily. They advocating for their demolition to facilitate the construction of lucrative, high-density commercial complexes.",
    "By meticulously safeguarding our architectural lineage, we effectively demonstrating profound reverence for our ancestors' unparalleled craftsmanship. The intricate, artisanal detailing on these ancient facades they are virtually impossible to replicate using contemporary mass-production techniques. But sadly, prolonged exposure to toxic industrial pollution and severe acid rain it accelerating the catastrophic deterioration of these delicate stone carvings. Protective environmental legislation it being urgently required to halt this alarming degradation.",
    "Historical monuments they frequently acting as the charismatic focal point for vibrant community gatherings and cultural festivals. They providing a majestic, historically resonant backdrop for significant civic ceremonies that reinforcing social cohesion. However, the pervasive commercialization of these sacred sites it often transforming them into tacky, superficial tourist traps. This rampant commodification it severely diluting their profound historical gravitas and intrinsic cultural significance.",
    "Ultimately, these architectural treasures they constituting the irreplaceable, foundational bedrock of our distinct national identity. They silently witnessing the tumultuous ebb and flow of centuries, offering invaluable perspective on our contemporary societal struggles. If we allowing these monumental edifices to crumble into obscure oblivion, we inevitably severing our profound, vital connection to the invaluable lessons of our shared historical past."
]

for i in range(10):
    wc = len(c1_t[i].split())
    samples.append({
        "sample_id": f"syn_p3_v8_g5_{start_id:04d}", "video_id": "synthetic", "part": 3, "question": c1_q,
        "transcript_cleaned": c1_t[i], "word_count": wc, "response_type": "extended" if wc > 80 else "direct_answer",
        "vocabulary": 8, "grammar": 5, "is_valid": True, "dataset_source": "synthetic",
        "idiom_present": False, "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": f"Part: 3\nQuestion: {c1_q}\n\nTranscript: {c1_t[i]}\n\nWord Count: {wc} words\nResponse Type: {'extended' if wc > 80 else 'direct_answer'}",
        "vocab_reason": "[LR8] Very sophisticated and precise vocabulary ('architectural marvels', 'tangible repositories', 'rampant urban gentrification', 'indispensable antiquities'). The vocabulary range is wide and used skillfully.",
        "grammar_reason": "[GRA5] Grammar is plagued by systematic errors in basic structures, especially verb forms ('I believing', 'they functions', 'it demanding', 'they prioritizing'). While complex structures are attempted, the frequent and fundamental errors restrict the score.",
        "micro_flaws": ["verb form errors: 'I believing', 'they functions'", "double subjects: 'authorities they'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "variable", "flexibility": "limited"},
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Wide vocabulary range used precisely and skillfully.\n\n>Band 7: More sophisticated and idiomatic than a 7.\n\nNot Band 9: The broken grammar makes it hard to judge absolute native-like perfection, though the vocabulary is excellent.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Systematic errors in basic sentence forms and verb conjugations.\n\n>Band 4: Attempts more complex structures than a 4, though with errors.\n\nNot Band 6: The errors are too frequent and systematic in basic structures."
    })
    start_id += 1

# V6 / G9
c2_q = "Do you think public transport should be free of charge?"
c2_t = [
    "I am strongly convinced that providing complimentary public transportation would yield immense societal benefits. By eliminating fare collection entirely, municipalities could seamlessly alleviate the severe traffic congestion that chronically plagues our urban centers. Were people not financially burdened by daily commuting costs, they would undoubtedly be far more inclined to utilize buses and trains instead of relying on their private vehicles. This paradigm shift would concurrently lead to a drastic reduction in harmful greenhouse gas emissions.",
    "Making public transit entirely free is essentially a matter of promoting fundamental social equality. For individuals grappling with low incomes, daily transportation expenses often constitute an unmanageable portion of their limited monthly budgets. Provided that the government implements a robust subsidy system, we could guarantee that marginalized communities have unhindered access to broader employment and educational opportunities. No one should ever find themselves economically disadvantaged simply because they cannot afford a basic bus ticket to reach their workplace.",
    "There is a highly compelling economic argument to be made for completely abolishing transit fares. Although the initial loss of ticket revenue might appear daunting to city planners, the long-term financial dividends would be substantial. By minimizing the number of cars on the road, the government would save astronomical sums of money that are currently squandered on repairing damaged highways and managing complex traffic accidents. A highly efficient, free transport network essentially acts as a powerful catalyst for broader economic productivity.",
    "One must also consider the profound implications this policy would have on overall public health. The pervasive air pollution generated by thousands of idling cars is a leading cause of severe respiratory illnesses in densely populated cities. Should local authorities decide to fully subsidize clean, electric public transport, the subsequent improvement in air quality would be dramatic. Consequently, the national healthcare system would be relieved of the immense financial strain currently caused by treating pollution-related diseases.",
    "I believe that implementing free public transport would fundamentally revolutionize the architectural layout of our modern cities. Currently, vast, valuable areas of urban real estate are entirely wasted on massive concrete parking structures and wide highways. If a reliable, free transit system were established, urban planners could confidently reclaim these spaces, transforming them into vibrant public parks and pedestrian zones. This would drastically enhance the overall aesthetic appeal and livability of our crowded urban environments.",
    "While some critics argue that free transit would inevitably lead to overcrowded and poorly maintained vehicles, I find this perspective rather short-sighted. It is imperative that the removal of fares is accompanied by a massive, sustained injection of government funding to upgrade the existing infrastructure. Only by simultaneously expanding the network capacity and ensuring rigorous maintenance schedules can authorities prevent the system from collapsing under the weight of increased passenger demand.",
    "A completely free, highly efficient transit system is absolutely crucial for maintaining a city's competitive edge on the global stage. Major international corporations and highly skilled professionals are consistently drawn to metropolitan areas that boast seamless, affordable connectivity. Were a city's transportation infrastructure to remain prohibitively expensive and inefficient, it would inevitably suffer from severe economic stagnation, as investment capital naturally gravitates towards more progressive and accessible urban centers.",
    "The societal advantages of this policy extend far beyond simple logistical efficiency; it actively fosters a palpable sense of community cohesion. When individuals from vastly different socioeconomic backgrounds share the exact same commuting spaces daily, it subtly breaks down rigid societal barriers. This shared urban experience serves to counteract the profound social isolation that frequently occurs when everyone is perpetually segregated within the confined spaces of their private automobiles.",
    "From an environmental perspective, mere incremental improvements are no longer sufficient to combat the looming crisis. We are currently facing unprecedented ecological challenges that demand bold, decisive governmental action. Transitioning the vast majority of the population away from gas-powered private transport towards heavily subsidized, electrified public rail networks is not merely an optional civic upgrade; it is an absolute necessity for ensuring our long-term environmental sustainability.",
    "For this ambitious initiative to be truly successful, the execution must be flawlessly managed by the relevant authorities. It is simply not enough to make the buses free if they remain notoriously unreliable or fail to serve remote suburban neighborhoods. The financial investment must holistically address the entire network, ensuring frequent, punctual services that genuinely offer a superior commuting alternative to driving a personal vehicle."
]

for i in range(10):
    wc = len(c2_t[i].split())
    samples.append({
        "sample_id": f"syn_p3_v6_g9_{start_id:04d}", "video_id": "synthetic", "part": 3, "question": c2_q,
        "transcript_cleaned": c2_t[i], "word_count": wc, "response_type": "extended" if wc > 80 else "direct_answer",
        "vocabulary": 6, "grammar": 9, "is_valid": True, "dataset_source": "synthetic",
        "idiom_present": False, "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": f"Part: 3\nQuestion: {c2_q}\n\nTranscript: {c2_t[i]}\n\nWord Count: {wc} words\nResponse Type: {'extended' if wc > 80 else 'direct_answer'}",
        "vocab_reason": "[LR6] Uses an adequate range of vocabulary for the topic ('complimentary', 'municipalities', 'alleviate', 'marginalized'). It goes beyond basic vocabulary but lacks the highly sophisticated and idiomatic expressions typical of Band 8 or 9.",
        "grammar_reason": "[GRA9] Flawless use of a wide range of complex structures ('Were people not financially burdened...', 'Provided that the government implements...', 'Should local authorities decide...'). The grammar is completely natural and accurate.",
        "micro_flaws": [],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses an adequate range of vocabulary clearly and accurately.\n\n>Band 5: Better range and more precision than a 5.\n\nNot Band 7: Lacks the sustained stylistic awareness and less common idiomatic items of a 7.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Flawless use of a wide range of complex structures. The grammar is entirely natural.\n\n>Band 8: Complete mastery with zero minor slips.\n\nNot Band N/A: Top score.\n\n**Micro flaws identified:**\n- None."
    })
    start_id += 1

# V9 / G6
c3_q = "How does advertising influence consumer behavior?"
c3_t = [
    "The ubiquitous nature of contemporary advertising unequivocally manipulating consumer psychology on a profound level. Marketing conglomerates they employing highly sophisticated, data-driven algorithms to relentlessly target our deepest insecurities. By masterfully fabricating an artificial sense of inadequacy, these pervasive campaigns it compelling individuals to purchase superfluous commodities they do not genuinely require. This relentless psychological bombardment it ultimately fostering a highly unsustainable, hyper-consumerist societal paradigm.",
    "I believe that modern advertising it operating as an insidious catalyst for relentless materialistic desire. Rather than merely highlighting a product's utilitarian functionality, advertisers they ingeniously associating their brands with abstract concepts like prestige, happiness, and social validation. Consequently, vulnerable consumers they purchasing these premium luxury items in a desperate, futile attempt to elevate their perceived socioeconomic status among their peer group.",
    "The sheer proliferation of targeted digital marketing it has fundamentally obliterating the concept of consumer privacy. Tech behemoths they constantly harvesting our intimate browsing data to meticulously curate hyper-personalized advertisements. This bespoke algorithmic targeting it effectively bypassing our rational cognitive defenses, making us highly susceptible to impulsive, unnecessary expenditures. It representing a very dystopian convergence of surveillance capitalism and psychological manipulation.",
    "While some proponents arguing that advertising it serving a vital educational function by informing the public about innovative new products, I remain deeply skeptical. The overarching objective of these corporate campaigns it are rarely objective education; rather, it is the aggressive maximization of corporate profitability. They frequently utilizing deceptive, highly hyperbolic rhetoric to deliberately obscure a product's inherent flaws or detrimental environmental consequences.",
    "The pervasive influence of advertising on impressionable youth it is a particularly egregious moral concern. Children they possessing highly malleable cognitive faculties, making them exceptionally vulnerable to aggressive, brightly colored marketing campaigns for ubiquitous junk food and frivolous toys. Unless stringent governmental regulations is immediately implemented to curtail this predatory corporate behavior, we risking the psychological well-being of an entire generation.",
    "Advertising it profoundly exacerbating our collective ecological footprint by relentlessly championing a culture of rapid, disposable consumption. Brands they constantly churning out ephemeral micro-trends, psychologically coercing consumers into believing their perfectly functional possessions is perpetually obsolete. This orchestrated strategy of planned obsolescence it driving catastrophic levels of environmental degradation and resource depletion globally, all in the relentless pursuit of infinite economic growth.",
    "I asserting that the omnipresence of advertising it significantly diluting the authenticity of our shared cultural landscape. Public spaces, once dedicated to civic engagement, they being aggressively monopolized by glaring, intrusive corporate billboards. This relentless visual pollution it completely commodifying our environment, transforming every conceivable surface into a desperate, aggressive plea for our dwindling financial resources and increasingly fractured attention spans.",
    "The psychological toll of this constant exposure it being deeply detrimental to collective societal mental health. By perpetually projecting impossibly flawless, digitally altered standards of beauty and success, the advertising industry it actively cultivating a pervasive epidemic of low self-esteem and chronic anxiety. Individuals they constantly feeling inadequate because their mundane reality predictably failing to mirror the highly curated, unattainable utopias depicted on their screens.",
    "Furthermore, political advertising it has profoundly corrupting the foundational integrity of our democratic processes. Well-funded special interest groups they deploying highly sophisticated, emotionally resonant smear campaigns to deliberately manipulate public opinion and obscure nuanced policy debates. This weaponization of marketing psychology it polarizing the electorate, transforming rational civic discourse into a toxic, superficial spectacle driven by tribalistic fear-mongering and blatant misinformation.",
    "Ultimately, the pervasive advertising apparatus it functioning as the indispensable, driving engine of contemporary global capitalism. It meticulously engineering the insatiable consumer demand required to sustain perpetual, unchecked economic expansion. However, confronting the severe environmental and psychological externalities of this system it necessitating a radical paradigm shift. We must actively cultivating profound media literacy to empower citizens to critically deconstruct and resist these relentless manipulative narratives."
]

for i in range(10):
    wc = len(c3_t[i].split())
    samples.append({
        "sample_id": f"syn_p3_v9_g6_{start_id:04d}", "video_id": "synthetic", "part": 3, "question": c3_q,
        "transcript_cleaned": c3_t[i], "word_count": wc, "response_type": "extended" if wc > 80 else "direct_answer",
        "vocabulary": 9, "grammar": 6, "is_valid": True, "dataset_source": "synthetic",
        "idiom_present": False, "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": f"Part: 3\nQuestion: {c3_q}\n\nTranscript: {c3_t[i]}\n\nWord Count: {wc} words\nResponse Type: {'extended' if wc > 80 else 'direct_answer'}",
        "vocab_reason": "[LR9] Uses highly sophisticated vocabulary with complete flexibility and precision ('ubiquitous', 'unequivocally', 'insidious catalyst', 'planned obsolescence', 'hyper-consumerist').",
        "grammar_reason": "[GRA6] While the vocabulary is exceptional, the grammar suffers from frequent, noticeable errors in basic structures ('advertising it operating', 'consumers they purchasing', 'campaigns it are'). Meaning is clear, but the error rate restricts the score.",
        "micro_flaws": ["double subjects: 'consumers they'", "verb form errors: 'it operating', 'it compelling'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "output": "## Vocabulary (Lexical Resource): Band 9\n\n**Reasoning:** [LR9] Complete flexibility and precision in vocabulary usage.\n\n>Band 8: More sophisticated and precise than an 8.\n\nNot Band N/A: Top score.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Frequent errors in basic sentence structures and verb forms, despite attempting complex sentences.\n\n>Band 5: Better range than a 5, meaning is never impeded.\n\nNot Band 7: Errors are far too frequent and noticeable for a 7.\n\n**Micro flaws identified:**\n- pervasive double subjects and incorrect verb conjugations"
    })
    start_id += 1

# V5 / G5
c4_q = "Why do people like traveling to new places?"
c4_t = [
    "I think people like to travel because they want to see beautiful things. When they go to a new country, they can look at big mountains and nice beaches. It is very fun for them. Also, they escaping their boring job in the city. Because the work is very hard, they needing a good holiday to relax their tired mind and body.",
    "Traveling is very popular because people want to eat different food. In my country, we eating the same things every day, which is very boring. If I going to Japan, I can try real sushi. Trying new food make people feel very happy. They can take many nice photos of the food and show them to their good friends at home.",
    "Many young people they travel because they want to learn about the world. When you visit an old city, you can seeing many old buildings and museums. This is much better than reading a boring book in school. You can learn about how other people living in the past. It making you very smart and give you a lot of good knowledge.",
    "I believe people travel to meet new friends. If you staying in your small town forever, you only see the same people. But when you stay in a big hotel in another country, you can talking to many different foreigners. Even if your English is not very good, you can smile and make a new friend. It is a very exciting experience.",
    "Traveling is a good way to spend free time with your family. Because parents working hard every day, they not having time to play with their children. When they go on a long holiday together, they can swimming in the pool and laughing together. This happy time making the family very close and they will remember the good memories forever.",
    "Some people they travel because the weather in their country is very bad. In the winter, it is too cold and dark in my city. So, many rich people they flying to a warm island to enjoy the bright sun. Lying on the hot sand is very relaxing for them. It helps them forget about the terrible cold weather back at home.",
    "People like to visit new places to buy cheap things. In some countries, clothes and shoes is very cheap to buy in the big markets. Many tourists they bringing empty bags and buying many gifts for their family. It is very fun to walk around the busy shops and find a good price. Shopping is a very big part of a nice holiday.",
    "Traveling helps people to be more brave and strong. When you are in a strange place, you must finding the right bus or train by yourself. Sometimes you getting lost, but you must ask people for help. This difficult situation it teaching you how to survive alone. After the trip, you feeling very confident because you solved the big problems successfully.",
    "I think some people travel just to show off on the internet. They visiting famous places like Paris or London so they can posting beautiful pictures on their phone. When their friends clicking 'like' on the photos, they feeling very proud and happy. It is a modern way to show people that you having a very good and rich life.",
    "Traveling is very important because it stop people from being narrow-minded. If you never leaving your country, you thinking your culture is the best in the world. But when you travel, you seeing that other people have different, good ways to live. It making you respect other cultures and be more friendly to foreigners when they visit your home country."
]

for i in range(10):
    wc = len(c4_t[i].split())
    samples.append({
        "sample_id": f"syn_p3_v5_g5_{start_id:04d}", "video_id": "synthetic", "part": 3, "question": c4_q,
        "transcript_cleaned": c4_t[i], "word_count": wc, "response_type": "extended" if wc > 80 else "direct_answer",
        "vocabulary": 5, "grammar": 5, "is_valid": True, "dataset_source": "synthetic",
        "idiom_present": False, "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": f"Part: 3\nQuestion: {c4_q}\n\nTranscript: {c4_t[i]}\n\nWord Count: {wc} words\nResponse Type: {'extended' if wc > 80 else 'direct_answer'}",
        "vocab_reason": "[LR5] Uses a limited range of basic vocabulary ('good', 'bad', 'happy', 'fun', 'nice', 'big'). It is adequate to communicate basic ideas but lacks any less common vocabulary or precision.",
        "grammar_reason": "[GRA5] Attempts complex structures but these are plagued by frequent errors ('If I going', 'It making you', 'you must finding'). Basic sentences are sometimes accurate, but grammatical control is weak.",
        "micro_flaws": ["verb form errors: 'they needing', 'it making'", "double subjects: 'people they'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "controlled", "flexibility": "limited"},
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Adequate vocabulary for basic communication but very limited in range.\n\n>Band 4: Better control of basic words than a 4, does not struggle to find words.\n\nNot Band 6: Lacks the less common vocabulary required for a 6.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Frequent errors in both simple and complex structures, particularly with verb forms.\n\n>Band 4: Attempts more complex sentences than a 4.\n\nNot Band 6: Error rate is too high and basic structures are not consistently accurate.\n\n**Micro flaws identified:**\n- frequent gerund/infinitive confusion and verb form errors"
    })
    start_id += 1

# V6 / G6
c5_q = "What are the advantages of playing team sports?"
c5_t = [
    "Playing team sports is very beneficial because it teaching children how to cooperate with others. When they playing football, they must pass the ball and communicate clearly with their teammates. This skill is very crucial for their future careers. However, sometimes the competitive environment it causing arguments between the young players, which can negatively impacting their long-term friendships.",
    "A major advantage is the significant improvement in physical health. Team sports usually requires a lot of running and intense cardiovascular exercise. By participating regularly, individuals they maintaining a healthy weight and building strong muscles. But the risk of serious physical injury is always present. A bad tackle on the field it can resulting in a broken leg or severe knee damage.",
    "I believe team sports helps people to develop strong leadership skills. The captain of the team must motivating the other players and making quick tactical decisions during the stressful match. This practical experience it preparing them for difficult management roles in the real corporate world. Unfortunately, not everyone get the chance to be the leader, so some quiet players might feeling ignored.",
    "Participating in a local sports club creates a strong sense of community belonging. People from different social backgrounds they coming together every weekend to support their local team. This shared passion it breaking down cultural barriers and fostering deep mutual respect. Yet, the extreme fanaticism of some aggressive supporters it can leading to terrible violence and dangerous hooliganism after the important games.",
    "Team sports provides an excellent way to relieve severe mental stress. After a long, exhausting week at the busy office, running around the pitch it helps individuals to completely clear their minds. The physical exertion releases positive endorphins, which significantly improving their overall mood. However, if the team loses a crucial match, the intense disappointment it might actually increasing their anxiety levels.",
    "One important benefit is learning how to deal with failure gracefully. In team sports, you cannot winning every single game. When the team suffers a heavy defeat, the players they must learning to accept the loss and try harder next time. This building mental resilience. But sometimes, coaches they putting too much pressure on young athletes to win, which destroying the fun.",
    "Team sports encourages a disciplined and highly structured lifestyle. The players they must attending rigorous training sessions every week, regardless of the bad weather. This strict routine it teaching them punctuality and strong dedication to a difficult long-term goal. Conversely, this massive time commitment it can interfering with their important academic studies or personal family responsibilities, causing significant friction at home.",
    "Playing in a team environment helps individuals to overcome crippling social shyness. When you are forced to interact with your teammates to win the game, you naturally becoming more extroverted and confident. It is a very safe space to practice essential social skills. However, if a player performing very badly, the harsh criticism from their teammates it can completely crushing their fragile self-esteem.",
    "I think team sports is essential for promoting gender equality in modern society. When schools providing equal funding for both male and female sports teams, it empowering young girls to be physically strong and highly competitive. But sadly, the professional female athletes they still receiving significantly less financial sponsorship and media coverage compared to their famous male counterparts in the industry.",
    "Finally, playing team sports is simply a very enjoyable and entertaining recreational activity. The thrilling excitement of scoring a late winning goal it providing an unparalleled adrenaline rush. It brings immense joy to both the exhausted players and the cheering spectators. Despite the occasional minor injuries or bitter arguments, the overall positive emotional experience far outweighs any temporary negative drawbacks."
]

for i in range(10):
    wc = len(c5_t[i].split())
    samples.append({
        "sample_id": f"syn_p3_v6_g6_{start_id:04d}", "video_id": "synthetic", "part": 3, "question": c5_q,
        "transcript_cleaned": c5_t[i], "word_count": wc, "response_type": "extended" if wc > 80 else "direct_answer",
        "vocabulary": 6, "grammar": 6, "is_valid": True, "dataset_source": "synthetic",
        "idiom_present": False, "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": f"Part: 3\nQuestion: {c5_q}\n\nTranscript: {c5_t[i]}\n\nWord Count: {wc} words\nResponse Type: {'extended' if wc > 80 else 'direct_answer'}",
        "vocab_reason": "[LR6] Uses an adequate range of vocabulary with some less common items ('cardiovascular exercise', 'mental resilience', 'recreational activity') effectively. Meaning is clear, though it lacks the sophisticated precision of Band 7.",
        "grammar_reason": "[GRA6] Uses a mix of simple and complex structures. There are noticeable errors in verb forms ('it causing', 'individuals they maintaining', 'must motivating') and subject-verb agreement, but these errors rarely impede communication.",
        "micro_flaws": ["verb form errors after modal: 'must motivating'", "double subjects: 'individuals they'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Adequate vocabulary with some successful less common items.\n\n>Band 5: Wider range and more precision than a 5.\n\nNot Band 7: Lacks the consistent stylistic awareness of a 7.\n\n**Idiom present:** No\n**Risk level:** Low\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Mix of simple and complex structures, but with frequent, noticeable errors that do not impede meaning.\n\n>Band 5: Better range of complex structures than a 5.\n\nNot Band 7: Error rate is too high for a 7.\n\n**Micro flaws identified:**\n- frequent errors in verb forms and double subjects"
    })
    start_id += 1

with open(filename, 'w', encoding='utf-8') as f:
    for s in samples:
        f.write(json.dumps(s) + '\n')
print(f"Batch {batch_num} written with {len(samples)} samples. Fully unique manual text. Expanded to hit 60 words natively.")
