import json

batch_num = 62
filename = "ielts-data/phase3/v76_review_output/synthetic_batches/batch_p1_03.jsonl"
start_id = 101
samples = []

# Batch 62: V7/G8(10) V8/G7(10) V8/G8(10) V8/G9(10) V9/G8(10) | IDs: 0101–0150

# V7 / G8 (Friends and Relationships)
c1_t = [
    ("How do you usually spend time with your friends?", "We typically prefer to meet at a cozy, independent cafe downtown where we can discuss our stressful academic week. If the weather is particularly nice, we occasionally organize a small barbecue in the local botanical gardens. Provided that everyone is free, we might also catch an independent film at the local arts cinema."),
    ("What qualities do you value most in a good friend?", "I believe absolute loyalty and genuine honesty are the most crucial characteristics of any profound friendship. A true friend should be someone you can completely rely on, especially when you are facing incredibly difficult personal challenges. Furthermore, possessing a similar sense of humor makes the relationship significantly more enjoyable and resilient."),
    ("Is it easy for you to make new friends?", "Although I consider myself to be quite friendly, I occasionally find it difficult to initiate conversations with complete strangers. Were I to join a structured social club, such as a local hiking group, I would undoubtedly find the process of meeting new people significantly less intimidating and much more organic."),
    ("Do you prefer having a few close friends or a large group of acquaintances?", "I definitely prefer maintaining a very small circle of incredibly close, intimate friends. While having a massive network of casual acquaintances might seem impressive on social media, those superficial connections rarely provide genuine emotional support during a severe personal crisis. Deep, meaningful relationships require a substantial investment of time and focused energy."),
    ("Has the internet changed how you communicate with your friends?", "The internet has unquestionably revolutionized how I maintain my long-distance friendships. By utilizing sophisticated video calling applications, I can effortlessly chat with my former university classmates who now live on completely different continents. Had this technology not been available, our close bond would have inevitably faded away due to the immense geographical distance."),
    ("What do you usually talk about when you meet your friends?", "Our conversations typically revolve around our current professional aspirations and the complex challenges we face in our respective careers. Since we are all attempting to navigate the highly competitive job market, sharing practical advice and providing mutual encouragement is extremely beneficial. We also passionately debate recent political developments and cultural trends."),
    ("Do you think it is possible to remain friends with someone from your childhood?", "It is entirely possible, though it requires a significant amount of mutual effort and continuous emotional adaptation. As people grow older, their fundamental values and daily priorities naturally evolve. Unless both individuals actively choose to embrace and respect those inevitable personal changes, the childhood friendship will eventually become completely obsolete."),
    ("How do you usually resolve disagreements with your friends?", "Whenever a serious disagreement arises, I strongly prefer to address the underlying issue immediately through calm, direct communication. Ignoring the problem invariably allows minor resentments to fester and eventually destroy the relationship. Provided that both parties remain respectful and willing to compromise, an honest conversation can actually strengthen the overall friendship."),
    ("Have you ever traveled on holiday with your friends?", "Yes, last summer a group of us rented a small, traditional cottage near the southern coast for two weeks. Because we meticulously planned the complex itinerary together, the entire trip was remarkably smooth and incredibly enjoyable. It was a fantastic opportunity to create lasting memories away from our demanding urban responsibilities."),
    ("Why do some friendships naturally fade away over time?", "Many friendships naturally fade simply due to the unavoidable logistical constraints of adult life. When an individual gets married or accepts a demanding corporate promotion, their available free time is drastically reduced. Consequently, they inadvertently neglect their casual social connections, causing those once-vibrant relationships to slowly dissolve without any malicious intent.")
]
for q, t in c1_t:
    wc = len(t.split())
    samples.append({
        "sample_id": f"syn_p1_v7_g8_{start_id:04d}", "video_id": "synthetic", "part": 1, "question": q,
        "transcript_cleaned": t, "word_count": wc, "response_type": "direct_answer" if wc <= 50 else "extended",
        "vocabulary": 7, "grammar": 8, "is_valid": True, "dataset_source": "synthetic", "idiom_present": False, "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": f"Part: 1\nQuestion: {q}\n\nTranscript: {t}\n\nWord Count: {wc} words\nResponse Type: {'direct_answer' if wc <= 50 else 'extended'}",
        "vocab_reason": "[LR7] Good range of less common vocabulary ('profound friendship', 'logistical constraints', 'superficial connections'). Paraphrasing is effective.",
        "grammar_reason": "[GRA8] Wide range of structures used flexibly and accurately ('Were I to join', 'Provided that everyone is free'). The majority of sentences are completely error-free.",
        "micro_flaws": ["none significant"],
        "grammar_profile": {"complexity": "very_high", "accuracy": "high", "flexibility": "very_high"},
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Good range of less common vocabulary used with flexibility and precision.\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Wide range of structures used flexibly and accurately. The majority of sentences are error-free."
    })
    start_id += 1

# V8 / G7 (Food and Cooking)
c2_t = [
    ("Do you enjoy cooking your own meals at home?", "I find the meticulous process of preparing my own culinary dishes to be incredibly therapeutic after a chaotic workday. Sourcing fresh, vibrant ingredients from the local farmers' market allows me to exert absolute control over my nutritional intake. Furthermore, successfully executing a highly complex, traditional recipe provides a profound sense of personal accomplishment."),
    ("What is the most difficult dish you know how to cook?", "The most formidable culinary challenge I regularly undertake is a slow-roasted, authentically spiced Moroccan lamb. The intricate preparation demands an incredibly precise balance of highly aromatic spices and several hours of continuous, gentle simmering. If the delicate temperature is mismanaged even slightly, the incredibly tender meat will immediately become completely unpalatable."),
    ("Have your eating habits changed since you were a child?", "My dietary preferences have unquestionably undergone a radical transformation since my early childhood. Previously, I possessed an insatiable appetite for heavily processed, sugary confectioneries. However, as I became increasingly cognizant of the severe long-term health ramifications, I completely eliminated artificial sweeteners, gravitating instead toward a predominantly wholesome, plant-based nutritional regimen."),
    ("Do you prefer eating at home or dining out at a restaurant?", "While dining at an exclusive, sophisticated restaurant offers an undeniably luxurious gastronomic experience, I genuinely prefer eating in the comfortable sanctuary of my own home. The exorbitant prices charged by premium establishments often feel completely unjustifiable for a Tuesday evening. Moreover, my own meticulously customized recipes usually align perfectly with my specific dietary requirements."),
    ("What traditional food is your hometown most famous for?", "My picturesque coastal hometown is internationally renowned for its incredibly rich, deeply flavorful seafood chowder. The authentic recipe utilizes a remarkably diverse array of freshly caught shellfish, simmered slowly in a decadent, incredibly creamy broth. Visitors invariably travel immense distances simply to sample this highly celebrated, iconic regional delicacy at our harbor restaurants."),
    ("Do you think it is important for children to learn how to cook?", "It is absolutely imperative that children acquire fundamental culinary skills during their formative adolescent years. Equipping them with the practical ability to prepare nutritious, wholesome meals essentially guarantees their long-term physical independence. Unless we actively teach them to navigate a kitchen safely, they will inevitably become entirely reliant on highly processed, incredibly detrimental fast food."),
    ("Are there any foods that you absolutely refuse to eat?", "I harbor an intense, visceral aversion to any dishes containing raw or severely undercooked meat, such as traditional beef tartare. Beyond the obvious, deeply concerning hygienic risks associated with potential bacterial contamination, the distinctly gelatinous, slimy texture is completely repulsive to my personal palate. I strictly insist that all my protein is cooked thoroughly."),
    ("How often do you invite friends over for dinner?", "I enthusiastically host intimate, meticulously planned dinner parties for my closest associates approximately once a month. I view these delightful gastronomic gatherings as the quintessential opportunity to showcase my expanding culinary repertoire while fostering profound interpersonal connections. The delightfully convivial atmosphere invariably makes the extensive preparation incredibly worthwhile and deeply rewarding."),
    ("What is your usual routine for grocery shopping?", "My routine involves a highly systematic, weekly expedition to the sprawling organic supermarket on Saturday mornings. I meticulously draft a comprehensive inventory beforehand to prevent the impulsive acquisition of unnecessary, expensive luxury items. This incredibly disciplined approach completely eliminates mid-week logistical panic and drastically minimizes wasteful household food spoilage over the month."),
    ("Do you think international fast-food chains are ruining traditional cuisine?", "The aggressive, relentless proliferation of ubiquitous international fast-food franchises is undeniably jeopardizing the survival of our authentic culinary heritage. Because these colossal corporations offer incredibly cheap, highly addictive meals, local artisan vendors struggle desperately to remain financially viable. This tragic homogenization of our global food landscape represents an incalculable, irreversible cultural impoverishment." )
]
for q, t in c2_t:
    wc = len(t.split())
    # Add a slight grammar slip for G7: 'vendors struggles', 'children acquires'
    t = t.replace("vendors struggle", "vendors struggles")
    t = t.replace("children acquire", "children acquires")
    samples.append({
        "sample_id": f"syn_p1_v8_g7_{start_id:04d}", "video_id": "synthetic", "part": 1, "question": q,
        "transcript_cleaned": t, "word_count": wc, "response_type": "direct_answer" if wc <= 50 else "extended",
        "vocabulary": 8, "grammar": 7, "is_valid": True, "dataset_source": "synthetic", "idiom_present": False, "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": f"Part: 1\nQuestion: {q}\n\nTranscript: {t}\n\nWord Count: {wc} words\nResponse Type: {'direct_answer' if wc <= 50 else 'extended'}",
        "vocab_reason": "[LR8] Wide range of sophisticated vocabulary ('meticulous process', 'insatiable appetite', 'visceral aversion'). Highly precise and idiomatic.",
        "grammar_reason": "[GRA7] Frequently produces error-free sentences. Minor slips in agreement ('vendors struggles', 'children acquires') cap the score at 7.",
        "micro_flaws": ["agreement slip: 'vendors struggles'", "agreement slip: 'children acquires'"],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Wide vocabulary range used readily and flexibly to convey precise meaning.\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Frequently produces error-free sentences and uses a range of complex structures, but occasional slips cap the score."
    })
    start_id += 1

# V8 / G8 (Sports and Fitness)
c3_t = [
    ("Do you participate in any competitive sports?", "I am deeply committed to participating in highly competitive amateur rowing during the summer months. The intense, grueling cardiovascular demands of navigating the heavy boat across the river continuously push my absolute physical limits. Furthermore, the meticulous synchronization required among the eight crew members fosters an incredibly profound sense of collaborative camaraderie."),
    ("How important is daily exercise for your overall health?", "Maintaining a rigorous, daily exercise regimen is absolutely paramount for preserving my optimal cognitive and physical well-being. Whenever I inadvertently neglect my morning cardiovascular workout, I subsequently experience a highly noticeable, detrimental decline in my overall concentration at the office. This proactive physical discipline undeniably functions as a highly effective, natural antidote to severe professional stress."),
    ("What are the primary benefits of joining a local sports club?", "Joining a well-established local sports club provides incredibly valuable opportunities for substantial community integration. Beyond the obvious, highly tangible physiological benefits of regular, structured athletic training, these vibrant organizations naturally facilitate the organic development of profound, lasting friendships. They essentially serve as crucial social anchors within an increasingly fragmented, isolated urban environment."),
    ("Have you ever watched a professional sporting event live in a stadium?", "I vividly recall attending a tremendously exhilarating professional tennis championship tournament several years ago. The incredibly electric, palpable tension radiating from the massive, passionate crowd was an absolutely unforgettable sensory experience. Witnessing the astonishing, almost superhuman agility of the elite athletes firsthand profoundly deepened my personal appreciation for their incredibly rigorous professional dedication."),
    ("Why do some people find going to the gym incredibly boring?", "Many individuals find the conventional gymnasium environment incredibly monotonous because the highly repetitive nature of lifting static weights entirely lacks any engaging narrative or intellectual stimulation. If a person inherently despises the sterile, artificial atmosphere of a commercial fitness center, they would likely derive significantly more enjoyment from dynamic, unpredictable outdoor activities like mountain biking."),
    ("Do you prefer team sports or individual athletic pursuits?", "I consistently gravitate toward individual athletic pursuits, specifically long-distance marathon running, because I deeply value absolute personal accountability. In a solitary sport, your ultimate competitive success or failure is dictated entirely by your own meticulous preparation and sheer psychological resilience. I find this incredibly direct correlation between dedicated effort and ultimate reward to be profoundly motivating."),
    ("How has the popularization of fitness trackers influenced people's workout routines?", "The sudden, ubiquitous popularization of sophisticated digital fitness trackers has fundamentally revolutionized how ordinary individuals meticulously quantify their daily physical exertion. By providing highly precise, real-time physiological metrics regarding heart rate and caloric expenditure, these innovative devices incredibly effectively gamify the entire exercise experience. This technological integration undeniably encourages far greater consistency in personal fitness regimes."),
    ("Is it difficult to maintain a healthy lifestyle in a busy modern city?", "Navigating the incredibly demanding schedule of a modern urban professional undeniably makes maintaining a healthy, balanced lifestyle exceedingly difficult. Because the relentless corporate culture frequently necessitates exhausting, extended working hours, finding the requisite energy to subsequently prepare a nutritious, wholesome meal is often impossible. Consequently, city dwellers frequently succumb to the incredibly convenient, yet highly detrimental, fast-food alternatives."),
    ("Do you think professional athletes are appropriate role models for young children?", "Elite professional athletes can undeniably serve as remarkably inspiring role models for impressionable young children, provided they consistently demonstrate impeccable sportsmanship. When a globally renowned champion visibly exhibits profound humility in defeat and unwavering dedication to their strenuous craft, it imparts incredibly valuable ethical lessons. However, highly publicized, scandalous off-field behavior can quickly negate these positive psychological impacts."),
    ("What new sport or physical activity would you like to try in the future?", "I possess a very strong, lingering desire to systematically learn the incredibly complex, highly disciplined art of traditional rock climbing. The formidable prospect of meticulously scaling a massive, intimidating natural cliff face demands an extraordinary combination of raw physical strength and intense, calculated psychological focus. It presents an absolutely thrilling, unparalleled personal challenge that I am eager to undertake.")
]
for q, t in c3_t:
    wc = len(t.split())
    samples.append({
        "sample_id": f"syn_p1_v8_g8_{start_id:04d}", "video_id": "synthetic", "part": 1, "question": q,
        "transcript_cleaned": t, "word_count": wc, "response_type": "direct_answer" if wc <= 50 else "extended",
        "vocabulary": 8, "grammar": 8, "is_valid": True, "dataset_source": "synthetic", "idiom_present": False, "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": f"Part: 1\nQuestion: {q}\n\nTranscript: {t}\n\nWord Count: {wc} words\nResponse Type: {'direct_answer' if wc <= 50 else 'extended'}",
        "vocab_reason": "[LR8] Wide range of sophisticated vocabulary used flexibly and precisely ('grueling cardiovascular demands', 'collaborative camaraderie', 'physiological metrics').",
        "grammar_reason": "[GRA8] Wide range of structures used flexibly and accurately ('Whenever I inadvertently neglect', 'If a person inherently despises'). The majority of sentences are error-free.",
        "micro_flaws": ["none significant"],
        "grammar_profile": {"complexity": "very_high", "accuracy": "high", "flexibility": "very_high"},
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Wide vocabulary range used readily and flexibly to convey precise meaning.\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Wide range of structures used flexibly and accurately. The majority of sentences are error-free."
    })
    start_id += 1

# V8 / G9 (Technology and Internet)
c4_t = [
    ("How often do you use the internet for your daily work?", "I rely on the internet virtually constantly throughout the entirety of my professional workday. Given that my role involves coordinating complex logistics with an entirely remote, international team, continuous access to secure cloud-based servers and high-definition video conferencing tools is absolutely non-negotiable. Were my internet connection to fail unexpectedly, my overall productivity would instantly plummet to zero."),
    ("Has the widespread use of smartphones improved our quality of life?", "While smartphones have undeniably provided unprecedented convenience regarding instant global communication, I seriously question whether they have holistically improved our actual quality of life. The relentless barrage of digital notifications creates a pervasive, underlying anxiety that completely shatters our capacity for deep, uninterrupted concentration. We are increasingly becoming tethered to these incredibly demanding devices, sacrificing genuine human interaction in the process."),
    ("Do you prefer reading news online or buying a printed newspaper?", "I unequivocally prefer consuming my daily news via sophisticated, highly curated online platforms. The remarkable ability to instantly cross-reference multiple international sources allows me to formulate a significantly more nuanced, objective understanding of complex geopolitical events. Furthermore, the sheer ecological waste associated with printing millions of disposable physical newspapers daily seems completely unjustifiable in the modern era."),
    ("How do you usually protect your personal privacy on the internet?", "Protecting my digital privacy is a paramount concern, prompting me to employ highly robust, encrypted password managers for all my sensitive online accounts. Additionally, I meticulously review the opaque privacy policies of any new application to absolutely ensure they are not covertly monetizing my personal data. One must remain incredibly vigilant, as corporate data harvesting has become an alarmingly pervasive industry standard."),
    ("What are the main disadvantages of spending too much time on social media?", "The primary disadvantage of excessive social media consumption is the insidious, deeply detrimental impact it has on an individual's psychological well-being. Because users are constantly bombarded with highly manipulated, entirely unrealistic depictions of perfection, it inevitably fosters profound feelings of personal inadequacy and severe social isolation. Should one fail to strictly moderate their usage, this toxic digital environment can easily trigger severe clinical depression."),
    ("Do you think artificial intelligence will eventually replace human teachers?", "Although highly advanced artificial intelligence algorithms excel at efficiently delivering personalized, factual information, I remain entirely unconvinced that they will ever fully replace human educators. The profound nuances of empathetic mentorship and the ability to organically inspire a struggling, discouraged student are fundamentally human traits. A cold, algorithmic interface simply cannot replicate the crucial emotional resonance required for genuine intellectual development."),
    ("How has e-commerce changed the way small local businesses operate?", "The explosive growth of global e-commerce platforms has forced small, independent local businesses to radically overhaul their traditional operational strategies simply to survive. Unable to compete directly with the incredibly ruthless pricing models of multinational retail giants, clever local artisans must now exclusively focus on providing highly personalized, bespoke customer experiences. This strategic pivot toward exceptional, niche service is their only viable defense mechanism."),
    ("What is the most useful software application on your mobile phone?", "The most indispensable application on my device is undoubtedly a highly sophisticated, real-time digital navigation tool. Because I frequently travel to entirely unfamiliar, densely populated metropolitan areas for my corporate work, this incredibly precise software meticulously calculates the most efficient transit routes, intelligently avoiding catastrophic traffic congestion. It has consistently saved me from missing crucial, career-defining international meetings."),
    ("Do you think children should be allowed to use tablet computers at a young age?", "I firmly believe that permitting toddlers to utilize tablet computers requires incredibly strict parental supervision and extreme moderation. While highly interactive, educational software can occasionally stimulate early cognitive development, excessive, unmonitored screen time threatens to severely impair their fundamental social skills and natural attention spans. Parents must prioritize organic, tactile play over convenient digital pacification to ensure healthy neurological growth."),
    ("How will virtual reality technology change the future of the entertainment industry?", "Virtual reality technology possesses the profound potential to completely revolutionize the entertainment industry by offering entirely immersive, unprecedented sensory experiences. Instead of passively watching a two-dimensional cinematic projection, the viewer will be physically integrated directly into the vibrant, dynamic narrative environment. Once the currently prohibitive hardware costs inevitably decrease, this astonishing technology will undoubtedly become the dominant paradigm for global media consumption.")
]
for q, t in c4_t:
    wc = len(t.split())
    samples.append({
        "sample_id": f"syn_p1_v8_g9_{start_id:04d}", "video_id": "synthetic", "part": 1, "question": q,
        "transcript_cleaned": t, "word_count": wc, "response_type": "direct_answer" if wc <= 50 else "extended",
        "vocabulary": 8, "grammar": 9, "is_valid": True, "dataset_source": "synthetic", "idiom_present": False, "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": f"Part: 1\nQuestion: {q}\n\nTranscript: {t}\n\nWord Count: {wc} words\nResponse Type: {'direct_answer' if wc <= 50 else 'extended'}",
        "vocab_reason": "[LR8] Wide range of sophisticated vocabulary used flexibly and precisely.",
        "grammar_reason": "[GRA9] Flawless grammar with full flexibility. Uses advanced structures naturally and accurately ('Were my internet connection to fail', 'Should one fail to strictly moderate').",
        "micro_flaws": ["none in grammar", "none in vocabulary"],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Wide vocabulary range used readily and flexibly to convey precise meaning.\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Full mastery of complex structures. Flawless accuracy and natural flexibility."
    })
    start_id += 1

# V9 / G8 (Culture and Traditions)
c5_t = [
    ("How important is it to preserve your country's traditional languages?", "Preserving indigenous linguistic dialects is of paramount importance because a language encapsulates the very cognitive framework and profound mythological worldview of its speakers. When a distinct dialect is tragically allowed to slip into total obsolescence, humanity suffers an irrecoverable loss of unique philosophical perspectives and localized ecological wisdom. Therefore, robust governmental initiatives supporting bilingual education are absolutely crucial for maintaining this invaluable cultural tapestry."),
    ("In what ways do traditional festivals strengthen local community bonds?", "Traditional cultural festivals serve as remarkably potent mechanisms for reinforcing the intrinsic social cohesion of a fragmented local community. By collectively participating in highly symbolic, ancestral rituals, disparate individuals are momentarily united by a profound, shared historical narrative. These vibrant, joyous public celebrations effectively dissolve modern socioeconomic barriers, fostering a deeply reassuring atmosphere of mutual belonging and enduring civic solidarity."),
    ("How has globalization affected the unique cultural identity of your hometown?", "The relentless march of globalization has undeniably diluted the once-distinctive, idiosyncratic cultural identity of my quiet coastal hometown. Ubiquitous multinational franchises have aggressively supplanted the charming, independent artisan boutiques, replacing our authentic architectural heritage with sterile, homogenous commercial facades. While this economic integration brings undeniable material convenience, it tragically erodes the quintessential, irreplaceable charm that initially defined our vibrant local community."),
    ("Do you think younger generations are losing respect for ancient cultural traditions?", "I wouldn't necessarily claim they are losing respect; rather, the younger generation is pragmatically recontextualizing these ancient cultural traditions to align with their demanding modern lifestyles. While they may entirely discard the more rigid, esoteric historical rituals, they frequently retain the core philosophical values, such as familial devotion. It is a natural, albeit somewhat controversial, evolution of cultural expression in a rapidly shifting world."),
    ("What role does traditional music play in preserving a nation's historical heritage?", "Traditional folk music functions as an incredibly resilient, auditory archive, preserving a nation's complex historical heritage far more viscerally than dry academic texts. The hauntingly beautiful melodies and deeply poetic lyrics often chronicle the profound struggles, heroic triumphs, and everyday realities of our resilient ancestors. Whenever these ancient compositions are passionately performed, they instantly evoke a powerful, almost genetic sense of profound national identity."),
    ("How do traditional culinary practices reflect the geography of a specific region?", "Authentic culinary practices are intrinsically inextricably linked to the specific, localized geography and severe climatic constraints of their native region. For instance, the intensely spicy, heavily fermented dishes of my southern province originally evolved as a brilliant, necessary preservation technique before the advent of modern refrigeration. Consequently, every traditional recipe serves as a fascinating, edible testament to human agricultural ingenuity in overcoming harsh environmental limitations."),
    ("Why is it important to protect historical monuments from modern urban development?", "Safeguarding magnificent historical monuments from the aggressive encroachment of modern urban development is absolutely essential for retaining a city's tangible connection to its profound architectural legacy. These awe-inspiring, ancient edifices stand as resolute, physical reminders of the brilliant craftsmanship and complex societal structures of previous, vanished civilizations. Obliterating them to construct generic, soulless office blocks represents an unforgivable act of cultural vandalism that cannot be reversed."),
    ("How does the traditional clothing of your country symbolize its cultural history?", "The intricate, heavily symbolic traditional garments of my country function as a highly legible, visual encyclopedia of our complex cultural history. The extraordinarily precise embroidery patterns and specific, vibrant color palettes historically communicated an individual's exact social hierarchy and regional provenance. Although rarely worn during the chaotic modern workday, donning these magnificent silk robes during crucial ceremonies remains a profound expression of deep ethnic pride."),
    ("Do you think cultural assimilation is an inevitable consequence of increased global migration?", "While increased global migration undeniably accelerates cross-cultural exchange, I do not believe complete, homogenous cultural assimilation is a strictly inevitable consequence. Many vibrant immigrant communities successfully manage to meticulously preserve their core religious traditions and unique culinary practices while simultaneously integrating into the broader civic framework of their adopted nation. This dynamic, multicultural coexistence is vastly superior to the total erasure of minority identities."),
    ("What can individuals do to ensure their unique cultural heritage is passed on to their children?", "To effectively ensure the successful transmission of a unique cultural heritage, individuals must proactively immerse their children in the visceral, lived experience of those traditions. Merely lecturing them about abstract historical facts is insufficient; parents must actively involve them in preparing complex ancestral recipes and celebrating specific regional festivals. This hands-on, deeply emotional engagement virtually guarantees that the profound cultural flame will continue burning brightly.")
]
for q, t in c5_t:
    wc = len(t.split())
    # G8 grammar
    samples.append({
        "sample_id": f"syn_p1_v9_g8_{start_id:04d}", "video_id": "synthetic", "part": 1, "question": q,
        "transcript_cleaned": t, "word_count": wc, "response_type": "direct_answer" if wc <= 50 else "extended",
        "vocabulary": 9, "grammar": 8, "is_valid": True, "dataset_source": "synthetic", "idiom_present": False, "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": f"Part: 1\nQuestion: {q}\n\nTranscript: {t}\n\nWord Count: {wc} words\nResponse Type: {'direct_answer' if wc <= 50 else 'extended'}",
        "vocab_reason": "[LR9] Exceptional, highly precise, and sophisticated vocabulary ('obsolescence', 'idiosyncratic', 'inextricably'). Idiomatic language is natural and accurate.",
        "grammar_reason": "[GRA8] Wide range of structures used flexibly and accurately. The majority of sentences are error-free.",
        "micro_flaws": ["none significant"],
        "grammar_profile": {"complexity": "very_high", "accuracy": "high", "flexibility": "very_high"},
        "output": "## Vocabulary (Lexical Resource): Band 9\n\n**Reasoning:** [LR9] Uses vocabulary with full flexibility and precision in all topics.\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Wide range of structures used flexibly and accurately. The majority of sentences are error-free."
    })
    start_id += 1

with open(filename, 'w', encoding='utf-8') as f:
    for s in samples:
        f.write(json.dumps(s) + '\n')
print(f"Batch {batch_num} written with {len(samples)} samples. Part 1 lengths optimized natively.")
