import json

batch_num = 57
filename = "ielts-data/phase3/v76_review_output/synthetic_batches/batch_p3_25.jsonl"
start_id = 1201
samples = []

# Batch 57: V9/G9(10) V4/G4(10) V5/G5(10) V6/G7(10) V7/G8(10) | IDs: 1201–1250

# V9 / G9 (History/Architecture)
c1_t = [
    ("How does the preservation of historical architecture influence contemporary urban identity?", "The meticulous preservation of historical architecture is absolutely quintessential for maintaining a cohesive and resonant urban identity. When municipalities deliberately safeguard their architectural heritage, they are essentially providing a tangible chronological narrative that connects contemporary citizens with their ancestral past. This profound sense of continuity not only instills immense civic pride but also serves as a robust defense against the creeping, soulless homogenization that unfortunately characterizes so much of modern, utilitarian city planning."),
    ("In what ways do ubiquitous modern skyscrapers impact the psychological well-being of city dwellers?", "While modern skyscrapers undeniably represent the pinnacle of structural engineering, their ubiquitous presence can be somewhat psychologically alienating for the average pedestrian. The sheer monolithic scale of these towering edifices frequently dwarfs the human experience, creating streetscapes that feel cold, intimidating, and decidedly impersonal. Were architects to prioritize human-centric design by incorporating accessible green spaces and varied textures at the ground level, they could significantly mitigate this pervasive sense of urban isolation."),
    ("Why is it imperative to strike a delicate balance between urban modernization and historical conservation?", "Striking a delicate equilibrium between rapid urban modernization and historical conservation is imperative because it dictates the cultural legacy we leave for posterity. If city planners recklessly demolish culturally significant landmarks to construct generic commercial complexes, they effectively obliterate the unique soul of the metropolis. Conversely, a city completely frozen in time risks becoming a mere open-air museum, stifling necessary economic growth. True architectural brilliance lies in seamlessly integrating cutting-edge innovation with deep historical reverence."),
    ("How do majestic ancient cathedrals continue to evoke a sense of profound awe in modern observers?", "Majestic ancient cathedrals continue to evoke a profound sense of awe primarily because their design was intentionally crafted to visually represent the infinite and the divine. The soaring vaulted ceilings and intricate stained-glass windows masterfully manipulate natural light, creating an atmosphere of ethereal transcendence that remains deeply moving regardless of one's personal religious convictions. It is a testament to the unparalleled visionary genius of those medieval architects who worked entirely without modern machinery."),
    ("What role does adaptive reuse play in sustainable urban development strategies today?", "The concept of adaptive reuse is increasingly recognized as a cornerstone of genuinely sustainable urban development strategies. Rather than defaulting to the environmentally catastrophic practice of demolishing sturdy old structures, visionary developers are brilliantly repurposing abandoned industrial warehouses into vibrant art galleries or chic residential lofts. Not only does this practice drastically reduce the immense carbon footprint associated with new construction, but it also preserves the invaluable historical character of evolving neighborhoods."),
    ("How does the architectural homogenization of global cities affect the tourism industry?", "The creeping architectural homogenization of global cities poses a rather insidious threat to the international tourism industry. When a traveler traverses the globe only to find that the commercial center of Tokyo looks virtually identical to that of New York or London, the intrinsic motivation for cultural exploration is severely diminished. Discerning tourists actively seek out idiosyncratic local flavor and unique historical aesthetics, not an endless, repetitive expanse of generic glass-and-steel commercial architecture."),
    ("Why are indigenous architectural techniques experiencing a sudden resurgence among contemporary designers?", "There is a fascinating resurgence of indigenous architectural techniques among contemporary designers, driven largely by the pressing imperative for ecological sustainability. These ancestral methods, meticulously refined over millennia, often utilize locally sourced materials and brilliant passive cooling strategies that are intrinsically adapted to the specific regional climate. By intelligently resurrecting these ancient, low-tech solutions, modern architects are proving that true sustainability often requires looking backward for inspiration rather than relying exclusively on futuristic technologies."),
    ("How does the aesthetic quality of our built environment directly shape our daily emotional state?", "It is an undeniable sociological reality that the aesthetic quality of our built environment directly shapes our daily emotional state. A neighborhood characterized by dilapidated, brutalist concrete blocks inevitably fosters an atmosphere of pervasive despair and social alienation. In stark contrast, environments that feature harmonious proportions, natural materials, and abundant natural light intuitively elevate the human spirit. Therefore, investing in beautiful civic architecture is not a frivolous luxury, but rather a profound public health necessity."),
    ("What are the primary ethical considerations when restoring severely damaged historical monuments?", "Restoring severely damaged historical monuments involves navigating an incredibly complex web of ethical considerations. The primary dilemma lies in deciding whether to meticulously recreate the structure exactly as it was, potentially crossing the line into historical forgery, or to clearly demarcate the modern interventions from the original ancient fabric. Most reputable preservationists advocate for absolute transparency, ensuring that future generations can accurately distinguish between authentic historical remnants and necessary contemporary structural stabilization efforts."),
    ("How do monumental public squares function as the quintessential stage for civic democracy?", "Monumental public squares function as the quintessential stage for civic democracy by providing a designated physical space for collective assembly and unhindered ideological expression. Historically, these expansive civic arenas have accommodated both joyous national celebrations and passionate, transformative political protests. The very existence of such inclusive, egalitarian spaces within the dense urban fabric is an absolute prerequisite for maintaining a healthy, vibrant, and highly participatory democratic society.")
]
for q, t in c1_t:
    wc = len(t.split())
    samples.append({
        "sample_id": f"syn_p3_v9_g9_{start_id:04d}", "video_id": "synthetic", "part": 3, "question": q,
        "transcript_cleaned": t, "word_count": wc, "response_type": "extended" if wc > 80 else "direct_answer",
        "vocabulary": 9, "grammar": 9, "is_valid": True, "dataset_source": "synthetic", "idiom_present": False, "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": f"Part: 3\nQuestion: {q}\n\nTranscript: {t}\n\nWord Count: {wc} words\nResponse Type: {'extended' if wc > 80 else 'direct_answer'}",
        "vocab_reason": "[LR9] Exceptional, highly precise, and sophisticated vocabulary used with full flexibility ('quintessential', 'homogenization', 'utilitarian').",
        "grammar_reason": "[GRA9] Flawless grammar with full flexibility. Uses advanced structures naturally and accurately.",
        "micro_flaws": ["none in grammar", "none in vocabulary"],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "output": "## Vocabulary (Lexical Resource): Band 9\n\n**Reasoning:** [LR9] Uses vocabulary with full flexibility and precision in all topics.\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Full mastery of complex structures. Flawless accuracy and natural flexibility."
    })
    start_id += 1

# V4 / G4 (Food and Diet)
c2_t = [
    ("Why is eating breakfast considered very important for young school children?", "I think eat breakfast is very important thing for children. In the morning, the children they need much energy to play and study the book in school. If they not eat the food, they feel very tired and hungry. They cannot listen to the teacher. So mother she always cook the egg and bread for them. Eating good food it make them strong and happy everyday."),
    ("How does eating too much sweet food cause problems for our teeth?", "The sweet food it is very bad for the white teeth. When young people eat too much chocolate and sugar candy, the teeth become black and very painful. Then they must go to the doctor and it cost much money. I not like the sweet food because I want to keep my teeth strong. Eating the apple is much better than the bad chocolate candy."),
    ("Why do many busy people prefer buying fast food instead of cooking?", "Many people they buy the fast food because they working very long time. When they come home at night, they feel very tired and not want to cook the dinner. The fast food it is very cheap and quick. You just buy the hamburger and eat it in the car. But it is not healthy food, so people they getting very fat if they eat it everyday."),
    ("How can drinking plenty of clean water improve our daily physical health?", "Drinking water it is very good for the body. Every day we losing water when we walking and working in the hot sun. If we not drink the water, we feel very dizzy and sick. The clean water it help the stomach to digest the heavy food. I try to drink big bottle of water everyday because the doctor say it make the skin very nice."),
    ("Why is it necessary to wash vegetables carefully before cooking them?", "We must wash the green vegetables very careful before we eat them. The farmer they put the bad chemical on the plant to kill the small bugs. If we not wash it with the clean water, the chemical it goes into our stomach and we feel very sick. My mother she always wash the tomato and cabbage three times because she wanting the food to be very safe."),
    ("What are the benefits of eating fresh fruit rather than sugary snacks?", "Fresh fruit it have many good vitamin inside. If you eating the orange and banana, you will not get the sick easily in the cold winter. The sugar snack it only give you fat and bad teeth. Also, the fruit it is very delicious and sweet from nature. Therefore, I choosing to eat the fresh fruit when I feeling hungry in the afternoon time."),
    ("How does a heavy, rich dinner affect our ability to sleep well at night?", "Eating big dinner it make sleeping very difficult. If you eat much heavy meat and rice before you go to the bed, the stomach it working very hard. You will feeling very uncomfortable and you tossing in the bed all night. It is much better to eat the small, light soup in the evening so you waking up feeling very fresh in the morning."),
    ("Why do vegetarian diets seem to be gaining popularity among young adults?", "Many young people they not eating the meat anymore. They thinking that killing the poor animal is very cruel thing to do. Also, eating the vegetable and bean it is much cheaper than buying the expensive beef. They feel very healthy and light when they follow the green diet. I thinking this is a very good choice for the body and the nature environment."),
    ("How do shared family meals help build stronger relationships at home?", "Eating the dinner together it is very important for the happy family. When everyone sitting at the big table, they can talk about the long day. The father he tell the funny story and the children they laughing very loud. If everyone eating alone in the bedroom, the family they become very quiet and sad. The food it always tasting much better when you share it."),
    ("Why is it important to check the expiration date on supermarket products?", "You must looking at the date on the milk and bread before you buy them. If the food it is too old, the bacteria it growing inside very fast. When you eat the bad food, your stomach it hurting very much and you must go to the hospital. The supermarket they sometimes forgetting to throw away the old thing, so the customer they must be very careful always.")
]
for q, t in c2_t:
    wc = len(t.split())
    samples.append({
        "sample_id": f"syn_p3_v4_g4_{start_id:04d}", "video_id": "synthetic", "part": 3, "question": q,
        "transcript_cleaned": t, "word_count": wc, "response_type": "extended" if wc > 80 else "direct_answer",
        "vocabulary": 4, "grammar": 4, "is_valid": True, "dataset_source": "synthetic", "idiom_present": False, "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": f"Part: 3\nQuestion: {q}\n\nTranscript: {t}\n\nWord Count: {wc} words\nResponse Type: {'extended' if wc > 80 else 'direct_answer'}",
        "vocab_reason": "[LR4] Uses basic vocabulary exclusively ('good', 'bad', 'big', 'small', 'happy', 'things'). Cannot paraphrase effectively.",
        "grammar_reason": "[GRA4] Frequent and systematic errors in basic structures ('I think eat breakfast', 'they not eat', 'mother she always cook'). Basic sentence forms are recognizable but heavily flawed.",
        "micro_flaws": ["systematic tense errors: 'I think eat'", "double subjects: 'mother she', 'food it'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Uses basic vocabulary exclusively. Cannot paraphrase effectively.\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Frequent and systematic errors in basic structures. Only basic sentence forms are recognizable."
    })
    start_id += 1

# V5 / G5 (Sports and Competition)
c3_t = [
    ("Why do so many people enjoy watching professional sports on television?", "I think watching sports on TV is very popular because it is very exciting. When people they working hard all week, they feeling tired. So on the weekend, they sitting on the sofa and watching the football with their friends. They drinking beer and shouting very loud when their favorite team scoring a goal. It is a good way to forget the stress from the boring office job."),
    ("How does playing team sports benefit young children's social development?", "Playing the team sport it is very good for young children. When they playing the basketball together, they must learning how to share the ball. If they playing selfishly, the whole team will losing the match. The clever coach he teaching them how to communicate and help the other players. These are very important social rules that they needing when they growing up and finding a job."),
    ("Why are some professional athletes paid such massive salaries today?", "The famous athletes they making too much money because many people watching them. When the big star playing the game, the television company it selling many expensive advertisements. Also, the fans they buying the expensive team shirts with the player name on the back. Because the athlete bringing so much money to the club, the rich owner he paying them millions of dollars every single year."),
    ("How can competitive sports occasionally create unhealthy rivalries between fans?", "Sometimes the sport competition it becoming very bad and dangerous. The angry fans from different cities they fighting outside the stadium when their team losing the important game. They drinking too much alcohol and breaking the windows in the street. I thinking this is very stupid behavior because sport it should be just a fun game, not a real war between the normal people."),
    ("Why is physical education considered a necessary subject in primary schools?", "The school it must teaching the physical education because the children they sitting too much. If they only studying the math and reading books, they becoming very fat and unhealthy. In the gym class, they running and jumping, which making their bones very strong. Also, doing the exercise it giving them fresh energy so they can concentrating better when they returning to the normal classroom."),
    ("How do international sporting events like the Olympics bring countries together?", "The big Olympic games they bringing all the different countries together in one place. Even if two countries they having the bad political argument, their athletes they still shaking hands and playing the game fairly. Millions of people around the world they watching the same television program at the same time. This shared experience it creating a very nice feeling of global peace and human friendship."),
    ("Why do some individuals prefer extreme sports over traditional athletic activities?", "Some brave people they liking the extreme sport like jumping from the airplane. Because the normal sports like tennis they feeling too boring and slow for them. When they doing the dangerous thing, their heart it beating very fast and they feeling totally alive. Even though it is very risky and they can breaking their leg, the exciting feeling it making them want to do it again."),
    ("How does winning a major championship affect a local community's mood?", "When the local city team winning the big championship, everyone they feeling incredibly happy. The people they wearing the team colors and dancing in the public street all night long. Even the strangers they hugging each other and celebrating the great victory together. This positive emotion it lifting the mood of the whole city, making everyone feel very proud of where they are living."),
    ("Why is it important to have strict rules and referees in professional games?", "If the game not having the strict referee, the players they will doing bad things to win. They might hitting each other and the game it becoming totally chaotic. The referee he making sure that everyone following the exact same rules fairly. When someone cheating, the referee he giving them the red card and sending them away. This keeping the sport clean and safe for everyone watching."),
    ("How has modern technology changed the way we referee sporting events?", "The new technology it helping the referee to make the perfect decision. In the past, the human referee he sometimes making the bad mistake because the game it moving too fast. Now, the smart video camera it recording everything from many different angles. If there is a big problem, they stopping the game and looking at the slow video to find the absolute truth of the situation.")
]
for q, t in c3_t:
    wc = len(t.split())
    samples.append({
        "sample_id": f"syn_p3_v5_g5_{start_id:04d}", "video_id": "synthetic", "part": 3, "question": q,
        "transcript_cleaned": t, "word_count": wc, "response_type": "extended" if wc > 80 else "direct_answer",
        "vocabulary": 5, "grammar": 5, "is_valid": True, "dataset_source": "synthetic", "idiom_present": False, "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": f"Part: 3\nQuestion: {q}\n\nTranscript: {t}\n\nWord Count: {wc} words\nResponse Type: {'extended' if wc > 80 else 'direct_answer'}",
        "vocab_reason": "[LR5] Vocabulary is adequate but relies heavily on simple, everyday terms ('boring office job', 'famous athletes', 'bad political argument'). Lacks precision and less common vocabulary.",
        "grammar_reason": "[GRA5] Attempts complex structures but with frequent, systematic errors ('they working hard', 'it becoming totally chaotic'). Relies heavily on incorrect present participle forms without the auxiliary verb.",
        "micro_flaws": ["systematic verb form errors: 'they working', 'it becoming'", "frequent double subjects: 'people they'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "controlled", "flexibility": "limited"},
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Vocabulary is adequate but relies on basic, everyday terms.\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 5\n\n**Reasoning:** [GRA5] Attempts complex structures but shows frequent, systematic errors in basic verb forms."
    })
    start_id += 1

# V6 / G7 (Media and News)
c4_t = [
    ("How has the 24-hour news cycle affected the public's perception of world events?", "I strongly believe that the 24-hour news cycle is making people much more anxious about the world. Because the television stations constantly need to fill their broadcast time, they often exaggerate minor problems into huge global crises. If you watch the news all day, you will probably start thinking that the world is a terribly dangerous place. This constant stream of negative information is very bad for our mental health."),
    ("Why do many young people prefer getting their news from social media rather than traditional newspapers?", "Most young people today prefer getting their daily news from social media because it is incredibly fast and convenient. When you open a modern app, you can see short video summaries of the most important events instantly. Although traditional newspapers provide much deeper analysis, the younger generation simply doesn't have the patience to read long, boring articles. They want the information delivered quickly straight to their mobile phones."),
    ("What are the dangers of relying exclusively on algorithmic news feeds?", "There is a very significant danger when people rely entirely on smart computer algorithms for their news. The system only shows you opinions that you already agree with, which creates a very tight echo chamber. If someone never reads an opposing viewpoint, they become extremely narrow-minded and refuse to listen to different ideas. We must actively search for diverse news sources to maintain a properly balanced perspective."),
    ("How does sensationalist reporting undermine the credibility of professional journalism?", "When journalists use sensational headlines just to attract more readers, it severely damages the trust in professional journalism. If a newspaper prints a shocking story that later turns out to be completely false, the angry public will never believe them again. Although clickbait titles generate a lot of money in the short term, this dishonest strategy destroys the long-term reputation of the entire media industry."),
    ("Why is independent investigative journalism crucial for a functioning democracy?", "Independent investigative journalism is absolutely crucial because it holds powerful politicians accountable for their secret actions. When brave reporters discover a major corruption scandal, they force the government to answer to the angry public. Had these independent newspapers not existed, corrupt leaders would easily steal public money without anyone ever knowing. Therefore, a free press acts as a vital protective shield for any democratic society."),
    ("How has the decline of local newspapers impacted community engagement?", "The sad decline of local newspapers has definitely reduced community engagement in many small towns. In the past, people read the local paper to learn about upcoming town meetings and important local elections. Because these small newspapers are going bankrupt, many citizens are completely unaware of what the local mayor is doing. This dangerous lack of information means that fewer people care about their immediate local neighborhood."),
    ("Why do some individuals choose to completely avoid watching the daily news?", "Nowadays, many sensitive individuals are choosing to avoid the news entirely to protect their own peace of mind. They argue that seeing endless reports of terrible wars and natural disasters only makes them feel depressed and totally helpless. While it is important to be an informed citizen, stepping away from the television for a few weeks can be a very healthy decision for someone suffering from severe anxiety."),
    ("How can schools effectively teach media literacy to younger generations?", "Schools must urgently start teaching young students how to identify fake news on the internet. Teachers should provide practical lessons where students must carefully analyze an article to see if the author is telling the real truth. If children learn to question where the information comes from, they won't be easily tricked by dishonest websites. This critical thinking skill is perhaps the most important lesson for the modern digital age."),
    ("What influence do wealthy media owners have on the political narrative?", "It is undeniable that extremely wealthy media owners hold too much power over the national political narrative. Because they control the biggest television stations, they can easily decide which politicians get the most positive coverage. If a billionaire owner dislikes a specific new law, the news anchors will magically start criticizing it every single night. This concentrated power severely threatens the fairness of democratic elections."),
    ("How do graphic images in news reports affect the viewer's emotional response?", "Broadcasting graphic images of tragic events is a highly controversial practice in modern journalism. While showing the terrible reality of a war zone can generate necessary international sympathy, it can also deeply traumatize sensitive viewers sitting at home. The news editors must strike a very careful balance between telling the honest truth and showing respect for the victims' families who are watching the painful broadcast.")
]
for q, t in c4_t:
    wc = len(t.split())
    # minor grammar slips removed, this is G7 so it's mostly error free complex sentences. V6 means vocabulary is adequate but not sophisticated.
    samples.append({
        "sample_id": f"syn_p3_v6_g7_{start_id:04d}", "video_id": "synthetic", "part": 3, "question": q,
        "transcript_cleaned": t, "word_count": wc, "response_type": "extended" if wc > 80 else "direct_answer",
        "vocabulary": 6, "grammar": 7, "is_valid": True, "dataset_source": "synthetic", "idiom_present": False, "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": f"Part: 3\nQuestion: {q}\n\nTranscript: {t}\n\nWord Count: {wc} words\nResponse Type: {'extended' if wc > 80 else 'direct_answer'}",
        "vocab_reason": "[LR6] Uses an adequate range of vocabulary with some less common items ('echo chamber', 'sensationalist', 'investigative journalism') successfully. Meaning is clear.",
        "grammar_reason": "[GRA7] Produces frequent error-free complex sentences ('Although traditional newspapers provide...', 'If a billionaire owner dislikes...'). Shows good flexibility and high accuracy.",
        "micro_flaws": ["vocabulary lacks the precision and flair of a 7 or 8"],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses an adequate range of vocabulary with some less common items successfully.\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Produces frequent error-free complex sentences. Shows good flexibility with high accuracy."
    })
    start_id += 1

# V7 / G8 (Art and Creativity)
c5_t = [
    ("How does early exposure to the arts influence a child's cognitive development?", "I firmly believe that early exposure to the arts profoundly accelerates a child's overall cognitive development. When young students are actively encouraged to paint or play a musical instrument, they aren't just having fun; they are actively forging complex neural pathways that enhance their creative problem-solving abilities. Had I not been enrolled in piano lessons during my formative years, I severely doubt I would possess the discipline required for my current academic pursuits. This early creative stimulation is absolutely invaluable."),
    ("Why do some modern abstract artworks command such exorbitant prices at auction?", "The exorbitant prices frequently commanded by modern abstract artworks can seem completely baffling to the casual observer. However, one must recognize that in the elite echelons of the contemporary art market, an individual is rarely just purchasing the physical canvas; rather, they are investing in the historical significance and cultural prestige of the renowned artist. Should a wealthy collector acquire a seminal piece by a famous abstractionist, it immediately serves as a highly visible testament to their refined cultural sophisticated status."),
    ("In what ways has digital technology democratized the creation of visual art?", "The rapid proliferation of digital technology has unquestionably democratized the creation of visual art to an unprecedented degree. Previously, aspiring artists were severely hindered by the prohibitive costs associated with high-quality paints, canvases, and specialized studio space. Today, provided they possess a standard tablet and relatively inexpensive software, a talented teenager in a remote village can effortlessly produce and globally distribute digital masterpieces. This remarkable accessibility has completely dismantled the traditional, elitist barriers to artistic expression."),
    ("How do public art installations shape the emotional atmosphere of a bustling city?", "Strategic public art installations are remarkably effective at transforming the underlying emotional atmosphere of an otherwise sterile metropolitan environment. A vibrantly painted mural on a previously dilapidated concrete wall can instantly inject a profound sense of civic pride and vibrant energy into a struggling local neighborhood. Were city councils to allocate more substantial funding towards commissioning local sculptors and painters, the aggregate mood of the commuting public would undoubtedly experience a significant and measurable uplift."),
    ("Why is it vital to preserve traditional artisanal crafts in the modern industrial age?", "Preserving traditional artisanal crafts in our era of relentless mass production is vital for maintaining a tangible connection to our specific cultural heritage. While automated factories can rapidly churn out thousands of identical ceramic bowls in a single hour, these generic items completely lack the idiosyncratic warmth and unique imperfections of a hand-thrown piece. By actively patronizing dedicated local artisans, we ensure that centuries of specialized, inherited knowledge aren't tragically lost to the ruthless efficiency of the assembly line."),
    ("How can the rigorous study of literature foster deeper human empathy?", "Engaging deeply with classic literature is arguably one of the most effective methods for cultivating profound human empathy. When you are deeply immersed in a brilliantly crafted novel, you are essentially forced to inhabit the psychological perspective of a character whose life experiences may differ drastically from your own. Unless we regularly challenge our inherent biases by exploring these diverse literary narratives, we risk becoming intellectually isolated and dangerously unsympathetic to the complex struggles of marginalized populations."),
    ("What are the primary arguments against government censorship of controversial artistic expression?", "The primary argument against government censorship is that art must remain completely unrestricted in order to function as a mirror reflecting society's hidden flaws. If cautious politicians are permitted to unilaterally ban a controversial play or an inflammatory painting simply because it makes the comfortable elite feel uneasy, the vital mechanism of social critique is completely broken. Suppressing provocative artistic expression inevitably paves the dark road toward authoritarianism, silencing the marginalized voices that desperately need to be heard."),
    ("How does participating in community theater benefit individuals with social anxiety?", "Participating in community theater can serve as a profoundly therapeutic exercise for individuals struggling with severe social anxiety. By adopting a scripted persona, an anxious individual is granted a safe, highly structured psychological framework within which they can comfortably explore bold vocal projection and expressive physical movement. Once they experience the exhilarating validation of a supportive audience's applause, their newfound theatrical confidence frequently bleeds over into their ordinary interpersonal interactions, drastically improving their daily quality of life."),
    ("Why do we naturally gravitate towards aesthetically pleasing environments?", "Human beings possess a deeply ingrained, evolutionary predisposition to gravitate towards environments that we perceive as aesthetically pleasing. From a psychological perspective, encountering symmetrical architecture, harmonious color palettes, or majestic natural landscapes immediately triggers a soothing neurological response that significantly reduces our baseline stress levels. It is precisely because the modern world is so chaotic and demanding that we continuously seek out these beautiful sanctuaries to mentally recharge our exhausted cognitive batteries."),
    ("How has the concept of what constitutes 'true art' evolved over the last century?", "The fundamental definition of what constitutes true art has undergone a radical and highly controversial evolution over the past century. Whereas traditional critics once rigidly demanded strict realistic representation and undeniable technical mastery, the revolutionary advent of conceptual art boldly shifted the primary focus entirely onto the underlying intellectual premise. Even if a modern installation consists solely of an unmade bed or a solitary brick, it is considered legitimate art provided it successfully provokes a profound intellectual reaction from the viewer.")
]
for q, t in c5_t:
    wc = len(t.split())
    samples.append({
        "sample_id": f"syn_p3_v7_g8_{start_id:04d}", "video_id": "synthetic", "part": 3, "question": q,
        "transcript_cleaned": t, "word_count": wc, "response_type": "extended" if wc > 80 else "direct_answer",
        "vocabulary": 7, "grammar": 8, "is_valid": True, "dataset_source": "synthetic", "idiom_present": False, "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": f"Part: 3\nQuestion: {q}\n\nTranscript: {t}\n\nWord Count: {wc} words\nResponse Type: {'extended' if wc > 80 else 'direct_answer'}",
        "vocab_reason": "[LR7] Good range of less common vocabulary ('cognitive development', 'exorbitant prices', 'democratized'). Paraphrasing is effective and meaning is conveyed precisely.",
        "grammar_reason": "[GRA8] Wide range of structures used flexibly and accurately ('Had I not been enrolled', 'Were city councils to allocate', 'Unless we regularly challenge'). The majority of sentences are error-free.",
        "micro_flaws": ["none significant"],
        "grammar_profile": {"complexity": "very_high", "accuracy": "high", "flexibility": "very_high"},
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Good range of less common vocabulary used with flexibility and precision.\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Wide range of structures used flexibly and accurately. The majority of sentences are error-free."
    })
    start_id += 1

with open(filename, 'w', encoding='utf-8') as f:
    for s in samples:
        f.write(json.dumps(s) + '\n')
print(f"Batch {batch_num} completely built manually. Min >60 words native.")
