import json

batch_num = 56
filename = f"ielts-data/phase3/v76_review_output/synthetic_batches/batch_p3_24.jsonl"
start_id = 1151
samples = []

# V6 / G9 (Public Transport)
c1_t = [
    ("How would free public bus systems reduce the frequency of terrible traffic jams?", "I'd argue that having good buses and trains is incredibly important for any modern city. Not only does it help people save a lot of money, but it also reduces the terrible traffic jams we see every single day. Were the government to make all the buses completely free, I genuinely believe that far fewer people would ever want to drive their own cars to the office."),
    ("Why is a well-organized subway network crucial for improving local air quality?", "A well-organized subway system is crucial because it allows workers to commute much faster. Rarely have I ever been late for a meeting since I started taking the train instead of driving my old car. Furthermore, if more people decided to use public transport, the air quality in the city center would undoubtedly improve, creating a much healthier environment for all the local residents."),
    ("How does affordable public transport support the local economy in poorer neighborhoods?", "One of the main reasons we need good public transport is that it connects the poorer neighborhoods to the city center. It's an undeniable fact that many people simply cannot afford to buy and maintain a private vehicle. Provided that the train tickets remain reasonably cheap, these individuals will always be able to reach their jobs, ensuring that the local economy continues to grow steadily."),
    ("Why do experts consider expanding train lines the only viable solution to urban pollution?", "Many experts suggest that building more train lines is the only viable solution to urban pollution. Had city planners recognized this problem twenty years ago, we probably wouldn't be dealing with such thick smog today. Therefore, investing heavily in the public bus system isn't just a matter of convenience; it is absolutely necessary for the long-term survival of our rapidly growing cities."),
    ("In what ways do efficient tram systems make a city more attractive to foreign tourists?", "I think it's fair to say that efficient public transport makes a city much more attractive to foreign tourists. Scarcely does a visitor want to rent an expensive car and navigate confusing, crowded streets when they are on vacation. By providing clear maps and clean, regular buses, the city authorities can ensure that tourists have a fantastic time, which ultimately brings more money into the local shops."),
    ("How can building new train stations eventually increase surrounding property values?", "Despite the high cost of building new train stations, the long-term benefits are definitely worth the initial investment. If the government were to introduce a brand-new tram system, the property values in the connected areas would almost certainly increase. This would give the city more tax money in the future, meaning the whole project would eventually pay for itself without creating a massive financial burden."),
    ("Why is reliable bus service vital for the mental health of elderly citizens?", "Public transport is also very important for older people who can no longer drive safely. Should an elderly person lose their driving license, a reliable bus service ensures they don't become totally isolated in their own homes. It gives them the freedom to go to the supermarket or visit their friends whenever they want, which is vital for their mental health and overall happiness."),
    ("How does commuting by train decrease overall stress levels for busy office workers?", "There's no doubt that riding the train is significantly less stressful than driving in heavy traffic. Instead of staring angrily at the cars in front of you, you can comfortably read a book or listen to some nice music. Were more workers to experience this relaxing morning commute, I'm certain that the overall stress levels in busy corporate offices would decrease quite noticeably."),
    ("Why are dedicated bus lanes necessary for prioritizing public transit over private cars?", "Some people argue that buses are too slow, but that is only true if there are no dedicated bus lanes. If the city council had the courage to ban private cars from certain main roads, the public buses would actually be the fastest way to travel. It's entirely a matter of political will and prioritizing the needs of the many over the convenience of a few drivers."),
    ("How does promoting public transportation effectively improve overall road safety?", "Finally, a good transport network helps to reduce the number of terrible accidents on our roads. Given that professional bus drivers are highly trained, they are far less likely to cause a crash than a tired office worker driving home late at night. Consequently, promoting the use of public trains and buses is perhaps the most effective way to improve overall road safety.")
]
for q, t in c1_t:
    wc = len(t.split())
    samples.append({
        "sample_id": f"syn_p3_v6_g9_{start_id:04d}", "video_id": "synthetic", "part": 3, "question": q,
        "transcript_cleaned": t, "word_count": wc, "response_type": "extended" if wc > 80 else "direct_answer",
        "vocabulary": 6, "grammar": 9, "is_valid": True, "dataset_source": "synthetic", "idiom_present": False, "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": f"Part: 3\nQuestion: {q}\n\nTranscript: {t}\n\nWord Count: {wc} words\nResponse Type: {'extended' if wc > 80 else 'direct_answer'}",
        "vocab_reason": "[LR6] Uses an adequate range of vocabulary with some less common items ('commute', 'viable solution', 'isolated'). Meaning is clear, but lacks the precision and sophistication of higher bands.",
        "grammar_reason": "[GRA9] Flawless grammar with full flexibility. Uses advanced structures naturally and accurately ('Were the government to make', 'Rarely have I ever been'). No errors.",
        "micro_flaws": ["none in grammar", "vocabulary is functional but lacks flair"],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses an adequate range of vocabulary with some less common items successfully.\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Full mastery of complex structures. Flawless accuracy and natural flexibility."
    })
    start_id += 1

# V9 / G6 (Globalization)
c2_t = [
    ("How is multinational corporate expansion eroding the nuances of indigenous traditions?", "The relentless homogenization of global culture it invariably eroding the quintessential nuances of indigenous traditions. When ubiquitous multinational conglomerates they disseminating standardized consumer products worldwide, local artisanal craftsmanship it inevitably facing obsolescence. This profound cultural assimilation it precipitating a tragic loss of unique linguistic dialects and ancestral customs. I sincerely believing that this ongoing paradigm shift it representing an irreversible cultural impoverishment for everyone."),
    ("In what ways is the proliferation of Western media diluting local cultural tapestries?", "The ubiquitous proliferation of Western media it significantly diluting the authentic cultural tapestry of developing nations. Because impressionable youth they incessantly consuming Hollywood blockbusters and ubiquitous pop music, they subconsciously adopting foreign ideological frameworks. This subtle cultural imperialism it gradually superseding their inherited traditional values and idiosyncratic social mores. The indigenous cinematic industries they struggling desperately to remain relevant amidst this overwhelming foreign influx constantly."),
    ("How does digital dissemination facilitate the cross-pollination of diverse musical genres?", "Conversely, global interconnectedness it arguably facilitating a remarkable cross-pollination of diverse artistic expressions. The seamless digital dissemination of world music it introducing previously marginalized genres to a truly cosmopolitan audience. However, the commercial commodification of these authentic cultural artifacts it frequently resulting in superficial, sanitized representations. The indigenous artists they often feeling exploited when their profound spiritual traditions it being aggressively monetized for foreign entertainment simply."),
    ("Why is the aggressive spread of fast-food franchises marginalizing regional gastronomies?", "The pervasive standardization of the global culinary landscape it completely marginalizing exquisite regional gastronomies. As ubiquitous fast-food franchises they aggressively infiltrating every metropolitan corner, the younger generation it slowly losing its palate for complex traditional delicacies. This tragic culinary homogenization it undeniably representing a profound loss of invaluable agricultural heritage. The local food purveyors they desperately attempting to preserve these intricate, ancestral recipes against insurmountable odds today."),
    ("How does the global necessity for English proficiency accelerate indigenous linguistic extinction?", "Globalization it undeniably exacerbating the rapid linguistic extinction of innumerable indigenous dialects. When global commerce it strictly necessitating English proficiency for economic survival, parents they deliberately discouraging their children from speaking their native tongue. This utilitarian linguistic shift it severing the vital generational transmission of complex mythological narratives and localized philosophical wisdom. I firmly believing that every permanently lost native language it equating to a completely vanished intellectual universe forever."),
    ("What is the profound paradox that international tourism presents for cultural preservation?", "The meteoric rise of international tourism it presenting a profound paradox for authentic cultural preservation. While it ostensibly providing vital economic sustenance for marginalized communities, the relentless tourist influx it inevitably commodifying sacred traditional rituals. The solemn religious ceremonies they often degenerating into mere theatrical spectacles designed specifically for foreign consumption. The local inhabitants they feeling increasingly alienated and ignored within their own drastically altered ancestral domains everywhere."),
    ("How does the global workforce mobility foster vibrant, multicultural metropolitan epicenters?", "The unprecedented mobility of the global workforce it creating incredibly vibrant, multicultural metropolitan epicenters. This unprecedented demographic convergence it fostering an undeniably dynamic atmosphere of cosmopolitan tolerance and intellectual diversity. Nevertheless, the rapid formation of insular ethnic enclaves it occasionally precipitating underlying social friction and complex integration challenges. The municipal governments they constantly struggling to balance multicultural celebration with necessary civic cohesion properly."),
    ("Why is the mass production of synthetic garments destroying traditional textile arts?", "The aggressive globalization of the ubiquitous fashion industry it completely standardizing global sartorial preferences. As multinational apparel corporations they flooding the market with cheap, homogenous garments, traditional textile arts it rapidly disappearing. The intricate, symbolic woven patterns of indigenous clothing they being replaced by generic, mass-produced synthetic fabrics. The meticulous artisan weavers they finding it utterly impossible to compete against this enormous, relentless industrial manufacturing machine entirely."),
    ("How are multinational philosophies altering the egalitarian workplace dynamics of Eastern societies?", "Multinational corporate philosophies they profoundly altering the traditional egalitarian workplace dynamics of many Eastern societies. The aggressive imposition of ruthless Western hyper-competitiveness it rapidly dismantling the intrinsic harmony of collective, consensus-based organizational structures. This fundamental psychological shift it arguably generating unprecedented levels of corporate anxiety and widespread social alienation. The loyal employees they feeling totally disconnected and isolated from the newly imposed, cutthroat corporate ethos unfortunately."),
    ("Why must the international community proactively safeguard intangible cultural heritage?", "Ultimately, the sheer velocity of modern globalization it demanding a concerted, deliberate effort to safeguard intangible cultural heritage. If the international community it failing to proactively document and protect these vanishing indigenous paradigms, humanity it suffering an immeasurable intellectual loss. The unique cosmological perspectives held by remote tribes they offering invaluable insights into sustainable ecological management. We must actively preventing this rapid and devastating homogenization of the human experience together.")
]
for q, t in c2_t:
    wc = len(t.split())
    samples.append({
        "sample_id": f"syn_p3_v9_g6_{start_id:04d}", "video_id": "synthetic", "part": 3, "question": q,
        "transcript_cleaned": t, "word_count": wc, "response_type": "extended" if wc > 80 else "direct_answer",
        "vocabulary": 9, "grammar": 6, "is_valid": True, "dataset_source": "synthetic", "idiom_present": False, "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": f"Part: 3\nQuestion: {q}\n\nTranscript: {t}\n\nWord Count: {wc} words\nResponse Type: {'extended' if wc > 80 else 'direct_answer'}",
        "vocab_reason": "[LR9] Exceptional, highly precise, and sophisticated vocabulary.",
        "grammar_reason": "[GRA6] Highly noticeable and systematic errors despite the advanced vocabulary ('culture it invariably eroding').",
        "micro_flaws": ["systematic missing copula: 'culture it eroding'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "output": "## Vocabulary (Lexical Resource): Band 9\n\n**Reasoning:** [LR9] Uses vocabulary with full flexibility and precision in all topics.\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Uses a mix of simple and complex sentence forms, but makes frequent, systematic errors in basic structures."
    })
    start_id += 1

# V6 / G6 (City Living)
c3_t = [
    ("Why do ambitious graduates prefer migrating to the capital for career opportunities?", "Many young people they prefer the city because the career opportunities it is much better there. If you wanting to work in a big modern bank, you definitely must move to the busy capital. The rural villages they not having any major international companies. Therefore, ambitious graduates they always migrating to the noisy city to start their professional working life successfully and achieve their high goals."),
    ("How does the variety of entertainment options make urban living more exciting?", "The city it offering an incredible variety of entertainment options every single night. When you living in a small town, the local cinema it only showing one old movie every week. But the big city it has numerous theaters, loud concerts, and interesting art museums. If someone enjoying a busy social life, the city it is the absolute perfect place to spend their valuable weekends."),
    ("What makes public transportation more convenient than owning a private car in a city?", "Another important reason is that the public transportation it is extremely convenient in urban areas. You not needing to buy an expensive private car to travel around the busy city. The underground trains they running every five minutes from the early morning until very late. Because of this fast system, the daily commute it becoming much less stressful for workers heading to their offices every morning."),
    ("Why are large city hospitals generally more reliable during serious medical emergencies?", "The healthcare facilities in major cities they are significantly better than in the quiet countryside. If you suddenly having a serious medical emergency, the large city hospital it has all the specialized modern equipment. The rural clinics they often lacking the highly trained professional doctors for complicated diseases. This reliable medical security it making older people feel much safer when they choosing where to live permanently."),
    ("How does a multicultural urban environment introduce residents to new global perspectives?", "Cities they are incredibly diverse, meaning you can meet many interesting people from different foreign countries. This multicultural environment it introducing you to completely new global perspectives and delicious international food. When I living in the village, everyone they having the exact same traditional background. I genuinely enjoying the vibrant mix of different cultures in the busy metropolis because it makes life more interesting."),
    ("Why do prestigious technical universities primarily locate their campuses in major cities?", "The educational institutions in the city they offering a much higher standard of modern learning. The prestigious universities and specialized technical schools they attracting the smartest international professors. If a student wanting to study advanced computer science, the rural college it simply cannot provide the necessary equipment. Excellent education it is the main magnet pulling families to the urban center to help their children."),
    ("How does living in a managed apartment simplify the lifestyle of single professionals?", "Living in an apartment it is generally much easier to maintain than a large country house. Because the building manager they fixing any broken pipes or electrical problems immediately, you not worrying about difficult home repairs. Also, the modern apartments they usually having good security systems and cameras. This convenient lifestyle it is very attractive for busy single professionals who lacking time to clean."),
    ("Why do massive shopping malls offer a better retail experience than small village stores?", "Shopping in the city it is a completely different and exciting experience. The massive shopping malls they containing hundreds of famous international clothing brands under one big roof. If you needing a very specific electronic device, you easily finding it in the specialized city center stores. The small village shops they simply lacking this huge variety of consumer goods that city residents usually demanding."),
    ("What aspects of the intense urban energy appeal to people with a fast personal rhythm?", "Some people they simply loving the fast, energetic pace of the metropolitan lifestyle. The constant movement of traffic and the bright neon lights they creating a very exciting daily atmosphere. While the quiet countryside it feeling extremely boring to them, the city it constantly offering new surprises. This intense urban energy it matching their own fast personal rhythm perfectly without making them feel isolated."),
    ("How do international airports provide essential global connectivity for corporate managers?", "Finally, the city it providing much better connectivity to the rest of the entire world. The massive international airports they allowing you to travel to completely different countries very quickly. If you managing a big global business, you needing to fly to important meetings constantly. This essential global access it making the city the only logical place to live for highly successful international executives.")
]
for q, t in c3_t:
    wc = len(t.split())
    samples.append({
        "sample_id": f"syn_p3_v6_g6_{start_id:04d}", "video_id": "synthetic", "part": 3, "question": q,
        "transcript_cleaned": t, "word_count": wc, "response_type": "extended" if wc > 80 else "direct_answer",
        "vocabulary": 6, "grammar": 6, "is_valid": True, "dataset_source": "synthetic", "idiom_present": False, "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": f"Part: 3\nQuestion: {q}\n\nTranscript: {t}\n\nWord Count: {wc} words\nResponse Type: {'extended' if wc > 80 else 'direct_answer'}",
        "vocab_reason": "[LR6] Uses an adequate range of vocabulary with some less common items.",
        "grammar_reason": "[GRA6] Uses a mix of simple and complex sentence forms. Noticeable errors in basic structures ('people they prefer').",
        "micro_flaws": ["double subjects: 'people they'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses an adequate range of vocabulary with some less common items successfully.\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Mix of simple and complex structures, with noticeable but non-impeding errors."
    })
    start_id += 1

# V7 / G7 (Workplace Stress)
c4_t = [
    ("How does the constant pressure to meet corporate deadlines cause emotional burnout?", "I'd suggest that chronic stress is having a severely detrimental impact on the mental health of modern professionals. The constant pressure to meet unrealistic corporate deadlines frequently result in complete physical and emotional burnout. Furthermore, because smartphones allow managers to contact employees at any hour, workers rarely experience genuine relaxation. This inescapable professional anxiety inevitably damages their personal relationships and overall well-being, leaving them feeling completely exhausted every weekend."),
    ("Why does the modern gig economy introduce a uniquely stressful level of financial insecurity?", "The modern gig economy has introduced a uniquely stressful level of financial insecurity. Freelance workers constantly worry about securing their next contract, which completely destroys their peace of mind. Without the safety net of paid sick leave or reliable health insurance, a minor illness can quickly become a major financial catastrophe. Consequently, this persistent economic precariousness leads to severe, long-term psychological strain that affects their physical health dramatically."),
    ("In what ways does a culture of presenteeism negatively impact actual productivity?", "In many highly competitive industries, taking a well-deserved vacation is unfortunately viewed as a sign of weakness. Employees feel intense pressure to perform presenteeism, sitting at their desks for ten hours despite achieving very little actual productivity. If the corporate culture actively discourage a healthy work-life balance, the staff will eventually suffer from severe exhaustion. This toxic environment is completely unsustainable in the long run for any serious business."),
    ("How does excessive workplace anxiety degrade an employee's cognitive problem-solving abilities?", "I believe that excessive workplace stress significantly degrades a person's cognitive abilities over time. When an employee is overwhelmed by anxiety, their capacity to solve complex problems or think creatively is drastically reduced. They begin making careless mistakes, which only generates more reprimands from their frustrated supervisors. Breaking this vicious cycle requires companies to actively prioritize the psychological welfare of their workforce by offering comprehensive mental health support."),
    ("Why is checking business emails before sleep detrimental to a worker's circadian rhythms?", "The relentless demand for continuous productivity has completely eroded the traditional boundaries of the workday. Modern professionals often check their business emails immediately before going to sleep, which severely disrupts their natural circadian rhythms. This chronic lack of restorative sleep leaves them highly irritable and unable to focus the following morning. Unless we establish strict digital boundaries, this exhaustion will only worsen and destroy their long-term career prospects."),
    ("What are the tangible physical consequences of sustained professional stress for office staff?", "Physical health problems are a very common, tangible consequence of sustained professional stress. Stressed office workers frequently develops chronic back pain and terrible migraines from sitting rigidly at their computers all day. Moreover, they tend to consume unhealthy fast food because they simply lack the energy to prepare nutritious meals at home. Ultimately, the stressful workplace is silently contributing to a massive public health crisis in major metropolitan areas."),
    ("Why do toxic corporate environments frequently lose their most talented management leaders?", "Stress often forces intelligent employees to abandon highly demanding but rewarding career paths. When the psychological cost of a management position becomes too high, many talented individuals deliberately choose to accept a demotion. They realize that earning a lucrative salary is completely meaningless if they are too depressed to enjoy their wealth. Therefore, toxic workplaces are actively losing their most capable leaders simply because they refuse to reduce the pressure."),
    ("How is the fear of technological redundancy creating anxiety among older administrative workers?", "The fear of sudden technological redundancy is creating a pervasive, underlying anxiety among older workers. As artificial intelligence continues to automate complex administrative tasks, many employees worry that their specialized skills are becoming entirely obsolete. This terrifying prospect of late-career unemployment forces them to constantly retrain under immense pressure. It is a deeply unsettling reality that the previous generation simply never had to face during their stable, lifelong careers."),
    ("Why is professional autonomy considered a remarkably effective strategy for reducing corporate stress?", "I strongly feel that a lack of professional autonomy is a primary trigger for severe workplace stress. When employees are constantly micromanaged by suspicious supervisors, they feel utterly disempowered and deeply unappreciated. Conversely, if workers are trusted to manage their own specific schedules, their overall job satisfaction increases dramatically. Empowering employees is a remarkably effective strategy for reducing unnecessary corporate anxiety while simultaneously boosting overall creative output and loyalty."),
    ("How does basing personal identity entirely on career achievements trigger existential crises?", "Ultimately, the societal expectation that our career defines our entire personal identity is extremely unhealthy. When a person bases their self-worth entirely on their professional achievements, a simple setback at work can trigger a profound existential crisis. We need to cultivate a broader cultural perspective that values family, hobbies, and personal happiness just as highly as corporate success, ensuring that people maintain a deeply balanced and truly fulfilling existence.")
]
for q, t in c4_t:
    wc = len(t.split())
    samples.append({
        "sample_id": f"syn_p3_v7_g7_{start_id:04d}", "video_id": "synthetic", "part": 3, "question": q,
        "transcript_cleaned": t, "word_count": wc, "response_type": "extended" if wc > 80 else "direct_answer",
        "vocabulary": 7, "grammar": 7, "is_valid": True, "dataset_source": "synthetic", "idiom_present": False, "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": f"Part: 3\nQuestion: {q}\n\nTranscript: {t}\n\nWord Count: {wc} words\nResponse Type: {'extended' if wc > 80 else 'direct_answer'}",
        "vocab_reason": "[LR7] Good range of vocabulary.",
        "grammar_reason": "[GRA7] Frequently produces error-free complex sentences. Occasional minor slips in subject-verb agreement ('deadlines... result').",
        "micro_flaws": ["agreement slip: 'culture... discourage'"],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Good range of less common vocabulary used with flexibility and precision.\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Produces frequent error-free complex sentences, but occasional minor slips occur."
    })
    start_id += 1

# V8 / G8 (AI in Education)
c5_t = [
    ("How are adaptive learning algorithms revolutionizing the conventional paradigm of classroom instruction?", "Artificial intelligence is fundamentally revolutionizing the conventional paradigm of classroom instruction. By employing sophisticated, adaptive learning algorithms, educational software can now meticulously tailor its curriculum to accommodate the idiosyncratic pace of every single student. Had educators possessed this phenomenal capability a decade ago, the pervasive issue of students falling hopelessly behind would have been significantly mitigated. Consequently, this remarkable personalization is fostering unprecedented levels of academic engagement."),
    ("Why is the continuous pedagogical support of an AI tutor indispensable for anxious students?", "A particularly striking development is the deployment of highly advanced AI tutors that provide instantaneous, customized feedback. Unlike an exhausted human teacher managing thirty diverse students, an AI system patiently elucidates complex mathematical concepts repeatedly without the slightest hint of frustration. This continuous, unjudging pedagogical support is absolutely indispensable for students grappling with severe learning anxieties. The ultimate objective isn't to render teachers obsolete, but rather to massively amplify their effectiveness."),
    ("What formidable challenges do generative language models present regarding traditional academic integrity?", "We must critically acknowledge the formidable challenges AI presents regarding academic integrity. The sudden ubiquity of sophisticated generative language models has made it remarkably easy for students to effortlessly mass-produce highly convincing essays. If universities fail to proactively implement robust, AI-resistant assessment methodologies, the intrinsic value of traditional academic qualifications will invariably plummet. Preserving the rigor of genuine intellectual endeavor in this rapidly shifting landscape is absolutely imperative."),
    ("How do AI-driven analytical tools proactively identify marginalized students at risk of failure?", "The integration of AI-driven analytical tools allows educational institutions to proactively identify marginalized students who are at extreme risk of dropping out. By meticulously analyzing massive datasets regarding attendance and erratic assignment submission patterns, the software accurately predicts impending academic failure long before it actually materializes. This crucial early intervention empowers dedicated counselors to provide highly targeted emotional and academic support, potentially salvaging a struggling student's entire educational trajectory."),
    ("In what ways is artificial intelligence dismantling geographical barriers to elite global education?", "I would emphatically argue that AI is successfully dismantling formidable geographical and socioeconomic barriers to elite education. An impoverished student residing in an entirely remote, rural village can now effortlessly access remarkably sophisticated, AI-driven language instruction that rival the quality of expensive private academies. Provided they possess a stable internet connection, the previously inaccessible gates to profound global knowledge are now thrown wide open. This represents a monumental leap toward genuine educational equity."),
    ("Why might an over-reliance on automated instruction erode vital interpersonal soft skills?", "However, a significant peril of an AI-dominated educational framework is the potential erosion of vital interpersonal soft skills. The subtle nuances of human empathy, spontaneous collaborative debate, and emotional intelligence simply cannot be effectively cultivated by interacting exclusively with a cold, algorithmic interface. Should schools mistakenly over-rely on automated digital instruction, we risk producing a generation of academically brilliant but socially incapacitated individuals. Human connection remains the irreplaceable core of genuine education."),
    ("How does automating tedious administrative tasks drastically alleviate the burden on dedicated teachers?", "AI is also drastically alleviating the crushing administrative burden that perpetually afflicts dedicated teachers. By automating tedious, repetitive tasks such as grading countless multiple-choice examinations and intricately scheduling classes, AI liberates educators to focus exclusively on highly creative lesson planning. Were teachers definitively freed from this exhausting bureaucratic nightmare, their overall job satisfaction would inevitably soar, drastically reducing the severe retention crisis currently crippling the profession."),
    ("How does real-time AI translation profoundly enrich the multicultural academic environment?", "The capacity of AI to instantly translate complex academic material is a profound blessing for the massive international student demographic. Instead of constantly struggling to comprehend an incredibly fast-paced, jargon-heavy lecture in a secondary language, an AI tool provides impeccable, real-time subtitling. This magnificent technological bridge allows international students to actively participate in rigorous intellectual debates rather than remaining passive, confused observers. It profoundly enriches the entire multicultural academic environment."),
    ("Why are AI-powered virtual reality simulations staggering in their pedagogical value for medical students?", "Furthermore, virtual reality simulations, comprehensively powered by advanced AI, are creating deeply immersive, unprecedented learning environments. Medical students can safely perform intricate, highly realistic virtual surgeries on responsive digital patients long before they ever enter a physical operating theater. The sheer pedagogical value of these highly controlled, risk-free practical simulations is absolutely staggering. This deeply experiential approach to learning definitively eclipses the severe limitations of traditional, static textbook diagrams."),
    ("How does the incorporation of AI necessitate a philosophical pivot towards teaching critical thinking?", "Ultimately, the rapid incorporation of AI necessitates a profound philosophical reevaluation of what we actually teach. Since AI can effortlessly memorize an infinite database of factual information, schools must urgently pivot towards prioritizing highly sophisticated critical thinking and complex emotional intelligence. We must rigorously train students to intelligently question the algorithmic outputs and ethically manage the technology, rather than merely competing with its prodigious computational memory.")
]
for q, t in c5_t:
    wc = len(t.split())
    samples.append({
        "sample_id": f"syn_p3_v8_g8_{start_id:04d}", "video_id": "synthetic", "part": 3, "question": q,
        "transcript_cleaned": t, "word_count": wc, "response_type": "extended" if wc > 80 else "direct_answer",
        "vocabulary": 8, "grammar": 8, "is_valid": True, "dataset_source": "synthetic", "idiom_present": False, "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": f"Part: 3\nQuestion: {q}\n\nTranscript: {t}\n\nWord Count: {wc} words\nResponse Type: {'extended' if wc > 80 else 'direct_answer'}",
        "vocab_reason": "[LR8] Wide range of sophisticated vocabulary used flexibly and precisely.",
        "grammar_reason": "[GRA8] Wide range of structures used flexibly and accurately.",
        "micro_flaws": ["none significant, minor stylistic density"],
        "grammar_profile": {"complexity": "very_high", "accuracy": "high", "flexibility": "very_high"},
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Wide vocabulary range used readily and flexibly to convey precise meaning.\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Wide range of structures used flexibly and accurately. The majority of sentences are error-free."
    })
    start_id += 1

with open(filename, 'w', encoding='utf-8') as f:
    for s in samples:
        f.write(json.dumps(s) + '\n')
print(f"Batch {batch_num} completely rebuilt without scripts.")
