import json

batch_num = 67
filename = "ielts-data/phase3/v76_review_output/synthetic_batches/batch_p1_08.jsonl"
start_id = 351
samples = []

# Batch 67: V6/G7(10) V7/G8(10) V8/G9(10) V9/G8(10) V5/G6(10) | IDs: 0351–0400

# V6 / G7 (Nature and Environment)
c1_t = [
    ("How often do you go to the park?", "I usually go to the local park about twice a week, particularly during the warm summer months. Although I have a very busy work schedule, taking a short walk among the green trees helps me relax completely. If it rains, however, I prefer to stay safely inside my dry apartment."),
    ("Do you like looking at the stars at night?", "Yes, looking at the stars is a very relaxing activity for me. Whenever I travel away from the bright city lights, the night sky looks absolutely beautiful and full of tiny white dots. It makes me realize how incredibly small our world actually is in the huge universe."),
    ("Have you ever planted a tree or some flowers?", "I actually planted several small rose bushes in my garden last spring. Because I carefully watered them every single morning, they eventually produced some very beautiful, bright red flowers. It was a surprisingly satisfying experience to watch something grow successfully from a tiny little seed."),
    ("Do you think it is important to protect wild animals?", "It is definitely very important to protect all wild animals from losing their natural homes. If we continue to destroy the large forests to build new roads, many beautiful creatures will completely disappear forever. The government really needs to create more safe areas where these animals can live peacefully."),
    ("What kind of outdoor activities do you enjoy in the winter?", "During the freezing winter months, my absolute favorite activity is going ice skating on the frozen lake. Provided that the ice is thick and safe, gliding across the smooth surface is incredibly fun. Even though I fall down quite often, I always enjoy the cold, fresh air."),
    ("Do you like spending time near the ocean?", "I genuinely love spending my holidays near the massive, blue ocean. The repetitive sound of the waves crashing against the sandy beach is probably the most relaxing noise in the entire world. Unless the weather is terribly windy, I can easily spend the whole day just looking at the water."),
    ("Are there many green spaces in your hometown?", "My hometown is actually quite famous for having many large, well-maintained green spaces. Almost every neighborhood has its own small park where local families can safely walk their dogs. Having access to these clean, natural areas makes living in the busy city much more pleasant and healthy."),
    ("Have you ever been camping in the forest?", "I went camping in a dark pine forest once when I was a young teenager. While sleeping in a small plastic tent was quite exciting initially, the cold ground made my back hurt terribly the next morning. I am glad I experienced it, but I much prefer a comfortable hotel bed now."),
    ("Do you think climate change is a serious problem?", "I believe that climate change is an extremely serious problem that affects everyone on the planet. Because the summer temperatures are getting noticeably hotter every year, our local farmers are struggling to grow enough fresh vegetables. We must urgently reduce our pollution before the weather becomes completely uncontrollable."),
    ("What do you do to help the environment?", "To help protect the environment, I always make sure to recycle my plastic bottles and paper waste carefully. Furthermore, whenever I go to the supermarket, I deliberately bring my own strong cloth bags instead of using the cheap plastic ones. These small daily actions can make a very big difference.")
]
for q, t in c1_t:
    wc = len(t.split())
    samples.append({
        "sample_id": f"syn_p1_v6_g7_{start_id:04d}", "video_id": "synthetic", "part": 1, "question": q,
        "transcript_cleaned": t, "word_count": wc, "response_type": "direct_answer" if wc <= 50 else "extended",
        "vocabulary": 6, "grammar": 7, "is_valid": True, "dataset_source": "synthetic", "idiom_present": False, "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": f"Part: 1\nQuestion: {q}\n\nTranscript: {t}\n\nWord Count: {wc} words\nResponse Type: {'direct_answer' if wc <= 50 else 'extended'}",
        "vocab_reason": "[LR6] Uses an adequate range of vocabulary with some less common items ('uncontrollable', 'well-maintained', 'satisfying experience'). Meaning is clear.",
        "grammar_reason": "[GRA7] Produces frequent error-free complex sentences ('Although I have a very busy work schedule...', 'Because I carefully watered them...'). Shows good flexibility and high accuracy.",
        "micro_flaws": ["vocabulary is slightly functional compared to grammar"],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses an adequate range of vocabulary with some less common items successfully.\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Produces frequent error-free complex sentences. Shows good flexibility with high accuracy."
    })
    start_id += 1

# V7 / G8 (History and Museums)
c2_t = [
    ("Do you enjoy learning about history?", "I find the rigorous study of ancient history to be incredibly fascinating and deeply rewarding. Understanding how complex previous civilizations navigated their unique political crises provides invaluable context for our modern societal struggles. Were we to completely ignore the vital lessons of the past, we would undoubtedly repeat those exact same tragic mistakes."),
    ("Have you ever visited a famous historical monument?", "Last autumn, I had the remarkable opportunity to explore the ancient Roman Colosseum in person. Standing within that massive, iconic stone structure, vividly imagining the chaotic, deafening roar of the historical crowds, was a profoundly humbling sensory experience. It dramatically altered my basic understanding of classical architectural engineering."),
    ("Do you think museums are still important in the digital age?", "Despite the convenient accessibility of online virtual tours, physical museums remain absolutely indispensable cultural institutions. Viewing a meticulously preserved historical artifact directly in front of you evokes a genuine, visceral emotional connection that a digital screen simply cannot replicate. They serve as crucial, irreplaceable physical guardians of our collective human heritage."),
    ("What period of history interests you the most?", "I am particularly captivated by the unprecedented intellectual explosion of the European Renaissance period. The dramatic, sudden shift from religious dogmatism toward secular humanism fundamentally reshaped the entire trajectory of global art and scientific discovery. Exploring the brilliant minds of that specific era is always a deeply inspiring academic pursuit."),
    ("How did you learn about history when you were a child?", "During my formative school years, my history teachers primarily relied on requiring us to memorize extensive lists of irrelevant dates and boring battles. Had they utilized compelling narrative storytelling to vividly describe the actual people involved, the classroom lessons would have been significantly more engaging and memorable for the restless students."),
    ("Do you think historical films are accurate?", "While historical cinematic productions can successfully generate initial public interest in a specific forgotten era, they are notoriously inaccurate regarding the actual factual details. Hollywood directors frequently manipulate or entirely invent dramatic romantic subplots simply to ensure the expensive movie achieves commercial success. Consequently, one must always view these entertaining films with intense academic skepticism."),
    ("What historical event do you wish you could have witnessed?", "I frequently wish I could have personally witnessed the incredible, tense atmosphere surrounding the first successful lunar landing. Observing humanity collectively achieve such an impossible, unprecedented technological milestone must have generated an overwhelming, global sense of unified optimism. It represents a genuinely triumphant, peaceful moment in our otherwise violent twentieth-century history."),
    ("Is your hometown famous for any historical events?", "My remarkably quiet hometown is actually nationally famous for being the precise location where a crucial, decisive historical treaty was finally signed. We have a modest, well-curated local museum dedicated entirely to explaining the complex political negotiations that miraculously ended the devastating regional conflict. The local residents remain incredibly proud of this peaceful legacy."),
    ("Do you prefer reading historical books or watching historical documentaries?", "I strongly prefer consuming comprehensive historical documentaries produced by reputable academic organizations. The clever integration of authentic archival footage and expert scholarly interviews provides a highly dynamic, easily digestible educational format. While a dense, academic book is excellent for specific research, a brilliant documentary brings the distant past vividly to life."),
    ("Why is it important to preserve old, historical buildings in a modern city?", "Preserving vulnerable historical architecture amidst rapid modern development is crucial for maintaining a city's tangible, unique civic identity. These elegant, centuries-old structures provide a beautiful, grounding visual contrast to the generic, sterile glass skyscrapers that currently dominate the metropolitan skyline. Erasing them completely would tragically destroy the city's complex, irreplaceable historical soul.")
]
for q, t in c2_t:
    wc = len(t.split())
    samples.append({
        "sample_id": f"syn_p1_v7_g8_{start_id:04d}", "video_id": "synthetic", "part": 1, "question": q,
        "transcript_cleaned": t, "word_count": wc, "response_type": "direct_answer" if wc <= 50 else "extended",
        "vocabulary": 7, "grammar": 8, "is_valid": True, "dataset_source": "synthetic", "idiom_present": False, "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": f"Part: 1\nQuestion: {q}\n\nTranscript: {t}\n\nWord Count: {wc} words\nResponse Type: {'direct_answer' if wc <= 50 else 'extended'}",
        "vocab_reason": "[LR7] Good range of less common vocabulary ('civic identity', 'secular humanism', 'dogmatism', 'visceral emotional connection'). Paraphrasing is effective.",
        "grammar_reason": "[GRA8] Wide range of structures used flexibly and accurately ('Were we to completely ignore', 'Had they utilized'). The majority of sentences are error-free.",
        "micro_flaws": ["none significant"],
        "grammar_profile": {"complexity": "very_high", "accuracy": "high", "flexibility": "very_high"},
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Good range of less common vocabulary used with flexibility and precision.\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Wide range of structures used flexibly and accurately. The majority of sentences are error-free."
    })
    start_id += 1

# V8 / G9 (Science and Technology)
c3_t = [
    ("How has the internet revolutionized academic research?", "The advent of the internet has unequivocally revolutionized academic research by democratizing instantaneous access to global scholarly databases. Previously, researchers were severely constrained by the limited physical inventory of their local university library. Now, provided one possesses a reliable connection, the entirety of human scientific endeavor is accessible within mere milliseconds, dramatically accelerating the pace of intellectual discovery."),
    ("Do you think artificial intelligence will pose a threat to creative professions?", "While highly sophisticated artificial intelligence can arguably mimic the structural mechanics of a poetic sonnet or a classical painting, I seriously doubt it possesses the capacity for genuine, spontaneous creativity. True artistic expression is fundamentally rooted in the chaotic, unpredictable depths of the authentic human emotional experience. An algorithmic interface, no matter how advanced, merely synthesizes pre-existing data without any actual emotional resonance."),
    ("What is the most significant scientific breakthrough of the last decade?", "I would emphatically argue that the rapid development and subsequent global deployment of the mRNA vaccine platform constitutes the most monumental scientific breakthrough of our current era. Had this highly adaptable, revolutionary biotechnology not been aggressively funded, our collective response to the devastating viral pandemic would have been catastrophically sluggish. It represents a miraculous triumph of modern molecular biology."),
    ("Do you enjoy keeping up with the latest technological gadgets?", "I am actually quite selective regarding the integration of new technological gadgets into my daily routine. Unless a novel device demonstrably resolves a specific, highly frustrating logistical problem I currently face, I usually dismiss it as an unnecessary, expensive distraction. The relentless, aggressive marketing cycle of constant hardware upgrades is something I actively attempt to avoid."),
    ("How do you think autonomous vehicles will change urban planning?", "The widespread integration of fully autonomous vehicles will undoubtedly necessitate a radical reimagining of our fundamental urban infrastructure. If computer-driven cars successfully eliminate the terrifying unpredictability of human error, cities could theoretically replace massive, unsightly concrete parking structures with expansive, vibrant public parks. This inevitable transition promises to miraculously reclaim the congested urban environment exclusively for the pedestrian."),
    ("Why is space exploration important for the future of humanity?", "Space exploration remains absolutely paramount because it forces us to systematically confront and overcome seemingly insurmountable technological limitations. The incredibly resilient materials and sophisticated life-support systems initially engineered for harsh orbital environments invariably trickle down to benefit mundane commercial manufacturing. Furthermore, securing a viable extraterrestrial sanctuary serves as an essential, pragmatic insurance policy against potential ecological collapse on Earth."),
    ("What are the ethical concerns regarding genetic engineering?", "The staggering potential of CRISPR genetic engineering introduces a myriad of profoundly disturbing ethical dilemmas regarding the fundamental nature of human equality. While eradicating horrific hereditary diseases is an undeniably noble pursuit, the terrifying prospect of affluent parents selectively designing intellectually enhanced offspring is deeply unsettling. Strict, internationally enforced regulatory frameworks are absolutely vital to prevent a dystopian, genetically stratified society."),
    ("How has digital communication affected your attention span?", "I must candidly admit that the relentless barrage of instantaneous digital communication has severely fragmented my natural cognitive attention span. The pervasive expectation of immediate replies to mundane text messages consistently derails my ability to maintain deep, sustained intellectual focus. Relearning how to engage in prolonged, uninterrupted contemplation without constantly checking a glowing screen has become an incredibly difficult personal challenge."),
    ("Do you think scientific literacy is important for the general public?", "A robust foundation in basic scientific literacy is an absolute prerequisite for any fully functioning, modern participatory democracy. When ordinary citizens lack the critical analytical skills required to evaluate complex empirical evidence, they become dangerously susceptible to manipulative, pseudoscientific political propaganda. Therefore, educational institutions must urgently prioritize teaching students how to rigorously question data rather than merely memorizing isolated facts."),
    ("What new technology do you hope to see developed in your lifetime?", "I harbor a profound, lingering hope for the successful, widespread commercialization of clean, limitless nuclear fusion energy during my lifetime. Should brilliant physicists finally manage to stabilize this remarkably elusive reaction, it would permanently eradicate our toxic reliance on environmentally devastating fossil fuels. This single, miraculous technological achievement would essentially solve the escalating global climate crisis entirely overnight.")
]
for q, t in c3_t:
    wc = len(t.split())
    samples.append({
        "sample_id": f"syn_p1_v8_g9_{start_id:04d}", "video_id": "synthetic", "part": 1, "question": q,
        "transcript_cleaned": t, "word_count": wc, "response_type": "direct_answer" if wc <= 50 else "extended",
        "vocabulary": 8, "grammar": 9, "is_valid": True, "dataset_source": "synthetic", "idiom_present": False, "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": f"Part: 1\nQuestion: {q}\n\nTranscript: {t}\n\nWord Count: {wc} words\nResponse Type: {'direct_answer' if wc <= 50 else 'extended'}",
        "vocab_reason": "[LR8] Wide range of sophisticated vocabulary ('democratizing', 'molecular biology', 'pseudoscientific political propaganda'). Meaning is precise.",
        "grammar_reason": "[GRA9] Flawless grammar with full flexibility. Uses advanced structures naturally and accurately ('Had this highly adaptable... not been aggressively funded', 'Should brilliant physicists finally manage').",
        "micro_flaws": ["none in grammar", "none in vocabulary"],
        "grammar_profile": {"complexity": "very_high", "accuracy": "near_perfect", "flexibility": "very_high"},
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Wide vocabulary range used readily and flexibly to convey precise meaning.\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 9\n\n**Reasoning:** [GRA9] Full mastery of complex structures. Flawless accuracy and natural flexibility."
    })
    start_id += 1

# V9 / G8 (Language and Communication)
c4_t = [
    ("How does bilingualism alter a person's cognitive framework?", "Attaining genuine bilingualism profoundly alters an individual's fundamental cognitive framework, essentially rewiring their neurological capacity for complex problem-solving. By seamlessly alternating between two entirely distinct syntactical structures, a bilingual speaker inherently develops remarkable intellectual agility and heightened executive function. It is not merely a method of diverse communication, but a comprehensive, rigorous workout for the incredibly malleable human brain."),
    ("What are the primary challenges of translating idiomatic expressions?", "Translating deeply culturally entrenched idiomatic expressions presents an extraordinarily formidable linguistic challenge because their actual meaning is rarely derived from the literal definitions of the constituent words. If a novice translator attempts a strict, verbatim conversion, the resulting phrase is typically incomprehensible and occasionally inadvertently offensive to the native speaker. Mastering the subtle, contextual nuances is absolutely crucial for accurate localization."),
    ("Why do some regional dialects gradually face extinction?", "Countless obscure regional dialects are tragically facing imminent extinction primarily due to the overwhelming, homogenizing pressure exerted by centralized national education systems. When young children are aggressively compelled to exclusively utilize the standardized, prestige dialect to secure future economic opportunities, the localized, ancestral tongue is rapidly abandoned. This utilitarian linguistic shift essentially eradicates centuries of unique, highly localized mythological wisdom."),
    ("How does body language contribute to effective communication?", "The subtle, frequently subconscious projection of dynamic body language undeniably constitutes the vast majority of our genuine interpersonal communication. Even if an individual's carefully chosen words project absolute, unshakeable confidence, a slight, nervous tremor in their hands will immediately betray their profound underlying anxiety. Therefore, mastering the incredibly complex art of deciphering non-verbal micro-expressions is vital for navigating difficult social situations."),
    ("In what ways has digital texting degraded formal writing skills?", "The ubiquitous, inescapable reliance on rapid digital texting has severely degraded the formal writing proficiency of the current younger generation. Because they are constantly accustomed to utilizing heavily abbreviated slang and completely omitting necessary punctuation, their capacity to construct a coherent, sophisticated academic argument is alarmingly deficient. This pervasive linguistic laziness threatens to permanently erode the elegant structural integrity of written discourse."),
    ("Do you think English will remain the dominant global lingua franca?", "While Mandarin is undeniably surging in profound economic significance, I firmly believe English will inevitably maintain its entrenched position as the undisputed global lingua franca for the foreseeable future. The sheer, overwhelming volume of international scientific research and crucial diplomatic negotiations conducted exclusively in English creates a self-perpetuating momentum. Its established ubiquity across the interconnected digital landscape is currently entirely unassailable."),
    ("How does the tone of voice alter the meaning of a sentence?", "The specific, calculated inflection of a speaker's vocal tone can completely invert the fundamental, literal meaning of a seemingly innocuous sentence. A brilliant deployment of sharp, biting sarcasm relies entirely on a deliberate, exaggerated tonal shift to communicate profound disdain, despite utilizing ostensibly polite vocabulary. Consequently, written transcripts frequently fail to capture the actual, complex emotional reality of a tense conversation."),
    ("Why is preserving linguistic diversity important for humanity?", "Meticulously preserving fragile linguistic diversity is of paramount, existential importance because every unique language intrinsically encapsulates a fundamentally different philosophical approach to perceiving the natural universe. When a language is irreversibly lost, we are not merely losing a random collection of grammatical rules; we are suffering the tragic, permanent destruction of an entire, irreplaceable cognitive ecosystem and unique human worldview."),
    ("What are the psychological benefits of learning a foreign language?", "The rigorous, systematic pursuit of mastering a completely foreign language yields incredibly profound, well-documented psychological benefits, particularly concerning long-term cognitive preservation. Immersing oneself in a bewildering new grammatical paradigm forces the aging brain to constantly forge robust new neural pathways, significantly delaying the terrifying onset of debilitating neurodegenerative diseases. It is a highly effective, intellectually stimulating prophylactic against cognitive decline."),
    ("How do colloquialisms reflect the unique culture of a specific region?", "Vibrant, highly localized colloquialisms essentially serve as a fascinating, incredibly accurate linguistic mirror, perfectly reflecting the unique historical struggles and defining geographic characteristics of a specific region. The colorful slang utilized by resilient coastal fishermen will naturally differ drastically from the terminology employed by isolated mountain communities. These fascinating linguistic idiosyncrasies provide an unparalleled, visceral insight into their distinct daily realities.")
]
for q, t in c4_t:
    wc = len(t.split())
    samples.append({
        "sample_id": f"syn_p1_v9_g8_{start_id:04d}", "video_id": "synthetic", "part": 1, "question": q,
        "transcript_cleaned": t, "word_count": wc, "response_type": "direct_answer" if wc <= 50 else "extended",
        "vocabulary": 9, "grammar": 8, "is_valid": True, "dataset_source": "synthetic", "idiom_present": False, "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": f"Part: 1\nQuestion: {q}\n\nTranscript: {t}\n\nWord Count: {wc} words\nResponse Type: {'direct_answer' if wc <= 50 else 'extended'}",
        "vocab_reason": "[LR9] Exceptional, highly precise, and sophisticated vocabulary ('syntactical structures', 'utilitarian linguistic shift', 'prophylactic against cognitive decline'). Idiomatic language is natural and accurate.",
        "grammar_reason": "[GRA8] Wide range of structures used flexibly and accurately. The majority of sentences are error-free.",
        "micro_flaws": ["none significant"],
        "grammar_profile": {"complexity": "very_high", "accuracy": "high", "flexibility": "very_high"},
        "output": "## Vocabulary (Lexical Resource): Band 9\n\n**Reasoning:** [LR9] Uses vocabulary with full flexibility and precision in all topics.\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 8\n\n**Reasoning:** [GRA8] Wide range of structures used flexibly and accurately. The majority of sentences are error-free."
    })
    start_id += 1

# V5 / G6 (Everyday Objects)
c5_t = [
    ("What is your most important personal possession?", "My most important thing is definitely my small laptop computer that I use every day. Because all my university homework and important family photos are saved inside it, I would feel completely lost if it suddenly broke. It helps me to study effectively and connect with my friends on the weekend."),
    ("Do you prefer buying new things or fixing old ones?", "I usually prefer trying to fix my old things before I spend money on something brand new. If my jacket has a small hole, my mother can easily sew it closed with some thread. It is much better for the environment and it saves a lot of my limited student money."),
    ("What kind of bags do you usually use?", "I typically use a strong, black backpack when I travel to the busy university. Because I need to carry many heavy science books and a bottle of water, a shoulder bag would make my back hurt terribly. The backpack is very comfortable and keeps my hands completely free while walking."),
    ("Do you wear a watch every day?", "Yes, I wear a simple digital watch on my wrist every single day. Even though my smart phone clearly shows the exact time, looking quickly at my watch is much more polite during a boring meeting. It stops me from getting distracted by angry text messages when I check the hour."),
    ("What items do you always carry in your pockets?", "I always carry my house keys, a small leather wallet, and some extra tissues in my deep pockets. Unless I double-check my pockets before I leave the dark apartment, I usually forget my important travel card for the train. These basic items are absolutely necessary for surviving in the big city."),
    ("Have you ever lost something very important?", "Unfortunately, I lost my brand-new expensive smartphone on the crowded public bus last summer. Because I was listening to loud music, I didn't notice it falling out of my coat pocket. I felt incredibly stupid and angry at myself because I had to buy another cheap phone immediately."),
    ("Do you collect any specific objects?", "When I was a younger teenager, I used to collect many colorful stamps from different foreign countries. I kept them perfectly organized in a big, heavy book on my wooden shelf. Although I don't collect them anymore, I still enjoy looking at the beautiful historical pictures occasionally when I feel bored."),
    ("What piece of furniture do you use the most?", "The furniture I use the most is my wide wooden desk located in my small bedroom. Since I have to study for my difficult exams almost every night, I sit there for many exhausting hours. Having a clean, organized desk really helps me to focus deeply on my complicated homework."),
    ("Do you think people buy too many unnecessary things?", "I strongly believe that people buy far too many useless plastic things because of the crazy internet advertisements. Whenever there is a big discount sale, shoppers buy items they will probably only use one single time. This terrible habit creates a massive amount of garbage that pollutes our green environment."),
    ("What is the oldest object you currently own?", "The oldest object I own is a beautiful silver necklace that my grandmother wore when she was young. Even though the shiny metal is slightly scratched now, it is incredibly valuable to me because of the family history. I only wear it safely around my neck during very special holiday celebrations.")
]
for q, t in c5_t:
    wc = len(t.split())
    samples.append({
        "sample_id": f"syn_p1_v5_g6_{start_id:04d}", "video_id": "synthetic", "part": 1, "question": q,
        "transcript_cleaned": t, "word_count": wc, "response_type": "direct_answer" if wc <= 50 else "extended",
        "vocabulary": 5, "grammar": 6, "is_valid": True, "dataset_source": "synthetic", "idiom_present": False, "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": f"Part: 1\nQuestion: {q}\n\nTranscript: {t}\n\nWord Count: {wc} words\nResponse Type: {'direct_answer' if wc <= 50 else 'extended'}",
        "vocab_reason": "[LR5] Vocabulary is adequate but relies on basic, everyday terms ('small laptop', 'brand new', 'heavy science books', 'garbage').",
        "grammar_reason": "[GRA6] Uses a mix of simple and complex sentence forms ('Even though my smart phone clearly shows...', 'Because all my university homework...'). Grammatical control is reasonably good, better than the vocabulary range.",
        "micro_flaws": ["vocabulary is noticeably simpler than the grammar structures used"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Vocabulary is adequate but relies on basic, everyday terms.\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Mix of simple and complex structures, with noticeable but non-impeding errors."
    })
    start_id += 1

with open(filename, 'w', encoding='utf-8') as f:
    for s in samples:
        f.write(json.dumps(s) + '\n')
print(f"Batch {batch_num} written natively.")
