import json

batch_num = 54
filename = f"ielts-data/phase3/v76_review_output/synthetic_batches/batch_p3_22.jsonl"
start_id = 1051
samples = []

# ALL QUESTIONS MUST BE UNIQUE AND MATCH THE TRANSCRIPT CONTENT.
# ALL TRANSCRIPTS MUST BE MANUALLY WRITTEN TO BE > 60 WORDS NATURALLY. NO SCRIPTS TO EXPAND LATER.

# V7 / G6
c1_t = [
    ("How does advertising influence consumer choices directly?", "I believe advertising it subtly manipulates our purchasing behavior by creating artificial desires. When we see a highly persuasive commercial for a new smartphone, it makes our current device seem completely inadequate. This psychological pressure they forces us to constantly upgrade our possessions to maintain social status. Had we not seen the marketing campaign, we probably feeling entirely satisfied with what we already own."),
    ("Why do celebrity endorsements remain effective in marketing today?", "A prominent method advertisers use is the strategic deployment of celebrity endorsements. If a famous athlete claims a specific sports drink improved their performance, their loyal fans they will instinctively buy it. Consumers subconsciously believing that purchasing the product will grant them a small piece of that celebrity's success. It is a highly effective tactic that completely bypassing rational financial evaluation for most young people."),
    ("How does targeted digital advertising shape personal shopping habits online?", "From my perspective, modern targeted digital advertising it is particularly insidious. Because social media platforms track our online browsing habits, they displaying highly personalized adverts for products we recently researched. This constant, inescapable exposure it significantly increasing the likelihood of an impulse purchase. Unless we use robust ad-blocking software, resisting these tailored temptations becoming an incredibly difficult daily struggle for many vulnerable consumers."),
    ("In what ways do cosmetic brands exploit personal insecurities?", "I'd argue that marketing campaigns frequently exploiting our deepest personal insecurities. Cosmetic brands often feature digitally altered, flawless models to establish an entirely unattainable standard of physical beauty. They then conveniently offering their expensive lotions as the magical solution to our perceived flaws. By making consumers feel inadequate, these corporations they guarantee a continuous demand for their lucrative products indefinitely without feeling any moral guilt."),
    ("How do lifestyle commercials persuade people to buy expensive cars?", "Another significant factor is the clever association of a product with a highly desirable lifestyle. A car commercial it rarely focusing solely on engine specifications; instead, it shows an attractive family driving along a sunlit coastal road. The underlying message they conveying is that buying this car will instantly grant you that idyllic life. This emotional branding is usually far more persuasive than practical features alone."),
    ("How has advertising normalized the purchase of expensive bottled water?", "I think advertising it heavily dictates what society considers normal or essential. Decades ago, purchasing expensive bottled water it was viewed as a ridiculous luxury. However, relentless marketing campaigns have successfully convincing the public that tap water is inferior or dangerous. Now, buying bottled water is a standard daily necessity for millions. It demonstrates the profound power of sustained advertising over long periods of time."),
    ("Why do many consumers underestimate the subconscious effect of billboards?", "While many people claim they are totally immune to marketing, I strongly believing it affects everyone subconsciously. Even if you consciously ignoring a billboard on your morning commute, your brain still briefly registering the bright logo. When you are standing in the supermarket staring at fifty different toothpastes, you will instinctively choosing the brand your brain subtly remembers from that billboard without realizing it."),
    ("How does the aggressive repetition of radio jingles affect brand memory?", "The sheer, aggressive repetition of advertisements it is a highly calculated psychological tactic. Hearing the same annoying radio jingle twenty times a day it might be incredibly frustrating, but it guarantees the brand name is deeply embedded in your memory. When a consumer eventually needing that specific service, that heavily advertised brand will be the first one they recalling automatically without even thinking about it."),
    ("What role does marketing play in accelerating the fast fashion cycle?", "Advertising also significantly accelerating the incredibly wasteful cycle of fast fashion. Clothing brands constantly bombarding us with images of the latest seasonal trends, making last month's wardrobe feel instantly obsolete. This intense pressure to remain fashionable it encouraging people to buy cheap, poor-quality garments that they throwing away after two weeks. The environmental impact of this driven consumption is absolutely devastating for our entire planet."),
    ("How do limited-time discounts impact our rational budgeting processes?", "Ultimately, the primary overarching goal of advertising it is to completely bypass our rational budgeting processes. By offering limited-time discounts or creating a false sense of urgency, retailers deliberately inducing a state of mild panic in the consumer. They want you to making an immediate, emotional purchase before you having the necessary time to carefully consider if you genuinely need the expensive item at all.")
]
for q, t in c1_t:
    wc = len(t.split())
    samples.append({
        "sample_id": f"syn_p3_v7_g6_{start_id:04d}", "video_id": "synthetic", "part": 3, "question": q,
        "transcript_cleaned": t, "word_count": wc, "response_type": "extended" if wc > 80 else "direct_answer",
        "vocabulary": 7, "grammar": 6, "is_valid": True, "dataset_source": "synthetic", "idiom_present": False, "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": f"Part: 3\nQuestion: {q}\n\nTranscript: {t}\n\nWord Count: {wc} words\nResponse Type: {'extended' if wc > 80 else 'direct_answer'}",
        "vocab_reason": "[LR7] Good range of less common vocabulary ('artificial desires', 'celebrity endorsements', 'insidious', 'obsolete'). Paraphrasing is effective and meaning is always clear.",
        "grammar_reason": "[GRA6] Uses a mix of simple and complex sentence forms. However, there are frequent errors in basic structures ('advertising it subtly', 'they offering', 'consumers subconsciously believing') which restrict the score to 6.",
        "micro_flaws": ["double subject: 'advertising it'", "verb form error: 'subconsciously believing'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "output": "## Vocabulary (Lexical Resource): Band 7\n\n**Reasoning:** [LR7] Good range of less common vocabulary used with some flexibility and style awareness.\n\n>Band 6: More precise and stylistically aware than a 6.\n\nNot Band 8: Lacks the sustained idiomatic naturalness of an 8.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Mix of simple and complex structures, but with frequent, noticeable errors that do not impede meaning.\n\n>Band 5: Better range of complex structures than a 5.\n\nNot Band 7: Error rate is too high for a 7.\n\n**Micro flaws identified:**\n- frequent errors in verb forms and double subjects"
    })
    start_id += 1

# V8 / G7
c2_t = [
    ("How is climate volatility disrupting traditional agricultural yields globally?", "The escalating volatility of global weather patterns is profoundly disrupting traditional agricultural yields. Prolonged, devastating droughts in formerly fertile regions is causing catastrophic crop failures, significantly threatening the precarious food security of developing nations. Furthermore, the unpredictable shifting of distinct seasonal cycles confuses the natural planting rhythms that farmers have relied upon for generations. This meteorological unpredictability forces the agricultural sector to urgently adopt highly resilient, drought-resistant crop varieties to mitigate impending catastrophic famine."),
    ("Why does rising temperature lead to the proliferation of agricultural pests?", "A particularly insidious consequence of rising global temperatures is the rapid proliferation of invasive agricultural pests. As winters become increasingly mild, destructive insects that were previously killed by severe frost are now surviving and migrating to entirely new geographical territories. These highly adaptable pests decimate vulnerable local crops that possess no natural evolutionary resistance against them. Consequently, farmers is compelled to utilize exorbitant quantities of toxic chemical pesticides, which severely degrades the surrounding ecological balance."),
    ("How does saltwater intrusion from rising seas affect coastal farming?", "We must critically examine the devastating impact of rising sea levels on crucial coastal agricultural zones. As the oceans inevitably encroach upon low-lying arable land, the subsequent saltwater intrusion profoundly contaminates the delicate freshwater aquifers essential for intensive irrigation. This terrifying phenomenon of soil salinization effectively renders vast tracts of formerly highly productive farmland completely barren and unusable. This forces marginalized coastal farming communities to abandon their ancestral land and desperately relocate further inland immediately."),
    ("What is the paradoxical relationship between livestock farming and climate change?", "The agricultural sector is trapped in a deeply paradoxical relationship with global climate change. While it suffers immensely from extreme weather events, intensive commercial agriculture—particularly massive livestock farming—remains one of the primary drivers of greenhouse gas emissions. The staggering volume of methane produced by billions of cattle significantly accelerates the exact atmospheric warming that is destroying their vital grazing pastures. Breaking this destructive, cyclical feedback loop requires a fundamental, global transition towards sustainable, plant-based diets."),
    ("How might global warming shift the geographical centers of food production?", "I believe that climate change will inevitably necessitate a radical geographical shift in global food production. Regions located closer to the equator are becoming excessively arid and hostile to traditional farming. Conversely, northern latitudes in countries like Canada or Russia are slowly experiencing longer, warmer growing seasons, potentially opening up vast new frontiers for lucrative agricultural exploitation. However, this massive geographical transition will undoubtedly cause severe geopolitical friction as nations fiercely competes for these newly fertile territories."),
    ("What are the specific economic ramifications of climate change for subsistence farmers?", "The economic ramifications for small-scale, subsistence farmers are frankly terrifying. Unlike massive multinational agribusinesses, these impoverished rural workers lack the necessary financial capital to invest in highly sophisticated, climate-resilient irrigation infrastructure. When a sudden, unprecedented flash flood inevitably washes away their entire annual harvest, they are immediately plunged into insurmountable debt and desperate poverty. Therefore, the international community must provide substantial financial subsidies to protect these incredibly vulnerable agricultural demographics from total economic ruin."),
    ("How does elevated atmospheric carbon dioxide alter crop nutritional profiles?", "Climate change is also significantly altering the fundamental nutritional composition of our staple food crops. Recent rigorous scientific studies indicates that elevated levels of atmospheric carbon dioxide actually reduce the essential protein and vital mineral content in crucial crops like wheat and rice. This subtle, invisible degradation of global food quality poses a massive, silent threat to public health, potentially exacerbating severe malnutrition in populations that rely almost exclusively on these specific dietary staples for survival."),
    ("How do extreme weather events disrupt the international agricultural supply chain?", "The increased frequency of extreme, catastrophic weather events severely disrupts the complex global agricultural supply chain. A massive hurricane striking a major agricultural export hub can instantly destroy vital transportation infrastructure, such as crucial shipping ports and massive grain silos. This logistical paralysis immediately halts the international distribution of food, causing sudden, terrifying spikes in global food prices and triggering severe political instability in nations heavily reliant on cheap agricultural imports to feed their populations."),
    ("In what ways are agritech companies innovating to mitigate climate impacts?", "I'd argue that the pressing necessity to adapt to climate change is finally driving profound technological innovation within the farming sector. Visionary agritech companies are developing highly sophisticated, AI-driven precision farming techniques that drastically minimize water consumption and optimize fertilizer application. Furthermore, the rapid development of controlled-environment indoor vertical farms offers a remarkably promising, climate-proof alternative to traditional open-field agriculture, guaranteeing consistent crop yields regardless of the volatile external meteorological conditions."),
    ("Why is international collaboration essential for future global food security?", "Ultimately, securing the future of global agriculture in the face of escalating climate change demands an unprecedented level of international collaborative effort. Wealthy developed nations, who are historically responsible for the vast majority of carbon emissions, bear a profound moral obligation to freely share advanced, sustainable agricultural technologies with struggling developing countries. If we selfishly hoard this crucial knowledge, the resulting global famine and massive climate-induced migration will inevitably destabilize the entire geopolitical order.")
]
for q, t in c2_t:
    wc = len(t.split())
    samples.append({
        "sample_id": f"syn_p3_v8_g7_{start_id:04d}", "video_id": "synthetic", "part": 3, "question": q,
        "transcript_cleaned": t, "word_count": wc, "response_type": "extended" if wc > 80 else "direct_answer",
        "vocabulary": 8, "grammar": 7, "is_valid": True, "dataset_source": "synthetic", "idiom_present": False, "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": f"Part: 3\nQuestion: {q}\n\nTranscript: {t}\n\nWord Count: {wc} words\nResponse Type: {'extended' if wc > 80 else 'direct_answer'}",
        "vocab_reason": "[LR8] Uses a wide vocabulary resource readily and flexibly ('escalating volatility', 'insidious consequence', 'geopolitical friction'). Precise meaning and excellent stylistic awareness.",
        "grammar_reason": "[GRA7] Frequently produces error-free sentences. However, occasional minor slips in subject-verb agreement ('droughts... is', 'farmers is compelled', 'studies indicates') cap the score at 7.",
        "micro_flaws": ["agreement slip: 'droughts... is'", "agreement slip: 'farmers is'"],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "output": "## Vocabulary (Lexical Resource): Band 8\n\n**Reasoning:** [LR8] Wide vocabulary range used readily and flexibly to convey precise meaning.\n\n>Band 7: More sophisticated and idiomatic than a 7.\n\nNot Band 9: Lacks the absolute native-like perfection of a 9.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Frequently produces error-free sentences and uses a range of complex structures, but occasional slips cap the score.\n\n>Band 6: Better accuracy and wider range of complex structures than a 6.\n\nNot Band 8: Slips in agreement are a bit too noticeable for an 8.\n\n**Micro flaws identified:**\n- minor agreement inconsistencies"
    })
    start_id += 1

# V4 / G6
c3_t = [
    ("Why is learning to swim considered a vital life-saving skill?", "I think swimming is very important for all people. If you fall into the deep water from a boat, you must know how to swim to save your life. Many people die every year because they cannot swim. Although learning to swim is very scary at first, it is a completely necessary skill for safety. I think every school should teach the children how to swim in the pool before they become teenagers."),
    ("How does swimming serve as an effective full-body exercise?", "Swimming is a very good exercise for the whole body. When you swim, you use your arms and legs at the same time. This makes you very strong and healthy. Because the water supports your heavy body, it is very good for old people who have bad knees. If they swim every day, they will feel much better and have less pain in their tired bodies when they walk around the park."),
    ("In what ways does knowing how to swim enhance summer holidays?", "I believe knowing how to swim makes summer holidays much more fun. When you go to the beautiful beach with your friends, you can jump in the cold water and play games. If you cannot swim, you must sit on the hot sand alone. Since I love playing in the sea, I am very happy that my father taught me how to swim when I was young, so I never feel afraid."),
    ("How can swimming lessons help people overcome a fear of water?", "Some people they are very afraid of the dark water. They panic and forget how to breathe when they go in the pool. But if they take slow lessons with a good teacher, they can overcome this big fear. It is very important to feel confident in the water. Once you learn, you never forget how to do it, just like riding a simple bicycle around your neighborhood on the weekend."),
    ("Why is floating an important confidence-building milestone for children?", "Learning to swim is very important for children's confidence. When a small child learns to float on their back, they feel very proud of their new skill. This positive feeling helps them to try other difficult things in their life. Even if they don't want to be a fast Olympic swimmer, the basic lessons are incredibly valuable for their personal growth as they learn to be brave."),
    ("What makes swimming an accessible and affordable hobby for families?", "I think swimming is a very cheap hobby. You only need to buy a cheap swimsuit and pay a small ticket for the public pool. You don't need to buy expensive shoes or a heavy ball like in other sports. Because it is so cheap, anyone from a poor family can learn to do it easily. It is a very accessible sport for everyone, no matter how much money they have."),
    ("How does basic swimming proficiency open doors to other water sports?", "If you want to do fun water sports, you absolutely must know how to swim first. You cannot go surfing or ride a fast jet ski if you are afraid of falling in the water. Therefore, swimming is like the first door you must open to enjoy many other exciting activities. Without this basic skill, you miss a lot of great adventures when you go to the big ocean."),
    ("Why do many busy workers find swimming to be mentally relaxing?", "Swimming is very relaxing for the stressed mind. When you are underwater, it is very quiet and peaceful. You cannot hear the noisy traffic or the loud people talking. It helps you forget about the difficult homework or the bad boss at the office. Many busy workers go to the pool after work just to find some quiet time for themselves before they go home to sleep."),
    ("How could more public pools prevent accidents in natural water bodies?", "In my country, there are many big rivers and deep lakes. Because there is water everywhere, it is very dangerous if you don't know how to swim. Parents are always very worried when their children play near the river. If the government builds more safe swimming pools, fewer children will have terrible accidents in the dangerous wild water during the hot summer when they play outside."),
    ("In what ways can a local swimming club serve as a social activity?", "Finally, swimming can be a very good social activity. You can join a local swimming club and meet many friendly people who like the same sport. Even though you cannot talk while you are swimming under the water, you can talk and laugh in the rest area. It is a great way to make healthy new friends in your big city when you have free time on the weekend.")
]
for q, t in c3_t:
    wc = len(t.split())
    samples.append({
        "sample_id": f"syn_p3_v4_g6_{start_id:04d}", "video_id": "synthetic", "part": 3, "question": q,
        "transcript_cleaned": t, "word_count": wc, "response_type": "extended" if wc > 80 else "direct_answer",
        "vocabulary": 4, "grammar": 6, "is_valid": True, "dataset_source": "synthetic", "idiom_present": False, "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": f"Part: 3\nQuestion: {q}\n\nTranscript: {t}\n\nWord Count: {wc} words\nResponse Type: {'extended' if wc > 80 else 'direct_answer'}",
        "vocab_reason": "[LR4] Uses basic vocabulary ('good', 'bad', 'big', 'small', 'happy', 'things') repeatedly. Cannot paraphrase effectively. Extremely limited range.",
        "grammar_reason": "[GRA6] Produces a mix of simple and complex sentence forms ('Although learning to swim...', 'If you fall...'). Minor errors but meaning is clear.",
        "micro_flaws": ["vague phrasing: 'dark water', 'bad knees'"],
        "grammar_profile": {"complexity": "moderate", "accuracy": "controlled", "flexibility": "moderate"},
        "output": "## Vocabulary (Lexical Resource): Band 4\n\n**Reasoning:** [LR4] Uses basic vocabulary exclusively. Cannot paraphrase effectively.\n\n>Band 3: Better control of simple words than a 3.\n\nNot Band 5: Fails to attempt less common vocabulary.\n\n**Idiom present:** No\n**Risk level:** Medium\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 6\n\n**Reasoning:** [GRA6] Mix of simple and complex structures, with noticeable but non-impeding errors.\n\n>Band 5: Better range of complex structures than a 5.\n\nNot Band 7: Error rate is too high for a 7."
    })
    start_id += 1

# V6 / G4
c4_t = [
    ("How have smartphones revolutionized our daily music listening habits?", "Technology changing music listening very much today. We using our small smart phones to playing thousands of different songs instantly. But the old people they not knowing how to use the complicated Spotify app. So they listening to the boring radio. It creating a big problem for the older generation who wanting to enjoy their favorite classical music easily while sitting comfortably inside their quiet homes."),
    ("What are the practical drawbacks of relying entirely on wireless headphones?", "The digital headphones they is very small and loud. You just putting them in the ear and ignoring the noisy world outside. However, if the battery it dying suddenly, the listener they feeling very annoyed. They completely relying on the small battery to survive the long, boring bus journey to the busy office every single morning during the cold winter months when the traffic is terrible."),
    ("How does the infinite choice on streaming apps cause listener confusion?", "Many popular streaming apps it giving us too many choices. When you opening the app, it showing millions of new songs. But sometimes the user they feeling very confused and cannot deciding what to listen to. So they just playing the same old song again and again. Too much choice it is a very bad thing for the simple brain when we trying to relax after work."),
    ("Why has the physical CD album lost its popularity in recent years?", "People they not buying physical CD albums anymore. They paying a small monthly fee to streaming all the music in the world. Because the plastic CD it becoming old and useless very fast. But the internet connection it sometimes failing during bad weather. Then the music stopping completely and you sitting in the quiet room feeling very frustrated and angry. The digital format it simply not providing a completely reliable listening experience."),
    ("What social conflicts can arise from using powerful wireless home speakers?", "The new wireless speakers they playing music incredibly loud in the house. This advanced technology it saving a lot of space in the small living room. But playing the heavy bass music it annoying the angry neighbors next door. The loud sound it causing a very terrible argument between the people living in the same apartment building. Eventually, the local police they arriving to stop the disturbing noise late at night."),
    ("How might artificial intelligence eventually change music discovery algorithms?", "Artificial intelligence it will completely changing how we find new music. The smart computer it analyzing your favorite songs and suggesting perfect new bands for you. However, many music fans they not trusting the invisible machine algorithm. They fearing that the computer it will making them listen to bad commercial pop music instead of authentic underground rock. They preferring the personal recommendations from their close human friends."),
    ("In what ways has digital downloading impacted traditional local record shops?", "The digital music files they destroying the traditional record shop business completely. Because the phone download it is much cheaper and faster, everyone choosing to use it. The poor shop owners they losing their important jobs and closing their doors forever. The government they struggling to help these small local businesses survive this rapidly changing situation. It creating a massive economic crisis for the independent music retail sector."),
    ("How do smartwatches make exercising to music more convenient for runners?", "Smart watches it allowing runners to listen to music without carrying a heavy phone. You just tapping your wrist and the fast running song starting immediately. It is a very easy and light way to exercising in the public park. But it never replacing the actual feeling of reading the beautiful paper booklet inside a real vinyl record cover. The physical connection to the album art it completely disappearing."),
    ("How have digital screens transformed the live concert experience recently?", "Modern concerts they using advanced digital screens and lasers to entertain the massive crowd. You just looking at the bright stage and dancing to the perfect electronic sound. This modern technology it making the live show very spectacular. But many purists they arguing that the musicians using too much computer help instead of playing real physical instruments. The live performance it losing its raw, authentic musical soul."),
    ("Why are independent artists increasingly using the internet to share music?", "Because of the strong internet, independent artists they can uploading their new songs directly to the whole world. This new digital freedom it becoming very popular with young, smart musicians. They finding global fans constantly without needing a greedy record label. But they frequently feeling very stressed because they must promoting their own music constantly on the exhausting social media networks instead of writing new songs.")
]
for q, t in c4_t:
    wc = len(t.split())
    samples.append({
        "sample_id": f"syn_p3_v6_g4_{start_id:04d}", "video_id": "synthetic", "part": 3, "question": q,
        "transcript_cleaned": t, "word_count": wc, "response_type": "extended" if wc > 80 else "direct_answer",
        "vocabulary": 6, "grammar": 4, "is_valid": True, "dataset_source": "synthetic", "idiom_present": False, "risk_level": "medium",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": f"Part: 3\nQuestion: {q}\n\nTranscript: {t}\n\nWord Count: {wc} words\nResponse Type: {'extended' if wc > 80 else 'direct_answer'}",
        "vocab_reason": "[LR6] Adequate range of vocabulary ('complicated Spotify app', 'invisible machine algorithm', 'spectacular'). Meaning is clear.",
        "grammar_reason": "[GRA4] Frequent and systematic errors in basic structures, missing 'be' verbs ('Technology changing', 'We using', 'it creating') and double subjects.",
        "micro_flaws": ["systematic missing auxiliary: 'We using'", "double subjects: 'people they'"],
        "grammar_profile": {"complexity": "basic", "accuracy": "variable", "flexibility": "limited"},
        "output": "## Vocabulary (Lexical Resource): Band 6\n\n**Reasoning:** [LR6] Uses an adequate range of vocabulary with some less common items successfully.\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 4\n\n**Reasoning:** [GRA4] Frequent and systematic errors in basic structures. Only basic sentence forms are recognizable."
    })
    start_id += 1

# V5 / G7
c5_t = [
    ("Why is protecting wild tigers crucial for forest ecosystems?", "I believe protecting wild animals is very important for the natural world. When people hunt tigers or elephants, the balance of the whole forest is completely broken. Even though building new farms is necessary for human food, we must leave some safe space for the animals. If we kill all the wild creatures, the earth will become a very lonely and boring place for everyone living here."),
    ("How do birds and insects indirectly protect human agricultural crops?", "Wild animals are very useful because they help to keep the environment clean and healthy. Unless birds and insects eat the bad bugs, the farmers' green crops will be completely destroyed. By protecting these small animals, we are actually helping to produce more food for ourselves. Furthermore, it gives us a strong feeling that we are doing the right thing for nature when we save them."),
    ("In what ways does wildlife tourism support the local economy in developing nations?", "Many local countries rely on wild animals to make money from international tourism. When the big safari parks are full of lions and monkeys, thousands of tourists visit to take exciting photos. If the government stopped protecting these animals, the local hotels and guides would lose their jobs quickly. Therefore, keeping the animals alive is a very smart economic decision for poor areas around the world."),
    ("How do national parks help city dwellers reconnect with the natural world?", "I think wild animals are a great way for busy city people to learn about nature. Because everyone is watching TV and playing on phones, they forget about the real world. Had I not visited the big national park last year, I would never have seen a real bear. It is a necessary reminder that humans share this planet with many other living things in the forest."),
    ("Why should the government subsidize farmers affected by dangerous predators?", "Some people argue that protecting dangerous animals is too expensive and risky. While it is true that a hungry lion can hurt local farm cows, the natural beauty they bring is totally worth the trouble. The government should definitely provide some money to help the farmers build stronger fences to keep their cows safe, instead of just killing the wild lions when they are hungry for food."),
    ("What role do large predatory fish play in maintaining ocean cleanliness?", "Preserving wild animals helps to keep the oceans and rivers perfectly clean. During the long summer, the big fish eat the smaller dead fish, which stops the water from getting dirty. If the big sharks disappear because of heavy fishing, the ocean will probably become very sick and polluted. So, the wild animals act like a living cleaning system for the deep water and the environment."),
    ("How do wildlife documentaries teach children valuable lessons about empathy?", "These beautiful animals are very important for teaching children to be kind. Usually, when a young boy sees a tiny baby monkey on television, he feels very happy and wants to protect it. Not only do they learn about science, but they also learn to care for things weaker than themselves. It is a vital lesson for raising good, gentle citizens for the future of our planet."),
    ("Why are monkeys and other noisy animals important for the jungle atmosphere?", "I strongly feel that without wild animals, all forests would look exactly the same and empty. Because of the big cities cutting down trees, the green areas are already becoming very small and quiet. The noisy, crazy monkeys are the only things that make the jungle truly alive and special. We must protect them carefully so the world remains a magical place for our future children."),
    ("Why should we respect dangerous reptiles rather than automatically destroying them?", "Although some wild animals seem strange or scary today, we must protect all of them equally. If an ugly snake is dangerous, we can easily stay away from it but let it live in peace. By respecting every animal slowly, we ensure that the complex web of life remains strong and unbroken for the next generation of humans living on earth today and tomorrow."),
    ("How does wildlife conservation reflect our maturity as a civilized modern species?", "Ultimately, an animal is a beautiful living thing that deserves to exist. In the past, humans hunted these animals just for fun or to make expensive coats. Even if we don't need their fur anymore, protecting them from illegal hunters is still very important for our human morality. It shows that we are finally becoming a responsible and highly civilized modern species that cares about nature.")
]
for q, t in c5_t:
    wc = len(t.split())
    samples.append({
        "sample_id": f"syn_p3_v5_g7_{start_id:04d}", "video_id": "synthetic", "part": 3, "question": q,
        "transcript_cleaned": t, "word_count": wc, "response_type": "extended" if wc > 80 else "direct_answer",
        "vocabulary": 5, "grammar": 7, "is_valid": True, "dataset_source": "synthetic", "idiom_present": False, "risk_level": "low",
        "instruction": "Score this IELTS Speaking response for Vocabulary (Lexical Resource) and Grammar (Grammatical Range and Accuracy) based on IELTS band descriptors (4-9). Provide band scores with detailed reasoning.",
        "input": f"Part: 3\nQuestion: {q}\n\nTranscript: {t}\n\nWord Count: {wc} words\nResponse Type: {'extended' if wc > 80 else 'direct_answer'}",
        "vocab_reason": "[LR5] Vocabulary is adequate but relies heavily on simple, everyday terms ('wild animals', 'lonely place', 'bad bugs'). Lacks precision and less common vocabulary.",
        "grammar_reason": "[GRA7] Produces frequent error-free complex sentences. Shows good flexibility with high accuracy despite simple vocabulary.",
        "micro_flaws": ["basic vocabulary: 'wild animals', 'bad bugs'"],
        "grammar_profile": {"complexity": "high", "accuracy": "high", "flexibility": "high"},
        "output": "## Vocabulary (Lexical Resource): Band 5\n\n**Reasoning:** [LR5] Vocabulary is adequate but relies on basic terms.\n\n---\n\n## Grammar (Grammatical Range & Accuracy): Band 7\n\n**Reasoning:** [GRA7] Produces frequent error-free complex sentences. Shows good flexibility with high accuracy."
    })
    start_id += 1

with open(filename, 'w', encoding='utf-8') as f:
    for s in samples:
        f.write(json.dumps(s) + '\n')
print(f"Batch {batch_num} completely rebuilt without scripts.")
